import type { Item } from "@/engine/types";
import { ADA_DX, ASHP_HD, CEFTRIAXONE, DISINFECTION, GLUCOSE_METER, HEPB, HINKLE, HYPERCALCEMIA, OSHA_BBP, OSHA_PICTO, TLS, meta } from "./common";

export const PART2: Item[] = [
  {
    ...meta("rn-s26-11", {
      need: "SIPC",
      topic: "Hepatitis B protection in a vaccine responder",
      cjmm: "analyze",
      process: "clinical-judgment",
      difficulty: 3,
      stem: "A nurse finished a 3-dose hepatitis B vaccine series 6 years ago. A test 2 months after the last dose showed an anti-HBs level of 85 mIU/mL. Today the nurse has a needlestick from a client who is positive for hepatitis B surface antigen. After first aid, which hepatitis B measure does the nurse need?",
      rationale:
        "The anti-HBs level of 85 mIU/mL after the series is above 10 mIU/mL. The nurse is a proven vaccine responder. Responders stay protected even when the antibody level later falls. No hepatitis B prophylaxis is needed, whatever the source status. Immune globulin with a vaccine dose is for workers without proven immunity. Follow-up for HIV and hepatitis C still proceeds.",
      refs: ["An anti-HBs level of 10 mIU/mL or more after a complete vaccine series marks a vaccine responder."],
      sources: [HEPB],
    }),
    kind: "mc",
    options: [
      { text: "Hepatitis B immune globulin and a vaccine dose", why: "This pairing is for exposed workers who are unvaccinated or have no proven response." },
      { text: "A single booster dose of hepatitis B vaccine", why: "A responder keeps immune memory. A booster adds nothing after this exposure." },
      { text: "No hepatitis B prophylaxis after this exposure", why: "A documented level above 10 mIU/mL after the series means the nurse is protected." },
      { text: "A repeat 3-dose hepatitis B vaccine series", why: "Revaccination is for workers whose level stayed below 10 mIU/mL after the series." },
    ],
    correct: 2,
  },
  {
    ...meta("rn-s26-12", {
      need: "RRP",
      topic: "First treatment for high calcium in bone metastases",
      cjmm: "action",
      process: "nursing-process",
      difficulty: 3,
      stem: "A client with breast cancer that has spread to bone reports thirst, constipation and new confusion. Urine output has been high for 2 days. Serum calcium is 13.4 mg/dL (3.34 mmol/L) and serum albumin is 3.9 g/dL (39 g/L). The calcium reference range is 8.5 mg/dL (2.12 mmol/L) to 10.5 mg/dL (2.62 mmol/L). Which prescription should the nurse carry out first?",
      rationale:
        "A calcium of 13.4 mg/dL with a normal albumin of 3.9 g/dL is true hypercalcemia. High calcium stops the kidneys from concentrating urine, so the client loses water. Thirst and high urine output show this loss. IV 0.9% sodium chloride restores volume and helps the kidneys clear calcium. Drugs that slow bone breakdown follow. A diuretic before fluid, fluid limits and bed rest all make the problem worse.",
      sources: [HYPERCALCEMIA, HINKLE],
    }),
    kind: "mc",
    options: [
      { text: "Give IV furosemide 20 mg", why: "A loop diuretic given before volume is restored deepens the fluid deficit." },
      { text: "Infuse IV 0.9% sodium chloride", why: "Saline replaces the water lost to high urine output and increases calcium excretion." },
      { text: "Limit oral fluids to 1 L/day", why: "Fluid limits worsen the dehydration that high calcium has already caused." },
      { text: "Keep the client on strict bed rest", why: "Immobility speeds calcium release from bone and raises the level further." },
    ],
    correct: 1,
  },
  {
    ...meta("rn-s26-13", {
      need: "SIPC",
      topic: "Employer duties under the bloodborne standard",
      cjmm: "recognize",
      process: "nursing-process",
      difficulty: 2,
      stem: "A nurse starts work on a hospital unit where contact with blood is expected. Under the federal bloodborne pathogens standard, what must the employer provide? Select all that apply.",
      rationale:
        "The federal standard puts the cost and the controls on the employer. The employer offers hepatitis B vaccine and provides protective equipment at no cost to the worker. Training happens at hire and at least yearly. The worker may decline the vaccine by signing a declination. Two-handed recapping is prohibited. The exposure plan is reviewed at least yearly. Exposure follow-up is free to the worker.",
      sources: [OSHA_BBP, { body: "Canadian Centre for Occupational Health and Safety", work: "Health and Safety Legislation in Canada: Introduction", year: 2022, url: "https://www.ccohs.ca/oshanswers/legisl/intro.html" }],
      canada: "In Canada, hospital employer duties come from provincial or territorial occupational health and safety acts, not a federal standard. Rules on vaccine, equipment and training vary by province.",
    }),
    kind: "sata",
    options: [
      { text: "Rules requiring vaccine acceptance", why: "The worker may decline hepatitis B vaccine by signing a declination statement." },
      { text: "Hepatitis B vaccine at no cost", why: "The employer offers the vaccine series free to workers with exposure risk." },
      { text: "Protective equipment at no cost", why: "Gloves, gowns, masks and eye protection are supplied free by the employer." },
      { text: "Two-handed needle recapping", why: "Recapping is banned unless no alternative exists, and then only one-handed or with a device." },
      { text: "Exposure plan review every 5 years", why: "The exposure control plan is reviewed and updated at least once a year." },
      { text: "Bloodborne pathogen training yearly", why: "Training is given at hire and at least once a year after that." },
      { text: "Exposure follow-up at worker cost", why: "Evaluation and follow-up after an exposure are provided free to the worker." },
    ],
    correct: [1, 2, 5],
  },
  {
    ...meta("rn-s26-14", {
      need: "SIPC",
      topic: "Infection control with a shared glucose meter",
      cjmm: "action",
      process: "nursing-process",
      difficulty: 2,
      stem: "The nurse checks capillary blood glucose for four residents in a long-term care home. The unit has one glucose meter that the residents share. Which actions should the nurse take? Select all that apply.",
      rationale:
        "Shared glucose equipment has spread hepatitis B between residents. Each fingerstick uses a single-use lancet that disables itself. A shared meter is cleaned and disinfected after every use, as the maker directs. Gloves change between residents. A reusable lancing pen is for one person only. An insulin pen is never shared, even with a new needle, because blood can back up into the cartridge.",
      sources: [GLUCOSE_METER],
    }),
    kind: "sata",
    options: [
      { text: "Use a single-use auto-disabling lancet", why: "A lancet that disables itself after one use cannot carry blood to another resident." },
      { text: "Reuse one lancing pen with new lancets", why: "A reusable lancing pen can carry blood on its cap. It is for one person only." },
      { text: "Clean and disinfect the meter after each use", why: "Blood on a shared meter can reach the next resident unless it is disinfected every time." },
      { text: "Wipe the meter once at the end of the round", why: "One wipe at the end leaves blood on the meter between residents." },
      { text: "Change gloves between residents", why: "Gloves that touched one resident's blood can carry it to the next." },
      { text: "Share one insulin pen with a new needle", why: "Blood can flow back into the pen cartridge, so a pen stays with one person." },
    ],
    correct: [0, 2, 4],
  },
  {
    ...meta("rn-s26-15", {
      need: "RRP",
      topic: "Electrolyte pattern after the first chemotherapy dose",
      cjmm: "prioritize",
      process: "clinical-judgment",
      difficulty: 4,
      stem: "A 24-year-old client with acute lymphoblastic leukemia had the first dose of chemotherapy 30 hours ago. The client reports muscle cramps and tingling around the mouth. Urine output has been 20 mL per hour for 3 hours. Temperature is 37.0°C (98.6°F) and BP is 132/78 mmHg. Current prescriptions include IV fluids and allopurinol. Results: potassium 6.2 mEq/L (6.2 mmol/L), phosphorus 7.1 mg/dL (2.29 mmol/L), calcium 7.3 mg/dL (1.82 mmol/L), uric acid 11.4 mg/dL (678 micromol/L), creatinine 2.1 mg/dL (186 micromol/L). Complete the diagram by choosing the condition the client is most likely experiencing, 2 actions to take and 2 parameters to monitor.",
      rationale:
        "Chemotherapy has broken down many leukemia cells at once. The cells release potassium, phosphorus and uric acid into the blood. Phosphorus binds calcium, so calcium falls to 7.3 mg/dL and causes cramps and tingling. Uric acid and calcium phosphate crystals block the kidney tubules, so urine output falls and creatinine rises to 2.1 mg/dL. A potassium of 6.2 mEq/L can cause fatal dysrhythmias, so the heart is monitored. More IV fluid flushes the kidneys. Potassium and hourly urine output show whether treatment works.",
      sources: [TLS, HINKLE],
    }),
    kind: "bowtie",
    conditions: [
      { text: "Hypercalcemia of malignancy", why: "The calcium is low at 7.3 mg/dL, not high." },
      { text: "Tumor lysis syndrome", why: "High potassium, phosphorus and uric acid with low calcium after chemotherapy fit cell breakdown." },
      { text: "Syndrome of inappropriate ADH", why: "That syndrome lowers sodium. It does not raise potassium, phosphorus and uric acid." },
      { text: "Septic shock", why: "The temperature is 37.0°C and the BP is 132/78 mmHg. Nothing points to sepsis." },
    ],
    actions: [
      { text: "Give oral potassium chloride", why: "Potassium is already high at 6.2 mEq/L. More potassium adds to the danger." },
      { text: "Increase IV fluids as prescribed", why: "More fluid raises urine flow and helps clear potassium, phosphorus and uric acid." },
      { text: "Restrict fluids to 1 L/day", why: "Fluid limits cut urine flow further and worsen the kidney injury." },
      { text: "Start continuous cardiac monitoring", why: "A potassium of 6.2 mEq/L can trigger dysrhythmias that need quick treatment." },
      { text: "Hold the prescribed allopurinol", why: "Allopurinol lowers uric acid production. Holding it lets uric acid climb." },
    ],
    parameters: [
      { text: "Serum amylase level", why: "Amylase tracks pancreatic injury, not cell breakdown after chemotherapy." },
      { text: "Hemoglobin A1C level", why: "A1C reflects months of glucose control and does not guide this acute problem." },
      { text: "Serum potassium level", why: "Potassium is the value most likely to cause a fatal rhythm." },
      { text: "Hourly urine output", why: "Urine output shows whether the kidneys are clearing the released cell contents." },
      { text: "Serum albumin level", why: "Albumin changes slowly and does not track this syndrome." },
    ],
    correct: { condition: 1, actions: [1, 3], parameters: [2, 3] },
  },
  {
    ...meta("rn-s26-16", {
      need: "SIPC",
      topic: "Processing level for reusable equipment",
      cjmm: "analyze",
      process: "nursing-process",
      difficulty: 3,
      stem: "The nurse sends reusable equipment for reprocessing after use. Place the level of processing that each item needs.",
      rationale:
        "The level of processing depends on the tissue the item touches. Scissors used in a sterile procedure enter sterile tissue, so they are sterilized. A laryngoscope blade touches mucous membranes, so it needs high-level disinfection at least. A blood pressure cuff touches only intact skin, so low-level disinfection is enough. Detergent cleaning alone comes before disinfection but does not replace it.",
      sources: [DISINFECTION],
    }),
    kind: "dnd",
    scoring: "zero-one",
    targets: ["Surgical scissors from a sterile procedure", "Laryngoscope blade", "Blood pressure cuff"],
    tokens: [
      { text: "High-level disinfection", why: "Items that touch mucous membranes, such as a laryngoscope blade, need at least high-level disinfection." },
      { text: "Low-level disinfection", why: "Items that touch only intact skin, such as a cuff, need low-level disinfection." },
      { text: "Sterilization", why: "Items that enter sterile tissue, such as surgical scissors, must be sterilized." },
      { text: "Detergent cleaning only", why: "Cleaning removes soil before disinfection. It does not kill enough microbes on its own." },
    ],
    correct: [2, 0, 1],
  },
  {
    ...meta("rn-s26-17", {
      need: "SIPC",
      topic: "Reading a chemical hazard pictogram",
      cjmm: "recognize",
      process: "nursing-process",
      difficulty: 2,
      stem: "The nurse finds a bottle of tissue fixative in a procedure room. Its label shows a pictogram of a human outline with a star-shaped burst on the chest. What hazard does this pictogram warn about?",
      rationale:
        "The pictogram with a human outline and a burst on the chest is the health hazard symbol. It warns of long-term harm such as cancer, harm to fertility or respiratory sensitization. The skull and crossbones marks acute toxicity that can kill. The exclamation mark marks irritants. The corrosion symbol marks chemicals that burn skin and eyes.",
      sources: [OSHA_PICTO, { body: "Canadian Centre for Occupational Health and Safety", work: "WHMIS: Pictograms", year: 2026, url: "https://www.ccohs.ca/oshanswers/chemicals/whmis_ghs/pictograms.html" }],
      canada: "Canadian workplaces label chemicals under WHMIS, which Canada has aligned with the GHS. The WHMIS health hazard pictogram is the same person with a starburst and covers carcinogens and reproductive toxins.",
    }),
    kind: "mc",
    options: [
      { text: "Cancer or harm to fertility", why: "The health hazard pictogram warns of long-term effects such as cancer and reproductive harm." },
      { text: "Fatal poisoning in small doses", why: "Acute toxicity that can kill is shown by the skull and crossbones." },
      { text: "Mild skin and eye irritation", why: "Irritants carry the exclamation mark pictogram." },
      { text: "Burns to the skin and eyes", why: "Corrosive chemicals carry the corrosion pictogram of liquid eating into a hand." },
    ],
    correct: 0,
  },
  {
    ...meta("rn-s26-18", {
      need: "RRP",
      topic: "Screening results that meet diabetes thresholds",
      cjmm: "analyze",
      process: "clinical-judgment",
      difficulty: 3,
      stem: "A 52-year-old client has no symptoms of high blood glucose. The nurse reviews the client's screening results. Which two results meet a threshold for diagnosing diabetes? Select two.",
      rationale:
        "A fasting glucose of 131 mg/dL is above the 126 mg/dL threshold. An A1C of 6.7% is above the 6.5% threshold. An A1C of 6.1% and a fasting glucose of 112 mg/dL fall in the prediabetes range. A 2-hour value of 182 mg/dL is below 200 mg/dL. A random value of 176 mg/dL is below 200 mg/dL and the client has no symptoms.",
      refs: [
        "Diabetes thresholds: A1C 6.5% or more, fasting glucose 126 mg/dL (7.0 mmol/L) or more, 2-hour glucose 200 mg/dL (11.1 mmol/L) or more on an oral glucose tolerance test.",
        "Prediabetes ranges: A1C 5.7% to 6.4%, fasting glucose 100 mg/dL (5.6 mmol/L) to 125 mg/dL (6.9 mmol/L).",
        "A random glucose of 200 mg/dL or more counts only with classic symptoms of high glucose.",
      ],
      sources: [ADA_DX, { body: "Punthakee Z, Goldenberg R, Katz P. Diabetes Canada Clinical Practice Guidelines Expert Committee", work: "Definition, Classification and Diagnosis of Diabetes, Prediabetes and Metabolic Syndrome. Canadian Journal of Diabetes 42(Suppl 1):S10", year: 2018, url: "https://www.diabetes.ca/for-professionals/full-guidelines/chapter-3" }],
      canada: "Diabetes Canada uses the same diabetes thresholds in mmol/L: fasting 7.0, 2-hour 11.1 and A1C 6.5%. Its prediabetes ranges are narrower, fasting 6.1 to 6.9 mmol/L and A1C 6.0% to 6.4%, but both prediabetes options still fall inside them.",
    }),
    kind: "msn",
    select: 2,
    options: [
      { text: "A1C 6.1%", why: "An A1C of 6.1% lies in the prediabetes range of 5.7% to 6.4%." },
      { text: "Fasting glucose 131 mg/dL (7.3 mmol/L)", why: "A fasting value at or above 126 mg/dL meets the diabetes threshold." },
      { text: "2-hour glucose 182 mg/dL (10.1 mmol/L)", why: "The 2-hour threshold is 200 mg/dL, so 182 mg/dL falls short." },
      { text: "A1C 6.7%", why: "An A1C at or above 6.5% meets the diabetes threshold." },
      { text: "Fasting glucose 112 mg/dL (6.2 mmol/L)", why: "A fasting value of 112 mg/dL lies in the prediabetes range." },
      { text: "Random glucose 176 mg/dL (9.8 mmol/L)", why: "A random value needs 200 mg/dL or more with symptoms. Neither applies." },
    ],
    correct: [1, 3],
  },
  {
    ...meta("rn-s26-19", {
      need: "SIPC",
      topic: "Hazardous drug assignment during pregnancy",
      cjmm: "generate",
      process: "nursing-process",
      difficulty: 3,
      stem: "A staff nurse tells the charge nurse that she is 10 weeks pregnant. Tomorrow's assignment includes a client who will receive IV cyclophosphamide, an antineoplastic drug. What should the charge nurse do?",
      rationale:
        "Many hazardous drugs can cause miscarriage or birth defects. Workers who are pregnant, breastfeeding or trying to conceive should be offered duties that do not involve handling these drugs. Extra gowns and a respirator lower exposure but do not remove it. A signed waiver does not change the risk to the pregnancy.",
      sources: [ASHP_HD],
    }),
    kind: "mc",
    options: [
      { text: "Assign her the client with a second gown", why: "A second gown lowers skin contact but leaves the reproductive risk in place." },
      { text: "Assign her the client with an N95 respirator", why: "A respirator does not stop skin contact with the drug or its residue." },
      { text: "Assign her the client after she signs a waiver", why: "A waiver shifts paperwork, not risk. The exposure to the pregnancy remains." },
      { text: "Offer her an assignment without hazardous drugs", why: "Alternative duty is offered to pregnant workers because of reproductive risk." },
    ],
    correct: 3,
  },
  {
    ...meta("rn-s26-20", {
      need: "PPT",
      topic: "Volume of reconstituted ceftriaxone for IM use",
      cjmm: "action",
      process: "nursing-process",
      difficulty: 3,
      stem: "The primary health care provider prescribes ceftriaxone 500 mg IM once. The nurse reconstitutes a 1 g vial with 2.1 mL of sterile water for injection. The label states that this gives 350 mg/mL. How many mL should the nurse draw up? Round to the nearest tenth.",
      rationale:
        "The dose is 500 mg and the solution holds 350 mg in each mL. Dividing 500 by 350 gives 1.43 mL, which rounds to 1.4 mL. The diluent volume is not the dose volume. Drawing up the whole vial would give about 1 g, twice the prescribed dose.",
      calc: { expr: "500 / 350", answer: 1.4285714285714286, unit: "mL", round: 1, steps: ["500 / 350 = 1.43"] },
      sources: [CEFTRIAXONE],
    }),
    kind: "mc",
    options: [
      { text: "0.7 mL", why: "This divides 350 by 500 instead of the dose by the concentration." },
      { text: "1.4 mL", why: "500 mg divided by 350 mg/mL is 1.43 mL, which rounds to 1.4 mL." },
      { text: "2.0 mL", why: "At 350 mg/mL this volume holds more than the 500 mg dose." },
      { text: "2.1 mL", why: "This is the diluent volume. At 350 mg/mL, 2.1 mL holds far more than the 500 mg dose." },
    ],
    correct: 1,
  },
];
