// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const olderWomanConfusionSeizure: OralCase = {
  id: "older-woman-confusion-seizure",
  title: "Confused, then shaking",
  blueprint: "geri",
  alsoCovers: ["neuro"],
  priorityTopic: "seizures",
  keyFeatures: [
    { topic: "seizures", n: 2 },
    { topic: "seizures", n: 4 },
    { topic: "delirium-agitation", n: 2 },
  ],
  summary: "An 84 year old woman is brought in by her daughter with two days of vomiting and confusion.",
  durationMinutes: 14,
  stem:
    "You are the emergency physician at a 220 bed community hospital in Ontario. There is an ICU, a step down unit, CT and a lab with results in about 30 minutes. " +
    "Evelyn Park is 84 years old and about 50 kg. She lives alone. Her daughter found her confused this morning. She has vomited several times over 2 days and has been unsteady on her feet. " +
    "Her family doctor started hydrochlorothiazide 25 mg daily 6 weeks ago for blood pressure. She has taken sertraline for 3 months for low mood. " +
    "Her daughter says she has been drinking lots of water and eating little besides tea and toast. " +
    "Triage vitals: heart rate 88, blood pressure 138/74, respiratory rate 18, SpO2 96 percent on room air, temperature 36.6, capillary glucose 6.1 mmol/L. GCS 13. CTAS 2. " +
    "The nurse says: 'She keeps asking the same questions and she just vomited again. Her daughter thinks she might have had a small stroke.'",
  findings: [
    {
      id: "exam",
      label: "Physical exam",
      result:
        "Drowsy but rousable. GCS 13 (E3 V4 M6). No focal weakness. Pupils equal and reactive. No neck stiffness. Mucous membranes moist. JVP 2 cm. No edema. Chest clear. Abdomen soft.",
    },
    {
      id: "labs",
      label: "Electrolytes and renal",
      result:
        "Sodium 112 mmol/L. Potassium 2.9 mmol/L. Chloride 78 mmol/L. Bicarbonate 27 mmol/L. Glucose 6.2 mmol/L. Urea 3.1 mmol/L. Creatinine 64 µmol/L. Calcium normal. Magnesium 0.68 mmol/L.",
    },
    {
      id: "osm",
      label: "Serum and urine studies",
      result: "Serum osmolality 236 mmol/kg. Urine osmolality 390 mmol/kg. Urine sodium 58 mmol/L. Urine potassium 34 mmol/L.",
    },
    {
      id: "endo",
      label: "Thyroid and adrenal",
      result: "TSH 2.1 mIU/L. Random cortisol 540 nmol/L.",
    },
    {
      id: "ecg",
      label: "ECG",
      result: "Sinus rhythm at 86. Prominent U waves. QTc 490 ms.",
    },
    {
      id: "ct-head",
      label: "CT head",
      result: "No hemorrhage or infarct. Mild generalized atrophy. No signs of raised pressure.",
    },
    {
      id: "baseline",
      label: "Previous results",
      result: "Sodium 136 mmol/L three months ago before sertraline. No sodium checked since the thiazide was started.",
    },
    {
      id: "repeat-na",
      label: "Sodium after hypertonic saline",
      result: "Sodium 117 mmol/L 30 minutes after the second bolus. She is awake and talking. No further seizures.",
    },
    {
      id: "six-hours",
      label: "Six hour check",
      result: "Sodium 122 mmol/L. Urine output 380 mL/h for the last 3 hours. Urine osmolality now 95 mmol/kg. Potassium 3.6 mmol/L after replacement.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "Assessment",
      text: "Evelyn is on a stretcher, drowsy and repeating herself. Her daughter holds a bag of pill bottles.",
      next: "q-initial",
    },
    {
      kind: "question",
      id: "q-initial",
      phase: "Initial approach",
      prompt: "What is your differential and what do you do in the first 15 minutes?",
      seconds: 75,
      modelAnswer: [
        "Delirium in an older adult. Look for a cause.",
        "Hyponatremia from a thiazide, SSRI and low solute intake is high on the list.",
        "Also stroke, subdural hematoma, infection, hypoglycemia, other drugs and seizure.",
        "Monitor, IV access, capillary glucose, electrolytes, osmolality, ECG.",
        "CT head given her age and confusion.",
        "Review every medication with the bottles.",
      ],
      rubric: ["hn-a1"],
      next: "s-seizure",
    },
    {
      kind: "say",
      id: "s-seizure",
      phase: "Deterioration",
      text: "While you review the bottles the nurse calls out. Evelyn is having a generalized tonic clonic seizure. At the same moment the lab calls: sodium 112 mmol/L.",
      next: "q-seizure",
    },
    {
      kind: "question",
      id: "q-seizure",
      phase: "Seizure",
      prompt: "She is still seizing after 2 minutes. What exactly do you give?",
      seconds: 75,
      modelAnswer: [
        "Severe symptomatic hyponatremia. Hypertonic saline is the treatment.",
        "3 percent saline 150 mL IV over 20 minutes, or 100 mL over 10 minutes. A peripheral line is acceptable.",
        "Repeat up to twice more, checking sodium, until symptoms stop or sodium rises about 5 mmol/L.",
        "Lorazepam 1 to 2 mg IV if the seizure continues while the saline runs.",
        "Airway support, oxygen, recovery position, suction.",
        "Standard antiseizure drugs will not fix the cause.",
      ],
      rubric: ["hn-r1", "hn-r2"],
      choices: [
        {
          id: "c-hypertonic",
          label: "I gave 150 mL of 3 percent saline over 20 minutes with lorazepam 1 mg IV, then repeated the bolus after a sodium check.",
          next: "q-targets",
          quality: "strong",
          feedback:
            "Strong. A rise of 4 to 6 mmol/L is usually enough to stop seizures from hyponatremia. Hypertonic saline treats the brain edema directly.",
        },
        {
          id: "c-antiseizure",
          label: "I gave lorazepam and loaded levetiracetam 20 mg/kg, then planned to correct the sodium slowly.",
          next: "s-antiseizure",
          quality: "partial",
          feedback:
            "Partial. Supporting her through the seizure is right. But the cause is cerebral edema from low sodium. Only hypertonic saline treats it. Slow correction is for patients without severe symptoms.",
        },
        {
          id: "c-restrict",
          label: "I restricted her fluids and started normal saline at 100 mL/h.",
          next: "s-restrict",
          quality: "unsafe",
          feedback:
            "Unsafe. Fluid restriction and normal saline raise sodium over days, not minutes. A seizing patient with sodium of 112 needs 3 percent saline now.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-antiseizure",
      phase: "Ten minutes later",
      text: "The seizure stops, then a second one starts. The ICU resident arrives and suggests 3 percent saline. You give 150 mL over 20 minutes.",
      next: "q-targets",
    },
    {
      kind: "say",
      id: "s-restrict",
      phase: "Fifteen minutes later",
      text: "She is still seizing and her SpO2 is 84 percent. You give 3 percent saline 150 mL over 20 minutes and lorazepam 1 mg IV.",
      next: "q-targets",
    },
    {
      kind: "question",
      id: "q-targets",
      phase: "Correction plan",
      prompt: "The seizures have stopped and her sodium is now 117. What is your correction limit for the next 24 hours and how will you monitor?",
      seconds: 75,
      modelAnswer: [
        "She is at high risk of osmotic demyelination: low potassium, poor nutrition, older age and a thiazide.",
        "Limit the total rise to 8 mmol/L in the first 24 hours, counted from 112. So no higher than about 120.",
        "She has already risen 5. Stop hypertonic saline now that symptoms are controlled.",
        "Sodium every 2 hours at first. Strict urine output.",
        "Replace potassium, but remember it raises sodium as well.",
        "Replace magnesium.",
      ],
      rubric: ["hn-m1", "hn-m2"],
      next: "q-cause",
    },
    {
      kind: "question",
      id: "q-cause",
      phase: "Cause",
      prompt: "Look at her urine studies and history. What is the cause, and how does it change your plan?",
      seconds: 75,
      modelAnswer: [
        "Urine osmolality of 390 means ADH is active and water is not being cleared.",
        "Urine sodium is high, but the thiazide makes it hard to interpret.",
        "Likely causes together: thiazide, SSRI induced SIADH and low solute intake with high water intake.",
        "TSH and cortisol are normal.",
        "Stop the hydrochlorothiazide and the sertraline.",
        "Expect a water diuresis once the drugs stop and solute intake returns. Sodium may rise quickly.",
      ],
      rubric: ["hn-a2", "hn-m3"],
      choices: [
        {
          id: "c-multi",
          label: "I called it multifactorial from the thiazide, sertraline and low solute intake, stopped both drugs and warned the team about a water diuresis.",
          next: "s-overcorrect",
          quality: "strong",
          feedback:
            "Strong. Several causes often combine in older adults. Once the triggers are removed the kidneys can dump free water fast. Anticipating that is the key safety step.",
        },
        {
          id: "c-siadh",
          label: "I diagnosed SIADH, restricted fluids to 800 mL a day and continued her home medications.",
          next: "s-siadh",
          quality: "partial",
          feedback:
            "Partial. SIADH from the SSRI is part of it. But continuing the thiazide and sertraline keeps the cause going. You also missed the risk of rapid correction when they stop.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-siadh",
      phase: "Pharmacy",
      text: "The pharmacist flags the thiazide and sertraline on her admission orders as likely causes. You stop both.",
      next: "s-overcorrect",
    },
    {
      kind: "say",
      id: "s-overcorrect",
      phase: "Six hours later",
      text: "The nurse calls you. Evelyn has passed 380 mL of urine per hour for 3 hours. Her urine osmolality is now 95. Her sodium is 122, up 10 from the start.",
      next: "q-overcorrect",
    },
    {
      kind: "question",
      id: "q-overcorrect",
      phase: "Overcorrection",
      prompt: "What is happening and what do you do?",
      seconds: 75,
      modelAnswer: [
        "Water diuresis. She has already passed the 8 mmol/L limit in 6 hours.",
        "High risk of osmotic demyelination.",
        "Stop all sodium containing fluids.",
        "Desmopressin 2 mcg IV to stop the water loss, repeated every 6 to 8 hours as needed.",
        "D5W at about 3 mL/kg/h, about 150 mL/h, to bring sodium back toward the target.",
        "Sodium every 1 to 2 hours. Involve ICU or nephrology.",
      ],
      rubric: ["hn-r3", "hn-l1"],
      choices: [
        {
          id: "c-relower",
          label: "I stopped saline, gave desmopressin 2 mcg IV and started D5W at 150 mL/h, with sodium checks every 1 to 2 hours.",
          next: "q-dispo",
          quality: "strong",
          feedback:
            "Strong. Desmopressin clamps the water loss and D5W brings the sodium back down. Relowering after overcorrection may reduce the risk of osmotic demyelination.",
        },
        {
          id: "c-stop",
          label: "I stopped all IV fluids and planned to recheck in 6 hours.",
          next: "s-stop",
          quality: "partial",
          feedback:
            "Partial. Stopping fluids is a start. But the kidneys are still clearing free water fast, so the sodium will keep climbing. Desmopressin and D5W are needed.",
        },
        {
          id: "c-continue",
          label: "I was pleased she was improving and continued toward a normal sodium.",
          next: "s-continue",
          quality: "unsafe",
          feedback:
            "Unsafe. Chronic hyponatremia must be corrected slowly. A rise of more than 8 mmol/L in 24 hours in a high risk patient can cause osmotic demyelination days later.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-stop",
      phase: "Six hours later",
      text: "Her sodium is 127. The nephrologist asks you to start desmopressin and D5W right away.",
      next: "q-dispo",
    },
    {
      kind: "say",
      id: "s-continue",
      phase: "Next morning",
      text: "Her sodium is 131, up 19 in 24 hours. The ICU team starts desmopressin and D5W to relower it and warns the family about the risk of delayed neurological injury.",
      next: "q-dispo",
    },
    {
      kind: "question",
      id: "q-dispo",
      phase: "Disposition",
      prompt: "Where should she be admitted and what goes in your plan and handover?",
      seconds: 60,
      modelAnswer: [
        "Step down unit or ICU for sodium checks every 1 to 2 hours and neuro checks.",
        "Clear written sodium limit for the next 24 and 48 hours.",
        "Stop hydrochlorothiazide and do not restart it. Hold sertraline. Her family doctor should review her mood treatment with sodium checks if an antidepressant is restarted.",
        "Potassium and magnesium replacement.",
        "Seizure precautions. Fall risk. Delirium prevention.",
        "Nutrition review for low solute intake.",
      ],
      rubric: ["hn-d1", "hn-m4"],
      next: "q-family",
    },
    {
      kind: "question",
      id: "q-family",
      phase: "Family",
      prompt: "Her daughter asks, 'Did her pills do this? What should we watch for?' What do you tell her?",
      seconds: 60,
      modelAnswer: [
        "Her sodium was very low. That caused the confusion and the seizure.",
        "The water pill and the antidepressant likely both contributed, along with eating little and drinking lots of water.",
        "The water pill is stopped for good. The antidepressant is on hold. Her family doctor will review other options for blood pressure and mood.",
        "We corrected slowly to protect her brain. Explain the risk of delayed nerve injury and what we are doing to prevent it.",
        "Send a letter to her family doctor. Future sodium checks after any new medication.",
      ],
      rubric: ["hn-c1", "hn-p1"],
      next: "end",
    },
    { kind: "end", id: "end", text: "Evelyn is admitted to the step down unit. That is the end of the case." },
  ],
  rubric: [
    {
      id: "hn-a1",
      competency: "assessment",
      criterion: "approach",
      text: "Builds a differential for delirium in an older adult and reviews every medication.",
      points: 1,
      teaching: "Drugs are among the most common reversible causes of delirium and electrolyte problems in older adults.",
      source: "beers",
    },
    {
      id: "hn-r1",
      competency: "resuscitation",
      criterion: "plan",
      text: "Treats seizures from hyponatremia with 3 percent saline 100 to 150 mL IV bolus, repeated as needed.",
      points: 3,
      critical: true,
      teaching: "A 4 to 6 mmol/L rise reverses most severe symptoms. Give it quickly in bolus form.",
      source: "spasovski",
    },
    {
      id: "hn-r2",
      competency: "resuscitation",
      criterion: "plan",
      text: "Supports airway and uses a benzodiazepine as a bridge, without relying on standard antiseizure drugs.",
      points: 1,
      teaching: "Antiseizure drugs do not treat cerebral edema. Hypertonic saline does.",
      source: "verbalis",
    },
    {
      id: "hn-m1",
      competency: "management",
      criterion: "diagnosis",
      text: "Identifies her high risk for osmotic demyelination and sets a limit of 8 mmol/L in 24 hours.",
      points: 3,
      critical: true,
      teaching: "Hypokalemia, malnutrition, alcohol use and liver disease raise the risk. Use the lower limit.",
      source: "verbalis",
    },
    {
      id: "hn-m2",
      competency: "management",
      criterion: "plan",
      text: "Stops hypertonic saline once symptoms settle and monitors sodium every 2 hours.",
      points: 2,
      teaching: "Hypertonic saline is for symptoms. Once they settle, the goal is slow, safe correction.",
      source: "spasovski",
    },
    {
      id: "hn-a2",
      competency: "assessment",
      criterion: "data",
      text: "Interprets urine osmolality and urine sodium in light of the thiazide.",
      points: 1,
      teaching: "Urine osmolality over 100 mmol/kg means ADH is acting. Diuretics make urine sodium unreliable.",
      source: "spasovski",
    },
    {
      id: "hn-m3",
      competency: "management",
      criterion: "plan",
      text: "Stops the thiazide and SSRI and anticipates a water diuresis.",
      points: 2,
      teaching: "When the cause of ADH release or the thiazide effect is removed, the sodium can rise very fast.",
      source: "sterns",
    },
    {
      id: "hn-r3",
      competency: "resuscitation",
      criterion: "plan",
      text: "Treats overcorrection with desmopressin 2 mcg IV and D5W about 3 mL/kg/h with frequent sodium checks.",
      points: 3,
      critical: true,
      teaching: "Relowering sodium after overcorrection may prevent osmotic demyelination.",
      source: "sterns",
    },
    {
      id: "hn-l1",
      competency: "leadership",
      criterion: "plan",
      text: "Involves ICU or nephrology early and sets clear nursing triggers for urine output and sodium.",
      points: 1,
      teaching: "Tell nurses to call for urine output over 100 mL/h or a sodium rise beyond the plan.",
      source: "sterns",
    },
    {
      id: "hn-d1",
      competency: "disposition",
      criterion: "plan",
      text: "Admits to a monitored unit with a written sodium limit for 24 and 48 hours.",
      points: 2,
      teaching: "A written limit guides every clinician who touches the orders overnight.",
      source: "verbalis",
    },
    {
      id: "hn-m4",
      competency: "management",
      criterion: "plan",
      text: "Replaces potassium and magnesium and accounts for their effect on sodium.",
      points: 1,
      teaching: "Potassium replacement raises serum sodium. Include it in the correction budget.",
      source: "spasovski",
    },
    {
      id: "hn-c1",
      competency: "communication",
      criterion: "plan",
      text: "Explains the cause and the risk of delayed neurological injury to the daughter in plain language.",
      points: 1,
      teaching: "Families should know that problems from fast correction can appear days later.",
      source: "sterns",
    },
    {
      id: "hn-p1",
      competency: "professionalism",
      criterion: "plan",
      text: "Communicates the drug harm to the family doctor and recommends avoiding thiazides and SSRIs without sodium monitoring.",
      points: 1,
      teaching: "The Beers criteria flag thiazides and SSRIs as causes of hyponatremia in older adults.",
      source: "beers",
    },
  ],
  sources: [
    {
      id: "spasovski",
      citation: "Spasovski G, et al. Clinical practice guideline on diagnosis and treatment of hyponatraemia. Eur J Endocrinol. 2014.",
    },
    {
      id: "verbalis",
      citation: "Verbalis JG, et al. Diagnosis, evaluation, and treatment of hyponatremia: expert panel recommendations. Am J Med. 2013.",
    },
    {
      id: "sterns",
      citation: "Sterns RH. Disorders of plasma sodium: causes, consequences, and correction. N Engl J Med. 2015.",
    },
    {
      id: "beers",
      citation: "American Geriatrics Society Beers Criteria Update Expert Panel. American Geriatrics Society 2023 updated AGS Beers Criteria for potentially inappropriate medication use in older adults. J Am Geriatr Soc. 2023.",
    },
  ],
  reviewed: false,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 1,
};
