// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Preceptor", version: 1 } as const;

const S = {
  icg: { id: "icg", citation: "Barkun AN, Almadi M, Kuipers EJ, et al. Management of nonvariceal upper gastrointestinal bleeding: guideline recommendations from the International Consensus Group. Ann Intern Med. 2019." },
  acgUgib: { id: "acg-ugib", citation: "Laine L, Barkun AN, Saltzman JR, Martel M, Leontiadis GI. ACG clinical guideline: upper gastrointestinal and ulcer bleeding. Am J Gastroenterol. 2021." },
  acgCag: { id: "acg-cag", citation: "Abraham NS, Barkun AN, et al. American College of Gastroenterology and Canadian Association of Gastroenterology clinical practice guideline: management of anticoagulants and antiplatelets during acute gastrointestinal bleeding and the periendoscopic period. Am J Gastroenterol. 2022." },
  baveno: { id: "baveno", citation: "de Franchis R, Bosch J, Garcia-Tsao G, Reiberger T, Ripoll C, Baveno VII Faculty. Baveno VII. Renewing consensus in portal hypertension. J Hepatol. 2022." },
  villanueva: { id: "villanueva", citation: "Villanueva C, et al. Transfusion strategies for acute upper gastrointestinal bleeding. N Engl J Med. 2013." },
  haltit: { id: "halt-it", citation: "HALT-IT Trial Collaborators. Effects of a high-dose 24-h infusion of tranexamic acid on death and thromboembolic events in patients with acute gastrointestinal bleeding (HALT-IT): an international randomised, double-blind, placebo-controlled trial. Lancet. 2020." },
  blatchford: { id: "blatchford", citation: "Blatchford O, Murray WR, Blatchford M. A risk score to predict need for treatment for upper gastrointestinal haemorrhage. Lancet. 2000." },
  stanley: { id: "stanley", citation: "Stanley AJ, et al. Comparison of risk scoring systems for patients presenting with upper gastrointestinal bleeding: international multicentre prospective study. BMJ. 2017." },
  bsgLgib: { id: "bsg-lgib", citation: "Oakland K, et al. Diagnosis and management of acute lower gastrointestinal bleeding: guidelines from the British Society of Gastroenterology. Gut. 2019." },
  acgLgib: { id: "acg-lgib", citation: "Sengupta N, et al. Management of patients with acute lower gastrointestinal bleeding: an updated ACG guideline. Am J Gastroenterol. 2023." },
  tcDoac: { id: "tc-doac", citation: "Thrombosis Canada. Clinical guide: DOACs: management of bleeding. 2024.", url: "https://thrombosiscanada.ca/clinical_guides/pdfs/MANAGEMENTOFBLEEDINGINPATIENTS_75.pdf" },
  tcWarfarin: { id: "tc-warfarin", citation: "Thrombosis Canada. Clinical guide: warfarin. 2024.", url: "https://thrombosiscanada.ca/clinical_guides/pdfs/WARFARIN_40.pdf" },
  cbs: { id: "cbs", citation: "Trudeau JD, Dawe P, Shih AW. Massive hemorrhage and emergency transfusion. In: Clarke G, Chargé S, editors. Clinical Guide to Transfusion. Chapter 11. Canadian Blood Services. 2021.", url: "https://professionaleducation.blood.ca/en/transfusion/clinical-guide/massive-hemorrhage-and-emergency-transfusion" },
  pollack: { id: "pollack", citation: "Pollack CV Jr, et al. Idarucizumab for dabigatran reversal. N Engl J Med. 2015." },
  mint: { id: "mint", citation: "Carson JL, et al. Restrictive or liberal transfusion strategy in myocardial infarction and anemia. N Engl J Med. 2023. The MINT trial." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. 10th ed. Elsevier. 2023. Chapters on gastrointestinal bleeding, esophagus and aortic disease." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, Ma OJ, Yealy DM, Meckler GD, Stapczynski JS, Cline DM, Thomas SH, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. 9th ed. McGraw Hill. 2020. Chapter 75, Upper Gastrointestinal Bleeding. Chapter 77, Esophageal Emergencies. Chapter 134, Gastrointestinal Bleeding in Infants and Children." },
  acrGv: { id: "acr-gv", citation: "Expert Panel on Interventional Radiology, Kim CY, Pinchot JW, et al. ACR Appropriateness Criteria: radiologic management of gastric varices. J Am Coll Radiol. 2020. 17(5S):S239-S254.", url: "https://acsearch.acr.org/docs/70911/Narrative/" },
  ncsReversal: { id: "ncs-reversal", citation: "Frontera JA, Lewin JJ, Rabinstein AA, et al. Guideline for reversal of antithrombotics in intracranial hemorrhage: a statement for healthcare professionals from the Neurocritical Care Society and Society of Critical Care Medicine. Neurocrit Care. 2016. 24(1):6-46.", url: "https://doi.org/10.1007/s12028-015-0222-x" },
  ccsStemi: { id: "ccs-stemi", citation: "Wong GC, Welsford M, Ainsworth C, et al. 2019 Canadian Cardiovascular Society/Canadian Association of Interventional Cardiology guidelines on the acute management of ST-elevation myocardial infarction: focused update on regionalization and reperfusion. Can J Cardiol. 2019. 35(2):107-132.", url: "https://doi.org/10.1016/j.cjca.2018.11.031" },
} satisfies Record<string, Source>;

export const GI_BLEED_SAMPS: Samp[] = [
  {
    id: "gi-bleed-01",
    topic: "gi-bleed",
    title: "Hematemesis in a man who no longer drinks",
    stem:
      "A 51-year-old man is brought to the emergency department by ambulance after three episodes of hematemesis over 2 hours, about 2 cups each time. He has chronic pancreatitis from alcohol and has not had a drink in 4 years. He was admitted with a flare of pancreatitis 7 months ago. He takes pancrelipase with meals and no NSAIDs, antiplatelets or anticoagulants. He has never had a transfusion. He is pale and anxious. There is no jaundice, spider angioma, palmar erythema or ascites. The spleen tip is palpable 4 cm below the left costal margin. Hemoglobin 76 g/L, platelets 88 x 10^9/L, INR 1.1, bilirubin 12 umol/L, albumin 38 g/L, creatinine 84 umol/L.",
    vitals: { temperature: "36.4°C", pulse: "126/minute", resp: "22/minute", bp: "86/52 mmHg", o2sat: "97% on room air", weight: "72 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of his history and examination point to the likely source of bleeding?",
        accept: [
          { id: "panc", text: "Chronic pancreatitis with a recent flare", match: ["pancreatitis", "pancreatic"] },
          { id: "spleen", text: "A palpable, enlarged spleen", match: ["spleen", "splenomegaly", "splenic"] },
          { id: "plt", text: "A low platelet count from hypersplenism", match: ["platelet", "thrombocytopenia", "hypersplenism"] },
          { id: "noliver", text: "No stigmata of cirrhosis and normal liver tests", match: ["no stigmata", "normal liver", "no cirrhosis", "no jaundice", "no ascites", "normal inr", "normal albumin", "normal bilirubin", "no spider"] },
          { id: "nodrugs", text: "No NSAID, antiplatelet or anticoagulant use", match: ["no nsaid", "no antiplatelet", "no anticoagulant", "no asa", "no ibuprofen"] },
        ],
        explanation:
          "Chronic pancreatitis with a palpable spleen and a low platelet count, but normal liver tests and no stigmata of cirrhosis, points to splenic vein thrombosis. The ACR Appropriateness Criteria describe how pancreatitis can occlude the splenic vein, causing splenomegaly, increased splenic flow and gastric varices, known as sinistral portal hypertension. Absent NSAID and antithrombotic use makes a drug-related ulcer less likely. Stigmata of cirrhosis would instead suggest esophageal varices from generalized portal hypertension.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "acr-gv",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What are your immediate resuscitation actions?",
        accept: [
          { id: "iv", text: "Two large bore IV lines", match: ["large bore", "two iv", "2 iv", "two peripheral", "iv access", "intraosseous", "rapid infuser"] },
          { id: "xm", text: "Group and crossmatch", match: ["crossmatch", "cross match", "type and screen", "group and screen", "type and cross", "blood bank sample"] },
          { id: "rbc", text: "Uncrossmatched group O red cells now, RhD positive being acceptable for him", match: ["uncrossmatched", "o positive", "o pos", "o negative", "o neg", "group o", "emergency release", "prbc", "red cell", "red blood cell", "transfuse", "transfusion"] },
          { id: "mhp", text: "Activate the massive hemorrhage protocol", match: ["massive hemorrhage", "massive transfusion", "mtp", "mhp"] },
          { id: "limit", text: "Limit crystalloid to about 1 L before blood", match: ["limit crystalloid", "minimize crystalloid", "restrict crystalloid", "avoid crystalloid", "avoid large volume crystalloid", "limit fluid", "permissive"] },
          { id: "ca", text: "Monitor and replace ionized calcium", match: ["calcium"] },
        ],
        unacceptable: [
          { text: "Large volume crystalloid to a normal BP", match: ["aggressive crystalloid", "aggressive fluid", "wide open saline", "normal saline wide open"] },
        ],
        explanation:
          "He is in hemorrhagic shock with a hemoglobin of 76 g/L and ongoing hematemesis. Secure large bore access, send a crossmatch sample and give uncrossmatched group O red cells now through the massive hemorrhage protocol. Canadian Blood Services advises that group O RhD positive red cells can be given to males with no prior transfusion of RhD positive blood, which keeps RhD negative units for females of childbearing age and children. Limit crystalloid to about 1 L before switching to blood. Calcium monitoring and replacement belong in every massive hemorrhage protocol.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "cbs",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "Emergency endoscopy shows a large isolated fundal varix with an adherent clot, and no esophageal varices or ulcer. Cyanoacrylate injection stops the bleeding. CT with a portal venous phase shows an occluded splenic vein, a patent portal vein, splenomegaly and a normal liver.",
        prompt: "Which of the following treatments are most appropriate to prevent rebleeding from this varix?",
        options: [
          "Balloon-occluded retrograde transvenous obliteration",
          "Carvedilol 6.25 mg PO daily",
          "Esophageal band ligation every 2 weeks",
          "Heparin infusion for the splenic vein thrombosis",
          "Partial splenic embolization",
          "Splenectomy by general surgery",
          "Transjugular intrahepatic portosystemic shunt",
        ],
        correct: [4, 5],
        explanation:
          "His varix fills because the occluded splenic vein drains through the short gastric veins into the stomach wall. For gastric variceal bleeding with splenic vein occlusion, the ACR Appropriateness Criteria rate partial splenic embolization and surgical management such as splenectomy as usually appropriate, because both cut the splenic inflow that feeds the varix. TIPS and BRTO are rated usually not appropriate, since his portal pressure is normal and the problem lies in the splenic bed. Carvedilol lowers portal pressure in cirrhosis and does not treat an occluded splenic vein. He has no esophageal varices to band. Heparin adds bleeding risk and does not reopen a chronic occlusion.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "acr-gv",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Before either procedure can be done, he vomits 600 mL of fresh blood. His BP is 78/44 mmHg.",
        prompt: "What measures can control this rebleeding while definitive treatment is arranged?",
        accept: [
          { id: "repeat", text: "Repeat endoscopic cyanoacrylate injection", match: ["repeat endoscopy", "repeat endoscopic", "repeat glue", "repeat cyanoacrylate", "cyanoacrylate", "glue"] },
          { id: "balloon", text: "Balloon tamponade using a gastric balloon, such as a Minnesota or Linton tube", match: ["balloon tamponade", "tamponade", "sengstaken", "blakemore", "minnesota", "linton"] },
          { id: "sae", text: "Emergency splenic artery embolization", match: ["splenic artery embolization", "splenic embolization", "embolization", "embolize"] },
          { id: "surg", text: "Emergency splenectomy", match: ["splenectomy"] },
        ],
        unacceptable: [
          { text: "TIPS", match: ["tips", "transjugular"] },
        ],
        explanation:
          "Endoscopic cyanoacrylate injection is rated may be appropriate for this anatomy and can be repeated to regain control. Splenic embolization or splenectomy stops the inflow and can be done urgently. Balloon tamponade with the gastric balloon inflated against the fundus is a temporary bridge and needs a protected airway. TIPS is rated usually not appropriate with splenic vein occlusion because it does not decompress the splenic bed.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "acr-gv",
      },
    ],
    sources: [S.acrGv, S.cbs],
    ...META,
    reviewed: false,
    version: 2,
  },
  {
    id: "gi-bleed-02",
    topic: "gi-bleed",
    title: "Black stools and light headedness",
    stem:
      "A 67-year-old woman has had three days of black stools and feels light headed when she stands. She has knee osteoarthritis. She has no chest pain and no known heart disease. Hemoglobin 94 g/L (128 g/L one year ago), urea 14.2 mmol/L, creatinine 88 micromol/L, INR 1.0, platelets 260 x 10^9/L.",
    vitals: { pulse: "96/minute", resp: "16/minute", bp: "118/70 mmHg", o2sat: "98% on arrival", weight: "62 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What medications or substances would you specifically ask about?",
        accept: [
          { id: "nsaid", text: "NSAIDs such as ibuprofen or naproxen", match: ["nsaid", "ibuprofen", "naproxen", "anti inflammatory"] },
          { id: "asa", text: "ASA", match: ["asa", "aspirin"] },
          { id: "anticoag", text: "Anticoagulants such as warfarin or a DOAC", match: ["anticoagulant", "warfarin", "doac", "apixaban"] },
          { id: "clop", text: "Antiplatelets such as clopidogrel or ticagrelor", match: ["clopidogrel", "antiplatelet"] },
          { id: "ssri", text: "SSRIs", match: ["ssri"] },
          { id: "steroid", text: "Corticosteroids", match: ["steroid", "corticosteroid", "prednisone"] },
          { id: "alcohol", text: "Alcohol", match: ["alcohol"] },
          { id: "iron", text: "Iron or bismuth, which blacken stool", match: ["iron", "bismuth"] },
        ],
        explanation:
          "NSAIDs, ASA, anticoagulants, antiplatelets, SSRIs and steroids all raise the risk of peptic ulcer bleeding. Many patients take over the counter NSAIDs for arthritis and do not think of them as medications. Iron and bismuth can mimic melena.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "icg",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate transfusion plan for her now?",
        options: [
          "Frozen plasma 2 units IV",
          "IV iron now instead of repeat hemoglobin",
          "Red cells 1 unit now for symptoms on standing",
          "Red cells 2 units to a hemoglobin above 100 g/L",
          "No transfusion now, recheck, transfuse below 70 to 80 g/L",
        ],
        correct: 4,
        explanation:
          "A restrictive strategy lowers rebleeding and death in upper GI bleeding compared with liberal transfusion. Without cardiovascular disease, guidelines use a threshold of about 70 to 80 g/L. She is hemodynamically stable at 94 g/L. Plasma is not indicated with a normal INR.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "villanueva",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        prompt: "What acid suppression order would you write, including the drug, dose and route?",
        accept: [
          { id: "panto80", text: "Pantoprazole 80 mg IV bolus, then 8 mg/h infusion or 40 mg IV twice daily", match: ["pantoprazole 80", "esomeprazole 80", "80 mg iv", "pantoprazole 40 mg iv"] },
        ],
        unacceptable: [
          { text: "H2 receptor antagonist such as famotidine", match: ["famotidine"], },
          { text: "Ranitidine", match: ["ranitidine"], },
          { text: "Oral PPI in the ED", match: ["pantoprazole 40 mg po"], },
        ],
        explanation:
          "High dose IV PPI before endoscopy may downstage the lesion. After endoscopic therapy of a high risk ulcer, high dose PPI reduces rebleeding. Either continuous infusion or intermittent high dose IV dosing is acceptable. H2 blockers do not work in this setting.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "acg-ugib",
      },
      {
        id: "q4",
        kind: "single",
        update: "Her Glasgow Blatchford score is 11.",
        prompt: "Which of the following is the most appropriate disposition for her?",
        options: [
          "Abdominal CT angiography now",
          "Admit for endoscopy within 24 hours",
          "Admit to ICU for an octreotide infusion",
          "Discharge with outpatient endoscopy within one week",
          "Emergency endoscopy within 2 hours",
        ],
        correct: 1,
        explanation:
          "Urea 14.2 mmol/L scores 4, hemoglobin below 100 g/L in a woman scores 6 and melena scores 1, for a total of 11. Only a score of 0 or 1 identifies very low risk patients for outpatient care. Endoscopy within 24 hours is recommended for admitted patients. Earlier endoscopy within 6 hours has not improved outcomes in stable patients.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "icg",
      },
    ],
    sources: [S.icg, S.villanueva, S.acgUgib],
    ...META,
  },
  {
    id: "gi-bleed-03",
    topic: "gi-bleed",
    alsoTopics: ["loc"],
    title: "Collapse in the bathroom",
    stem:
      "A 79-year-old man fainted on the bathroom floor at 0600 and woke within a minute. He has no chest pain, abdominal pain or vomiting. He has atrial fibrillation on apixaban 5 mg twice daily and takes over the counter ibuprofen for back pain. His usual systolic BP is in the 140s. Capillary glucose is 6.8 mmol/L. His conjunctivae are pale. ECG shows atrial fibrillation at 108 with no acute ischemic change.",
    vitals: { temperature: "36.7°C", pulse: "108/minute irregular", resp: "18/minute", bp: "98/58 mmHg", o2sat: "97% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What serious causes of his syncope must you consider?",
        accept: [
          { id: "gi", text: "Occult gastrointestinal bleeding", match: ["gi", "gastrointestinal", "ulcer", "blood loss", "melena", "peptic"] },
          { id: "arr", text: "Arrhythmia such as heart block or ventricular tachycardia", match: ["arrhythmia", "dysrhythmia", "ventricular tachycardia", "heart block"] },
          { id: "pe", text: "Pulmonary embolism", match: ["pulmonary embolism"] },
          { id: "aaa", text: "Ruptured abdominal aortic aneurysm", match: ["aneurysm", "aaa"] },
          { id: "acs", text: "Acute coronary syndrome", match: ["coronary", "myocardial infarction"] },
          { id: "as", text: "Aortic stenosis", match: ["aortic stenosis"] },
          { id: "dissect", text: "Aortic dissection", match: ["dissection"] },
          { id: "retro", text: "Retroperitoneal hemorrhage", match: ["retroperitoneal"] },
        ],
        explanation:
          "Syncope with tachycardia, relative hypotension and pallor in an anticoagulated patient taking NSAIDs is occult hemorrhage until proven otherwise. GI bleeding often presents without GI symptoms, especially in older adults. Arrhythmia, PE and a ruptured AAA are the other must not miss causes.",
        keyFeature: { topic: "gi-bleed", n: 3 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 1,
        prompt: "What bedside examination is most likely to confirm the leading diagnosis quickly?",
        accept: [
          { id: "dre", text: "Digital rectal examination for melena", match: ["rectal", "dre", "melena"] },
        ],
        explanation:
          "A rectal examination showing melena confirms upper GI bleeding in seconds. It should be part of the assessment of any unexplained syncope, anemia or shock. A normal stool colour does not exclude a bleed that has not yet reached the rectum.",
        keyFeature: { topic: "gi-bleed", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "Rectal examination shows black tarry stool. Hemoglobin 71 g/L (130 g/L three months ago), urea 21 mmol/L, creatinine 110 micromol/L, INR 1.3. His last apixaban dose was 3 hours ago. BP falls to 86/52 mmHg despite 1 L of Ringer's lactate.",
        prompt: "What management steps are specific to his anticoagulant and his bleeding?",
        accept: [
          { id: "hold", text: "Hold apixaban", match: ["hold apixaban", "stop apixaban", "discontinue apixaban", "hold anticoagulant", "stop anticoagulant", "hold anticoagulation", "stop anticoagulation", "discontinue anticoagulation"] },
          { id: "pcc", text: "Reverse with prothrombin complex concentrate 50 units/kg (maximum 3000 units) or a fixed 2000 units, or andexanet where available", match: ["prothrombin complex", "pcc", "octaplex", "beriplex", "andexanet"] },
          { id: "rbc", text: "Transfuse red blood cells", match: ["transfuse", "transfusion", "prbc", "red cell", "red blood cell"] },
          { id: "ppi", text: "IV pantoprazole", match: ["pantoprazole", "ppi", "proton pump", "esomeprazole"] },
          { id: "endo", text: "Urgent gastroenterology consult for endoscopy", match: ["endoscopy", "gastroenterology"] },
          { id: "nsaid", text: "Stop NSAIDs", match: ["stop ibuprofen", "stop nsaid", "hold ibuprofen", "hold nsaid", "discontinue ibuprofen", "discontinue nsaid", "avoid nsaid", "no more ibuprofen"] },
        ],
        unacceptable: [
          { text: "Idarucizumab, which reverses only dabigatran", match: ["idarucizumab"], },
          { text: "Protamine", match: ["protamine"], },
          { text: "Frozen plasma", match: ["plasma", "ffp"], },
          { text: "Vitamin K to reverse apixaban", match: ["vitamin k"], },
        ],
        explanation:
          "Hold the drug, transfuse, start IV PPI and arrange early endoscopy. The ACG and CAG guideline suggests against routine reversal in GI bleeding, but shock despite fluid, a hemoglobin of 71 g/L and a factor Xa inhibitor taken 3 hours ago make this life threatening bleeding that justifies it. Thrombosis Canada suggests PCC 50 units/kg (maximum 3000 units) or a fixed 2000 units, or andexanet where available. Idarucizumab, vitamin K, protamine and plasma do not reverse apixaban.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "tc-doac",
      },
    ],
    sources: [S.rosen, S.tcDoac],
    ...META,
  },
  {
    id: "gi-bleed-04",
    topic: "gi-bleed",
    alsoTopics: ["shock"],
    title: "Large volume rectal bleeding in a young man",
    stem:
      "A 45-year-old man has passed three large maroon and red stools with clots over 2 hours. He feels faint. He has taken ibuprofen 800 mg three times daily for three weeks for a back injury. He has no abdominal pain. He is pale and diaphoretic. Hemoglobin 82 g/L, urea 19.8 mmol/L, creatinine 84 micromol/L, INR 1.1.",
    vitals: { pulse: "126/minute", resp: "22/minute", bp: "86/52 mmHg", o2sat: "97% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features suggest an upper GI source for this bleeding?",
        accept: [
          { id: "shock", text: "Hemodynamic instability or shock with hematochezia", match: ["shock", "hypotension", "tachycardia", "hemodynamic", "unstable"] },
          { id: "urea", text: "Elevated urea or high urea to creatinine ratio", match: ["urea", "bun"] },
          { id: "nsaid", text: "Heavy NSAID use", match: ["nsaid", "ibuprofen", "anti inflammatory"] },
        ],
        unacceptable: [
          { text: "Absence of hematemesis excludes an upper source", match: ["no hematemesis"], },
        ],
        explanation:
          "About one in ten patients with severe hematochezia has an upper source. Shock with rectal bleeding, a raised urea from digested blood, and NSAID use all point upward. The absence of hematemesis does not exclude a duodenal ulcer.",
        keyFeature: { topic: "gi-bleed", n: 2 },
        source: "acg-lgib",
      },
      {
        id: "q2",
        kind: "single",
        update: "Resuscitation is under way.",
        prompt: "Which of the following is the most appropriate first diagnostic procedure?",
        options: [
          "Flexible sigmoidoscopy",
          "Nasogastric lavage",
          "Tagged red blood cell scan",
          "Upper endoscopy",
          "Urgent colonoscopy",
        ],
        correct: 3,
        explanation:
          "With shock, a urea to creatinine ratio well above 100 (19.8 mmol/L against 0.084 mmol/L) and heavy NSAID use, the most likely source is a bleeding duodenal ulcer. The ACG guideline advises upper endoscopy first when hematochezia with instability suggests an upper source. The BSG favours CT angiography first for unstable lower GI bleeding when an upper source is not suspected, and CTA is a reasonable next step if the upper endoscopy is negative. A negative nasogastric aspirate does not exclude a duodenal source.",
        keyFeature: { topic: "gi-bleed", n: 2 },
        source: "acg-lgib",
      },
      {
        id: "q3",
        kind: "single",
        update: "The blood bank says crossmatched blood will take 45 minutes.",
        prompt: "Which of the following is the most appropriate product to give immediately?",
        options: [
          "Albumin 5% 500 mL IV",
          "Frozen plasma 4 units first",
          "Normal saline 2 L, then reassess",
          "Uncrossmatched group O red cells now",
          "Wait for crossmatched red cells",
        ],
        correct: 3,
        explanation:
          "In hemorrhagic shock, give uncrossmatched group O red cells rather than waiting. For an adult man, O positive red cells are acceptable and conserve O negative stock. Colloid and large crystalloid volumes add no oxygen carrying capacity and dilute clotting factors.",
        keyFeature: { topic: "shock", n: 3 },
        source: "cbs",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Upper endoscopy shows a 1.5 cm posterior duodenal bulb ulcer with active spurting. Endoscopic therapy fails to stop the bleeding.",
        prompt: "What are the next options for definitive hemostasis?",
        accept: [
          { id: "tae", text: "Transcatheter arterial embolization by interventional radiology", match: ["embolization", "interventional radiology", "angiography"] },
          { id: "surg", text: "Surgery to oversew the ulcer", match: ["surgery", "surgical", "laparotomy"] },
          { id: "otsc", text: "Over the scope clip or repeat endoscopic therapy", match: ["over the scope", "repeat endoscopy", "hemostatic powder"] },
        ],
        explanation:
          "When endoscopic therapy fails, transcatheter arterial embolization is usually preferred over surgery because it has lower morbidity. Surgery remains the option when embolization is unavailable or fails. Posterior duodenal ulcers erode the gastroduodenal artery, which explains the brisk bleeding.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "icg",
      },
    ],
    sources: [S.acgLgib, S.cbs, S.icg],
    ...META,
  },
  {
    id: "gi-bleed-05",
    topic: "gi-bleed",
    title: "Blood in the vomit after a cold",
    stem:
      "A 34-year-old woman woke at 0400 and vomited dark red clots once. She has had a cold for four days and had a nosebleed the evening before that stopped with pressure. She takes no medications and drinks rarely. Hemoglobin 136 g/L.",
    vitals: { pulse: "88/minute", resp: "16/minute", bp: "124/78 mmHg", o2sat: "99% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What areas would you examine to look for a source outside the GI tract?",
        accept: [
          { id: "nose", text: "Nose and nasal septum with a speculum and good light", match: ["nose", "nasal", "septum"] },
          { id: "pharynx", text: "Posterior pharynx and oropharynx", match: ["pharynx", "nasopharynx", "oropharynx", "throat"] },
          { id: "mouth", text: "Mouth, teeth and gums", match: ["mouth", "gum", "teeth"] },
          { id: "lung", text: "Lungs by auscultation", match: ["lung", "chest"] },
        ],
        explanation:
          "Swallowed blood from the nose, pharynx or mouth can be vomited and can look like hematemesis or cause melena. Hemoptysis can also be confused with hematemesis. A focused ENT and chest exam avoids an unnecessary endoscopy and finds the real source.",
        keyFeature: { topic: "gi-bleed", n: 4 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What features would favour hemoptysis over hematemesis?",
        accept: [
          { id: "froth", text: "Bright red and frothy", match: ["frothy", "foamy"] },
          { id: "cough", text: "Coughed up rather than vomited", match: ["cough", "coughed", "coughing"] },
          { id: "sputum", text: "Mixed with sputum", match: ["sputum"] },
          { id: "alk", text: "Alkaline pH", match: ["alkaline"] },
          { id: "dysp", text: "Dyspnea or respiratory symptoms", match: ["dyspnea", "shortness of breath", "respiratory"] },
          { id: "nonaus", text: "No nausea or vomiting", match: ["no nausea"] },
          { id: "lungdz", text: "Known lung disease such as bronchiectasis, TB or cancer", match: ["lung disease", "tuberculosis", "bronchiectasis"] },
        ],
        unacceptable: [
          { text: "Coffee ground appearance", match: ["coffee ground"], },
          { text: "Contains food particles", match: ["food"], },
        ],
        explanation:
          "Hemoptysis is usually bright red, frothy, alkaline and coughed up with sputum. Hematemesis is often dark or coffee ground, acidic, may contain food and follows nausea. Getting this wrong sends the patient down the wrong pathway.",
        keyFeature: { topic: "gi-bleed", n: 4 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "Anterior rhinoscopy shows a small oozing vessel on the left anterior septum. The pharynx has a trickle of old blood. Her chest is clear.",
        prompt: "Which of the following is the most appropriate management of her bleeding?",
        options: [
          "CT of the paranasal sinuses with contrast",
          "Posterior nasal packing using an inflatable balloon catheter",
          "Pressure, vasoconstrictor, then focal silver nitrate cautery",
          "Silver nitrate cautery of both sides of the septum",
          "Urgent upper endoscopy by gastroenterology",
        ],
        correct: 2,
        explanation:
          "Her hematemesis came from swallowed blood from an anterior septal bleed. Direct pressure and a topical vasoconstrictor, then silver nitrate cautery of the bleeding point only, is appropriate. Cauterizing both sides of the septum risks perforation. With a clear ENT source and a normal hemoglobin, endoscopy is not needed.",
        keyFeature: { topic: "gi-bleed", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.rosen],
    ...META,
  },
  {
    id: "gi-bleed-06",
    topic: "gi-bleed",
    title: "Brief hematemesis in an older man with a vascular history",
    stem:
      "A 72-year-old man vomited about 200 mL of bright red blood 3 hours ago. It stopped and he now feels well. He had an open abdominal aortic aneurysm repair with a synthetic graft six years ago. He has coronary disease and takes ASA 81 mg daily. Abdomen is soft with a healed midline scar. Hemoglobin 118 g/L.",
    vitals: { pulse: "94/minute", resp: "16/minute", bp: "132/80 mmHg", o2sat: "97% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 1,
        prompt: "What is the most dangerous diagnosis you must exclude?",
        accept: [
          { id: "aef", text: "Aortoenteric fistula", match: ["aortoenteric", "aorto enteric", "aortoduodenal", "graft enteric", "fistula"] },
        ],
        explanation:
          "Any GI bleed in a patient with an aortic graft is an aortoenteric fistula until proven otherwise. A self limited herald bleed often precedes exsanguination by hours to days. The usual site is the third or fourth part of the duodenum.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate next investigation?",
        options: [
          "Abdominal ultrasound of the aortic graft",
          "CT angiography of the abdomen and pelvis",
          "Tagged red blood cell nuclear scan",
          "Upper endoscopy tomorrow morning",
          "Upright abdominal radiograph",
        ],
        correct: 1,
        explanation:
          "CT angiography can show loss of the fat plane between graft and bowel, perigraft gas or fluid, and contrast extravasation. It should be done promptly with vascular surgery aware. Endoscopy is often also done, but a next day scope is too slow for a possible herald bleed.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What other actions would you take now while awaiting imaging?",
        accept: [
          { id: "vasc", text: "Consult vascular surgery now", match: ["vascular surgery", "vascular surgeon"] },
          { id: "xm", text: "Group and crossmatch several units", match: ["crossmatch", "type and screen", "massive"] },
          { id: "iv", text: "Two large bore IV lines", match: ["large bore", "two iv", "2 iv", "two peripheral", "intraosseous"] },
          { id: "monitor", text: "Monitored bed with close observation", match: ["monitored", "cardiac monitor", "telemetry"] },
          { id: "transfer", text: "Arrange transfer to a centre with vascular surgery if not available", match: ["transfer"] },
          { id: "gi", text: "Notify gastroenterology for endoscopy", match: ["gastroenterology"] },
        ],
        unacceptable: [
          { text: "Discharge because the bleeding has stopped", match: ["discharge"], dangerous: true },
        ],
        explanation:
          "A herald bleed can be followed by massive hemorrhage without warning. Prepare blood, secure access and involve vascular surgery early. Transfer to a vascular centre if needed. Discharging this patient could be fatal.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "rosen",
      },
    ],
    sources: [S.rosen],
    ...META,
  },
  {
    id: "gi-bleed-07",
    topic: "gi-bleed",
    alsoTopics: ["chest-pain"],
    title: "Streaks of blood after a night out",
    stem:
      "A 26-year-old man vomited six times after binge drinking at a party. The last two vomits had streaks of bright red blood and one small coffee ground emesis. He now feels well apart from a sore throat. He takes no medications. His pulse and BP are the same lying and standing. Rectal exam shows brown stool. Hemoglobin 152 g/L, urea 5.1 mmol/L, creatinine 76 micromol/L.",
    vitals: { pulse: "84/minute", resp: "14/minute", bp: "128/76 mmHg", o2sat: "99% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 1,
        prompt: "What is the most likely diagnosis?",
        accept: [
          { id: "mw", text: "Mallory Weiss tear", match: ["mallory", "weiss", "mucosal tear", "gastroesophageal junction"] },
        ],
        unacceptable: [
          { text: "Esophageal varices", match: ["varice"], },
        ],
        explanation:
          "Repeated retching followed by hematemesis is the classic history of a Mallory Weiss tear. Most stop bleeding on their own. Varices are unlikely in a young man with no stigmata of liver disease.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is his Glasgow Blatchford score based on these findings?",
        options: ["0", "1", "2", "3", "6"],
        correct: 0,
        explanation:
          "Urea below 6.5 mmol/L, hemoglobin at least 130 g/L in a man, systolic BP at least 110, HR below 100, and no melena, syncope, liver disease or heart failure all score zero. The score predicts the need for transfusion, endoscopic therapy or surgery.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "blatchford",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate disposition for him?",
        options: [
          "Admit for endoscopy within 24 hours",
          "Discharge with advice and outpatient follow up",
          "Emergency endoscopy tonight",
          "IV pantoprazole infusion and admit",
          "Observe for 24 hours with serial hemoglobin",
        ],
        correct: 1,
        explanation:
          "A Glasgow Blatchford score of 0 or 1 identifies patients at very low risk of needing intervention or dying, and they can be managed as outpatients. The score outperforms other tools for this purpose. Admission adds cost and risk without benefit.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "stanley",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "He asks whether the vomiting could have caused a more serious injury.",
        prompt: "What findings would suggest esophageal perforation?",
        accept: [
          { id: "cp", text: "Severe chest pain", match: ["chest pain", "retrosternal", "abdominal pain", "swallowing"] },
          { id: "emph", text: "Subcutaneous emphysema or crepitus in the neck", match: ["emphysema", "crepitus", "hamman"] },
          { id: "pneumo", text: "Pneumomediastinum on chest radiograph", match: ["pneumomediastinum"] },
          { id: "effusion", text: "Pleural effusion, usually left", match: ["effusion"] },
          { id: "fever", text: "Fever", match: ["fever", "tachycardia", "sepsis"] },
          { id: "dysp", text: "Dyspnea", match: ["dyspnea", "shortness of breath"] },
        ],
        explanation:
          "Boerhaave syndrome is a transmural tear from forceful vomiting. It presents with severe chest or upper abdominal pain, subcutaneous emphysema, pleural effusion and rapid progression to sepsis. His absence of pain and normal vitals is reassuring, and these are the return precautions to give him.",
        keyFeature: { topic: "chest-pain", n: 1 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.blatchford, S.stanley],
    ...META,
  },
  {
    id: "gi-bleed-08",
    topic: "gi-bleed",
    alsoTopics: ["airway"],
    title: "Collapse with hematemesis in a young woman",
    stem:
      "A 31-year-old woman with a known duodenal ulcer stopped her PPI two months ago. Tonight she vomited a large amount of blood at home and fainted. She smokes and does not drink alcohol. There is no history of liver disease. She is cool and mottled, GCS 13.",
    vitals: { pulse: "138/minute", resp: "28/minute", bp: "72/40 mmHg", o2sat: "94% on room air", weight: "58 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following red cell products is most appropriate for her right now?",
        options: [
          "Albumin 25% while awaiting blood",
          "Fully crossmatched red cells in 45 minutes",
          "Group specific red cells in 15 minutes",
          "Uncrossmatched O negative red cells",
          "Uncrossmatched O positive red cells",
        ],
        correct: 3,
        explanation:
          "She is in hemorrhagic shock and cannot wait for crossmatched blood. Females of childbearing potential should receive O negative red cells to avoid RhD alloimmunization and later hemolytic disease of the fetus and newborn. Switch to group specific, then crossmatched blood as soon as it is available.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "cbs",
      },
      {
        id: "q2",
        kind: "short",
        required: 4,
        prompt: "What blood tests would you send now?",
        accept: [
          { id: "xm", text: "Group and crossmatch", match: ["crossmatch", "cross match", "type and screen", "type and cross", "group and screen"] },
          { id: "cbc", text: "CBC", match: ["cbc", "hemoglobin", "platelet"] },
          { id: "inr", text: "INR and PTT", match: ["inr", "ptt", "coagulation"] },
          { id: "fib", text: "Fibrinogen", match: ["fibrinogen"] },
          { id: "lactate", text: "Lactate", match: ["lactate", "blood gas"] },
          { id: "urea", text: "Urea and creatinine", match: ["urea", "creatinine", "electrolyte"] },
          { id: "hcg", text: "Beta hCG", match: ["hcg", "pregnancy"] },
          { id: "ca", text: "Ionized calcium", match: ["calcium"] },
          { id: "liver", text: "Liver enzymes and bilirubin", match: ["liver"] },
        ],
        explanation:
          "Crossmatch is the most time critical test. Baseline hemoglobin, platelets, INR and fibrinogen guide product replacement. Lactate tracks perfusion and urea supports an upper source. A pregnancy test matters in any woman of childbearing age in shock.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "cbs",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        prompt: "Which of the following medications are indicated for her before endoscopy?",
        options: [
          "Ceftriaxone 1 g IV daily",
          "Desmopressin 0.3 mcg/kg IV",
          "Erythromycin 250 mg IV about 30 to 120 minutes before",
          "Octreotide 50 mcg IV bolus, then 50 mcg/h",
          "Pantoprazole 80 mg IV bolus",
          "Pantoprazole 40 mg PO",
          "Tranexamic acid 1 g IV, then 3 g infusion",
          "Vitamin K 10 mg IV once",
        ],
        correct: [2,  4],
        explanation:
          "IV PPI is standard for suspected ulcer bleeding. IV erythromycin about 30 to 120 minutes before endoscopy clears the stomach of blood, improves the view and reduces the need for repeat endoscopy. High dose tranexamic acid did not reduce death and increased venous thrombosis in the HALT-IT trial. Octreotide and ceftriaxone are for suspected variceal bleeding in cirrhosis.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "icg",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "After 3 units of red cells her GCS falls to 10 and she vomits blood again. You decide to intubate before endoscopy.",
        prompt: "What measures would reduce the risk of aspiration or cardiovascular collapse during intubation?",
        accept: [
          { id: "resus", text: "Resuscitate with blood before induction", match: ["blood before", "transfuse before", "resuscitate before", "transfuse prior", "resuscitate prior", "blood prior", "resuscitation before", "resuscitation prior"] },
          { id: "ketamine", text: "Hemodynamically stable induction agent such as ketamine", match: ["ketamine", "etomidate", "reduced dose"] },
          { id: "pressor", text: "Push dose or infusion vasopressor ready", match: ["push dose", "vasopressor", "norepinephrine", "phenylephrine"] },
          { id: "suction", text: "Two large bore rigid suction catheters ready", match: ["suction"] },
          { id: "headup", text: "Head up or reverse Trendelenburg position", match: ["head up", "reverse trendelenburg"] },
          { id: "ng", text: "Nasogastric tube to decompress the stomach", match: ["nasogastric"] },
          { id: "vl", text: "Video laryngoscope and the most experienced operator", match: ["video"] },
          { id: "preox", text: "Preoxygenate well", match: ["preoxygenate", "preoxygenation", "pre oxygenate", "pre oxygenation"] },
        ],
        unacceptable: [
          { text: "Full dose propofol", match: ["full dose propofol"], },
        ],
        explanation:
          "Massive hematemesis makes this a physiologically and anatomically difficult airway. Resuscitate before induction, use a hemodynamically stable agent at reduced dose, and have a vasopressor ready. Position head up, have two suction catheters, and use the most experienced operator.",
        keyFeature: { topic: "airway", n: 4 },
        source: "rosen",
      },
      {
        id: "q5",
        kind: "short",
        required: 3,
        update: "She has now received 6 units of red cells, 4 units of plasma and a dose of platelets.",
        prompt: "What complications of massive transfusion would you monitor and treat?",
        accept: [
          { id: "ca", text: "Hypocalcemia from citrate", match: ["hypocalcemia", "calcium"] },
          { id: "cold", text: "Hypothermia", match: ["hypothermia"] },
          { id: "coag", text: "Dilutional coagulopathy", match: ["coagulopathy", "thrombocytopenia"] },
          { id: "k", text: "Hyperkalemia", match: ["hyperkalemia"] },
          { id: "acid", text: "Acidosis", match: ["acidosis"] },
          { id: "taco", text: "Transfusion associated circulatory overload", match: ["taco", "overload"] },
          { id: "trali", text: "Transfusion related acute lung injury", match: ["trali", "lung injury"] },
          { id: "rxn", text: "Hemolytic or allergic transfusion reaction", match: ["reaction"] },
        ],
        explanation:
          "Citrate binds calcium, and hypocalcemia worsens coagulopathy and contractility. Cold products cause hypothermia unless a warmer is used. Stored red cells release potassium. Dilution of clotting factors and platelets, TACO and TRALI are the other key complications.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "cbs",
      },
    ],
    sources: [S.cbs, S.icg, S.rosen],
    ...META,
  },
  {
    id: "gi-bleed-09",
    topic: "gi-bleed",
    title: "Maroon stools in a toddler",
    stem:
      "A 2-year-old boy is brought in after two large maroon stools in the past 3 hours. He has had no abdominal pain, vomiting or fever and was playing normally until today. He looks pale. Capillary refill is 3 seconds. His abdomen is soft and non tender. Hemoglobin 76 g/L.",
    vitals: { pulse: "164/minute", resp: "30/minute", bp: "84/50 mmHg", weight: "12 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 1,
        prompt: "What is the most likely diagnosis?",
        accept: [
          { id: "meckel", text: "Meckel diverticulum", match: ["meckel"] },
        ],
        unacceptable: [
          { text: "Intussusception", match: ["intussusception"], },
          { text: "Anal fissure", match: ["fissure"], },
        ],
        explanation:
          "Painless large volume bleeding in a toddler is classic for a Meckel diverticulum. Ectopic gastric mucosa secretes acid and ulcerates adjacent ileum. Intussusception is usually painful with intermittent crying and vomiting. A fissure causes small streaks of blood, not shock.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What initial resuscitation orders would you give, including volumes for any fluid or blood product?",
        accept: [
          { id: "rbc10", text: "Red cells 10 to 15 mL/kg (about 120 to 180 mL)", match: ["10 ml/kg red", "15 ml/kg red", "10 ml/kg prbc", "15 ml/kg prbc", "10 ml/kg blood", "15 ml/kg blood", "10 ml/kg rbc", "15 ml/kg rbc", "10 cc/kg", "15 cc/kg", "120 ml red", "150 ml red", "180 ml red", "120 ml prbc", "150 ml prbc", "180 ml prbc", "120 ml blood", "150 ml blood", "180 ml blood"] },
          { id: "ns", text: "Crystalloid bolus 10 to 20 mL/kg while blood is prepared", match: ["20 ml/kg saline", "20 ml/kg crystalloid", "20 ml/kg ringer", "10 ml/kg saline", "10 ml/kg crystalloid"] },
          { id: "access", text: "IV or intraosseous access", match: ["intraosseous", "io", "iv access", "peripheral iv", "large bore"] },
          { id: "xm", text: "Group and crossmatch", match: ["crossmatch"] },
        ],
        unacceptable: [
          { text: "Fluid bolus of 60 mL/kg before blood", match: ["60 ml/kg"], },
        ],
        explanation:
          "He is in compensated hemorrhagic shock, tachycardic with delayed capillary refill but a systolic BP still above the cutoff for age of about 74. Give red cells 10 to 15 mL/kg early. A crystalloid bolus of 10 to 20 mL/kg can bridge until blood arrives, but large crystalloid volumes should be avoided. Use intraosseous access if IV access is slow.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following investigations would best confirm the suspected diagnosis?",
        options: [
          "Abdominal ultrasound",
          "Air contrast enema",
          "Colonoscopy under sedation",
          "Plain abdominal radiograph",
          "Technetium 99m pertechnetate scan",
        ],
        correct: 4,
        explanation:
          "Pertechnetate is taken up by ectopic gastric mucosa, which is present in most bleeding Meckel diverticula. A negative scan does not fully exclude it, and pediatric surgery may proceed to laparoscopy when suspicion is high. Ultrasound and enema are the tests for intussusception.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },
  {
    id: "gi-bleed-10",
    topic: "gi-bleed",
    alsoTopics: ["delirium-agitation"],
    title: "Confusion in a nursing home resident",
    stem:
      "An 84-year-old woman is sent from her long term care home with two days of increasing confusion and fatigue. She fell yesterday without injury. Staff report no vomiting or complaints of pain. She has mild dementia, atrial fibrillation on dabigatran 110 mg twice daily, chronic kidney disease (eGFR 38 mL/min) and osteoarthritis. Her usual BP is 150/80 mmHg. Capillary glucose is 7.2 mmol/L. She is inattentive and oriented only to person.",
    vitals: { temperature: "36.8°C", pulse: "104/minute", resp: "20/minute", bp: "102/60 mmHg", o2sat: "96% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 4,
        prompt: "What investigations would you order to look for the cause of her delirium?",
        accept: [
          { id: "cbc", text: "CBC with hemoglobin", match: ["cbc", "hemoglobin"] },
          { id: "lytes", text: "Electrolytes including sodium", match: ["electrolyte", "sodium"] },
          { id: "cr", text: "Urea and creatinine", match: ["creatinine", "urea"] },
          { id: "ca", text: "Calcium", match: ["calcium"] },
          { id: "ua", text: "Urinalysis", match: ["urinalysis"] },
          { id: "cxr", text: "Chest radiograph", match: ["chest"] },
          { id: "ecg", text: "ECG", match: ["ecg"] },
          { id: "trop", text: "Troponin", match: ["troponin"] },
          { id: "ct", text: "CT head, given the fall on an anticoagulant", match: ["ct head"] },
          { id: "coag", text: "INR, PTT or thrombin time", match: ["ptt", "inr", "thrombin time"] },
          { id: "cx", text: "Blood cultures", match: ["culture"] },
          { id: "lactate", text: "Lactate or blood gas", match: ["lactate"] },
          { id: "liver", text: "Liver enzymes", match: ["liver"] },
          { id: "tsh", text: "TSH", match: ["tsh"] },
        ],
        explanation:
          "Delirium in an older adult has a broad differential. Infection, electrolyte disorders, drugs, ischemia and intracranial bleeding after a fall on an anticoagulant are all important. Anemia from occult bleeding is easy to miss when no GI symptoms are reported.",
        keyFeature: { topic: "delirium-agitation", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "Hemoglobin is 64 g/L (118 g/L three months ago). Urea 24.6 mmol/L, creatinine 131 micromol/L. CT head is normal.",
        prompt: "What findings in this case point to an upper GI bleed as the cause?",
        accept: [
          { id: "urea", text: "Urea raised out of proportion to creatinine", match: ["urea", "bun"] },
          { id: "hb", text: "Large fall in hemoglobin from baseline", match: ["hemoglobin", "anemia"] },
          { id: "anticoag", text: "Anticoagulant use", match: ["anticoagulant", "dabigatran"] },
          { id: "bp", text: "Blood pressure well below her baseline with tachycardia", match: ["blood pressure", "hypotension", "tachycardia"] },
          { id: "nsaid", text: "Possible NSAID use for osteoarthritis", match: ["nsaid"] },
        ],
        explanation:
          "A urea to creatinine ratio well above baseline suggests blood being digested in the upper GI tract. Anticoagulation, a large drop in hemoglobin and relative hypotension complete the picture. Older patients with occult bleeding often present only with confusion, falls or fatigue.",
        keyFeature: { topic: "gi-bleed", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "Rectal exam shows melena. Her BP falls to 84/50 mmHg after the first unit of red cells. Her last dabigatran dose was 5 hours ago.",
        prompt: "Which of the following reversal strategies is most appropriate for her now?",
        options: [
          "Four factor PCC 50 units/kg IV",
          "Frozen plasma 15 mL/kg",
          "Idarucizumab 5 g IV",
          "Urgent hemodialysis",
          "Vitamin K 10 mg IV",
        ],
        correct: 2,
        explanation:
          "Idarucizumab 5 g IV rapidly and specifically reverses dabigatran and is indicated for life threatening bleeding. Her renal impairment prolongs dabigatran clearance, which makes reversal more important. PCC is a second line option only if idarucizumab is unavailable. Dialysis removes dabigatran but is slow to arrange in an unstable patient.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "pollack",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What do you need to establish about her care wishes before planning endoscopy?",
        accept: [
          { id: "sdm", text: "Identify her substitute decision maker", match: ["substitute decision maker", "sdm", "power of attorney"] },
          { id: "ad", text: "Advance directive", match: ["advance directive", "goals of care", "code status", "level of care"] },
          { id: "cap", text: "Whether she has capacity to consent", match: ["capacity", "consent"] },
        ],
        explanation:
          "Delirium means she likely lacks capacity for endoscopy and transfusion decisions right now. Find her substitute decision maker and any documented wishes or level of care. Many long term care residents have clear goals that should shape the intensity of treatment.",
        keyFeature: { topic: "delirium-agitation", n: 5 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.pollack],
    ...META,
  },
  {
    id: "gi-bleed-11",
    topic: "gi-bleed",
    title: "Melena in a man with known liver disease",
    stem:
      "A 55-year-old man with alcohol related cirrhosis and known esophageal varices has had melena for 24 hours and one coffee ground emesis. He stopped his propranolol a month ago. He is mildly confused with asterixis. Hemoglobin 78 g/L, platelets 62 x 10^9/L, INR 1.9, bilirubin 58 micromol/L, albumin 26 g/L, creatinine 98 micromol/L, sodium 131 mmol/L. His abdomen is mildly distended with shifting dullness.",
    vitals: { temperature: "36.9°C", pulse: "102/minute", resp: "18/minute", bp: "104/64 mmHg", o2sat: "96% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        update: "The admitting resident plans to transfuse to a hemoglobin of 100 g/L and give frozen plasma to correct the INR.",
        prompt: "Why do you disagree with this plan?",
        accept: [
          { id: "portal", text: "Over transfusion raises portal pressure and increases rebleeding", match: ["portal pressure", "volume"] },
          { id: "rebleed", text: "Liberal transfusion increases rebleeding and death", match: ["rebleeding", "rebleed"] },
          { id: "restrict", text: "A restrictive threshold of about 70 g/L with a target of 70 to 90 g/L improves survival", match: ["restrictive", "70"] },
          { id: "inr", text: "The INR does not reflect bleeding risk in cirrhosis", match: ["inr not", "inr unreliable", "rebalanced"] },
          { id: "trali", text: "Plasma risks TACO and TRALI without benefit", match: ["trali", "taco"] },
        ],
        explanation:
          "In variceal bleeding a restrictive strategy, transfusing at about 70 g/L, reduced rebleeding and death. Extra volume raises portal pressure. The INR measures only procoagulant factors and does not predict bleeding in cirrhosis. Baveno VII advises against plasma to correct it.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "baveno",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What medications would you start now, including the dose of each?",
        accept: [
          { id: "oct", text: "Octreotide 50 mcg IV bolus, then 50 mcg/h", match: ["octreotide 50 mcg", "octreotide 50 microgram", "octreotide 50 ug", "octreotide 50 mcg/h"] },
          { id: "cef", text: "Ceftriaxone 1 g IV daily", match: ["ceftriaxone 1 g", "ceftriaxone 1000"] },
          { id: "ppi", text: "Pantoprazole 80 mg IV until endoscopy defines the source", match: ["pantoprazole 80", "pantoprazole 40", "esomeprazole 80", "esomeprazole 40"] },
          { id: "ery", text: "Erythromycin 250 mg IV before endoscopy", match: ["erythromycin 250"] },
          { id: "lact", text: "Lactulose 20 to 30 mL PO or by nasogastric tube, titrated to stools", match: ["lactulose"] },
          { id: "thia", text: "Thiamine 100 to 500 mg IV", match: ["thiamine"] },
        ],
        unacceptable: [
          { text: "Restart propranolol now", match: ["propranolol"], },
          { text: "Beta blocker", match: ["beta blocker"], },
          { text: "Tranexamic acid", match: ["tranexamic"], },
          { text: "TXA", match: ["txa"], },
        ],
        explanation:
          "Start octreotide and ceftriaxone as soon as variceal bleeding is suspected and continue octreotide for 2 to 5 days and ceftriaxone for up to 7 days. A PPI is reasonable until endoscopy excludes an ulcer. Lactulose treats his encephalopathy. Beta blockers are held during acute bleeding and restarted once the vasoactive drug stops.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "baveno",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "Apart from the bleed itself, what precipitants of his encephalopathy would you look for?",
        accept: [
          { id: "sbp", text: "Spontaneous bacterial peritonitis, by diagnostic paracentesis", match: ["peritonitis", "sbp"] },
          { id: "inf", text: "Other infection such as UTI or pneumonia", match: ["infection"] },
          { id: "na", text: "Hyponatremia", match: ["hyponatremia", "hypokalemia", "electrolyte"] },
          { id: "aki", text: "Acute kidney injury or dehydration", match: ["kidney", "dehydration"] },
          { id: "const", text: "Constipation", match: ["constipation"] },
          { id: "drugs", text: "Sedatives, benzodiazepines or opioids", match: ["benzodiazepine", "sedative", "opioid"] },
          { id: "glu", text: "Hypoglycemia", match: ["hypoglycemia"] },
          { id: "lactnon", text: "Stopping lactulose", match: ["lactulose", "stop lactulose", "stopped lactulose", "missed lactulose", "not taking lactulose", "no lactulose"] },
          { id: "alc", text: "Alcohol intoxication or withdrawal", match: ["alcohol", "wernicke"] },
        ],
        explanation:
          "GI bleeding is a major precipitant of hepatic encephalopathy, but infection, especially SBP, often coexists. Tap the ascites. Electrolyte disturbance, kidney injury, sedatives and constipation are other common triggers. Alcohol withdrawal and Wernicke encephalopathy can mimic it.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "baveno",
      },
      {
        id: "q4",
        kind: "single",
        update: "Endoscopy shows an actively bleeding esophageal varix, which is banded successfully. His Child Pugh score is 12 (class C).",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "Continue octreotide for 24 hours, then discharge",
          "Prophylactic balloon tamponade tube",
          "Refer for a surgical portosystemic shunt",
          "Refer for pre-emptive TIPS within 72 hours",
          "Restart propranolol 80 mg twice daily today",
        ],
        correct: 3,
        explanation:
          "Baveno VII recommends pre-emptive TIPS within 72 hours, ideally within 24, for Child Pugh C below 14 or Child Pugh B above 7 with active bleeding at endoscopy. It reduces rebleeding and death in these high risk patients. Balloon tamponade is only a rescue bridge. Beta blockers restart after the vasoactive drug stops.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "baveno",
      },
    ],
    sources: [S.baveno],
    ...META,
  },
  {
    id: "gi-bleed-12",
    topic: "gi-bleed",
    title: "Painless rectal bleeding in an older man",
    stem:
      "A 76-year-old man has had three painless bright red stools with clots today. Colonoscopy two years ago showed sigmoid diverticulosis. He takes ASA 81 mg daily for a coronary stent placed five years ago, and ramipril. Rectal exam shows fresh red blood and no visible hemorrhoidal bleeding. Hemoglobin 121 g/L (138 g/L last year), urea 6.8 mmol/L, creatinine 90 micromol/L, INR 1.0.",
    vitals: { pulse: "88/minute", resp: "16/minute", bp: "138/76 mmHg", o2sat: "97% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What are the likely sources of his bleeding?",
        accept: [
          { id: "div", text: "Diverticular bleeding", match: ["diverticular", "diverticulosis"] },
          { id: "angio", text: "Angiodysplasia", match: ["angiodysplasia", "arteriovenous", "avm"] },
          { id: "ca", text: "Colorectal cancer or polyp", match: ["cancer", "neoplasm", "polyp", "tumour"] },
          { id: "isch", text: "Ischemic colitis", match: ["ischemic"] },
          { id: "hem", text: "Hemorrhoids", match: ["hemorrhoid"] },
          { id: "upper", text: "Brisk upper GI bleeding", match: ["upper"] },
          { id: "rad", text: "Radiation proctitis", match: ["radiation"] },
          { id: "ibd", text: "Inflammatory bowel disease", match: ["inflammatory bowel"] },
        ],
        explanation:
          "Diverticular bleeding is the most common cause of major lower GI bleeding in older adults and is typically painless. Angiodysplasia and neoplasia follow. Ischemic colitis usually causes pain. A brisk upper source must always stay on the list.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "acg-lgib",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What findings, if present, would make you suspect an upper GI source instead?",
        accept: [
          { id: "shock", text: "Hemodynamic instability or shock", match: ["shock", "hypotension", "tachycardia", "unstable"] },
          { id: "urea", text: "Raised urea or urea to creatinine ratio", match: ["urea", "bun"] },
          { id: "hemat", text: "Hematemesis or coffee ground emesis", match: ["hematemesis", "coffee ground"] },
          { id: "melena", text: "Earlier melena", match: ["melena"] },
          { id: "pud", text: "History of peptic ulcer", match: ["ulcer", "nsaid"] },
          { id: "liver", text: "Liver disease or varices", match: ["liver", "cirrhosis"] },
          { id: "epig", text: "Epigastric pain or dyspepsia", match: ["epigastric", "dyspepsia"] },
        ],
        explanation:
          "Hematochezia with shock carries roughly a 10 to 15 percent chance of an upper source. A raised urea, melena, hematemesis, ulcer history, NSAIDs or liver disease all increase that chance. When present, upper endoscopy should come before lower tract evaluation.",
        keyFeature: { topic: "gi-bleed", n: 2 },
        source: "acg-lgib",
      },
      {
        id: "q3",
        kind: "single",
        update: "Two hours later he passes another large bloody stool. Pulse 118/minute, BP 92/58 mmHg. Repeat urea is 7.0 mmol/L. There is no hematemesis and no upper GI history.",
        prompt: "Which of the following is the most appropriate next investigation?",
        options: [
          "Colonoscopy tomorrow after bowel preparation",
          "CT angiography of the abdomen and pelvis",
          "Plain abdominal radiograph",
          "Tagged red blood cell nuclear scan",
          "Video capsule endoscopy",
        ],
        correct: 1,
        explanation:
          "In hemodynamically significant lower GI bleeding, CT angiography quickly localizes active bleeding and guides embolization. With no upper GI features and a normal urea, an upper source is unlikely. If CTA is negative and bleeding continues, upper endoscopy is the next step.",
        keyFeature: { topic: "gi-bleed", n: 2 },
        source: "bsg-lgib",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "CT angiography shows active contrast extravasation in the sigmoid colon.",
        prompt: "What are the next steps?",
        accept: [
          { id: "emb", text: "Transcatheter embolization by interventional radiology, ideally within an hour", match: ["embolization", "interventional radiology", "angiography"] },
          { id: "surg", text: "General surgery consult", match: ["surgery", "surgical"] },
          { id: "tx", text: "Continue red cell transfusion", match: ["transfusion", "transfuse", "crossmatch"] },
          { id: "gi", text: "Gastroenterology for colonoscopy", match: ["colonoscopy"] },
        ],
        explanation:
          "A positive CTA should prompt catheter angiography and embolization quickly while the bleeding is active. Surgery is reserved for failed embolization or ongoing instability. Keep transfusing and involve surgery early in case embolization fails.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "bsg-lgib",
      },
      {
        id: "q5",
        kind: "single",
        prompt: "Which of the following is the most appropriate plan for his ASA?",
        options: [
          "Continue, or hold briefly and resume after hemostasis",
          "Give a platelet transfusion to reverse it",
          "Hold ASA for 6 weeks, then reassess",
          "Replace ASA with clopidogrel 75 mg daily",
          "Stop ASA permanently after this bleed",
        ],
        correct: 0,
        explanation:
          "ASA for secondary cardiovascular prevention protects against thrombotic events and death. Guidelines suggest not stopping it, or resuming it as soon as hemostasis is achieved. Platelet transfusion for antiplatelet associated GI bleeding is not recommended.",
        keyFeature: { topic: "ischemic-heart-disease", n: 7 },
        source: "acg-cag",
      },
    ],
    sources: [S.acgLgib, S.bsgLgib, S.acgCag],
    ...META,
  },
  {
    id: "gi-bleed-13",
    topic: "gi-bleed",
    title: "Vomiting blood on warfarin",
    stem:
      "A 70-year-old woman on warfarin for atrial fibrillation presents with melena and one episode of hematemesis. She finished a course of trimethoprim sulfamethoxazole for a urinary tract infection three days ago. INR 6.8, hemoglobin 84 g/L, platelets 210 x 10^9/L.",
    vitals: { pulse: "118/minute", resp: "22/minute", bp: "88/56 mmHg", o2sat: "96% on arrival", weight: "70 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What factors commonly raise the INR in a patient on warfarin?",
        accept: [
          { id: "abx", text: "Antibiotics such as trimethoprim sulfamethoxazole or a fluoroquinolone", match: ["antibiotic", "trimethoprim", "septra", "ciprofloxacin", "metronidazole", "fluconazole"] },
          { id: "amio", text: "Amiodarone", match: ["amiodarone"] },
          { id: "diet", text: "Reduced dietary vitamin K or poor oral intake", match: ["diet", "intake"] },
          { id: "alc", text: "Alcohol binge", match: ["alcohol"] },
          { id: "liver", text: "Liver dysfunction or congestion", match: ["liver"] },
          { id: "illness", text: "Acute illness, fever or diarrhea", match: ["diarrhea"] },
          { id: "dose", text: "Dosing error or extra doses", match: ["dosing error", "extra dose"] },
          { id: "apap", text: "Regular acetaminophen use", match: ["acetaminophen"] },
          { id: "herbal", text: "Herbal or natural products", match: ["herbal"] },
          { id: "thyroid", text: "Hyperthyroidism", match: ["hyperthyroidism"] },
        ],
        explanation:
          "Interacting drugs, especially antibiotics like trimethoprim sulfamethoxazole, are a common cause of a high INR. Reduced intake, acute illness, alcohol and liver dysfunction also potentiate warfarin. Identifying the cause helps prevent recurrence when warfarin is restarted.",
        keyFeature: { topic: "gi-bleed", n: 1 },
        source: "tc-warfarin",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What agents would you give to reverse her anticoagulation, including the dose and route of vitamin K?",
        accept: [
          { id: "vitk", text: "Vitamin K 10 mg IV", match: ["vitamin k 10 mg iv", "vitamin k 10 mg intravenous", "vit k 10 mg iv", "phytonadione 10 mg iv", "phytonadione 10 mg intravenous"] },
          { id: "pcc", text: "Prothrombin complex concentrate dosed by INR and weight", match: ["prothrombin complex", "pcc", "octaplex", "beriplex"] },
        ],
        unacceptable: [
          { text: "Oral vitamin K", match: ["vitamin k po"], },
          { text: "Oral vitamin K", match: ["vitamin k oral"], },
          { text: "Subcutaneous vitamin K", match: ["subcutaneous"], },
          { text: "Frozen plasma as the main reversal agent", match: ["plasma"], },
          { text: "FFP", match: ["ffp"], },
          { text: "Recombinant factor VIIa", match: ["viia"], },
        ],
        explanation:
          "Shock with active bleeding and an INR of 6.8 is life threatening bleeding, so reversal is justified. Give PCC, which works in minutes in a small volume, plus vitamin K 10 mg IV to sustain the effect. Plasma is slower, needs thawing and large volumes. Oral and subcutaneous vitamin K act too slowly or unpredictably.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "tc-warfarin",
      },
      {
        id: "q3",
        kind: "single",
        update: "A colleague suggests tranexamic acid.",
        prompt: "Which of the following is the most appropriate response to this suggestion?",
        options: [
          "Give 4 g IV over 24 hours",
          "Give 1 g IV, then 1 g over 8 hours",
          "Give only if endoscopy is delayed over 24 hours",
          "Give orally after endoscopy",
          "Withhold tranexamic acid",
        ],
        correct: 4,
        explanation:
          "HALT-IT randomized about 12 000 patients with GI bleeding. High dose tranexamic acid did not reduce death from bleeding and increased venous thromboembolism and seizures. It should not be used routinely in GI bleeding.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "halt-it",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What resuscitation measures other than reversal would you order now?",
        accept: [
          { id: "iv", text: "Two large bore IV lines", match: ["large bore", "two iv", "2 iv", "two peripheral", "intraosseous"] },
          { id: "xm", text: "Group and crossmatch", match: ["crossmatch", "cross match", "type and screen", "type and cross", "group and screen"] },
          { id: "rbc", text: "Transfuse red cells", match: ["transfuse", "transfusion", "prbc", "massive"] },
          { id: "ppi", text: "IV pantoprazole", match: ["pantoprazole", "ppi", "proton pump", "esomeprazole"] },
          { id: "gi", text: "Urgent gastroenterology consult for endoscopy", match: ["endoscopy", "gastroenterology"] },
        ],
        unacceptable: [
          { text: "Large volume crystalloid to normalize blood pressure", match: ["aggressive fluid"], },
        ],
        explanation:
          "She is in shock. Reversal alone is not enough. Secure access, send crossmatch, transfuse red cells and start IV PPI while arranging endoscopy. Limit crystalloid to what is needed until blood arrives.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "tc-warfarin",
      },
    ],
    sources: [S.tcWarfarin, S.haltit],
    ...META,
  },
  {
    id: "gi-bleed-14",
    topic: "gi-bleed",
    alsoTopics: ["ischemic-heart-disease"],
    title: "Chest pressure and pallor",
    stem:
      "A 66-year-old man has had two days of chest pressure on exertion and one hour of pressure at rest. Paramedics gave ASA 160 mg chewed. He looks pale. ECG shows 1 mm horizontal ST depression in V4 to V6. High sensitivity troponin is 88 ng/L. Hemoglobin 72 g/L. No previous values are available. The resident is about to order a heparin bolus and infusion.",
    vitals: { pulse: "110/minute", resp: "20/minute", bp: "108/66 mmHg", o2sat: "96% on arrival" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What history questions would you ask to find the cause of his anemia?",
        accept: [
          { id: "melena", text: "Black or tarry stools", match: ["black", "melena", "tarry"] },
          { id: "hemat", text: "Vomiting blood or coffee grounds", match: ["hematemesis", "vomiting blood", "coffee ground"] },
          { id: "pr", text: "Rectal bleeding or hematochezia", match: ["rectal bleeding", "hematochezia", "blood in stool"] },
          { id: "nsaid", text: "NSAID use", match: ["nsaid", "anticoagulant", "antiplatelet"] },
          { id: "alc", text: "Alcohol use", match: ["alcohol"] },
          { id: "wt", text: "Weight loss or change in bowel habit", match: ["weight loss", "bowel habit"] },
          { id: "ulcer", text: "Previous ulcer or GI bleed", match: ["ulcer", "previous gi bleed"] },
          { id: "dysp", text: "Dyspepsia or epigastric pain", match: ["dyspepsia", "epigastric"] },
          { id: "last", text: "Last colonoscopy or endoscopy", match: ["colonoscopy"] },
        ],
        explanation:
          "Severe anemia can cause demand ischemia and present as angina with no GI complaints. A targeted GI history and exam may reveal an occult bleed. Missing it and starting full anticoagulation can be catastrophic.",
        keyFeature: { topic: "gi-bleed", n: 3 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "Emergent coronary angiography",
          "Heparin bolus and infusion plus ticagrelor 180 mg",
          "Hold anticoagulation, do rectal exam and GI assessment",
          "Nitroglycerin infusion and repeat troponin in 3 hours",
          "Tenecteplase IV at weight based dose",
        ],
        correct: 2,
        explanation:
          "This picture fits type 2 myocardial injury from anemia until proven otherwise. The ECG shows ST depression, not STEMI. Heparin and more antiplatelet therapy could worsen an occult bleed. Assess for GI bleeding before any antithrombotic escalation.",
        keyFeature: { topic: "gi-bleed", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "Rectal exam shows melena. BP 104/64 mmHg, pulse 108/minute. He still has chest pressure.",
        prompt: "Which of the following transfusion plans is most appropriate for him now?",
        options: [
          "Erythropoietin with IV iron instead of red cells",
          "IV iron infusion instead of red cells",
          "Transfuse red cells now, reassess, target 80 g/L or more",
          "Transfuse to a hemoglobin above 130 g/L",
          "No transfusion unless hemoglobin falls below 70 g/L",
        ],
        correct: 2,
        explanation:
          "Active myocardial ischemia raises the transfusion threshold. Guidelines for GI bleeding suggest a higher threshold, such as 80 g/L or more, in cardiovascular disease. The MINT trial compared a liberal threshold of 100 g/L with a restrictive threshold of 70 to 80 g/L in myocardial infarction with anemia and found a nonsignificant trend toward fewer deaths or reinfarctions with the liberal strategy. Transfuse one unit at a time and reassess symptoms and hemoglobin.",
        keyFeature: { topic: "gi-bleed", n: 5 },
        source: "mint",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What consultations would you request?",
        accept: [
          { id: "gi", text: "Gastroenterology for endoscopy within 24 hours", match: ["gastroenterology", "endoscopy"] },
          { id: "cards", text: "Cardiology to plan antithrombotic therapy and timing of angiography", match: ["cardiology", "cardiologist"] },
          { id: "icu", text: "Critical care or coronary care unit", match: ["icu", "ccu", "critical care"] },
        ],
        explanation:
          "He needs endoscopy to find and treat the bleeding source and cardiology input to balance ischemic and bleeding risk. Angiography is usually deferred until the bleeding is controlled. A monitored bed is appropriate while both problems are active.",
        keyFeature: { topic: "ischemic-heart-disease", n: 7 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.mint],
    ...META,
  },
  {
    id: "gi-bleed-15",
    topic: "gi-bleed",
    alsoTopics: ["shock"],
    title: "Vomiting blood while waiting for transfer",
    stem:
      "You are working in a rural hospital 3 hours by road from the nearest PCI centre, which also has endoscopy. A 64-year-old man with an anterior STEMI received tenecteplase 4 hours ago, with ASA 160 mg, clopidogrel 300 mg and an IV heparin bolus of 4 000 units. A heparin infusion of 1 000 units/hour has run since then. His chest pain has settled and the ST elevation has fallen by more than half. While he waits for transport he vomits about 400 mL of bright red blood and then passes a melena stool. He has had dyspepsia for weeks and has taken ibuprofen daily for back pain. There are fine crackles at both lung bases.",
    vitals: { pulse: "118/minute", resp: "22/minute", bp: "92/58 mmHg", o2sat: "93% on 2 L/minute by nasal prongs", weight: "88 kg" },
    questions: [
      {
        id: "q1",
        kind: "menu",
        select: 4,
        prompt: "Which of the following should he receive now to control the bleeding?",
        options: [
          "Andexanet alfa 400 mg IV bolus",
          "Cryoprecipitate 10 units IV",
          "Idarucizumab 5 g IV",
          "Octreotide 50 mcg IV bolus",
          "Pantoprazole 80 mg IV bolus",
          "Protamine 25 mg IV over 10 minutes",
          "Prothrombin complex concentrate 2 000 units IV",
          "Stop the heparin infusion",
          "Vitamin K 10 mg IV",
        ],
        correct: [1, 4, 5, 7],
        explanation:
          "His bleeding began 4 hours after tenecteplase with heparin still running, so the drugs impairing clotting must be addressed along with the likely NSAID ulcer. Stop the heparin. The NCS and SCCM reversal guideline doses protamine at 1 mg per 100 units of heparin given in the previous 2 to 3 hours, up to 50 mg. His infusion delivered 2 000 to 3 000 units in that time, so about 25 mg is right, given slowly. The same guideline gives cryoprecipitate 10 units for serious bleeding within 24 hours of a thrombolytic. It was written for intracranial hemorrhage, and its approach is applied here to a major GI bleed. Pantoprazole treats a probable ulcer while he awaits endoscopy. PCC and vitamin K reverse warfarin, andexanet reverses factor Xa inhibitors, idarucizumab reverses dabigatran, and octreotide is for variceal bleeding.",
        keyFeature: { topic: "gi-bleed", n: 6 },
        source: "ncs-reversal",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "Hemoglobin 98 g/L, platelets 210 x 10^9/L, fibrinogen 1.2 g/L. Ten minutes later he vomits again and his BP falls to 84/50 mmHg. The crackles are unchanged.",
        prompt: "What fluids would you use to resuscitate him?",
        accept: [
          { id: "rbc", text: "Red cells early, uncrossmatched if needed", match: ["red cell", "prbc", "red blood cell", "packed cell", "uncrossmatched", "transfuse", "transfusion", "blood transfusion"] },
          { id: "fib", text: "Cryoprecipitate or fibrinogen concentrate to raise fibrinogen to at least 1.5 g/L", match: ["cryoprecipitate", "cryo", "fibrinogen concentrate", "fibrinogen replacement", "replace fibrinogen"] },
          { id: "small", text: "Crystalloid only in small volumes, with reassessment for pulmonary edema", match: ["small bolus", "small volume", "250 ml", "limit crystalloid", "minimize crystalloid", "avoid large volume", "avoid crystalloid", "reassess"] },
          { id: "ca", text: "Monitor and replace ionized calcium", match: ["calcium"] },
        ],
        unacceptable: [
          { text: "Large volume crystalloid", match: ["aggressive fluid", "aggressive crystalloid", "wide open"] },
        ],
        explanation:
          "He is in hemorrhagic shock with a fibrinogen of 1.2 g/L and bibasal crackles from his infarct. Blood is the right fluid, so give red cells early and replace fibrinogen. Canadian Blood Services notes that many guidelines now recommend a fibrinogen level of at least 1.5 to 2.0 g/L during bleeding. Crystalloid carries no oxygen or clotting factors and can worsen his pulmonary edema, so use it only in small volumes with reassessment. Calcium monitoring and replacement are part of any massive hemorrhage protocol. His hemoglobin of 98 g/L does not yet reflect the blood lost.",
        keyFeature: { topic: "shock", n: 3 },
        source: "cbs",
      },
      {
        id: "q3",
        kind: "single",
        update: "After treatment his BP is 104/66 mmHg and he has had no further hematemesis. The ambulance crew has arrived.",
        prompt: "Which of the following is the most important preparation before he leaves for the PCI centre?",
        options: [
          "Insert a nasogastric tube for gastric lavage",
          "Restart heparin at half the previous rate",
          "Send blood products with a critical care escort",
          "Send with a primary care paramedic crew",
          "Wait for a repeat hemoglobin in 6 hours",
        ],
        correct: 2,
        explanation:
          "After fibrinolysis the 2019 CCS and CAIC guideline advises transfer to a PCI centre, and this one also offers endoscopy. He may rebleed during 3 hours on the road, so send red cells and cryoprecipitate with a critical care escort able to transfuse, protect the airway and treat arrhythmia. A primary care paramedic crew cannot give blood. Restarting heparin now risks renewed bleeding, and that decision belongs to the receiving cardiology and GI teams. Gastric lavage delays departure without treating the bleed. Waiting 6 hours for a hemoglobin delays both angiography and endoscopy.",
        keyFeature: { topic: "ems", n: 3 },
        source: "ccs-stemi",
      },
    ],
    sources: [S.ncsReversal, S.cbs, S.ccsStemi],
    ...META,
    reviewed: false,
    version: 2,
  },
];
