// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Preceptor", version: 1 } as const;

const S = {
  cafg: { id: "cafg", citation: "Law JA, et al. Canadian Airway Focus Group updated consensus-based recommendations for management of the difficult airway. Can J Anesth. 2021." },
  cpsCroup: { id: "cps-croup", citation: "Ortiz-Alvarez O, Canadian Paediatric Society Acute Care Committee. Acute management of croup in the emergency department. Paediatr Child Health. 2017.", url: "https://cps.ca/en/documents/position/acute-management-of-croup" },
  trekkCroup: { id: "trekk-croup", citation: "TREKK (Translating Emergency Knowledge for Kids). Bottom line recommendations. Croup. Version 4.0. 2023.", url: "https://trekk.ca/resources/bottom-line-recommendations-croup" },
  gina: { id: "gina", citation: "Global Initiative for Asthma. Global Strategy for Asthma Management and Prevention. 2024 update.", url: "https://ginasthma.org/wp-content/uploads/2024/05/GINA-2024-Strategy-Report-24_05_22_WMS.pdf" },
  gold: { id: "gold", citation: "Agusti A, et al. Global Initiative for Chronic Obstructive Lung Disease 2023 Report. GOLD executive summary. Am J Respir Crit Care Med. 2023." },
  ersNiv: { id: "ers-niv", citation: "Rochwerg B, et al. Official ERS/ATS clinical practice guidelines. Noninvasive ventilation for acute respiratory failure. Eur Respir J. 2017." },
  ccsHf: { id: "ccs-hf", citation: "Ezekowitz JA, et al. 2017 Comprehensive update of the Canadian Cardiovascular Society guidelines for the management of heart failure. Can J Cardiol. 2017." },
  idsaCap: { id: "idsa-cap", citation: "Metlay JP, et al. Diagnosis and treatment of adults with community-acquired pneumonia. An official clinical practice guideline of the American Thoracic Society and Infectious Diseases Society of America. Am J Respir Crit Care Med. 2019." },
  dcDka: { id: "dc-dka", citation: "Goguen J, Gilbert J. Diabetes Canada 2018 Clinical Practice Guidelines. Hyperglycemic emergencies in adults. Can J Diabetes. 2018." },
  extripSal: { id: "extrip-sal", citation: "Juurlink DN, et al. Extracorporeal treatment for salicylate poisoning. Systematic review and recommendations from the EXTRIP workgroup. Ann Emerg Med. 2015." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, Ma OJ, Yealy DM, Meckler GD, Stapczynski JS, Cline DM, Thomas SH, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. 9th ed. McGraw Hill. 2020. Chapter 14, Allergy and Anaphylaxis. Chapter 62, Respiratory Distress. Chapter 69, Acute Asthma and Status Asthmaticus. Chapter 126, Stridor and Drooling in Infants and Children. Chapter 172, Acute Peripheral Neurologic Disorders. Chapter 189, Salicylates. Chapter 225, Diabetic Ketoacidosis." },
  thrombCan: { id: "thromb-can", citation: "Thrombosis Canada. Clinical guide. Pulmonary embolism (PE): diagnosis. 2025.", url: "https://thrombosiscanada.ca/clinical_guides/pdfs/PULMONARYEMBOLISMDIAGNOSISANDM_83.pdf" },
  perc: { id: "perc", citation: "Kline JA, et al. Clinical criteria to prevent unnecessary diagnostic testing in emergency department patients with suspected pulmonary embolism. J Thromb Haemost. 2004." },
  adjust: { id: "adjust", citation: "Righini M, et al. Age-adjusted D-dimer cutoff levels to rule out pulmonary embolism. The ADJUST-PE study. JAMA. 2014." },
  escPe: { id: "esc-pe", citation: "Konstantinides SV, et al. 2019 ESC Guidelines for the diagnosis and management of acute pulmonary embolism. Eur Heart J. 2020." },
  artemis: { id: "artemis", citation: "van der Pol LM, et al. Pregnancy-adapted YEARS algorithm for diagnosis of suspected pulmonary embolism. N Engl J Med. 2019." },
  sogcVte: { id: "sogc-vte", citation: "Chan WS, Rey E, Kent NE, et al. Venous thromboembolism and antithrombotic therapy in pregnancy. SOGC clinical practice guideline. J Obstet Gynaecol Can. 2014." },
  bts: { id: "bts", citation: "Roberts ME, et al. British Thoracic Society guideline for pleural disease, including spontaneous pneumothorax. Thorax. 2023." },
  atls: { id: "atls", citation: "American College of Surgeons Committee on Trauma. Advanced Trauma Life Support Student Course Manual. 10th ed. 2018. Chapter on thoracic trauma." },
  waoAna: { id: "wao-ana", citation: "Cardona V, et al. World Allergy Organization Anaphylaxis Guidance 2020. World Allergy Organ J. 2020." },
} satisfies Record<string, Source>;

export const SOB_SAMPS: Samp[] = [
  {
    id: "sob-01",
    topic: "sob",
    alsoTopics: ["airway", "anaphylaxis"],
    title: "Woke up with a thick tongue",
    stem:
      "A 64-year-old woman arrives by private car at 06:00. She woke with swollen lips and a thick tongue. Over the past hour her voice has become muffled and she is spitting saliva into a basin. She has hypertension and type 2 diabetes treated with ramipril, which was started 5 months ago, and metformin. She has no itch and no rash. She sits upright and leans forward. There is soft inspiratory stridor. The tongue and floor of mouth are visibly swollen. Air entry is equal and the chest is clear.",
    vitals: { temperature: "36.8°C", pulse: "104/minute", resp: "24/minute", bp: "158/92 mmHg", o2sat: "95% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What findings in this presentation place the obstruction in the upper airway rather than the lower airway?",
        accept: [
          { id: "stridor", text: "Inspiratory stridor", match: ["stridor"] },
          { id: "voice", text: "Muffled or changed voice", match: ["voice", "muffled", "hoarse", "hoarseness", "dysphonia"] },
          { id: "drool", text: "Drooling or inability to handle secretions", match: ["drooling", "drool", "secretion", "saliva", "spitting"] },
          { id: "position", text: "Sitting upright and leaning forward, tripod posture", match: ["tripod", "leaning forward", "sitting forward", "sniffing"] },
          { id: "clear", text: "Clear chest without wheeze", match: ["clear chest", "clear lung", "no wheeze", "no wheezing", "absent wheeze"] },
          { id: "swelling", text: "Visible tongue or floor of mouth swelling", match: ["tongue", "floor of mouth", "lip swelling", "oropharyngeal swelling"] },
        ],
        unacceptable: [{ text: "Low oxygen saturation", match: ["saturation", "spo2", "hypoxia"] }],
        explanation:
          "Stridor, voice change, pooling secretions and a forward seated posture localize obstruction above the carina. A clear chest argues against bronchospasm. Oxygen saturation stays normal until upper airway obstruction is near complete, so it does not localize or grade the problem.",
        keyFeature: { topic: "sob", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        update: "Twenty minutes later her voice is barely audible and the stridor is louder. She can still maintain her own oxygenation.",
        prompt: "Which of the following is the most appropriate airway strategy for her?",
        options: [
          "Awake flexible bronchoscopic intubation with double setup",
          "High flow nasal oxygen and observation for 4 hours",
          "Immediate surgical cricothyrotomy before any other attempt",
          "Rapid sequence intubation with video laryngoscopy",
          "Trial of BiPAP to splint the airway open",
        ],
        correct: 0,
        explanation:
          "Progressive angioedema with voice loss is a predicted difficult airway. Awake flexible bronchoscopic intubation with topical anesthesia keeps spontaneous breathing and avoids a cannot intubate cannot oxygenate situation after paralysis. A double setup, with a surgical airway set up and the neck marked, is essential. Positive pressure does not relieve tissue swelling and delays definitive care.",
        keyFeature: { topic: "sob", n: 3 },
        source: "cafg",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What preparations do you make before the airway attempt?",
        accept: [
          { id: "help", text: "Call the most experienced airway help available, such as anesthesia or ENT", match: ["anesthesia", "anaesthesia", "anesthesiologist", "ent", "otolaryngology", "experienced", "call for help"] },
          { id: "fona", text: "Open the front of neck access kit and palpate or ultrasound mark the cricothyroid membrane", match: ["cricothyroid", "cricothyrotomy", "front of neck", "scalpel", "surgical airway"] },
          { id: "small", text: "Prepare smaller endotracheal tubes, for example 6.0 or 6.5", match: ["smaller tube", "small tube", "smaller ett", "tube size", "6.0"] },
          { id: "topical", text: "Topical airway anesthesia with lidocaine", match: ["lidocaine", "topical", "topicalize"] },
          { id: "preox", text: "Preoxygenate with high flow nasal oxygen kept on during the attempt", match: ["preoxygenate", "preoxygenation", "apneic oxygenation", "high flow nasal"] },
          { id: "location", text: "Move to the operating room if time allows", match: ["operating room"] },
          { id: "plan", text: "Verbalize plan A, B and C to the team", match: ["plan b", "backup plan", "verbalize plan", "team briefing"] },
        ],
        explanation:
          "Airway swelling can progress quickly and distort landmarks. Marking the membrane before swelling worsens makes rescue faster. Smaller tubes pass narrowed tissue. Experienced help and a shared plan reduce fixation on one technique.",
        keyFeature: { topic: "airway", n: 3 },
        source: "cafg",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "She is extubated in the ICU 2 days later and is ready to go home.",
        prompt: "What discharge instructions are specific to the likely cause of this episode?",
        accept: [
          { id: "stop", text: "Stop ramipril permanently and never take any ACE inhibitor again", match: ["stop ramipril", "stop ace", "discontinue ramipril", "discontinue ace", "never take ace", "avoid ace"] },
          { id: "alert", text: "Record ACE inhibitor angioedema as an allergy or intolerance and wear a medical alert", match: ["medical alert", "medicalert", "allergy list", "intolerance", "chart alert"] },
          { id: "alt", text: "Arrange an alternative antihypertensive, such as a calcium channel blocker, with the family physician", match: ["alternative antihypertensive", "calcium channel blocker", "amlodipine", "alternative blood pressure"] },
          { id: "arb", text: "An ARB may be used only with caution after discussion with her physician, since cross reactivity is uncommon but possible", match: ["arb", "angiotensin receptor"] },
          { id: "recur", text: "Swelling can recur for weeks after stopping, so return urgently for any swelling or voice change", match: ["recur", "return"] },
        ],
        unacceptable: [{ text: "Continue ramipril with an antihistamine", match: ["continue ramipril", "continue ace", "restart ramipril"], dangerous: true }],
        explanation:
          "ACE inhibitor angioedema is bradykinin mediated and can occur months or years after starting the drug. The drug class must be stopped for life. Attacks may recur for several weeks after stopping. Antihistamines do not prevent bradykinin angioedema.",
        keyFeature: { topic: "anaphylaxis", n: 4 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.cafg],
    ...META,
  },
  {
    id: "sob-02",
    topic: "sob",
    title: "Noisy breathing in the night",
    stem:
      "A 20-month-old boy is carried in by his father at 02:30. He has had a runny nose for 2 days. Tonight he woke with a harsh cough that sounds like a seal and noisy breathing. He is fully immunized. He took a bottle of milk 3 hours ago. He is restless and clinging to his father. There is inspiratory stridor at rest with suprasternal and subcostal retractions. Air entry is mildly decreased. He is not drooling.",
    vitals: { temperature: "38.1°C", pulse: "150/minute", resp: "40/minute", o2sat: "96% on room air", weight: "12 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features favour viral croup over epiglottitis or bacterial tracheitis?",
        accept: [
          { id: "bark", text: "Barking, seal like cough", match: ["barking", "barky", "bark", "seal"] },
          { id: "prodrome", text: "Coryzal prodrome with gradual onset", match: ["coryza", "coryzal", "runny nose", "prodrome", "gradual onset", "uri", "urti", "viral prodrome"] },
          { id: "fever", text: "Only low grade fever", match: ["low grade fever", "low fever", "mild fever"] },
          { id: "nodrool", text: "No drooling and able to swallow", match: ["no drooling", "not drooling", "able to swallow", "drinking", "swallowing"] },
          { id: "toxic", text: "Not toxic appearing", match: ["not toxic", "nontoxic", "non toxic", "well appearing"] },
          { id: "age", text: "Typical age of 6 months to 3 years", match: ["age", "typical age"] },
          { id: "imm", text: "Fully immunized, making Hib epiglottitis unlikely", match: ["immunized", "vaccinated", "hib"] },
        ],
        explanation:
          "Croup follows a coryzal prodrome and features a barking cough with low fever in a child who can still swallow. Epiglottitis and bacterial tracheitis present with toxicity, high fever and drooling, and the cough is usually absent in epiglottitis. Immunization makes Hib epiglottitis rare.",
        keyFeature: { topic: "sob", n: 1 },
        source: "cps-croup",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Which of the following treatments should he receive at this time?",
        options: [
          "Amoxicillin 40 mg/kg PO",
          "Cool mist humidification",
          "Dexamethasone 0.6 mg/kg PO",
          "Dexamethasone 0.06 mg/kg PO",
          "Epinephrine 0.01 mg/kg IM",
          "Nebulized budesonide as the only steroid",
          "Nebulized epinephrine 1 mg/mL, 0.5 mL/kg, maximum 5 mL",
          "Nebulized salbutamol 2.5 mg",
        ],
        correct: [2, 6],
        explanation:
          "Stridor at rest with retractions is moderate to severe croup. Oral dexamethasone reduces severity and return visits. The CPS dose is 0.6 mg/kg, and doses as low as 0.15 mg/kg are also accepted, so 0.06 mg/kg is too low. Nebulized epinephrine gives rapid but temporary relief of subglottic edema. Humidified air has no proven benefit and salbutamol treats the wrong level of the airway.",
        keyFeature: { topic: "sob", n: 3 },
        source: "cps-croup",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What findings would indicate impending respiratory failure in this child?",
        accept: [
          { id: "loc", text: "Decreased level of consciousness or lethargy", match: ["lethargy", "lethargic", "decreased loc", "decreased level of consciousness", "drowsy", "obtunded", "altered mental status"] },
          { id: "fatigue", text: "Fatigue or decreasing respiratory effort", match: ["fatigue", "tiring", "tired", "decreasing effort", "decreased effort"] },
          { id: "airentry", text: "Markedly decreased air entry", match: ["decreased air entry", "poor air entry", "reduced air entry", "silent"] },
          { id: "cyan", text: "Cyanosis or pallor", match: ["cyanosis", "cyanotic", "pallor", "pale", "dusky"] },
          { id: "hypox", text: "Hypoxemia with SpO2 below 92%", match: ["hypoxia", "hypoxemia", "low saturation", "spo2", "desaturation"] },
          { id: "stridor", text: "Stridor becoming quieter while work of breathing persists", match: ["quieter stridor", "stridor quieter", "decreasing stridor", "less stridor"] },
          { id: "retract", text: "Severe retractions or paradoxical breathing", match: ["severe retraction", "paradoxical", "marked retraction"] },
        ],
        unacceptable: [{ text: "Louder barking cough", match: ["louder cough", "cough louder"] }],
        explanation:
          "Falling mental status, tiring and poor air entry signal impending failure. A quieter child with softer stridor may be worse, not better. Hypoxemia and cyanosis are late signs in upper airway obstruction.",
        keyFeature: { topic: "sob", n: 4 },
        source: "trekk-croup",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Thirty minutes after treatment he is asleep on his father with no stridor at rest and mild retractions only.",
        prompt: "What conditions must be met before discharge home?",
        accept: [
          { id: "obs", text: "Observe at least 2 hours after the last epinephrine dose", match: ["2 hour", "two hour", "observe", "observation"] },
          { id: "nostridor", text: "No stridor at rest", match: ["no stridor", "without stridor", "stridor resolved"] },
          { id: "work", text: "Normal work of breathing and air entry", match: ["work of breathing", "no retraction", "normal air entry", "air entry"] },
          { id: "drink", text: "Tolerating oral fluids", match: ["tolerating fluid", "drinking", "oral fluid", "tolerating po", "feeding"] },
          { id: "sat", text: "Normal colour and oxygen saturation", match: ["colour", "color", "saturation", "spo2"] },
          { id: "caregiver", text: "Caregiver understands return signs and can return quickly", match: ["return", "caregiver", "parent understand", "access to care"] },
        ],
        unacceptable: [{ text: "Discharge now because stridor has resolved", match: ["discharge now", "discharge immediately"] }],
        explanation:
          "Nebulized epinephrine wears off in about 2 hours and symptoms can return. Discharge is reasonable after that period if there is no stridor at rest and the child is drinking. Caregivers need clear return advice because croup is often worse at night.",
        keyFeature: { topic: "sob", n: 4 },
        source: "cps-croup",
      },
    ],
    sources: [S.cpsCroup, S.trekkCroup],
    ...META,
  },
  {
    id: "sob-03",
    topic: "sob",
    alsoTopics: ["asthma-copd"],
    title: "A toddler who coughed at a party",
    stem:
      "A 2-year-old girl is brought in 3 hours after a sudden bout of coughing and gagging at her brother's birthday party. Bowls of mixed nuts were on a low table. The coughing settled after a few minutes but she still coughs now and then. She has no history of wheeze and no fever. She is alert and playing. There is decreased air entry over the right lower chest with a focal expiratory wheeze on that side. There is no stridor.",
    vitals: { temperature: "37.0°C", pulse: "132/minute", resp: "34/minute", o2sat: "95% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most likely location of the obstruction?",
        options: [
          "Esophagus at the cricopharyngeus",
          "Larynx above the vocal cords",
          "Left main or lower lobe bronchus",
          "Right main or lower lobe bronchus",
          "Subglottic trachea below the cords",
        ],
        correct: 3,
        explanation:
          "A unilateral wheeze with reduced air entry after a choking episode points to a bronchial foreign body. The right side is more often involved in older children and adults because of the straighter right bronchus. Absence of stridor and voice change argues against a laryngeal or tracheal object.",
        keyFeature: { topic: "sob", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What imaging approaches increase the yield for an aspirated nut?",
        accept: [
          { id: "insexp", text: "Inspiratory and expiratory chest radiographs", match: ["inspiratory expiratory", "expiratory film", "expiratory view", "expiratory xray", "expiratory x ray", "expiratory cxr", "expiratory radiograph"] },
          { id: "decub", text: "Bilateral lateral decubitus chest radiographs", match: ["decubitus"] },
          { id: "ct", text: "Low dose CT of the chest", match: ["ct chest", "ct of the chest", "chest ct", "computed tomography"] },
          { id: "fluoro", text: "Chest fluoroscopy", match: ["fluoroscopy"] },
        ],
        unacceptable: [{ text: "Soft tissue neck radiograph only", match: ["neck xray", "soft tissue neck", "neck x ray"] }],
        explanation:
          "Nuts are radiolucent. Air trapping on the affected side shows on expiratory or dependent decubitus films because that lung fails to deflate. CT can help when films are equivocal and suspicion is moderate.",
        keyFeature: { topic: "asthma-copd", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "The chest radiographs are read as normal. Her mother asks whether they can go home.",
        prompt: "What are the elements of your plan now?",
        accept: [
          { id: "bronch", text: "Consult paediatric ENT or surgery for rigid bronchoscopy", match: ["bronchoscopy", "ent", "otolaryngology", "paediatric surgery", "pediatric surgery", "thoracic surgery"] },
          { id: "npo", text: "Keep her NPO", match: ["npo", "nil by mouth", "nothing by mouth"] },
          { id: "monitor", text: "Keep her monitored in hospital with airway equipment ready", match: ["monitor", "monitored", "monitoring", "admit", "observe"] },
          { id: "calm", text: "Keep her calm with her parent and avoid agitating procedures", match: ["calm", "avoid agitation", "with parent"] },
          { id: "explain", text: "Explain that normal films do not exclude an aspirated object", match: ["normal film", "normal xray", "normal x ray", "does not exclude", "doesnt exclude", "not rule out", "doesn rule out", "rule out"] },
        ],
        unacceptable: [{ text: "Discharge because the radiographs are normal", match: ["discharge home", "send home", "discharge now", "safe to discharge", "safe for discharge", "go home"], dangerous: true }],
        explanation:
          "Most aspirated objects in children are radiolucent and many films are normal. A clear choking history with focal findings warrants bronchoscopy. Missed foreign bodies cause recurrent pneumonia and bronchiectasis and can shift and obstruct acutely.",
        keyFeature: { topic: "sob", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "While waiting for the operating room she suddenly cannot cry or cough and becomes cyanotic. She is still conscious.",
        prompt: "What immediate interventions would you use, in order, if she deteriorates?",
        accept: [
          { id: "abdo", text: "Abdominal thrusts while she is conscious", match: ["abdominal thrust", "heimlich"] },
          { id: "cpr", text: "Start CPR with chest compressions if she becomes unresponsive", match: ["cpr", "chest compression"] },
          { id: "magill", text: "Direct laryngoscopy and removal with Magill forceps", match: ["magill", "laryngoscopy", "forceps"] },
          { id: "push", text: "Intubate and advance the tube to push the object into one main bronchus, then ventilate the other lung", match: ["push", "advance the tube", "mainstem", "main bronchus"] },
          { id: "help", text: "Call for anesthesia and ENT help", match: ["anesthesia", "anaesthesia", "call for help"] },
        ],
        unacceptable: [{ text: "Blind finger sweep", match: ["blind finger", "finger sweep", "blind sweep"] }],
        explanation:
          "A conscious child over 1 year with complete obstruction gets abdominal thrusts. If she becomes unresponsive, start CPR and look in the mouth before breaths. Under laryngoscopy, remove a visible object with Magill forceps. A distal object that cannot be removed can be pushed into one bronchus to ventilate the other lung. Blind sweeps can push the object deeper.",
        keyFeature: { topic: "sob", n: 3 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },
  {
    id: "sob-04",
    topic: "sob",
    alsoTopics: ["asthma-copd", "airway"],
    title: "Worsening wheeze after a cold",
    stem:
      "A 27-year-old woman with asthma arrives by ambulance. She has had a cold for 3 days and has used her salbutamol inhaler every hour today. She stopped her controller inhaler 4 months ago when her prescription ran out. She speaks in short phrases. She is using her accessory muscles and has diffuse expiratory wheeze. She cannot perform a peak flow.",
    vitals: { temperature: "37.4°C", pulse: "128/minute", resp: "32/minute", bp: "132/78 mmHg", o2sat: "89% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What further items of history would identify her as at high risk of fatal asthma?",
        accept: [
          { id: "intub", text: "Previous intubation for asthma", match: ["intubation", "intubated", "ventilated", "mechanical ventilation"] },
          { id: "icu", text: "Previous ICU admission", match: ["icu", "intensive care"] },
          { id: "visits", text: "Frequent ED visits or hospital admissions in the past year", match: ["ed visit", "emergency visit", "hospitalization", "admission", "hospital visit"] },
          { id: "steroid", text: "Recent or current oral corticosteroid use", match: ["prednisone", "oral steroid", "systemic steroid", "corticosteroid", "steroid course"] },
          { id: "saba", text: "Heavy SABA use, for example more than one canister a month", match: ["canister", "saba use", "salbutamol use", "reliever use", "overuse"] },
          { id: "psych", text: "Psychiatric illness or psychosocial barriers", match: ["psychiatric", "psychosocial", "depression", "mental health", "substance"] },
          { id: "food", text: "Food allergy", match: ["food allergy", "anaphylaxis"] },
          { id: "perception", text: "Poor perception of airflow obstruction", match: ["perception", "poor perceiver"] },
        ],
        explanation:
          "Prior intubation or ICU care is the strongest marker of fatal asthma risk. Frequent visits, recent oral steroids, heavy reliever use and no inhaled corticosteroid all mark poorly controlled disease. Psychosocial barriers and food allergy add risk.",
        keyFeature: { topic: "asthma-copd", n: 2 },
        source: "gina",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What medications, with dose and route, do you order in the first 20 minutes?",
        accept: [
          { id: "salb", text: "Salbutamol 2.5 to 5 mg nebulized or 8 to 10 puffs by MDI with spacer every 20 minutes or continuous", match: ["salbutamol 5 mg", "salbutamol 5mg", "salbutamol 2.5 mg", "salbutamol 2.5mg", "salbutamol puff", "salbutamol continuous", "salbutamol 10 puff", "salbutamol 8 puff", "ventolin 5 mg"] },
          { id: "ipra", text: "Ipratropium 500 mcg nebulized or 4 to 8 puffs by MDI every 20 minutes for 3 doses", match: ["ipratropium 500", "ipratropium 0.5 mg", "ipratropium 0.5mg", "ipratropium puff", "atrovent 500", "ipratropium 250"] },
          { id: "steroid", text: "Prednisone 50 mg PO or methylprednisolone 125 mg IV", match: ["prednisone 50", "prednisone 40", "methylprednisolone 125", "methylprednisolone 80", "hydrocortisone 200", "dexamethasone 10", "dexamethasone 12"] },
          { id: "mag", text: "Magnesium sulfate 2 g IV over 20 minutes", match: ["magnesium 2 g", "magnesium 2g", "magnesium sulfate 2", "mgso4 2"] },
          { id: "o2", text: "Oxygen titrated to SpO2 93 to 95%", match: ["oxygen 93", "oxygen titrated", "o2 titrated", "oxygen to 9"] },
        ],
        unacceptable: [
          { text: "Benzodiazepine for anxiety", match: ["lorazepam", "midazolam", "benzodiazepine", "diazepam"], dangerous: true },
          { text: "Epinephrine 1 mg IV", match: ["epinephrine 1 mg iv", "epinephrine 1mg iv"], dangerous: true },
        ],
        explanation:
          "Severe asthma needs repeated high dose short acting bronchodilator plus ipratropium, early systemic steroid and IV magnesium. Oral prednisone works as well as IV steroid when the patient can swallow. GINA advises that sedatives be strictly avoided in acute asthma, because sedating an anxious, hypoxemic patient removes her respiratory drive and can precipitate arrest.",
        keyFeature: { topic: "asthma-copd", n: 5 },
        source: "gina",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "After 1 hour she is drowsy and answers in single words. The chest is now quiet. O2 sat 90% on a 10 L/minute mask. Venous gas pH 7.24, PCO2 62 mmHg.",
        prompt: "What findings show she is heading into respiratory failure?",
        accept: [
          { id: "loc", text: "Drowsiness or decreased level of consciousness", match: ["drowsy", "drowsiness", "decreased loc", "decreased level of consciousness", "altered mental status", "confusion", "obtunded"] },
          { id: "silent", text: "Silent chest", match: ["silent chest", "quiet chest", "no wheeze", "absent wheeze", "decreased air entry"] },
          { id: "co2", text: "Rising PCO2 with respiratory acidosis", match: ["pco2", "hypercapnia", "hypercarbia", "co2", "respiratory acidosis", "acidosis"] },
          { id: "words", text: "Speaking in single words only", match: ["single word", "one word", "words only", "unable to speak"] },
          { id: "hypox", text: "Hypoxemia despite high flow oxygen", match: ["hypoxia", "hypoxemia", "despite oxygen", "spo2 90"] },
          { id: "fatigue", text: "Fatigue with falling respiratory effort", match: ["fatigue", "tiring", "exhaustion", "decreasing effort"] },
        ],
        unacceptable: [{ text: "Improving because the wheeze is gone", match: ["improving", "better", "resolved wheeze"], dangerous: true }],
        explanation:
          "A normal or rising PCO2 in a tachypneic asthmatic means she can no longer ventilate. A silent chest reflects minimal airflow, not improvement. Drowsiness is a late and ominous sign that should prompt immediate airway planning.",
        keyFeature: { topic: "sob", n: 4 },
        source: "gina",
      },
      {
        id: "q4",
        kind: "menu",
        select: 2,
        update: "You decide to intubate.",
        prompt: "Which of the following choices are most appropriate for her intubation and ventilation?",
        options: [
          "Applied PEEP of 15 cm H2O",
          "Ketamine 1.5 mg/kg IV for induction",
          "Propofol 3 mg/kg IV bolus for induction",
          "Rate 24/minute targeting a normal PCO2",
          "Rate 10/minute, tidal volume 6 to 8 mL/kg, long expiration",
          "Stop inhaled bronchodilators once the tube is in",
          "Tidal volume 12 mL/kg ideal body weight",
        ],
        correct: [1, 4],
        explanation:
          "Ketamine keeps blood pressure and adds bronchodilation. The main danger after intubation is breath stacking with auto PEEP and cardiovascular collapse. A rate of about 10/minute, a tidal volume of 6 to 8 mL/kg ideal body weight and a long expiratory time, accepting hypercapnia, reduce that risk. Large propofol boluses cause hypotension in a preload dependent patient.",
        keyFeature: { topic: "airway", n: 5 },
        source: "tintinalli",
      },
    ],
    sources: [S.gina, S.tintinalli],
    ...META,
  },
  {
    id: "sob-05",
    topic: "sob",
    alsoTopics: ["asthma-copd"],
    title: "Home oxygen and a worse week",
    stem:
      "A 71-year-old man with severe COPD uses 2 L/minute of home oxygen. For 3 days he has had more breathlessness and thick green sputum. He is sitting forward, pursed lip breathing, and speaking in phrases. He is alert but says he is exhausted. Arterial gas on 2 L/minute: pH 7.28, PaCO2 72 mmHg, PaO2 50 mmHg, HCO3 33 mmol/L.",
    vitals: { temperature: "37.9°C", pulse: "112/minute", resp: "30/minute", bp: "148/86 mmHg", o2sat: "82% on 2 L/minute oxygen" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following oxygen saturation targets is most appropriate for him?",
        options: [
          "80 to 84%",
          "85 to 87%",
          "88 to 92%",
          "93 to 96%",
          "97 to 100%",
        ],
        correct: 2,
        explanation:
          "In hypercapnic COPD, uncontrolled high flow oxygen worsens hypercapnia through ventilation perfusion mismatch and the Haldane effect. A target of 88 to 92% avoids both hypoxia and oxygen induced CO2 retention. Oxygen should never be withheld from a hypoxemic patient.",
        keyFeature: { topic: "asthma-copd", n: 5 },
        source: "gold",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What features of his arterial gas indicate he needs ventilatory support?",
        accept: [
          { id: "ph", text: "Acidemia with pH below 7.35", match: ["ph", "acidemia", "acidosis", "acidotic"] },
          { id: "co2", text: "PaCO2 above 45 mm Hg with acidosis, meaning acute hypercapnia", match: ["paco2", "pco2", "hypercapnia", "hypercarbia", "co2 72", "co2"] },
          { id: "o2", text: "Persistent hypoxemia with PaO2 50 mm Hg on oxygen", match: ["pao2", "hypoxemia", "hypoxia", "po2"] },
          { id: "acute", text: "Bicarbonate too low for the degree of hypercapnia, so an acute on chronic process", match: ["acute on chronic", "inadequate compensation", "incomplete compensation", "bicarbonate", "hco3"] },
        ],
        explanation:
          "A pH below 7.35 with PaCO2 above 45 mmHg defines acute hypercapnic respiratory failure and is the trigger for NIV in COPD. The raised bicarbonate shows chronic retention, but the low pH shows he has decompensated on top of it.",
        keyFeature: { topic: "sob", n: 4 },
        source: "ers-niv",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following forms of ventilatory support is most appropriate now?",
        options: [
          "BiPAP starting near IPAP 10 and EPAP 5 cm H2O",
          "Continue 2 L/minute nasal prongs, repeat gas in 2 hours",
          "CPAP 10 cm H2O by full face mask",
          "High flow nasal cannula, 60 L/minute and FiO2 1.0",
          "Rapid sequence intubation and ventilation",
        ],
        correct: 0,
        explanation:
          "Bilevel NIV reduces intubation and mortality in hypercapnic COPD exacerbations with pH 7.25 to 7.35 and is reasonable below that with close watch. He is alert and protecting his airway, so NIV is first. Start near IPAP 10 cm H2O and EPAP 5 cm H2O and titrate to comfort and PaCO2. CPAP alone gives no inspiratory support to unload the muscles.",
        keyFeature: { topic: "sob", n: 3 },
        source: "ers-niv",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What drug therapies are indicated for this exacerbation?",
        accept: [
          { id: "saba", text: "Short acting beta agonist such as salbutamol", match: ["salbutamol", "saba", "beta agonist", "ventolin"] },
          { id: "sama", text: "Short acting anticholinergic such as ipratropium", match: ["ipratropium", "anticholinergic", "sama", "atrovent"] },
          { id: "steroid", text: "Systemic corticosteroid such as prednisone 40 mg daily for 5 days", match: ["prednisone", "corticosteroid", "steroid", "methylprednisolone"] },
          { id: "abx", text: "Antibiotic for increased sputum purulence, such as amoxicillin clavulanate or doxycycline", match: ["antibiotic", "amoxicillin", "doxycycline", "clavulanate", "cefuroxime", "levofloxacin", "moxifloxacin", "azithromycin", "clarithromycin"] },
        ],
        unacceptable: [{ text: "Theophylline or aminophylline load", match: ["theophylline", "aminophylline"] }],
        explanation:
          "Inhaled short acting bronchodilators, a short course of systemic corticosteroid and an antibiotic when sputum purulence has increased are the core of exacerbation care. Five days of prednisone is as effective as longer courses. Methylxanthines add toxicity without benefit.",
        keyFeature: { topic: "asthma-copd", n: 6 },
        source: "gold",
      },
      {
        id: "q5",
        kind: "short",
        required: 3,
        update: "After 90 minutes on BiPAP he is harder to rouse and has vomited once. Repeat gas: pH 7.18, PaCO2 94 mmHg.",
        prompt: "What are the reasons to move to intubation now?",
        accept: [
          { id: "loc", text: "Worsening level of consciousness", match: ["consciousness", "loc", "drowsy", "rouse", "obtunded", "mental status", "gcs"] },
          { id: "gas", text: "Worsening acidosis and hypercapnia despite NIV", match: ["worsening acidosis", "worsening ph", "rising co2", "rising pco2", "rising paco2", "worsening gas", "worsening hypercapnia", "ph 7.18", "failed niv", "failure of niv"] },
          { id: "vomit", text: "Vomiting with aspiration risk under a mask", match: ["vomit", "vomiting", "aspiration"] },
          { id: "airway", text: "Unable to protect his airway or clear secretions", match: ["protect", "secretion"] },
          { id: "tolerate", text: "Unable to cooperate with or tolerate the mask", match: ["tolerate", "cooperate", "intolerance"] },
        ],
        explanation:
          "NIV needs an awake patient who can protect his airway. Falling consciousness, vomiting and a worsening gas after a fair trial all mark NIV failure. Delayed intubation after failed NIV is linked to higher mortality.",
        keyFeature: { topic: "asthma-copd", n: 7 },
        source: "ers-niv",
      },
    ],
    sources: [S.gold, S.ersNiv],
    ...META,
  },
  {
    id: "sob-06",
    topic: "sob",
    alsoTopics: ["dvt-pe", "asthma-copd"],
    title: "Not her usual flare",
    stem:
      "A 68-year-old woman with moderate COPD was discharged 10 days ago after an 8 day admission for pneumonia. Since yesterday she has been more short of breath with sharp right sided chest pain on inspiration. Her cough and sputum are unchanged from baseline. Her usual O2 sat is 92% on room air. There is minimal wheeze, no more than her usual. Her right calf is 2 cm larger than the left.",
    vitals: { temperature: "37.1°C", pulse: "118/minute", resp: "28/minute", bp: "124/76 mmHg", o2sat: "86% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features suggest a cause other than a COPD exacerbation?",
        accept: [
          { id: "sputum", text: "No change in cough or sputum", match: ["unchanged sputum", "cough unchanged", "unchanged cough", "no change in cough", "no change in sputum", "no sputum", "no change sputum", "no increase sputum", "no purulence", "no change cough", "no increased sputum", "baseline sputum"] },
          { id: "pleuritic", text: "Pleuritic chest pain", match: ["pleuritic", "chest pain", "pain on inspiration"] },
          { id: "wheeze", text: "Hypoxemia worse than baseline without extra wheeze", match: ["out of proportion", "hypoxemia", "hypoxia", "desaturation", "no wheeze", "minimal wheeze", "usual wheeze", "without wheeze", "no increase wheeze", "no extra wheeze", "no increased wheeze", "no more wheeze"] },
          { id: "tachy", text: "Tachycardia above 100", match: ["tachycardia", "heart rate", "hr 118"] },
          { id: "hosp", text: "Recent hospitalization and immobility", match: ["hospitalization", "admission", "immobility", "immobilization", "recent admit"] },
          { id: "calf", text: "Unilateral calf swelling", match: ["calf", "leg swelling", "dvt"] },
        ],
        explanation:
          "COPD exacerbations are defined by more dyspnea, sputum and purulence. New pleuritic pain, a unilateral swollen calf and hypoxemia with no increase in sputum or wheeze point elsewhere. Recent admission is a major VTE risk factor.",
        keyFeature: { topic: "sob", n: 2 },
        source: "thromb-can",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What acute diagnoses, other than a COPD exacerbation, must you consider in her?",
        accept: [
          { id: "pe", text: "Pulmonary embolism", match: ["pulmonary embolism", "pe", "embolus"] },
          { id: "ptx", text: "Pneumothorax", match: ["pneumothorax", "ptx"] },
          { id: "pna", text: "Recurrent or hospital acquired pneumonia", match: ["pneumonia"] },
          { id: "acs", text: "Acute coronary syndrome", match: ["acs", "coronary", "mi", "myocardial", "ischemia"] },
          { id: "hf", text: "Heart failure", match: ["heart failure", "chf", "pulmonary edema"] },
          { id: "arrhy", text: "Arrhythmia such as atrial fibrillation", match: ["arrhythmia", "atrial fibrillation", "af"] },
          { id: "eff", text: "Pleural effusion", match: ["effusion"] },
        ],
        explanation:
          "Patients with chronic lung disease still get new acute diseases. PE is common after a COPD admission and is easily blamed on the underlying disease. Pneumothorax, pneumonia, cardiac ischemia and heart failure are the other frequent culprits.",
        keyFeature: { topic: "asthma-copd", n: 4 },
        source: "gold",
      },
      {
        id: "q3",
        kind: "single",
        update: "Her Wells score puts PE in the likely range.",
        prompt: "Which of the following is the most appropriate next test?",
        options: [
          "CT pulmonary angiogram",
          "D-dimer, with imaging only if positive",
          "Portable chest radiograph alone",
          "Transthoracic echocardiogram",
          "Ventilation perfusion scan",
        ],
        correct: 0,
        explanation:
          "With a PE likely score, a negative D-dimer cannot safely exclude PE and D-dimer is often raised after recent admission anyway. Underlying lung disease makes a VQ scan likely to be nondiagnostic, so CT pulmonary angiography is preferred. CT also shows pneumothorax, pneumonia and effusion.",
        keyFeature: { topic: "dvt-pe", n: 5 },
        source: "thromb-can",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "CT shows right segmental and subsegmental emboli. The RV is normal in size. Troponin is normal.",
        prompt: "What findings favour admission over outpatient treatment for her?",
        accept: [
          { id: "o2", text: "Hypoxemia needing supplemental oxygen, SpO2 below 90%", match: ["oxygen", "hypoxemia", "hypoxia", "spo2", "saturation"] },
          { id: "lung", text: "Chronic lung disease with poor reserve", match: ["chronic lung", "copd", "cardiopulmonary", "reserve"] },
          { id: "hr", text: "Heart rate of 110 or more", match: ["heart rate", "tachycardia", "hr"] },
          { id: "pesi", text: "Positive simplified PESI or Hestia criteria", match: ["pesi", "hestia"] },
          { id: "recent", text: "Recent hospital discharge with possible limited home support", match: ["home support", "support", "recent discharge"] },
        ],
        explanation:
          "Simplified PESI gives a point each for chronic cardiopulmonary disease, heart rate of 110 or more and SpO2 below 90%. A need for oxygen is itself an exclusion for outpatient care under Hestia. A normal RV and troponin make her intermediate low risk, not low risk.",
        keyFeature: { topic: "dvt-pe", n: 7 },
        source: "esc-pe",
      },
    ],
    sources: [S.thrombCan, S.gold, S.escPe],
    ...META,
  },
  {
    id: "sob-07",
    topic: "sob",
    alsoTopics: ["pulmonary-edema"],
    title: "Fever, cough and a weak heart",
    stem:
      "A 79-year-old man with ischemic cardiomyopathy and an ejection fraction of 30% has had a productive cough and fever for 3 days. Tonight he woke gasping and could not lie flat. He is diaphoretic and speaking in 2 to 3 word phrases. JVP is elevated. There are crackles to the mid lung fields bilaterally and bronchial breath sounds at the right base.",
    vitals: { temperature: "38.4°C", pulse: "116/minute regular", resp: "34/minute", bp: "172/98 mmHg", o2sat: "84% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What bedside or rapid tests will help you sort out the causes of his dyspnea in the next 15 minutes?",
        accept: [
          { id: "pocus", text: "Lung point of care ultrasound for B lines and consolidation", match: ["ultrasound", "pocus", "b line"] },
          { id: "ecg", text: "12 lead ECG", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "cxr", text: "Portable chest radiograph", match: ["chest xray", "chest x ray", "cxr", "chest radiograph", "chest film"] },
          { id: "vbg", text: "Blood gas with lactate", match: ["blood gas", "vbg", "abg", "lactate"] },
          { id: "trop", text: "Troponin", match: ["troponin"] },
          { id: "bnp", text: "BNP or NT proBNP", match: ["bnp", "probnp", "natriuretic"] },
          { id: "echo", text: "Focused cardiac ultrasound for LV function and effusion", match: ["echo", "cardiac ultrasound", "echocardiogram"] },
          { id: "cbc", text: "CBC for anemia and white count", match: ["cbc", "hemoglobin", "complete blood count"] },
        ],
        explanation:
          "He likely has pneumonia and acute heart failure together, and ischemia may be a third trigger. Ultrasound quickly shows B lines and consolidation. The ECG and troponin look for an ischemic precipitant. A gas shows whether ventilation is failing.",
        keyFeature: { topic: "sob", n: 2 },
        source: "ccs-hf",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What treatments do you start immediately for his respiratory distress?",
        accept: [
          { id: "niv", text: "Noninvasive ventilation with CPAP or BiPAP", match: ["niv", "bipap", "cpap", "noninvasive", "non invasive", "positive pressure"] },
          { id: "nitro", text: "Nitroglycerin, sublingual then IV infusion titrated to blood pressure", match: ["nitroglycerin", "nitro", "ntg", "nitrate"] },
          { id: "furo", text: "Furosemide IV", match: ["furosemide", "lasix", "diuretic"] },
          { id: "abx", text: "Early antibiotics for pneumonia", match: ["antibiotic", "ceftriaxone", "azithromycin", "levofloxacin", "moxifloxacin"] },
          { id: "upright", text: "Sit fully upright", match: ["upright", "sit up"] },
          { id: "o2", text: "Oxygen to correct hypoxemia", match: ["oxygen", "o2"] },
        ],
        unacceptable: [{ text: "Fluid bolus of 30 mL/kg for sepsis", match: ["30 ml/kg", "fluid bolus", "2 l bolus", "litre bolus"], dangerous: true }],
        explanation:
          "Hypertensive acute heart failure responds fastest to positive pressure and high dose nitrates, which lower preload and afterload. Diuretic helps if he is volume overloaded. Pneumonia is the trigger and needs prompt antibiotics. A large sepsis fluid bolus would worsen his pulmonary edema.",
        keyFeature: { topic: "pulmonary-edema", n: 1 },
        source: "ccs-hf",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        prompt: "What is an appropriate empiric antibiotic regimen for his pneumonia, given he needs admission to a ward bed or higher?",
        accept: [
          { id: "betamac", text: "Ceftriaxone plus a macrolide such as azithromycin", match: ["ceftriaxone azithromycin", "ceftriaxone macrolide", "ceftriaxone clarithromycin", "cefotaxime azithromycin", "cefotaxime macrolide", "ceftriaxone doxycycline"] },
          { id: "fq", text: "Respiratory fluoroquinolone alone, such as levofloxacin or moxifloxacin", match: ["levofloxacin", "moxifloxacin", "respiratory fluoroquinolone"] },
        ],
        unacceptable: [
          { text: "Ciprofloxacin", match: ["ciprofloxacin"] },
          { text: "Azithromycin alone", match: ["azithromycin alone", "azithromycin only"] },
        ],
        explanation:
          "Hospitalized community acquired pneumonia is covered by a beta lactam plus a macrolide, or by a respiratory fluoroquinolone alone. Ciprofloxacin covers pneumococcus poorly. Macrolide monotherapy is not enough for an admitted older patient with comorbidity.",
        keyFeature: { topic: "sob", n: 2 },
        source: "idsa-cap",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "Forty minutes later on BiPAP and a nitroglycerin infusion, he is confused and mottled. Pulse 124/minute, BP 84/52 mmHg, O2 sat 88% on FiO2 0.8.",
        prompt: "What changes do you make to his management now?",
        accept: [
          { id: "stopnitro", text: "Stop the nitroglycerin infusion", match: ["stop nitro", "stop nitroglycerin", "stop ntg", "hold nitro", "hold nitroglycerin", "discontinue nitro", "discontinue nitroglycerin"] },
          { id: "intub", text: "Intubate for worsening mental status and hypoxemia", match: ["intubate", "intubation", "ett", "invasive ventilation", "rsi"] },
          { id: "pressor", text: "Start a vasopressor such as norepinephrine", match: ["norepinephrine", "vasopressor", "pressor", "levophed"] },
          { id: "ino", text: "Consider an inotrope such as dobutamine for cardiogenic shock", match: ["dobutamine", "inotrope", "milrinone"] },
          { id: "cultures", text: "Blood cultures and lactate, treat as possible septic shock", match: ["culture", "lactate", "septic"] },
          { id: "icu", text: "Call ICU or cardiology", match: ["icu", "critical care", "cardiology"] },
          { id: "smallfluid", text: "Small cautious fluid bolus such as 250 mL with ultrasound guidance", match: ["250 ml", "small bolus", "cautious fluid"] },
        ],
        unacceptable: [{ text: "Increase the nitroglycerin", match: ["increase nitro", "increase nitroglycerin", "more nitro"], dangerous: true }],
        explanation:
          "He now has shock, likely mixed cardiogenic and septic, and is failing NIV. Vasodilators must stop. Norepinephrine restores perfusion pressure and an inotrope may be added if the output is low. Falling mental status on NIV means he needs intubation, with pressor running first to prevent peri intubation arrest.",
        keyFeature: { topic: "pulmonary-edema", n: 4 },
        source: "ccs-hf",
      },
    ],
    sources: [S.ccsHf, S.idsaCap],
    ...META,
  },
  {
    id: "sob-08",
    topic: "sob",
    title: "Deep breathing and a sore stomach",
    stem:
      "A 19-year-old woman with type 1 diabetes has had 2 days of vomiting and crampy abdominal pain. She tells triage she cannot catch her breath. She has been skipping insulin doses because her pump supplies ran out. Her breathing is deep and regular. Her mucous membranes are dry and her chest is clear. Glucose 28 mmol/L. Venous gas pH 6.98, PCO2 14 mmHg, HCO3 3 mmol/L. Na 131, K 5.6, Cl 98 mmol/L.",
    vitals: { temperature: "37.2°C", pulse: "124/minute", resp: "32/minute", bp: "102/64 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features tell you her dyspnea is not from a lung problem?",
        accept: [
          { id: "sat", text: "Normal oxygen saturation", match: ["saturation", "spo2", "oxygenation", "no hypoxia"] },
          { id: "clear", text: "Clear chest on auscultation", match: ["clear chest", "clear lung", "normal lung", "normal chest"] },
          { id: "kussmaul", text: "Deep regular Kussmaul breathing", match: ["kussmaul", "deep breathing", "deep regular", "deep breath"] },
          { id: "gas", text: "Very low PCO2 with severe metabolic acidosis, meaning respiratory compensation", match: ["compensation", "metabolic acidosis", "low pco2", "pco2 14", "acidosis"] },
          { id: "dm", text: "Diabetes with missed insulin and hyperglycemia", match: ["diabetes", "insulin", "hyperglycemia", "glucose", "dka"] },
          { id: "gi", text: "Vomiting and abdominal pain", match: ["vomiting", "abdominal pain"] },
        ],
        explanation:
          "Kussmaul breathing with normal oxygenation and a clear chest is the respiratory response to metabolic acidosis. The gas confirms maximal compensation. The dyspnea will settle as the acidosis is corrected, not with respiratory therapies.",
        keyFeature: { topic: "sob", n: 2 },
        source: "dc-dka",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What are the initial treatments, with specifics, for her metabolic problem?",
        accept: [
          { id: "fluid", text: "0.9% saline 1 L IV bolus, repeated to restore perfusion", match: ["saline", "normal saline", "ns", "crystalloid", "ringer", "plasmalyte", "fluid bolus", "iv fluid"] },
          { id: "insulin", text: "Regular insulin infusion at 0.1 units/kg/h once K is at least 3.3 mmol/L", match: ["insulin infusion", "insulin drip", "insulin 0.1", "iv insulin"] },
          { id: "k", text: "Add potassium to fluids once K falls below 5.0 to 5.5 mmol/L", match: ["potassium", "kcl"] },
          { id: "dex", text: "Add dextrose when glucose falls to about 14 mmol/L", match: ["dextrose", "d5", "d10"] },
          { id: "trigger", text: "Look for and treat a precipitant", match: ["precipitant", "trigger", "infection"] },
        ],
        unacceptable: [{ text: "Insulin bolus without fluids or potassium check", match: ["insulin bolus only", "sc insulin only", "subcutaneous insulin only"] }],
        explanation:
          "Volume restoration comes first and helps lower glucose. A fixed rate insulin infusion clears ketones. Potassium falls quickly once insulin starts, so it is added when K is below about 5 mmol/L. Dextrose lets insulin continue until the gap closes.",
        keyFeature: { topic: "shock", n: 3 },
        source: "dc-dka",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "Two hours later she is drowsy with a GCS of 11. A colleague suggests intubation to protect her airway.",
        prompt: "What are the considerations before and during intubation of this patient?",
        accept: [
          { id: "cause", text: "Look for a reversible cause of drowsiness first, such as hypoglycemia or cerebral edema", match: ["hypoglycemia", "cerebral edema", "glucose check", "reversible cause"] },
          { id: "apnea", text: "Loss of her respiratory compensation during apnea can drop the pH and cause arrest", match: ["apnea", "compensation", "arrest", "worsening acidosis"] },
          { id: "vent", text: "Set a high minute ventilation to match her pre intubation PCO2", match: ["minute ventilation", "high rate", "high respiratory rate", "match pco2", "hyperventilate", "match her"] },
          { id: "gasafter", text: "Check a blood gas soon after intubation", match: ["repeat gas", "blood gas", "abg", "vbg"] },
          { id: "resus", text: "Resuscitate with fluids and have pressor ready before induction", match: ["pressor", "fluid", "hemodynamic", "push dose"] },
          { id: "awake", text: "Consider avoiding intubation if she can protect her airway", match: ["avoid intubation", "protect her airway", "defer"] },
        ],
        unacceptable: [{ text: "Standard ventilator settings with a rate of 12 to 14", match: ["rate 12", "rr 12", "rate of 12", "standard setting", "rate 14"], dangerous: true }],
        explanation:
          "A patient with severe metabolic acidosis depends on hyperventilation. Even a short apnea or a normal ventilator rate lets CO2 rise and the pH collapse. If she must be intubated, keep apnea short and match her minute ventilation. Drowsiness in DKA should also prompt a search for cerebral edema and hypoglycemia.",
        keyFeature: { topic: "sob", n: 3 },
        source: "tintinalli",
      },
    ],
    sources: [S.dcDka, S.tintinalli],
    ...META,
  },
  {
    id: "sob-09",
    topic: "sob",
    alsoTopics: ["tox"],
    title: "Breathless and muddled at 78",
    stem:
      "A 78-year-old woman is brought from home by her son. She has been short of breath and increasingly confused for 2 days. She has osteoarthritis and has been taking extra strength ASA tablets from the pharmacy shelf several times a day for knee pain. She complains of a ringing in her ears. She has fine crackles at both bases. The chest radiograph shows mild bilateral interstitial opacities. Arterial gas: pH 7.44, PaCO2 24 mmHg, HCO3 16 mmol/L. Na 140, Cl 104 mmol/L. Glucose 6.2 mmol/L. Creatinine 124 umol/L.",
    vitals: { temperature: "37.9°C", pulse: "112/minute", resp: "30/minute", bp: "138/72 mmHg", o2sat: "94% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        update: "The admitting team plans to treat her for pneumonia.",
        prompt: "What clues point to a toxicologic cause?",
        accept: [
          { id: "mixed", text: "Mixed respiratory alkalosis and metabolic acidosis", match: ["mixed", "respiratory alkalosis", "metabolic acidosis"] },
          { id: "gap", text: "Raised anion gap of 20", match: ["anion gap", "gap"] },
          { id: "tinnitus", text: "Tinnitus", match: ["tinnitus", "ringing"] },
          { id: "asa", text: "Regular over the counter ASA use", match: ["asa", "aspirin", "salicylate"] },
          { id: "confusion", text: "Confusion out of proportion to the illness", match: ["confusion", "confused", "delirium", "altered"] },
          { id: "edema", text: "Noncardiogenic pulmonary edema pattern", match: ["noncardiogenic", "non cardiogenic", "pulmonary edema"] },
        ],
        explanation:
          "Chronic salicylate toxicity in older adults is often mistaken for sepsis, pneumonia or delirium. Primary respiratory alkalosis with an anion gap metabolic acidosis is the classic gas. Tinnitus and a history of regular ASA use should prompt a level.",
        keyFeature: { topic: "sob", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 1,
        prompt: "What single test confirms your suspicion?",
        accept: [{ id: "level", text: "Serum salicylate level", match: ["salicylate level", "asa level", "aspirin level", "serum salicylate", "salicylate concentration"] }],
        unacceptable: [{ text: "Urine drug screen", match: ["urine drug", "tox screen", "urine screen"] }],
        explanation:
          "A serum salicylate level confirms the diagnosis. Levels should be repeated every 2 hours until falling because absorption can be delayed. Urine drug screens do not detect salicylate reliably and do not guide care.",
        keyFeature: { topic: "tox", n: 7 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "The salicylate level is 4.1 mmol/L. She remains confused. O2 sat has fallen to 89% on room air.",
        prompt: "What treatments does she need?",
        accept: [
          { id: "bicarb", text: "Sodium bicarbonate IV bolus then infusion to alkalinize urine to pH 7.5 to 8", match: ["bicarbonate", "bicarb", "nahco3", "alkalinization", "alkalinize"] },
          { id: "hd", text: "Urgent hemodialysis with nephrology", match: ["hemodialysis", "dialysis", "hd", "nephrology", "extracorporeal"] },
          { id: "k", text: "Potassium replacement to allow urine alkalinization", match: ["potassium", "kcl"] },
          { id: "dex", text: "IV dextrose for neuroglycopenia despite a normal serum glucose", match: ["dextrose", "d50", "d10", "d5", "iv glucose", "glucose infusion"] },
          { id: "o2", text: "Supplemental oxygen", match: ["oxygen", "o2"] },
          { id: "stop", text: "Stop ASA", match: ["stop asa", "stop aspirin", "hold asa"] },
          { id: "poison", text: "Call the poison centre", match: ["poison"] },
        ],
        unacceptable: [{ text: "Furosemide for the pulmonary edema", match: ["furosemide", "lasix", "diuretic"] }],
        explanation:
          "Her level of 4.1 mmol/L (about 57 mg/dL) is below the EXTRIP level thresholds, but altered mental status and new hypoxemia needing oxygen are each an indication for extracorporeal removal whatever the level. Her impaired kidney function adds to the case. Alkalinization traps salicylate in blood and urine while dialysis is arranged and needs potassium to work. CNS glucose can be low when serum glucose is normal.",
        keyFeature: { topic: "tox", n: 6 },
        source: "extrip-sal",
      },
      {
        id: "q4",
        kind: "single",
        update: "While dialysis is being arranged, she becomes obtunded and her respiratory effort weakens. Intubation is needed.",
        prompt: "Which of the following ventilator approaches is most appropriate after intubation?",
        options: [
          "Delay intubation and use BiPAP despite obtundation",
          "Match or exceed her pre intubation minute ventilation",
          "Permissive hypercapnia to limit barotrauma",
          "Rate 14/minute and tidal volume 6 mL/kg",
          "Stop the bicarbonate infusion once the tube is secured",
        ],
        correct: 1,
        explanation:
          "Her tachypnea was keeping her pH up and salicylate out of the brain. A normal ventilator rate lets PCO2 rise, the pH fall and more salicylate enter the CNS, which can cause sudden death. Match or exceed her pre intubation minute ventilation, continue the bicarbonate and recheck the gas within minutes.",
        keyFeature: { topic: "tox", n: 4 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.extripSal],
    ...META,
  },
  {
    id: "sob-10",
    topic: "sob",
    alsoTopics: ["dvt-pe"],
    title: "Sharp pain with each breath",
    stem:
      "A 26-year-old woman has had sharp left sided chest pain for a day. It is worse when she breathes in. She is mildly short of breath climbing stairs. She takes a combined oral contraceptive. She has no hemoptysis, recent surgery or prior clot. Her legs are normal. The ECG shows sinus rhythm and the chest radiograph is normal. You judge PE to be less likely than another diagnosis.",
    vitals: { temperature: "36.9°C", pulse: "92/minute", resp: "18/minute", bp: "118/74 mmHg", o2sat: "98% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What further history items do you need to estimate her VTE risk?",
        accept: [
          { id: "fhx", text: "Family history of VTE or known thrombophilia", match: ["family history", "thrombophilia"] },
          { id: "preg", text: "Possible pregnancy or recent postpartum state", match: ["pregnancy", "pregnant", "postpartum", "lmp"] },
          { id: "travel", text: "Recent long haul travel or immobility", match: ["travel", "immobility", "immobilization", "flight"] },
          { id: "cancer", text: "Active cancer", match: ["cancer", "malignancy"] },
          { id: "trauma", text: "Recent trauma or leg injury", match: ["trauma", "injury", "fracture", "cast"] },
          { id: "leg", text: "Leg pain or swelling", match: ["leg pain", "leg swelling", "calf"] },
          { id: "smoke", text: "Smoking", match: ["smoking", "smoker", "tobacco"] },
        ],
        explanation:
          "Pretest probability rests on the history. Pregnancy, family history of clot, recent travel or immobility and active cancer all raise risk and change the testing pathway. Smoking adds to estrogen related risk.",
        keyFeature: { topic: "dvt-pe", n: 1 },
        source: "thromb-can",
      },
      {
        id: "q2",
        kind: "single",
        update: "She has none of these. Her Wells score is 0.",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "CT pulmonary angiogram",
          "D-dimer level",
          "Leg compression ultrasound",
          "Ventilation perfusion scan",
          "No further testing for PE",
        ],
        correct: 1,
        explanation:
          "PERC can only rule out PE when all 8 criteria are met in a low gestalt patient. Exogenous estrogen fails PERC, so she needs a D-dimer. A negative D-dimer in a low probability patient excludes PE without imaging.",
        keyFeature: { topic: "sob", n: 5 },
        source: "perc",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        update: "Her D-dimer is 1 240 ng/mL FEU. The laboratory cutoff is 500 ng/mL.",
        prompt: "What is the most appropriate next diagnostic step?",
        accept: [
          { id: "ctpa", text: "CT pulmonary angiogram", match: ["ctpa", "ct pulmonary", "ct angiogram", "ct angiography", "ct chest"] },
          { id: "vq", text: "Ventilation perfusion scan, since her chest radiograph is normal", match: ["vq", "v/q", "ventilation perfusion"] },
        ],
        unacceptable: [
          { text: "Repeat the D-dimer", match: ["repeat d dimer", "repeat dimer"] },
          { text: "Discharge with no imaging", match: ["discharge", "no imaging"], dangerous: true },
        ],
        explanation:
          "A positive D-dimer in a patient not excluded by a rule needs imaging. CT pulmonary angiography or VQ scanning are both acceptable. VQ gives a lower breast dose in a young woman with a normal chest radiograph.",
        keyFeature: { topic: "sob", n: 5 },
        source: "thromb-can",
      },
      {
        id: "q4",
        kind: "short",
        required: 1,
        update: "Your resident asks about another patient. He is a 64-year-old man, PE unlikely by Wells, with a D-dimer of 590 ng/mL FEU.",
        prompt: "What is his age adjusted D-dimer cutoff, and is PE excluded?",
        accept: [{ id: "cut", text: "640 ng/mL FEU, so PE is excluded without imaging", match: ["640"] }],
        unacceptable: [{ text: "The standard 500 ng/mL cutoff applies, so he needs imaging", match: ["needs imaging", "need imaging", "requires imaging", "needs ct", "needs ctpa", "order ctpa"] }],
        explanation:
          "For patients over 50, the age adjusted cutoff is age times 10 ng/mL FEU. For a 64-year-old that is 640 ng/mL. His result of 590 is below it, so PE is excluded in a PE unlikely patient. This reduces imaging without increasing missed PE.",
        keyFeature: { topic: "sob", n: 5 },
        source: "adjust",
      },
    ],
    sources: [S.thrombCan, S.perc, S.adjust],
    ...META,
  },
  {
    id: "sob-11",
    topic: "sob",
    alsoTopics: ["dvt-pe", "shock"],
    title: "Collapse during chemotherapy",
    stem:
      "A 55-year-old man with metastatic pancreatic cancer on chemotherapy fainted at home after 2 hours of worsening breathlessness. He is now awake. His neck veins are distended and his chest is clear. His right leg has been swollen for a week. The portable chest radiograph is normal.",
    vitals: { temperature: "37.0°C", pulse: "128/minute", resp: "32/minute", bp: "86/58 mmHg", o2sat: "85% on room air, rising to 91% on a non rebreather mask" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        update: "Your resident wants a D-dimer and says the normal chest radiograph makes PE less likely.",
        prompt: "What are the reasons this reasoning is wrong?",
        accept: [
          { id: "highptp", text: "Pretest probability is high, so a negative D-dimer cannot exclude PE", match: ["pretest", "high probability", "high risk", "cannot exclude", "cannot rule out", "negative d dimer"] },
          { id: "cancer", text: "D-dimer is commonly raised in cancer, so it adds little", match: ["cancer", "malignancy", "nonspecific", "specificity", "false positive", "always positive", "elevated"] },
          { id: "cxr", text: "The chest radiograph is often normal in PE", match: ["normal chest", "normal cxr", "normal xray", "normal x ray", "normal radiograph", "often normal"] },
          { id: "unstable", text: "He is unstable and needs immediate bedside ultrasound and treatment, not a lab test", match: ["unstable", "shock", "hypotension", "bedside", "ultrasound", "pocus"] },
        ],
        explanation:
          "D-dimer is only useful to exclude PE when pretest probability is low or moderate. In a hypotensive cancer patient with a swollen leg, it cannot lower the probability enough. Most patients with PE have a normal or nonspecific chest radiograph, and an unexplained hypoxemia with a clear film should raise suspicion.",
        keyFeature: { topic: "sob", n: 5 },
        source: "esc-pe",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "He is too unstable for CT.",
        prompt: "What bedside ultrasound findings would support massive PE?",
        accept: [
          { id: "rv", text: "Dilated right ventricle, RV to LV ratio above 1", match: ["rv dilation", "dilated rv", "right ventricle", "rv enlarge", "rv larger", "rv to lv", "rv/lv"] },
          { id: "dsign", text: "Septal flattening, D sign", match: ["d sign", "septal", "septum"] },
          { id: "mcconnell", text: "McConnell sign", match: ["mcconnell"] },
          { id: "dvt", text: "DVT on leg compression ultrasound", match: ["dvt", "compression", "noncompressible", "non compressible", "leg"] },
          { id: "clot", text: "Clot in transit in the right heart", match: ["clot in transit", "thrombus in transit", "right heart thrombus", "mobile thrombus"] },
          { id: "ivc", text: "Plethoric IVC", match: ["ivc", "plethoric"] },
          { id: "tapse", text: "Reduced TAPSE", match: ["tapse"] },
        ],
        explanation:
          "In a patient too unstable for CT, RV dilation with septal flattening on bedside echo supports treating as massive PE. A proximal DVT on compression ultrasound adds strong support. A normal RV makes PE an unlikely cause of his shock.",
        keyFeature: { topic: "dvt-pe", n: 2 },
        source: "esc-pe",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "Echo shows a markedly dilated RV with septal flattening. There is a noncompressible right femoral vein. BP is now 78/50 mmHg.",
        prompt: "Which of the following immediate treatments are most appropriate for him?",
        options: [
          "Alteplase 100 mg IV over 2 hours",
          "Alteplase 0.9 mg/kg IV, maximum 90 mg",
          "Apixaban 10 mg PO",
          "Furosemide 40 mg IV",
          "Immediate rapid sequence intubation",
          "IVC filter insertion",
          "Norepinephrine infusion",
          "Normal saline 2 L IV bolus",
        ],
        correct: [0, 6],
        explanation:
          "Massive PE with persistent hypotension is an indication for systemic thrombolysis unless contraindicated. The standard PE regimen is alteplase 100 mg over 2 hours. Norepinephrine supports RV perfusion. Large fluid volumes overdistend the failing RV, and intubation can cause arrest from loss of preload and sympathetic drive.",
        keyFeature: { topic: "sob", n: 3 },
        source: "esc-pe",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What contraindications to thrombolysis must you screen for in this patient?",
        accept: [
          { id: "brainmets", text: "Brain metastases or other intracranial tumour", match: ["brain metastase", "brain metastasis", "brain met", "intracranial tumour", "intracranial tumor", "intracranial neoplasm", "brain lesion", "cns tumour", "cns metastase"] },
          { id: "ich", text: "Any prior intracranial hemorrhage", match: ["intracranial hemorrhage", "ich", "brain bleed", "hemorrhagic stroke"] },
          { id: "stroke", text: "Recent ischemic stroke, within 3 to 6 months depending on the guideline", match: ["stroke", "cva"] },
          { id: "bleed", text: "Active bleeding or bleeding diathesis, including low platelets from chemotherapy", match: ["active bleed", "bleeding", "thrombocytopenia", "platelet", "coagulopathy"] },
          { id: "surgery", text: "Recent major surgery or trauma in the past 3 weeks", match: ["surgery", "trauma"] },
          { id: "headinj", text: "Recent head injury", match: ["head injury", "head trauma"] },
          { id: "htn", text: "Severe uncontrolled hypertension", match: ["hypertension", "blood pressure"] },
        ],
        explanation:
          "Cancer patients carry specific lysis risks, including brain metastases and chemotherapy induced thrombocytopenia. Prior intracranial hemorrhage and recent stroke, surgery or bleeding are standard contraindications. If lysis is contraindicated, options include catheter directed therapy or surgical embolectomy.",
        keyFeature: { topic: "dvt-pe", n: 6 },
        source: "esc-pe",
      },
    ],
    sources: [S.escPe],
    ...META,
  },
  {
    id: "sob-12",
    topic: "sob",
    alsoTopics: ["dvt-pe"],
    title: "Breathless at 28 weeks",
    stem:
      "A 31-year-old woman, G2P1 at 28 weeks gestation, has had 2 days of breathlessness and right sided pleuritic chest pain. Her left calf has been sore and swollen for 4 days. The pregnancy has been uncomplicated. The left calf is 3 cm larger than the right and tender. The fetal heart rate is 145/minute.",
    vitals: { temperature: "36.8°C", pulse: "108/minute", resp: "24/minute", bp: "112/68 mmHg", o2sat: "95% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate first diagnostic test?",
        options: [
          "CT pulmonary angiogram",
          "D-dimer concentration",
          "Left leg compression ultrasound",
          "MRI pulmonary angiogram",
          "Ventilation perfusion lung scan",
        ],
        correct: 2,
        explanation:
          "When a pregnant patient with suspected PE has leg symptoms, compression ultrasound comes first. A proximal DVT confirms VTE and justifies full anticoagulation with no chest imaging or fetal radiation. MR angiography is not validated for PE diagnosis.",
        keyFeature: { topic: "dvt-pe", n: 5 },
        source: "sogc-vte",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "The leg ultrasound shows no DVT. Her D-dimer is 1 450 ng/mL FEU.",
        prompt: "What are the appropriate next steps?",
        accept: [
          { id: "ctpa", text: "CT pulmonary angiogram", match: ["ctpa", "ct pulmonary", "ct angiogram", "ct angiography", "ct chest"] },
          { id: "vq", text: "Ventilation perfusion scan, often preceded by a chest radiograph", match: ["vq", "v/q", "ventilation perfusion", "perfusion scan"] },
          { id: "cxr", text: "Chest radiograph", match: ["chest xray", "chest x ray", "cxr", "chest radiograph"] },
          { id: "lmwh", text: "Start therapeutic LMWH while awaiting imaging if there is no contraindication", match: ["lmwh", "enoxaparin", "dalteparin", "tinzaparin", "low molecular weight heparin", "anticoagulate", "heparin"] },
          { id: "obs", text: "Involve obstetrics", match: ["obstetric", "obstetrician", "ob"] },
        ],
        unacceptable: [{ text: "No imaging because D-dimer is always high in pregnancy", match: ["skip imaging", "no imaging needed", "no imaging required", "no chest imaging", "discharge home"], dangerous: true }],
        explanation:
          "In the pregnancy adapted YEARS approach, a negative leg ultrasound does not end the workup. A D-dimer of 1 000 ng/mL or more needs chest imaging whatever the YEARS items, so her result of 1 450 mandates imaging. D-dimer rises in pregnancy but a high value cannot be dismissed. Empiric LMWH is appropriate if imaging is delayed.",
        keyFeature: { topic: "sob", n: 5 },
        source: "artemis",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "She is worried about radiation to her baby.",
        prompt: "What are accurate counselling points for her?",
        accept: [
          { id: "dose", text: "The fetal dose from CTPA or VQ is far below the level linked to fetal harm", match: ["below", "low dose", "very low", "far below", "small dose", "minimal", "negligible"] },
          { id: "risk", text: "Missing a PE is a greater risk to her and the baby than the imaging", match: ["missed pe", "missing pe", "missing a pe", "untreated pe", "greater risk", "risk of not"] },
          { id: "breast", text: "CTPA gives a higher dose to maternal breast tissue than VQ", match: ["breast"] },
          { id: "vqfetal", text: "VQ and CTPA both give very low fetal doses, so the choice is guided by maternal factors", match: ["vq and ct", "ct and vq", "vq or ct", "ct or vq", "vq and ctpa", "ctpa and vq", "both give", "both test", "either test", "both scan", "either scan"] },
          { id: "contrast", text: "Iodinated contrast is considered safe, with routine newborn thyroid screening", match: ["contrast", "iodine", "thyroid"] },
        ],
        unacceptable: [{ text: "Advise termination because of imaging radiation", match: ["termination", "terminate"], dangerous: true }],
        explanation:
          "Both CTPA and VQ deliver fetal doses of about 1 mGy or less, far below the 50 mGy level linked to fetal harm. The risk of an untreated PE is much greater. CTPA exposes maternal breast tissue more, which matters in young women. Newborn screening covers the theoretical thyroid effect of iodinated contrast.",
        keyFeature: { topic: "dvt-pe", n: 5 },
        source: "sogc-vte",
      },
      {
        id: "q4",
        kind: "single",
        update: "CT shows a right lower lobe segmental PE. Her weight is 78 kg and her creatinine is normal.",
        prompt: "Which of the following is the most appropriate anticoagulant treatment for her?",
        options: [
          "Apixaban 10 mg PO twice daily for 7 days",
          "ASA 81 mg PO once daily until delivery",
          "Enoxaparin 1 mg/kg SC every 12 hours",
          "Rivaroxaban 15 mg PO twice daily for 21 days",
          "Warfarin with a target INR of 2 to 3",
        ],
        correct: 2,
        explanation:
          "LMWH is the anticoagulant of choice in pregnancy because it does not cross the placenta. Warfarin is teratogenic and direct oral anticoagulants are not recommended in pregnancy. Treatment continues through pregnancy and for at least 6 weeks postpartum, with a total of at least 3 months.",
        keyFeature: { topic: "dvt-pe", n: 6 },
        source: "sogc-vte",
      },
    ],
    sources: [S.sogcVte, S.artemis],
    ...META,
  },
  {
    id: "sob-13",
    topic: "sob",
    alsoTopics: ["airway"],
    title: "Weak legs, then weak breathing",
    stem:
      "A 42-year-old man had a diarrheal illness 2 weeks ago. For 5 days he has had tingling feet and weakness that has climbed from his legs to his arms. Today he feels short of breath when lying flat and his cough is weak. He speaks in short sentences and his breathing is shallow. Venous gas: pH 7.38, PCO2 43 mmHg. He has symmetric weakness of all limbs and no reflexes.",
    vitals: { temperature: "36.9°C", pulse: "104/minute", resp: "26/minute", bp: "146/92 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        update: "Your resident says his breathing is fine because the saturation and gas are normal.",
        prompt: "What are the reasons this is unsafe?",
        accept: [
          { id: "late", text: "Hypoxemia and hypercapnia are late findings in neuromuscular failure", match: ["late", "late sign", "late finding"] },
          { id: "normalco2", text: "A normal PCO2 in a tachypneic patient means he is barely compensating", match: ["normal pco2", "normal co2", "should be low", "barely compensating", "inappropriately normal"] },
          { id: "sudden", text: "Collapse can be sudden once the muscles fatigue", match: ["sudden", "abrupt", "precipitous", "fatigue"] },
          { id: "measure", text: "Respiratory muscle strength must be measured directly with FVC and NIF", match: ["fvc", "vital capacity", "nif", "negative inspiratory", "mip", "spirometry"] },
          { id: "bulbar", text: "Weak cough and possible bulbar weakness put him at risk of aspiration", match: ["bulbar", "aspiration", "weak cough", "secretion"] },
        ],
        explanation:
          "In Guillain Barre syndrome the lungs are normal until the pump fails. Oximetry and gases stay normal until very late and then deteriorate quickly. A tachypneic patient should have a low PCO2, so a normal value is a warning. Serial bedside measures of respiratory muscle strength are needed.",
        keyFeature: { topic: "sob", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What bedside measures will you use to follow his respiratory function?",
        accept: [
          { id: "fvc", text: "Forced vital capacity", match: ["fvc", "vital capacity"] },
          { id: "nif", text: "Negative inspiratory force or maximal inspiratory pressure", match: ["nif", "negative inspiratory", "mip", "maximal inspiratory", "inspiratory pressure"] },
          { id: "mep", text: "Maximal expiratory pressure", match: ["mep", "expiratory pressure"] },
          { id: "count", text: "Single breath count", match: ["breath count", "count"] },
          { id: "neck", text: "Neck flexion strength", match: ["neck flexion", "neck strength", "head lift"] },
          { id: "cough", text: "Cough strength and ability to clear secretions", match: ["cough", "secretion"] },
          { id: "para", text: "Paradoxical abdominal breathing or accessory muscle use", match: ["paradoxical", "accessory", "abdominal breathing"] },
          { id: "swallow", text: "Swallowing and bulbar function", match: ["swallow", "bulbar", "dysphagia"] },
        ],
        explanation:
          "Vital capacity and inspiratory force track diaphragm strength directly. Neck flexion strength parallels diaphragm strength. Weak cough and bulbar dysfunction signal aspiration risk. These should be repeated every few hours.",
        keyFeature: { topic: "sob", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        update: "His FVC is 14 mL/kg and his NIF is minus 20 cm H2O. He is coughing on sips of water.",
        prompt: "Which of the following is the most appropriate respiratory plan?",
        options: [
          "Admit to a ward with continuous oximetry",
          "Begin IVIG and intubate only if the gas worsens",
          "BiPAP trial and reassess in 2 hours",
          "Controlled intubation now",
          "High flow nasal cannula, repeat FVC in 4 hours",
        ],
        correct: 3,
        explanation:
          "An FVC below 20 mL/kg, a NIF weaker than minus 30 cm H2O and bulbar weakness each predict the need for ventilation. A planned intubation is far safer than a crash airway. BiPAP is a poor choice with bulbar weakness and a progressive disease. IVIG helps later but will not reverse weakness today.",
        keyFeature: { topic: "sob", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following neuromuscular blockers is most appropriate for his intubation?",
        options: [
          "Rocuronium 1.2 mg/kg IV",
          "Rocuronium 0.3 mg/kg IV",
          "Succinylcholine 1.5 mg/kg IV",
          "Succinylcholine 0.5 mg/kg IV",
          "No paralytic, induction agent alone",
        ],
        correct: 0,
        explanation:
          "Denervation upregulates extrajunctional acetylcholine receptors, so succinylcholine can cause life threatening hyperkalemia in Guillain Barre syndrome. Rocuronium at an RSI dose is safe. A low dose gives poor intubating conditions.",
        keyFeature: { topic: "airway", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q5",
        kind: "short",
        required: 3,
        prompt: "What other neuromuscular causes of respiratory failure would you consider in an emergency department patient with weakness and dyspnea?",
        accept: [
          { id: "mg", text: "Myasthenic crisis", match: ["myasthenia", "myasthenic", "mg crisis"] },
          { id: "botulism", text: "Botulism", match: ["botulism", "botulinum"] },
          { id: "als", text: "Amyotrophic lateral sclerosis", match: ["als", "amyotrophic", "motor neuron"] },
          { id: "op", text: "Organophosphate or carbamate poisoning", match: ["organophosphate", "carbamate", "cholinergic"] },
          { id: "cord", text: "High cervical spinal cord lesion", match: ["spinal cord", "cervical cord", "myelopathy", "transverse myelitis", "cord compression"] },
          { id: "tick", text: "Tick paralysis", match: ["tick"] },
          { id: "lytes", text: "Severe hypokalemia or hypophosphatemia", match: ["hypokalemia", "hypophosphatemia", "potassium", "phosphate", "hypermagnesemia"] },
          { id: "myositis", text: "Inflammatory myopathy or rhabdomyolysis", match: ["myositis", "myopathy", "rhabdomyolysis"] },
        ],
        explanation:
          "Dyspnea from pump failure has many neuromuscular and metabolic causes. Myasthenic crisis, botulism, toxins and cord lesions can all present to the ED with a normal chest radiograph. Electrolyte disorders are quick to test for and fully reversible.",
        keyFeature: { topic: "sob", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },
  {
    id: "sob-14",
    topic: "sob",
    alsoTopics: ["asthma-copd"],
    title: "Sudden chest pain in a young man",
    stem:
      "A 24-year-old man with mild asthma was using his salbutamol more often this week for a cold. An hour ago he felt a sudden sharp pain in the left chest and became very short of breath. He now looks grey and sweaty. Breath sounds are absent on the left, the left chest is hyperresonant, the trachea is shifted to the right and the neck veins are distended.",
    vitals: { pulse: "138/minute", resp: "36/minute", bp: "78/40 mmHg", o2sat: "80% on a non rebreather mask" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate immediate action?",
        options: [
          "Continuous nebulized salbutamol and IV magnesium",
          "Needle or finger decompression of the left chest",
          "Portable chest radiograph before any procedure",
          "Rapid sequence intubation and ventilation",
          "Urgent CT scan of the chest",
        ],
        correct: 1,
        explanation:
          "Hypotension, absent breath sounds, tracheal shift and distended neck veins are tension pneumothorax. It is a clinical diagnosis and needs decompression before any imaging. Positive pressure ventilation before decompression will worsen the tension and can cause arrest.",
        keyFeature: { topic: "sob", n: 3 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What findings in this patient separate tension physiology from a simple pneumothorax?",
        accept: [
          { id: "bp", text: "Hypotension", match: ["hypotension", "low blood pressure", "shock", "bp 78"] },
          { id: "trachea", text: "Tracheal deviation away from the affected side", match: ["trachea", "tracheal"] },
          { id: "jvp", text: "Distended neck veins", match: ["neck vein", "jvp", "jugular", "jvd"] },
          { id: "hypox", text: "Severe hypoxemia despite high flow oxygen", match: ["hypoxemia", "hypoxia", "spo2 80", "saturation", "desaturation"] },
          { id: "tachy", text: "Marked tachycardia", match: ["tachycardia", "hr 138", "heart rate"] },
          { id: "mental", text: "Grey diaphoretic appearance or altered mental status", match: ["grey", "gray", "diaphoretic", "sweaty", "mental status", "confusion"] },
        ],
        unacceptable: [{ text: "Absent breath sounds", match: ["breath sound", "hyperresonance", "hyperresonant"] }],
        explanation:
          "Absent breath sounds and hyperresonance occur in any large pneumothorax. Tension is marked by obstructive shock with hypotension, neck vein distension, tracheal shift and refractory hypoxemia. These findings mean decompression cannot wait.",
        keyFeature: { topic: "sob", n: 4 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "After decompression and a left chest tube, the lung re-expands. The tube is removed 3 days later and he is ready for discharge.",
        prompt: "What advice or follow up arrangements do you give at discharge?",
        accept: [
          { id: "smoke", text: "Stop smoking tobacco and cannabis", match: ["smoking", "smoke", "cannabis", "tobacco", "stop smoking", "quit smoking", "smoking cessation", "no smoking", "avoid smoking", "stop cannabis", "no cannabis", "avoid cannabis"] },
          { id: "fly", text: "Avoid air travel until the pneumothorax has resolved on a follow up radiograph", match: ["air travel", "fly", "flying", "flight", "airplane", "avoid air travel", "avoid flying", "no flying", "no air travel", "don fly", "avoid flight"] },
          { id: "dive", text: "Avoid scuba diving permanently unless he has definitive surgery", match: ["diving", "scuba", "dive", "avoid diving", "no diving", "avoid scuba", "no scuba", "never dive", "don dive", "never scuba"] },
          { id: "return", text: "Return right away for new chest pain or breathlessness", match: ["return"] },
          { id: "fu", text: "Follow up with respirology or thoracic surgery with a repeat chest radiograph", match: ["respirology", "respirologist", "thoracic", "follow up", "repeat chest", "repeat cxr", "repeat xray"] },
          { id: "asthma", text: "Review asthma control, controller therapy and inhaler technique", match: ["controller", "inhaled corticosteroid", "ics", "inhaler technique", "asthma control", "asthma action plan"] },
          { id: "recur", text: "Counsel about the risk of recurrence", match: ["recurrence", "recur"] },
        ],
        explanation:
          "Pneumothorax recurs in about a third of patients, and smoking raises that risk. Flying is unsafe until resolution is confirmed. Diving is contraindicated for life without definitive surgery. His asthma control needs review because poorly controlled asthma adds risk.",
        keyFeature: { topic: "asthma-copd", n: 8 },
        source: "bts",
      },
    ],
    sources: [S.atls, S.bts],
    ...META,
  },
  {
    id: "sob-15",
    topic: "sob",
    alsoTopics: ["anaphylaxis", "airway"],
    title: "Throat tightness after dinner",
    stem:
      "A 35-year-old woman walks into triage from a restaurant across the street. Ten minutes after eating a shrimp dish she developed itchy hives, a tight throat and wheezing. She has no prior allergy history. Her voice is hoarse. She has widespread urticaria, lip swelling, soft inspiratory stridor and scattered expiratory wheeze.",
    vitals: { pulse: "130/minute", resp: "28/minute", bp: "84/50 mmHg", o2sat: "91% on room air", weight: "70 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What findings show her upper airway is involved?",
        accept: [
          { id: "hoarse", text: "Hoarse voice", match: ["hoarse", "hoarseness", "voice", "dysphonia"] },
          { id: "stridor", text: "Inspiratory stridor", match: ["stridor"] },
          { id: "throat", text: "Throat tightness", match: ["throat", "tightness"] },
          { id: "lip", text: "Lip or tongue swelling", match: ["lip", "tongue", "angioedema", "uvula"] },
          { id: "drool", text: "Drooling or difficulty swallowing", match: ["drooling", "swallow", "dysphagia"] },
        ],
        unacceptable: [{ text: "Expiratory wheeze", match: ["wheeze", "wheezing"] }],
        explanation:
          "Anaphylaxis can obstruct both the upper and lower airway. Hoarseness, stridor and throat tightness show laryngeal edema, which may need early airway intervention. Wheeze reflects lower airway bronchospasm and is treated differently.",
        keyFeature: { topic: "sob", n: 1 },
        source: "wao-ana",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate first medication?",
        options: [
          "Diphenhydramine 50 mg IV",
          "Epinephrine 0.5 mg IM",
          "Epinephrine 0.5 mg IV push",
          "Methylprednisolone 125 mg IV",
          "Salbutamol 5 mg nebulized",
        ],
        correct: 1,
        explanation:
          "IM epinephrine 0.01 mg/kg of the 1 mg/mL solution, up to 0.5 mg in adults, is first line. Give it into the anterolateral thigh. It can be repeated every 5 to 15 minutes. Undiluted IV bolus epinephrine causes dangerous hypertension and arrhythmia. Antihistamines and steroids do not treat airway edema or shock.",
        keyFeature: { topic: "anaphylaxis", n: 3 },
        source: "wao-ana",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "After two IM epinephrine doses 5 minutes apart her BP is 80/46 mmHg and her stridor is louder.",
        prompt: "What are the next interventions?",
        accept: [
          { id: "infusion", text: "Epinephrine infusion titrated to effect", match: ["epinephrine infusion", "epinephrine drip", "epi infusion", "epi drip", "adrenaline infusion"] },
          { id: "fluid", text: "Crystalloid bolus 1 to 2 L IV", match: ["fluid", "saline", "crystalloid", "ringer", "bolus"] },
          { id: "airway", text: "Prepare early intubation by the most experienced operator with a surgical airway backup", match: ["intubate", "intubation", "airway", "cricothyrotomy", "surgical airway"] },
          { id: "neb", text: "Nebulized epinephrine for stridor", match: ["nebulized epinephrine", "neb epi", "nebulized epi", "racemic"] },
          { id: "position", text: "Lay her supine with legs raised", match: ["supine", "legs raised", "leg raise", "trendelenburg"] },
          { id: "help", text: "Call anesthesia or ENT", match: ["anesthesia", "anaesthesia", "ent"] },
          { id: "third", text: "Third IM epinephrine dose while the infusion is prepared", match: ["third dose", "repeat im", "repeat epinephrine", "another im"] },
        ],
        unacceptable: [{ text: "Antihistamine or steroid as the main next step", match: ["diphenhydramine", "antihistamine", "steroid", "methylprednisolone"] }],
        explanation:
          "Refractory anaphylaxis after two IM doses needs an epinephrine infusion and aggressive fluid, because distributive shock involves large fluid shifts. Worsening stridor predicts a rapidly closing airway, so plan an early, experienced intubation with front of neck access ready. She may need to sit up for her airway, so position her with care.",
        keyFeature: { topic: "airway", n: 2 },
        source: "wao-ana",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "She improves and is observed overnight. The next morning she is well.",
        prompt: "What items belong in her discharge plan?",
        accept: [
          { id: "ai", text: "Prescribe an epinephrine autoinjector, ideally two", match: ["autoinjector", "auto injector", "epipen", "allerject", "emerade"] },
          { id: "teach", text: "Teach when and how to use the autoinjector", match: ["teach", "training", "how to use", "technique"] },
          { id: "avoid", text: "Avoid shellfish until assessed", match: ["avoid", "shellfish", "shrimp"] },
          { id: "allergy", text: "Referral to an allergist", match: ["allergist", "allergy referral", "allergy clinic", "immunology", "allergy follow"] },
          { id: "biphasic", text: "Return immediately for recurrent symptoms, as biphasic reactions can occur", match: ["biphasic", "return", "recurrence"] },
          { id: "alert", text: "Medical alert identification", match: ["medical alert", "medicalert", "bracelet"] },
          { id: "plan", text: "Written anaphylaxis action plan", match: ["action plan", "written plan"] },
        ],
        explanation:
          "Every patient with anaphylaxis leaves with an epinephrine autoinjector, training in its use and an allergy referral. Avoidance of the likely trigger continues until testing. Patients should know that symptoms can recur and that they must use epinephrine and call 9-1-1.",
        keyFeature: { topic: "anaphylaxis", n: 4 },
        source: "wao-ana",
      },
    ],
    sources: [S.waoAna],
    ...META,
  },
];
