import type { Samp } from "@/engine/samp";
import { BANK_BLOB } from "./generated/encoded";

/**
 * Decodes the obfuscated SAMP snapshot generated by
 * scripts/build-bank-cache.mjs (held-back SAMPs already excluded there).
 * Mirrors that script's xor() exactly — keep the two in sync. Not
 * encryption, see that script's header comment.
 *
 * Runs fully offline: base64 + XOR + JSON.parse, no fetch, no native API.
 */
const KEY = "preceptor-ccfpem-samps-v1";

function fromBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function xor(bytes: Uint8Array, key: string): Uint8Array {
  const keyBytes = new TextEncoder().encode(key);
  const out = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) out[i] = bytes[i] ^ keyBytes[i % keyBytes.length];
  return out;
}

let cached: Samp[] | null = null;

/** The shipped SAMP bank (held-back SAMPs already excluded), decoded once and cached. */
export function decodedSamps(): Samp[] {
  if (!cached) {
    const json = new TextDecoder().decode(xor(fromBase64(BANK_BLOB), KEY));
    cached = JSON.parse(json) as Samp[];
  }
  return cached;
}
