// DRAFT. Written for exam practice only. Requires physician review before release.
//
// The real, plaintext SAMP bank, held-back filtering included.
// src/samps/index.ts (what the app and most of the code import) is an
// obfuscated snapshot of exactly this file's SAMPS, generated by
// scripts/build-bank-cache.mjs. Tests and content-pipeline tools that need
// the per-batch structure (SAMP_BATCHES), the unfiltered set
// (AUTHORED_SAMPS) or HELD_BACK import this file directly; nothing else
// should.

import type { Samp } from "@/engine/samp";
import { AUTHORED_SAMPS, SAMP_BATCHES } from "./batches";

export { AUTHORED_SAMPS, SAMP_BATCHES };

const heldBackFiles = import.meta.glob<{ ids: Record<string, string> }>("./held-back/*.json", { eager: true, import: "default" });

/** Ids held back from the release until they have a fresh sign-off. See held-back/README.md. */
export const HELD_BACK = new Set<string>(Object.values(heldBackFiles).flatMap((f) => Object.keys(f.ids)));

/** The SAMPs the app shows. Held-back SAMPs are left out. */
export const SAMPS: Samp[] = AUTHORED_SAMPS.filter((s) => !HELD_BACK.has(s.id));

export function getSamp(id: string): Samp | undefined {
  return SAMPS.find((s) => s.id === id);
}
