import type { ItemMeta, Source } from "@/engine/types";

/** Shared defaults for batch c18 items. */
export const meta = (id: string, over: Partial<ItemMeta>): ItemMeta => ({
  id,
  need: "PA",
  topic: "",
  cjmm: "recognize",
  process: "clinical-judgment",
  difficulty: 3,
  stem: "",
  rationale: "",
  sources: [],
  canada: "",
  reviewed: false,
  version: 1,
  ...over,
});

export const SRC: Record<string, Source> = {
  adaFoot: {
    body: "American Diabetes Association Professional Practice Committee",
    work: "12. Retinopathy, Neuropathy, and Foot Care: Standards of Care in Diabetes 2026. Diabetes Care 49(Suppl 1):S261",
    year: 2026,
    url: "https://pubmed.ncbi.nlm.nih.gov/41358886/",
  },
  adaCkd: {
    body: "American Diabetes Association Professional Practice Committee",
    work: "11. Chronic Kidney Disease and Risk Management: Standards of Care in Diabetes 2026. Diabetes Care 49(Suppl 1):S246",
    year: 2026,
    url: "https://pubmed.ncbi.nlm.nih.gov/41358881/",
  },
  adaCv: {
    body: "American Diabetes Association Professional Practice Committee",
    work: "10. Cardiovascular Disease and Risk Management: Standards of Care in Diabetes 2026. Diabetes Care 49(Suppl 1):S216",
    year: 2026,
    url: "https://pubmed.ncbi.nlm.nih.gov/41358899/",
  },
  adaGlyc: {
    body: "American Diabetes Association Professional Practice Committee",
    work: "6. Glycemic Goals, Hypoglycemia, and Hyperglycemic Crises: Standards of Care in Diabetes 2026. Diabetes Care 49(Suppl 1):S132",
    year: 2026,
    url: "https://pubmed.ncbi.nlm.nih.gov/41358894",
  },
  zestril: {
    body: "AstraZeneca. US Food and Drug Administration",
    work: "Zestril (lisinopril) tablets prescribing information",
    year: 2017,
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/019777s076lbl.pdf",
  },
  acogAnemia: {
    body: "American College of Obstetricians and Gynecologists",
    work: "Anemia in Pregnancy. ACOG Practice Bulletin No. 233. Obstetrics and Gynecology 138(2):e55",
    year: 2021,
    url: "https://pubmed.ncbi.nlm.nih.gov/34293770/",
  },
  acogRh: {
    body: "American College of Obstetricians and Gynecologists",
    work: "Prevention of Rh D Alloimmunization. ACOG Practice Bulletin No. 181. Obstetrics and Gynecology 130(2):e57",
    year: 2017,
    url: "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2017/08/prevention-of-rh-d-alloimmunization",
  },
  aspirin: {
    body: "US Preventive Services Task Force",
    work: "Aspirin Use to Prevent Preeclampsia and Related Morbidity and Mortality: Recommendation Statement. JAMA 326(12):1186",
    year: 2021,
    url: "https://jamanetwork.com/journals/jama/fullarticle/2784499",
  },
  folic: {
    body: "US Preventive Services Task Force",
    work: "Folic Acid Supplementation to Prevent Neural Tube Defects: Reaffirmation Recommendation Statement. JAMA 330(5):454",
    year: 2023,
    url: "https://pubmed.ncbi.nlm.nih.gov/37526713/",
  },
  mmrAcip: {
    body: "McLean HQ, Fiebelkorn AP, Temte JL, Wallace GS. Advisory Committee on Immunization Practices",
    work: "Prevention of Measles, Rubella, Congenital Rubella Syndrome, and Mumps, 2013. MMWR Recommendations and Reports 62(RR-4):1",
    year: 2013,
    url: "https://www.cdc.gov/mmwr/preview/mmwrhtml/rr6204a1.htm",
  },
  tobacco: {
    body: "Krist AH, Davidson KW, Mangione CM, et al. US Preventive Services Task Force",
    work: "Interventions for Tobacco Smoking Cessation in Adults, Including Pregnant Persons. JAMA 325(3):265",
    year: 2021,
    url: "https://pubmed.ncbi.nlm.nih.gov/33464343/",
  },
  nvp: {
    body: "American College of Obstetricians and Gynecologists",
    work: "ACOG Practice Bulletin No. 189: Nausea and Vomiting of Pregnancy. Obstetrics and Gynecology 131(1):e15",
    year: 2018,
    url: "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2018/01/nausea-and-vomiting-of-pregnancy",
  },
  toxo: {
    body: "US Food and Drug Administration",
    work: "Toxoplasma: Food Safety for Moms-to-Be",
    year: 2018,
    url: "https://www.fda.gov/food/people-risk-foodborne-illness/toxoplasma-food-safety-moms-be",
  },
  lowdermilk: {
    body: "Lowdermilk DL, Cashion K, Alden KR, Olshansky E, Perry SE",
    work: "Maternity and Women's Health Care, 13th edition",
    year: 2023,
    url: "https://www.us.elsevierhealth.com/maternity-and-womens-health-care-9780323810180.html",
  },
  sti: {
    body: "Workowski KA, Bachmann LH, Chan PA, et al. Centers for Disease Control and Prevention",
    work: "Sexually Transmitted Infections Treatment Guidelines, 2021. MMWR Recommendations and Reports 70(4):1",
    year: 2021,
    url: "https://pubmed.ncbi.nlm.nih.gov/34292926/",
  },
  heeadsss: {
    body: "Klein DA, Goldenring JM, Adelman WP",
    work: "HEEADSSS 3.0: The psychosocial interview for adolescents updated for a new century fueled by media. Contemporary Pediatrics 31(1):16",
    year: 2014,
    url: "https://www.contemporarypediatrics.com/view/heeadsss-30-psychosocial-interview-adolescents-updated-new-century-fueled-media",
  },
  doxy: {
    body: "Pfizer Labs. US Food and Drug Administration",
    work: "Vibramycin and Vibra-Tabs (doxycycline) prescribing information",
    year: 2025,
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/050006s096,050007s040,050480s064,050533s051lbl.pdf",
  },
  condom: {
    body: "Centers for Disease Control and Prevention",
    work: "Condom Use: An Overview",
    year: 2024,
    url: "https://www.cdc.gov/condom-use/index.html",
  },
  condomHow: {
    body: "Centers for Disease Control and Prevention",
    work: "How to Use a Condom",
    year: 2024,
    url: "https://www.cdc.gov/condom-use/resources/external.html",
  },
  iwgdf: {
    body: "Bus SA, Sacco ICN, Monteiro-Soares M, et al. International Working Group on the Diabetic Foot",
    work: "Guidelines on the prevention of foot ulcers in persons with diabetes (IWGDF 2023 update). Diabetes/Metabolism Research and Reviews 40(3):e3651",
    year: 2024,
    url: "https://pubmed.ncbi.nlm.nih.gov/37302121/",
  },
  catchup: {
    body: "Centers for Disease Control and Prevention",
    work: "Catch-up Immunization Schedule for Children and Adolescents Who Start Late or Who Are More than 1 Month Behind, United States, 2025",
    year: 2025,
    url: "https://www.cdc.gov/vaccines/hcp/imz-schedules/child-adolescent-catch-up.html",
  },
  bestPractice: {
    body: "Centers for Disease Control and Prevention",
    work: "Epidemiology and Prevention of Vaccine-Preventable Diseases (Pink Book), Chapter 2: General Best Practice Guidance for Immunization",
    year: 2024,
    url: "https://www.cdc.gov/pinkbook/hcp/table-of-contents/chapter-2-general-best-practice-guidance.html",
  },
  refugeeImz: {
    body: "Centers for Disease Control and Prevention",
    work: "Immunizations: Refugee Health Domestic Guidance",
    year: 2024,
    url: "https://www.cdc.gov/immigrant-refugee-health/hcp/domestic-guidance/immunizations.html",
  },
  storage: {
    body: "Centers for Disease Control and Prevention",
    work: "Vaccine Storage and Handling Toolkit, July 2026 edition",
    year: 2026,
    url: "https://www.cdc.gov/vaccines/hcp/downloads/storage-handling-toolkit.pdf",
  },
  varivax: {
    body: "Merck Sharp and Dohme. US Food and Drug Administration",
    work: "Varivax (varicella virus vaccine live) prescribing information",
    year: 2023,
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=524cf052-e90e-4595-af0a-608edbe9bd31",
  },
  mmrLabel: {
    body: "Merck Sharp and Dohme. US Food and Drug Administration",
    work: "M-M-R II (measles, mumps, and rubella virus vaccine live) prescribing information",
    year: 2023,
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0a9e384f-e717-436b-b9a0-15e53cef0862",
  },
  ahrq: {
    body: "Agency for Healthcare Research and Quality",
    work: "Health Literacy Universal Precautions Toolkit, 3rd edition",
    year: 2024,
    url: "https://www.ahrq.gov/health-literacy/improve/precautions/toolkit.html",
  },
  wong: {
    body: "Hockenberry MJ, Duffy EA, Gibbs KD",
    work: "Wong's Nursing Care of Infants and Children, 12th edition",
    year: 2023,
    url: "https://www.us.elsevierhealth.com/wongs-nursing-care-of-infants-and-children-9780323776707.html",
  },
  beers: {
    body: "American Geriatrics Society Beers Criteria Update Expert Panel",
    work: "American Geriatrics Society 2023 updated AGS Beers Criteria for potentially inappropriate medication use in older adults. Journal of the American Geriatrics Society 71(7):2052",
    year: 2023,
    url: "https://pubmed.ncbi.nlm.nih.gov/37139824/",
  },
  stopp: {
    body: "O'Mahony D, Cherubini A, Guiteras AR, et al.",
    work: "STOPP/START criteria for potentially inappropriate prescribing in older people: version 3. European Geriatric Medicine 14(4):625",
    year: 2023,
    url: "https://pubmed.ncbi.nlm.nih.gov/37256475/",
  },
  orthostatic: {
    body: "Freeman R, Wieling W, Axelrod FB, et al.",
    work: "Consensus Statement on the Definition of Orthostatic Hypotension, Neurally Mediated Syncope and the Postural Tachycardia Syndrome. Clinical Autonomic Research 21(2):69",
    year: 2011,
    url: "https://pubmed.ncbi.nlm.nih.gov/21431947/",
  },
  falls: {
    body: "Montero-Odasso M, van der Velde N, Martin FC, et al. Task Force on Global Guidelines for Falls in Older Adults",
    work: "World guidelines for falls prevention and management for older adults. Age and Ageing 51(9):afac205",
    year: 2022,
    url: "https://pubmed.ncbi.nlm.nih.gov/36178003/",
  },
};
