// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const toddlerAirwayForeignBody: OralCase = {
  id: "toddler-airway-foreign-body",
  title: "Trouble breathing at a birthday party",
  blueprint: "peds",
  priorityTopic: "airway",
  keyFeatures: [
    { topic: "airway", n: 1 },
    { topic: "airway", n: 3 },
    { topic: "airway", n: 4 },
    { topic: "sob", n: 1 },
    { topic: "asthma-copd", n: 1 },
  ],
  summary: "A 22 month old is carried in by her mother after a sudden coughing fit at a family party.",
  durationMinutes: 13,
  stem:
    "You are working in a suburban community emergency department in Ontario on a Saturday afternoon. The anesthetist is in the hospital. ENT is on call from home but there is no pediatric ENT surgeon on site. The regional children's hospital is 40 minutes away. " +
    "Amelia Santos is 22 months old. Her mother carries her through the ambulance doors. Ten minutes ago at a birthday party she was eating from a fruit tray, started coughing hard and could not settle. " +
    "Triage vitals: heart rate 172, respiratory rate 40, SpO2 92 percent on room air, temperature 36.8 degrees C. Weight 11.5 kg. CTAS 1. " +
    "The triage nurse says: 'She is coughing and crying and has noisy breathing when she breathes in. Mom did some back slaps in the car. There were whole grapes on the tray.'",
  findings: [
    {
      id: "appearance",
      label: "Appearance on arrival",
      result: "Upright on her mother's lap. Frightened. Strong cough. Crying with a hoarse voice. Pink. Drooling slightly.",
    },
    {
      id: "resp",
      label: "Respiratory exam on arrival",
      result: "Inspiratory stridor. Moderate suprasternal retractions. Air entry present on both sides. No wheeze.",
    },
    {
      id: "history",
      label: "History",
      result:
        "Witnessed sudden choking while eating whole grapes and cheese cubes at 14:20. No fever or cold symptoms before. No allergies. Healthy. Immunizations up to date.",
    },
    {
      id: "mouth",
      label: "Mouth seen while she cries",
      result: "No object visible in the mouth or front of the oropharynx when she opens her mouth to cry. No swelling of the lips or tongue. No urticaria.",
    },
    {
      id: "post-vitals",
      label: "Vitals after removal",
      result: "Heart rate 148. SpO2 97 percent on 10 L/min by mask. Respiratory rate 32. Blood pressure 94/56. Crying and moving all limbs.",
    },
    {
      id: "post-exam",
      label: "Chest exam 30 minutes later",
      result: "Decreased air entry over the right lower chest with a fixed monophonic wheeze on the right. Left side clear. SpO2 93 percent on room air.",
    },
    {
      id: "cxr",
      label: "Chest X ray with bilateral decubitus views",
      result: "Inspiratory film nearly normal. On the right side down decubitus view the right lung stays hyperinflated, consistent with air trapping. No radio opaque object. No pneumothorax.",
    },
    { id: "glucose", label: "Point of care glucose", result: "Capillary glucose 6.8 mmol/L after the event." },
    {
      id: "vbg",
      label: "Venous blood gas after removal",
      result: "pH 7.24. pCO2 52 mmHg. Bicarbonate 21 mmol/L. Lactate 3.2 mmol/L.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "In the resuscitation bay",
      text: "Amelia is coughing hard on her mother's lap. She has stridor and is crying. A nurse is reaching for a tongue depressor.",
      next: "q-first",
    },
    {
      kind: "question",
      id: "q-first",
      phase: "First two minutes",
      prompt: "What is your assessment and what do you do right now?",
      seconds: 75,
      modelAnswer: [
        "Upper airway foreign body with partial obstruction and an effective cough.",
        "Leave her upright on her mother's lap. Encourage coughing. Do not intervene with thrusts while the cough is effective.",
        "No tongue depressor, no blind finger sweeps and do not lay her flat.",
        "Oxygen held near her face.",
        "Call the anesthetist and ENT now. Set up suction, a laryngoscope, Magill forceps, small tubes and a needle cricothyroidotomy kit.",
      ],
      rubric: ["fb-a1", "fb-r1", "fb-l1"],
      choices: [
        {
          id: "c-comfort",
          label: "I left her upright with mom, encouraged her to cough, gave blow by oxygen, and called anesthesia and ENT while the team set up Magill forceps and airway equipment.",
          next: "s-complete",
          quality: "strong",
          feedback:
            "Correct. An effective cough clears more than any manoeuvre. Your job is to avoid turning a partial obstruction into a complete one and to be ready if it happens.",
        },
        {
          id: "c-look",
          label: "I laid her flat and looked in her mouth with a tongue depressor to find the object.",
          next: "s-look",
          quality: "partial",
          feedback:
            "Lying her flat and upsetting her can move the object into a worse position. A tongue depressor is unlikely to help. Keep her upright and let her cough.",
        },
        {
          id: "c-thrusts",
          label: "I started abdominal thrusts right away because she was choking.",
          next: "s-look",
          quality: "unsafe",
          feedback:
            "Thrusts are for an ineffective cough, a silent child or one who cannot breathe. With a strong cough and crying, thrusts can convert a partial obstruction into a complete one.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-look",
      phase: "Seconds later",
      text: "She gags and struggles. Her crying stops abruptly. The nurse sits her back up.",
      next: "s-complete",
    },
    {
      kind: "say",
      id: "s-complete",
      phase: "Three minutes after arrival",
      text: "Amelia suddenly goes silent. She is clutching at her throat with her mouth open. She cannot cough or cry. Her lips are blue. SpO2 78 percent and falling. She is still conscious.",
      next: "q-complete",
    },
    {
      kind: "question",
      id: "q-complete",
      phase: "Complete obstruction",
      prompt: "What do you do now?",
      seconds: 60,
      modelAnswer: [
        "Complete obstruction with an ineffective cough in a conscious child over 1 year.",
        "Give cycles of 5 back blows and 5 abdominal thrusts until the object comes out or she becomes unresponsive.",
        "Call a code blue. Anesthetist to the bedside now.",
        "No blind finger sweeps.",
        "Have the laryngoscope and Magill forceps in hand for when she becomes unresponsive.",
      ],
      rubric: ["fb-r2"],
      choices: [
        {
          id: "c-abdo",
          label: "I gave cycles of 5 back blows and 5 abdominal thrusts, called a code blue and had the laryngoscope and Magill forceps ready.",
          next: "s-unresponsive",
          quality: "strong",
          feedback:
            "Correct for a conscious child over 1 year with an ineffective cough. Alternating 5 back blows and 5 abdominal thrusts matches Canadian first aid teaching and the 2025 AHA update. The equipment in hand means no delay if she collapses.",
        },
        {
          id: "c-sweep",
          label: "I did a blind finger sweep to try to hook it out.",
          next: "s-sweep",
          quality: "unsafe",
          feedback:
            "Blind finger sweeps can push the object deeper and injure the pharynx. Remove an object only if you can see it. Back blows and abdominal thrusts are the right step.",
        },
        {
          id: "c-bag",
          label: "I tried bag mask ventilation while she was still conscious.",
          next: "s-sweep",
          quality: "partial",
          feedback:
            "A conscious child with complete obstruction will fight the mask and air will not pass the object. Back blows and abdominal thrusts come first. Ventilation is part of CPR once she is unresponsive.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-sweep",
      phase: "Thirty seconds later",
      text: "Nothing changes. The anesthetist arrives and starts back blows and abdominal thrusts. She becomes floppy.",
      next: "s-unresponsive",
    },
    {
      kind: "say",
      id: "s-unresponsive",
      phase: "Collapse",
      text: "Amelia becomes unresponsive. Heart rate 58. SpO2 is unreadable. The object has not come out.",
      next: "q-unresponsive",
    },
    {
      kind: "question",
      id: "q-unresponsive",
      phase: "Unresponsive",
      prompt: "She is unresponsive with a heart rate of 58. Walk me through exactly what you do.",
      seconds: 90,
      modelAnswer: [
        "Lay her flat and start CPR. Compressions can dislodge the object. Bradycardia under 60 with poor perfusion needs compressions.",
        "Immediate direct or video laryngoscopy. If the object is seen, remove it with Magill forceps.",
        "If it is below the cords and cannot be removed, intubate and push it into the right mainstem, then pull the tube back and ventilate the left lung.",
        "If you cannot ventilate and cannot remove an object above the cords, needle cricothyroidotomy is the rescue in a child this age. With the upper airway blocked, gas cannot escape upward, so use small breaths, watch the chest fall and get ENT for a surgical airway.",
        "Do not do a scalpel cricothyrotomy in a toddler. The cricothyroid membrane is too small.",
      ],
      rubric: ["fb-r3", "fb-r4"],
      choices: [
        {
          id: "c-magill",
          label: "I laid her flat, started CPR, did laryngoscopy right away and pulled the grape out with Magill forceps, then ventilated with bag mask.",
          next: "s-removed",
          quality: "strong",
          feedback:
            "Correct. Direct visualization and Magill forceps are the definitive step for an upper airway object. You also knew the next steps if it had been below the cords.",
        },
        {
          id: "c-scalpel",
          label: "I went straight to a scalpel cricothyrotomy.",
          next: "s-scalpel",
          quality: "unsafe",
          feedback:
            "A scalpel cricothyrotomy is not recommended in young children. The membrane is tiny and the larynx is easily injured. Look first. If you cannot remove the object or ventilate, needle cricothyroidotomy is the rescue.",
        },
        {
          id: "c-more-thrusts",
          label: "I kept doing abdominal thrusts on the stretcher.",
          next: "s-scalpel",
          quality: "partial",
          feedback:
            "Once a child is unresponsive, switch to CPR and look in the airway. In the ED you have a laryngoscope and Magill forceps. Direct removal is faster and more reliable.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-scalpel",
      phase: "Seconds later",
      text: "The anesthetist asks you to stop and hands you a laryngoscope. You see a whole grape wedged at the laryngeal inlet and remove it with Magill forceps. CPR is running.",
      next: "s-removed",
    },
    {
      kind: "say",
      id: "s-removed",
      phase: "Two minutes later",
      text: "With bag mask ventilation her heart rate rises to 148 and her SpO2 to 97 percent. She starts to cry and breathe on her own. Her mother is sobbing in the corner with a nurse.",
      next: "q-post",
    },
    {
      kind: "question",
      id: "q-post",
      phase: "After removal",
      prompt: "The grape is out and she is crying. What now? Can she go home after a period of observation?",
      seconds: 75,
      modelAnswer: [
        "Reassess airway, breathing and neurological status. Check glucose and a blood gas.",
        "Examine the chest carefully for asymmetry, wheeze or reduced air entry.",
        "Chest X ray to look for residual objects, air trapping, aspiration and pneumothorax.",
        "Watch for negative pressure pulmonary edema.",
        "She needed CPR for hypoxic bradycardia. She needs admission and monitoring, not discharge.",
      ],
      rubric: ["fb-a2", "fb-d1"],
      next: "s-residual",
    },
    {
      kind: "say",
      id: "s-residual",
      phase: "Thirty minutes later",
      text:
        "Amelia is sitting up and alert. But now her SpO2 is 93 percent on room air. There is reduced air entry on the right with a fixed wheeze. " +
        "The decubitus films show air trapping in the right lung. The grape was whole. Her mother remembers she had also been eating peanuts from a bowl on the coffee table.",
      next: "q-residual",
    },
    {
      kind: "question",
      id: "q-residual",
      phase: "A second problem",
      prompt: "What do you think is going on and what is your plan?",
      seconds: 75,
      modelAnswer: [
        "A second foreign body in the right bronchus, likely a peanut, causing a ball valve effect.",
        "Unilateral wheeze and air trapping after a choking episode are enough. A normal inspiratory film does not exclude it.",
        "She needs rigid bronchoscopy under general anesthesia.",
        "No pediatric ENT here. Arrange transfer to the children's hospital through CritiCall with a monitored escort.",
        "Keep her calm, NPO and on oxygen. Avoid positive pressure unless needed.",
      ],
      rubric: ["fb-a3", "fb-d2"],
      choices: [
        {
          id: "c-bronch",
          label: "I suspected a second bronchial foreign body and arranged urgent transfer through CritiCall for rigid bronchoscopy, keeping her NPO and on oxygen.",
          next: "q-family",
          quality: "strong",
          feedback:
            "Correct. Unilateral findings after choking mean a bronchial foreign body until proven otherwise. Peanuts are common and can cause inflammation within hours. Rigid bronchoscopy is diagnostic and therapeutic.",
        },
        {
          id: "c-salbutamol",
          label: "I treated it as bronchospasm with salbutamol and planned to reassess in the morning.",
          next: "s-salbutamol",
          quality: "partial",
          feedback:
            "A fixed one sided wheeze after choking is not asthma. Salbutamol delays the diagnosis. The examiner wanted a bronchoscopy plan.",
        },
        {
          id: "c-discharge",
          label: "I discharged her home because the chest X ray was nearly normal.",
          next: "s-salbutamol",
          quality: "unsafe",
          feedback:
            "Most aspirated foods are radiolucent and the inspiratory film is often normal. A missed bronchial foreign body can cause pneumonia, abscess or sudden obstruction. She needs bronchoscopy.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-salbutamol",
      phase: "Two hours later",
      text: "Her wheeze has not changed and her SpO2 is 91 percent. The pediatrician on call asks whether a bronchial foreign body has been considered. You call CritiCall and arrange transfer for rigid bronchoscopy.",
      next: "q-family",
    },
    {
      kind: "question",
      id: "q-family",
      phase: "Family",
      prompt: "Her mother says she should never have let her eat at the party. What do you say, and what prevention advice do you give?",
      seconds: 60,
      modelAnswer: [
        "Acknowledge how frightening this was. She acted quickly and brought her straight in.",
        "Avoid blame.",
        "Cut grapes lengthwise into quarters for children under 4 years.",
        "No whole nuts, popcorn or hard candy for children under 4 years.",
        "Children should sit to eat and be supervised.",
        "Offer information on a first aid course that teaches choking response.",
      ],
      rubric: ["fb-c1", "fb-c2"],
      next: "q-debrief",
    },
    {
      kind: "question",
      id: "q-debrief",
      phase: "The team",
      prompt: "After she leaves, one of the nurses is shaken. How do you close this event with your team?",
      seconds: 60,
      modelAnswer: [
        "Hold a short hot debrief while details are fresh.",
        "Review what went well and what could improve, such as where the Magill forceps were stored.",
        "Check on staff wellbeing and offer peer support resources.",
        "Complete documentation with times of arrest, interventions and removal.",
        "Share learning with the department.",
      ],
      rubric: ["fb-l2"],
      next: "end",
    },
    {
      kind: "end",
      id: "end",
      text: "Amelia is transferred. At bronchoscopy half a peanut is removed from the right bronchus intermedius. She goes home two days later. That is the end of the case.",
    },
  ],
  rubric: [
    {
      id: "fb-a1",
      competency: "assessment",
      criterion: "approach",
      text: "Recognizes partial upper airway obstruction with an effective cough.",
      points: 2,
      teaching: "A child who can cough, cry or speak is moving air. The cough is the best tool for clearing the object.",
      source: "ilcor-fb",
    },
    {
      id: "fb-r1",
      competency: "resuscitation",
      criterion: "plan",
      text: "Keeps the child upright with the parent and avoids thrusts, finger sweeps and tongue depressors while the cough is effective.",
      points: 3,
      critical: true,
      teaching: "Interventions during partial obstruction can convert it to complete obstruction. Support and prepare instead.",
      source: "ilcor-fb",
    },
    {
      id: "fb-l1",
      competency: "leadership",
      criterion: "plan",
      text: "Calls anesthesia and ENT early and prepares laryngoscope, Magill forceps, suction, small tubes and a needle cricothyroidotomy kit.",
      points: 2,
      teaching: "Partial obstruction can become complete at any moment. Have the rescue equipment in the room before it is needed.",
      source: "apls",
    },
    {
      id: "fb-r2",
      competency: "resuscitation",
      criterion: "plan",
      text: "Gives back blows and abdominal thrusts for a conscious child over 1 year with an ineffective cough.",
      points: 2,
      teaching: "An ineffective cough, silence or cyanosis means severe obstruction. Alternate 5 back blows with 5 abdominal thrusts. Infants under 1 year get chest thrusts instead of abdominal thrusts.",
      source: "ilcor-fb",
    },
    {
      id: "fb-r3",
      competency: "resuscitation",
      criterion: "plan",
      text: "Starts CPR when the child becomes unresponsive and performs immediate laryngoscopy with Magill forceps removal.",
      points: 3,
      critical: true,
      teaching: "In the ED the fastest definitive step is to look and remove. Compressions may also move the object.",
      source: "aha-pals",
    },
    {
      id: "fb-r4",
      competency: "resuscitation",
      criterion: "plan",
      text: "States the backup plans: push a subglottic object into the right mainstem, and use needle rather than scalpel cricothyroidotomy in a young child.",
      points: 2,
      teaching: "Pushing the object into one bronchus lets you ventilate the other lung. The cricothyroid membrane is too small for a scalpel technique in toddlers, and needle oxygenation with a blocked upper airway risks barotrauma.",
      source: "apls",
    },
    {
      id: "fb-a2",
      competency: "assessment",
      criterion: "approach",
      text: "Reassesses after removal and looks for residual objects, air trapping, aspiration and negative pressure pulmonary edema.",
      points: 2,
      teaching: "Children often aspirate more than one piece. A careful chest exam and imaging after removal can find a second object.",
      source: "apls",
    },
    {
      id: "fb-d1",
      competency: "disposition",
      criterion: "plan",
      text: "Admits the child for monitoring after an obstruction that caused an arrest.",
      points: 1,
      teaching: "A brief hypoxic arrest needs observation for neurological, respiratory and cardiac complications.",
      source: "aha-pals",
    },
    {
      id: "fb-a3",
      competency: "assessment",
      criterion: "diagnosis",
      text: "Suspects a bronchial foreign body from unilateral wheeze, reduced air entry and air trapping despite a nearly normal inspiratory film.",
      points: 3,
      critical: true,
      teaching: "Most food foreign bodies are radiolucent. Air trapping on expiratory or decubitus views is a clue, but a normal film does not exclude it.",
      source: "apls",
    },
    {
      id: "fb-d2",
      competency: "disposition",
      criterion: "plan",
      text: "Arranges rigid bronchoscopy under general anesthesia, transferring through CritiCall if pediatric ENT is not available.",
      points: 2,
      teaching: "Rigid bronchoscopy is diagnostic and therapeutic. Organic material like peanuts swells and inflames the airway over hours.",
      source: "apls",
    },
    {
      id: "fb-c1",
      competency: "communication",
      criterion: "plan",
      text: "Supports the parent without blame and acknowledges her quick action.",
      points: 1,
      teaching: "Parents often feel guilt after a choking event. Recognizing what they did well helps them absorb safety advice.",
      source: "cps-choking",
    },
    {
      id: "fb-c2",
      competency: "communication",
      criterion: "plan",
      text: "Gives specific prevention advice: quarter grapes lengthwise, no whole nuts, popcorn or hard candy under 4 years, and supervised seated eating.",
      points: 2,
      teaching: "Round, firm foods are the most common fatal choking hazards in young children. Specific advice is more useful than general warnings.",
      source: "cps-choking",
    },
    {
      id: "fb-l2",
      competency: "leadership",
      criterion: "plan",
      text: "Leads a brief team debrief and checks on staff wellbeing after a pediatric arrest.",
      points: 1,
      teaching: "Pediatric arrests are distressing for staff. A short debrief supports the team and captures system lessons.",
      source: "aha-pals",
    },
  ],
  sources: [
    {
      id: "ilcor-fb",
      citation: "American Heart Association. 2025 Guidelines for CPR and ECC. Part 6. Pediatric basic life support. Foreign body airway obstruction.",
    },
    {
      id: "aha-pals",
      citation: "American Heart Association. 2025 Guidelines for CPR and ECC. Part 8. Pediatric advanced life support.",
    },
    { id: "apls", citation: "Advanced Life Support Group. Advanced Paediatric Life Support. A practical approach to emergencies." },
    { id: "cps-choking", citation: "Canadian Paediatric Society. Preventing choking and suffocation in children. Position statement. 2012." },
  ],
  reviewed: false,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 1,
};
