// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Preceptor", version: 1 } as const;

const S = {
  asra: { id: "asra-last", citation: "Neal JM, et al. The third American Society of Regional Anesthesia and Pain Medicine practice advisory on local anesthetic systemic toxicity. Executive summary 2017. Reg Anesth Pain Med. 2018." },
  green: { id: "green-ketamine", citation: "Green SM, Roback MG, Kennedy RM, Krauss B. Clinical practice guideline for emergency department ketamine dissociative sedation. 2011 update. Ann Emerg Med. 2011." },
  cigTet: { id: "cig-tetanus", citation: "Public Health Agency of Canada. Canadian Immunization Guide. Part 4. Tetanus toxoid. Tetanus prophylaxis in wound management. 2026.", url: "https://www.canada.ca/en/public-health/services/publications/healthy-living/canadian-immunization-guide-part-4-active-vaccines/page-22-tetanus-toxoid.html" },
  cigRab: { id: "cig-rabies", citation: "Public Health Agency of Canada. Canadian Immunization Guide. Part 4. Rabies vaccine. Post-exposure prophylaxis. 2026.", url: "https://www.canada.ca/en/public-health/services/publications/healthy-living/canadian-immunization-guide-part-4-active-vaccines/page-18-rabies-vaccine.html" },
  onRabies: { id: "on-rabies", citation: "Ontario Ministry of Health. Management of Potential Rabies Exposures Guideline. 2020.", url: "https://files.ontario.ca/moh-guidelines-management-of-potential-rabies-exposures-guideline-en-2020.pdf" },
  hppa: { id: "hppa", citation: "Health Protection and Promotion Act, R.S.O. 1990, c. H.7, and its regulation on communicable diseases (Ontario). Duty to report animal bites to the medical officer of health." },
  idsa: { id: "idsa-ssti", citation: "Stevens DL, et al. Practice guidelines for the diagnosis and management of skin and soft tissue infections. 2014 update by the Infectious Diseases Society of America. Clin Infect Dis. 2014." },
  singer: { id: "singer-nejm", citation: "Singer AJ, Hollander JE, Quinn JV. Evaluation and management of traumatic lacerations. N Engl J Med. 1997." },
  water: { id: "cochrane-water", citation: "Fernandez R, Green HL, Griffiths R, Atkinson RA, Ellwood LJ. Water for wound cleansing. Cochrane Database Syst Rev. 2022.", url: "https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD003861.pub4/full" },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. 10th ed. Elsevier. 2023. Chapters on wound management, hand injuries and mammalian bites." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, Ma OJ, Yealy DM, Meckler GD, Stapczynski JS, Cline DM, Thomas SH, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. 9th ed. McGraw Hill. 2020. Chapter 36, Local and Regional Anesthesia. Chapter 39, Wound Evaluation. Chapter 42, Face and Scalp Lacerations. Chapter 43, Arm, Forearm, and Hand Lacerations. Chapter 44, Thigh, Leg, and Foot Lacerations. Chapter 45, Soft Tissue Foreign Bodies. Chapter 46, Puncture Wounds and Bites. Chapter 268, Injuries to the Hand and Digits." },
  konda: { id: "konda-ct", citation: "Konda SR, et al. Computed tomography scan to detect traumatic arthrotomies of the knee joint. J Bone Joint Surg Am. 2013." },
  cchr: { id: "cchr", citation: "Stiell IG, et al. The Canadian CT Head Rule for patients with minor head injury. Lancet. 2001." },
  garciaLopez: { id: "garcia-lopez", citation: "Garcia-Lopez E, Vutescu E, Orman S, Schiller J, Eberson C, Cruz AI Jr. Antibiotic considerations in the management of pediatric open fractures. Current concept review. Journal of the Pediatric Orthopaedic Society of North America. 2021.", url: "https://www.jposna.org/index.php/jposna/article/view/225" },
  cdcYellowBook: { id: "cdc-yellowbook", citation: "Centers for Disease Control and Prevention. CDC Yellow Book 2026. Health information for international travel. Zoonotic exposures: bites, scratches, and other hazards. 2025.", url: "https://www.cdc.gov/yellow-book/hcp/environmental-hazards-risks/zoonotic-exposures.html" },
  cdcBvirus: { id: "cdc-bvirus", citation: "Centers for Disease Control and Prevention. B virus (herpes B). Patient care for B virus: postexposure prophylaxis and treatment. Page reviewed 2026.", url: "https://www.cdc.gov/herpes-b-virus/hcp/clinical-care/index.html" },
  awanaDuct: { id: "awana-duct", citation: "Awana M, Arora SS, Arora S, Hansraj V. Reconstruction of a traumatically transected Stensen's duct using facial vein graft. Ann Maxillofac Surg. 2015. 5(1):96 to 99.", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4555959/" },
  cpsProcedural: { id: "cps-procedural", citation: "Trottier ED, Doré-Bergeron MJ, Chauvin-Kimoff L, Baerg K, Ali S. Managing pain and distress in children undergoing brief diagnostic and therapeutic procedures. Canadian Paediatric Society position statement. Paediatr Child Health. 2019. 24(8):509 to 521. Updated 2025.", url: "https://cps.ca/en/documents/position/managing-pain-and-distress" },
  aapdNitrous: { id: "aapd-nitrous", citation: "American Academy of Pediatric Dentistry. Use of nitrous oxide for pediatric dental patients. Best practices. The Reference Manual of Pediatric Dentistry. 2025. 415 to 422." },
  asraLast: { id: "asra-last", citation: "Neal JM, Neal EJ, Weinberg GL. American Society of Regional Anesthesia and Pain Medicine local anesthetic systemic toxicity checklist. 2020 version. Reg Anesth Pain Med. 2021. 46(1):81 to 82.", url: "https://asra.com/docs/default-source/guidelines-articles/local-anesthetic-systemic-toxicity-rgb.pdf" },
  afpLaceration: { id: "afp-laceration", citation: "Forsch RT, Little SH, Williams C. Laceration repair. A practical approach. Am Fam Physician. 2017. 95(10):628 to 636.", url: "https://www.aafp.org/pubs/afp/issues/2017/0515/p628.html" },
} satisfies Record<string, Source>;

export const LACERATIONS_SAMPS: Samp[] = [
  {
    id: "lacerations-01",
    topic: "lacerations",
    alsoTopics: ["msk"],
    title: "Kitchen knife injury to a finger",
    stem:
      "A 34-year-old right handed line cook presents 90 minutes after his boning knife slipped while he was deboning chicken. He has a 2 cm transverse laceration on the palmar surface of his right index finger, over the middle of the proximal phalanx. Bleeding is controlled with a gauze dressing. He is healthy and takes no medications. Vital signs are normal. At rest, his right index finger lies straighter than the other fingers.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "Before giving any local anaesthetic, what specific examinations will you perform on this finger?",
        accept: [
          { id: "fdp", text: "Isolated FDP test. Hold the PIP joint extended and ask him to flex the DIP joint", match: ["fdp", "profundus", "dip flexion", "flex dip", "dip joint"] },
          { id: "fds", text: "Isolated FDS test. Hold the other fingers extended and ask him to flex the PIP joint", match: ["fds", "superficialis", "pip flexion", "flex pip", "pip joint"] },
          { id: "2pd", text: "Two point discrimination on the radial and ulnar sides of the fingertip", match: ["two point", "2 point", "2pd"] },
          { id: "cap", text: "Capillary refill and colour of the fingertip", match: ["capillary refill"] },
          { id: "tendon-resist", text: "Flexion strength against resistance, with pain suggesting a partial tendon laceration", match: ["against resistance"] },
          { id: "cascade", text: "Resting finger cascade and tenodesis with passive wrist extension", match: ["tenodesis"] },
          { id: "sensation", text: "Light touch sensation on each side of the digit to test the digital nerves", match: ["digital nerve", "light touch", "sensation"] },
        ],
        unacceptable: [
          { text: "Allen test of the wrist alone without digital assessment", match: ["allen test only"] },
        ],
        explanation:
          "A loss of the normal flexion cascade suggests a flexor tendon cut. FDP and FDS must each be isolated, and a partial laceration may only show as pain or weakness against resistance. Digital nerves run beside the flexor sheath, so test two point discrimination on both sides before anaesthesia masks the findings.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        update: "With the PIP joint held extended, he cannot flex the DIP joint. He can flex the PIP joint when the other fingers are held extended. Two point discrimination is 10 mm on the radial side of the fingertip and 4 mm on the ulnar side.",
        prompt: "Which of the following is the most accurate interpretation of these examination findings?",
        options: [
          "Extensor tendon injury with a radial digital nerve injury",
          "FDP and FDS laceration with an ulnar digital nerve injury",
          "FDP laceration with a radial digital nerve injury",
          "FDP laceration with no digital nerve injury",
          "FDS laceration with an intact FDP and no nerve injury",
        ],
        correct: 2,
        explanation:
          "Inability to flex the DIP joint with the PIP blocked means the FDP is cut. An intact isolated PIP flexion shows FDS works. Two point discrimination above about 6 mm on one side, compared with a normal other side, indicates a digital nerve injury on that side.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "The on call plastic surgeon asks you to manage him in the emergency department today.",
        prompt: "What are the elements of your management and disposition?",
        accept: [
          { id: "irrigate", text: "Irrigate the wound and close the skin only", match: ["irrigate", "irrigation", "close skin", "skin closure", "suture skin"] },
          { id: "splint", text: "Dorsal blocking splint with the wrist and MCP joints flexed and the IP joints extended", match: ["dorsal blocking splint", "dorsal splint", "dorsal block"] },
          { id: "fu", text: "Hand surgery follow up for tendon and nerve repair within a few days", match: ["hand surgery", "plastic surgery follow", "plastic follow", "hand clinic"] },
          { id: "elevate", text: "Elevation and no active use of the finger until repair", match: ["elevate", "elevation", "elevated", "no active flexion"] },
          { id: "analgesia", text: "Oral analgesia such as acetaminophen and ibuprofen", match: ["analgesia", "acetaminophen", "ibuprofen"] },
          { id: "tetanus", text: "Update tetanus immunization if not current", match: ["tetanus"] },
        ],
        unacceptable: [
          { text: "Primary tendon repair by the emergency physician in zone II", match: ["tendon repair emergency department", "repair tendon myself", "tendon repair myself"] },
        ],
        explanation:
          "Zone II flexor tendon injuries need repair by a hand surgeon, usually within days, not in the emergency department. The skin can be closed and the hand protected in a dorsal blocking splint so the repaired or cut tendon is not stressed. The digital nerve injury is repaired at the same operation.",
        keyFeature: { topic: "msk", n: 8 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "single",
        update: "He asks whether he needs antibiotics. The wound was made by a clean knife, is 90 minutes old and is not contaminated.",
        prompt: "Which of the following is the most appropriate antibiotic plan for this wound?",
        options: [
          "Amoxicillin clavulanate 875/125 mg PO twice daily for 5 days",
          "Cefazolin 2 g IV once in the emergency department",
          "Cephalexin 500 mg PO four times daily for 7 days",
          "Topical mupirocin under the dressing",
          "No prophylactic antibiotics, return if signs of infection",
        ],
        correct: 4,
        explanation:
          "Simple, clean hand lacerations from a sharp object seen early do not benefit from prophylactic antibiotics. Good irrigation matters more. Antibiotics add cost, adverse effects and resistance without lowering infection rates in low risk wounds. Give him instructions to return for signs of infection.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "singer-nejm",
      },
    ],
    sources: [S.tintinalli, S.rosen, S.singer],
    ...META,
  },
  {
    id: "lacerations-02",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Injury from the family pet",
    stem:
      "A 46-year-old woman presents to your emergency department in Barrie, Ontario, 3 hours after her neighbour's dog bit her left hand while she was separating it from her own dog. She has two puncture wounds on the dorsum of the hand over the third and fourth metacarpals, each about 5 mm, and a 2 cm ragged laceration on the thenar eminence. She has type 2 diabetes treated with metformin. Vital signs are normal. Tendon, nerve and vascular examination are normal. Her last tetanus booster was 4 years ago.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features of this injury or patient increase the risk of wound infection?",
        accept: [
          { id: "hand", text: "Location on the hand", match: ["hand"] },
          { id: "puncture", text: "Puncture wounds that are hard to irrigate", match: ["puncture"] },
          { id: "dm", text: "Diabetes", match: ["diabete", "diabetic"] },
          { id: "crush", text: "Crush component from a dog bite", match: ["crush"] },
          { id: "joint", text: "Proximity to bones, tendons or joints of the hand", match: ["joint", "tendon", "bone"] },
          { id: "delay", text: "Delay of several hours before presentation", match: ["delay", "delayed", "late presentation", "3 hour"] },
        ],
        explanation:
          "Bite wounds to the hand, puncture wounds, crush injury and host factors such as diabetes all raise infection risk. Punctures cannot be irrigated well and hand compartments are small with tendons and joints close to the skin.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "idsa-ssti",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What are the elements of your wound management before she leaves the department?",
        accept: [
          { id: "irrigate", text: "Copious irrigation with tap water or saline", match: ["irrigate", "irrigation", "irrigated"] },
          { id: "debride", text: "Debride devitalized tissue", match: ["debride", "debridement", "debrided"] },
          { id: "open", text: "Leave the hand wounds open or loosely approximated rather than closed primarily", match: ["leave open", "not close", "don close", "dont close", "no suture", "loosely approximate", "secondary intention", "do not suture", "delayed closure", "no primary closure", "avoid closure", "avoid primary closure"] },
          { id: "xray", text: "Hand radiograph to look for fracture or a tooth fragment", match: ["x ray", "xray", "radiograph"] },
          { id: "splint", text: "Splint and elevate the hand", match: ["splint", "splinting", "elevate", "elevation", "elevated"] },
        ],
        unacceptable: [
          { text: "Primary closure of the hand puncture wounds with sutures", match: ["suture puncture", "primary closure", "close puncture"] },
        ],
        explanation:
          "Irrigation and debridement are the most effective infection prevention steps. Hand bite wounds have a high infection rate and are usually left open or loosely approximated. Puncture wounds should never be sutured closed.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "She has no drug allergies.",
        prompt: "Which of the following is the most appropriate antibiotic plan for this patient?",
        options: [
          "Amoxicillin clavulanate 875/125 mg PO BID, 3 to 5 days",
          "Cephalexin 500 mg PO four times daily for 5 days",
          "Ciprofloxacin 500 mg PO twice daily for 7 days",
          "Clindamycin 300 mg PO four times daily for 10 days",
          "No antibiotic, and return if redness develops",
        ],
        correct: 0,
        explanation:
          "Prophylaxis is recommended for dog bites to the hand, puncture wounds and patients with diabetes. Amoxicillin clavulanate covers Pasteurella, streptococci, staphylococci and oral anaerobes. Cephalexin and clindamycin alone miss Pasteurella. A short course, twice daily for 3 to 5 days, with a wound check in 24 to 48 hours is standard.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "idsa-ssti",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "The dog is owned, lives next door and appears healthy. The owner is unsure of its rabies vaccination status.",
        prompt: "What actions regarding rabies are needed in this case?",
        accept: [
          { id: "report", text: "Report the bite to the local public health unit", match: ["public health", "report", "reported", "reporting", "notify"] },
          { id: "observe", text: "Arrange 10 day observation of the dog", match: ["10 day", "ten day", "observe dog", "observation"] },
          { id: "withhold", text: "Withhold rabies post-exposure prophylaxis unless the dog develops signs of rabies during observation", match: ["withhold", "defer", "no rabies", "not needed", "not indicated", "no pep", "hold pep", "no post exposure", "no prophylaxis"] },
        ],
        unacceptable: [
          { text: "Euthanize the dog immediately for testing", match: ["euthanize"] },
        ],
        explanation:
          "A healthy dog, cat or ferret that can be observed for 10 days does not need to be tested, and post-exposure prophylaxis can be withheld unless the animal becomes ill. Animal bites are reportable to the medical officer of health in Ontario, who arranges the observation.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "on-rabies",
      },
    ],
    sources: [S.idsa, S.rosen, S.onRabies],
    ...META,
  },
  {
    id: "lacerations-03",
    topic: "lacerations",
    alsoTopics: ["msk"],
    title: "Knuckle wound after a night out",
    stem:
      "A 26-year-old man presents at 11:00 with a 6 mm laceration over the dorsum of his right fourth metacarpophalangeal joint. He says he caught it on a chain link fence at about 01:00. He has mild swelling but full range of motion. He is otherwise well. Vital signs are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of this presentation should make you suspect a more serious mechanism than he describes?",
        accept: [
          { id: "site", text: "Location over the dorsal MCP joint, typical of a punch to the mouth", match: ["mcp", "knuckle", "metacarpophalangeal"] },
          { id: "size", text: "Small wound of 3 to 8 mm typical of a tooth", match: ["small", "tooth"] },
          { id: "hand", text: "Dominant hand", match: ["dominant"] },
          { id: "time", text: "Night time injury in a young man, possibly an altercation", match: ["night", "fight", "altercation", "alcohol"] },
          { id: "delay", text: "Delayed presentation of 10 hours", match: ["delay", "delayed", "10 hour"] },
        ],
        explanation:
          "A small wound over the dorsal MCP joint of the dominant hand is a clenched fist injury until proven otherwise. Patients often give another story. Asking directly and without judgment changes management, because human bites to the joint carry a high infection risk.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "He admits he punched another man in the mouth.",
        prompt: "What are the steps in your assessment of this wound?",
        accept: [
          { id: "xray", text: "Hand radiographs for fracture, tooth fragment or air in the joint", match: ["x ray", "xray", "radiograph"] },
          { id: "fist", text: "Explore the wound with the fingers flexed in a fist position as at the time of injury", match: ["fist", "clenched", "flexed", "flexion"] },
          { id: "tendon", text: "Examine the extensor tendon through full range of motion", match: ["extensor", "tendon"] },
          { id: "capsule", text: "Look for joint capsule penetration", match: ["capsule", "joint penetration", "joint involvement", "arthrotomy"] },
          { id: "infect", text: "Look for signs of infection such as erythema, pain on passive motion or purulence", match: ["infection", "passive motion", "purulent", "purulence", "pus"] },
          { id: "nv", text: "Neurovascular examination of the finger", match: ["neurovascular"] },
        ],
        explanation:
          "At impact the MCP is flexed and the extensor tendon and capsule are drawn distally. When the hand is opened, the tendon wound moves away from the skin wound. Exploration must therefore reproduce the fist position. Radiographs look for a fracture, a tooth fragment or air in the joint.",
        keyFeature: { topic: "msk", n: 6 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        update: "Radiographs are normal. On exploration in a fist position the extensor tendon and joint capsule appear intact. There are no signs of infection. He has no allergies.",
        prompt: "Which of the following is the most appropriate antibiotic plan for this patient?",
        options: [
          "Amoxicillin clavulanate 875/125 mg PO twice daily",
          "Cephalexin 500 mg PO four times daily",
          "Clindamycin 300 mg PO four times daily",
          "Cloxacillin 500 mg PO four times daily",
          "No antibiotic until infection develops",
        ],
        correct: 0,
        explanation:
          "All clenched fist injuries deserve prophylaxis. Amoxicillin clavulanate covers Eikenella corrodens, streptococci, staphylococci and anaerobes. Eikenella is resistant to clindamycin and first generation cephalosporins cover it poorly.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "idsa-ssti",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "The wound is irrigated and he is placed in a splint.",
        prompt: "What are the further elements of his disposition?",
        accept: [
          { id: "noclose", text: "Leave the wound open without sutures", match: ["leave open", "not suture", "don suture", "dont suture", "no suture", "do not close", "not close", "don close", "dont close", "open"] },
          { id: "recheck", text: "Wound recheck in 24 to 48 hours", match: ["recheck", "24 hour", "48 hour", "reassess", "follow up", "review"] },
          { id: "hand", text: "Hand surgery referral if joint or tendon involvement is suspected or infection develops", match: ["hand surgery", "hand surgeon", "plastic"] },
          { id: "return", text: "Return instructions for swelling, redness, fever or pain on moving the finger", match: ["return"] },
          { id: "elev", text: "Elevate the hand", match: ["elevate", "elevation", "elevated"] },
          { id: "tet", text: "Tetanus update if due", match: ["tetanus"] },
        ],
        unacceptable: [
          { text: "Primary closure with sutures", match: ["primary closure", "suture closed", "close with suture"] },
        ],
        explanation:
          "Clenched fist wounds are left open. Close review is essential because septic arthritis and tenosynovitis can develop within a day. Any joint penetration, tendon injury or established infection needs hand surgery for operative washout and IV antibiotics.",
        keyFeature: { topic: "msk", n: 7 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.tintinalli, S.idsa],
    ...META,
  },
  {
    id: "lacerations-04",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Night visitor at the cottage",
    stem:
      "A 29-year-old woman presents at 08:00 from a cottage near Parry Sound, Ontario. At 03:00 she woke to find a bat on her bare forearm. She brushed it off and it flew out an open window. She sees no mark on her skin. She is healthy and has never had a rabies vaccine.",
    vitals: { weight: "60 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What questions would you ask to characterize this exposure?",
        accept: [
          { id: "contact", text: "Was there direct physical contact with the bat", match: ["direct contact", "touch", "physical contact", "contact"] },
          { id: "bite", text: "Did she feel a bite or scratch", match: ["bite", "scratch"] },
          { id: "mucous", text: "Any saliva contact with eyes, mouth or broken skin", match: ["saliva", "mucous", "mucosa"] },
          { id: "avail", text: "Is the bat available for testing", match: ["available", "captured", "testing", "caught"] },
          { id: "others", text: "Were others, such as sleeping children, in the room", match: ["other people", "other person", "anyone else", "sleeping", "children", "child"] },
          { id: "vacc", text: "Previous rabies vaccination", match: ["previous vaccine", "previous vaccination", "prior vaccine", "prior vaccination", "rabies vaccine", "rabies vaccination", "immunized"] },
          { id: "immune", text: "Immune status or immunosuppressing drugs", match: ["immune", "immunocompromised", "immunosuppressed", "immunosuppression", "immunosuppressant", "immunosuppressive"] },
        ],
        explanation:
          "Bat bites can be tiny and painless and may leave no mark. The Canadian Immunization Guide treats any direct skin contact with a live bat as an exposure. A bat in the room, even with a sleeping person, counts only if there was direct contact. Whether the bat can be tested, and who else was exposed, also shape the decision.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "cig-rabies",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate recommendation for this exposure?",
        options: [
          "Observation, with return for fever or neurological signs",
          "Rabies immune globulin and a rabies vaccine series",
          "Rabies immune globulin only, without vaccine",
          "Rabies vaccine series only, without immune globulin",
          "No prophylaxis",
        ],
        correct: 1,
        explanation:
          "Direct skin contact with a live bat is an exposure under the Canadian Immunization Guide. Ontario guidance asks whether a bite, scratch or saliva exposure can be ruled out, and here it cannot because she was asleep. Either way she needs full post-exposure prophylaxis. The absence of a visible wound does not rule out a bite. The bat cannot be tested, so prophylaxis should not be delayed.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-rabies",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What are the specifics of the prophylaxis you will order, including doses, sites and schedule where relevant?",
        accept: [
          { id: "rigdose", text: "Rabies immune globulin 20 IU/kg, which is 1200 IU", match: ["20 iu/kg", "20 iu kg", "20 unit/kg", "20 unit kg", "1200 iu", "1200 unit"] },
          { id: "rigsite", text: "With no visible wound, give the immune globulin IM at a site distant from the vaccine, such as the other limb", match: ["infiltrate", "infiltration", "infiltrated", "distant", "different site", "separate site", "other limb", "different limb", "opposite"] },
          { id: "vaxsite", text: "Vaccine 1 mL IM in the deltoid", match: ["deltoid"] },
          { id: "sched", text: "Vaccine on days 0, 3, 7 and 14", match: ["0 3 7 14", "four dose", "4 dose"] },
          { id: "day0", text: "Give immune globulin once on day 0 with the first vaccine dose", match: ["day 0", "same day", "once"] },
        ],
        unacceptable: [
          { text: "Vaccine in the gluteal region", match: ["gluteal", "buttock"] },
          { text: "Immune globulin and vaccine in the same syringe or site", match: ["same syringe", "same site"] },
        ],
        explanation:
          "Rabies immune globulin is 20 IU/kg given once on day 0. When there is a wound it is infiltrated there. When no wound site is known, the whole dose goes IM at a site away from the vaccine. An immunocompetent person needs four 1 mL vaccine doses in the deltoid on days 0, 3, 7 and 14. Gluteal injection has been linked to vaccine failure.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-rabies",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "She mentions she started prednisone 40 mg daily 3 weeks ago for a flare of Crohn disease.",
        prompt: "What changes to her prophylaxis plan are needed because of this?",
        accept: [
          { id: "d28", text: "Add a fifth vaccine dose on day 28", match: ["day 28", "fifth dose", "5th dose", "five dose", "5 dose"] },
          { id: "sero", text: "Check rabies antibody titres after the series", match: ["titre", "titer", "serology", "antibody"] },
          { id: "id", text: "Consult infectious diseases or public health on the plan", match: ["infectious disease", "public health"] },
          { id: "reduce", text: "Consider whether immunosuppression can be reduced during the series", match: ["reduce prednisone", "reduce steroid", "reduced", "reduce immunosuppression", "hold prednisone", "hold steroid", "taper"] },
        ],
        unacceptable: [
          { text: "Delay the vaccine series until the prednisone is stopped", match: ["hold vaccine", "delay vaccine", "defer vaccine", "postpone vaccine", "delay prophylaxis", "defer prophylaxis", "delay pep", "defer pep"], dangerous: true },
        ],
        explanation:
          "Immunosuppressed patients respond less reliably to rabies vaccine. They receive a fifth dose on day 28, and serology is checked 7 to 14 days after the last dose. Immune globulin is still given on day 0. Immunosuppressants should be avoided during the series unless essential, which here is a decision to share with her gastroenterologist.",
        keyFeature: { topic: "infectious-diseases", n: 3 },
        source: "cig-rabies",
      },
    ],
    sources: [S.cigRab],
    ...META,
  },
  {
    id: "lacerations-05",
    topic: "lacerations",
    alsoTopics: ["analgesia-sedation"],
    title: "Preschooler who fell against a table",
    stem:
      "A 4-year-old boy is brought in after falling against a coffee table. He has a 1.5 cm vertical laceration of the lower lip that crosses the vermilion border onto the skin. He is crying and uncooperative. He is otherwise healthy. Vital signs are normal for age.",
    vitals: { weight: "18 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features must you specifically assess in this wound?",
        accept: [
          { id: "through", text: "Whether it is through and through into the mouth", match: ["through and through", "through through", "full thickness", "intraoral", "inside mouth"] },
          { id: "teeth", text: "Injured or missing teeth, with possible tooth fragments in the wound", match: ["teeth", "tooth", "dental"] },
          { id: "muscle", text: "Involvement of the orbicularis oris muscle", match: ["orbicularis", "muscle"] },
          { id: "vermilion", text: "Exact position of the vermilion border", match: ["vermilion"] },
          { id: "fb", text: "Foreign body in the wound", match: ["foreign body"] },
          { id: "frenulum", text: "Frenulum or gingival injury", match: ["frenulum", "gingiva", "gum"] },
        ],
        explanation:
          "Lip lacerations that cross the vermilion border need exact realignment because a 1 mm step is visible. Tooth fragments can embed in the lip and may need a soft tissue radiograph. Muscle and mucosal layers need separate repair when involved.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What measures will help you achieve an accurate repair of the vermilion border?",
        accept: [
          { id: "mark", text: "Mark the vermilion border with a skin marker before injecting", match: ["mark", "marker", "marking"] },
          { id: "block", text: "Mental nerve block rather than local infiltration so the tissue is not distorted", match: ["mental nerve", "nerve block", "regional block"] },
          { id: "first", text: "Place the first suture exactly at the vermilion border", match: ["first suture"] },
          { id: "sedation", text: "Procedural sedation so the child is still", match: ["sedation", "ketamine"] },
        ],
        unacceptable: [
          { text: "Tissue adhesive across the vermilion", match: ["adhesive", "glue", "dermabond"] },
        ],
        explanation:
          "Local infiltration swells the tissue and hides the vermilion line, so mark it first or use a mental nerve block. The first stitch aligns the vermilion border. Tissue adhesive is not suited to moist mucosa or to wounds crossing the vermilion.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "You plan ketamine dissociative sedation.",
        prompt: "What are the elements of your pre-sedation risk assessment?",
        accept: [
          { id: "airway", text: "Airway assessment for difficult bag mask ventilation or intubation", match: ["airway"] },
          { id: "uri", text: "Active upper respiratory infection or asthma", match: ["respiratory infection", "uri", "urti", "cold", "asthma", "cough"] },
          { id: "asa", text: "ASA class and comorbid illness", match: ["asa", "comorbid"] },
          { id: "prior", text: "Previous sedation or anaesthesia problems", match: ["previous sedation", "prior sedation", "previous anaesthesia", "previous anaesthetic", "previous anesthesia", "previous anesthetic", "prior anesthesia", "prior anesthetic", "prior anaesthesia", "prior anaesthetic"] },
          { id: "fast", text: "Time of last oral intake", match: ["fasting", "last meal", "npo", "oral intake", "last ate"] },
          { id: "allergy", text: "Allergies and current medications", match: ["allergy", "allergie", "allergic", "medication"] },
          { id: "cv", text: "Cardiovascular disease or hypertension", match: ["cardiac", "cardiovascular"] },
        ],
        explanation:
          "Formal pre-sedation assessment looks for predictors of airway problems and cardiorespiratory complications. With ketamine, an active respiratory infection and airway abnormality raise the risk of laryngospasm. Recent intake guides timing but should not by itself delay sedation for a needed procedure.",
        keyFeature: { topic: "analgesia-sedation", n: 5 },
        source: "green-ketamine",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following is the most appropriate initial IV ketamine dose for this child?",
        options: ["9 mg", "27 mg", "54 mg", "72 mg", "180 mg"],
        correct: 1,
        explanation:
          "The usual initial IV dose for dissociative sedation in children is 1.5 mg/kg given over 30 to 60 seconds, which is 27 mg for 18 kg. 4 mg/kg is an IM dose, not an IV dose. 0.5 mg/kg gives analgesia without reliable dissociation.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "green-ketamine",
      },
      {
        id: "q5",
        kind: "short",
        required: 3,
        update: "Two minutes after the dose he develops high pitched inspiratory noise, then silence with chest wall retractions. O2 sat falls to 82%.",
        prompt: "What interventions would you use, in order of escalation?",
        accept: [
          { id: "jaw", text: "Jaw thrust with pressure at the laryngospasm notch", match: ["jaw thrust", "laryngospasm notch", "larson"] },
          { id: "bvm", text: "Bag valve mask ventilation with 100% oxygen and positive pressure", match: ["bag", "bvm", "positive pressure", "cpap", "peep"] },
          { id: "suction", text: "Suction the oropharynx", match: ["suction"] },
          { id: "sux", text: "Succinylcholine if laryngospasm persists", match: ["succinylcholine", "suxamethonium", "paralytic", "paralysis", "paralyze", "paralyse"] },
          { id: "intubate", text: "Intubation if the airway cannot be restored", match: ["intubate", "intubation", "intubated"] },
        ],
        unacceptable: [
          { text: "Give more ketamine", match: ["more ketamine", "repeat ketamine"], dangerous: true },
        ],
        explanation:
          "Laryngospasm is an uncommon ketamine complication. Most cases respond to jaw thrust and positive pressure ventilation with oxygen. Persistent spasm with falling saturation is treated with succinylcholine, followed by ventilation or intubation.",
        keyFeature: { topic: "analgesia-sedation", n: 6 },
        source: "green-ketamine",
      },
    ],
    sources: [S.tintinalli, S.green],
    ...META,
  },
  {
    id: "lacerations-06",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Roofer who stepped on something sharp",
    stem:
      "A 42-year-old roofer presents 3 hours after stepping on a roofing nail. It passed through the sole of his running shoe into the ball of his right foot, near the second metatarsal head. He pulled it out himself. There is a 3 mm puncture wound with minimal bleeding. He is healthy. He moved to Canada from abroad as an adult and has no record of tetanus immunization.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features of the history help you estimate the risk of complications from this wound?",
        accept: [
          { id: "shoe", text: "Penetration through a rubber soled shoe", match: ["shoe", "sneaker", "footwear"] },
          { id: "depth", text: "Estimated depth of penetration", match: ["depth", "deep"] },
          { id: "loc", text: "Location over the metatarsal heads near bone and joint", match: ["metatarsal", "forefoot", "joint", "bone"] },
          { id: "fb", text: "Possible retained foreign body such as shoe material or a broken tip", match: ["foreign body", "retained"] },
          { id: "dm", text: "Diabetes, peripheral vascular disease or immunosuppression", match: ["diabete", "vascular", "immune", "immunocompromised", "immunosuppressed", "immunosuppression", "immunosuppressant"] },
          { id: "time", text: "Time since injury", match: ["time since", "delay", "delayed"] },
          { id: "object", text: "State of the nail, rusty or contaminated", match: ["rust", "rusty", "dirty", "contaminated", "contamination"] },
        ],
        explanation:
          "Plantar puncture wounds through a rubber soled shoe can drive shoe material and Pseudomonas into deep tissue. Forefoot punctures near the metatarsal heads carry a higher risk of osteomyelitis and septic arthritis. Diabetes and vascular disease raise the risk further.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What are the elements of tetanus prophylaxis for him today, including the dose where relevant?",
        accept: [
          { id: "tdap", text: "Tdap or Td vaccine now", match: ["tdap", "td", "tetanus toxoid", "tetanus vaccine", "tetanus booster"] },
          { id: "tig", text: "Tetanus immune globulin 250 units IM at a separate site", match: ["immune globulin 250", "tig 250", "tetanus immunoglobulin 250", "immunoglobulin 250"] },
          { id: "series", text: "Arrange completion of the primary series with further doses", match: ["primary series", "complete series", "further dose", "two more dose", "2 more dose"] },
        ],
        unacceptable: [
          { text: "No tetanus prophylaxis because the wound is small", match: ["no tetanus", "not needed"] },
        ],
        explanation:
          "A puncture wound is not a clean minor wound. With unknown or incomplete immunization, give tetanus toxoid, preferably as Tdap, and tetanus immune globulin 250 units IM at a different site. He then needs the rest of the primary series.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-tetanus",
      },
      {
        id: "q3",
        kind: "single",
        update: "He returns 8 days later. The pain has worsened over 3 days. The forefoot is swollen and tender over the second metatarsal head. He is afebrile.",
        prompt: "Which of the following organisms must your empiric antibiotic choice cover?",
        options: [
          "Clostridium perfringens",
          "Eikenella corrodens",
          "Pasteurella multocida",
          "Pseudomonas aeruginosa",
          "Vibrio vulnificus",
        ],
        correct: 3,
        explanation:
          "Late deep infection after a nail through a rubber soled shoe is classically caused by Pseudomonas aeruginosa, which thrives in shoe foam. Early superficial cellulitis is usually staphylococcal or streptococcal. Late worsening pain near bone suggests osteomyelitis or osteochondritis.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What further steps are needed in his management at this visit?",
        accept: [
          { id: "xray", text: "Foot radiographs for foreign body and bone changes", match: ["x ray", "xray", "radiograph"] },
          { id: "mri", text: "MRI to look for osteomyelitis or abscess", match: ["mri"] },
          { id: "us", text: "Ultrasound for a radiolucent foreign body or abscess", match: ["ultrasound", "pocus"] },
          { id: "surg", text: "Orthopaedic or surgical consultation for debridement and bone cultures", match: ["orthopaedic", "orthopedic", "orthopaedics", "orthopedics", "surgery", "surgical", "surgeon", "debride", "debridement", "debrided"] },
          { id: "labs", text: "CBC, CRP and ESR", match: ["crp", "esr", "cbc"] },
          { id: "abx", text: "Anti-pseudomonal antibiotic such as ciprofloxacin", match: ["ciprofloxacin", "pseudomonal", "cipro"] },
        ],
        explanation:
          "Suspected deep infection needs imaging for foreign body and bone involvement, and early surgical input. Pseudomonal osteomyelitis usually needs debridement plus targeted antibiotics. Plain films may be normal early, so MRI is often needed.",
        keyFeature: { topic: "infectious-diseases", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.cigTet, S.rosen],
    ...META,
  },
  {
    id: "lacerations-07",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Farmer with a leg wound",
    stem:
      "A 70-year-old dairy farmer presents 20 hours after cutting his left shin on a rusty disc harrow blade. He finished his chores before coming in. There is an 8 cm ragged laceration of the anterior shin, with soil and manure in the wound and some devitalized skin edges. He has type 2 diabetes and peripheral vascular disease. He cannot recall ever having a tetanus shot. Vital signs are otherwise normal.",
    vitals: { temperature: "36.9°C" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What steps would you take in preparing this wound before any decision on closure?",
        accept: [
          { id: "irr", text: "High volume pressure irrigation", match: ["irrigate", "irrigation", "irrigated"] },
          { id: "debride", text: "Sharp debridement of devitalized tissue", match: ["debride", "debridement", "debrided", "devitalized"] },
          { id: "fb", text: "Remove foreign material and explore the wound", match: ["foreign", "explore", "exploration", "explored"] },
          { id: "xray", text: "Radiograph for retained metal or fracture", match: ["x ray", "xray", "radiograph"] },
          { id: "anaes", text: "Adequate local anaesthesia before cleaning", match: ["anaesthesia", "anaesthetic", "anesthesia", "anesthetic", "lidocaine"] },
          { id: "nv", text: "Assess distal pulses and sensation", match: ["pulse", "neurovascular", "sensation"] },
        ],
        explanation:
          "Heavily contaminated wounds need anaesthesia, exploration, removal of foreign material, debridement and high volume irrigation before closure is considered. Imaging finds retained metal. Poor perfusion from vascular disease raises infection and healing risk.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "singer-nejm",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        update: "The wound is cleaned.",
        prompt: "Which of the following are the most appropriate next steps for this wound?",
        options: [
          "Admission to hospital for IV vancomycin",
          "Oral amoxicillin clavulanate, wound check in 48 hours",
          "Packing, delayed primary closure in 3 to 5 days",
          "Primary closure with staples today",
          "Primary closure with sutures today",
          "Tissue adhesive closure today",
          "Topical antibiotic ointment only",
          "No antibiotics and family physician follow up in 10 days",
        ],
        correct: [1, 2],
        explanation:
          "A wound that is 20 hours old, contaminated with soil and manure, with devitalized edges in a patient with diabetes and vascular disease is high risk. Packing and dressing the wound, with delayed primary closure in 3 to 5 days, lowers infection risk. Prophylactic oral amoxicillin clavulanate with a wound check in 48 hours is reasonable for this infection prone wound.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What are the elements of his tetanus prophylaxis, including the dose where relevant?",
        accept: [
          { id: "tdap", text: "Tdap or Td vaccine now", match: ["tdap", "td", "tetanus toxoid", "tetanus vaccine", "tetanus booster"] },
          { id: "tig", text: "Tetanus immune globulin 250 units IM at a separate site", match: ["immune globulin 250", "tig 250", "tetanus immunoglobulin 250", "immunoglobulin 250"] },
          { id: "series", text: "Complete the primary series with further doses", match: ["primary series", "complete series", "further dose"] },
        ],
        explanation:
          "A contaminated wound in a person with no reliable history of a primary series needs both tetanus toxoid and tetanus immune globulin 250 units IM. Older adults are the group most likely to be unimmunized in Canada. Arrange the remaining primary series doses.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-tetanus",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "He returns 36 hours later with severe pain, spreading dusky erythema and a small area of crepitus above the wound. Pulse 124/minute, BP 88/50 mmHg, temperature 38.9°C.",
        prompt: "What urgent actions are needed?",
        accept: [
          { id: "surg", text: "Emergent surgical consultation for debridement", match: ["surgery", "surgical", "surgeon", "debride", "debridement", "debrided", "operating room"] },
          { id: "abx", text: "Broad spectrum IV antibiotics such as piperacillin tazobactam or meropenem with vancomycin", match: ["piperacillin", "meropenem", "broad spectrum", "vancomycin"] },
          { id: "clinda", text: "Add clindamycin for toxin suppression", match: ["clindamycin"] },
          { id: "fluid", text: "IV crystalloid resuscitation", match: ["fluid", "crystalloid", "ringer", "saline"] },
          { id: "cult", text: "Blood cultures and lactate", match: ["culture", "lactate"] },
          { id: "press", text: "Vasopressors if hypotension persists after fluids", match: ["norepinephrine", "vasopressor", "pressor"] },
        ],
        unacceptable: [
          { text: "Wait for CT before calling the surgeon", match: ["wait for ct", "ct first"], dangerous: true },
        ],
        explanation:
          "Pain out of proportion, crepitus and shock indicate a necrotizing soft tissue infection. Mortality rises with every hour that surgical debridement is delayed. Imaging must not delay the surgeon. Broad spectrum antibiotics with clindamycin and resuscitation run in parallel.",
        keyFeature: { topic: "infectious-diseases", n: 4 },
        source: "idsa-ssti",
      },
    ],
    sources: [S.singer, S.rosen, S.cigTet, S.idsa],
    ...META,
  },
  {
    id: "lacerations-08",
    topic: "lacerations",
    alsoTopics: ["analgesia-sedation", "tox"],
    title: "Several cuts after a fall through a door",
    stem:
      "A 23-year-old woman fell through a glass patio door. She has seven lacerations on both forearms and both shins, totalling 38 cm. There is no tendon, nerve or vascular injury. She is healthy. You have 1% lidocaine with epinephrine and 1% plain lidocaine.",
    vitals: { weight: "50 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the maximum volume of 1% lidocaine with epinephrine you should infiltrate?",
        options: ["15 mL", "22 mL", "35 mL", "50 mL", "70 mL"],
        correct: 2,
        explanation:
          "1% lidocaine is 10 mg/mL. The usual maximum with epinephrine is 7 mg/kg, which is 350 mg or 35 mL for 50 kg. Plain lidocaine is limited to about 4.5 to 5 mg/kg, which would be 22 to 25 mL here.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "You will reach the maximum dose before all wounds are anaesthetized.",
        prompt: "What are the ways to complete the repair safely?",
        accept: [
          { id: "block", text: "Regional nerve blocks, such as forearm or ankle blocks", match: ["nerve block", "regional", "hematoma block"] },
          { id: "dilute", text: "Dilute to 0.5% lidocaine to give more volume for the same dose", match: ["dilute", "diluted", "dilution", "0.5%"] },
          { id: "stage", text: "Stage the repair over time or on another day", match: ["stage", "staged", "another day", "later"] },
          { id: "sedation", text: "Procedural sedation", match: ["sedation", "ketamine"] },
          { id: "or", text: "Repair under anaesthesia in the operating room", match: ["operating room", "general anaesthesia", "general anaesthetic", "general anesthesia", "general anesthetic"] },
          { id: "adhesive", text: "Tissue adhesive or skin tapes for small low tension wounds", match: ["adhesive", "glue", "steri", "tape"] },
          { id: "topical", text: "Topical LET gel for small wounds", match: ["let gel", "lidocaine epinephrine tetracaine", "topical"] },
        ],
        unacceptable: [
          { text: "Exceed the maximum dose because she is young and healthy", match: ["exceed"], dangerous: true },
        ],
        explanation:
          "Adding up small infiltrations is how toxic doses happen. Nerve blocks cover large areas with little drug, and dilution stretches the volume. Low tension wounds may not need anaesthesia at all if closed with adhesive or tapes.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "A colleague helps and infiltrates another 20 mL of 2% plain lidocaine into the shin wounds without checking the total. Ten minutes later she reports perioral tingling and ringing in her ears, then has a generalized seizure. Pulse 118/minute, BP 146/88 mmHg.",
        prompt: "What immediate actions are needed?",
        accept: [
          { id: "stop", text: "Stop injecting local anaesthetic and call for help", match: ["stop", "stopped", "call for help"] },
          { id: "airway", text: "Airway support with 100% oxygen and ventilation", match: ["airway", "oxygen", "ventilate", "ventilation", "bag"] },
          { id: "benzo", text: "Benzodiazepine such as midazolam for the seizure", match: ["benzodiazepine", "midazolam", "lorazepam", "diazepam"] },
          { id: "lipid", text: "Lipid emulsion 20%, 1.5 mL/kg IV bolus then 0.25 mL/kg/min infusion", match: ["lipid", "intralipid"] },
          { id: "monitor", text: "Cardiac monitoring for arrhythmias", match: ["monitor", "monitoring"] },
        ],
        unacceptable: [
          { text: "Phenytoin", match: ["phenytoin"] },
          { text: "Lidocaine for an arrhythmia", match: ["lidocaine antiarrhythmic", "lidocaine 1 mg/kg", "lidocaine 1.5 mg/kg", "lidocaine 100 mg"], dangerous: true },
        ],
        explanation:
          "She has received about 750 mg of lidocaine, well above safe limits, and has local anaesthetic systemic toxicity. Stop the drug, support the airway and treat seizures with a benzodiazepine. Give 20% lipid emulsion early, 1.5 mL/kg over 2 to 3 minutes then 0.25 mL/kg/min. Phenytoin and further sodium channel blockers such as lidocaine for arrhythmias are not used.",
        keyFeature: { topic: "tox", n: 4 },
        source: "asra-last",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "She recovers fully. The next day, before closure of a deep shin wound, she says it hurts sharply when pressed in one spot.",
        prompt: "What steps are needed before closing this wound?",
        accept: [
          { id: "xray", text: "Radiograph for retained glass", match: ["x ray", "xray", "radiograph"] },
          { id: "us", text: "Point of care ultrasound for a foreign body", match: ["ultrasound", "pocus"] },
          { id: "explore", text: "Explore the wound under good light in a bloodless field", match: ["explore", "exploration", "explored"] },
          { id: "irr", text: "Irrigate the wound", match: ["irrigate", "irrigation", "irrigated"] },
        ],
        unacceptable: [
          { text: "Close and reassess if pain persists", match: ["close and reassess"] },
        ],
        explanation:
          "Point tenderness in a glass wound suggests a retained fragment. Most glass fragments of 2 mm or more are visible on plain films. Retained glass left behind causes infection, pain and a medicolegal risk, so image and explore before closing.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.asra],
    ...META,
  },
  {
    id: "lacerations-09",
    topic: "lacerations",
    alsoTopics: ["msk"],
    title: "Painter with a tiny fingertip wound",
    stem:
      "A 38-year-old house painter presents 2 hours after his airless paint sprayer discharged into the pad of his left index finger while he was clearing the tip. The paint is oil based. There is a 2 mm puncture on the finger pad. He has mild pain and slight swelling. He is healthy. Vital signs are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features of this injury make it high risk despite its appearance?",
        accept: [
          { id: "pressure", text: "High pressure injection mechanism", match: ["high pressure", "pressure injection", "injection"] },
          { id: "oil", text: "Oil based paint or solvent causes intense chemical inflammation", match: ["oil", "solvent", "paint"] },
          { id: "finger", text: "Injection into a finger with small, tight compartments", match: ["finger", "digit", "compartment"] },
          { id: "small", text: "Small entry wound hides extensive deep spread", match: ["small", "entry wound", "deep spread"] },
          { id: "time", text: "Time to surgical decompression affects outcome", match: ["time", "delay", "delayed"] },
          { id: "sheath", text: "Spread along the flexor tendon sheath", match: ["sheath", "tendon"] },
        ],
        explanation:
          "High pressure injection injuries look trivial at first. Material spreads along tissue planes and tendon sheaths, causing ischemia and chemical necrosis. Oil based paints and solvents, index finger injuries and delay to surgery are linked with amputation.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What examinations will you document for this finger?",
        accept: [
          { id: "cap", text: "Capillary refill and colour", match: ["capillary refill", "colour", "color", "perfusion"] },
          { id: "sens", text: "Digital nerve sensation or two point discrimination", match: ["sensation", "two point"] },
          { id: "tense", text: "Tension of the finger pulp and swelling along the digit and palm", match: ["tension", "swelling", "tense"] },
          { id: "kanavel", text: "Kanavel signs of flexor sheath involvement", match: ["kanavel", "passive extension", "sheath"] },
          { id: "rom", text: "Active flexion and extension of the finger", match: ["range of motion", "flexion", "rom"] },
        ],
        explanation:
          "Baseline perfusion and sensation are needed because swelling can compromise the digit over hours. Pain on passive extension and tenderness along the sheath suggest sheath spread. Findings evolve, so repeat and document them.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What are the elements of your emergency department management while arranging definitive care?",
        accept: [
          { id: "xray", text: "Radiographs to show spread of radiopaque paint or air", match: ["x ray", "xray", "radiograph"] },
          { id: "abx", text: "Broad spectrum IV antibiotics", match: ["antibiotic", "cefazolin"] },
          { id: "tet", text: "Tetanus prophylaxis if not up to date", match: ["tetanus"] },
          { id: "splint", text: "Splint and elevate the hand", match: ["splint", "splinting", "elevate", "elevation", "elevated"] },
          { id: "analg", text: "Parenteral analgesia", match: ["analgesia", "analgesic", "opioid", "morphine", "hydromorphone", "fentanyl"] },
          { id: "npo", text: "Keep him fasting for surgery", match: ["npo", "fasting", "nothing by mouth"] },
          { id: "noclose", text: "Do not close the wound", match: ["not close", "don close", "dont close", "no closure", "leave open"] },
        ],
        unacceptable: [
          { text: "Suture the puncture closed", match: ["suture puncture", "close puncture"] },
        ],
        explanation:
          "Radiographs map the spread of lead based or radiopaque material. Antibiotics, tetanus, splinting and analgesia are given while the surgeon is on the way. Keep him fasting because he needs the operating room.",
        keyFeature: { topic: "msk", n: 7 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following is the most appropriate disposition for this patient?",
        options: [
          "Admit to medicine for IV antibiotics and observation",
          "Discharge on oral antibiotics, wound check in 24 hours",
          "Oral steroids and follow up with his family physician",
          "Urgent hand surgery for decompression and debridement today",
          "Warm soaks, elevation and hand clinic review within one week",
        ],
        correct: 3,
        explanation:
          "High pressure injection injuries are surgical emergencies that need urgent hand surgery consultation for operative decompression and debridement today. Early operative decompression and debridement reduce amputation rates. Observation or antibiotics alone allow ongoing chemical and ischemic damage.",
        keyFeature: { topic: "msk", n: 7 },
        source: "tintinalli",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },
  {
    id: "lacerations-10",
    topic: "lacerations",
    alsoTopics: ["msk"],
    title: "Knee wound from a glass table",
    stem:
      "A 24-year-old man fell onto a glass patio table 3 hours ago. He has a 3 cm laceration on the anterolateral knee, just lateral to the patella. The wound is not bleeding. He can walk with a limp. He is healthy. Vital signs are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What structures or complications must you specifically assess for in this wound?",
        accept: [
          { id: "joint", text: "Penetration of the knee joint capsule", match: ["joint", "capsule", "arthrotomy"] },
          { id: "ext", text: "Extensor mechanism, including straight leg raise", match: ["extensor", "straight leg", "quadricep", "patellar tendon"] },
          { id: "fb", text: "Retained glass", match: ["glass", "foreign body"] },
          { id: "nerve", text: "Peroneal or saphenous nerve function", match: ["peroneal", "saphenous", "nerve"] },
          { id: "vasc", text: "Distal pulses", match: ["pulse", "vascular"] },
          { id: "fracture", text: "Patellar fracture", match: ["fracture"] },
        ],
        explanation:
          "Wounds near a joint can enter it even when small. Leaking synovial fluid or fat globules, or a capsule defect seen through range of motion, are clues. The extensor mechanism, glass fragments and nearby nerves must be examined before closure.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What investigations would help determine whether the joint has been penetrated?",
        accept: [
          { id: "ct", text: "CT of the knee looking for intra-articular air", match: ["ct", "computed tomography"] },
          { id: "xray", text: "Plain radiographs for intra-articular air and glass", match: ["x ray", "xray", "radiograph"] },
          { id: "slt", text: "Saline load test", match: ["saline load", "saline arthrogram", "load test"] },
          { id: "explore", text: "Direct exploration of the wound", match: ["explore", "exploration", "explored"] },
        ],
        unacceptable: [
          { text: "MRI", match: ["mri"] },
        ],
        explanation:
          "Intra-articular air on CT is more sensitive than the saline load test for traumatic knee arthrotomy. Plain films show air and most glass. A negative saline load test with a small volume does not exclude penetration.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "konda-ct",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "CT shows intra-articular air in the knee. There is no fracture or foreign body.",
        prompt: "Which of the following actions are most appropriate for this patient now?",
        options: [
          "Admit to medicine for observation",
          "Aspirate and inject corticosteroid",
          "Cefazolin 2 g IV",
          "Knee immobilizer and physiotherapy",
          "Oral cephalexin and follow up in one week",
          "Orthopaedic surgery for joint irrigation",
          "Primary closure and discharge",
          "Urgent MRI of the knee",
        ],
        correct: [2, 5],
        explanation:
          "A traumatic arthrotomy is an open joint injury. It needs prompt IV antibiotics, such as cefazolin, and orthopaedic consultation for operative irrigation and debridement of the joint. Closing the skin in the emergency department and discharging risks septic arthritis.",
        keyFeature: { topic: "msk", n: 7 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.konda, S.rosen],
    ...META,
  },
  {
    id: "lacerations-11",
    topic: "lacerations",
    alsoTopics: ["multiple-trauma", "abuse-domestic"],
    title: "Older woman with a scalp wound",
    stem:
      "An 81-year-old woman lives with her son. She tripped on a rug at home this morning and struck the back of her head on a door frame. She has a 6 cm oozing laceration over the occiput. She did not lose consciousness and has no headache or vomiting. GCS is 15. She takes apixaban 5 mg twice daily for atrial fibrillation.",
    vitals: { pulse: "84/minute irregular", bp: "158/80 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What findings will you look for when you explore this scalp wound?",
        accept: [
          { id: "galea", text: "A defect in the galea aponeurosis", match: ["galea", "aponeurosi"] },
          { id: "skull", text: "Skull fracture, felt as a step or depression", match: ["skull", "fracture", "step", "depressed", "depression"] },
          { id: "fb", text: "Foreign body", match: ["foreign body", "debris"] },
          { id: "artery", text: "Arterial bleeding point", match: ["artery", "arterial", "bleeding"] },
          { id: "hematoma", text: "Subgaleal hematoma", match: ["hematoma", "haematoma"] },
        ],
        explanation:
          "Scalp wounds should be explored with a gloved finger under good light. A palpable step suggests a depressed skull fracture. Large galeal defects are repaired to control bleeding and limit subgaleal hematoma.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate imaging plan for this patient?",
        options: [
          "Brain MRI as outpatient",
          "CT head now",
          "Observation for 4 hours",
          "Skull radiographs",
          "No imaging",
        ],
        correct: 1,
        explanation:
          "The Canadian CT Head Rule does not apply. It excluded patients on anticoagulants and applies only after loss of consciousness, amnesia or disorientation. Even if it did apply, age 65 or more is a high risk criterion. Anticoagulated older adults with head trauma should have CT. Skull radiographs do not exclude intracranial bleeding.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "cchr",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "The CT is normal. The wound continues to ooze.",
        prompt: "What measures would you use to control bleeding and close this wound?",
        accept: [
          { id: "press", text: "Firm direct pressure", match: ["pressure", "hold pressure", "hold direct pressure", "hold firm pressure"] },
          { id: "lidoepi", text: "Lidocaine with epinephrine infiltration", match: ["epinephrine", "adrenaline"] },
          { id: "staple", text: "Prompt closure with staples or sutures", match: ["staple", "suture"] },
          { id: "galea", text: "Repair a large galeal defect", match: ["galea", "galeal"] },
          { id: "hat", text: "Hair apposition technique", match: ["hair apposition", "hat"] },
          { id: "txa", text: "Topical tranexamic acid", match: ["tranexamic", "txa"] },
          { id: "dress", text: "Pressure dressing after closure", match: ["dressing"] },
        ],
        unacceptable: [
          { text: "Reverse the apixaban for scalp oozing", match: ["andexanet", "reverse apixaban", "reversal agent", "pcc", "octaplex"] },
        ],
        explanation:
          "Scalp bleeding from a laceration is controlled by pressure, local epinephrine and prompt closure, which is itself haemostatic. Reversal of a DOAC is reserved for life threatening bleeding and carries thrombotic risk.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "While undressing her you see fingertip shaped bruises of different colours on both upper arms. She says she bruises easily.",
        prompt: "What are the next steps?",
        accept: [
          { id: "private", text: "Interview her alone, away from her son", match: ["alone", "private", "separate"] },
          { id: "ask", text: "Ask directly and nonjudgmentally about abuse or neglect", match: ["ask", "screen", "screening"] },
          { id: "doc", text: "Document the injuries with a body map or photographs", match: ["document", "documentation", "documented", "photograph", "photo", "body map"] },
          { id: "sw", text: "Involve social work or an elder abuse team", match: ["social work", "elder abuse"] },
          { id: "old", text: "Review previous visits and injuries", match: ["previous visit", "prior visit", "old chart", "previous injury", "previous injurie"] },
        ],
        explanation:
          "Grip mark bruises of different ages on the upper arms are a pattern of inflicted injury. Anticoagulation does not explain their shape. Speak with her alone, document carefully and involve social work before discharge.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.cchr, S.rosen],
    ...META,
  },
  {
    id: "lacerations-12",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Punctures from a household pet",
    stem:
      "A 58-year-old woman presents 6 hours after her own cat bit her right index finger while she was giving it a pill. There are two deep punctures on the palmar surface over the proximal phalanx. She had a splenectomy after a car crash 20 years ago. She takes methotrexate and prednisone 10 mg daily for rheumatoid arthritis. The cat is an indoor cat with current rabies vaccination. Vital signs are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What host factors increase her risk of serious infection from this bite?",
        accept: [
          { id: "asplenia", text: "Asplenia", match: ["splenectomy", "spleen", "asplenic", "asplenia"] },
          { id: "mtx", text: "Methotrexate", match: ["methotrexate"] },
          { id: "pred", text: "Prednisone", match: ["prednisone", "steroid"] },
          { id: "ra", text: "Rheumatoid arthritis with immunosuppression", match: ["rheumatoid", "immunosuppressed", "immunosuppression", "immunosuppressive", "immunocompromised"] },
        ],
        explanation:
          "Asplenia raises the risk of overwhelming sepsis from bite organisms such as Capnocytophaga and Pasteurella. Methotrexate and corticosteroids blunt the immune response and can mask early signs of infection.",
        keyFeature: { topic: "infectious-diseases", n: 3 },
        source: "idsa-ssti",
      },
      {
        id: "q2",
        kind: "single",
        update: "She has no drug allergies.",
        prompt: "Which of the following antibiotics is most appropriate for this patient?",
        options: [
          "Amoxicillin clavulanate 875/125 mg PO twice daily",
          "Cephalexin 500 mg PO four times daily",
          "Clindamycin 300 mg PO four times daily",
          "Cloxacillin 500 mg PO four times daily",
          "No antibiotic, with a wound check in 48 hours",
        ],
        correct: 0,
        explanation:
          "Cat bites inoculate deeply and infect often, especially on the hand. Pasteurella multocida is the key pathogen, and amoxicillin clavulanate covers it along with staphylococci, streptococci and anaerobes. Cephalexin, cloxacillin and clindamycin alone cover Pasteurella poorly.",
        keyFeature: { topic: "infectious-diseases", n: 8 },
        source: "idsa-ssti",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        prompt: "If she had a history of anaphylaxis to penicillin, what oral regimen would be appropriate?",
        accept: [
          { id: "doxy", text: "Doxycycline", match: ["doxycycline"] },
          { id: "moxi", text: "Moxifloxacin", match: ["moxifloxacin"] },
          { id: "smxmet", text: "Trimethoprim sulfamethoxazole plus metronidazole", match: ["trimethoprim metronidazole", "tmp smx metronidazole", "septra metronidazole", "cotrimoxazole metronidazole", "bactrim metronidazole", "septra flagyl", "tmp smx flagyl", "bactrim flagyl"] },
          { id: "smxclin", text: "Trimethoprim sulfamethoxazole plus clindamycin", match: ["trimethoprim clindamycin", "tmp smx clindamycin", "septra clindamycin", "cotrimoxazole clindamycin", "bactrim clindamycin"] },
        ],
        unacceptable: [
          { text: "Amoxicillin clavulanate", match: ["amoxicillin clavulanate", "clavulin", "amox clav"], dangerous: true },
          { text: "Clindamycin alone", match: ["clindamycin alone", "clindamycin only"] },
          { text: "Cephalexin", match: ["cephalexin"] },
        ],
        explanation:
          "Doxycycline and moxifloxacin both cover Pasteurella. Trimethoprim sulfamethoxazole covers Pasteurella but not anaerobes, so it is combined with metronidazole or clindamycin. Clindamycin alone misses Pasteurella.",
        keyFeature: { topic: "infectious-diseases", n: 8 },
        source: "idsa-ssti",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "She returns 30 hours later. The finger is held slightly flexed and uniformly swollen. There is tenderness along the palmar finger and severe pain on passive extension. Temperature 38.2°C.",
        prompt: "What actions are needed now?",
        accept: [
          { id: "hand", text: "Urgent hand surgery consultation for flexor sheath irrigation", match: ["hand surgery", "hand surgeon", "plastic", "irrigation", "washout"] },
          { id: "ivabx", text: "IV antibiotics covering Pasteurella, staphylococci, streptococci and anaerobes, such as piperacillin tazobactam", match: ["iv antibiotic", "piperacillin", "intravenous antibiotic", "ceftriaxone", "ampicillin sulbactam", "unasyn"] },
          { id: "cult", text: "Blood cultures", match: ["blood culture", "culture"] },
          { id: "splint", text: "Splint and elevate", match: ["splint", "splinting", "elevate", "elevation", "elevated"] },
          { id: "admit", text: "Admit to hospital", match: ["admit", "admission"] },
          { id: "labs", text: "CBC and lactate given asplenia", match: ["cbc", "lactate"] },
        ],
        unacceptable: [
          { text: "Change to a different oral antibiotic and discharge", match: ["change oral antibiotic", "switch oral antibiotic", "different oral antibiotic", "discharge home"] },
        ],
        explanation:
          "These are the Kanavel signs of flexor tenosynovitis. It needs IV antibiotics and urgent hand surgery for sheath drainage. In an asplenic, immunosuppressed patient, watch closely for sepsis.",
        keyFeature: { topic: "infectious-diseases", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.idsa, S.rosen],
    ...META,
  },
  {
    id: "lacerations-13",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Warehouse worker with a forearm cut",
    stem:
      "A 30-year-old warehouse worker cut his left forearm with a new box cutter 1 hour ago. There is a 4 cm linear laceration on the dorsal forearm through the dermis with clean edges. Bleeding stopped with pressure. Motor, sensory and vascular examination of the hand is normal. He is healthy. He had a Tdap booster 7 years ago.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What questions about the injury or patient help confirm this is a low risk wound?",
        accept: [
          { id: "object", text: "What cut him, and was the object clean", match: ["object", "clean", "what cut", "blade"] },
          { id: "time", text: "Time since injury", match: ["time", "when", "late presentation", "3 hour"] },
          { id: "fb", text: "Any possibility of a foreign body such as a broken blade", match: ["foreign body", "broken"] },
          { id: "contam", text: "Contamination with soil or other material", match: ["contaminated", "contamination", "dirt", "soil"] },
          { id: "host", text: "Diabetes, immunosuppression or other host factors", match: ["diabete", "immune", "immunocompromised", "immunosuppressed", "immunosuppression", "immunosuppressant", "host"] },
          { id: "intent", text: "Whether the injury was intentional", match: ["intentional", "intent", "self harm", "self inflicted"] },
          { id: "func", text: "Any weakness or numbness in the hand", match: ["numb", "numbness", "weak", "weakness"] },
        ],
        explanation:
          "Mechanism, contamination, wound age, foreign body risk and host factors decide whether a wound is low risk. A clean sharp blade within a few hours in a healthy host is the lowest risk scenario. Always consider self harm in forearm lacerations.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "singer-nejm",
      },
      {
        id: "q2",
        kind: "single",
        update: "He asks for antibiotics because a coworker had an infection last year.",
        prompt: "Which of the following is the most appropriate response to his request for antibiotics?",
        options: [
          "Amoxicillin clavulanate 875/125 mg PO twice daily for 3 days",
          "Cephalexin 500 mg PO four times daily for 5 days",
          "Single dose of cefazolin 2 g IV",
          "Topical antibiotic ointment three times daily",
          "No antibiotics",
        ],
        correct: 4,
        explanation:
          "Clean, simple lacerations in healthy people do not need prophylactic antibiotics. Infection rates are low and are not reduced by antibiotics. Explain this and give clear return advice instead.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "singer-nejm",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is correct about his tetanus prophylaxis at this visit?",
        options: [
          "Td and tetanus immune globulin now",
          "Tdap booster dose now",
          "Tetanus antibody level before deciding",
          "Tetanus immune globulin alone",
          "No tetanus vaccine is needed today",
        ],
        correct: 4,
        explanation:
          "For a clean minor wound in a person with a completed primary series, a booster is needed only if the last dose was 10 or more years ago. The 5 year interval applies to other wounds, such as contaminated or puncture wounds.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-tetanus",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What are the elements of your repair and aftercare plan?",
        accept: [
          { id: "irr", text: "Irrigate with tap water or saline", match: ["irrigate", "irrigation", "irrigated", "tap water"] },
          { id: "suture", text: "Simple interrupted sutures, such as 4-0 nylon", match: ["suture", "nylon", "prolene"] },
          { id: "absorb", text: "Absorbable sutures to avoid removal", match: ["absorbable", "gut", "vicryl rapide"] },
          { id: "adhesive", text: "Tissue adhesive if edges come together easily", match: ["adhesive", "glue", "dermabond"] },
          { id: "remove", text: "Remove sutures in 7 to 10 days", match: ["7 day", "10 day", "removal", "remove"] },
          { id: "shower", text: "Keep dry for 24 to 48 hours, then gentle washing is allowed", match: ["shower", "wash", "dry"] },
          { id: "return", text: "Return for redness, swelling, pus or fever", match: ["return", "sign of infection", "infection"] },
        ],
        explanation:
          "Tap water irrigation is as effective as sterile saline for simple wounds. Forearm sutures come out at about 7 to 10 days. Absorbable sutures or adhesive avoid a return visit and give similar cosmetic results in low tension wounds.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "cochrane-water",
      },
    ],
    sources: [S.singer, S.cigTet, S.water],
    ...META,
  },
  {
    id: "lacerations-14",
    topic: "lacerations",
    alsoTopics: ["eye", "infectious-diseases"],
    title: "Child bitten on the face",
    stem:
      "In your Ontario emergency department, a 5-year-old girl was bitten on the face 1 hour ago by her grandparents' Labrador retriever when she hugged it. She has a 2 cm laceration through the lower eyelid starting just medial to the punctum, and a 3 cm laceration on the cheek. She is crying but consolable. She is fully immunized. The dog is healthy and up to date with rabies vaccination.",
    vitals: { weight: "20 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features of the eyelid and eye must you assess?",
        accept: [
          { id: "canal", text: "Involvement of the lacrimal canaliculus medial to the punctum", match: ["canaliculus", "canalicular", "canaliculi", "lacrimal", "tear duct", "nasolacrimal"] },
          { id: "margin", text: "Involvement of the lid margin", match: ["lid margin", "margin"] },
          { id: "full", text: "Full thickness lid injury", match: ["full thickness"] },
          { id: "fat", text: "Orbital fat in the wound, indicating septal penetration", match: ["fat", "septum", "septal"] },
          { id: "globe", text: "Globe injury, including visual acuity", match: ["globe", "visual acuity", "acuity", "vision"] },
          { id: "fb", text: "Foreign body or tooth fragment", match: ["foreign body", "tooth"] },
        ],
        explanation:
          "A lower lid laceration medial to the punctum should be presumed to involve the canaliculus. Lid margin, full thickness injury and orbital fat also need specialist repair. Always check visual acuity and look for a globe injury.",
        keyFeature: { topic: "lacerations", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        update: "Examination confirms a canalicular laceration.",
        prompt: "Which of the following is the most appropriate management of the eyelid wound?",
        options: [
          "Closure by the emergency physician after an orbital CT scan",
          "Emergency department closure with 6-0 absorbable sutures",
          "Leave open to heal by secondary intention",
          "Ophthalmology or oculoplastic repair with canalicular stent",
          "Tissue adhesive and review in 48 hours",
        ],
        correct: 3,
        explanation:
          "Canalicular lacerations need ophthalmology or oculoplastic referral for microsurgical repair with canalicular intubation, a stent that prevents chronic tearing. Repair is usually done within a day or two by ophthalmology or oculoplastics, often under general anaesthesia in a child.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What are the elements of your management of the cheek laceration?",
        accept: [
          { id: "irr", text: "Thorough irrigation", match: ["irrigate", "irrigation", "irrigated"] },
          { id: "debride", text: "Debride devitalized tissue conservatively", match: ["debride", "debridement", "debrided"] },
          { id: "primary", text: "Primary closure is acceptable on the face after cleaning", match: ["primary closure", "suture", "close primarily", "primarily close", "close wound", "close laceration", "closed primarily"] },
          { id: "sedation", text: "Procedural sedation or repair under the same general anaesthetic", match: ["sedation", "ketamine", "general anaesthesia", "general anaesthetic", "general anesthesia", "general anesthetic"] },
          { id: "nerve", text: "Check facial nerve function and parotid duct", match: ["facial nerve", "parotid"] },
        ],
        explanation:
          "Facial dog bite lacerations can be closed primarily after thorough irrigation and debridement. The face has an excellent blood supply, so infection rates are low and cosmetic results are better with closure. Check the facial nerve and parotid duct with deep cheek wounds.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "single",
        update: "She has no allergies.",
        prompt: "Which of the following is the most appropriate antibiotic plan for this child?",
        options: [
          "Amoxicillin clavulanate orally for 3 to 5 days",
          "Azithromycin orally once daily for 3 days",
          "Cephalexin orally four times daily for 7 days",
          "Topical mupirocin ointment only",
          "No antibiotics",
        ],
        correct: 0,
        explanation:
          "Short course prophylaxis with amoxicillin clavulanate is recommended for moderate to severe dog bites, including those on the face that are closed primarily. It covers Pasteurella, staphylococci, streptococci and anaerobes. Cephalexin and azithromycin alone are not ideal.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "idsa-ssti",
      },
      {
        id: "q5",
        kind: "short",
        required: 2,
        update: "The family asks whether she needs rabies shots.",
        prompt: "What are the elements of your answer or actions?",
        accept: [
          { id: "noPEP", text: "Rabies prophylaxis is not needed now because the dog is healthy, vaccinated and can be observed", match: ["not needed", "no rabies", "not required", "not indicated", "withhold"] },
          { id: "obs", text: "The dog should be observed for 10 days", match: ["10 day", "ten day", "observe", "observation", "observed"] },
          { id: "report", text: "Report the bite to public health", match: ["public health", "report", "reported", "reporting", "notify"] },
        ],
        explanation:
          "Rabies post-exposure prophylaxis can be withheld when a healthy dog is available for a 10 day observation. Report the bite to the local public health unit, which arranges observation and follows up.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "hppa",
      },
    ],
    sources: [S.tintinalli, S.rosen, S.idsa, S.hppa],
    ...META,
  },
  {
    id: "lacerations-15",
    topic: "lacerations",
    alsoTopics: ["infectious-diseases"],
    title: "Wildlife rehabilitation worker",
    stem:
      "A 32-year-old wildlife rehabilitation worker in the Hamilton, Ontario, area presents 2 hours after being bitten on the left forearm by a raccoon that wandered into the centre's yard and was acting aggressively. The raccoon ran off. She has two 4 mm puncture wounds and a 1 cm laceration. She completed a documented 3 dose rabies pre-exposure vaccine series 3 years ago. She is healthy. Her last tetanus booster was 2 years ago.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What information determines her rabies risk and management?",
        accept: [
          { id: "species", text: "The species of animal", match: ["species", "raccoon", "type of animal"] },
          { id: "behav", text: "Unprovoked attack or abnormal behaviour", match: ["behaviour", "behavior", "unprovoked", "provoked", "aggressive"] },
          { id: "avail", text: "Whether the animal is available for testing", match: ["available", "testing", "captured", "caught"] },
          { id: "type", text: "Type of exposure, such as bite, scratch or saliva on mucosa", match: ["type of exposure", "bite", "scratch", "saliva"] },
          { id: "local", text: "Local rabies activity in that species", match: ["local rabies", "local activity", "local epidemiology", "endemic", "rabies activity", "outbreak"] },
          { id: "prior", text: "Documented prior rabies vaccination", match: ["prior vaccine", "prior vaccination", "previous vaccine", "previous vaccination", "pre exposure", "documented"] },
          { id: "immune", text: "Immune status", match: ["immune", "immunocompromised", "immunosuppressed", "immunosuppression", "immunosuppressant"] },
        ],
        explanation:
          "Species, local rabies activity, behaviour, availability for testing and type of exposure set the risk. A raccoon strain rabies outbreak began in the Hamilton area in 2015. Cases have fallen sharply with vaccine baiting, but the area remains under surveillance. Documented prior vaccination changes the regimen.",
        keyFeature: { topic: "lacerations", n: 1 },
        source: "on-rabies",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following rabies prophylaxis regimens is most appropriate for her?",
        options: [
          "Rabies immune globulin 20 IU/kg and 4 vaccine doses",
          "Rabies immune globulin only, without vaccine",
          "Rabies vaccine IM days 0 and 3, no immune globulin",
          "Rabies vaccine series of 5 doses, no immune globulin",
          "No prophylaxis",
        ],
        correct: 2,
        explanation:
          "A person with a documented 3 dose pre-exposure series needs two vaccine doses of 1 mL IM on days 0 and 3. Immune globulin is not given because it can blunt the anamnestic response. The newer 2 dose series is different. If the second dose was 3 or more years ago, the Canadian Immunization Guide advises full prophylaxis with immune globulin. Exposure to a wild terrestrial carnivore that cannot be tested still requires prophylaxis.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "cig-rabies",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What elements of local wound care reduce rabies and bacterial infection risk?",
        accept: [
          { id: "soap", text: "Immediate thorough washing with soap and water for about 15 minutes", match: ["soap", "wash"] },
          { id: "irr", text: "Copious irrigation", match: ["irrigate", "irrigation", "irrigated"] },
          { id: "virucidal", text: "Apply a virucidal agent such as povidone iodine", match: ["povidone", "iodine", "virucidal"] },
          { id: "noclose", text: "Avoid primary closure of the punctures", match: ["avoid closure", "not close", "don close", "dont close", "no suture", "leave open", "avoid suture", "delay closure", "delayed closure"] },
          { id: "debride", text: "Debride devitalized tissue", match: ["debride", "debridement", "debrided"] },
        ],
        unacceptable: [
          { text: "Suture the punctures closed", match: ["suture puncture", "close puncture"] },
        ],
        explanation:
          "Prompt, vigorous washing with soap and water reduces rabies transmission and is recommended for every exposure. Irrigation and a virucidal antiseptic add to this. Punctures should not be sutured.",
        keyFeature: { topic: "lacerations", n: 3 },
        source: "cig-rabies",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What further steps are needed before she leaves?",
        accept: [
          { id: "report", text: "Report the exposure to the local public health unit", match: ["public health", "report", "reported", "reporting", "notify"] },
          { id: "abx", text: "Prophylactic amoxicillin clavulanate for the puncture wounds", match: ["amoxicillin clavulanate", "clavulin", "amox clav", "antibiotic"] },
          { id: "fu", text: "Arrange the day 3 vaccine dose and a wound check", match: ["day 3", "follow up", "wound check", "recheck"] },
          { id: "return", text: "Return instructions for signs of infection", match: ["return", "sign of infection"] },
          { id: "worksafe", text: "Workplace injury report", match: ["wsib", "workplace"] },
        ],
        unacceptable: [
          { text: "Tetanus booster", match: ["tetanus booster", "tdap"] },
        ],
        explanation:
          "Animal exposures are reportable to the medical officer of health in Ontario. Puncture bites from a wild animal warrant prophylactic antibiotics and early review. Her tetanus booster 2 years ago is current, so none is needed.",
        keyFeature: { topic: "lacerations", n: 4 },
        source: "hppa",
      },
    ],
    sources: [S.onRabies, S.cigRab, S.hppa],
    ...META,
  },
];
