// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Draft for review by Arjan Dhoot, MD", version: 1 } as const;

const S = {
  ctas: { id: "ctas", citation: "Bullard MJ, et al. Revisions to the Canadian Emergency Department Triage and Acuity Scale (CTAS) guidelines 2016. CJEM. 2017." },
  start: { id: "start", citation: "Benson M, Koenig KL, Schultz CH. Disaster triage. START, then SAVE. A new method of dynamic triage for victims of a catastrophic earthquake. Prehosp Disaster Med. 1996." },
  jumpstart: { id: "jumpstart", citation: "Romig LE. Pediatric triage. A system to JumpSTART your triage of young patients at MCIs. JEMS. 2002." },
  salt: { id: "salt", citation: "Lerner EB, et al. Mass casualty triage. An evaluation of the data and development of a proposed national guideline. Disaster Med Public Health Prep. 2008." },
  ohaCodes: { id: "oha-codes", citation: "Ontario Hospital Association. Emergency management toolkit and standardized hospital emergency codes." },
  ipass: { id: "ipass", citation: "Starmer AJ, et al. Changes in medical errors after implementation of a handoff program. N Engl J Med. 2014." },
  cpsiFramework: { id: "cpsi-ciaf", citation: "Canadian Patient Safety Institute. Canadian Incident Analysis Framework. 2012." },
  cpsiDisclosure: { id: "cpsi-disclosure", citation: "Canadian Patient Safety Institute. Canadian Disclosure Guidelines. Being open with patients and families. 2011." },
  caepCrowding: { id: "caep-crowding", citation: "Affleck A, Parks P, Drummond A, Rowe BH, Ovens HJ. Emergency department overcrowding and access block. CAEP position statement. CJEM. 2013." },
  atls: { id: "atls", citation: "American College of Surgeons Committee on Trauma. Advanced Trauma Life Support Student Course Manual. Chapters on initial assessment, teamwork and transfer to definitive care." },
  nrp: { id: "nrp", citation: "American Academy of Pediatrics and American Heart Association. Textbook of Neonatal Resuscitation (NRP). 8th edition." },
  sogcPph: { id: "sogc-pph", citation: "Robinson D, et al. Guideline No. 431. Postpartum hemorrhage and hemorrhagic shock. J Obstet Gynaecol Can. 2022.", url: "https://www.jogc.com/article/S1701-2163(22)00668-5/abstract" },
  ssc: { id: "ssc", citation: "Evans L, et al. Surviving Sepsis Campaign. International guidelines for management of sepsis and septic shock 2021. Crit Care Med. 2021." },
  csbpr: { id: "csbpr", citation: "Heart and Stroke Foundation of Canada. Canadian Stroke Best Practice Recommendations. Acute stroke management." },
  eddleston: { id: "eddleston-op", citation: "Eddleston M, Buckley NA, Eyer P, Dawson AH. Management of acute organophosphorus pesticide poisoning. Lancet. 2008." },
  abls: { id: "abls", citation: "American Burn Association. Advanced Burn Life Support Provider Manual." },
  criticall: { id: "criticall", citation: "CritiCall Ontario. Emergency consultation and referral service for Ontario hospitals." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. Elsevier. Chapters on disaster preparedness, ED crowding and airway management." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, et al, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. McGraw Hill. Chapters on disaster preparedness, hazardous materials, organophosphates and hyperkalemia." },
} satisfies Record<string, Source>;

export const MULTIPLE_PATIENTS_SAMPS: Samp[] = [
  {
    id: "multiple-patients-01",
    topic: "multiple-patients",
    title: "Night shift at a small rural hospital",
    stem:
      "It is 02:30. You are the only physician in a 10 bed emergency department in rural Ontario. You have three nurses. A respiratory therapist is on site. Within 10 minutes these patients arrive.\nA. A 71 year old man with 40 minutes of crushing chest pain. HR 58, BP 98/62. The triage ECG shows inferior ST elevation. The nearest PCI centre is 2.5 hours away.\nB. A 19 year old woman brought in by friends after a party. GCS 8, snoring respirations, RR 6, SpO2 84% on room air. Pupils are pinpoint.\nC. A 3 year old with a barking cough and stridor at rest with mild retractions. SpO2 96%.\nD. A 45 year old man with an ankle injury. Normal vital signs. Pain 7/10.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which patient should you attend to first? Select one.",
        options: ["Patient A", "Patient B", "Patient C", "Patient D"],
        correct: 1,
        explanation:
          "Patient B has an immediate threat to airway and breathing with hypoxia and hypoventilation. It is also quickly reversible with airway positioning, bag mask ventilation and naloxone. Patient A is next and much of his care can start by delegation. A nurse can place him on the monitor, give ASA and start an IV while you secure B's airway.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "While you manage patient B, list THREE specific tasks you delegate for the other patients.",
        accept: [
          { id: "asa", text: "Nurse gives ASA 162 to 325 mg chewed to patient A", match: ["asa", "aspirin", "acetylsalicylic"] },
          { id: "ecg", text: "Right sided ECG leads and IV access for patient A", match: ["right sided", "v4r", "iv access", "iv line"] },
          { id: "lytics", text: "Prepare tenecteplase for patient A", match: ["tenecteplase", "tnk", "thrombolytic", "fibrinolytic", "fibrinolysis", "lytic"] },
          { id: "dex", text: "Dexamethasone for patient C", match: ["dexamethasone", "steroid"] },
          { id: "neb", text: "Nebulized epinephrine for patient C", match: ["nebulized epinephrine", "racemic epinephrine", "epinephrine neb", "epinephrine nebulizer"] },
          { id: "analg", text: "Analgesia and splint for patient D", match: ["analgesia", "ibuprofen", "acetaminophen", "splint", "ice"] },
          { id: "rt", text: "RT supports ventilation of patient B with a bag valve mask", match: ["rt bag", "respiratory therapist", "bag valve mask", "bvm"] },
          { id: "monitor", text: "Cardiac monitor and defibrillator pads for patient A", match: ["monitor", "pad"] },
        ],
        unacceptable: [
          { text: "Nitroglycerin for patient A, who has an inferior STEMI with borderline blood pressure", match: ["nitroglycerin", "nitro", "nitrate", "ntg"] },
        ],
        explanation:
          "A single physician can run several resuscitations by giving clear, specific orders to named team members. Most early care for STEMI and croup is protocol driven. Closed loop communication confirms each task is done. Nitroglycerin is avoided in patient A because an inferior STEMI with a low normal blood pressure may involve the right ventricle.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "Patient B wakes after naloxone. Patient A's pain continues. The PCI centre cannot accept him within 120 minutes.",
        prompt: "List TWO calls you make now to get help.",
        accept: [
          { id: "backup", text: "Call in the on call or backup physician", match: ["backup", "back up", "on call physician", "colleague", "second physician", "another physician"] },
          { id: "cardio", text: "Cardiology at the PCI centre through CritiCall for advice and transfer after fibrinolysis", match: ["criticall", "cardiology", "cardiologist", "pci centre", "pci center"] },
          { id: "transport", text: "Arrange transport such as Ornge or land critical care transport", match: ["ornge", "transport", "ambulance", "ems"] },
          { id: "nurse", text: "Call in an extra nurse", match: ["extra nurse", "another nurse", "additional nurse", "call in nurse"] },
          { id: "lab", text: "On call lab and radiology technologists", match: ["lab", "radiology", "technologist", "x ray tech"] },
        ],
        explanation:
          "When the load exceeds what one physician can safely manage, call early. A colleague can take over one patient while you manage another. CritiCall links you to cardiology and arranges transfer after fibrinolysis when PCI is too far away.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "criticall",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "Patient B is now GCS 14 with RR 14. List TWO elements of your ongoing plan for her.",
        accept: [
          { id: "obs", text: "Continuous monitoring with frequent reassessment for resedation", match: ["monitor", "monitoring", "reassess", "reassessment", "observe", "observation", "resedation"] },
          { id: "duration", text: "Observe for recurrent toxicity because naloxone wears off before many opioids", match: ["wear off", "short acting", "duration", "recur", "recurrent"] },
          { id: "repeat", text: "Repeat naloxone or start an infusion if respiratory depression recurs", match: ["repeat naloxone", "naloxone infusion", "infusion"] },
          { id: "coing", text: "Look for co-ingestants with acetaminophen level, glucose and ECG", match: ["acetaminophen", "glucose", "ecg", "co ingestant", "coingestant"] },
          { id: "etco2", text: "End tidal CO2 monitoring", match: ["etco2", "end tidal", "capnography"] },
        ],
        explanation:
          "Once the immediate threat is controlled, the patient still needs timely reassessment. Naloxone often wears off before the opioid does, so resedation can occur while your attention is elsewhere. Assign a nurse to monitor her and set clear triggers to call you.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [S.ctas, S.rosen, S.criticall, S.tintinalli],
    ...META,
  },
  {
    id: "multiple-patients-02",
    topic: "multiple-patients",
    title: "Busy triage desk",
    stem:
      "You are helping at triage in a busy urban emergency department. Six adults are waiting to be assigned a CTAS level.\n1. A 58 year old woman with 30 minutes of central chest pressure radiating to her jaw. HR 96, BP 150/90, SpO2 97%.\n2. A 24 year old man with 3 days of sore throat. T 38.1 C, HR 92. He is swallowing and looks well.\n3. A 67 year old man receiving chemotherapy for lymphoma. T 38.4 C, HR 104, BP 118/70.\n4. A 35 year old woman with 2 years of low back pain, unchanged, pain 4/10. Normal vital signs.\n5. A 42 year old man with a 3 cm forearm laceration. Bleeding controlled. Pain 3/10. Normal vital signs.\n6. A 30 year old woman with an itchy rash for 1 week. Normal vital signs.",
    questions: [
      {
        id: "q1",
        kind: "menu",
        select: 2,
        prompt: "Which TWO patients should be assigned CTAS level 2? Select TWO.",
        options: ["Patient 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6"],
        correct: [0, 2],
        explanation:
          "Chest pain with cardiac features is CTAS 2 even with normal vital signs. Fever in an immunocompromised patient, such as one on chemotherapy, is CTAS 2 because of the risk of neutropenic sepsis. The others are lower acuity.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "What CTAS level is most appropriate for patient 5? Select one.",
        options: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
        correct: 3,
        explanation:
          "A laceration needing closure with controlled bleeding, mild pain and normal vital signs is CTAS 4. For peripheral pain, level 3 needs severe acute pain of 8 to 10. Level 3 could also come from a vital sign modifier or uncontrolled bleeding.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "State the CTAS target for time to physician assessment for level 2 and for level 3.",
        accept: [
          { id: "l2", text: "Level 2 within 15 minutes", match: ["15 minute", "15 min"] },
          { id: "l3", text: "Level 3 within 30 minutes", match: ["30 minute", "30 min"] },
        ],
        unacceptable: [
          { text: "Level 2 within 60 minutes", match: ["60 minute", "60 min"] },
        ],
        explanation:
          "CTAS targets are immediate for level 1, 15 minutes for level 2, 30 minutes for level 3, 60 minutes for level 4 and 120 minutes for level 5. Nurses should reassess waiting patients at about the same intervals.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "Ninety minutes later, the triage nurse tells you patient 2 is now drooling, speaking in a muffled voice and sitting forward. SpO2 95%.",
        prompt: "List THREE immediate actions.",
        accept: [
          { id: "retriage", text: "Re-triage to a higher acuity level", match: ["retriage", "re triage", "upgrade", "ctas 1", "ctas 2", "level 1", "level 2"] },
          { id: "resus", text: "Move him now to the resuscitation room with monitoring", match: ["resuscitation room", "resus", "monitored bed", "monitored"] },
          { id: "see", text: "Physician assessment immediately", match: ["see now", "assess now", "immediately", "assess immediately"] },
          { id: "airway", text: "Call anaesthesia or ENT and prepare for a difficult airway", match: ["anaesthesia", "anesthesia", "ent", "otolaryngology", "difficult airway", "double setup", "cricothyrotomy"] },
          { id: "upright", text: "Keep him sitting upright and avoid agitating him", match: ["upright", "sitting", "position of comfort", "avoid agitating"] },
          { id: "abx", text: "IV antibiotics such as ceftriaxone", match: ["ceftriaxone", "antibiotic"] },
        ],
        unacceptable: [
          { text: "Lie him flat to examine the throat with a tongue depressor", match: ["lie flat", "supine", "tongue depressor"], dangerous: true },
        ],
        explanation:
          "Drooling, muffled voice and tripod positioning suggest impending airway obstruction, such as epiglottitis or a deep neck infection. A waiting patient whose condition changes must be re-triaged and seen at once. Keep him upright and bring airway expertise to the bedside.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "rosen",
      },
    ],
    sources: [S.ctas, S.rosen],
    ...META,
  },
  {
    id: "multiple-patients-03",
    topic: "multiple-patients",
    alsoTopics: ["ems"],
    title: "Call from a highway",
    stem:
      "It is 14:00 on a weekday. You work in the emergency department of a 200 bed community hospital in northern Ontario. The nearest trauma centre is 2 hours away by land. EMS dispatch calls. A highway coach carrying 38 passengers has rolled over 20 minutes from your hospital. They expect to send you at least 15 patients, the first within 25 minutes. Your department has 6 patients, 2 of them admitted and waiting for beds.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate actions to prepare your hospital.",
        accept: [
          { id: "code", text: "Activate the hospital external disaster plan, Code Orange", match: ["code orange", "disaster plan", "mass casualty plan", "emergency plan"] },
          { id: "admin", text: "Notify the administrator on call and set up incident command", match: ["administrator", "incident command", "incident management"] },
          { id: "staff", text: "Call in extra physicians, nurses and support staff", match: ["call in", "fan out", "extra staff", "additional staff", "more staff", "call back"] },
          { id: "clear", text: "Clear the department by moving admitted patients up and discharging stable patients", match: ["clear", "discharge", "move admitted", "decant"] },
          { id: "triage", text: "Set up a triage point at the ambulance entrance with an experienced triage lead", match: ["triage area", "triage point", "triage officer", "triage lead", "triage station"] },
          { id: "notify", text: "Alert the OR, blood bank, laboratory and diagnostic imaging", match: ["operating room", "blood bank", "laboratory", "diagnostic imaging", "ct"] },
          { id: "tc", text: "Contact the regional trauma centre and CritiCall early", match: ["trauma centre", "trauma center", "criticall"] },
        ],
        explanation:
          "A known surge of this size exceeds normal capacity, so the disaster plan must be activated before the first patient arrives. Early activation brings in staff, clears space and warns support services. The trauma centre should hear early because some patients will need transfer.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "oha-codes",
      },
      {
        id: "q2",
        kind: "menu",
        select: 4,
        prompt: "Paramedics are using START triage at the scene. Which FOUR adults should be tagged red (immediate)? Select FOUR.",
        options: [
          "Walking, with a scalp laceration",
          "Not walking. RR 36",
          "Not walking. RR 20, radial pulse present, follows commands, deformed thigh",
          "Not breathing. Starts breathing after the airway is repositioned",
          "Not breathing after the airway is repositioned",
          "Not walking. RR 22, radial pulse absent",
          "Not walking. RR 18, radial pulse present, cannot follow simple commands",
          "Not walking. RR 16, capillary refill 1 second, follows commands, pelvic pain",
        ],
        correct: [1, 3, 5, 6],
        explanation:
          "In START, respirations over 30, breathing only after airway repositioning, an absent radial pulse or delayed capillary refill, and inability to follow commands each mean red. Non ambulatory patients without these are yellow. No breathing after repositioning is expectant.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "start",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "A 6 year old passenger is not breathing but has a palpable pulse. Breathing does not start after airway repositioning. Using JumpSTART, what is the next step? Select one.",
        options: [
          "Tag black (expectant) and move on",
          "Give 5 rescue breaths, then tag red if breathing starts",
          "Start CPR",
          "Tag yellow and move on",
          "Stay with the child and ventilate until an ambulance is available",
        ],
        correct: 1,
        explanation:
          "Children more often have a respiratory cause of apnea. JumpSTART adds 5 rescue breaths for an apneic child with a pulse. If breathing resumes the child is red. If not, the child is expectant, and the triager moves on.",
        keyFeature: { topic: "ems", n: 4 },
        source: "jumpstart",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "List THREE ways to create capacity in your hospital for these patients.",
        accept: [
          { id: "admit", text: "Move admitted ED patients to inpatient units, including hallway beds", match: ["move admitted", "admitted patient", "inpatient unit", "inpatient bed", "hallway", "to ward", "to the ward"] },
          { id: "discharge", text: "Early discharge of stable inpatients, reverse triage", match: ["reverse triage", "early discharge", "discharge inpatient", "discharge stable", "discharge"] },
          { id: "elective", text: "Cancel elective surgery and procedures", match: ["cancel elective", "elective"] },
          { id: "pacu", text: "Open the recovery room or other areas as treatment spaces", match: ["pacu", "recovery room", "day surgery", "clinic", "alternate care"] },
          { id: "staff", text: "Call in extra staff", match: ["call in", "extra staff", "additional staff", "call back"] },
          { id: "divert", text: "Redirect non urgent patients to other care", match: ["redirect", "divert", "urgent care", "walk in"] },
        ],
        explanation:
          "Surge capacity comes from space, staff and supplies. Moving admitted patients out, discharging stable inpatients and cancelling elective cases free beds and ORs quickly. Staff call back lists turn that space into usable capacity.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.ohaCodes, S.start, S.jumpstart, S.rosen],
    ...META,
  },
  {
    id: "multiple-patients-04",
    topic: "multiple-patients",
    alsoTopics: ["cqi"],
    title: "End of a long night shift",
    stem:
      "It is 06:55. Your night shift ends at 07:00. You have 9 patients to hand over to the day physician. In the resuscitation room, a 63 year old man with an upper GI bleed has BP 78/44 despite 2 units of red cells. You are about to intubate him. Five patients have results pending. Three are waiting for consultants.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "What is the most appropriate approach to the man in the resuscitation room? Select one.",
        options: [
          "Hand him over verbally at the desk at 07:00 and leave",
          "Hand him over to the charge nurse to pass on",
          "Stay and complete the airway and resuscitation, then hand over at the bedside once he is stable",
          "Leave a written note on the chart for the day physician",
          "Ask the day physician to intubate while you hand over the others",
        ],
        correct: 2,
        explanation:
          "Handover in the middle of a critical intervention is dangerous. The physician running the resuscitation should finish the critical step and then hand over at the bedside. Bedside handover lets the receiver see the patient and ask questions.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "ipass",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE elements of a structured handover for each patient.",
        accept: [
          { id: "severity", text: "Illness severity, stable or watcher or unstable", match: ["severity", "stable", "unstable", "watcher", "acuity"] },
          { id: "summary", text: "Patient summary with working diagnosis", match: ["summary", "diagnosis", "background", "situation"] },
          { id: "actions", text: "Action list of tasks still to be done", match: ["action", "to do", "task"] },
          { id: "pending", text: "Pending results and who will follow them", match: ["pending", "outstanding", "result"] },
          { id: "contingency", text: "Contingency plan if the patient changes", match: ["contingency", "if then", "plan if", "anticipate"] },
          { id: "synthesis", text: "Synthesis or read back by the receiver", match: ["synthesis", "read back", "readback", "summarize back", "closed loop"] },
          { id: "consult", text: "Consults called and their status", match: ["consult", "consultant"] },
          { id: "dispo", text: "Expected disposition", match: ["disposition", "dispo"] },
        ],
        explanation:
          "Structured handover tools such as I-PASS and SBAR reduce omissions and medical errors. The most common omission is a pending result or planned action that no one follows up. A read back by the receiver confirms understanding.",
        keyFeature: { topic: "cqi", n: 5 },
        source: "ipass",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO features of the handover setting that improve its safety.",
        accept: [
          { id: "f2f", text: "Face to face and verbal, with a chance to ask questions", match: ["face to face", "verbal", "in person"] },
          { id: "quiet", text: "Protected time with few interruptions", match: ["interruption", "protected", "quiet", "uninterrupted"] },
          { id: "written", text: "A written or electronic tool to support the verbal handover", match: ["written", "electronic", "tool", "template"] },
          { id: "bedside", text: "At the bedside for unstable patients", match: ["bedside"] },
          { id: "nurse", text: "Include the charge nurse", match: ["nurse"] },
          { id: "document", text: "Document the time responsibility is transferred", match: ["document", "documentation", "documented"] },
        ],
        explanation:
          "Interruptions and rushed handovers are when information is lost. A verbal handover supported by a written tool, in a quiet place, allows questions. Clear documentation shows who is responsible from what time.",
        keyFeature: { topic: "cqi", n: 5 },
        source: "cpsi-ciaf",
      },
      {
        id: "q4",
        kind: "single",
        update: "At 07:25 you are leaving. The laboratory calls you with a critical potassium of 6.9 mmol/L on a patient you handed over.",
        prompt: "What is the most appropriate response? Select one.",
        options: [
          "Tell the laboratory to call the day physician and leave",
          "Order treatment yourself without telling the day physician",
          "Tell the day physician directly, confirm read back, and stay until they take responsibility",
          "Write a note on the chart",
          "Ask the unit clerk to pass on the message",
        ],
        correct: 2,
        explanation:
          "A critical result must reach the physician now responsible, with closed loop confirmation. Passing it through a third party risks loss. If the day physician cannot be reached, the physician who received the call acts.",
        keyFeature: { topic: "cqi", n: 5 },
        source: "cpsi-ciaf",
      },
    ],
    sources: [S.ipass, S.cpsiFramework],
    ...META,
  },
  {
    id: "multiple-patients-05",
    topic: "multiple-patients",
    alsoTopics: ["airway"],
    title: "Alarm in the resuscitation room",
    stem:
      "You are the only physician on overnight in a community emergency department. Twenty minutes ago you intubated a 66 year old woman with a severe COPD exacerbation. She is on a ventilator. A respiratory therapist and two nurses are with you. Paramedics then patch that they are 10 minutes out with a 30 year old motorcyclist. He is hypotensive with a GCS of 13. Now your ventilated patient's SpO2 falls to 80%. The ventilator is alarming for high peak pressure. BP 76/40.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE causes you must check for in this ventilated patient.",
        accept: [
          { id: "disp", text: "Displacement of the endotracheal tube", match: ["displacement", "displaced", "dislodged", "esophageal", "right mainstem", "mainstem"] },
          { id: "obs", text: "Obstruction of the tube, such as a mucus plug or kinking", match: ["obstruction", "plug", "kink", "secretion"] },
          { id: "ptx", text: "Tension pneumothorax", match: ["pneumothorax"] },
          { id: "equip", text: "Equipment failure, including oxygen supply and circuit", match: ["equipment", "circuit", "oxygen supply", "ventilator failure"] },
          { id: "stack", text: "Breath stacking with auto PEEP", match: ["breath stacking", "stacking", "auto peep", "autopeep", "dynamic hyperinflation", "air trapping"] },
        ],
        explanation:
          "The DOPES causes are displacement, obstruction, pneumothorax, equipment failure and stacked breaths. In severe COPD, auto PEEP and pneumothorax both cause high pressures and hypotension. Each can be checked quickly at the bedside.",
        keyFeature: { topic: "airway", n: 6 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate interventions.",
        accept: [
          { id: "disconnect", text: "Disconnect from the ventilator and allow full exhalation", match: ["disconnect", "exhale", "exhalation", "chest compression to exhale"] },
          { id: "bag", text: "Bag with 100% oxygen at a slow rate", match: ["bag", "bvm", "hand ventilate"] },
          { id: "etco2", text: "Check the end tidal CO2 waveform", match: ["etco2", "end tidal", "capnography", "waveform"] },
          { id: "suction", text: "Pass a suction catheter down the tube", match: ["suction"] },
          { id: "pocus", text: "Ultrasound for lung sliding", match: ["ultrasound", "pocus", "lung sliding"] },
          { id: "decompress", text: "Needle or finger thoracostomy if tension pneumothorax is found", match: ["needle", "thoracostomy", "decompress", "decompression", "chest tube"] },
          { id: "fluid", text: "Fluid bolus", match: ["fluid", "bolus"] },
        ],
        explanation:
          "Disconnecting the ventilator relieves auto PEEP and removes equipment as a cause. Bagging with oxygen, checking capnography and passing a suction catheter test the tube. Ultrasound quickly shows a pneumothorax needing decompression.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "Disconnection and a slower ventilator rate restore her BP to 104/60 and SpO2 to 93%. The motorcyclist arrives in 6 minutes.",
        prompt: "List THREE instructions you give now to prepare for the trauma patient.",
        accept: [
          { id: "backup", text: "Call in the on call physician or anaesthetist", match: ["on call", "anaesthetist", "anesthetist", "backup", "back up", "colleague", "second physician"] },
          { id: "rt", text: "RT stays with the ventilated patient", match: ["rt stay", "rt remain", "respiratory therapist stay", "respiratory therapist remain", "stay with ventilated", "rt ventilated", "respiratory therapist ventilated", "rt copd"] },
          { id: "blood", text: "Ask the blood bank for uncrossmatched O blood and activate the massive transfusion protocol", match: ["blood bank", "o negative", "uncrossmatched", "massive transfusion", "mtp", "o positive"] },
          { id: "bay", text: "Assign a nurse to prepare the trauma bay with warmed fluids, rapid infuser and a pelvic binder", match: ["trauma bay", "rapid infuser", "warm", "pelvic binder", "level 1 infuser"] },
          { id: "surgeon", text: "Call the general surgeon", match: ["surgeon", "general surgery"] },
          { id: "tc", text: "Contact the trauma centre early about transfer", match: ["trauma centre", "trauma center", "criticall", "transfer"] },
          { id: "roles", text: "Assign roles to each team member before arrival", match: ["assign role", "roles", "role"] },
        ],
        explanation:
          "Pre-arrival briefing assigns roles so interventions happen in parallel. The ventilated patient still needs a skilled person at the bedside. Blood, a surgeon and the trauma centre should be alerted before the patient arrives.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "The on call anaesthetist will arrive in 20 minutes. Who should manage the ventilated patient until then? Select one.",
        options: [
          "No one. The ventilator alarms will warn you",
          "The unit clerk, who can call you if the alarm sounds",
          "The respiratory therapist, with clear triggers to call you",
          "A nurse from the inpatient ward who has not worked in critical care",
          "Transfer her to the ICU now without a physician",
        ],
        correct: 2,
        explanation:
          "The respiratory therapist is the most skilled available person to watch a ventilated patient. Give clear triggers for calling you, such as a fall in saturation or blood pressure. You remain responsible and reassess her between trauma tasks. Leaving her unwatched, with an untrained person, or in transit without a physician all risk a missed deterioration.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.atls],
    ...META,
  },
  {
    id: "multiple-patients-06",
    topic: "multiple-patients",
    alsoTopics: ["ems", "tox"],
    title: "Farm workers after a spraying accident",
    stem:
      "You are working in a rural emergency department in southwestern Ontario. At 10:30, EMS reports that four farm workers were sprayed with an organophosphate insecticide when a sprayer hose burst. Two ambulances are on scene. Before they arrive, a fifth worker walks into your waiting room. His clothes are soaked. He is vomiting, drooling and sweating.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate actions for the worker in the waiting room.",
        accept: [
          { id: "isolate", text: "Move him out of the waiting room to a designated decontamination area", match: ["move", "isolate", "remove from waiting", "decontamination area", "outside"] },
          { id: "ppe", text: "Staff wear chemical protective gloves and gowns", match: ["ppe", "protective", "glove", "gown", "nitrile", "butyl"] },
          { id: "clothes", text: "Remove and bag his clothing", match: ["clothing", "clothes", "undress"] },
          { id: "wash", text: "Wash his skin with soap and water", match: ["soap", "wash", "decontaminate", "decontamination"] },
          { id: "abc", text: "Assess airway, breathing and circulation", match: ["abc", "airway", "breathing"] },
          { id: "atropine", text: "Atropine for bronchorrhea or bradycardia", match: ["atropine"] },
          { id: "poison", text: "Call the poison centre", match: ["poison centre", "poison center", "poison control"] },
        ],
        explanation:
          "An unannounced contaminated patient can expose staff and other patients. Remove him from the waiting room and decontaminate by removing clothing and washing skin. Staff need protective equipment before hands on care, then treat the toxidrome.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "List TWO instructions you give the paramedics before they arrive.",
        accept: [
          { id: "decon", text: "Remove clothing and decontaminate at the scene before transport", match: ["decontaminate", "decontamination", "remove clothing", "strip", "wash"] },
          { id: "ppe", text: "Wear protective equipment", match: ["ppe", "protective", "glove"] },
          { id: "prealert", text: "Call again before arrival so a decontamination area is ready", match: ["call ahead", "notify", "pre alert", "prealert", "call before"] },
          { id: "entrance", text: "Come to a designated entrance, not the main ambulance bay", match: ["entrance", "designated", "separate"] },
          { id: "triage", text: "Triage by respiratory status and give atropine per their directives", match: ["atropine", "respiratory status", "triage"] },
        ],
        explanation:
          "Field decontamination prevents secondary contamination of ambulances and the department. A pre-arrival call lets you open the decontamination area and a separate entrance. Paramedics may give atropine under directives.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        update: "One worker arrives with copious bronchial secretions, wheeze and HR 44. SpO2 86%.",
        prompt: "Which is the most appropriate initial atropine regimen for this adult? Select one.",
        options: [
          "Atropine 0.5 mg IV once",
          "Atropine 1 to 2 mg IV, doubling the dose every 5 minutes until the chest is clear",
          "Atropine 0.02 mg/kg IV once",
          "Pralidoxime alone without atropine",
          "Glycopyrrolate 0.2 mg IM once",
        ],
        correct: 1,
        explanation:
          "Atropine is titrated to drying of bronchial secretions, not to heart rate or pupils. Start with 1 to 2 mg IV and double the dose every 5 minutes until the chest is clear, then infuse. Large total doses are often needed. Pralidoxime is an adjunct, not a substitute.",
        keyFeature: { topic: "tox", n: 2 },
        source: "eddleston-op",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO clinical findings that place a poisoned worker in the highest priority group.",
        accept: [
          { id: "resp", text: "Bronchorrhea or respiratory distress", match: ["bronchorrhea", "bronchorrhoea", "secretion", "respiratory distress", "wheeze"] },
          { id: "hypox", text: "Hypoxia", match: ["hypoxia", "hypoxemia", "low oxygen", "desaturation"] },
          { id: "brady", text: "Bradycardia or hypotension", match: ["bradycardia", "hypotension"] },
          { id: "loc", text: "Decreased level of consciousness or seizures", match: ["consciousness", "gcs", "seizure", "coma", "obtunded"] },
          { id: "weak", text: "Respiratory muscle weakness or fasciculations", match: ["weakness", "fasciculation", "paralysis"] },
        ],
        explanation:
          "Death in organophosphate poisoning is mainly from respiratory failure due to bronchorrhea, bronchospasm and muscle weakness. Hypoxia, bradycardia with hypotension and a falling level of consciousness mark the patients to treat first.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "eddleston-op",
      },
    ],
    sources: [S.tintinalli, S.eddleston],
    ...META,
  },
  {
    id: "multiple-patients-07",
    topic: "multiple-patients",
    alsoTopics: ["infectious-diseases"],
    title: "Full department on a Monday evening",
    stem:
      "It is 18:00 on a Monday in a large urban emergency department. There are 45 patients in the waiting room and 22 admitted patients occupying stretchers. Every monitored bed is full. The triage nurse tells you that an 80 year old man who has waited 4 hours with dysuria now has BP 84/50, HR 118, RR 26 and T 38.6 C. He is drowsy.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate actions for this man.",
        accept: [
          { id: "move", text: "Bring him into a monitored space now, even if another patient must move", match: ["move", "monitored", "resuscitation", "resus", "bring in"] },
          { id: "retriage", text: "Re-triage to a higher CTAS level", match: ["retriage", "re triage", "ctas", "upgrade"] },
          { id: "cultures", text: "Blood cultures and lactate", match: ["culture", "lactate"] },
          { id: "abx", text: "Broad spectrum IV antibiotics within 1 hour", match: ["antibiotic", "ceftriaxone", "piperacillin"] },
          { id: "fluid", text: "IV crystalloid bolus, about 30 mL/kg", match: ["fluid", "crystalloid", "bolus", "ringer", "saline"] },
          { id: "pressor", text: "Norepinephrine if hypotension persists after fluids", match: ["norepinephrine", "vasopressor", "pressor"] },
        ],
        explanation:
          "A waiting patient who deteriorates must be moved into a treatment space at once. He meets criteria for septic shock. Fluids, cultures and antibiotics within the first hour should not be delayed by a lack of beds.",
        keyFeature: { topic: "infectious-diseases", n: 2 },
        source: "ssc",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE system level actions to address the overcrowding tonight.",
        accept: [
          { id: "admin", text: "Notify the administrator on call and activate the hospital surge or overcapacity protocol", match: ["administrator", "surge", "overcapacity", "over capacity", "escalation"] },
          { id: "fcp", text: "Move admitted patients to inpatient units, including hallway beds under a full capacity protocol", match: ["full capacity", "move admitted", "inpatient unit", "hallway", "ward"] },
          { id: "staff", text: "Call in an extra physician or nurse", match: ["extra physician", "additional physician", "call in", "extra nurse", "additional staff"] },
          { id: "directives", text: "Start nurse initiated medical directives at triage", match: ["medical directive", "directive", "nurse initiated", "protocol at triage"] },
          { id: "rat", text: "Physician in triage or a rapid assessment zone", match: ["physician in triage", "rapid assessment", "fast track", "rat"] },
          { id: "discharge", text: "Speed up inpatient discharges", match: ["discharge"] },
        ],
        explanation:
          "ED crowding is mainly caused by admitted patients who cannot leave, which is access block. Escalation to hospital leadership and moving admitted patients to inpatient units address the cause. Front end strategies such as medical directives help, but do not fix access block.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "caep-crowding",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which intervention best reduces harm from boarding admitted patients in the emergency department? Select one.",
        options: [
          "Diverting all ambulances to other hospitals for the night",
          "Adding a second triage nurse",
          "An inpatient full capacity protocol that moves admitted patients to ward hallways",
          "Discharging waiting room patients without assessment",
          "Asking low acuity patients to leave and see their family physician",
        ],
        correct: 2,
        explanation:
          "Full capacity protocols share the burden of boarding across the hospital. Admitted patients get ward nursing, and ED stretchers open for new patients. Diversion simply shifts risk and sending people away unassessed is unsafe.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "caep-crowding",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO strategies to detect deterioration in waiting room patients.",
        accept: [
          { id: "reassess", text: "Scheduled nurse reassessment at CTAS intervals", match: ["reassess", "reassessment", "ctas interval", "scheduled"] },
          { id: "vitals", text: "Repeat vital signs", match: ["vital", "repeat vital"] },
          { id: "wrnurse", text: "A dedicated waiting room nurse", match: ["waiting room nurse", "dedicated nurse", "dedicated"] },
          { id: "tell", text: "Instruct patients to report any worsening", match: ["report", "tell", "worsening"] },
          { id: "ews", text: "An early warning score", match: ["early warning", "news", "score"] },
        ],
        explanation:
          "Triage is a snapshot. Patients change while they wait, and long waits are when deterioration is missed. Scheduled reassessment with repeat vital signs, ideally by a dedicated nurse, catches the change.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
    ],
    sources: [S.ssc, S.caepCrowding, S.ctas],
    ...META,
  },
  {
    id: "multiple-patients-08",
    topic: "multiple-patients",
    alsoTopics: ["multiple-trauma", "ems"],
    title: "Three patients from one crash",
    stem:
      "You are the only physician in a small hospital emergency department in Ontario. A family physician anaesthetist and a general surgeon are on call from home, 20 minutes away. The nearest trauma centre is 1 hour away by air. Three patients arrive together from one car crash.\nA. A 25 year old driver. GCS 13, RR 32, SpO2 86%. Absent breath sounds on the right. Trachea shifted to the left. HR 134, BP 82/50.\nB. A 55 year old passenger. GCS 15. HR 122, BP 90/60. Severe pelvic pain.\nC. A 17 year old passenger. GCS 15. HR 98, BP 126/78. Bone visible through a shin wound.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "What is your first action? Select one.",
        options: [
          "Intubate patient A",
          "Needle or finger decompression of the right chest of patient A",
          "Apply a pelvic binder to patient B",
          "Chest radiograph for patient A",
          "Give cefazolin to patient C",
        ],
        correct: 1,
        explanation:
          "Patient A has a clinical tension pneumothorax with shock. It is immediately life threatening and is treated on clinical grounds without imaging. Intubation with positive pressure before decompression can precipitate arrest.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE tasks you delegate to your team in parallel.",
        accept: [
          { id: "binder", text: "Apply a pelvic binder to patient B", match: ["binder", "pelvic binder", "sheet"] },
          { id: "iv", text: "Two large bore IVs and bloods for patients A and B", match: ["large bore", "iv access", "two iv", "2 iv"] },
          { id: "blood", text: "Get uncrossmatched blood and activate the massive transfusion protocol", match: ["blood", "massive transfusion", "mtp", "o negative", "uncrossmatched"] },
          { id: "cover", text: "Cover patient C's wound with a sterile moist dressing and splint", match: ["dressing", "splint", "cover wound"] },
          { id: "abx", text: "Cefazolin IV for patient C", match: ["cefazolin", "antibiotic"] },
          { id: "txa", text: "Tranexamic acid for patient B", match: ["tranexamic", "txa"] },
          { id: "monitor", text: "Monitor and repeat vital signs on all three", match: ["monitor", "vital sign", "vitals"] },
          { id: "tetanus", text: "Tetanus for patient C", match: ["tetanus"] },
        ],
        explanation:
          "A single physician must give clear tasks to named team members so care runs in parallel. Pelvic binding, blood and IV access for patient B, and dressing, splinting and antibiotics for patient C's open fracture are all delegable.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE resources or people you call now.",
        accept: [
          { id: "anaes", text: "The family physician anaesthetist", match: ["anaesthetist", "anesthetist", "anaesthesia", "anesthesia"] },
          { id: "surgeon", text: "The general surgeon", match: ["surgeon", "general surgery"] },
          { id: "criticall", text: "CritiCall or the trauma centre to arrange transfer", match: ["criticall", "trauma centre", "trauma center", "trauma team leader"] },
          { id: "ornge", text: "Air ambulance, Ornge", match: ["ornge", "air ambulance", "helicopter"] },
          { id: "staff", text: "Off duty nurses and another physician", match: ["nurse", "physician", "colleague", "staff"] },
          { id: "lab", text: "Laboratory and blood bank", match: ["blood bank", "laboratory", "lab"] },
          { id: "xray", text: "Radiology technologist", match: ["radiology", "technologist", "x ray"] },
        ],
        explanation:
          "Two patients in shock exceed what one physician can manage. Call the anaesthetist and surgeon from home right away. Early contact with CritiCall and Ornge starts transfer while you resuscitate.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "criticall",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "Patient A has been intubated. A chest tube is in place. Ornge will transport him to the trauma centre.",
        prompt: "List THREE steps to prepare him for air transport.",
        accept: [
          { id: "ett", text: "Secure the tube and confirm with end tidal CO2", match: ["secure tube", "secure ett", "end tidal", "etco2", "capnography"] },
          { id: "ct", text: "Chest tube secured and connected to a transport drainage system", match: ["chest tube", "heimlich", "drainage"] },
          { id: "og", text: "Orogastric tube", match: ["orogastric", "og tube", "nasogastric", "gastric tube"] },
          { id: "foley", text: "Urinary catheter", match: ["foley", "urinary catheter", "catheter"] },
          { id: "iv", text: "Two secure IV lines and blood products for the trip", match: ["iv line", "iv access", "two iv", "blood product", "blood for transport"] },
          { id: "sed", text: "Sedation and analgesia infusions", match: ["sedation", "analgesia", "fentanyl", "propofol", "ketamine"] },
          { id: "spine", text: "Spinal motion restriction", match: ["spine", "spinal", "collar"] },
          { id: "records", text: "Copies of imaging, records and a physician to physician handover", match: ["copy", "record", "imaging", "handover"] },
          { id: "warm", text: "Keep him warm", match: ["warm", "hypothermia", "blanket"] },
        ],
        unacceptable: [
          { text: "Needle decompression only without a chest tube", match: ["needle only", "needle alone"] },
        ],
        explanation:
          "Problems in the air are hard to manage. Secure the airway, drain the chest with a chest tube and decompress the stomach. Air in closed spaces expands with altitude, so a needle alone is not enough for transport.",
        keyFeature: { topic: "ems", n: 3 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.criticall],
    ...META,
  },
  {
    id: "multiple-patients-09",
    topic: "multiple-patients",
    alsoTopics: ["infectious-diseases", "cva"],
    title: "Three calls at once",
    stem:
      "It is 04:00. You are the only physician in a mid sized emergency department. There are five nurses and a respiratory therapist. Three things happen within 5 minutes.\nA. Paramedics arrive with a 62 year old man in cardiac arrest. CPR is in progress. The rhythm is ventricular fibrillation.\nB. A 70 year old woman has new right sided weakness and trouble speaking. She was last known well 50 minutes ago. BP 176/92.\nC. A 48 year old woman with pyelonephritis now has BP 86/50 and a lactate of 4.5 mmol/L. She has no orders yet.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE things you do in the first minutes to keep all three patients moving.",
        accept: [
          { id: "lead", text: "Lead the cardiac arrest yourself, with clear roles for the team", match: ["lead the arrest", "lead arrest", "run the arrest", "code leader", "team leader", "lead the code"] },
          { id: "orders", text: "Give verbal orders for patient C, fluids, cultures and antibiotics", match: ["verbal order", "order for c", "fluid", "antibiotic", "culture"] },
          { id: "ct", text: "Send patient B to CT immediately with a nurse under the stroke protocol", match: ["ct", "stroke protocol", "code stroke"] },
          { id: "glucose", text: "Point of care glucose for patient B", match: ["glucose", "sugar"] },
          { id: "backup", text: "Call in a backup physician", match: ["backup", "back up", "on call", "colleague", "second physician"] },
          { id: "neuro", text: "Call the stroke neurologist or telestroke", match: ["neurologist", "telestroke", "neurology", "stroke team"] },
        ],
        explanation:
          "You cannot be in three rooms. Lead the arrest, but give verbal orders for the septic patient and start the stroke protocol through the nurses. Call for backup early. Protocols let each patient progress while you are at the bedside of the sickest.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "For patient C, which order is most important not to delay? Select one.",
        options: [
          "CT of the abdomen",
          "Broad spectrum IV antibiotics",
          "Urine culture",
          "Arterial line insertion",
          "Repeat lactate",
        ],
        correct: 1,
        explanation:
          "In septic shock, each hour of delay in antibiotics increases mortality. Cultures should be drawn when possible but must not hold up antibiotics. Imaging and invasive lines can wait until the patient is stabilized.",
        keyFeature: { topic: "infectious-diseases", n: 2 },
        source: "ssc",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE steps for patient B that nurses can start before you see her.",
        accept: [
          { id: "glucose", text: "Point of care glucose", match: ["glucose", "sugar"] },
          { id: "ct", text: "Non contrast CT head and CT angiography", match: ["ct", "cta", "angiogram", "angiography"] },
          { id: "iv", text: "IV access and bloods", match: ["iv access", "iv line", "bloodwork", "blood work", "lab"] },
          { id: "weight", text: "Weight for thrombolysis dosing", match: ["weight", "weigh"] },
          { id: "npo", text: "Nothing by mouth until swallow screen", match: ["npo", "nothing by mouth", "swallow"] },
          { id: "neuro", text: "Page the stroke neurologist or telestroke", match: ["neurologist", "telestroke", "stroke team", "neurology"] },
          { id: "ecg", text: "ECG", match: ["ecg"] },
        ],
        explanation:
          "Stroke protocols let nurses and CT staff move a patient to imaging without waiting for the physician. Glucose excludes a common mimic. Early contact with the stroke team speeds decisions on thrombolysis and thrombectomy.",
        keyFeature: { topic: "cva", n: 3 },
        source: "csbpr",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Patient A has return of spontaneous circulation. He is intubated. His ECG shows anterior ST elevation.",
        prompt: "List TWO people or services you call to share the load.",
        accept: [
          { id: "icu", text: "ICU or intensivist", match: ["icu", "intensivist", "critical care"] },
          { id: "cardio", text: "Interventional cardiology for the catheterization laboratory", match: ["cardiology", "cardiologist", "cath lab", "catheterization", "pci"] },
          { id: "backup", text: "Backup emergency physician", match: ["backup", "back up", "colleague", "second physician", "on call"] },
          { id: "anaes", text: "Anaesthesia", match: ["anaesthesia", "anesthesia", "anaesthetist", "anesthetist"] },
          { id: "stroke", text: "Stroke neurologist", match: ["neurologist", "stroke team", "telestroke"] },
          { id: "admin", text: "Administrator on call or charge nurse to redistribute staff", match: ["administrator", "charge nurse"] },
        ],
        explanation:
          "Three time critical patients justify calling every available resource. Consultants can take ownership of parts of the care, such as the post arrest STEMI going to the cath lab. Your role is to coordinate and reassess each patient.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.ssc, S.csbpr],
    ...META,
  },
  {
    id: "multiple-patients-10",
    topic: "multiple-patients",
    alsoTopics: ["burns", "multiple-trauma"],
    title: "Fire at a long term care home",
    stem:
      "At 23:00, EMS informs your community hospital that a fire has broken out at a long term care home 10 minutes away. They expect to bring you 9 residents with smoke exposure, 2 with burns. You have 1 other physician, 6 nurses and 1 respiratory therapist in the department.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE hospital level actions before the patients arrive.",
        accept: [
          { id: "code", text: "Activate Code Orange", match: ["code orange", "disaster plan", "mass casualty plan"] },
          { id: "staff", text: "Call in extra physicians, nurses and respiratory therapists", match: ["call in", "extra staff", "additional staff", "more rt", "extra rt", "call back"] },
          { id: "airway", text: "Prepare airway equipment and ventilators", match: ["airway", "ventilator", "intubation"] },
          { id: "icu", text: "Notify ICU and anaesthesia", match: ["icu", "anaesthesia", "anesthesia", "intensivist"] },
          { id: "antidote", text: "Get hydroxocobalamin from pharmacy", match: ["hydroxocobalamin", "cyanokit", "pharmacy"] },
          { id: "burn", text: "Contact the regional burn centre", match: ["burn centre", "burn center", "burn unit"] },
          { id: "clear", text: "Clear space in the department", match: ["clear", "discharge", "move admitted"] },
          { id: "records", text: "Contact the care home for medication lists and advance directives", match: ["medication list", "advance directive", "goals of care", "mar"] },
        ],
        explanation:
          "Nine smoke exposed older adults could overwhelm the department and its airway resources. Activate the plan, bring in people with airway skills, and ready antidotes and ventilators. Care home records will be needed for goals of care.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "oha-codes",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE findings that suggest an inhalation injury needing early intubation.",
        accept: [
          { id: "stridor", text: "Stridor", match: ["stridor"] },
          { id: "voice", text: "Hoarseness or voice change", match: ["hoarse", "hoarseness", "voice"] },
          { id: "soot", text: "Carbonaceous sputum or soot in the oropharynx", match: ["soot", "carbonaceous", "carbon"] },
          { id: "edema", text: "Oropharyngeal swelling or blisters", match: ["edema", "oedema", "swelling", "blister"] },
          { id: "face", text: "Deep facial or neck burns", match: ["facial burn", "neck burn", "face burn", "full thickness"] },
          { id: "distress", text: "Respiratory distress or hypoxia", match: ["distress", "hypoxia", "work of breathing"] },
          { id: "loc", text: "Decreased level of consciousness", match: ["consciousness", "gcs", "obtunded"] },
          { id: "drool", text: "Drooling or trouble swallowing", match: ["drool", "drooling", "dysphagia", "swallow"] },
        ],
        unacceptable: [
          { text: "Singed nasal hair alone", match: ["singed hair alone", "nasal hair alone"] },
        ],
        explanation:
          "Airway swelling after inhalation injury worsens over hours and can make later intubation impossible. Stridor, voice change, soot in the airway and oropharyngeal swelling call for early intubation by the most skilled operator. Singed nasal hair alone is a marker of exposure, not an indication.",
        keyFeature: { topic: "burns", n: 2 },
        source: "abls",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "A 79 year old resident arrives with GCS 9, BP 84/50, lactate 12 mmol/L and SpO2 98% on a non rebreather mask.",
        prompt: "List TWO treatments you give now for likely toxic exposures. Include the dose where relevant.",
        accept: [
          { id: "o2", text: "100% oxygen for carbon monoxide poisoning", match: ["100% oxygen", "high flow oxygen", "100 oxygen", "fio2 100", "non rebreather", "nrb"] },
          { id: "hydroxo", text: "Hydroxocobalamin 5 g IV for cyanide", match: ["hydroxocobalamin 5 g", "hydroxocobalamin 5g", "hydroxocobalamin 5 gram", "hydroxocobalamin 70 mg/kg", "cyanokit 5 g", "cyanokit 5g", "cyanokit 5 gram"] },
        ],
        unacceptable: [
          { text: "Sodium nitrite", match: ["nitrite"], dangerous: true },
        ],
        explanation:
          "Smoke from house fires contains carbon monoxide and hydrogen cyanide. A lactate this high with shock and coma in a fire victim strongly suggests cyanide toxicity. Give hydroxocobalamin 5 g IV and 100% oxygen. Nitrites are relatively contraindicated in smoke inhalation. The methemoglobinemia they induce adds to the oxygen carrying deficit from carbon monoxide, and they cause hypotension in a patient already in shock. If hydroxocobalamin were unavailable, sodium thiosulfate alone is the safer choice.",
        keyFeature: { topic: "burns", n: 1 },
        source: "abls",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "You have one free ventilator and one airway team. Four residents arrive together. Which should be intubated first? Select one.",
        options: [
          "A 91 year old with soot in the nares, normal voice and SpO2 96%",
          "A 76 year old with stridor, hoarseness and oropharyngeal swelling, who wants full treatment",
          "An 84 year old with a documented wish for no intubation, now in respiratory distress",
          "A 69 year old with a mild cough and SpO2 95%",
          "An 88 year old with 5% partial thickness hand burns",
        ],
        correct: 1,
        explanation:
          "The patient with stridor and swelling is at highest risk of losing the airway and wants full treatment. A documented wish for no intubation must be respected, with comfort focused care. Soot alone with a normal voice needs close watching but not immediate intubation.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "abls",
      },
    ],
    sources: [S.ohaCodes, S.abls],
    ...META,
  },
  {
    id: "multiple-patients-11",
    topic: "multiple-patients",
    title: "A delivery and a second patient",
    stem:
      "At 22:00 you are the only physician in a rural Ontario emergency department with no obstetric service. A 28 year old G2P1 at 36 weeks arrives in active labour and delivers within minutes. At the same time, a nurse tells you a 60 year old man in bed 3 has new chest pain. The newborn is limp and not breathing after drying and stimulation.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE calls for help you make now.",
        accept: [
          { id: "physician", text: "Call in the on call family physician or another physician", match: ["on call", "another physician", "second physician", "family physician", "backup", "back up", "colleague"] },
          { id: "nurse", text: "An extra nurse with neonatal resuscitation training", match: ["nrp", "extra nurse", "another nurse", "additional nurse"] },
          { id: "rt", text: "Respiratory therapist", match: ["respiratory therapist", "rt"] },
          { id: "transport", text: "Paediatric or neonatal transport team through CritiCall", match: ["transport team", "neonatal transport", "criticall", "pediatric transport", "paediatric transport"] },
          { id: "peds", text: "Paediatrician or neonatologist by phone", match: ["paediatrician", "pediatrician", "neonatologist", "pediatrics", "paediatrics"] },
          { id: "obs", text: "Obstetrician by phone", match: ["obstetrician", "obstetrics", "obstetric"] },
          { id: "ecg", text: "A nurse gets an ECG on the man in bed 3", match: ["ecg"] },
        ],
        explanation:
          "A compromised newborn and a postpartum mother are two patients, plus the man with chest pain. Call early for anyone with neonatal skills, a colleague and the transport team. A nurse can get the ECG within 10 minutes while you resuscitate.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "criticall",
      },
      {
        id: "q2",
        kind: "single",
        update: "The newborn remains apneic. HR is 80.",
        prompt: "What is the next step? Select one.",
        options: [
          "Start chest compressions",
          "Positive pressure ventilation with a bag and mask, starting with 21% oxygen",
          "Free flow 100% oxygen by mask",
          "Intubate and give epinephrine",
          "Naloxone IM",
        ],
        correct: 1,
        explanation:
          "An apneic newborn with HR under 100 needs positive pressure ventilation within the first minute. For a baby of 35 weeks or more, start with 21% oxygen. Compressions are only started if HR stays under 60 despite 30 seconds of effective ventilation.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "nrp",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "The baby responds to ventilation. The mother now has brisk vaginal bleeding of about 800 mL. Her uterus is soft.",
        prompt: "List THREE interventions for the mother.",
        accept: [
          { id: "massage", text: "Uterine massage", match: ["massage", "fundal"] },
          { id: "oxytocin", text: "Oxytocin", match: ["oxytocin", "pitocin"] },
          { id: "iv", text: "Two large bore IVs, fluids and blood", match: ["large bore", "iv access", "fluid", "blood", "transfusion"] },
          { id: "txa", text: "Tranexamic acid 1 g IV", match: ["tranexamic", "txa"] },
          { id: "bimanual", text: "Bimanual compression", match: ["bimanual", "compression"] },
          { id: "causes", text: "Check for retained placenta or tears", match: ["placenta", "tear", "laceration", "retained"] },
          { id: "bladder", text: "Empty the bladder", match: ["bladder", "catheter", "foley"] },
          { id: "second", text: "Second line uterotonic such as carboprost or ergonovine", match: ["carboprost", "hemabate", "ergonovine", "misoprostol", "carbetocin"] },
        ],
        explanation:
          "Uterine atony is the most common cause of postpartum hemorrhage. Treat with massage, oxytocin and tranexamic acid, and resuscitate with fluids and blood. Look for the other causes, tissue, trauma and thrombin.",
        keyFeature: { topic: "multiple-patients", n: 2 },
        source: "sogc-pph",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "The ECG of the man in bed 3 shows anterior ST elevation.",
        prompt: "You are still at the mother's bedside. List TWO actions to get him treated without delay.",
        accept: [
          { id: "asa", text: "Verbal order for ASA", match: ["asa", "aspirin", "acetylsalicylic"] },
          { id: "criticall", text: "Call CritiCall or the PCI centre to arrange reperfusion", match: ["criticall", "pci", "cardiology", "cardiologist", "cath lab"] },
          { id: "lytic", text: "Fibrinolysis if PCI cannot happen within 120 minutes", match: ["tenecteplase", "tnk", "lytic", "thrombolysis", "thrombolytic", "fibrinolysis"] },
          { id: "colleague", text: "Hand him to the arriving colleague", match: ["colleague", "backup", "back up", "second physician", "another physician"] },
          { id: "monitor", text: "Monitor with defibrillator pads on", match: ["monitor", "pad", "defibrillator"] },
        ],
        explanation:
          "A STEMI cannot wait until the other emergencies settle. Verbal orders and a call to arrange reperfusion move his care forward. Handing him to a colleague as soon as one arrives lets each patient have a physician.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "criticall",
      },
    ],
    sources: [S.criticall, S.nrp, S.sogcPph],
    ...META,
  },
  {
    id: "multiple-patients-12",
    topic: "multiple-patients",
    alsoTopics: ["cqi", "arrhythmia"],
    title: "A result that fell through the cracks",
    stem:
      "You work in an Ontario emergency department. At 10:00 you assess a 76 year old man with acute kidney injury who was handed over to you at 07:00. The night physician's note says potassium pending. The result, 7.1 mmol/L, was reported at 06:40 and was not mentioned at handover. He now feels weak. His ECG shows wide QRS complexes and a heart rate of 42.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate treatments. Include doses where relevant.",
        accept: [
          { id: "calcium", text: "Calcium gluconate 3 g IV or calcium chloride 1 g IV", match: ["calcium gluconate", "calcium chloride", "calcium"] },
          { id: "insulin", text: "Regular insulin 10 units IV with dextrose", match: ["insulin"] },
          { id: "salb", text: "Nebulized salbutamol 10 to 20 mg", match: ["salbutamol", "ventolin", "albuterol", "beta agonist"] },
          { id: "dialysis", text: "Nephrology for urgent dialysis", match: ["dialysis", "nephrology", "nephrologist"] },
          { id: "monitor", text: "Continuous cardiac monitoring with pacing pads", match: ["monitor", "pacing", "pad"] },
          { id: "bicarb", text: "Sodium bicarbonate if acidotic", match: ["bicarbonate", "bicarb"] },
        ],
        unacceptable: [
          { text: "Sodium polystyrene sulfonate as the main treatment", match: ["kayexalate alone", "polystyrene alone"] },
        ],
        explanation:
          "Hyperkalemia with a wide QRS and bradycardia is a cardiac emergency. Calcium stabilizes the membrane within minutes. Insulin with dextrose and salbutamol shift potassium into cells, and dialysis removes it. Resin binders act too slowly for this situation.",
        keyFeature: { topic: "arrhythmia", n: 6 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "He responds to treatment and is admitted to the ICU for dialysis.",
        prompt: "List THREE elements of your disclosure conversation with the patient and his daughter.",
        accept: [
          { id: "facts", text: "Explain the facts of what happened in plain language", match: ["fact", "what happened", "explain"] },
          { id: "apology", text: "Express regret and apologize", match: ["apology", "apologize", "apologise", "sorry", "regret"] },
          { id: "done", text: "What is being done to treat him", match: ["treatment", "being done", "care plan", "management"] },
          { id: "prevent", text: "Steps being taken to prevent a recurrence", match: ["prevent", "recurrence", "review", "investigation"] },
          { id: "questions", text: "Invite questions and offer follow up", match: ["question", "follow up", "contact"] },
          { id: "document", text: "Document the disclosure", match: ["document", "documentation", "documented"] },
          { id: "timely", text: "Disclose promptly", match: ["prompt", "promptly", "timely", "soon"] },
        ],
        unacceptable: [
          { text: "Avoid mentioning the delay", match: ["not mention", "avoid mentioning", "no need to disclose"] },
        ],
        explanation:
          "Canadian disclosure guidance calls for prompt, honest disclosure of harmful incidents. Explain the facts known so far, express regret, describe the care now being given and the steps to prevent recurrence. An apology is appropriate. Under Ontario's Apology Act, 2009, an apology is not an admission of liability and cannot be used as evidence of fault.",
        keyFeature: { topic: "cqi", n: 2 },
        source: "cpsi-disclosure",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE contributing factors the incident review should explore.",
        accept: [
          { id: "tool", text: "Lack of a structured handover tool that includes pending results", match: ["structured", "handover tool", "sbar", "ipass", "i pass", "no structured", "no handover tool"] },
          { id: "callback", text: "Critical result call went to a physician about to leave", match: ["critical result", "callback", "call back", "lab call", "critical value"] },
          { id: "workload", text: "Workload, interruptions or fatigue at shift change", match: ["workload", "interruption", "fatigue", "busy", "volume"] },
          { id: "ehr", text: "Lack of an electronic flag for unreviewed results", match: ["electronic", "ehr", "flag", "alert", "no electronic", "no flag", "no alert"] },
          { id: "nursing", text: "Nursing handover and whether nurses knew of the result", match: ["nurse", "nursing"] },
          { id: "time", text: "Timing of the result close to shift change", match: ["timing", "shift change", "06 40"] },
        ],
        explanation:
          "Incident analysis looks for system factors rather than blaming one person. Handover without a structured tool, critical result callbacks at shift change and the lack of electronic flags all allow results to be lost.",
        keyFeature: { topic: "cqi", n: 1 },
        source: "cpsi-ciaf",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO system changes that would reduce the chance of this happening again.",
        accept: [
          { id: "tool", text: "A structured handover tool that lists pending results", match: ["structured", "handover tool", "sbar", "ipass", "i pass", "pending result"] },
          { id: "critical", text: "A critical result policy with read back to the responsible physician", match: ["critical result", "read back", "readback", "critical value"] },
          { id: "ehr", text: "An electronic list or alert for unreviewed results", match: ["electronic", "ehr", "alert", "flag"] },
          { id: "report", text: "Report the incident through the safety reporting system", match: ["report", "incident report", "safety reporting"] },
          { id: "audit", text: "Audit handovers and remeasure after the change", match: ["audit", "remeasure", "measure"] },
        ],
        explanation:
          "Durable fixes are system fixes. A handover tool that forces review of pending results, clear critical result routing and electronic flags work better than reminders to be careful. Measure again after the change to see if it worked.",
        keyFeature: { topic: "cqi", n: 5 },
        source: "ipass",
      },
    ],
    sources: [S.tintinalli, S.cpsiDisclosure, S.cpsiFramework, S.ipass],
    ...META,
  },
  {
    id: "multiple-patients-13",
    topic: "multiple-patients",
    alsoTopics: ["multiple-trauma"],
    title: "Shooting at a shopping centre",
    stem:
      "At 15:30 police and EMS report a shooting at a shopping centre 8 minutes from your hospital. You work in a community hospital with general surgery and two operating rooms. The nearest trauma centre is 40 minutes away by land. EMS will bring you 4 patients with gunshot wounds. Others are going to the trauma centre.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE hospital level actions now.",
        accept: [
          { id: "code", text: "Activate Code Orange", match: ["code orange", "disaster plan", "mass casualty plan"] },
          { id: "security", text: "Security lockdown of the department", match: ["security", "lockdown", "lock down", "police"] },
          { id: "blood", text: "Tell the blood bank to prepare for several massive transfusions", match: ["blood bank", "massive transfusion", "mtp", "blood"] },
          { id: "or", text: "Hold both operating rooms and call in surgeons and anaesthesia", match: ["operating room", "surgeon", "anaesthesia", "anesthesia", "hold or"] },
          { id: "staff", text: "Call in extra staff", match: ["call in", "extra staff", "additional staff", "call back"] },
          { id: "clear", text: "Clear resuscitation bays", match: ["clear", "resuscitation bay", "resus bay"] },
          { id: "trauma", text: "Contact the trauma centre for coordination and transfers", match: ["trauma centre", "trauma center", "criticall"] },
        ],
        explanation:
          "A known influx of penetrating trauma needs the disaster plan, the OR and the blood bank ready before arrival. Security matters because violence can follow patients to hospital. Early contact with the trauma centre coordinates who goes where.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "oha-codes",
      },
      {
        id: "q2",
        kind: "single",
        update: "The four patients arrive.\nA. Gunshot to the abdomen. HR 138, BP 74/40. FAST shows free fluid. Transient response to 2 units of blood.\nB. Gunshot to the thigh with a tourniquet. Bleeding controlled. HR 100, BP 122/80.\nC. Gunshot to the head. GCS 4 with fixed dilated pupils.\nD. Gunshot to the chest. Chest tube drained 400 mL, now 50 mL per hour. BP 112/70.",
        prompt: "Which patient should go to the operating room first? Select one.",
        options: ["Patient A", "Patient B", "Patient C", "Patient D"],
        correct: 0,
        explanation:
          "Patient A has ongoing intra-abdominal hemorrhage with shock and needs damage control laparotomy now. Patient D's drainage is below thresholds for urgent thoracotomy. Patient B's bleeding is controlled. Patient C has a devastating, likely non survivable injury.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE principles for blood product use while resuscitating these patients.",
        accept: [
          { id: "ratio", text: "Balanced transfusion with plasma, platelets and red cells near 1 to 1 to 1", match: ["balanced", "ratio", "plasma"] },
          { id: "txa", text: "Tranexamic acid 1 g IV within 3 hours of injury", match: ["tranexamic", "txa"] },
          { id: "oneg", text: "Save O negative for females of childbearing age and use O positive for males", match: ["o negative", "o positive", "o neg", "o pos"] },
          { id: "permissive", text: "Permissive hypotension until hemorrhage is controlled", match: ["permissive", "sbp 80", "sbp 90", "systolic 80", "systolic 90", "map 65"] },
          { id: "calcium", text: "Replace calcium", match: ["calcium"] },
          { id: "warm", text: "Warm all products", match: ["warm", "warmer", "hypothermia"] },
          { id: "bank", text: "Talk with the blood bank about stock and supply", match: ["blood bank", "inventory", "stock", "supply"] },
          { id: "limit", text: "Limit crystalloid", match: ["limit crystalloid", "avoid crystalloid", "minimize crystalloid"] },
        ],
        explanation:
          "Several simultaneous massive transfusions can drain a small blood bank. Keep the blood bank informed, reserve O negative for those who need it and give tranexamic acid early. Balanced ratios, permissive hypotension, warming and calcium reduce coagulopathy.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "As the emergency physician leading the response, list THREE roles you assign.",
        accept: [
          { id: "triage", text: "Triage officer at the ambulance entrance", match: ["triage officer", "triage lead", "triage"] },
          { id: "leader", text: "A team leader for each resuscitation bay", match: ["team leader", "bay leader", "leader for each"] },
          { id: "tracker", text: "A nurse to track patients, locations and identifiers", match: ["track", "tracking", "tracker", "board"] },
          { id: "scribe", text: "A scribe or recorder", match: ["scribe", "recorder", "documentation"] },
          { id: "liaison", text: "A communications liaison with incident command", match: ["liaison", "incident command", "communication"] },
          { id: "family", text: "Social work for families", match: ["social work", "family"] },
          { id: "runner", text: "A runner for blood and supplies", match: ["runner"] },
        ],
        explanation:
          "Clear roles keep several resuscitations running in parallel. An experienced triage officer controls flow at the door. Tracking and communication roles prevent lost patients and keep incident command informed.",
        keyFeature: { topic: "multiple-patients", n: 3 },
        source: "rosen",
      },
    ],
    sources: [S.ohaCodes, S.atls, S.rosen],
    ...META,
  },
  {
    id: "multiple-patients-14",
    topic: "multiple-patients",
    alsoTopics: ["ems"],
    title: "Ambulances waiting at the door",
    stem:
      "It is 16:00 in an urban emergency department. Every monitored bed is full except one resuscitation bay. Four ambulances arrive within 5 minutes.\nA. A 70 year old with COPD. RR 26, SpO2 91% on 2 L, speaking in full sentences.\nB. A 55 year old with hematemesis. HR 132, BP 74/40. Cool, clammy and confused.\nC. A 30 year old intoxicated man with a scalp laceration. GCS 14. Normal vital signs.\nD. An 84 year old with a suspected hip fracture. Normal vital signs. Pain controlled with fentanyl.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which patient should go to the resuscitation bay? Select one.",
        options: ["Patient A", "Patient B", "Patient C", "Patient D"],
        correct: 1,
        explanation:
          "Patient B is in shock from an upper GI bleed, which is CTAS 1. Patient A has moderate distress and can start treatment in another space with close monitoring. The others are stable.",
        keyFeature: { topic: "multiple-patients", n: 1 },
        source: "ctas",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE pieces of information you want from patient B's paramedics that only they can give.",
        accept: [
          { id: "scene", text: "Scene findings, such as the amount of blood and pill bottles", match: ["scene", "amount of blood", "pill bottle", "blood at home"] },
          { id: "tx", text: "Treatments given and the response", match: ["treatment", "given", "response", "fluid"] },
          { id: "trend", text: "Vital sign trend and changes en route", match: ["trend", "en route", "change", "initial vital"] },
          { id: "onset", text: "Time of onset", match: ["onset", "time", "when"] },
          { id: "meds", text: "Medications found, such as anticoagulants", match: ["medication", "anticoagulant", "med"] },
          { id: "family", text: "Family contact and advance directive documents", match: ["family", "contact", "advance directive", "dnr"] },
          { id: "etoh", text: "Evidence of alcohol use or liver disease at home", match: ["alcohol", "liver"] },
        ],
        explanation:
          "Paramedics saw the scene and the patient's first vital signs. How much blood was lost, what medications are in the home, what was given and how he responded are often not recorded anywhere else. Ask before the crew leaves.",
        keyFeature: { topic: "ems", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE actions to care for the other three patients safely while no beds are available.",
        accept: [
          { id: "accept", text: "Accept transfer of care promptly to a nurse in an offload area", match: ["offload", "transfer of care", "accept"] },
          { id: "assess", text: "Physician assessment and orders while patients are on EMS stretchers", match: ["assess", "order", "stretcher", "hallway"] },
          { id: "treat", text: "Start bronchodilators, steroids and monitoring for patient A in a hallway space", match: ["salbutamol", "bronchodilator", "steroid", "prednisone", "ipratropium", "bipap", "treat a"] },
          { id: "reassess", text: "Reassess all waiting patients at CTAS intervals", match: ["reassess", "reassessment", "repeat vital"] },
          { id: "escalate", text: "Escalate to the charge nurse and administrator on call", match: ["charge nurse", "administrator", "escalation", "escalate"] },
          { id: "beds", text: "Move admitted patients out to free monitored beds", match: ["admitted", "free bed", "move patient"] },
          { id: "cscan", text: "Order CT head for patient C if his level of consciousness falls", match: ["ct head", "ct", "gcs"] },
        ],
        explanation:
          "Ambulance offload delay harms both the waiting patients and the community, which is left without ambulances. Accepting care early, starting assessment on the stretcher and escalating to hospital leadership keep everyone safer.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "caep-crowding",
      },
    ],
    sources: [S.ctas, S.rosen, S.caepCrowding],
    ...META,
  },
  {
    id: "multiple-patients-15",
    topic: "multiple-patients",
    alsoTopics: ["ems"],
    title: "Winter storm on the highway",
    stem:
      "You are the emergency physician at a regional hospital during a snowstorm. At 08:10 an EMS superintendent calls. There has been a pileup of about 30 vehicles on the highway 25 minutes from your hospital. There are about 25 casualties, some trapped. Two smaller hospitals and a lead trauma centre 70 minutes away are also in the region. Air ambulance is grounded by weather.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE pieces of information you want from the EMS superintendent.",
        accept: [
          { id: "number", text: "Number of patients and triage categories", match: ["number", "how many", "triage category", "red", "severity"] },
          { id: "injuries", text: "Types of injuries, such as burns or entrapment", match: ["type of injury", "injury type", "injurie", "burn", "entrapment", "trapped"] },
          { id: "eta", text: "Expected arrival times", match: ["eta", "arrival", "arrive"] },
          { id: "hazmat", text: "Hazardous materials or contamination", match: ["hazmat", "hazardous", "chemical", "contamination", "fuel"] },
          { id: "special", text: "Children, pregnant patients or other special needs", match: ["children", "pediatric", "paediatric", "pregnant"] },
          { id: "resources", text: "Available ambulances and other hospitals already notified", match: ["ambulance", "resource", "other hospital", "unit"] },
          { id: "contact", text: "A direct callback number and who is in command at the scene", match: ["callback", "call back", "command", "contact number"] },
        ],
        explanation:
          "A structured pre-arrival report lets you size your response. Numbers, severity, injury types, contamination and timing drive how many staff and which spaces you need. A reliable callback line keeps information flowing.",
        keyFeature: { topic: "ems", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "The superintendent asks for advice on patient distribution. List THREE directions you give.",
        accept: [
          { id: "spread", text: "Distribute patients among all hospitals rather than sending everyone to the nearest", match: ["distribute", "spread", "share", "all hospital", "not all to", "other hospital"] },
          { id: "tc", text: "Send stable patients with major trauma to the lead trauma centre by land", match: ["trauma centre", "trauma center"] },
          { id: "nearest", text: "Bring unstable patients with airway or hemorrhage problems to the nearest hospital for stabilization", match: ["nearest", "closest", "unstable", "stabilization", "stabilize"] },
          { id: "walking", text: "Send walking wounded to the smaller hospitals", match: ["walking wounded", "green", "minor", "smaller hospital"] },
          { id: "triage", text: "Use a standard field triage system such as START", match: ["start triage", "salt triage", "field triage", "triage system", "start system", "start algorithm"] },
          { id: "casualty", text: "Set up a casualty collection point", match: ["casualty collection", "collection point", "staging"] },
        ],
        explanation:
          "Sending every patient to the nearest hospital overwhelms it while others sit idle. Unstable patients go to the nearest hospital that can stabilize them. Stable patients with major trauma can go straight to the trauma centre, and walking wounded to smaller sites.",
        keyFeature: { topic: "ems", n: 4 },
        source: "salt",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE steps to organize your department for the arriving patients.",
        accept: [
          { id: "code", text: "Activate Code Orange", match: ["code orange", "disaster plan", "mass casualty plan"] },
          { id: "zones", text: "Set up red, yellow and green treatment zones", match: ["zone", "area", "red", "yellow", "green"] },
          { id: "leads", text: "Assign a physician and nurse lead to each zone", match: ["lead", "leader", "assign"] },
          { id: "reg", text: "Use disaster registration numbers and tracking", match: ["registration", "tracking", "tag", "identifier"] },
          { id: "triage", text: "Triage point at the ambulance entrance", match: ["triage"] },
          { id: "staff", text: "Call in extra staff, allowing for travel delays in the storm", match: ["call in", "extra staff", "additional staff", "call back"] },
          { id: "clear", text: "Clear the department of admitted and stable patients", match: ["clear", "discharge", "move admitted"] },
          { id: "comm", text: "Communicate with hospital incident command", match: ["incident command", "command"] },
        ],
        explanation:
          "Inside the department, the plan works through zones, named leaders, a single triage point and a tracking system. Disaster registration numbers let care start before identities are confirmed. Staffing may be slow in a storm, so call early.",
        keyFeature: { topic: "multiple-patients", n: 4 },
        source: "oha-codes",
      },
    ],
    sources: [S.rosen, S.salt, S.ohaCodes],
    ...META,
  },
];
