// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const meta = { reviewed: true, author: "Draft for review by Arjan Dhoot, MD", version: 1 };

const SRC: Record<string, Source> = {
  svsAaa: { id: "svs-aaa", citation: "Society for Vascular Surgery. Practice guidelines on the care of patients with an abdominal aortic aneurysm. 2018." },
  esvsMes: { id: "esvs-mesenteric", citation: "European Society for Vascular Surgery. Clinical practice guidelines on the management of diseases of the mesenteric arteries and veins." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli's Emergency Medicine: A Comprehensive Study Guide. Acute abdominal pain chapter." },
  rosen: { id: "rosen", citation: "Rosen's Emergency Medicine: Concepts and Clinical Practice." },
  acrRlq: { id: "acr-rlq", citation: "American College of Radiology. ACR Appropriateness Criteria. Right lower quadrant pain." },
  wsesAppy: { id: "wses-appy", citation: "World Society of Emergency Surgery. Jerusalem guidelines for the diagnosis and treatment of acute appendicitis." },
  cpsCap: { id: "cps-cap", citation: "Canadian Paediatric Society. Uncomplicated pneumonia in healthy Canadian children and youth. Practice points for management." },
  imageGently: { id: "image-gently", citation: "Image Gently Alliance. Radiation safety in paediatric imaging." },
  ccsStemi: { id: "ccs-stemi", citation: "Canadian Cardiovascular Society and Canadian Association of Interventional Cardiology. Focused update of the guidelines for the management of ST elevation myocardial infarction." },
  dcDka: { id: "dc-dka", citation: "Diabetes Canada Clinical Practice Guidelines. Hyperglycemic emergencies in adults." },
  idsaAsb: { id: "idsa-asb", citation: "Infectious Diseases Society of America. Clinical practice guideline for the management of asymptomatic bacteriuria. 2019." },
  sisIai: { id: "sis-iai", citation: "Surgical Infection Society and Infectious Diseases Society of America. Guidelines for the diagnosis and management of complicated intra-abdominal infection." },
  sogcEctopic: { id: "sogc-ectopic", citation: "Society of Obstetricians and Gynaecologists of Canada. Clinical practice guideline on the diagnosis and management of ectopic pregnancy." },
  sogcRh: { id: "sogc-rh", citation: "Society of Obstetricians and Gynaecologists of Canada. Guideline No. 448. Prevention of Rh D alloimmunization. 2024." },
  twist: { id: "twist", citation: "Barbosa JA and colleagues. Development and initial validation of a scoring system to diagnose testicular torsion in children. J Urol. 2013." },
  acog723: { id: "acog-723", citation: "American College of Obstetricians and Gynecologists. Committee Opinion No. 723. Guidelines for diagnostic imaging during pregnancy and lactation." },
  caepCw: { id: "caep-cw", citation: "Choosing Wisely Canada. Emergency medicine recommendations from the Canadian Association of Emergency Physicians." },
  eauStone: { id: "eau-stone", citation: "European Association of Urology. Guidelines on urolithiasis." },
  acgPanc: { id: "acg-panc", citation: "American College of Gastroenterology. Guideline on the management of acute pancreatitis." },
  wsesPud: { id: "wses-pud", citation: "World Society of Emergency Surgery. Guidelines on perforated and bleeding peptic ulcer." },
  wsesSbo: { id: "wses-sbo", citation: "World Society of Emergency Surgery. Bologna guidelines for the diagnosis and management of adhesive small bowel obstruction." },
};

export const ABDOMINAL_PAIN: Samp[] = [
  {
    id: "abdominal-pain-01",
    topic: "abdominal-pain",
    alsoTopics: ["shock"],
    title: "Older man with sudden flank pain",
    stem:
      "A 74-year-old man arrives at 02:00 with sudden severe left flank pain radiating to the left groin. It began 90 minutes ago. He vomited once. He thinks he is passing a kidney stone, although he has never had one. He has hypertension and smokes one pack per day.\n\nVital signs: HR 112/min, BP 96/58 mmHg, RR 22/min, SpO2 96% on room air, temperature 36.4°C. Weight 88 kg.\n\nHe is pale and diaphoretic. The abdomen is mildly tender in the left lower quadrant. Urinalysis shows trace blood.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE life-threatening diagnoses you must consider before accepting renal colic.",
        required: 3,
        accept: [
          { id: "aaa", text: "Ruptured abdominal aortic aneurysm", match: ["aaa", "aortic aneurysm", "aneurysm", "abdominal aortic"] },
          { id: "mes", text: "Mesenteric ischemia", match: ["mesenteric", "ischemic bowel", "bowel ischemia"] },
          { id: "dis", text: "Aortic dissection", match: ["dissection"] },
          { id: "mi", text: "Acute myocardial infarction", match: ["myocardial infarction", "mi", "acs", "acute coronary", "stemi"] },
          { id: "perf", text: "Perforated viscus", match: ["perforated", "perforation", "free air"] },
          { id: "rp", text: "Retroperitoneal hemorrhage", match: ["retroperitoneal"] },
          { id: "inf", text: "Infected obstructing ureteric stone with urosepsis", match: ["infected", "urosepsis", "pyelonephritis", "obstructed kidney"] },
          { id: "volv", text: "Bowel obstruction or volvulus", match: ["volvulus", "obstruction", "incarcerated hernia"] },
        ],
        explanation:
          "New flank pain in an older smoker with hypotension is a ruptured AAA until proven otherwise. AAA is the classic atypical presentation of flank pain and hematuria mistaken for renal colic. Mesenteric ischemia, dissection and MI must also be kept on the list.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "svs-aaa",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate next investigation? Select one.",
        options: [
          "Point-of-care ultrasound of the abdominal aorta",
          "Non-contrast CT of the kidneys, ureters and bladder",
          "Plain abdominal radiograph",
          "Formal renal ultrasound in the morning",
          "Urine culture",
        ],
        correct: 0,
        explanation:
          "Bedside ultrasound identifies an aneurysm within minutes and can be done during resuscitation. A hypotensive patient should not leave the department for CT. Ultrasound does not reliably show rupture, but an aneurysm plus shock is enough to act.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        update: "Bedside ultrasound shows a 7.2 cm infrarenal aorta. BP is now 84/50 mmHg. He is alert and oriented.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "surg", text: "Call vascular surgery now for the operating room", match: ["vascular surgery", "vascular surgeon", "surgeon", "operating room", "surgery"] },
          { id: "tx", text: "Transfuse blood or activate the massive transfusion protocol", match: ["transfuse", "transfusion", "massive transfusion", "mtp", "prbc", "packed red", "uncrossmatched", "o negative", "o positive", "group o", "blood product"] },
          { id: "perm", text: "Permissive hypotension with a systolic target of 70 to 90 mmHg", match: ["permissive", "hypotensive resuscitation", "target systolic", "sbp 70", "sbp 80", "sbp 90", "limit crystalloid", "limit fluid", "avoid aggressive fluid", "avoid large volume", "avoid overresuscitation", "minimize crystalloid"] },
          { id: "iv", text: "Two large bore IV lines", match: ["large bore", "two iv", "2 iv"] },
          { id: "xm", text: "Crossmatch and send preoperative bloods", match: ["crossmatch", "cross match", "type and cross", "group and screen", "type and screen"] },
          { id: "trans", text: "Arrange immediate transfer to a vascular centre if none on site", match: ["transfer", "vascular centre", "vascular center"] },
          { id: "anes", text: "Notify anesthesia", match: ["anesthesia", "anaesthesia", "anesthetist", "anaesthetist"] },
        ],
        unacceptable: [
          { text: "Send for CT before calling the surgeon", match: ["ct first", "ct before", "cta first", "cta before", "ct scan to confirm"], dangerous: true },
        ],
        explanation:
          "An aneurysm with hypotension needs the operating room, not more imaging. Mobilize surgery, blood and access in parallel. Hypotensive resuscitation avoids diluting clotting factors and raising pressure against a contained rupture. CT is reserved for the stable patient.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "svs-aaa",
      },
      {
        id: "q4",
        kind: "menu",
        update: "BP is 78/46 mmHg after 500 mL of normal saline. He remains alert. The vascular surgeon is 20 minutes away.",
        prompt: "Which TWO of the following are most appropriate now? Select TWO.",
        options: [
          "Transfuse uncrossmatched group O red cells",
          "Target a systolic BP of 70 to 90 mmHg while mentation is preserved",
          "Give another 2 L of normal saline wide open",
          "Start norepinephrine to a MAP of 80 mmHg",
          "Give 1 L of 5% albumin",
          "Target a systolic BP above 120 mmHg",
          "Insert a nasogastric tube",
          "Give tranexamic acid as the main therapy",
        ],
        select: 2,
        correct: [0, 1],
        explanation:
          "Blood is the resuscitation fluid for hemorrhagic shock. Uncrossmatched group O Rh positive red cells are acceptable for a man. Large crystalloid volumes cause dilutional coagulopathy and may worsen bleeding. A lower pressure target is accepted while the patient stays alert and until the aorta is controlled.",
        keyFeature: { topic: "shock", n: 3 },
        source: "svs-aaa",
      },
    ],
    sources: [SRC.svsAaa, SRC.tintinalli],
    ...meta,
  },
  {
    id: "abdominal-pain-02",
    topic: "abdominal-pain",
    title: "Older woman with severe periumbilical pain",
    stem:
      "A 79-year-old woman presents with severe periumbilical pain that started suddenly 4 hours ago. She vomited twice and had one loose stool. She has atrial fibrillation. She stopped apixaban 2 weeks ago after a nosebleed.\n\nVital signs: HR 118/min irregular, BP 142/84 mmHg, RR 22/min, SpO2 95% on room air, temperature 36.9°C. Weight 61 kg.\n\nShe is writhing and asking for help. The abdomen is soft with mild diffuse tenderness and no guarding. Lactate is 1.8 mmol/L. WBC is 16.2 x 10^9/L.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE serious diagnoses that must be excluded.",
        required: 3,
        accept: [
          { id: "mes", text: "Acute mesenteric ischemia", match: ["mesenteric", "ischemic bowel", "bowel ischemia"] },
          { id: "aaa", text: "Abdominal aortic aneurysm", match: ["aaa", "aneurysm"] },
          { id: "panc", text: "Acute pancreatitis", match: ["pancreatitis"] },
          { id: "perf", text: "Perforated viscus", match: ["perforated", "perforation", "free air"] },
          { id: "obs", text: "Bowel obstruction or volvulus", match: ["obstruction", "volvulus", "sbo"] },
          { id: "dis", text: "Aortic dissection", match: ["dissection"] },
          { id: "mi", text: "Myocardial infarction", match: ["myocardial", "mi", "acs", "acute coronary"] },
          { id: "hern", text: "Incarcerated hernia", match: ["hernia"] },
        ],
        unacceptable: [{ text: "Gastroenteritis", match: ["gastroenteritis"] }],
        explanation:
          "Pain out of proportion to a soft abdomen is the classic warning of mesenteric ischemia. Atrial fibrillation off anticoagulation makes embolism likely. Pancreatitis, AAA and perforation can also present this way. Gastroenteritis is a diagnosis of exclusion in an older adult.",
        keyFeature: { topic: "abdominal-pain", n: 2 },
        source: "esvs-mesenteric",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate imaging test? Select one.",
        options: [
          "CT angiography of the abdomen and pelvis",
          "Abdominal ultrasound",
          "Upright chest and abdominal radiographs",
          "Non-contrast CT of the abdomen",
          "MRI of the abdomen",
          "Colonoscopy",
        ],
        correct: 0,
        explanation:
          "CT angiography is the test of choice for suspected acute mesenteric ischemia. It shows the vessel occlusion and the bowel. Plain films are often normal until infarction. Concern about creatinine should not delay CTA when ischemia is suspected.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "esvs-mesenteric",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "The resident suggests ischemia is unlikely because the lactate is normal. Which statement is most accurate? Select one.",
        options: [
          "A normal lactate does not exclude early mesenteric ischemia",
          "A lactate under 2 mmol/L rules out bowel ischemia",
          "Lactate is only useful when the WBC is normal",
          "A normal lactate means CT can wait until morning",
          "An elevated lactate is specific for bowel ischemia",
        ],
        correct: 0,
        explanation:
          "Lactate is insensitive early in mesenteric ischemia because the liver clears lactate from the portal circulation. It rises late, often after infarction. It is also nonspecific. Decisions rest on clinical suspicion and CTA.",
        keyFeature: { topic: "abdominal-pain", n: 6 },
        source: "esvs-mesenteric",
      },
      {
        id: "q4",
        kind: "short",
        update: "CT angiography shows an embolus occluding the proximal superior mesenteric artery. There is no free air.",
        prompt: "List THREE management steps now.",
        required: 3,
        accept: [
          { id: "surg", text: "Emergent vascular and general surgery consultation for revascularization", match: ["vascular", "surgery", "surgeon", "revascularization", "embolectomy", "interventional radiology"] },
          { id: "hep", text: "Unfractionated heparin bolus and infusion", match: ["heparin", "anticoagulation", "anticoagulate"] },
          { id: "abx", text: "Broad spectrum IV antibiotics", match: ["antibiotic", "piperacillin", "pip tazo", "ceftriaxone", "metronidazole", "meropenem"] },
          { id: "fluid", text: "IV fluid resuscitation", match: ["fluid", "crystalloid", "ringer", "saline"] },
          { id: "analg", text: "Opioid analgesia", match: ["analgesia", "opioid", "morphine", "hydromorphone", "fentanyl"] },
          { id: "npo", text: "NPO and nasogastric decompression", match: ["npo", "nothing by mouth", "nasogastric", "ng tube"] },
        ],
        unacceptable: [{ text: "Restart oral apixaban", match: ["apixaban", "doac"] }],
        explanation:
          "Arterial embolic mesenteric ischemia needs urgent revascularization and assessment of bowel viability. Start IV heparin early unless contraindicated. Give antibiotics because of bacterial translocation, and resuscitate. An oral anticoagulant has no role in the acute phase.",
        keyFeature: { topic: "abdominal-pain", n: 2 },
        source: "esvs-mesenteric",
      },
    ],
    sources: [SRC.esvsMes],
    ...meta,
  },
  {
    id: "abdominal-pain-03",
    topic: "abdominal-pain",
    title: "Young woman with right lower quadrant pain",
    stem:
      "A 23-year-old woman has 20 hours of abdominal pain. It began around the umbilicus and has moved to the right lower quadrant. She has anorexia and nausea. Her last menstrual period was 5 weeks ago. She is sexually active and uses condoms inconsistently.\n\nVital signs: HR 96/min, BP 118/72 mmHg, RR 16/min, SpO2 99% on room air, temperature 37.2°C. Weight 60 kg.\n\nShe has right lower quadrant tenderness with voluntary guarding. There is no costovertebral angle tenderness.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "Appendicitis is your leading concern. List THREE alternative diagnoses in her that would change your first investigations.",
        required: 3,
        accept: [
          { id: "ect", text: "Ectopic pregnancy", match: ["ectopic"] },
          { id: "tor", text: "Ovarian torsion", match: ["torsion"] },
          { id: "cyst", text: "Ruptured or hemorrhagic ovarian cyst", match: ["ovarian cyst", "cyst"] },
          { id: "pid", text: "Pelvic inflammatory disease or tubo-ovarian abscess", match: ["pid", "pelvic inflammatory", "tubo ovarian", "tuboovarian", "toa"] },
          { id: "stone", text: "Ureteric stone", match: ["stone", "renal colic", "ureteric", "nephrolithiasis", "urolithiasis"] },
          { id: "pyelo", text: "Pyelonephritis", match: ["pyelonephritis"] },
          { id: "crohn", text: "Crohn disease or terminal ileitis", match: ["crohn", "ileitis"] },
          { id: "aden", text: "Mesenteric adenitis", match: ["adenitis"] },
          { id: "endo", text: "Endometriosis", match: ["endometriosis", "endometrioma"] },
        ],
        explanation:
          "Location, migration and sex shape the differential. In a woman of reproductive age, ectopic pregnancy, torsion and PID must be considered alongside appendicitis. A pregnancy test comes first.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "acr-rlq",
      },
      {
        id: "q2",
        kind: "single",
        update: "Serum beta hCG is negative. WBC is 9.4 x 10^9/L.",
        prompt: "The resident says appendicitis is unlikely because she is afebrile with a normal white count. Which statement is most accurate? Select one.",
        options: [
          "A normal temperature and WBC do not rule out appendicitis",
          "Appendicitis is excluded when both are normal",
          "Only fever above 38.5°C is a reliable sign of appendicitis",
          "A normal CRP in 6 hours would exclude appendicitis",
          "She can be discharged if the pain improves with analgesia",
        ],
        correct: 0,
        explanation:
          "Fever and leukocytosis are each absent in a large share of confirmed appendicitis, especially early. No single finding is sensitive enough to exclude it. Migration of pain and localized peritonism carry more weight. Analgesia does not mask the diagnosis.",
        keyFeature: { topic: "abdominal-pain", n: 6 },
        source: "wses-appy",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "Name the most appropriate first imaging test for her.",
        required: 1,
        accept: [
          { id: "us", text: "Ultrasound of the right lower quadrant and pelvis", match: ["ultrasound", "us", "sonography", "sonogram", "transvaginal"] },
        ],
        unacceptable: [{ text: "CT abdomen and pelvis as the first test", match: ["ct", "computed tomography"] }],
        explanation:
          "In a young woman, ultrasound avoids ionizing radiation and also assesses the ovaries and adnexa. CT or MRI is used when ultrasound is nondiagnostic and doubt remains. Lifetime cancer risk from CT is highest in the young.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "acr-rlq",
      },
      {
        id: "q4",
        kind: "short",
        update: "Urinalysis shows 10 to 20 WBC per high power field, no nitrites and no bacteria. She has no dysuria. The resident proposes treating a urinary tract infection.",
        prompt: "List TWO reasons this urinalysis should not change your working diagnosis.",
        required: 2,
        accept: [
          { id: "adj", text: "An inflamed appendix next to the ureter or bladder causes sterile pyuria", match: ["adjacent", "ureter", "bladder", "next to", "sterile pyuria", "inflamed appendix", "irritation"] },
          { id: "sym", text: "She has no urinary symptoms", match: ["no urinary symptom", "no dysuria", "no frequency", "absence dysuria", "without dysuria", "without urinary", "lack of urinary", "absent urinary", "no symptom"] },
          { id: "nit", text: "No nitrites or bacteria are seen", match: ["nitrite", "no nitrite", "no bacteria", "negative nitrite"] },
          { id: "clin", text: "Migratory pain and localized guarding fit appendicitis", match: ["migration", "migratory", "guarding", "peritoneal", "peritonism", "classic", "clinical picture"] },
          { id: "ns", text: "Pyuria is nonspecific and may reflect contamination", match: ["nonspecific", "non specific", "contamination", "contaminated"] },
        ],
        explanation:
          "Mild pyuria is common in appendicitis because the inflamed appendix irritates the ureter or bladder. Without urinary symptoms, nitrites or bacteria, a UTI does not explain localized peritonism. Labelling abdominal pain as UTI in women is a common cause of missed appendicitis.",
        keyFeature: { topic: "abdominal-pain", n: 8 },
        source: "wses-appy",
      },
    ],
    sources: [SRC.acrRlq, SRC.wsesAppy],
    ...meta,
  },
  {
    id: "abdominal-pain-04",
    topic: "abdominal-pain",
    alsoTopics: ["infectious-diseases"],
    title: "Child with fever and abdominal pain",
    stem:
      "A 7-year-old boy has 1 day of abdominal pain, fever and two episodes of vomiting. He has a mild cough. His parents are worried about his appendix.\n\nVital signs: HR 136/min, RR 34/min, BP 102/64 mmHg, SpO2 92% on room air, temperature 39.4°C. Weight 26 kg.\n\nThe abdomen is soft with mild diffuse tenderness and no guarding. He can jump without pain. Air entry is reduced at the right base with crackles.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE causes of abdominal pain in children that originate outside the abdomen.",
        required: 3,
        accept: [
          { id: "pna", text: "Lower lobe pneumonia", match: ["pneumonia"] },
          { id: "strep", text: "Streptococcal pharyngitis", match: ["strep", "pharyngitis", "tonsillitis", "sore throat"] },
          { id: "dka", text: "Diabetic ketoacidosis", match: ["dka", "diabetic ketoacidosis", "ketoacidosis"] },
          { id: "tor", text: "Testicular torsion", match: ["torsion", "testicular"] },
          { id: "hsp", text: "IgA vasculitis (Henoch-Schonlein purpura)", match: ["hsp", "henoch", "iga vasculitis"] },
          { id: "mig", text: "Abdominal migraine", match: ["migraine"] },
          { id: "uri", text: "Otitis media or upper respiratory infection", match: ["otitis", "uri", "upper respiratory"] },
          { id: "tox", text: "Toxic ingestion such as iron or lead", match: ["ingestion", "lead poisoning", "iron", "poisoning", "toxic"] },
          { id: "sickle", text: "Sickle cell crisis", match: ["sickle"] },
        ],
        explanation:
          "Children often localize pain poorly and refer thoracic, pharyngeal and metabolic problems to the abdomen. Lower lobe pneumonia is a classic mimic of appendicitis. Examine the chest, throat and genitals in every child with abdominal pain.",
        keyFeature: { topic: "abdominal-pain", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "Name the single most useful investigation now.",
        required: 1,
        accept: [
          { id: "cxr", text: "Chest x-ray", match: ["chest x ray", "cxr", "chest radiograph", "chest xray", "chest film"] },
          { id: "lus", text: "Lung point-of-care ultrasound", match: ["lung ultrasound", "lung pocus"] },
        ],
        unacceptable: [
          { text: "CT abdomen", match: ["ct"] },
          { text: "Abdominal ultrasound for appendicitis", match: ["abdominal ultrasound", "appendix ultrasound", "abdo ultrasound"] },
        ],
        explanation:
          "Tachypnea, hypoxia and focal crackles point to pneumonia. A chest radiograph confirms it and avoids abdominal imaging. An abdominal ultrasound is reasonable only if the abdominal findings evolve.",
        keyFeature: { topic: "abdominal-pain", n: 3 },
        source: "cps-cap",
      },
      {
        id: "q3",
        kind: "short",
        update: "The chest x-ray shows right lower lobe consolidation. After acetaminophen he looks well. SpO2 is 94% on room air and he is drinking.",
        prompt: "Name the antibiotic and its total daily dose in mg/kg for outpatient treatment.",
        required: 1,
        accept: [
          { id: "amox", text: "Amoxicillin 40 to 90 mg/kg/day orally divided three times daily, maximum 4 g/day", match: ["amoxicillin 90", "amoxicillin 80", "amoxicillin 75", "amoxicillin 60", "amoxicillin 50", "amoxicillin 45", "amoxicillin 40", "amoxicillin 2340", "amoxicillin 2.3 g", "amoxicillin 780", "amoxicillin 1040", "amoxicillin 1170", "amoxicillin 1200"] },
        ],
        unacceptable: [
          { text: "Azithromycin or another macrolide as first line", match: ["azithromycin", "macrolide", "clarithromycin"] },
          { text: "Amoxicillin below the recommended range", match: ["amoxicillin 20", "amoxicillin 25", "amoxicillin 250"] },
        ],
        explanation:
          "The CPS recommends amoxicillin 40 to 90 mg/kg/day divided three times daily, to a maximum of 4 g per day. The higher end covers Streptococcus pneumoniae with reduced penicillin susceptibility. For this 26 kg child, 90 mg/kg/day is 2340 mg per day, about 780 mg three times daily. Macrolides are not first line for typical bacterial pneumonia in school age children.",
        keyFeature: { topic: "infectious-diseases", n: 8 },
        source: "cps-cap",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "The parents ask for a CT scan to be sure the appendix is normal. Which response is most appropriate? Select one.",
        options: [
          "No CT. Pneumonia explains his findings. CT radiation carries a higher lifetime cancer risk in children. Return if the pain localizes or worsens.",
          "Order CT abdomen with contrast to reassure the parents",
          "Order an abdominal x-ray to exclude appendicitis",
          "Admit for serial CT scans",
          "Order a low dose CT of the chest and abdomen",
        ],
        correct: 0,
        explanation:
          "Children are more radiosensitive and have more years to express radiation induced cancer. When a clear extra-abdominal cause explains the picture, CT adds risk without benefit. Safety netting and reassessment are the right tools.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "image-gently",
      },
    ],
    sources: [SRC.tintinalli, SRC.cpsCap, SRC.imageGently],
    ...meta,
  },
  {
    id: "abdominal-pain-05",
    topic: "abdominal-pain",
    alsoTopics: ["ischemic-heart-disease"],
    title: "Man with epigastric pain and nausea",
    stem:
      "A 61-year-old man with type 2 diabetes has 90 minutes of epigastric pain and nausea. An antacid at home gave slight relief. He is sweaty.\n\nVital signs: HR 54/min, BP 104/66 mmHg, RR 20/min, SpO2 95% on room air, temperature 36.6°C. Weight 92 kg.\n\nThe abdomen is soft with mild epigastric tenderness.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List TWO investigations to obtain within 10 minutes of arrival.",
        required: 2,
        accept: [
          { id: "ecg", text: "12 lead ECG", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "trop", text: "Troponin", match: ["troponin", "trop"] },
          { id: "glu", text: "Capillary glucose", match: ["glucose", "sugar"] },
        ],
        explanation:
          "Epigastric pain in a diabetic man with bradycardia and diaphoresis is ACS until proven otherwise. An ECG within 10 minutes is the priority. Antacid response does not distinguish cardiac from gastric pain.",
        keyFeature: { topic: "abdominal-pain", n: 3 },
        source: "ccs-stemi",
      },
      {
        id: "q2",
        kind: "menu",
        update: "The ECG shows 3 mm ST elevation in II, III and aVF with reciprocal ST depression in aVL. A primary PCI centre is 25 minutes away.",
        prompt: "Which TWO are the most appropriate immediate treatments? Select TWO.",
        options: [
          "ASA 160 mg chewed",
          "ASA 81 mg swallowed",
          "Activate the catheterization lab for primary PCI",
          "Tenecteplase now",
          "Metoprolol 5 mg IV",
          "Pantoprazole 80 mg IV",
          "Nitroglycerin 0.4 mg SL before any further assessment",
          "Morphine 10 mg IV",
          "Viscous lidocaine and antacid",
        ],
        select: 2,
        correct: [0, 2],
        explanation:
          "Chewed ASA 160 to 325 mg and rapid primary PCI are the core of STEMI care when PCI is available within 120 minutes. Fibrinolysis is for when timely PCI is not possible. Beta blockers are harmful with bradycardia and borderline pressure.",
        keyFeature: { topic: "ischemic-heart-disease", n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "The nurse asks about nitroglycerin for his pain. List TWO things you must check first.",
        required: 2,
        accept: [
          { id: "rv", text: "Right sided ECG for right ventricular infarction", match: ["right sided", "v4r", "right ventricular", "rv infarct", "rv involvement", "right ecg"] },
          { id: "bp", text: "Blood pressure", match: ["blood pressure", "bp", "systolic", "hypotension"] },
          { id: "pde5", text: "Recent phosphodiesterase 5 inhibitor use", match: ["pde5", "pde 5", "phosphodiesterase", "sildenafil", "tadalafil", "vardenafil", "erectile"] },
          { id: "hr", text: "Heart rate for bradycardia", match: ["heart rate", "bradycardia"] },
        ],
        explanation:
          "Inferior STEMI often involves the right ventricle, which is preload dependent. Nitrates can cause profound hypotension in RV infarction, with low BP, or after a PDE5 inhibitor. His pressure is already borderline.",
        keyFeature: { topic: "ischemic-heart-disease", n: 7 },
        source: "ccs-stemi",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "List THREE other causes outside the abdomen that can present as epigastric pain in adults.",
        required: 3,
        accept: [
          { id: "pe", text: "Pulmonary embolism", match: ["pulmonary embolism", "pe"] },
          { id: "pna", text: "Lower lobe pneumonia", match: ["pneumonia"] },
          { id: "dka", text: "Diabetic ketoacidosis", match: ["dka", "ketoacidosis"] },
          { id: "dis", text: "Aortic dissection", match: ["dissection"] },
          { id: "peri", text: "Pericarditis or myocarditis", match: ["pericarditis", "myocarditis"] },
          { id: "zos", text: "Herpes zoster", match: ["zoster", "shingles"] },
          { id: "ptx", text: "Pneumothorax", match: ["pneumothorax"] },
          { id: "eso", text: "Esophageal rupture", match: ["boerhaave", "esophageal rupture", "esophageal perforation", "oesophageal"] },
          { id: "adr", text: "Adrenal crisis", match: ["adrenal", "addison"] },
          { id: "hyperca", text: "Hypercalcemia", match: ["hypercalcemia", "calcium"] },
        ],
        unacceptable: [{ text: "Gastritis or peptic ulcer", match: ["gastritis", "peptic", "gerd", "reflux"] }],
        explanation:
          "Thoracic, metabolic and dermatologic conditions commonly refer pain to the epigastrium. When no clear abdominal cause is found, search the chest and the chemistry. Gastritis and ulcer disease are abdominal causes.",
        keyFeature: { topic: "abdominal-pain", n: 3 },
        source: "rosen",
      },
    ],
    sources: [SRC.ccsStemi, SRC.rosen],
    ...meta,
  },
  {
    id: "abdominal-pain-06",
    topic: "abdominal-pain",
    alsoTopics: ["shock"],
    title: "Young woman with vomiting and abdominal pain",
    stem:
      "A 19-year-old woman has 2 days of vomiting and diffuse abdominal pain. She has had thirst and frequent urination for 3 weeks and has lost 4 kg. She has no medical history.\n\nVital signs: HR 128/min, BP 98/60 mmHg, RR 32/min and deep, SpO2 99% on room air, temperature 37.1°C. Weight 58 kg.\n\nThe abdomen is diffusely tender without guarding. Venous gas: pH 7.08, bicarbonate 6 mmol/L. Glucose 31 mmol/L. Sodium 131, potassium 5.6, chloride 96 mmol/L. Creatinine 118 µmol/L. Beta hydroxybutyrate 7.2 mmol/L. Lipase is normal. Beta hCG is negative.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What is the most likely cause of her abdominal pain?",
        required: 1,
        accept: [{ id: "dka", text: "Diabetic ketoacidosis", match: ["dka", "diabetic ketoacidosis", "ketoacidosis"] }],
        unacceptable: [{ text: "Appendicitis", match: ["appendicitis"] }],
        explanation:
          "Abdominal pain is common in DKA and correlates with the severity of acidosis. This is new onset type 1 diabetes with an anion gap of 29. A surgical cause should be sought only if pain persists after the acidosis corrects.",
        keyFeature: { topic: "abdominal-pain", n: 3 },
        source: "dc-dka",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "List THREE priorities in her initial management.",
        required: 3,
        accept: [
          { id: "fluid", text: "IV 0.9% saline bolus to restore circulating volume", match: ["normal saline", "0.9%", "saline", "ns", "fluid", "crystalloid", "ringer", "bolus"] },
          { id: "ins", text: "IV insulin infusion", match: ["insulin"] },
          { id: "k", text: "Monitor and replace potassium", match: ["potassium", "k", "kcl"] },
          { id: "mon", text: "Frequent glucose, electrolyte and gas monitoring", match: ["monitor", "monitoring", "hourly", "repeat gas", "repeat vbg", "q1h"] },
          { id: "dex", text: "Add dextrose when glucose falls to about 14 mmol/L", match: ["dextrose", "d5", "d5w"] },
          { id: "prec", text: "Look for a precipitant such as infection", match: ["precipitant", "trigger", "infection"] },
        ],
        unacceptable: [{ text: "Sodium bicarbonate at this pH", match: ["sodium bicarbonate", "give bicarbonate", "bicarbonate infusion", "iv bicarbonate", "bicarb"] }],
        explanation:
          "Volume first, then insulin, with close attention to potassium. Total body potassium is depleted even when the serum level is high. Bicarbonate is generally reserved for pH below about 7.0.",
        keyFeature: { topic: "shock", n: 3 },
        source: "dc-dka",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which insulin plan is most appropriate now? Select one.",
        options: [
          "Regular insulin infusion at 0.1 units/kg/h with no bolus. Hold potassium replacement while potassium is above 5.0 mmol/L and recheck it often.",
          "Regular insulin 10 units IV bolus, then 0.1 units/kg/h",
          "Delay insulin until potassium is below 4.0 mmol/L",
          "Rapid acting insulin 10 units subcutaneously every 2 hours",
          "Insulin 0.1 units/kg/h plus 40 mmol/L potassium chloride in each litre now",
        ],
        correct: 0,
        explanation:
          "An insulin infusion of 0.1 units/kg/h is standard and a bolus is not needed. Insulin is withheld only for hypokalemia, below 3.3 mmol/L in Diabetes Canada guidance and below 3.5 mmol/L in the 2024 ADA consensus. Both start potassium once it falls below 5.0 mmol/L, which it will with insulin.",
        keyFeature: { topic: "shock", n: 8 },
        source: "dc-dka",
      },
      {
        id: "q4",
        kind: "single",
        update: "Eight hours later the pH is 7.29 and the anion gap has closed. Her abdominal pain has resolved. The abdomen is soft and nontender.",
        prompt: "The surgical resident asks whether CT of the abdomen is still needed. Select one.",
        options: [
          "No CT. Pain that resolves with correction of DKA supports DKA as the cause. Reassess and image only if pain persists.",
          "CT abdomen with contrast to exclude appendicitis before discharge",
          "Abdominal ultrasound for all patients with DKA and abdominal pain",
          "CT because abdominal pain in DKA always needs imaging",
          "Diagnostic laparoscopy",
        ],
        correct: 0,
        explanation:
          "Imaging should answer a real clinical question. Resolution of pain as acidosis clears is strong evidence against a surgical cause. Unnecessary CT in a 19-year-old adds lifetime cancer risk and contrast exposure.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "dc-dka",
      },
    ],
    sources: [SRC.dcDka],
    ...meta,
  },
  {
    id: "abdominal-pain-07",
    topic: "abdominal-pain",
    title: "Confused nursing home resident",
    stem:
      "An 83-year-old woman is sent from her long-term care home with confusion and a presumed urinary tract infection. Staff report poor intake for 2 days, one episode of vomiting, and pain when she is moved. She has dementia, hypertension and polymyalgia rheumatica. Medications include metoprolol and prednisone 10 mg daily.\n\nVital signs: HR 88/min, BP 102/60 mmHg, RR 24/min, SpO2 94% on room air, temperature 37.8°C.\n\nShe has lower abdominal tenderness, worse on the left, with voluntary guarding. Urine dipstick shows 2+ leukocytes and positive nitrites. WBC 10.1 x 10^9/L. Lactate 2.9 mmol/L.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE serious intra-abdominal diagnoses to consider before attributing her illness to a urinary tract infection.",
        required: 3,
        accept: [
          { id: "div", text: "Complicated diverticulitis", match: ["diverticulitis", "diverticular"] },
          { id: "perf", text: "Perforated viscus", match: ["perforated", "perforation", "free air"] },
          { id: "obs", text: "Bowel obstruction or volvulus", match: ["obstruction", "volvulus", "sbo"] },
          { id: "mes", text: "Mesenteric ischemia", match: ["mesenteric", "ischemic bowel", "bowel ischemia", "ischemic colitis"] },
          { id: "aaa", text: "Abdominal aortic aneurysm", match: ["aaa", "aneurysm"] },
          { id: "bil", text: "Cholecystitis or cholangitis", match: ["cholecystitis", "cholangitis", "biliary"] },
          { id: "app", text: "Appendicitis", match: ["appendicitis"] },
          { id: "hern", text: "Incarcerated hernia", match: ["hernia"] },
          { id: "cdiff", text: "Clostridioides difficile colitis", match: ["difficile", "c diff", "colitis"] },
        ],
        explanation:
          "Localized tenderness with guarding and a raised lactate are not explained by a UTI. Older adults with serious abdominal disease often present with confusion alone. Steroids and a beta blocker can blunt peritonism and tachycardia.",
        keyFeature: { topic: "abdominal-pain", n: 8 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "List TWO reasons the positive urine dipstick is unreliable in her.",
        required: 2,
        accept: [
          { id: "asb", text: "Asymptomatic bacteriuria is common in older women in long-term care", match: ["asymptomatic bacteriuria", "asymptomatic", "colonization", "colonized", "colonised", "baseline bacteriuria"] },
          { id: "adj", text: "Adjacent pelvic inflammation can cause pyuria", match: ["adjacent", "sterile pyuria", "pelvic inflammation", "nearby inflammation"] },
          { id: "dem", text: "Dementia prevents her from reporting urinary symptoms", match: ["dementia", "cannot report", "unable to report", "no urinary symptom", "no dysuria"] },
          { id: "exam", text: "Localized tenderness and guarding are not explained by UTI", match: ["guarding", "localized", "localised", "peritoneal", "exam"] },
          { id: "cont", text: "The specimen may be contaminated", match: ["contamination", "contaminated"] },
        ],
        explanation:
          "Bacteriuria and pyuria are present in a large share of women in long-term care without infection. A positive dipstick has poor positive predictive value here. Treating it as the diagnosis delays recognition of surgical disease.",
        keyFeature: { topic: "abdominal-pain", n: 8 },
        source: "idsa-asb",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "Name the most appropriate imaging test.",
        required: 1,
        accept: [{ id: "ct", text: "CT abdomen and pelvis with IV contrast", match: ["ct", "computed tomography"] }],
        unacceptable: [
          { text: "Abdominal radiograph", match: ["x ray", "xray", "radiograph", "plain film"] },
          { text: "Ultrasound", match: ["ultrasound"] },
        ],
        explanation:
          "CT with IV contrast is the best single test for undifferentiated abdominal pain in older adults, especially with left lower quadrant findings. Plain films and ultrasound miss diverticular abscess and small amounts of free air.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "sis-iai",
      },
      {
        id: "q4",
        kind: "short",
        update: "CT shows perforated sigmoid diverticulitis with free air and pelvic fluid. BP is now 88/50 mmHg.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "surg", text: "Urgent general surgery consultation", match: ["surgery", "surgeon", "surgical"] },
          { id: "abx", text: "Broad spectrum IV antibiotics such as piperacillin-tazobactam", match: ["antibiotic", "piperacillin", "pip tazo", "ceftriaxone", "metronidazole", "meropenem"] },
          { id: "fluid", text: "IV crystalloid bolus", match: ["fluid", "crystalloid", "ringer", "saline", "bolus"] },
          { id: "ster", text: "Stress dose hydrocortisone 100 mg IV", match: ["hydrocortisone", "stress dose", "steroid"] },
          { id: "goc", text: "Goals of care discussion with her substitute decision maker", match: ["goals of care", "advance directive", "code status", "substitute decision", "sdm"] },
          { id: "cult", text: "Blood cultures", match: ["blood culture", "culture"] },
          { id: "analg", text: "Analgesia", match: ["analgesia", "opioid", "morphine", "hydromorphone", "fentanyl"] },
        ],
        unacceptable: [{ text: "Treat as a urinary tract infection only", match: ["nitrofurantoin", "uti only"] }],
        explanation:
          "Perforation with hypotension needs source control, antibiotics and resuscitation at once. Chronic prednisone use calls for stress dose steroids in shock. Her goals of care should guide the surgical plan.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "sis-iai",
      },
    ],
    sources: [SRC.rosen, SRC.idsaAsb, SRC.sisIai],
    ...meta,
  },
  {
    id: "abdominal-pain-08",
    topic: "abdominal-pain",
    alsoTopics: ["first-trimester-bleeding"],
    title: "Young woman with lower abdominal pain and near syncope",
    stem:
      "A 27-year-old woman has 2 hours of sudden lower abdominal pain and light vaginal spotting. She nearly fainted in the shower. Her last menstrual period was 7 weeks ago. She is G2P1.\n\nVital signs: HR 124/min, BP 86/52 mmHg, RR 24/min, SpO2 98% on room air, temperature 36.5°C. Weight 64 kg.\n\nShe is pale. There is diffuse lower abdominal tenderness with guarding. She complains of right shoulder tip pain.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE diagnoses to consider.",
        required: 3,
        accept: [
          { id: "ect", text: "Ruptured ectopic pregnancy", match: ["ectopic"] },
          { id: "cyst", text: "Ruptured hemorrhagic ovarian cyst or corpus luteum", match: ["cyst", "corpus luteum"] },
          { id: "tor", text: "Ovarian torsion", match: ["torsion"] },
          { id: "spleen", text: "Splenic rupture", match: ["splenic", "spleen"] },
          { id: "perf", text: "Perforated viscus", match: ["perforated", "perforation"] },
          { id: "toa", text: "Ruptured tubo-ovarian abscess or septic abortion", match: ["tubo ovarian", "toa", "septic abortion", "pid"] },
          { id: "app", text: "Perforated appendicitis", match: ["appendicitis"] },
        ],
        explanation:
          "Shock with lower abdominal pain in a woman of reproductive age is a ruptured ectopic pregnancy until proven otherwise. Shoulder tip pain suggests hemoperitoneum. Other causes of intraperitoneal bleeding must also be considered.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "sogc-ectopic",
      },
      {
        id: "q2",
        kind: "short",
        update: "A urine pregnancy test is positive.",
        prompt: "Name the most useful bedside test now.",
        required: 1,
        accept: [{ id: "pocus", text: "Point-of-care ultrasound for free fluid and intrauterine pregnancy", match: ["pocus", "fast", "efast", "ultrasound", "bedside us"] }],
        unacceptable: [
          { text: "CT abdomen", match: ["ct"], dangerous: true },
          { text: "Quantitative beta hCG as the next step", match: ["quantitative", "serum hcg", "beta hcg level"] },
        ],
        explanation:
          "Bedside ultrasound shows hemoperitoneum in minutes and whether an intrauterine pregnancy is present. Free fluid with a positive test and shock means the operating room. A hypotensive patient must not go to CT.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "sogc-ectopic",
      },
      {
        id: "q3",
        kind: "short",
        update: "Bedside ultrasound shows free fluid in the hepatorenal space and no intrauterine pregnancy. BP is 80/48 mmHg.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "or", text: "Call gynecology now for the operating room", match: ["gynecology", "gynaecology", "gynecologist", "gynaecologist", "obstetric", "operating room", "surgery", "laparoscopy", "laparotomy", "obgyn", "ob gyn"] },
          { id: "tx", text: "Transfuse uncrossmatched red cells or activate massive transfusion", match: ["transfuse", "transfusion", "massive transfusion", "mtp", "o negative", "uncrossmatched", "prbc", "packed red", "blood product"] },
          { id: "iv", text: "Two large bore IV lines", match: ["large bore", "two iv", "2 iv", "iv access"] },
          { id: "xm", text: "Group and crossmatch", match: ["crossmatch", "cross match", "type and screen", "group and screen", "type and cross"] },
          { id: "cbc", text: "CBC and coagulation studies", match: ["cbc", "coagulation", "inr", "fibrinogen"] },
        ],
        unacceptable: [
          { text: "Methotrexate", match: ["methotrexate"], dangerous: true },
          { text: "Formal ultrasound before calling gynecology", match: ["formal ultrasound", "formal us"] },
        ],
        explanation:
          "A ruptured ectopic with shock needs surgery now, with blood running while the team assembles. Formal imaging adds delay and nothing to the decision. Methotrexate is only for stable, unruptured ectopic pregnancy.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "sogc-ectopic",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Her blood group is O Rh negative and her antibody screen is negative. Which statement is most accurate? Select one.",
        options: [
          "Current SOGC guidance advises against routine Rh immune globulin for an ectopic pregnancy at this gestation. Document her Rh status and discuss it with her.",
          "Surgery should wait until Rh immune globulin has been given",
          "Rh immune globulin is indicated only if her antibody screen is positive",
          "Give Rh immune globulin 1500 mcg IV because of the large hemoperitoneum",
          "Rh immune globulin is indicated only if a Kleihauer-Betke test is positive",
        ],
        correct: 0,
        explanation:
          "The 2024 SOGC guideline recommends not giving Rh immune globulin for ectopic pregnancy before 8 weeks and suggests not giving it from 8 to 12 weeks, because fetal red cell volume is too small to sensitize. Some centres still give 120 to 300 mcg IM within 72 hours, and SOGC allows this for risk averse patients from 8 weeks. A positive antibody screen means she is already sensitized and prophylaxis no longer helps. The hemoperitoneum is maternal blood and does not change the dose.",
        keyFeature: { topic: "first-trimester-bleeding", n: 5 },
        source: "sogc-rh",
      },
    ],
    sources: [SRC.sogcEctopic, SRC.sogcRh],
    ...meta,
  },
  {
    id: "abdominal-pain-09",
    topic: "abdominal-pain",
    title: "Teenager with lower abdominal pain and vomiting",
    stem:
      "A 14-year-old boy has 3 hours of severe lower abdominal pain and vomiting. The pain woke him from sleep. He describes it as belly pain and does not mention anything else.\n\nVital signs: HR 108/min, BP 128/76 mmHg, RR 18/min, SpO2 99% on room air, temperature 37.0°C. Weight 55 kg.\n\nThe abdomen is soft with mild left lower quadrant tenderness.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "You examine the genitals. List THREE findings that would support testicular torsion.",
        required: 3,
        accept: [
          { id: "high", text: "High riding testis", match: ["high riding", "elevated", "retracted", "high testis"] },
          { id: "horiz", text: "Horizontal lie", match: ["horizontal", "transverse lie"] },
          { id: "crem", text: "Absent cremasteric reflex", match: ["cremasteric"] },
          { id: "tend", text: "Firm, swollen, tender testis", match: ["swollen", "swelling", "tender testis", "tender testicle", "firm", "hard"] },
          { id: "ery", text: "Scrotal erythema or edema", match: ["erythema", "red", "scrotal edema", "scrotal oedema"] },
        ],
        explanation:
          "Adolescent boys often report torsion as abdominal pain. Every male with lower abdominal pain needs a genital exam. Absent cremasteric reflex, high riding testis and horizontal lie are the key findings.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "twist",
      },
      {
        id: "q2",
        kind: "single",
        update: "The left testis is high riding, firm and tender, with a horizontal lie and absent cremasteric reflex. Ultrasound is available in 2 hours.",
        prompt: "What is the most appropriate next step? Select one.",
        options: [
          "Urgent urology consultation for surgical exploration without waiting for ultrasound",
          "Doppler ultrasound first to confirm the diagnosis",
          "Urinalysis and treatment for epididymitis",
          "Analgesia and reassessment in 2 hours",
          "CT of the abdomen and pelvis",
        ],
        correct: 0,
        explanation:
          "With a high clinical probability of torsion, imaging only delays surgery. Testicular salvage falls steeply after about 6 hours. Ultrasound is useful when the diagnosis is genuinely uncertain.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "twist",
      },
      {
        id: "q3",
        kind: "single",
        update: "His mother says he was seen at a walk-in clinic yesterday for similar pain that settled. A Doppler ultrasound there was reported as normal.",
        prompt: "Which statement is most accurate? Select one.",
        options: [
          "A normal Doppler ultrasound yesterday does not exclude torsion today",
          "Normal flow yesterday makes torsion very unlikely today",
          "Intermittent torsion never needs surgical follow up",
          "Doppler ultrasound is 100% sensitive for torsion",
          "Torsion cannot present with abdominal pain alone",
        ],
        correct: 0,
        explanation:
          "Intermittent torsion and detorsion can produce normal flow between episodes. Doppler also misses partial torsion. A previous negative test must not override current clinical findings.",
        keyFeature: { topic: "abdominal-pain", n: 6 },
        source: "rosen",
      },
    ],
    sources: [SRC.twist, SRC.rosen],
    ...meta,
  },
  {
    id: "abdominal-pain-10",
    topic: "abdominal-pain",
    alsoTopics: ["shock"],
    title: "Infant with episodes of crying",
    stem:
      "A 10-month-old boy has 12 hours of episodes of inconsolable crying every 15 to 20 minutes. He draws his legs up during each episode. He has vomited four times, not bilious. Between episodes he is pale and sleepy. He passed one stool with dark red mucus.\n\nVital signs: HR 168/min, RR 36/min, BP 84/50 mmHg, SpO2 98% on room air, temperature 37.6°C. Capillary refill 3 seconds. Weight 9 kg.\n\nA vague mass is felt in the right upper quadrant. The abdomen is not peritonitic.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE diagnoses to consider at this age.",
        required: 3,
        accept: [
          { id: "intus", text: "Intussusception", match: ["intussusception"] },
          { id: "malr", text: "Malrotation with midgut volvulus", match: ["malrotation", "volvulus"] },
          { id: "hern", text: "Incarcerated inguinal hernia", match: ["hernia"] },
          { id: "tor", text: "Testicular torsion", match: ["torsion"] },
          { id: "ent", text: "Bacterial enterocolitis", match: ["enteritis", "enterocolitis", "gastroenteritis", "colitis"] },
          { id: "meck", text: "Meckel diverticulum", match: ["meckel"] },
          { id: "hus", text: "Hemolytic uremic syndrome", match: ["hemolytic uremic", "hus"] },
          { id: "nat", text: "Non-accidental abdominal trauma", match: ["abuse", "non accidental", "nonaccidental", "nat", "inflicted"] },
        ],
        explanation:
          "Age drives the differential. Intermittent colicky pain, lethargy between episodes and bloody mucus at 10 months point to intussusception. Volvulus, incarcerated hernia and torsion are time critical and must not be missed.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "Name the most appropriate imaging test.",
        required: 1,
        accept: [{ id: "us", text: "Abdominal ultrasound", match: ["ultrasound", "us", "pocus", "sonography"] }],
        unacceptable: [
          { text: "CT abdomen", match: ["ct", "computed tomography"] },
          { text: "Abdominal x-ray alone", match: ["x ray", "xray", "radiograph"] },
        ],
        explanation:
          "Ultrasound is highly sensitive and specific for intussusception and uses no radiation. CT adds radiation in a highly radiosensitive infant. Plain films are insensitive.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "image-gently",
      },
      {
        id: "q3",
        kind: "short",
        update: "Ultrasound shows a target sign in the right upper quadrant. There is no free fluid.",
        prompt: "List TWO next management steps.",
        required: 2,
        accept: [
          { id: "enema", text: "Air or hydrostatic enema reduction by radiology", match: ["enema", "air reduction", "pneumatic", "hydrostatic", "reduction"] },
          { id: "surg", text: "Notify pediatric surgery", match: ["surgery", "surgeon", "surgical"] },
          { id: "fluid", text: "IV fluid resuscitation", match: ["bolus", "fluid", "saline"] },
          { id: "analg", text: "Analgesia", match: ["analgesia", "morphine", "fentanyl"] },
          { id: "npo", text: "NPO with nasogastric decompression", match: ["npo", "nasogastric", "ng tube", "nothing by mouth"] },
        ],
        explanation:
          "Enema reduction is first line for a stable child without peritonitis or perforation. Surgery must be aware in case reduction fails or perforation occurs. Resuscitate first because these children are often volume depleted.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which initial fluid bolus is most appropriate? Select one.",
        options: [
          "0.9% sodium chloride 180 mL IV over 5 to 20 minutes",
          "0.9% sodium chloride 90 mL IV over 1 hour",
          "0.9% sodium chloride 900 mL IV",
          "5% dextrose in water 180 mL IV",
          "0.45% sodium chloride at 36 mL/h only",
          "5% albumin 45 mL IV",
        ],
        correct: 0,
        explanation:
          "Isotonic crystalloid at 20 mL/kg is the standard bolus for a child with poor perfusion, so 180 mL for 9 kg. Reassess after each bolus. Hypotonic or dextrose only fluids are not resuscitation fluids.",
        keyFeature: { topic: "shock", n: 3 },
        source: "tintinalli",
      },
    ],
    sources: [SRC.tintinalli, SRC.imageGently],
    ...meta,
  },
  {
    id: "abdominal-pain-11",
    topic: "abdominal-pain",
    title: "Pregnant woman with right lower quadrant pain",
    stem:
      "A 30-year-old woman, G1P0 at 14 weeks by dating ultrasound, has 24 hours of right lower quadrant pain, nausea and anorexia.\n\nVital signs: HR 104/min, BP 112/68 mmHg, RR 18/min, SpO2 99% on room air, temperature 37.9°C.\n\nShe has right lower quadrant tenderness with guarding. Fetal heart rate is 156/min. WBC is 15.0 x 10^9/L.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate first imaging test? Select one.",
        options: [
          "Graded compression ultrasound of the right lower quadrant",
          "CT abdomen and pelvis with IV contrast",
          "MRI with gadolinium",
          "Plain abdominal radiograph",
          "Nuclear medicine white cell scan",
        ],
        correct: 0,
        explanation:
          "Ultrasound is first line in pregnancy because it uses no ionizing radiation. A visualized inflamed appendix confirms the diagnosis. A nondiagnostic scan leads to MRI.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "acog-723",
      },
      {
        id: "q2",
        kind: "short",
        update: "The ultrasound does not visualize the appendix. There is no free fluid.",
        prompt: "Name the most appropriate next imaging test.",
        required: 1,
        accept: [{ id: "mri", text: "Non-contrast MRI of the abdomen and pelvis", match: ["mri", "magnetic resonance"] }],
        unacceptable: [{ text: "MRI with gadolinium", match: ["gadolinium"] }],
        explanation:
          "Non-contrast MRI is highly accurate for appendicitis in pregnancy and avoids radiation. Gadolinium crosses the placenta and should be avoided unless essential.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "acog-723",
      },
      {
        id: "q3",
        kind: "short",
        update: "MRI is not available at your hospital for 24 hours.",
        prompt: "List TWO acceptable next steps.",
        required: 2,
        accept: [
          { id: "surg", text: "General surgery consultation for clinical assessment", match: ["surgery", "surgeon", "surgical"] },
          { id: "ct", text: "CT after counselling that the fetal dose is low and below harmful thresholds", match: ["ct", "computed tomography"] },
          { id: "trans", text: "Transfer to a centre with MRI", match: ["transfer"] },
          { id: "obs", text: "Admit for serial examinations and repeat ultrasound", match: ["serial", "repeat ultrasound", "admit", "observe", "observation"] },
          { id: "ob", text: "Obstetrics consultation", match: ["obstetric", "obstetrician", "obstetrics"] },
        ],
        unacceptable: [
          { text: "Discharge home for outpatient MRI tomorrow", match: ["discharge", "outpatient mri", "mri tomorrow"], dangerous: true },
        ],
        explanation:
          "Perforated appendicitis carries a much higher risk of fetal loss than a single CT. The fetal dose from abdominal CT is well below the level linked to fetal harm. Imaging should not be withheld when it is needed to make the diagnosis.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "acog-723",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "List THREE other causes of right lower quadrant pain to consider in pregnancy.",
        required: 3,
        accept: [
          { id: "tor", text: "Ovarian torsion", match: ["torsion"] },
          { id: "cyst", text: "Ovarian cyst rupture or hemorrhage", match: ["cyst"] },
          { id: "pyelo", text: "Pyelonephritis", match: ["pyelonephritis"] },
          { id: "stone", text: "Ureteric stone", match: ["stone", "renal colic", "ureteric", "nephrolithiasis"] },
          { id: "rl", text: "Round ligament pain", match: ["round ligament"] },
          { id: "fib", text: "Degenerating fibroid", match: ["fibroid", "leiomyoma"] },
          { id: "bil", text: "Cholecystitis with an upwardly displaced gallbladder", match: ["cholecystitis", "biliary", "gallbladder"] },
          { id: "het", text: "Heterotopic pregnancy", match: ["heterotopic"] },
          { id: "misc", text: "Threatened miscarriage", match: ["miscarriage", "abortion"] },
          { id: "crohn", text: "Crohn disease", match: ["crohn", "ileitis"] },
        ],
        explanation:
          "Pregnancy adds obstetric causes and makes torsion and pyelonephritis more common. The enlarging uterus shifts the appendix and gallbladder, so location becomes less reliable.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "rosen",
      },
    ],
    sources: [SRC.acog723, SRC.rosen],
    ...meta,
  },
  {
    id: "abdominal-pain-12",
    topic: "abdominal-pain",
    alsoTopics: ["analgesia-sedation", "infectious-diseases"],
    title: "Man with recurrent flank pain",
    stem:
      "A 36-year-old man has 3 hours of colicky left flank pain radiating to the groin. This is his fourth episode of kidney stones. He has had three CT scans for stones in the past 5 years.\n\nVital signs: HR 96/min, BP 138/84 mmHg, RR 18/min, SpO2 99% on room air, temperature 36.8°C. Weight 80 kg.\n\nThe abdomen is soft and nontender. Urinalysis shows blood and no leukocytes or nitrites. Creatinine is 82 µmol/L.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which imaging strategy is most appropriate? Select one.",
        options: [
          "Point-of-care renal ultrasound for hydronephrosis, with no CT if the course is uncomplicated",
          "Non-contrast CT of the kidneys, ureters and bladder now",
          "CT abdomen with IV contrast",
          "IV pyelogram",
          "MRI urogram",
        ],
        correct: 0,
        explanation:
          "A young patient with known stones and a typical, uncomplicated episode does not need repeat CT. Ultrasound first reduces cumulative radiation without worse outcomes. CT is kept for atypical features or complications.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "caep-cw",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "List THREE features in a patient with suspected renal colic that should prompt urgent imaging or urology involvement.",
        required: 3,
        accept: [
          { id: "inf", text: "Fever or signs of infection", match: ["fever", "infection", "sepsis", "septic", "pyuria"] },
          { id: "sol", text: "Solitary or transplanted kidney", match: ["solitary", "single kidney", "transplant"] },
          { id: "aki", text: "Acute kidney injury", match: ["creatinine", "renal failure", "kidney injury", "aki", "renal function"] },
          { id: "pain", text: "Intractable pain or vomiting", match: ["intractable", "refractory", "uncontrolled", "persistent vomiting", "cannot tolerate"] },
          { id: "age", text: "Older age or first episode, raising concern for AAA", match: ["age", "older", "first episode", "aaa", "aneurysm"] },
          { id: "preg", text: "Pregnancy", match: ["pregnancy", "pregnant"] },
          { id: "unst", text: "Hemodynamic instability", match: ["hypotension", "unstable", "instability", "shock"] },
          { id: "large", text: "Large stone over 10 mm", match: ["large stone", "10 mm", "stone size"] },
        ],
        explanation:
          "An infected obstructed kidney is a urologic emergency. Any threat to renal function also needs urgent imaging. In older patients, a first episode of flank pain must prompt consideration of AAA.",
        keyFeature: { topic: "abdominal-pain", n: 1 },
        source: "eau-stone",
      },
      {
        id: "q3",
        kind: "menu",
        prompt: "Which TWO are most appropriate for his pain and stone passage? Select TWO.",
        options: [
          "Ketorolac 15 mg IV",
          "Ketorolac 60 mg IV",
          "Morphine 20 mg IV",
          "Tamsulosin 0.4 mg PO daily if the stone is distal and 5 to 10 mm",
          "2 L IV fluid bolus to flush the stone",
          "Hyoscine butylbromide 20 mg IV",
          "Tamsulosin 4 mg PO daily",
          "Oral oxycodone 5 mg only",
        ],
        select: 2,
        correct: [0, 3],
        explanation:
          "NSAIDs are first line for renal colic, and ketorolac shows a ceiling effect at 10 to 15 mg IV. Tamsulosin aids passage of distal stones of 5 to 10 mm. Forced IV hydration does not help and antispasmodics add little.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "eau-stone",
      },
      {
        id: "q4",
        kind: "short",
        update: "He returns 36 hours later with rigors. Temperature 39.2°C, HR 122/min, BP 94/58 mmHg. Bedside ultrasound shows moderate left hydronephrosis.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "cult", text: "Blood and urine cultures", match: ["culture"] },
          { id: "abx", text: "IV antibiotics such as ceftriaxone", match: ["antibiotic", "ceftriaxone", "piperacillin", "gentamicin", "ampicillin"] },
          { id: "uro", text: "Urgent urology for decompression by stent or nephrostomy", match: ["urology", "urologist", "stent", "nephrostomy", "decompression", "decompress"] },
          { id: "fluid", text: "IV fluid resuscitation", match: ["fluid", "bolus", "crystalloid", "saline", "ringer"] },
          { id: "lac", text: "Lactate and sepsis bloodwork", match: ["lactate"] },
        ],
        unacceptable: [{ text: "Discharge with oral antibiotics", match: ["oral antibiotic", "discharge"], dangerous: true }],
        explanation:
          "An obstructed infected kidney needs antibiotics and urgent drainage. Antibiotics alone fail because the collecting system cannot drain. Discharging this patient risks rapid progression to septic shock.",
        keyFeature: { topic: "infectious-diseases", n: 1 },
        source: "eau-stone",
      },
    ],
    sources: [SRC.caepCw, SRC.eauStone],
    ...meta,
  },
  {
    id: "abdominal-pain-13",
    topic: "abdominal-pain",
    title: "Man with epigastric pain radiating to the back",
    stem:
      "A 47-year-old man who drinks 12 beers a day has 10 hours of severe epigastric pain radiating to the back, with repeated vomiting.\n\nVital signs: HR 118/min, BP 108/70 mmHg, RR 22/min, SpO2 95% on room air, temperature 37.8°C. Weight 78 kg.\n\nHe is writhing in pain. There is epigastric tenderness with mild guarding. The rest of the abdomen is soft.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "List THREE serious diagnoses to exclude.",
        required: 3,
        accept: [
          { id: "perf", text: "Perforated peptic ulcer", match: ["perforated", "perforation", "free air"] },
          { id: "panc", text: "Acute pancreatitis", match: ["pancreatitis"] },
          { id: "aaa", text: "Abdominal aortic aneurysm", match: ["aaa", "aneurysm"] },
          { id: "mi", text: "Myocardial infarction", match: ["myocardial", "mi", "acs", "acute coronary"] },
          { id: "mes", text: "Mesenteric ischemia", match: ["mesenteric", "bowel ischemia", "ischemic bowel"] },
          { id: "dis", text: "Aortic dissection", match: ["dissection"] },
          { id: "eso", text: "Esophageal rupture", match: ["boerhaave", "esophageal", "oesophageal"] },
          { id: "bil", text: "Cholangitis or cholecystitis", match: ["cholangitis", "cholecystitis", "biliary"] },
        ],
        explanation:
          "Severe pain with few abdominal signs demands exclusion of pancreatitis, perforation and vascular catastrophes. An ECG, lipase and upright chest radiograph are quick first steps. Alcohol use raises the risk of several of these.",
        keyFeature: { topic: "abdominal-pain", n: 2 },
        source: "acg-panc",
      },
      {
        id: "q2",
        kind: "single",
        update: "Lipase is 1850 U/L. The upper limit of normal is 60 U/L. The ECG shows sinus tachycardia only. An upright chest radiograph shows no free air.",
        prompt: "Is CT required in the ED to confirm the diagnosis? Select one.",
        options: [
          "No. Typical pain plus lipase above three times normal confirms pancreatitis. Reserve CT for diagnostic doubt or failure to improve.",
          "Yes. Contrast CT is required to confirm all cases of pancreatitis.",
          "Yes. CT best predicts necrosis in the first 12 hours.",
          "No. Imaging is never needed in pancreatitis.",
          "Yes. MRCP is required before admission.",
        ],
        correct: 0,
        explanation:
          "Two of three criteria make the diagnosis. Early CT underestimates necrosis and rarely changes management. It adds radiation and contrast in a volume depleted patient.",
        keyFeature: { topic: "abdominal-pain", n: 7 },
        source: "acg-panc",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "List TWO investigations to look for a cause other than alcohol.",
        required: 2,
        accept: [
          { id: "us", text: "Right upper quadrant ultrasound for gallstones", match: ["ultrasound", "us", "gallstone"] },
          { id: "tg", text: "Triglycerides", match: ["triglyceride", "lipid"] },
          { id: "ca", text: "Calcium", match: ["calcium"] },
          { id: "lft", text: "Liver enzymes and bilirubin", match: ["alt", "ast", "liver enzyme", "lft", "liver", "bilirubin"] },
        ],
        explanation:
          "Gallstones are the most common cause of pancreatitis and change management, so every patient needs an ultrasound. Hypertriglyceridemia and hypercalcemia are treatable causes. Ultrasound is the right imaging for suspected biliary disease.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "acg-panc",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "List THREE elements of his initial ED management.",
        required: 3,
        accept: [
          { id: "fluid", text: "Moderate goal directed IV fluid with Ringer's lactate", match: ["ringer", "fluid", "crystalloid", "saline"] },
          { id: "analg", text: "Opioid analgesia", match: ["opioid", "analgesia", "hydromorphone", "morphine", "fentanyl"] },
          { id: "ae", text: "Antiemetic", match: ["antiemetic", "ondansetron", "metoclopramide"] },
          { id: "thi", text: "Thiamine", match: ["thiamine"] },
          { id: "wd", text: "Monitor and treat alcohol withdrawal", match: ["withdrawal", "ciwa", "benzodiazepine", "lorazepam", "diazepam"] },
          { id: "feed", text: "Early oral feeding as tolerated", match: ["feeding", "oral intake", "diet", "eat"] },
          { id: "noabx", text: "Avoid prophylactic antibiotics", match: ["avoid antibiotic", "no antibiotic", "no prophylactic antibiotic", "avoid prophylactic antibiotic", "withhold antibiotic"] },
        ],
        unacceptable: [{ text: "Prophylactic antibiotics", match: ["antibiotic", "meropenem", "imipenem"] }],
        explanation:
          "Early care is supportive. Moderate fluid is preferred over aggressive fluid, which causes overload without benefit. Prophylactic antibiotics do not help sterile pancreatitis. Alcohol use calls for thiamine and withdrawal monitoring.",
        keyFeature: { topic: "abdominal-pain", n: 2 },
        source: "acg-panc",
      },
    ],
    sources: [SRC.acgPanc],
    ...meta,
  },
  {
    id: "abdominal-pain-14",
    topic: "abdominal-pain",
    alsoTopics: ["analgesia-sedation"],
    title: "Man with sudden severe epigastric pain",
    stem:
      "A 68-year-old man had sudden severe epigastric pain 3 hours ago. It is now diffuse. He takes naproxen daily for knee osteoarthritis and smokes.\n\nVital signs: HR 116/min, BP 104/66 mmHg, RR 24/min, SpO2 96% on room air, temperature 37.6°C. Weight 84 kg.\n\nHe lies still. The abdomen is rigid with rebound tenderness.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "Name the fastest imaging test to support your leading diagnosis.",
        required: 1,
        accept: [
          { id: "cxr", text: "Upright chest x-ray for free air", match: ["upright chest", "erect chest", "chest x ray", "chest xray", "cxr", "chest radiograph"] },
          { id: "pocus", text: "Point-of-care ultrasound for free air", match: ["pocus", "ultrasound"] },
        ],
        explanation:
          "Sudden pain, NSAID use and a rigid abdomen point to a perforated ulcer. An upright chest radiograph shows free air in most cases and can be done at the bedside. A negative film does not exclude perforation.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "wses-pud",
      },
      {
        id: "q2",
        kind: "short",
        update: "The upright chest x-ray shows free air under the right hemidiaphragm.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "surg", text: "General surgery consultation now", match: ["surgery", "surgeon", "surgical", "operating room"] },
          { id: "abx", text: "Broad spectrum IV antibiotics", match: ["antibiotic", "piperacillin", "ceftriaxone", "metronidazole", "pip tazo"] },
          { id: "ppi", text: "IV proton pump inhibitor such as pantoprazole", match: ["ppi", "pantoprazole", "proton pump", "esomeprazole"] },
          { id: "fluid", text: "IV fluid resuscitation", match: ["fluid", "crystalloid", "ringer", "saline", "bolus"] },
          { id: "ng", text: "NPO and nasogastric tube", match: ["npo", "nothing by mouth", "nasogastric", "ng tube", "ngt"] },
          { id: "analg", text: "Opioid analgesia", match: ["analgesia", "opioid", "morphine", "hydromorphone", "fentanyl"] },
        ],
        explanation:
          "Free air with peritonitis is a surgical emergency. Resuscitation, antibiotics and acid suppression run alongside the call to surgery. Delay to source control increases mortality.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "wses-pud",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "The surgical resident asks for a CT abdomen before coming to see him. Which is the most appropriate response? Select one.",
        options: [
          "Ask the surgeon to assess him now, because free air with peritonitis needs operative management without further imaging",
          "Agree and order CT before surgical assessment",
          "Order an abdominal ultrasound first",
          "Repeat the chest x-ray in 6 hours",
          "Arrange urgent endoscopy",
        ],
        correct: 0,
        explanation:
          "The diagnosis and the need for surgery are already clear. CT may help the surgeon plan, but it must not delay surgical assessment. Endoscopy is contraindicated with a perforation.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "wses-pud",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which analgesic is most appropriate? Select one.",
        options: [
          "Hydromorphone 0.5 mg IV, titrated to effect",
          "Ketorolac 30 mg IV",
          "Withhold analgesia until the surgeon examines him",
          "Acetaminophen 1 g PO only",
          "Naproxen 500 mg PO",
        ],
        correct: 0,
        explanation:
          "Titrated IV opioid is safe and does not mask surgical findings. NSAIDs worsen ulcer disease and bleeding risk. Oral drugs are inappropriate in a patient who needs surgery.",
        keyFeature: { topic: "analgesia-sedation", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [SRC.wsesPud, SRC.tintinalli],
    ...meta,
  },
  {
    id: "abdominal-pain-15",
    topic: "abdominal-pain",
    title: "Older man with distension and vomiting",
    stem:
      "An 84-year-old man has 2 days of crampy abdominal pain, distension and vomiting. He has not passed flatus for 24 hours. He had an open colectomy 10 years ago. He takes metoprolol.\n\nVital signs: HR 84/min, BP 128/70 mmHg, RR 20/min, SpO2 95% on room air, temperature 37.1°C.\n\nThe abdomen is distended and tympanic with mild diffuse tenderness and no rebound. WBC is 9.8 x 10^9/L.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "A student notes the normal temperature, heart rate and WBC and suggests constipation. List THREE reasons older adults with serious abdominal disease may lack these findings.",
        required: 3,
        accept: [
          { id: "fev", text: "Blunted fever response", match: ["fever", "temperature", "thermoregulation", "afebrile"] },
          { id: "bb", text: "Beta blockers blunt tachycardia", match: ["beta blocker", "metoprolol", "heart rate", "tachycardia"] },
          { id: "wbc", text: "Blunted leukocyte response", match: ["wbc", "white", "leukocytosis", "leukocyte"] },
          { id: "perit", text: "Fewer peritoneal signs because of weaker abdominal wall response", match: ["peritoneal", "guarding", "rigidity", "abdominal wall", "peritonism"] },
          { id: "cog", text: "Cognitive impairment limits the history", match: ["cognitive", "dementia", "delirium", "historian", "communicate"] },
          { id: "drug", text: "Steroids or analgesics mask inflammation", match: ["steroid", "nsaid", "analgesic", "prednisone"] },
        ],
        explanation:
          "Older adults often lack fever, tachycardia, leukocytosis and peritonism even with surgical disease. Normal values in them are weak evidence. Their mortality from missed abdominal disease is high.",
        keyFeature: { topic: "abdominal-pain", n: 6 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "Name the most appropriate imaging test.",
        required: 1,
        accept: [{ id: "ct", text: "CT abdomen and pelvis with IV contrast", match: ["ct", "computed tomography"] }],
        explanation:
          "CT with IV contrast confirms obstruction, finds the transition point and shows signs of strangulation. Oral contrast is not required. Plain films cannot exclude ischemia.",
        keyFeature: { topic: "abdominal-pain", n: 5 },
        source: "wses-sbo",
      },
      {
        id: "q3",
        kind: "short",
        update: "CT shows a closed loop small bowel obstruction with reduced bowel wall enhancement and mesenteric fluid. Lactate is now 3.8 mmol/L.",
        prompt: "List THREE immediate management steps.",
        required: 3,
        accept: [
          { id: "surg", text: "Urgent general surgery for the operating room", match: ["surgery", "surgeon", "surgical", "operating room"] },
          { id: "ng", text: "Nasogastric decompression", match: ["nasogastric", "ng tube", "ngt", "decompression"] },
          { id: "fluid", text: "IV fluid resuscitation", match: ["fluid", "crystalloid", "ringer", "saline"] },
          { id: "abx", text: "IV antibiotics", match: ["antibiotic", "piperacillin", "ceftriaxone", "metronidazole"] },
          { id: "analg", text: "Analgesia and antiemetic", match: ["analgesia", "opioid", "hydromorphone", "morphine", "antiemetic", "ondansetron"] },
          { id: "goc", text: "Goals of care discussion", match: ["goals of care", "code status", "advance directive"] },
          { id: "foley", text: "Urinary catheter to monitor output", match: ["foley", "urine output", "urinary catheter"] },
        ],
        unacceptable: [
          { text: "Water soluble contrast challenge and observation", match: ["gastrografin", "water soluble", "contrast challenge", "conservative"], dangerous: true },
        ],
        explanation:
          "Closed loop obstruction with signs of ischemia needs surgery now. Conservative management suits simple adhesive obstruction only. Delay risks necrosis and perforation.",
        keyFeature: { topic: "abdominal-pain", n: 4 },
        source: "wses-sbo",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "His lactate on arrival 3 hours earlier was 1.6 mmol/L. List TWO reasons that normal value should not have been used to exclude ischemia.",
        required: 2,
        accept: [
          { id: "sens", text: "Lactate is insensitive in early ischemia", match: ["insensitive", "low sensitivity", "not sensitive", "early"] },
          { id: "liver", text: "The liver clears lactate from the portal circulation", match: ["liver", "hepatic", "clearance", "portal"] },
          { id: "trend", text: "It may rise later, so trends matter", match: ["serial", "repeat", "repeated", "trend", "rise", "later"] },
          { id: "clin", text: "Clinical and CT findings outweigh a single lab value", match: ["clinical", "ct finding", "imaging", "exam", "single"] },
        ],
        explanation:
          "No single laboratory test excludes bowel ischemia. Lactate often stays normal until ischemia is advanced. A closed loop can strangulate with little systemic signal.",
        keyFeature: { topic: "abdominal-pain", n: 6 },
        source: "wses-sbo",
      },
    ],
    sources: [SRC.rosen, SRC.wsesSbo],
    ...meta,
  },
];
