// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const meta = { reviewed: true, author: "Draft for review by Arjan Dhoot, MD", version: 1 };

const SRC: Record<string, Source> = {
  rnao: { id: "rnao-ipv", citation: "Registered Nurses' Association of Ontario. Woman abuse: screening, identification and initial response. Nursing best practice guideline. 2005, with 2012 supplement." },
  who: { id: "who-ipv", citation: "World Health Organization. Responding to intimate partner violence and sexual violence against women. WHO clinical and policy guidelines. 2013." },
  sogcIpv: { id: "sogc-ipv", citation: "Cherniak D, Grant L, Mason R, and colleagues. Intimate partner violence consensus statement. SOGC Clinical Practice Guideline No. 157. J Obstet Gynaecol Can. 2005." },
  sogcTrauma: { id: "sogc-trauma", citation: "Jain V, Chari R, and colleagues. Guidelines for the management of a pregnant trauma patient. SOGC Clinical Practice Guideline No. 325. J Obstet Gynaecol Can. 2015." },
  sogcRh: { id: "sogc-rh", citation: "Society of Obstetricians and Gynaecologists of Canada. Guideline No. 448. Prevention of Rh D alloimmunization. 2024." },
  cyfsa: { id: "cyfsa", citation: "Ontario. Child, Youth and Family Services Act, 2017. Duty to report a child in need of protection." },
  fltca: { id: "fltca", citation: "Ontario. Fixing Long-Term Care Act, 2021. Duty to report abuse of a resident to the Director." },
  aapAbuse: { id: "aap-abuse", citation: "Christian CW, Committee on Child Abuse and Neglect, American Academy of Pediatrics. The evaluation of suspected child physical abuse. Pediatrics. 2015." },
  ten4: { id: "ten4", citation: "Pierce MC and colleagues. Validation of a clinical decision rule to predict abuse in young children based on bruising characteristics. JAMA Netw Open. 2021." },
  strang: { id: "strangulation", citation: "Training Institute on Strangulation Prevention. Recommendations for the medical/radiographic evaluation of acute adult/adolescent non/near fatal strangulation. 2022." },
  danger: { id: "danger", citation: "Campbell JC, Webster DW, Glass N. The Danger Assessment: validation of a lethality risk assessment instrument for intimate partner femicide. J Interpers Violence. 2009." },
  easi: { id: "easi", citation: "Yaffe MJ, Wolfson C, Lithwick M, Weiss D. Development and validation of a tool to improve physician identification of elder abuse: the Elder Abuse Suspicion Index (EASI). J Elder Abuse Negl. 2008." },
  hivPep: { id: "hiv-pep", citation: "Tan DHS and colleagues. Canadian guideline on HIV pre- and postexposure prophylaxis. 2025 update. CMAJ. 2025.", url: "https://www.cmaj.ca/content/197/41/E1374" },
  sadv: { id: "sadv", citation: "Ontario Network of Sexual Assault/Domestic Violence Treatment Centres. Standards of care. 2nd ed. 2019." },
  rnaoSuicide: { id: "rnao-suicide", citation: "Registered Nurses' Association of Ontario. Assessment and care of adults at risk for suicidal ideation and behaviour. Nursing best practice guideline. 2009." },
  aba: { id: "aba", citation: "American Burn Association and American College of Surgeons Committee on Trauma. Burn center referral criteria. In: Resources for Optimal Care of the Injured Patient. 2006." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. 10th ed. 2023. Intimate partner violence and abuse chapter." },
};

export const ABUSE_DOMESTIC: Samp[] = [
  {
    id: "abuse-domestic-01",
    topic: "abuse-domestic",
    alsoTopics: ["multiple-trauma"],
    title: "Pregnant woman with abdominal pain after a fall",
    stem:
      "A 24-year-old woman, G2P1 at 22 weeks, presents at 23:00 with lower abdominal pain. She says she tripped on the stairs 2 days ago. This is her fourth ED visit in 3 months, previously for headache, urinary symptoms and back pain. She has missed her last two prenatal appointments.\n\nHer partner stays at the bedside, answers most questions for her and declines to step out.\n\nThe fetal heart rate is 148/minute.\n\nThere are bruises on her left upper arm and right breast.",
    vitals: { temperature: "36.8°C", pulse: "96/minute", resp: "16/minute", bp: "116/70 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features of this presentation raise concern for intimate partner violence?",
        required: 3,
        accept: [
          { id: "freq", text: "Repeated ED visits with vague complaints", match: ["repeat", "repeated", "frequent", "multiple visit", "recurrent", "fourth visit", "4 visit", "vague"] },
          { id: "delay", text: "Delayed presentation after injury", match: ["delay", "delayed", "late presentation", "2 day", "two day"] },
          { id: "prenatal", text: "Missed prenatal care", match: ["prenatal", "antenatal", "missed appointment"] },
          { id: "bruise", text: "Bruises on breast and arm that a fall does not explain", match: ["bruise", "bruising", "breast", "arm", "inconsistent", "mechanism"] },
          { id: "preg", text: "Pregnancy is a period of increased risk", match: ["pregnancy", "pregnant"] },
          { id: "ctrl", text: "Partner answers for her and will not leave", match: ["partner", "controlling", "speaks for", "answer for", "will not leave", "refuse to leave"] },
        ],
        explanation:
          "Pregnancy is a recognized period of onset or escalation of partner violence. Frequent visits, missed prenatal care, delay and injuries to the breast and abdomen are quiet clues. A controlling partner who will not leave is a red flag.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "sogc-ipv",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What steps make disclosure safer and more likely?",
        required: 2,
        accept: [
          { id: "alone", text: "Speak with her alone, away from the partner", match: ["alone", "without partner", "without the partner", "separate", "away from partner", "partner out", "away from the partner"] },
          { id: "priv", text: "Use a private room", match: ["private", "privacy", "quiet room"] },
          { id: "direct", text: "Ask directly and without judgment, as a routine question", match: ["direct", "directly", "nonjudgmental", "non judgmental", "without judgment", "without judgement", "routine", "normalize"] },
          { id: "conf", text: "Explain confidentiality and its limits", match: ["confidential", "confidentiality"] },
          { id: "interp", text: "Use a professional interpreter if needed", match: ["interpreter"] },
          { id: "pretext", text: "Use a pretext such as an ultrasound or urine sample to separate them", match: ["pretext", "ultrasound", "urine sample", "bathroom", "x ray"] },
        ],
        unacceptable: [
          { text: "Ask about abuse in front of the partner", match: ["in front of", "with partner present", "partner present", "confront"], dangerous: true },
        ],
        explanation:
          "Disclosure is unlikely and unsafe with the partner present. Asking in front of a possible abuser can provoke retaliation. A private, direct and nonjudgmental question, framed as routine, is most effective.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "rnao-ipv",
      },
      {
        id: "q3",
        kind: "single",
        update: "Alone with you, she says her partner pushed her down the stairs and kicked her abdomen 2 days ago.",
        prompt: "Which of the following is the most appropriate obstetric assessment for her now?",
        options: [
          "CT of the abdomen to assess the placenta",
          "Fetal Doppler only, then discharge",
          "Fetal monitoring, obstetric ultrasound and Rh status",
          "Kleihauer-Betke test as the only obstetric assessment",
          "No fetal assessment 2 days after the injury",
        ],
        correct: 2,
        explanation:
          "Direct abdominal trauma in pregnancy risks abruption, even when delayed. Obstetric assessment includes fetal monitoring, ultrasound and Rh status. A Kleihauer-Betke test alone does not exclude abruption.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "sogc-trauma",
      },
      {
        id: "q4",
        kind: "short",
        update: "She wants help but is not ready to leave her partner.",
        prompt: "What team members or services should you involve?",
        required: 3,
        accept: [
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "dv", text: "Hospital domestic violence program", match: ["domestic violence", "dv program", "sadv", "treatment centre", "ipv program"] },
          { id: "ob", text: "Obstetrics or her prenatal care provider", match: ["obstetric", "obstetrician", "prenatal", "midwife", "family physician"] },
          { id: "shelter", text: "Women's shelter or community violence services", match: ["shelter", "transition house", "community", "helpline", "crisis line", "assaulted women"] },
          { id: "couns", text: "Abuse counsellor", match: ["counsellor", "counselor", "counselling", "counseling"] },
          { id: "police", text: "Police, if she chooses", match: ["police"] },
        ],
        explanation:
          "A team approach supports her whether or not she leaves. Social work and domestic violence services can do safety planning. Her prenatal provider needs to be part of ongoing care.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "sogc-ipv",
      },
    ],
    sources: [SRC.sogcIpv, SRC.rnao, SRC.sogcTrauma],
    ...meta,
  },
  {
    id: "abuse-domestic-02",
    topic: "abuse-domestic",
    title: "Man with forearm pain after a fall",
    stem:
      "A 31-year-old man has right forearm pain 3 days after falling down the stairs. He had two previous ED visits this year, for a rib contusion and a lip laceration. He lives with his male partner, who is in the waiting room.\n\nThe mid ulna is tender. There are faded yellow bruises on the back of his neck. An x-ray shows a nondisplaced mid shaft ulnar fracture.",
    vitals: { temperature: "36.7°C", pulse: "88/minute", resp: "16/minute", bp: "132/80 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features suggest this injury may have been inflicted?",
        required: 3,
        accept: [
          { id: "delay", text: "Delayed presentation", match: ["delay", "delayed", "3 day", "three day", "late"] },
          { id: "def", text: "Isolated ulnar shaft fracture is a defensive injury", match: ["defensive", "nightstick", "parry", "raised forearm", "ulnar shaft", "ulna"] },
          { id: "mech", text: "Injury does not fit a fall down stairs", match: ["inconsistent", "mechanism", "does not fit", "not consistent"] },
          { id: "repeat", text: "Repeated visits for injuries", match: ["repeat", "repeated", "recurrent", "prior visit", "previous visit", "multiple visit", "frequent", "two previous"] },
          { id: "age", text: "Injuries of different ages", match: ["different age", "healing", "different stage", "old bruise", "older bruise", "faded"] },
          { id: "neck", text: "Bruising on the neck", match: ["neck"] },
        ],
        explanation:
          "A fracture of the ulnar shaft usually results from a direct blow to a raised forearm, not a fall. Delay, repeated injury visits and bruises of different ages add to concern. Men in same sex relationships experience partner violence at similar or higher rates and are rarely asked.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following approaches to asking him about abuse is most appropriate?",
        options: [
          "Ask his partner to come in and explain the injury",
          "Ask only if he is in a heterosexual relationship",
          "Ask privately and directly, as with every patient",
          "Report to police first and ask afterward",
          "Wait for him to raise the topic himself",
        ],
        correct: 2,
        explanation:
          "Partner violence occurs in all genders and relationships. Ask privately and directly, using the same questions asked of all patients, regardless of gender or relationship. A routine question avoids assumptions and signals that disclosure is safe. Involving the partner can place him at risk.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "rnao-ipv",
      },
      {
        id: "q3",
        kind: "short",
        update: "He discloses that his partner has hit him several times. He worries that staff will not take him seriously.",
        prompt: "What services or team members should you involve?",
        required: 2,
        accept: [
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "dv", text: "Domestic violence counsellor or program", match: ["domestic violence", "counsellor", "counselor", "dv program", "counselling"] },
          { id: "lgbt", text: "2SLGBTQI+ community support agency", match: ["lgbt", "lgbtq", "2slgbtqi", "2slgbtq", "queer", "gay"] },
          { id: "crisis", text: "Crisis line", match: ["crisis", "helpline", "hotline"] },
          { id: "fp", text: "Family physician follow-up", match: ["family physician", "family doctor", "primary care"] },
          { id: "police", text: "Police, if he chooses", match: ["police"] },
        ],
        explanation:
          "Male and 2SLGBTQI+ victims face extra barriers such as stigma and fear of not being believed. Social work and violence services that are inclusive of his identity improve engagement. Follow-up in primary care keeps the door open.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "who-ipv",
      },
      {
        id: "q4",
        kind: "single",
        update: "He declines police involvement. He is competent and has no children or dependants.",
        prompt: "Which of the following is the most appropriate action at this visit?",
        options: [
          "Call his partner to discuss the injuries",
          "Keep him in hospital until he agrees to report",
          "Report him to an adult protection agency without his consent",
          "Report the assault to police without his consent",
          "Respect wishes, document, resources, safety plan, follow-up",
        ],
        correct: 4,
        explanation:
          "Respect his decision, document carefully, provide resources and a safety plan, and offer follow-up. Canadian provinces, Ontario included, do not require reporting of partner violence against a competent adult unless another reporting law applies, such as gunshot wound reporting or a child at risk. Reporting against his wishes can increase danger and break trust. Careful documentation helps him if he chooses to act later.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "rnao-ipv",
      },
    ],
    sources: [SRC.rosen, SRC.rnao, SRC.who],
    ...meta,
  },
  {
    id: "abuse-domestic-03",
    topic: "abuse-domestic",
    alsoTopics: ["multiple-trauma"],
    title: "Woman with a sore throat after an argument",
    stem:
      "A 29-year-old woman arrives at 03:00. Five hours ago her former partner grabbed her by the neck during an argument. She briefly saw stars and wet herself. She now has a sore throat, a hoarse voice and pain on swallowing.\n\nGCS is 15.\n\nThere is faint linear redness on the front of the neck and there are petechiae on both eyelids. The neurologic exam is normal.",
    vitals: { temperature: "36.9°C", pulse: "102/minute", resp: "18/minute", bp: "138/86 mmHg", o2sat: "98% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What findings indicate a high risk strangulation injury?",
        required: 3,
        accept: [
          { id: "loc", text: "Near or complete loss of consciousness", match: ["loss of consciousness", "loc", "saw star", "syncope", "passed out", "near syncope"] },
          { id: "inc", text: "Urinary incontinence", match: ["incontinence", "wet", "urinary"] },
          { id: "voice", text: "Hoarse voice", match: ["hoarse", "voice", "dysphonia"] },
          { id: "swal", text: "Painful or difficult swallowing", match: ["swallow", "swallowing", "dysphagia", "odynophagia"] },
          { id: "pet", text: "Petechiae", match: ["petechiae", "petechial"] },
          { id: "neck", text: "Visible neck marks", match: ["neck mark", "redness", "erythema", "bruise", "abrasion"] },
        ],
        explanation:
          "Loss of consciousness, incontinence, voice change, swallowing pain and petechiae indicate significant compression of the airway or vessels. Many strangled patients have few external marks. These findings demand investigation and observation.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "strangulation",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following investigations is most appropriate for her now?",
        options: [
          "Carotid Doppler ultrasound",
          "CT angiography of the head and neck",
          "Non-contrast CT head only",
          "Soft tissue neck radiograph",
          "No imaging with a normal neurologic exam",
        ],
        correct: 1,
        explanation:
          "Strangulation can cause carotid or vertebral dissection with delayed stroke, and laryngeal injury. CT angiography of the head and neck is recommended when high risk features are present. A normal neurologic exam does not exclude dissection.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "strangulation",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "What elements should you include when documenting her injuries?",
        required: 2,
        accept: [
          { id: "map", text: "Body diagram marking each injury", match: ["body map", "diagram", "body chart", "drawing"] },
          { id: "photo", text: "Photographs with her consent", match: ["photo", "photograph", "photography"] },
          { id: "quote", text: "Her own words in quotation marks", match: ["quote", "quotation", "own word", "exact word", "verbatim"] },
          { id: "meas", text: "Size, colour and location of each injury", match: ["measure", "measurement", "size", "colour", "color", "location"] },
          { id: "time", text: "Timing of the assault and of each symptom", match: ["time", "timing", "timeline"] },
        ],
        explanation:
          "Objective, detailed records confirm the full extent of injury and support her if she seeks legal protection later. Quote her words rather than summarize them. Avoid judgmental terms such as alleged or claims.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "strangulation",
      },
      {
        id: "q4",
        kind: "short",
        update: "CT angiography is normal. She plans to stay at her sister's tonight.",
        prompt: "What factors increase her risk of being killed by this partner?",
        required: 3,
        accept: [
          { id: "strang", text: "Previous strangulation", match: ["strangulation", "choking", "strangled", "choked"] },
          { id: "sep", text: "Recent separation", match: ["separation", "separated", "leaving", "former partner", "ex partner", "breakup"] },
          { id: "gun", text: "Access to a firearm", match: ["firearm", "gun", "weapon"] },
          { id: "threat", text: "Threats to kill", match: ["threat", "threaten", "threatened"] },
          { id: "esc", text: "Escalating frequency or severity of violence", match: ["escalation", "escalating", "worsening", "increasing"] },
          { id: "stalk", text: "Stalking or extreme jealousy", match: ["stalking", "jealous", "jealousy"] },
          { id: "preg", text: "Pregnancy", match: ["pregnancy", "pregnant"] },
          { id: "sub", text: "Partner substance use or unemployment", match: ["substance", "alcohol", "drug", "unemployed", "unemployment"] },
          { id: "sex", text: "Forced sex", match: ["forced sex", "sexual assault", "sexual violence"] },
        ],
        explanation:
          "Nonfatal strangulation is one of the strongest predictors of later intimate partner homicide. Recent separation and firearm access also sharply raise risk. Risk assessment guides the safety plan and disposition.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "danger",
      },
    ],
    sources: [SRC.strang, SRC.danger],
    ...meta,
  },
  {
    id: "abuse-domestic-04",
    topic: "abuse-domestic",
    title: "Older woman brought in by her son",
    stem:
      "An 86-year-old woman with moderate dementia is brought in by her son, who lives with her and is her caregiver. He says she is more tired than usual, bruises easily and refuses food. He manages her finances. He is impatient and wants to leave soon.\n\nHer chart lists a weight of 52 kg six months ago.\n\nShe has dry mucous membranes, a stage 3 sacral pressure injury and bruises of different colours on both upper arms.",
    vitals: { temperature: "36.2°C", pulse: "104/minute", resp: "18/minute", bp: "102/58 mmHg", o2sat: "96% on room air", weight: "44 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What findings suggest elder abuse or neglect?",
        required: 3,
        accept: [
          { id: "wt", text: "Weight loss and malnutrition", match: ["weight loss", "malnutrition", "malnourished", "8 kg"] },
          { id: "dehyd", text: "Dehydration", match: ["dehydration", "dehydrated", "dry"] },
          { id: "pi", text: "Pressure injury", match: ["pressure", "ulcer", "bedsore", "decubitus"] },
          { id: "grip", text: "Bilateral upper arm bruises in a grip pattern", match: ["bruise", "bruising", "grip", "upper arm"] },
          { id: "ages", text: "Bruises of different ages", match: ["different colour", "different color", "different age", "varying"] },
          { id: "cg", text: "Impatient, dependent caregiver who wants to leave", match: ["caregiver", "son", "impatient"] },
          { id: "fin", text: "Caregiver controls her finances", match: ["financial", "finance", "money"] },
        ],
        explanation:
          "Neglect is the most common form of elder abuse. Weight loss, dehydration and pressure injuries in a dependent person suggest inadequate care. Grip bruises on both arms and a stressed caregiver add concern. Screening tools such as the EASI help structure the assessment.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "easi",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What investigations would identify injuries or neglect?",
        required: 3,
        accept: [
          { id: "cbc", text: "CBC", match: ["cbc", "hemoglobin", "complete blood count"] },
          { id: "lytes", text: "Electrolytes, urea and creatinine", match: ["electrolyte", "creatinine", "urea", "bun", "renal function", "sodium"] },
          { id: "alb", text: "Albumin and nutritional markers", match: ["albumin", "nutrition", "nutritional", "prealbumin"] },
          { id: "coag", text: "INR and platelets to assess easy bruising", match: ["inr", "coagulation", "platelet", "ptt"] },
          { id: "xr", text: "X-rays of tender or deformed areas", match: ["x ray", "xray", "radiograph", "skeletal survey"] },
          { id: "cth", text: "CT head if there are signs of head injury", match: ["ct head", "head ct"] },
          { id: "ck", text: "Creatine kinase", match: ["ck", "creatine kinase"] },
          { id: "levels", text: "Drug levels for prescribed medications", match: ["drug level", "medication level", "digoxin", "level"] },
          { id: "chart", text: "Review of old records and prior visits", match: ["old chart", "old record", "prior record", "previous record", "chart review", "prior visit", "previous visit"] },
        ],
        explanation:
          "Laboratory tests document dehydration and malnutrition and rule out medical causes of bruising. Imaging finds occult fractures in patients who cannot report pain. Old records reveal patterns of injury and weight loss.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "easi",
      },
      {
        id: "q3",
        kind: "single",
        update: "She cannot understand her situation or the risks of going home. Her son insists on taking her home now.",
        prompt: "Which of the following is the most appropriate disposition for her?",
        options: [
          "Admit, involve social work, address decision maker concerns",
          "Ask the son to sign a promise of better care",
          "Call police to arrest the son before any further assessment",
          "Discharge home with a home care referral",
          "Discharge home with her son as her caregiver",
        ],
        correct: 0,
        explanation:
          "She is medically unwell and may be unsafe at home, so admit her for safety, involve social work, and address concerns about her substitute decision maker. When a substitute decision maker may not be acting in her best interests, the hospital can involve its legal and social work teams and the provincial public guardian or adult protection service, such as the Office of the Public Guardian and Trustee in Ontario. Discharge to the suspected source of neglect is unsafe.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "What team members or agencies should you involve?",
        required: 2,
        accept: [
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "ger", text: "Geriatric medicine or geriatric emergency nurse", match: ["geriatric", "geriatrician", "gem nurse", "geriatrics"] },
          { id: "pgt", text: "Public guardian or provincial adult protection service", match: ["public guardian", "public trustee", "pgt", "opgt", "adult protection", "adult protective"] },
          { id: "home", text: "Home and community care services", match: ["home care", "community care", "hccss"] },
          { id: "police", text: "Police if a crime is suspected", match: ["police"] },
          { id: "elder", text: "Elder abuse resource or consultant", match: ["elder abuse"] },
          { id: "fp", text: "Her family physician", match: ["family physician", "family doctor", "primary care"] },
          { id: "cap", text: "Capacity assessor", match: ["capacity"] },
        ],
        explanation:
          "Elder abuse is best managed by a team. Social work and geriatrics assess needs and safety. Legal and community agencies address substitute decision maker concerns, finances and ongoing care.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "easi",
      },
    ],
    sources: [SRC.easi, SRC.rosen],
    ...meta,
  },
  {
    id: "abuse-domestic-05",
    topic: "abuse-domestic",
    title: "Long-term care resident with leg pain",
    stem:
      "A 90-year-old woman is sent from a long-term care home in Ontario because her right leg is shortened and externally rotated. She has severe dementia and is nonverbal. Staff do not know of a fall.\n\nAn x-ray shows a right femoral neck fracture. You also find bruises on both inner thighs and a small perineal skin tear.",
    vitals: { temperature: "37.0°C", pulse: "96/minute", resp: "18/minute", bp: "146/80 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following reporting obligations applies to you in this case?",
        options: [
          "Report immediately to the long-term care Director",
          "Report only after abuse is confirmed",
          "Report only if the family consents",
          "Report to the children's aid society",
          "No personal duty when the care home itself must report",
        ],
        correct: 0,
        explanation:
          "In Ontario, anyone with reasonable grounds to suspect abuse of a long-term care resident that caused harm or a risk of harm must report it immediately to the Director under the Fixing Long-Term Care Act, 2021. Other provinces have similar protection for persons in care laws. Certainty is not required. The duty is personal and is not met by assuming the home will report.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "fltca",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What steps would identify all of her injuries?",
        required: 3,
        accept: [
          { id: "skin", text: "Complete head to toe skin examination", match: ["skin", "head to toe", "full exam", "complete exam", "undress", "full body"] },
          { id: "xr", text: "X-rays of other tender or deformed areas", match: ["skeletal", "x ray", "xray", "radiograph"] },
          { id: "ct", text: "CT head", match: ["ct head", "head ct"] },
          { id: "gen", text: "Anogenital examination by a trained examiner", match: ["genital", "anogenital", "perineal", "pelvic"] },
          { id: "chart", text: "Review of old records for prior injuries", match: ["old record", "prior record", "chart", "previous", "prior injury"] },
          { id: "labs", text: "Labs for dehydration and medication levels", match: ["drug level", "cbc", "electrolyte", "medication level"] },
        ],
        explanation:
          "An unexplained fracture plus inner thigh bruising and perineal injury in a nonverbal resident raises concern for physical and sexual abuse. A complete survey finds other injuries that she cannot report. Old records may show a pattern.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "What team members or services should you involve?",
        required: 2,
        accept: [
          { id: "sadv", text: "Sexual assault nurse examiner or hospital sexual assault program", match: ["sexual assault", "nurse examiner", "forensic", "sane", "sadv", "domestic violence"] },
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "ger", text: "Geriatric medicine", match: ["geriatric", "geriatrician", "geriatrics"] },
          { id: "police", text: "Police", match: ["police"] },
          { id: "sdm", text: "Her substitute decision maker", match: ["substitute decision", "sdm", "power of attorney"] },
        ],
        explanation:
          "Suspected sexual assault of a resident needs a trained forensic examiner and social work. Police often become involved after a report. Her substitute decision maker must be informed and consent to examination on her behalf.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "sadv",
      },
    ],
    sources: [SRC.fltca, SRC.rosen, SRC.sadv],
    ...meta,
  },
  {
    id: "abuse-domestic-06",
    topic: "abuse-domestic",
    title: "Irritable infant after a short fall",
    stem:
      "A 4-month-old girl is brought in by her father for fussiness since yesterday. He says she rolled off the couch onto carpet. She was born at term and has been well.\n\nShe is irritable. There is a bruise on the left ear and a small bruise on the right cheek. The anterior fontanelle is soft. No other injuries are visible.",
    vitals: { temperature: "36.9°C", pulse: "156/minute", resp: "40/minute", o2sat: "99% on room air", weight: "6.2 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features raise concern for physical abuse?",
        required: 3,
        accept: [
          { id: "age", text: "Any bruise in an infant under 5 months who is not yet mobile", match: ["non mobile", "nonmobile", "not mobile", "not cruising", "under 5 month", "age", "infant"] },
          { id: "ear", text: "Bruise on the ear", match: ["ear"] },
          { id: "cheek", text: "Bruise on the cheek", match: ["cheek", "face", "facial"] },
          { id: "mech", text: "A short fall onto carpet does not explain the injuries", match: ["inconsistent", "mechanism", "short fall", "does not explain", "not explain"] },
          { id: "delay", text: "Delay in seeking care", match: ["delay", "delayed", "since yesterday"] },
          { id: "irr", text: "Irritability suggesting head injury", match: ["irritable", "irritability", "fussy", "head injury"] },
        ],
        explanation:
          "The TEN-4-FACESp rule flags bruising on the torso, ears or neck, facial bruises and any bruise in an infant under about 5 months. Short falls from furniture rarely cause bruising in these sites. Irritability may signal intracranial injury.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "ten4",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What investigations would find occult injuries?",
        required: 3,
        accept: [
          { id: "ss", text: "Skeletal survey", match: ["skeletal survey", "skeletal"] },
          { id: "neuro", text: "CT or MRI of the head", match: ["ct head", "head ct", "neuroimaging", "mri", "ct"] },
          { id: "eye", text: "Dilated fundoscopy by ophthalmology", match: ["fundoscopy", "funduscopy", "ophthalmology", "dilated eye", "retinal", "fundus"] },
          { id: "coag", text: "CBC and coagulation studies", match: ["cbc", "platelet", "coagulation", "inr", "ptt"] },
          { id: "liver", text: "Liver enzymes and lipase for occult abdominal injury", match: ["ast", "alt", "liver", "lipase", "transaminase"] },
          { id: "ua", text: "Urinalysis for blood", match: ["urinalysis", "urine"] },
        ],
        explanation:
          "Infants with suspected abuse need a skeletal survey and neuroimaging because occult fractures and intracranial bleeding are common and often silent. Fundoscopy looks for retinal hemorrhages. Screening labs detect abdominal injury and exclude bleeding disorders.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "aap-abuse",
      },
      {
        id: "q3",
        kind: "single",
        update: "The skeletal survey shows healing posterior rib fractures.",
        prompt: "Which of the following best describes your reporting obligation in this case?",
        options: [
          "Ask the social worker to decide whether to report",
          "Obtain the father's consent before reporting",
          "Report only once abuse is confirmed",
          "Report promptly to child protection services yourself",
          "Report to police only, not child protection",
        ],
        correct: 3,
        explanation:
          "Every province requires a physician with reasonable grounds to suspect a child is in need of protection to report promptly to child protection services. In Ontario the report goes directly to a children's aid society and cannot be delegated and does not require certainty or parental consent. Posterior rib fractures in an infant are highly specific for abuse.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "cyfsa",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "What team members or services should you involve?",
        required: 2,
        accept: [
          { id: "cpt", text: "Hospital child protection team", match: ["child protection", "scan", "suspected child abuse", "cpt", "child abuse team"] },
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "peds", text: "Pediatrics", match: ["pediatric", "paediatric", "pediatrician", "paediatrician", "pediatrics"] },
          { id: "oph", text: "Ophthalmology", match: ["ophthalmology", "ophthalmologist"] },
          { id: "cas", text: "Children's aid society or child protection services", match: ["children s aid", "cas", "child welfare", "child and family service", "child protective service"] },
          { id: "police", text: "Police", match: ["police"] },
          { id: "ns", text: "Neurosurgery if there is intracranial injury", match: ["neurosurgery", "neurosurgeon"] },
        ],
        explanation:
          "Suspected abuse in infants is managed by a specialized team. The child protection team coordinates the medical assessment, and the children's aid society assesses the safety of this infant and any siblings.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "aap-abuse",
      },
    ],
    sources: [SRC.ten4, SRC.aapAbuse, SRC.cyfsa],
    ...meta,
  },
  {
    id: "abuse-domestic-07",
    topic: "abuse-domestic",
    alsoTopics: ["infectious-diseases"],
    title: "Young woman after a party",
    stem:
      "A 22-year-old woman presents 20 hours after being sexually assaulted by an acquaintance at a party. There was vaginal penetration without a condom. She thinks she was drugged. Her last menstrual period was 2 weeks ago and she uses no contraception. She is unsure about involving police.\n\nThere are small abrasions on both wrists.",
    vitals: { temperature: "36.8°C", pulse: "92/minute", resp: "16/minute", bp: "118/72 mmHg", o2sat: "99% on room air", weight: "62 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What time-sensitive preventive treatments should you offer?",
        required: 3,
        accept: [
          { id: "ec", text: "Emergency contraception such as ulipristal or levonorgestrel", match: ["emergency contraception", "levonorgestrel", "ulipristal", "plan b", "ella", "copper iud", "iud", "morning after"] },
          { id: "hbv", text: "Hepatitis B vaccine", match: ["hepatitis b", "hbv", "hep b"] },
          { id: "hiv", text: "HIV post exposure prophylaxis", match: ["hiv", "pep", "post exposure", "postexposure"] },
          { id: "sti", text: "STI prophylaxis for gonorrhea, chlamydia and trichomonas", match: ["sti", "gonorrhea", "chlamydia", "ceftriaxone", "cefixime", "doxycycline", "azithromycin", "metronidazole", "sexually transmitted"] },
          { id: "tet", text: "Tetanus immunization if due", match: ["tetanus", "tdap", "td"] },
        ],
        explanation:
          "Emergency contraception and HIV prophylaxis lose effect with time. A copper IUD is the most effective option up to 7 days. Ulipristal works up to 120 hours and levonorgestrel is most effective within 72 hours. HIV PEP should start as soon as possible and within 72 hours when the exposure risk warrants it.",
        keyFeature: { topic: "infectious-diseases", n: 10 },
        source: "hiv-pep",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What points should you explain so that she can make informed choices about the forensic exam and police?",
        required: 2,
        accept: [
          { id: "opt", text: "Evidence collection is optional and she can consent to or decline each part", match: ["optional", "each part", "each step", "decline", "choose", "stop at any time"] },
          { id: "store", text: "Evidence can be collected and stored while she decides whether to report", match: ["store", "stored", "storage", "kept", "hold"] },
          { id: "police", text: "Reporting to police is her decision", match: ["her choice", "her decision", "police", "report"] },
          { id: "care", text: "Medical care does not depend on reporting", match: ["medical care", "without police", "regardless"] },
          { id: "tox", text: "Blood and urine can be collected for drug facilitated assault testing", match: ["toxicology", "drug screen", "drug facilitated", "urine sample", "blood sample"] },
        ],
        explanation:
          "A competent adult decides whether to report a sexual assault. Many programs can collect and store evidence for a period so she can decide later. Consent is sought for each part of the exam and she can stop at any time.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "sadv",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following should ideally provide her forensic and medical care?",
        options: [
          "An outpatient gynecology clinic in 2 weeks",
          "Her family physician at a visit next week",
          "Hospital sexual assault program with trained nurse examiners",
          "The ED physician alone, with no follow-up arranged",
          "The police forensic identification unit",
        ],
        correct: 2,
        explanation:
          "Specialized hospital sexual assault and domestic violence programs, with trained nurse examiners, provide trauma informed care, forensic collection, prophylaxis and follow-up. Delay loses evidence and the window for prophylaxis. Police do not provide medical care.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "sadv",
      },
      {
        id: "q4",
        kind: "short",
        prompt: "What follow-up arrangements should be made before she leaves?",
        required: 2,
        accept: [
          { id: "couns", text: "Counselling or mental health support", match: ["counselling", "counseling", "counsellor", "counselor", "mental health", "psychological", "therapy"] },
          { id: "test", text: "Repeat testing for STI, HIV and syphilis", match: ["repeat", "repeated", "testing", "serology", "syphilis", "retest"] },
          { id: "pep", text: "PEP follow-up with blood work and adherence checks", match: ["pep follow", "infectious disease", "id clinic", "hiv clinic", "adherence"] },
          { id: "preg", text: "Pregnancy test in 3 weeks", match: ["pregnancy test"] },
          { id: "sadv", text: "Follow-up visit with the sexual assault program", match: ["sexual assault", "sadv", "treatment centre", "program"] },
          { id: "fp", text: "Family physician follow-up", match: ["family physician", "family doctor", "primary care"] },
          { id: "crisis", text: "Crisis line", match: ["crisis", "helpline", "hotline"] },
        ],
        explanation:
          "Follow-up covers medical, laboratory and emotional needs. Survivors have high rates of post traumatic stress and benefit from early counselling. HIV PEP requires monitoring and adherence support.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "sadv",
      },
    ],
    sources: [SRC.hivPep, SRC.sadv],
    ...meta,
  },
  {
    id: "abuse-domestic-08",
    topic: "abuse-domestic",
    alsoTopics: ["suicide-risk"],
    title: "Young woman after an intentional ingestion",
    stem:
      "A 27-year-old woman is brought in by a friend 3 hours after taking twenty 400 mg ibuprofen tablets after a fight with her partner. She has been seen three times this year for injuries, a wrist sprain and a facial bruise after falls, and once for alcohol intoxication. She has a 3-year-old son at home.\n\nGCS is 15.\n\nThere are fingertip shaped bruises on her left upper arm.",
    vitals: { temperature: "36.7°C", pulse: "90/minute", resp: "16/minute", bp: "122/76 mmHg", o2sat: "99% on room air", weight: "60 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What suicide risk factors should you ask about specifically?",
        required: 3,
        accept: [
          { id: "intent", text: "Intent and plan, and whether she still wants to die", match: ["intent", "plan", "want to die", "ongoing ideation", "suicidal ideation"] },
          { id: "prior", text: "Previous attempts", match: ["previous attempt", "prior attempt", "past attempt", "history of attempt"] },
          { id: "hope", text: "Hopelessness", match: ["hopeless", "hopelessness"] },
          { id: "sub", text: "Substance use", match: ["alcohol", "substance", "drug use"] },
          { id: "means", text: "Access to lethal means", match: ["firearm", "means", "gun", "lethal", "medication at home"] },
          { id: "supp", text: "Social supports", match: ["support", "isolation", "isolated", "alone"] },
          { id: "psych", text: "Depression or other psychiatric illness", match: ["depression", "psychiatric", "mental illness", "mood"] },
          { id: "imp", text: "Impulsivity", match: ["impulsive", "impulsivity"] },
          { id: "ipv", text: "Ongoing abuse or relationship crisis", match: ["relationship", "violence", "abuse", "partner"] },
        ],
        explanation:
          "A structured assessment covers intent, prior attempts, hopelessness, substance use, supports and access to means. Partner violence is itself a strong risk factor for suicidal behaviour. The low toxicity of this ingestion does not measure her intent.",
        keyFeature: { topic: "suicide-risk", n: 1 },
        source: "rnao-suicide",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What features of her history suggest undisclosed intimate partner violence?",
        required: 2,
        accept: [
          { id: "rep", text: "Repeated visits for injuries", match: ["repeat", "repeated", "recurrent", "multiple", "three visit", "frequent", "prior injury", "previous injury"] },
          { id: "falls", text: "Injuries attributed to falls", match: ["fell", "fall", "implausible", "inconsistent"] },
          { id: "od", text: "Ingestion after a fight with her partner", match: ["fight", "conflict", "argument", "after overdose"] },
          { id: "sub", text: "Alcohol use", match: ["alcohol", "substance", "intoxication"] },
          { id: "grip", text: "Fingertip bruises on the arm", match: ["fingertip", "grip", "bruise", "arm"] },
        ],
        explanation:
          "Substance use, self-harm and frequent injury visits are recognized markers of hidden partner violence. Facial injuries and grip bruises are typical patterns. Each visit is a chance to ask.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "rnao-ipv",
      },
      {
        id: "q3",
        kind: "single",
        update: "She discloses that her partner assaults her every week, sometimes in front of her son.",
        prompt: "Which of the following is the most appropriate action regarding her son?",
        options: [
          "Advise her to report it herself within a week",
          "Report only if the child has physical injuries",
          "Report only with her written consent",
          "Report to child protection services and inform her",
          "No report when only the mother is assaulted",
        ],
        correct: 3,
        explanation:
          "Children exposed to partner violence are at risk of emotional and physical harm, and repeated exposure places her son at risk of harm. When there are reasonable grounds to suspect a child is in need of protection, the physician must report directly to child protection services, the children's aid society in Ontario. Telling her you are reporting, and framing the agency as a support, preserves trust and her safety.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "cyfsa",
      },
      {
        id: "q4",
        kind: "short",
        update: "Psychiatry assesses her suicide risk as low. She will stay with her sister tonight with her son.",
        prompt: "What are the elements of her discharge plan?",
        required: 3,
        accept: [
          { id: "fu", text: "Scheduled follow-up appointment", match: ["follow up", "appointment", "family physician", "scheduled"] },
          { id: "crisis", text: "Crisis line such as 9-8-8", match: ["988", "9 8 8", "crisis", "helpline", "hotline"] },
          { id: "sp", text: "Safety plan for partner violence", match: ["safety plan", "safety planning"] },
          { id: "means", text: "Limit access to medications and other means", match: ["means", "medication", "firearm", "lock"] },
          { id: "shelter", text: "Shelter or domestic violence services contact", match: ["shelter", "assaulted women", "domestic violence", "transition house"] },
          { id: "couns", text: "Counselling or social work", match: ["counselling", "counseling", "counsellor", "social work", "social worker"] },
          { id: "ret", text: "Clear return instructions", match: ["return"] },
        ],
        explanation:
          "A safe outpatient plan includes scheduled follow-up, crisis contacts and reduced access to means. Because the trigger was partner violence, the plan must also address her physical safety and that of her son.",
        keyFeature: { topic: "suicide-risk", n: 5 },
        source: "rnao-suicide",
      },
    ],
    sources: [SRC.rnaoSuicide, SRC.rnao, SRC.cyfsa],
    ...meta,
  },
  {
    id: "abuse-domestic-09",
    topic: "abuse-domestic",
    title: "Frequent visits for headache and insomnia",
    stem:
      "A 44-year-old woman presents for the eleventh time this year, with headaches, abdominal pain and poor sleep. Previous workups, including CT head and abdominal ultrasound, were normal. She speaks Punjabi and limited English. Her husband usually interprets for her.\n\nToday her vital signs and examination are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What presentations are associated with undisclosed intimate partner violence?",
        required: 3,
        accept: [
          { id: "ha", text: "Chronic headache", match: ["headache", "migraine"] },
          { id: "gi", text: "Chronic abdominal or gastrointestinal complaints", match: ["abdominal", "gastrointestinal", "ibs", "irritable bowel", "gi"] },
          { id: "mh", text: "Anxiety, depression, insomnia or PTSD", match: ["anxiety", "depression", "insomnia", "sleep", "ptsd", "post traumatic"] },
          { id: "sub", text: "Substance use", match: ["substance", "alcohol", "drug use"] },
          { id: "gyn", text: "Pelvic pain, STI or unintended pregnancy", match: ["pelvic pain", "sti", "sexually transmitted", "unintended pregnancy", "gynecologic", "gynaecologic"] },
          { id: "pain", text: "Chronic pain syndromes", match: ["chronic pain", "back pain", "fibromyalgia"] },
          { id: "freq", text: "Frequent ED visits", match: ["frequent", "repeat visit", "multiple visit"] },
          { id: "inj", text: "Unexplained injuries", match: ["injury", "injuries", "fracture", "bruise"] },
        ],
        explanation:
          "Many victims present with somatic and mental health complaints rather than injuries. Repeated visits with negative workups should prompt a private question about safety at home.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "who-ipv",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate way to communicate with her about safety at home?",
        options: [
          "Ask her 12-year-old son to interpret for her",
          "Ask her husband to interpret as he usually does",
          "Leave the safety question for her next visit",
          "Professional interpreter, with her husband out of the room",
          "Use gestures and simple English with her",
        ],
        correct: 3,
        explanation:
          "Family interpreters, especially a possible abuser or a child, prevent disclosure and may put her at risk. A professional medical interpreter, with her husband out of the room, preserves confidentiality and accuracy. Remote interpreting by phone or video is acceptable and fast.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "rnao-ipv",
      },
      {
        id: "q3",
        kind: "short",
        update: "Through the interpreter, she discloses years of physical abuse. She does not want police involved and wants to go home tonight. There are no children at home.",
        prompt: "What actions should you take before she leaves?",
        required: 3,
        accept: [
          { id: "sp", text: "Make a safety plan with her", match: ["safety plan", "safety planning"] },
          { id: "res", text: "Give resource numbers in a discreet way", match: ["resource", "helpline", "shelter", "phone number", "card", "hotline"] },
          { id: "doc", text: "Document her disclosure and findings objectively", match: ["document", "documentation", "record"] },
          { id: "fu", text: "Arrange follow-up", match: ["follow up", "appointment", "return"] },
          { id: "risk", text: "Assess danger, including weapons and escalation", match: ["risk assessment", "danger assessment", "lethality", "firearm", "weapon", "escalation", "danger"] },
          { id: "resp", text: "Respect her decision not to involve police", match: ["respect", "autonomy", "her decision", "her choice"] },
          { id: "sw", text: "Social work or counsellor involvement", match: ["social work", "social worker", "counsellor", "counselor", "counselling"] },
        ],
        explanation:
          "A competent adult may choose to return home. The role of the ED is to assess danger, make a safety plan, give resources safely and document well. Continued contact over time is what often leads to change.",
        keyFeature: { topic: "abuse-domestic", n: 6 },
        source: "rnao-ipv",
      },
    ],
    sources: [SRC.who, SRC.rnao],
    ...meta,
  },
  {
    id: "abuse-domestic-10",
    topic: "abuse-domestic",
    title: "Woman with facial injuries after walking into a door",
    stem:
      "A 35-year-old woman says she walked into a door last night.\n\nShe has left periorbital swelling, a subconjunctival hemorrhage and a tender nasal bridge. She reports right ear pain and muffled hearing. There is a bite mark on her right forearm. Visual acuity is 20/25 in both eyes. Pupils and eye movements are normal.",
    vitals: { temperature: "36.8°C", pulse: "90/minute", resp: "16/minute", bp: "128/80 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What findings are inconsistent with the stated mechanism?",
        required: 3,
        accept: [
          { id: "multi", text: "Injuries at several separate sites", match: ["multiple", "several", "more than one", "separate site", "both side", "bilateral"] },
          { id: "ear", text: "Ear injury with hearing loss, suggesting a slap", match: ["ear", "tympanic", "hearing", "slap"] },
          { id: "bite", text: "Bite mark", match: ["bite"] },
          { id: "fore", text: "Forearm injury in a defensive position", match: ["forearm", "defensive"] },
        ],
        explanation:
          "A single impact with a door cannot explain injuries to the eye, ear and forearm. Bite marks are never accidental. Head, face and neck injuries are the most common pattern in partner assault.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What examinations or investigations would identify all of her injuries?",
        required: 3,
        accept: [
          { id: "oto", text: "Otoscopy for tympanic membrane perforation", match: ["otoscopy", "otoscope", "ear exam", "tympanic"] },
          { id: "eye", text: "Full eye exam with slit lamp and fundoscopy", match: ["fundoscopy", "eye exam", "slit lamp", "ophthalmology", "ophthalmologic", "globe"] },
          { id: "ctf", text: "CT of the facial bones and orbits", match: ["ct facial", "ct face", "ct orbit", "facial bone", "ct maxillofacial", "facial ct"] },
          { id: "cth", text: "CT head if indicated", match: ["ct head", "head ct"] },
          { id: "skin", text: "Complete skin examination", match: ["skin", "full body", "head to toe", "undress", "full exam"] },
          { id: "chart", text: "Review of old records and imaging", match: ["old record", "prior record", "chart", "previous visit", "old imaging", "old x ray", "prior imaging"] },
          { id: "preg", text: "Pregnancy test", match: ["pregnancy", "hcg"] },
        ],
        explanation:
          "Assault victims often have injuries they do not mention or cannot see. Examine the ears, eyes and whole skin, and image the face. Old records may show healed fractures or earlier injuries.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "You are alone with her.",
        prompt: "Which of the following is the most appropriate way to open the conversation?",
        options: [
          "I am required to call police about injuries like these",
          "If your partner did this, you have to leave him",
          "Violence at home is common. Has someone hurt you?",
          "You must tell me the truth so I can help",
          "Your injuries do not match your story. Who did this?",
        ],
        correct: 2,
        explanation:
          "Saying that violence at home is common and that you ask everyone about it normalizes the question. Asking directly, without accusation, makes disclosure easier. Confrontation and ultimatums damage trust. Stating a false duty to report to police will stop disclosure.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "rnao-ipv",
      },
      {
        id: "q4",
        kind: "short",
        update: "She discloses that her husband assaulted her.",
        prompt: "What supports should you involve before discharge?",
        required: 2,
        accept: [
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
          { id: "dv", text: "Hospital domestic violence program or counsellor", match: ["domestic violence", "counsellor", "counselor", "counselling", "dv program", "sadv"] },
          { id: "shelter", text: "Shelter or transition house", match: ["shelter", "transition house"] },
          { id: "crisis", text: "Crisis line", match: ["crisis line", "helpline", "hotline", "assaulted women"] },
          { id: "vs", text: "Victim services or legal support", match: ["victim service", "legal", "lawyer"] },
          { id: "police", text: "Police, if she chooses", match: ["police"] },
        ],
        explanation:
          "A multidisciplinary response gives her safety planning, shelter options and legal information. The ED physician starts the connection. The patient decides which supports she uses.",
        keyFeature: { topic: "abuse-domestic", n: 5 },
        source: "who-ipv",
      },
    ],
    sources: [SRC.rosen, SRC.rnao, SRC.who],
    ...meta,
  },
  {
    id: "abuse-domestic-11",
    topic: "abuse-domestic",
    alsoTopics: ["multiple-trauma"],
    title: "Pregnant woman after a fall in the kitchen",
    stem:
      "A 32-year-old woman, G3P2 at 30 weeks, says she fell against the kitchen counter 1 hour ago. She has lower abdominal pain, cramping and light vaginal bleeding. Her partner brought her and has gone to park the car. Her chart shows two ED visits for falls earlier in this pregnancy.\n\nThe fetal heart rate is 158/minute.\n\nThe uterus is firm and tender. Her blood group is O Rh negative. She has not yet received antenatal Rh immune globulin.",
    vitals: { temperature: "36.7°C", pulse: "108/minute", resp: "20/minute", bp: "104/66 mmHg", o2sat: "98% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What immediate management steps are specific to her pregnancy?",
        required: 3,
        accept: [
          { id: "tilt", text: "Left lateral tilt or manual uterine displacement", match: ["left lateral", "tilt", "uterine displacement", "left side", "displace the uterus"] },
          { id: "ctg", text: "Continuous fetal heart and contraction monitoring", match: ["fetal monitoring", "ctg", "cardiotocography", "fetal heart", "tocodynamometry", "nst", "electronic fetal"] },
          { id: "ob", text: "Urgent obstetrics consultation", match: ["obstetric", "obstetrician", "obstetrics", "labour and delivery"] },
          { id: "rh", text: "Rh immune globulin", match: ["rh immune", "anti d", "rhogam", "winrho", "rhig"] },
          { id: "kb", text: "Kleihauer-Betke test", match: ["kleihauer", "kb test"] },
          { id: "iv", text: "IV access with group and screen", match: ["group and screen", "type and screen", "crossmatch", "iv access", "large bore"] },
          { id: "ster", text: "Betamethasone if preterm delivery is likely", match: ["betamethasone", "steroid", "corticosteroid"] },
        ],
        explanation:
          "A firm, tender uterus with bleeding after abdominal trauma suggests placental abruption. Displace the uterus, start fetal monitoring and involve obstetrics now. Rh negative patients need Rh immune globulin after abdominal trauma.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "sogc-trauma",
      },
      {
        id: "q2",
        kind: "short",
        update: "While her partner is parking, she tells the nurse she is afraid to go home.",
        prompt: "What features should have raised suspicion of partner violence even before her statement?",
        required: 2,
        accept: [
          { id: "preg", text: "Pregnancy", match: ["pregnancy", "pregnant"] },
          { id: "rep", text: "Repeated visits for falls in this pregnancy", match: ["repeat", "repeated", "previous", "prior", "recurrent", "two ed visit", "multiple"] },
          { id: "abd", text: "Abdominal trauma in pregnancy", match: ["abdominal", "abdomen", "belly"] },
          { id: "mech", text: "Vague or implausible mechanism", match: ["mechanism", "vague", "implausible", "inconsistent"] },
        ],
        explanation:
          "Violence often starts or escalates in pregnancy and targets the abdomen. Repeated falls in pregnancy are a recognized warning sign. Asking every pregnant patient privately is recommended.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "sogc-ipv",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following Rh immune globulin plans is most appropriate for her?",
        options: [
          "Give Rh immune globulin only if the bleeding becomes heavy",
          "Rh immune globulin 300 mcg IM now, plus Kleihauer-Betke",
          "Rh immune globulin 120 mcg IM with no further testing",
          "Wait for the Kleihauer-Betke result before giving any dose",
          "No Rh immune globulin after minor trauma",
        ],
        correct: 1,
        explanation:
          "Abdominal trauma in the third trimester can cause significant fetomaternal hemorrhage. Give a standard 300 mcg dose within 72 hours and use a Kleihauer-Betke test to quantify the hemorrhage and decide whether more is needed. Waiting or withholding risks alloimmunization.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "sogc-rh",
      },
    ],
    sources: [SRC.sogcTrauma, SRC.sogcIpv, SRC.sogcRh],
    ...meta,
  },
  {
    id: "abuse-domestic-12",
    topic: "abuse-domestic",
    alsoTopics: ["burns"],
    title: "Man with a scald to the back",
    stem:
      "A 41-year-old man has a scald to his upper back and the back of both shoulders. He says he spilled a kettle while reaching into a cupboard last evening. He waited until this morning to come in. His wife drove him. His chart shows two recent visits for a hand laceration from broken glass and a black eye from a cupboard door.\n\nThe burn is superficial partial thickness, covering about 6% of body surface area, with sharp margins and drip marks running down his back.",
    vitals: { temperature: "36.9°C", pulse: "104/minute", resp: "18/minute", bp: "142/88 mmHg", o2sat: "98% on room air", weight: "82 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features suggest this burn may have been inflicted?",
        required: 3,
        accept: [
          { id: "loc", text: "Location on the back does not fit the stated mechanism", match: ["back", "posterior", "location", "inconsistent", "mechanism"] },
          { id: "pattern", text: "Pattern of liquid thrown from behind", match: ["pattern", "thrown", "from behind", "drip", "pour"] },
          { id: "delay", text: "Delayed presentation", match: ["delay", "delayed", "late", "waited"] },
          { id: "rep", text: "Repeated injury visits", match: ["repeat", "repeated", "previous", "prior", "recurrent", "multiple visit"] },
          { id: "face", text: "Previous facial injury", match: ["black eye", "facial", "face"] },
        ],
        explanation:
          "A spill while reaching forward burns the front of the body, not the back. Drip marks down the back suggest liquid poured or thrown from above and behind. Men are less often asked about partner violence and less likely to volunteer it.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What other injury patterns in adults should raise concern for partner violence?",
        required: 2,
        accept: [
          { id: "head", text: "Head, face and neck injuries", match: ["head", "face", "facial", "neck"] },
          { id: "def", text: "Defensive forearm injuries", match: ["forearm", "defensive"] },
          { id: "central", text: "Injuries to the breasts, abdomen or genitals", match: ["breast", "abdomen", "abdominal", "genital", "central"] },
          { id: "bite", text: "Bite marks", match: ["bite"] },
          { id: "strang", text: "Strangulation marks", match: ["strangulation", "choking", "petechiae"] },
          { id: "pat", text: "Patterned injuries from belts, cords or objects", match: ["patterned", "belt", "cord", "object"] },
          { id: "cig", text: "Cigarette burns", match: ["cigarette"] },
          { id: "ages", text: "Injuries of different ages", match: ["different age", "different stage", "healing"] },
          { id: "tm", text: "Perforated eardrum", match: ["tympanic", "eardrum"] },
        ],
        explanation:
          "Assault injuries cluster centrally and on the head and neck, while accidental injuries favour the extremities and bony prominences. Patterned and defensive injuries are highly suggestive. Injuries of different ages indicate repeated violence.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "How can you find other current or past injuries?",
        required: 2,
        accept: [
          { id: "skin", text: "Complete skin examination with the patient undressed", match: ["skin", "undress", "undressed", "head to toe", "full body", "full exam", "complete exam"] },
          { id: "chart", text: "Review previous ED records", match: ["record", "chart", "previous visit", "prior visit", "old file"] },
          { id: "img", text: "Review previous imaging for healed fractures", match: ["imaging", "x ray", "xray", "radiograph", "healed fracture"] },
          { id: "ask", text: "Ask directly about other injuries", match: ["ask", "history of other"] },
        ],
        explanation:
          "A full examination and a review of past visits and imaging often reveal a pattern. Old healed fractures or repeated injuries support the concern and should be documented.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "single",
        update: "He discloses that his wife threw the kettle at him. He has nowhere else to stay tonight.",
        prompt: "Which of the following dispositions is most appropriate for him?",
        options: [
          "Admit or arrange a safe alternative",
          "Discharge and ask police to remove his wife",
          "Discharge home with dressings and clinic follow-up",
          "Discharge home with oral antibiotics",
          "Transfer to a burn centre for grafting",
        ],
        correct: 0,
        explanation:
          "Burn disposition depends on home circumstances as well as size and site. An unsafe home is itself a reason not to discharge a burn patient. Suspected abuse and an unsafe home are indications for admission or a safe placement, even for a 6% partial thickness burn. Prophylactic antibiotics are not indicated.",
        keyFeature: { topic: "burns", n: 5 },
        source: "aba",
      },
    ],
    sources: [SRC.rosen, SRC.aba],
    ...meta,
  },
  {
    id: "abuse-domestic-13",
    topic: "abuse-domestic",
    title: "Recent newcomer with pelvic pain",
    stem:
      "A 26-year-old woman who arrived in Canada 8 months ago as a sponsored spouse presents with vaginal discharge and pelvic pain. She speaks Arabic and limited English. A neighbour brought her. She mentions that her husband keeps her passport and health card and controls all the money. She has no friends or family in Canada.",
    vitals: { temperature: "37.0°C", pulse: "84/minute", resp: "14/minute", bp: "112/70 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features of her situation increase her risk of undisclosed abuse?",
        required: 3,
        accept: [
          { id: "imm", text: "Recent immigration and dependence on a spousal sponsor", match: ["sponsor", "sponsorship", "sponsored", "immigration", "newcomer", "immigrant"] },
          { id: "docs", text: "Husband controls her documents", match: ["passport", "document", "health card"] },
          { id: "fin", text: "Financial control", match: ["money", "financial", "finance"] },
          { id: "iso", text: "Social isolation", match: ["isolation", "isolated", "no friend", "no support", "no family"] },
          { id: "lang", text: "Language barrier", match: ["language", "english", "arabic"] },
          { id: "gyn", text: "Gynecologic complaint that may reflect sexual violence", match: ["sti", "pelvic", "discharge", "sexually transmitted", "gynecologic", "sexual"] },
        ],
        explanation:
          "Control of documents and money and social isolation are forms of coercive control. Newcomers may fear that disclosure threatens their immigration status. Gynecologic complaints may be the only visible sign of sexual violence.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "who-ipv",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What should you do to help her disclose safely?",
        required: 2,
        accept: [
          { id: "interp", text: "Use a professional interpreter", match: ["interpreter"] },
          { id: "alone", text: "Speak with her alone, without the neighbour", match: ["alone", "private", "privacy", "without the neighbour", "without neighbour"] },
          { id: "conf", text: "Explain confidentiality", match: ["confidential", "confidentiality"] },
          { id: "direct", text: "Ask directly and without judgment", match: ["direct", "directly", "nonjudgmental", "non judgmental", "without judgment", "without judgement"] },
          { id: "care", text: "Reassure her that care does not depend on her immigration status", match: ["immigration status", "status", "regardless"] },
        ],
        explanation:
          "A professional interpreter and privacy are essential. Even a friendly neighbour may be connected to the husband. Explaining confidentiality addresses a common fear that disclosure will reach her partner or the authorities.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "rnao-ipv",
      },
      {
        id: "q3",
        kind: "short",
        update: "She discloses physical and sexual abuse. She is afraid that leaving her husband will get her deported.",
        prompt: "What accurate responses or referrals would address her fear and build trust?",
        required: 2,
        accept: [
          { id: "legal", text: "Refer to legal aid or an immigration lawyer for accurate advice", match: ["legal", "lawyer", "legal aid"] },
          { id: "agency", text: "Refer to a newcomer or immigrant serving violence agency", match: ["settlement", "immigrant", "newcomer", "multicultural", "agency"] },
          { id: "shelter", text: "Shelters accept women regardless of immigration status", match: ["shelter"] },
          { id: "pr", text: "Explain that a sponsor cannot cancel permanent resident status", match: ["permanent resident", "cannot cancel", "cannot revoke", "sponsor cannot"] },
          { id: "help", text: "Multilingual violence helpline", match: ["helpline", "crisis line", "assaulted women", "hotline"] },
          { id: "sw", text: "Social worker", match: ["social work", "social worker", "sw"] },
        ],
        explanation:
          "Fear about immigration status is a major barrier to disclosure. Once granted, permanent residence is not cancelled because a sponsored spouse leaves an abusive sponsor. Referral to legal and culturally specific services gives her reliable information and builds trust.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "who-ipv",
      },
    ],
    sources: [SRC.who, SRC.rnao],
    ...meta,
  },
  {
    id: "abuse-domestic-14",
    topic: "abuse-domestic",
    title: "Young man from a group home with foot burns",
    stem:
      "A 23-year-old man with an intellectual disability and limited speech lives in a group home. Staff bring him in with burns to both feet. They say he stepped into a hot bath.\n\nBoth feet have symmetrical partial thickness burns up to the ankles with a sharp horizontal upper margin. There are no splash marks. The soles are spared. He becomes distressed whenever one staff member approaches.",
    vitals: { temperature: "37.0°C", pulse: "112/minute", resp: "20/minute", bp: "124/76 mmHg", o2sat: "98% on room air", weight: "70 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What features of this burn suggest forced immersion?",
        required: 3,
        accept: [
          { id: "sym", text: "Symmetrical burns on both feet", match: ["symmetric", "symmetrical", "bilateral", "both feet"] },
          { id: "line", text: "Sharp horizontal line of demarcation", match: ["sharp", "demarcation", "line", "tide mark", "clear margin"] },
          { id: "splash", text: "No splash marks", match: ["no splash", "absent splash", "absence of splash", "without splash", "lack of splash"] },
          { id: "stock", text: "Stocking distribution", match: ["stocking", "circumferential"] },
          { id: "spare", text: "Sparing of the soles", match: ["sparing", "spared", "sole"] },
          { id: "reflex", text: "A person stepping in would withdraw after one foot", match: ["withdraw", "reflex", "escape", "one foot", "inconsistent"] },
        ],
        explanation:
          "Accidental scalds are asymmetric with irregular edges and splash marks. Forced immersion causes symmetric stocking burns with a sharp tide line, and the soles are spared where they press against the cool tub floor. Adults with disabilities are at high risk of abuse by caregivers.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What steps would identify other current or old injuries?",
        required: 2,
        accept: [
          { id: "skin", text: "Complete skin examination", match: ["skin", "head to toe", "full body", "undress", "full exam", "complete exam"] },
          { id: "chart", text: "Review previous records", match: ["record", "chart", "previous visit", "prior visit", "old file"] },
          { id: "xr", text: "X-rays of tender or deformed areas", match: ["x ray", "xray", "radiograph", "skeletal", "imaging"] },
          { id: "gen", text: "Anogenital examination", match: ["genital", "anogenital"] },
          { id: "fam", text: "Collateral from family or his guardian", match: ["collateral", "family", "guardian"] },
        ],
        explanation:
          "Patients with limited communication cannot report other injuries or earlier abuse. A full examination and a review of records are needed. Collateral from someone other than the suspected caregiver adds history.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "How can you help him communicate safely about what happened?",
        required: 2,
        accept: [
          { id: "sep", text: "Speak with him away from the staff member", match: ["away from staff", "without staff", "away from the staff", "alone", "separate", "private"] },
          { id: "aid", text: "Use his usual communication aids or picture boards", match: ["communication aid", "picture", "board", "device", "sign language", "augmentative"] },
          { id: "trust", text: "Include a trusted support person he chooses", match: ["trusted", "support person", "advocate", "family"] },
          { id: "simple", text: "Use simple, open questions and allow extra time", match: ["simple", "open question", "extra time", "more time", "allow time", "patience"] },
          { id: "slp", text: "Involve a speech language pathologist", match: ["speech"] },
        ],
        explanation:
          "People with intellectual disability can often disclose when given privacy, their own communication tools and time. The suspected abuser must not be present or act as interpreter. A trusted, independent person helps him feel safe.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "who-ipv",
      },
    ],
    sources: [SRC.rosen, SRC.who],
    ...meta,
  },
  {
    id: "abuse-domestic-15",
    topic: "abuse-domestic",
    title: "Young woman asking for STI testing",
    stem:
      "A 19-year-old woman asks for a pregnancy test and STI testing. It is her third visit this year for STI concerns or a possible pregnancy. She says her boyfriend removes condoms without asking and threw out her birth control pills. He checks her phone and expects a text every hour.\n\nVital signs are normal. A urine pregnancy test is negative.",
    questions: [
      {
        id: "q1",
        kind: "short",
        prompt: "What indicators of intimate partner abuse are in her story?",
        required: 3,
        accept: [
          { id: "sab", text: "Contraceptive sabotage", match: ["pill", "birth control", "contraceptive", "contraception", "sabotage"] },
          { id: "condom", text: "Removing condoms without consent", match: ["condom", "stealthing"] },
          { id: "ctrl", text: "Monitoring her phone and demanding hourly texts", match: ["phone", "monitor", "monitoring", "text", "controlling", "control"] },
          { id: "rep", text: "Repeated visits for STI or pregnancy concerns", match: ["repeat", "repeated", "recurrent", "third", "multiple", "visit"] },
          { id: "age", text: "Young age", match: ["young", "age", "19"] },
        ],
        explanation:
          "Reproductive coercion, such as removing condoms or destroying contraception, is a form of abuse. Monitoring and controlling behaviour often come with it. Repeated STI or pregnancy visits can be the only clue.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "who-ipv",
      },
      {
        id: "q2",
        kind: "short",
        prompt: "What are the elements of a supportive response to her disclosure?",
        required: 2,
        accept: [
          { id: "val", text: "Believe and validate her, and say it is not her fault", match: ["believe", "validate", "not your fault", "not her fault", "acknowledge"] },
          { id: "nj", text: "Stay nonjudgmental", match: ["nonjudgmental", "non judgmental", "without judgment", "without judgement"] },
          { id: "conf", text: "Explain confidentiality", match: ["confidential", "confidentiality"] },
          { id: "resp", text: "Respect her choices and pace", match: ["respect", "autonomy", "her choice", "her pace"] },
          { id: "safe", text: "Ask about her immediate safety", match: ["safety", "safe"] },
          { id: "contra", text: "Offer discreet contraception such as an IUD or implant", match: ["discreet contraception", "iud", "implant", "injectable", "depo", "undetectable", "hidden contraception"] },
        ],
        explanation:
          "A first response that believes her, is nonjudgmental and respects her choices builds trust and improves later help seeking. Offering discreet contraception such as an IUD or injection addresses the coercion directly.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "who-ipv",
      },
      {
        id: "q3",
        kind: "short",
        prompt: "In which other patient groups should you have a higher index of suspicion for undisclosed partner abuse?",
        required: 2,
        accept: [
          { id: "preg", text: "Pregnant patients", match: ["pregnant", "pregnancy"] },
          { id: "old", text: "Older adults", match: ["older", "elderly", "elder", "senior"] },
          { id: "lgbt", text: "People in same sex relationships", match: ["same sex", "lgbt", "lgbtq", "2slgbtqi", "gay", "lesbian", "queer"] },
          { id: "sub", text: "People who use substances", match: ["substance", "alcohol", "drug"] },
          { id: "freq", text: "Frequent ED users", match: ["frequent", "repeat visit"] },
          { id: "dis", text: "People with disabilities", match: ["disability", "disabilities", "disabled"] },
          { id: "new", text: "Recent newcomers", match: ["newcomer", "immigrant", "refugee"] },
        ],
        explanation:
          "Pregnant people, older adults, people in same sex relationships, substance users and frequent ED users are at higher risk of hidden abuse. Their presenting complaints are often unrelated to injury. Keep abuse in the differential and ask privately.",
        keyFeature: { topic: "abuse-domestic", n: 1 },
        source: "rnao-ipv",
      },
    ],
    sources: [SRC.who, SRC.rnao],
    ...meta,
  },
];
