// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const febrileInfant: OralCase = {
  id: "febrile-infant",
  title: "A sleepy newborn",
  blueprint: "peds",
  alsoCovers: ["id", "resus"],
  priorityTopic: "pediatric-fever",
  keyFeatures: [
    { topic: "pediatric-fever", n: 1 },
    { topic: "pediatric-fever", n: 2 },
    { topic: "pediatric-fever", n: 3 },
    { topic: "shock", n: 1 },
    { topic: "seizures", n: 4 },
    { topic: "airway", n: 4 },
  ],
  summary: "A 3 week old brought in by her parents because she is not feeding and is hard to wake.",
  durationMinutes: 15,
  stem:
    "You are working in a community emergency department in Ontario. There is no pediatric ICU on site. " +
    "Amara Osei is 3 weeks old. Her parents brought her in because she has fed poorly since last evening and is hard to wake this morning. " +
    "Triage vitals: heart rate 204, respiratory rate 62, blood pressure 58/32, SpO2 94 percent on room air, rectal temperature 38.6. CTAS 1. " +
    "The triage nurse says: 'She is floppy and mottled. Her cap refill is about 4 seconds. I have put her in resus. Her weight on the scale is 3.6 kg. Mom is very upset.'",
  findings: [
    { id: "weight", label: "Weight", result: "3.6 kg. Birth weight was 3.4 kg." },
    { id: "glucose", label: "Point of care glucose", result: "Capillary glucose 2.1 mmol/L." },
    {
      id: "exam",
      label: "General and skin exam",
      result:
        "Lethargic with a weak cry. Responds only to pain. Mottled limbs. Central capillary refill 4 seconds. " +
        "Anterior fontanelle slightly full. No rash, no petechiae, no vesicles, no bruising. Umbilicus is healed. Scalp is normal. " +
        "Occasional grunting with mild subcostal indrawing. Chest clear.",
    },
    {
      id: "cardiac",
      label: "Cardiac exam and ductal screen",
      result:
        "No murmur. Femoral pulses present and equal to the brachial pulses. Right hand SpO2 95 percent, foot SpO2 94 percent. Liver edge 1 cm below the costal margin.",
    },
    {
      id: "birth-history",
      label: "Birth and feeding history",
      result:
        "Term at 39 weeks by vaginal delivery. Mother was GBS positive and received two doses of intrapartum penicillin more than 4 hours before delivery. " +
        "No maternal fever. No known maternal herpes. Discharged on day 2. Breastfeeding well until last evening. Only 2 wet diapers in the last 24 hours. No sick contacts.",
    },
    {
      id: "social",
      label: "Social history",
      result:
        "First child. Parents are 24 and 26 and live together. No prior involvement with child protection. No concerns raised by the public health nurse at the home visit.",
    },
    { id: "vbg", label: "Venous blood gas and lactate", result: "pH 7.23. pCO2 39 mmHg. Bicarbonate 16 mmol/L. Base excess minus 10. Lactate 4.8 mmol/L." },
    {
      id: "cbc",
      label: "CBC and inflammatory markers",
      result: "WBC 3.1 x 10^9/L with neutrophils 1.2. Hemoglobin 128 g/L. Platelets 98 x 10^9/L. CRP 64 mg/L. Procalcitonin 6.2 µg/L.",
    },
    {
      id: "chem",
      label: "Electrolytes and chemistry",
      result:
        "Sodium 134 mmol/L. Potassium 4.8 mmol/L. Chloride 104 mmol/L. Creatinine 48 µmol/L. Ionized calcium 1.12 mmol/L. Total bilirubin 88 µmol/L. ALT 30 U/L.",
    },
    { id: "urine", label: "Catheter urinalysis", result: "Leukocyte esterase negative. Nitrite negative. Urine culture sent." },
    { id: "cxr", label: "Chest X ray", result: "No consolidation. Normal heart size and shape. No effusion." },
    {
      id: "csf",
      label: "Lumbar puncture results",
      result:
        "Available only once she is stable enough for an LP. CSF WBC 1,240 x 10^6/L with 85 percent neutrophils. RBC 20 x 10^6/L. Protein 2.4 g/L. " +
        "Glucose 0.9 mmol/L with serum glucose 5.2 mmol/L. Gram stain shows Gram positive cocci in pairs and chains. HSV and enterovirus PCR pending.",
    },
    {
      id: "blood-culture",
      label: "Blood culture",
      result: "Drawn before antibiotics. At 11 hours it flags positive with Gram positive cocci in chains.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "Resus",
      text: "You walk into resus. The baby is limp on the stretcher. Her mother is standing in the corner crying.",
      next: "q-first",
    },
    {
      kind: "question",
      id: "q-first",
      phase: "First five minutes",
      prompt: "Tell me what you are doing in the first five minutes.",
      seconds: 90,
      modelAnswer: [
        "Recognize septic shock in a neonate. Call for help early, including pediatric advice.",
        "Oxygen, monitor, and a quick ABC assessment.",
        "Point of care glucose right away.",
        "IV access, or IO if IV fails quickly.",
        "Blood culture, gas, lactate, CBC, electrolytes and ionized calcium with the line.",
      ],
      rubric: ["fi-r1", "fi-d2"],
      next: "q-access",
    },
    {
      kind: "question",
      id: "q-access",
      phase: "Access",
      prompt: "The nurse cannot get an IV after two attempts. What do you do?",
      seconds: 45,
      modelAnswer: [
        "Move to intraosseous access now.",
        "Proximal tibia, just below and medial to the tibial tuberosity.",
        "Do not spend more than about 90 seconds on peripheral attempts in shock.",
      ],
      rubric: ["fi-r2"],
      choices: [
        { id: "c-io", label: "I placed an intraosseous needle in the proximal tibia right away.", next: "q-fluids", quality: "strong", feedback: "Strong. In a shocked infant, go to IO after about 90 seconds of failed IV attempts. The proximal tibia is quick and reliable. Fluids, dextrose and antibiotics all run through it." },
        { id: "c-more-iv", label: "I asked for more IV attempts, including with ultrasound.", next: "s-access-delay", quality: "partial", feedback: "Partial. Repeated IV attempts cost minutes this baby does not have. The examiner wanted IO access after two failed attempts or about 90 seconds. Ultrasound guided IV can come later." },
      ],
    },
    {
      kind: "say",
      id: "s-access-delay",
      phase: "Fifteen minutes later",
      text: "Three more attempts fail. Her heart rate is 212 and blood pressure 52/28. You place an IO in the proximal tibia on the first try.",
      next: "q-fluids",
    },
    {
      kind: "question",
      id: "q-fluids",
      phase: "Fluids",
      prompt: "What fluid will you give, what volume, and how will you decide whether to give more?",
      seconds: 60,
      modelAnswer: [
        "Balanced crystalloid or normal saline 10 mL/kg, about 36 mL, repeated to 20 mL/kg as needed.",
        "Push pull with a syringe over 5 to 10 minutes. Up to 40 to 60 mL/kg in the first hour if she keeps responding.",
        "Reassess heart rate, perfusion, liver size and lung sounds after each bolus.",
        "Stop and start inotropes if the liver enlarges or crackles appear.",
      ],
      rubric: ["fi-r3"],
      choices: [
        { id: "c-bolus", label: "I gave 10 to 20 mL/kg of normal saline by push pull and reassessed after each bolus.", next: "q-glucose", quality: "strong", feedback: "Strong. Give 10 to 20 mL/kg, about 36 to 72 mL, by push pull. Many neonatal order sets use 10 mL/kg at a time. Reassess heart rate, perfusion, liver edge and lungs after each bolus. Stop and start epinephrine if the liver grows or crackles appear." },
        { id: "c-wide-open", label: "I hung a bag of saline and ran it wide open.", next: "s-overload", quality: "unsafe", feedback: "Unsafe. A 3.6 kg neonate can be overloaded within minutes. Fluid must be measured in 10 to 20 mL/kg aliquots with reassessment after each. The examiner wanted syringe boluses and a plan for inotropes." },
      ],
    },
    {
      kind: "say",
      id: "s-overload",
      phase: "Twenty minutes later",
      text:
        "About 250 mL has run in, which is nearly 70 mL/kg. She has fine crackles at both bases. Her liver edge is 3 cm below the costal margin. SpO2 is 87 percent. The nurse clamps the line.",
      next: "q-glucose",
    },
    {
      kind: "question",
      id: "q-glucose",
      phase: "Glucose",
      prompt: "Her glucose is 2.1 mmol/L. What will you give, in what dose, and when will you recheck it?",
      seconds: 45,
      modelAnswer: [
        "D10W 2 mL/kg IV or IO, about 7 mL.",
        "Recheck in 15 to 30 minutes.",
        "Follow with D10W at about 4 mL/kg/h, about 14 mL/h.",
        "Avoid concentrated dextrose such as D50W in a neonate.",
      ],
      rubric: ["fi-r4"],
      choices: [
        { id: "c-d10", label: "I gave D10W 2 mL/kg, about 7 mL, and rechecked it in 15 minutes.", next: "q-abx", quality: "strong", feedback: "Strong. D10W 2 mL/kg, about 7 mL, is the neonatal dose. Recheck in 15 to 30 minutes. Follow with a dextrose containing infusion." },
        { id: "c-d50", label: "I gave D50W 1 mL/kg.", next: "s-d50", quality: "unsafe", feedback: "Unsafe. D50W is far too concentrated for a neonate and can damage veins or the IO site. The correct treatment is D10W 2 mL/kg. Always check the concentration when dosing dextrose in infants." },
        { id: "c-later", label: "I planned to recheck the glucose after antibiotics were in.", next: "s-low-sugar", quality: "partial", feedback: "Partial. A glucose of 2.1 mmol/L in a lethargic neonate needs treatment now. Delay risks seizures and brain injury. Give D10W 2 mL/kg at once and recheck in 15 to 30 minutes." },
      ],
    },
    {
      kind: "say",
      id: "s-d50",
      phase: "At the bedside",
      text:
        "The pharmacist stops you before it is pushed. D50W is very hypertonic and can damage the IO site and veins. It can also cause rebound hypoglycemia. Neonates get D10W 2 mL/kg. You give that instead.",
      next: "q-abx",
    },
    {
      kind: "say",
      id: "s-low-sugar",
      phase: "Fifteen minutes later",
      text: "She is more floppy and has a brief apnea. The repeat glucose is 1.6 mmol/L. You give D10W 2 mL/kg.",
      next: "q-abx",
    },
    {
      kind: "question",
      id: "q-abx",
      phase: "Antibiotics",
      prompt: "Which antibiotics will you give, in what doses? When will you do the lumbar puncture?",
      seconds: 90,
      modelAnswer: [
        "Blood culture first, but do not delay antibiotics. Aim for within one hour.",
        "Ampicillin 75 mg/kg IV every 6 hours, about 270 mg.",
        "Cefotaxime 50 to 75 mg/kg IV, about 180 to 270 mg. If pharmacy has none, ceftazidime or cefepime 50 mg/kg. Gentamicin alone does not treat meningitis well.",
        "Acyclovir 20 mg/kg IV every 8 hours, about 72 mg, for possible neonatal HSV.",
        "Avoid ceftriaxone under 28 days.",
        "Defer the LP until she is stable. Do it after antibiotics.",
      ],
      rubric: ["fi-a1", "fi-a2", "fi-a3", "fi-a4", "fi-d1", "fi-d3"],
      choices: [
        {
          id: "c-abx-now",
          label: "I drew a blood culture and gave ampicillin, cefotaxime and acyclovir now. I deferred the LP until she was stable.",
          next: "s-refractory",
          quality: "strong", feedback: "Strong. Antibiotics within one hour matter more than the LP. Ampicillin 75 mg/kg plus cefotaxime 50 to 75 mg/kg covers GBS, Listeria, Gram negatives and meningitis. Acyclovir 20 mg/kg covers HSV.",
        },
        { id: "c-lp-first", label: "I did the LP first so the cultures would be clean, then gave antibiotics.", next: "s-lp-first", quality: "unsafe", feedback: "Unsafe. Positioning a shocked neonate for an LP can cause apnea and collapse. Antibiotics must not wait for the LP. Draw a blood culture, treat, and tap once she is stable." },
        { id: "c-ctx", label: "I gave ceftriaxone 50 mg/kg on its own.", next: "s-ctx", quality: "partial", feedback: "Partial. Ceftriaxone is avoided under 28 days because it displaces bilirubin and must not be given with IV calcium. A single agent also misses Listeria and HSV. The examiner wanted ampicillin, cefotaxime and acyclovir." },
      ],
    },
    {
      kind: "say",
      id: "s-lp-first",
      phase: "During the LP",
      text:
        "While she is held curled for the LP her SpO2 falls to 78 percent and her heart rate drops to 90. The tap is bloody. You stop and resuscitate. Antibiotics go in 75 minutes after arrival.",
      next: "s-refractory",
    },
    {
      kind: "say",
      id: "s-ctx",
      phase: "Pharmacy call",
      text:
        "The pharmacist calls. Ceftriaxone is avoided under 28 days because it displaces bilirubin and can precipitate with calcium. It also does not cover Listeria or HSV. You add ampicillin and acyclovir and switch to cefotaxime.",
      next: "s-refractory",
    },
    {
      kind: "say",
      id: "s-refractory",
      phase: "Reassessment",
      text:
        "She has now had at least 40 mL/kg of fluid. Heart rate 196. Blood pressure 56/30. Capillary refill 4 seconds. The liver edge is 2 cm below the costal margin.",
      next: "q-pressor",
    },
    {
      kind: "question",
      id: "q-pressor",
      phase: "Refractory shock",
      prompt: "Which vasoactive agent will you start, at what dose and by what route? What else causes shock at this age, and how have you screened for it?",
      seconds: 90,
      modelAnswer: [
        "Epinephrine 0.05 to 0.3 mcg/kg/min by peripheral IV or IO. Do not wait for a central line. Norepinephrine is an accepted alternative.",
        "Consider duct dependent heart disease. Check pre and post ductal saturations and femoral pulses.",
        "Consider congenital adrenal hyperplasia. Check sodium and potassium. Hydrocortisone if adrenal crisis is possible.",
        "Consider inborn errors of metabolism, HSV and non accidental injury.",
      ],
      rubric: ["fi-r5", "fi-d4"],
      next: "s-seizure",
    },
    {
      kind: "say",
      id: "s-seizure",
      phase: "Minutes later",
      text: "The nurse says, 'She is twitching.' She has rhythmic jerking of the right arm and lip smacking. SpO2 is 85 percent and she has a 20 second pause in breathing.",
      next: "q-seizure",
    },
    {
      kind: "question",
      id: "q-seizure",
      phase: "Seizure",
      prompt: "What do you check first, and what will you give? What if the seizure continues after two doses?",
      seconds: 60,
      modelAnswer: [
        "Support breathing with bag valve mask.",
        "Recheck glucose. Check sodium and ionized calcium.",
        "Lorazepam or midazolam 0.1 mg/kg IV or IO, about 0.36 mg.",
        "Second line phenobarbital 20 mg/kg IV, about 72 mg, over 15 to 20 minutes. It is the preferred antiseizure drug at this age. Levetiracetam 40 to 60 mg/kg is an alternative.",
      ],
      rubric: ["fi-s1", "fi-s2"],
      next: "q-airway",
    },
    {
      kind: "question",
      id: "q-airway",
      phase: "Airway",
      prompt: "She is apneic and shocked. How will you manage her airway? Tell me your tube and your drugs with doses.",
      seconds: 90,
      modelAnswer: [
        "Call the most experienced help available.",
        "Resuscitate before induction. Have epinephrine and atropine ready.",
        "3.0 cuffed or 3.5 uncuffed tube at about 9.5 to 10 cm at the lip.",
        "Ketamine about 1 mg/kg in shock, with rocuronium 1 mg/kg.",
        "Avoid propofol in shock.",
      ],
      rubric: ["fi-s3", "fi-s4"],
      choices: [
        {
          id: "c-ketamine",
          label: "I resuscitated first, then used ketamine and rocuronium with atropine and epinephrine ready.",
          next: "s-intubated",
          quality: "strong", feedback: "Strong. Shocked infants arrest at induction. Resuscitate first, then use ketamine about 1 mg/kg with rocuronium 1 mg/kg. Have atropine 0.02 mg/kg and push dose epinephrine drawn up.",
        },
        { id: "c-propofol", label: "I used propofol 2 mg/kg for induction.", next: "s-propofol", quality: "unsafe", feedback: "Unsafe. Propofol causes vasodilation and myocardial depression. In septic shock it can cause arrest. The examiner wanted a hemodynamically stable agent such as ketamine after resuscitation." },
      ],
    },
    {
      kind: "say",
      id: "s-propofol",
      phase: "After induction",
      text: "Her blood pressure falls to 38/20 and her heart rate to 70. You start chest compressions and give epinephrine. She recovers a pulse after one minute.",
      next: "s-intubated",
    },
    {
      kind: "say",
      id: "s-intubated",
      phase: "Thirty minutes later",
      text:
        "She is intubated with a 3.5 uncuffed tube. The seizure has stopped. On epinephrine at 0.1 mcg/kg/min her blood pressure is 68/40 and capillary refill is 3 seconds. " +
        "The pediatric critical care transport team has accepted her. They are two hours away. The transport physician asks if the LP has been done.",
      next: "q-transport",
    },
    {
      kind: "question",
      id: "q-transport",
      phase: "Transport",
      prompt: "What do you tell the transport physician? What goes with the baby, and what will you monitor while you wait?",
      seconds: 60,
      modelAnswer: [
        "LP deferred because she was unstable. Antibiotics and acyclovir given, with times.",
        "Structured handover of fluids, dextrose, drugs, doses and infusion rates.",
        "Send blood culture details, results, images and the chart.",
        "Monitor glucose, gas, perfusion, urine output and seizure activity.",
      ],
      rubric: ["fi-c1", "fi-c4", "fi-d3"],
      next: "q-parents",
    },
    {
      kind: "question",
      id: "q-parents",
      phase: "The parents",
      prompt:
        "The father asks, 'Is my daughter going to die?' The mother says she had group B strep in pregnancy and asks if this is her fault. What do you say?",
      seconds: 90,
      modelAnswer: [
        "Sit down with both parents in a quiet space.",
        "Say plainly that she has a serious blood and likely brain infection.",
        "Be honest that she is very sick and the outcome is uncertain.",
        "Tell the mother she did everything right. She received antibiotics in labour and late infection can still happen.",
        "Explain the transfer and check what they understood.",
      ],
      rubric: ["fi-c2", "fi-c3"],
      next: "end",
    },
    { kind: "end", id: "end", text: "The transport team arrives and takes over her care. That is the end of the case." },
  ],
  rubric: [
    {
      id: "fi-r1",
      competency: "leadership",
      criterion: "diagnosis",
      text: "Recognizes septic shock and calls for help, including pediatric resources, early.",
      points: 1,
      teaching: "Tachycardia, mottling and slow capillary refill are shock in a neonate. Low blood pressure is a late sign.",
      source: "trekk-neonate",
    },
    {
      id: "fi-r2",
      competency: "resuscitation",
      criterion: "plan",
      text: "Moves to intraosseous access after failed IV attempts within about 90 seconds.",
      points: 2,
      teaching: "In a shocked infant, IO access is fast and reliable. Do not lose minutes to repeated IV attempts.",
      source: "ssc-peds",
    },
    {
      id: "fi-r3",
      competency: "resuscitation",
      criterion: "plan",
      text: "Gives crystalloid 10 to 20 mL/kg (about 36 to 72 mL) with reassessment of perfusion, liver size and lungs after each bolus.",
      points: 3,
      critical: true,
      teaching: "Neonates can be overloaded quickly. Give measured boluses by syringe and look for hepatomegaly and crackles each time.",
      source: "ssc-peds",
    },
    {
      id: "fi-r4",
      competency: "resuscitation",
      criterion: "plan",
      text: "Treats hypoglycemia with D10W 2 mL/kg IV or IO (about 7 mL) and rechecks glucose within 15 to 30 minutes.",
      points: 2,
      critical: true,
      teaching: "Sick neonates have small glycogen stores. Check glucose early and treat with D10W 2 mL/kg, then a D10W infusion, not concentrated dextrose.",
      source: "trekk-neonate",
    },
    {
      id: "fi-r5",
      competency: "resuscitation",
      criterion: "plan",
      text: "Starts epinephrine 0.05 to 0.3 mcg/kg/min by peripheral IV or IO for fluid refractory shock.",
      points: 2,
      teaching: "Epinephrine can run peripherally or by IO at low dose. Do not wait for a central line.",
      source: "ssc-peds",
    },
    {
      id: "fi-d1",
      competency: "assessment",
      criterion: "data",
      text: "Draws a blood culture before antibiotics without delaying them.",
      points: 1,
      teaching: "One culture drawn with the first line is enough. Never hold antibiotics to get more samples.",
      source: "ssc-peds",
    },
    {
      id: "fi-d2",
      competency: "assessment",
      criterion: "data",
      text: "Obtains catheter urine, gas, lactate, CBC, electrolytes and ionized calcium.",
      points: 1,
      teaching: "These guide resuscitation and help find the source. Urine should be a catheter or suprapubic sample.",
      source: "cps-febrile",
    },
    {
      id: "fi-d3",
      competency: "assessment",
      criterion: "data",
      text: "Defers the LP while the infant is unstable and plans it once stable.",
      points: 2,
      teaching: "Positioning for an LP can cause apnea and collapse. Treat first and tap later. CSF can still be useful after antibiotics.",
      source: "cps-febrile",
    },
    {
      id: "fi-d4",
      competency: "assessment",
      criterion: "diagnosis",
      text: "Considers duct dependent heart disease, adrenal crisis, inborn errors, HSV and non accidental injury, and screens for them.",
      points: 2,
      teaching: "Not every shocked neonate has sepsis. Pre and post ductal saturations, femoral pulses and electrolytes are quick screens.",
      source: "trekk-neonate",
    },
    {
      id: "fi-a1",
      competency: "management",
      criterion: "plan",
      text: "Gives empiric antibiotics within one hour without waiting for the LP.",
      points: 3,
      critical: true,
      teaching: "Every hour of delay in septic shock raises mortality. Antibiotics come before the LP in an unstable infant.",
      source: "ssc-peds",
    },
    {
      id: "fi-a2",
      competency: "management",
      criterion: "plan",
      text: "Chooses ampicillin 75 mg/kg IV plus cefotaxime 50 to 75 mg/kg IV, or ceftazidime or cefepime if cefotaxime is unavailable.",
      points: 2,
      teaching: "Ampicillin covers Listeria and enterococcus. A third generation cephalosporin covers GBS and Gram negative organisms and reaches the CSF. Gentamicin does not reach the CSF well.",
      source: "cps-febrile",
    },
    {
      id: "fi-a3",
      competency: "management",
      criterion: "plan",
      text: "Adds acyclovir 20 mg/kg IV for possible neonatal HSV.",
      points: 2,
      teaching: "Neonatal HSV can present without vesicles or maternal history. Seizures and a sick neonate should prompt acyclovir.",
      source: "cps-febrile",
    },
    {
      id: "fi-a4",
      competency: "management",
      criterion: "plan",
      text: "Avoids ceftriaxone in an infant under 28 days and can explain why.",
      points: 1,
      teaching: "Ceftriaxone displaces bilirubin and can precipitate with IV calcium in neonates. Shocked neonates often need calcium, so cefotaxime is the safer choice.",
      source: "cps-febrile",
    },
    {
      id: "fi-s1",
      competency: "management",
      criterion: "plan",
      text: "Rechecks glucose and gives a benzodiazepine, e.g. lorazepam or midazolam 0.1 mg/kg IV or IO (about 0.36 mg).",
      points: 2,
      teaching: "Treat reversible causes first. Low glucose, sodium and calcium can all cause neonatal seizures.",
      source: "trekk-neonate",
    },
    {
      id: "fi-s2",
      competency: "management",
      criterion: "plan",
      text: "Uses phenobarbital 20 mg/kg IV (about 72 mg) as second line, or levetiracetam 40 to 60 mg/kg.",
      points: 1,
      teaching: "The ILAE neonatal guideline makes phenobarbital the first antiseizure drug in neonates. Watch for respiratory depression and hypotension.",
      source: "ilae-neonatal",
    },
    {
      id: "fi-s3",
      competency: "resuscitation",
      criterion: "plan",
      text: "Chooses a 3.0 cuffed or 3.5 uncuffed tube at about 9.5 to 10 cm at the lip.",
      points: 1,
      teaching: "For a term neonate, lip depth is roughly weight in kg plus 6 cm. Confirm with end tidal CO2 and X ray.",
      source: "hsf-pals",
    },
    {
      id: "fi-s4",
      competency: "resuscitation",
      criterion: "plan",
      text: "Resuscitates before induction and uses a stable agent, e.g. ketamine about 1 mg/kg with rocuronium 1 mg/kg, with atropine and epinephrine ready.",
      points: 2,
      teaching: "Shocked infants arrest at induction. Fill the tank, pick a stable drug and have push dose epinephrine drawn up.",
      source: "hsf-pals",
    },
    {
      id: "fi-c1",
      competency: "disposition",
      criterion: "plan",
      text: "Arranges early transfer through the pediatric critical care transport team or CritiCall.",
      points: 2,
      teaching: "Call the transport team as soon as she is critically ill. Their travel time is part of her resuscitation.",
      source: "ssc-peds",
    },
    {
      id: "fi-c2",
      competency: "communication",
      criterion: "plan",
      text: "Explains to the parents in plain language, gives honest uncertainty about outcome, and checks understanding.",
      points: 1,
      teaching: "Parents remember how they were told. Be honest, avoid jargon, and give them a next step.",
      source: "trekk-neonate",
    },
    {
      id: "fi-c3",
      competency: "communication",
      criterion: "plan",
      text: "Addresses the mother's guilt about GBS status with accurate reassurance.",
      points: 1,
      teaching: "Intrapartum antibiotics prevent early onset GBS but not late onset disease. She did nothing wrong.",
      source: "cps-febrile",
    },
    {
      id: "fi-c4",
      competency: "communication",
      criterion: "plan",
      text: "Gives a structured handover with antibiotic times, doses, fluids given and outstanding results.",
      points: 1,
      teaching: "The receiving team needs exact times and doses. Write them on the transfer sheet as you go.",
      source: "ssc-peds",
    },
  ],
  sources: [
    {
      id: "ssc-peds",
      citation: "Weiss SL, et al. Surviving Sepsis Campaign International Guidelines for the Management of Sepsis and Septic Shock in Children 2026. Pediatric Critical Care Medicine. 2026. Replaces the 2020 edition.",
      url: "https://www.sccm.org/clinical-resources/guidelines/guidelines/surviving-sepsis-campaign-international-guidelines-for-the-management-of-sepsis-and-septic-shock-in",
    },
    {
      id: "cps-febrile",
      citation: "Canadian Paediatric Society. Management of well appearing febrile young infants aged 90 days or younger. Position statement. Paediatrics and Child Health. 2024.",
      url: "https://cps.ca/en/documents/position/management-of-well-appearing-febrile-young-infants-aged-90-days",
    },
    {
      id: "trekk-neonate",
      citation: "TREKK. Critically ill neonate algorithm and emergency department order set, version 2.1. 2025.",
      url: "https://trekk.ca/resources/order-set-critically-ill-neonate",
    },
    {
      id: "ilae-neonatal",
      citation: "Pressler RM, et al. Treatment of seizures in the neonate. Guidelines and consensus based recommendations. ILAE Task Force on Neonatal Seizures. Epilepsia. 2023.",
      url: "https://onlinelibrary.wiley.com/doi/10.1111/epi.17745",
    },
    {
      id: "hsf-pals",
      citation: "Heart and Stroke Foundation of Canada. 2025 Guidelines for CPR and Emergency Cardiovascular Care, Canadian edition, including pediatric advanced life support.",
      url: "https://cpr.heartandstroke.ca/s/article/2025-Guidelines?language=en_US",
    },
  ],
  reviewed: true,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 1,
};
