// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const overdose: OralCase = {
  id: "overdose-mixed",
  title: "A drowsy woman found at home",
  blueprint: "tox",
  alsoCovers: ["psych", "resus"],
  priorityTopic: "tox",
  keyFeatures: [
    { topic: "tox", n: 1 },
    { topic: "tox", n: 3 },
    { topic: "tox", n: 4 },
    { topic: "tox", n: 5 },
    { topic: "tox", n: 7 },
    { topic: "suicide-risk", n: 3 },
  ],
  summary: "A 34 year old woman brought in by ambulance after her partner found her drowsy with empty pill packages.",
  durationMinutes: 12,
  stem:
    "You are working in the emergency department of a community hospital when the following patient arrives. There is an ICU on site. " +
    "A 34 year old woman arrives by ambulance after her partner found her drowsy at home beside empty pill packages.",
  card: {
    vitals: {
      temperature: "37.8°C",
      pulse: "124/minute",
      resp: "16/minute",
      bp: "96/58 mmHg",
      o2sat: "95% on room air",
      weight: "60 kg (132 lb), estimated",
    },
    medications: "Amitriptyline 50 mg",
    allergies: "None known",
  },
  findings: [
    {
      id: "hpi",
      label: "History of presenting illness",
      result:
        "Her partner found her drowsy on the couch about an hour ago. She was last seen well about 5 hours before that. " +
        "Empty blister packs and an empty wine bottle were beside her. Paramedics say she was talking in the truck but is getting sleepier.",
    },
    {
      id: "pmh",
      label: "Past history and medications",
      result:
        "Depression and chronic back pain. Amitriptyline was started 6 months ago. No other known medications. She took an overdose of sertraline 2 years ago.",
    },
    {
      id: "ecg",
      label: "ECG",
      result: "Sinus tachycardia at 124. QRS 132 ms. Terminal R wave in aVR of 4 mm. Terminal 40 ms axis deviated to the right. QTc 510 ms. No Brugada pattern.",
    },
    {
      id: "exam",
      label: "Physical exam",
      result:
        "GCS 12 (E3 V4 M5). Pupils 6 mm and sluggish. Skin flushed and dry. Mucous membranes dry. Bowel sounds reduced. Bladder palpable. " +
        "Reflexes normal. No clonus. No rigidity. No signs of trauma. Gag present.",
    },
    {
      id: "packages",
      label: "Pill packages",
      result:
        "Amitriptyline 50 mg, 60 tablets dispensed 10 days ago, 38 missing. Acetaminophen 500 mg, a bottle of 100 that is about half empty. An empty 750 mL bottle of wine.",
    },
    {
      id: "partner",
      label: "Collateral and social history from partner",
      result:
        "She lost her job last month. He found a note on the counter that says 'I am sorry. I cannot keep doing this.' " +
        "No drug use that he knows of.",
    },
    { id: "vbg", label: "Venous blood gas", result: "pH 7.29. pCO2 48 mmHg. Bicarbonate 22 mmol/L. Lactate 2.9 mmol/L." },
    {
      id: "chem",
      label: "Electrolytes and chemistry",
      result:
        "Sodium 138 mmol/L. Potassium 3.6 mmol/L. Chloride 104 mmol/L. Bicarbonate 21 mmol/L. Anion gap 13. Creatinine 72 µmol/L. Glucose 6.1 mmol/L. CK 210 U/L.",
    },
    { id: "apap", label: "Acetaminophen level", result: "Acetaminophen 412 µmol/L. Time of ingestion unknown." },
    { id: "other-tox", label: "Salicylate, ethanol and osmolality", result: "Salicylate undetectable. Ethanol 18 mmol/L. Serum osmolality 306 mOsm/kg." },
    { id: "lft", label: "Liver function and INR", result: "ALT 38 U/L. AST 41 U/L. Bilirubin 12 µmol/L. INR 1.0." },
    { id: "hcg", label: "Pregnancy test", result: "Serum beta hCG negative." },
    { id: "bladder", label: "Bladder scan", result: "Bladder scan shows 650 mL of urine." },
    {
      id: "poison-centre",
      label: "Ontario Poison Centre advice",
      result:
        "The specialist agrees with bicarbonate targets of QRS under 100 ms and pH 7.50 to 7.55. " +
        "They recommend acetylcysteine now, benzodiazepines for seizures, and a call back if hypotension persists despite bicarbonate and norepinephrine. They will review lipid emulsion if she arrests.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "Resus",
      text:
        "She is in resus on the monitor. Triage made her CTAS 1. The nurse says the monitor rhythm looks wide. " +
        "Her partner brought the pill packages. They are in a bag at the desk. The nurse hands you the ECG.",
      next: "q-ecg",
    },
    {
      kind: "question",
      id: "q-ecg",
      phase: "Initial assessment",
      prompt: "Interpret this ECG. What has she taken, how much, and which features predict complications?",
      seconds: 60,
      modelAnswer: [
        "Sinus tachycardia with QRS 132 ms and a terminal R in aVR of 4 mm.",
        "Pattern of sodium channel blockade from a tricyclic.",
        "QRS over 100 ms predicts seizures. QRS over 160 ms predicts ventricular dysrhythmias.",
        "Amitriptyline about 1,900 mg, roughly 30 mg/kg. That is a severe ingestion.",
        "Anticholinergic toxidrome on exam.",
        "Ask what she took, how much, when, with alcohol, and when she was last seen well.",
        "Examine pupils, skin, bowel sounds, bladder, reflexes and clonus.",
      ],
      rubric: ["od-r1", "od-t1", "od-h1", "od-x1"],
      next: "q-bicarb",
    },
    {
      kind: "question",
      id: "q-bicarb",
      phase: "Treatment",
      prompt: "What do you give now? What dose, how often, and what is your endpoint?",
      seconds: 60,
      modelAnswer: [
        "Sodium bicarbonate 1 to 2 mEq/kg IV push, 60 to 120 mEq.",
        "That is one to two 50 mL ampoules of 8.4 percent.",
        "Repeat every 3 to 5 minutes until the QRS is under 100 ms. Do not push the pH above 7.55.",
        "Then an infusion, e.g. 150 mEq in 1 L D5W at 150 to 250 mL/h.",
        "Monitor potassium, sodium and pH.",
      ],
      rubric: ["od-r2", "od-r3"],
      choices: [
        { id: "c-bolus", label: "I gave sodium bicarbonate 1 to 2 mEq/kg IV push and repeated it to narrow the QRS.", next: "q-workup", quality: "strong", feedback: "Strong. QRS over 100 ms in a tricyclic overdose needs sodium bicarbonate 1 to 2 mEq/kg IV push now. That is 60 to 120 mEq for her. Repeat every 3 to 5 minutes to a QRS under 100 ms, keeping the pH at 7.55 or lower." },
        { id: "c-infusion-only", label: "I started a bicarbonate infusion without a bolus.", next: "s-slow-bicarb", quality: "partial", feedback: "Partial. An infusion keeps the effect going but does not reverse blockade quickly. The examiner wanted a 1 to 2 mEq/kg bolus first. Start the infusion once the QRS has narrowed." },
        { id: "c-amio", label: "I gave amiodarone for the wide complex rhythm.", next: "s-amio", quality: "unsafe", feedback: "Unsafe. Amiodarone blocks sodium and potassium channels and worsens tricyclic toxicity. Wide complex rhythms here are treated with sodium bicarbonate. Avoid class IA, IC and III antiarrhythmics." },
      ],
    },
    {
      kind: "say",
      id: "s-slow-bicarb",
      phase: "Fifteen minutes later",
      text: "The QRS is 136 ms. She has a 6 beat run of wide complex tachycardia. An infusion alone is too slow to reverse sodium channel blockade. You push 100 mEq.",
      next: "q-workup",
    },
    {
      kind: "say",
      id: "s-amio",
      phase: "Five minutes later",
      text:
        "Her blood pressure falls to 72/40. The QRS widens to 150 ms and she has a run of ventricular tachycardia. Amiodarone adds sodium and potassium channel blockade. You push 100 mEq of bicarbonate.",
      next: "q-workup",
    },
    {
      kind: "question",
      id: "q-workup",
      phase: "Workup",
      prompt: "What bloodwork do you want? Who will you call? Will you give activated charcoal?",
      seconds: 60,
      modelAnswer: [
        "Acetaminophen, salicylate, ethanol, gas, electrolytes, liver tests, INR and pregnancy test.",
        "Collateral from her partner about the pills, timing, note and past attempts.",
        "Call the Ontario Poison Centre early.",
        "No charcoal while her airway is unprotected and her level of consciousness is falling.",
        "Consider charcoal after intubation with poison centre advice.",
      ],
      rubric: ["od-t2", "od-t5", "od-c1", "od-c2", "od-h2"],
      next: "s-seizure",
    },
    {
      kind: "say",
      id: "s-seizure",
      phase: "Ten minutes later",
      text: "Her QRS narrowed to 108 ms after bicarbonate. Now she has a generalized tonic clonic seizure. SpO2 falls to 86 percent. The QRS on the monitor looks wider again.",
      next: "q-seizure",
    },
    {
      kind: "question",
      id: "q-seizure",
      phase: "Seizure",
      prompt: "Which drug and dose will you use for the seizure? Is there any drug you would avoid? What else do you give?",
      seconds: 60,
      modelAnswer: [
        "Lorazepam 2 to 4 mg IV or midazolam 5 mg IV, repeated as needed.",
        "Avoid phenytoin. It is a sodium channel blocker and does not work for toxic seizures.",
        "Phenobarbital or propofol for refractory seizures, with airway control.",
        "Give more bicarbonate. Seizure acidosis worsens cardiotoxicity.",
      ],
      rubric: ["od-s1", "od-s2"],
      choices: [
        { id: "c-benzo", label: "I gave lorazepam 2 mg IV, repeated it, and gave more bicarbonate.", next: "q-intubate", quality: "strong", feedback: "Strong. Benzodiazepines are first line for toxic seizures. Lorazepam 2 to 4 mg IV is appropriate. More bicarbonate is needed because seizure acidosis widens the QRS." },
        { id: "c-phenytoin", label: "I loaded phenytoin after the first dose of lorazepam.", next: "s-phenytoin", quality: "unsafe", feedback: "Unsafe. Phenytoin is a sodium channel blocker and adds to tricyclic cardiotoxicity. It also does not work well for toxic seizures. Use repeat benzodiazepines, then phenobarbital or propofol." },
      ],
    },
    {
      kind: "say",
      id: "s-phenytoin",
      phase: "During the infusion",
      text: "Her QRS widens to 164 ms and her blood pressure falls to 68/36. The seizure continues. You stop the phenytoin, give more lorazepam and push bicarbonate.",
      next: "q-intubate",
    },
    {
      kind: "question",
      id: "q-intubate",
      phase: "Airway",
      prompt: "The seizure stops but her GCS is now 6. Talk me through your intubation and drug doses.",
      seconds: 90,
      modelAnswer: [
        "Intubate for airway protection.",
        "Give a bicarbonate bolus just before induction.",
        "Preoxygenate well and keep apnea as short as possible.",
        "Reduced dose induction in hypotension, e.g. ketamine 0.5 to 1 mg/kg.",
        "Rocuronium 1.2 to 1.5 mg/kg.",
        "Push dose vasopressor ready.",
      ],
      rubric: ["od-s3", "od-s4"],
      choices: [
        {
          id: "c-bicarb-first",
          label: "I gave a bicarbonate bolus, preoxygenated, used reduced dose ketamine with rocuronium, and kept apnea short.",
          next: "q-vent",
          quality: "strong", feedback: "Strong. A bicarbonate bolus before induction protects against the pH drop during apnea. Reduced dose ketamine, about 0.5 to 1 mg/kg, suits her low pressure. Short apnea and a high rate afterward complete the plan.",
        },
        { id: "c-tube-first", label: "I intubated first and planned more bicarbonate once she was on the ventilator.", next: "s-tube-first", quality: "unsafe", feedback: "Unsafe. During apnea the pCO2 rises and pH falls. That increases free drug and can trigger ventricular dysrhythmias. Give a bicarbonate bolus before induction and keep apnea short." },
      ],
    },
    {
      kind: "say",
      id: "s-tube-first",
      phase: "During intubation",
      text:
        "The first attempt takes 70 seconds. Her pCO2 rises and her pH falls. The QRS widens to 172 ms and she goes into ventricular tachycardia with a pulse. You push 150 mEq of bicarbonate and the rhythm narrows.",
      next: "q-vent",
    },
    {
      kind: "question",
      id: "q-vent",
      phase: "Ventilation",
      prompt: "How will you set the ventilator, and why does it matter in this ingestion?",
      seconds: 45,
      modelAnswer: [
        "Match or exceed her pre intubation minute ventilation.",
        "Tidal volume 6 to 8 mL/kg ideal body weight with a high rate, e.g. 24 to 30.",
        "Target pH 7.50 to 7.55 with a gas soon after intubation.",
        "Respiratory acidosis increases free drug and worsens sodium channel blockade.",
      ],
      rubric: ["od-s5"],
      next: "s-hypotension",
    },
    {
      kind: "say",
      id: "s-hypotension",
      phase: "After intubation",
      text: "Her blood pressure is 74/40. The QRS is 148 ms.",
      next: "q-hypotension",
    },
    {
      kind: "question",
      id: "q-hypotension",
      phase: "Hypotension",
      prompt: "What now? If she keeps deteriorating, what else is available?",
      seconds: 60,
      modelAnswer: [
        "More bicarbonate boluses toward QRS under 100 ms.",
        "Crystalloid bolus.",
        "Norepinephrine infusion.",
        "Hypertonic saline if pH is already high.",
        "Lipid emulsion and ECMO as rescue, with poison centre input.",
        "Recheck QRS, pressure and gas after each bolus.",
      ],
      rubric: ["od-r4", "od-p1"],
      next: "s-apap",
    },
    {
      kind: "say",
      id: "s-apap",
      phase: "New result",
      text:
        "With more bicarbonate and norepinephrine at 0.1 mcg/kg/min her pressure is 102/60 and the QRS is 104 ms. " +
        "The lab calls. Her acetaminophen level is 412 µmol/L. Her partner is still not sure when she took the pills.",
      next: "q-apap",
    },
    {
      kind: "question",
      id: "q-apap",
      phase: "Co ingestion",
      prompt: "How do you interpret this level? What will you give, and where does she go from here?",
      seconds: 60,
      modelAnswer: [
        "The nomogram cannot be used when the time of ingestion is unknown.",
        "A detectable level with an unknown time means start acetylcysteine now.",
        "200 mg/kg over 4 hours then 100 mg/kg over 16 hours, or the regimen your poison centre uses.",
        "Repeat the acetaminophen level, liver tests and INR near the end of the infusion before stopping.",
        "Admit to ICU with a handover of bicarbonate targets and acetylcysteine timing.",
      ],
      rubric: ["od-t3", "od-t4", "od-c3"],
      choices: [
        { id: "c-nac", label: "I started acetylcysteine now because the level is detectable and the time is unknown.", next: "s-later", quality: "strong", feedback: "Strong. The nomogram needs a known ingestion time. A detectable level with an unknown time means start acetylcysteine now. Use 200 mg/kg over 4 hours then 100 mg/kg over 16 hours, or the regimen your poison centre uses." },
        { id: "c-repeat", label: "I planned to repeat the level in four hours and plot it on the nomogram.", next: "s-no-nac", quality: "unsafe", feedback: "Unsafe. The nomogram cannot be used when the time is unknown. She may be close to or past 8 hours from ingestion, when delay raises the risk of liver injury. Start acetylcysteine now and reassess at the end of the infusion." },
      ],
    },
    {
      kind: "say",
      id: "s-no-nac",
      phase: "Poison centre call",
      text:
        "The poison centre specialist says the nomogram does not apply with an unknown ingestion time. She could be close to or past 8 hours from ingestion, when delay raises the risk of liver injury. They advise starting acetylcysteine now. You start it.",
      next: "s-later",
    },
    {
      kind: "say",
      id: "s-later",
      phase: "Two days later",
      text:
        "You are back on shift. She was extubated in the ICU yesterday. Her QRS is 88 ms, acetaminophen is undetectable and ALT is 44. " +
        "She is in your ED observation area waiting for psychiatry in the morning. She is dressed and says, 'I am fine now. I am going home.' Her partner is not here.",
      next: "q-risk",
    },
    {
      kind: "question",
      id: "q-risk",
      phase: "Risk and capacity",
      prompt: "How will you assess her suicide risk and her capacity to refuse psychiatric assessment?",
      seconds: 90,
      modelAnswer: [
        "Ask directly about intent, plan and whether she regrets surviving.",
        "Weigh the note, the severity of the ingestion, the prior attempt, the job loss and her supports.",
        "Assess capacity: understanding, appreciation of risk, reasoning and a stable choice.",
        "Get collateral from her partner with her consent, or without it if needed to prevent serious harm.",
      ],
      rubric: ["od-m1"],
      next: "q-form1",
    },
    {
      kind: "question",
      id: "q-form1",
      phase: "Leaving",
      prompt: "She walks toward the exit. What legal authority do you have to keep her, what paperwork is needed, and what must she be given?",
      seconds: 90,
      modelAnswer: [
        "Keep her safe now, using the least restrictive means.",
        "Form 1 under the Ontario Mental Health Act when the criteria are met.",
        "Form 1 allows detention up to 72 hours in a Schedule 1 facility for psychiatric assessment. If this hospital is not one, it authorizes transfer to one.",
        "The physician must have examined her within the past 7 days.",
        "Give her a Form 42 and explain her rights.",
        "Close observation and removal of means of self harm.",
      ],
      rubric: ["od-m2", "od-m3", "od-m4", "od-m5"],
      choices: [
        {
          id: "c-form1",
          label: "I kept her safely, completed a Form 1, gave her a Form 42 and arranged close observation.",
          next: "end",
          quality: "strong", feedback: "Strong. A serious attempt with a note, a prior attempt and recent job loss puts her at high risk. A Form 1 allows detention for up to 72 hours for psychiatric assessment. She must receive a Form 42.",
        },
        {
          id: "c-let-go",
          label: "She seemed calm and said she felt fine, so I let her go with a crisis line number.",
          next: "s-left",
          quality: "unsafe", feedback: "Unsafe. A calm presentation after a near lethal overdose does not mean low risk. She had a note and a prior attempt. The examiner wanted a structured risk assessment and a Form 1.",
        },
      ],
    },
    {
      kind: "say",
      id: "s-left",
      phase: "Three hours later",
      text:
        "Her partner phones the department. She has not come home and is not answering her phone. Police are asked to do a wellness check. Her risk factors were high and she had not been assessed by psychiatry.",
      next: "end",
    },
    { kind: "end", id: "end", text: "That is the end of the case." },
  ],
  rubric: [
    {
      id: "od-r1",
      competency: "assessment",
      criterion: "physical",
      text: "Identifies QRS over 100 ms and terminal R in aVR over 3 mm as signs of sodium channel blockade.",
      points: 2,
      teaching: "In tricyclic toxicity, QRS width predicts seizures and dysrhythmias better than the drug level does.",
      source: "gemnet-tca",
    },
    {
      id: "od-r2",
      competency: "resuscitation",
      criterion: "management",
      text: "Gives sodium bicarbonate 1 to 2 mEq/kg IV bolus (60 to 120 mEq), repeated to a QRS under 100 ms with the pH kept at 7.55 or lower.",
      points: 3,
      critical: true,
      teaching: "The sodium load and alkalemia overcome sodium channel blockade. Bolus first. An infusion alone is too slow.",
      source: "bicarb-review",
    },
    {
      id: "od-r3",
      competency: "management",
      criterion: "management",
      text: "Starts a bicarbonate infusion, e.g. 150 mEq in 1 L D5W at 150 to 250 mL/h, and monitors potassium, sodium and pH.",
      points: 1,
      teaching: "Alkalinization drives potassium into cells. Check electrolytes and gas often and replace potassium.",
      source: "bicarb-review",
    },
    {
      id: "od-r4",
      competency: "resuscitation",
      criterion: "management",
      text: "Treats hypotension with fluid, more bicarbonate and norepinephrine, and knows lipid emulsion and ECMO are rescue options.",
      points: 2,
      teaching: "Refractory tricyclic shock may respond to lipid emulsion or need ECMO. Involve the poison centre early.",
      source: "gemnet-tca",
    },
    {
      id: "od-s1",
      competency: "resuscitation",
      criterion: "management",
      text: "Treats the seizure with a benzodiazepine, e.g. lorazepam 2 to 4 mg IV or midazolam 5 mg IV, and avoids phenytoin.",
      points: 3,
      critical: true,
      teaching: "Phenytoin blocks sodium channels and can worsen cardiotoxicity. Benzodiazepines are first line for toxic seizures.",
      source: "gemnet-tca",
    },
    {
      id: "od-s2",
      competency: "management",
      criterion: "management",
      text: "Gives additional bicarbonate after the seizure because acidosis worsens toxicity.",
      points: 1,
      teaching: "Seizures cause lactic acidosis. A lower pH increases free tricyclic and widens the QRS.",
      source: "gemnet-tca",
    },
    {
      id: "od-s3",
      competency: "resuscitation",
      criterion: "management",
      text: "Gives a bicarbonate bolus before induction and minimizes apnea time.",
      points: 2,
      teaching: "During apnea the pCO2 rises and pH falls. A pre induction bolus buys protection.",
      source: "gemnet-tca",
    },
    {
      id: "od-s4",
      competency: "resuscitation",
      criterion: "management",
      text: "Uses reduced dose induction in hypotension, e.g. ketamine 0.5 to 1 mg/kg, with rocuronium 1.2 to 1.5 mg/kg.",
      points: 1,
      teaching: "A hypotensive patient needs less induction agent. Full dose paralysis gives the best first pass conditions.",
      source: "gemnet-tca",
    },
    {
      id: "od-s5",
      competency: "management",
      criterion: "management",
      text: "Sets a high respiratory rate after intubation to avoid respiratory acidosis and targets pH 7.50 to 7.55.",
      points: 2,
      teaching: "The ventilator must match the patient's own high minute ventilation. Check a gas soon after.",
      source: "gemnet-tca",
    },
    {
      id: "od-t1",
      competency: "assessment",
      criterion: "physical",
      text: "Estimates the amitriptyline dose per kg and recognizes it as severe.",
      points: 1,
      teaching: "Tricyclic ingestions over about 10 mg/kg can be life threatening.",
      source: "gemnet-tca",
    },
    {
      id: "od-t2",
      competency: "assessment",
      criterion: "physical",
      text: "Sends acetaminophen, salicylate, ethanol, pregnancy test and electrolytes.",
      points: 1,
      teaching: "Every intentional overdose needs an acetaminophen level. Co ingestions are common and often silent early.",
      source: "chiew-apap",
    },
    {
      id: "od-t3",
      competency: "management",
      criterion: "management",
      text: "Starts acetylcysteine for a detectable acetaminophen level with an unknown time of ingestion.",
      points: 3,
      critical: true,
      teaching: "The nomogram needs a known time. If the time is unknown and the level is detectable, treat.",
      source: "chiew-apap",
    },
    {
      id: "od-t4",
      competency: "management",
      criterion: "management",
      text: "States a correct acetylcysteine regimen, e.g. 200 mg/kg over 4 hours then 100 mg/kg over 16 hours, or the local poison centre regimen.",
      points: 2,
      teaching: "Know one regimen well. Regimens differ between provincial poison centres. Recheck the acetaminophen level, liver tests and INR before stopping the infusion.",
      source: "chiew-apap",
    },
    {
      id: "od-t5",
      competency: "management",
      criterion: "management",
      text: "Gives activated charcoal only if the airway is protected and after discussion with the poison centre.",
      points: 1,
      teaching: "Charcoal in a drowsy patient who is about to seize risks aspiration. Protect the airway first.",
      source: "gemnet-tca",
    },
    {
      id: "od-c1",
      competency: "communication",
      criterion: "process",
      text: "Calls the Ontario Poison Centre early.",
      points: 1,
      teaching: "The poison centre gives real time advice on targets, rescue therapies and co ingestions.",
      source: "gemnet-tca",
    },
    {
      id: "od-c2",
      competency: "communication",
      criterion: "history",
      text: "Obtains collateral from the partner including the note and prior attempt.",
      points: 1,
      teaching: "Collateral shapes both the medical plan and the later suicide risk assessment.",
      source: "cpsi-suicide",
    },
    {
      id: "od-c3",
      competency: "disposition",
      criterion: "process",
      text: "Admits to ICU with a clear handover of bicarbonate targets and acetylcysteine timing.",
      points: 1,
      teaching: "State the QRS and pH targets and the start time of each acetylcysteine bag.",
      source: "gemnet-tca",
    },
    {
      id: "od-m1",
      competency: "assessment",
      criterion: "history",
      text: "Performs a structured suicide risk assessment including intent, plan, note, prior attempt and supports.",
      points: 2,
      teaching: "A calm patient after a serious attempt can still be at high risk. Ask directly about intent.",
      source: "cpsi-suicide",
    },
    {
      id: "od-m2",
      competency: "disposition",
      criterion: "process",
      text: "Does not let her leave and uses a Form 1 under the Ontario Mental Health Act when criteria are met.",
      points: 3,
      critical: true,
      teaching: "A recent serious attempt with a note is high risk. A Form 1 allows safe assessment by psychiatry.",
      source: "mha",
    },
    {
      id: "od-m3",
      competency: "professionalism",
      criterion: "process",
      text: "Knows a Form 1 allows detention up to 72 hours for psychiatric assessment and requires an exam within the past 7 days.",
      points: 1,
      teaching: "The form must be completed by a physician who personally examined the patient in the past 7 days.",
      source: "mha",
    },
    {
      id: "od-m4",
      competency: "professionalism",
      criterion: "process",
      text: "Gives her a Form 42 and explains her rights.",
      points: 1,
      teaching: "Form 42 tells the patient why she is held and that she can speak to a lawyer.",
      source: "mha",
    },
    {
      id: "od-m5",
      competency: "disposition",
      criterion: "process",
      text: "Uses the least restrictive measures, arranges close observation, and removes means of self harm.",
      points: 1,
      teaching: "Start with talking and observation. Use restraint only when needed for safety.",
      source: "cpsi-suicide",
    },
    {
      id: "od-h1",
      competency: "assessment",
      criterion: "history",
      text: "Asks what was taken, how much, when and with what, including alcohol, and when she was last seen well.",
      points: 3,
      teaching: "The ingestion history sets the dose per kg and the timeline for co ingestants. With an unknown time, treat from the time she was last seen well.",
      source: "gemnet-tca",
    },
    {
      id: "od-h2",
      competency: "assessment",
      criterion: "history",
      text: "Asks about past psychiatric history, prior overdoses, other prescribed medications and substance use.",
      points: 2,
      teaching: "A prior overdose raises the risk of another. Other medications and drugs change both the toxidrome and the treatment.",
      source: "cpsi-suicide",
    },
    {
      id: "od-x1",
      competency: "assessment",
      criterion: "physical",
      text: "Examines for a toxidrome: level of consciousness, pupils, skin, mucous membranes, bowel sounds, bladder, reflexes and clonus.",
      points: 2,
      teaching: "Dilated pupils, dry flushed skin, reduced bowel sounds and urinary retention point to an anticholinergic toxidrome. Clonus and rigidity would point to serotonin toxicity instead.",
      source: "gemnet-tca",
    },
    {
      id: "od-p1",
      competency: "resuscitation",
      criterion: "process",
      text: "Reassesses QRS width, blood pressure and pH after each bicarbonate bolus and after every change in her condition.",
      points: 1,
      teaching: "Bicarbonate is titrated to the ECG and the gas. Recheck after each bolus so you neither undertreat nor push the pH above 7.55.",
      source: "bicarb-review",
    },
  ],
  sources: [
    {
      id: "gemnet-tca",
      citation: "Body R, et al. Guidelines in Emergency Medicine Network (GEMNet). Guideline for the management of tricyclic antidepressant overdose. Emergency Medicine Journal. 2011.",
      url: "https://pubmed.ncbi.nlm.nih.gov/21436332/",
    },
    {
      id: "bicarb-review",
      citation: "Bruccoleri RE, Burns MM. A literature review of the use of sodium bicarbonate for the treatment of QRS widening. Journal of Medical Toxicology. 2016.",
      url: "https://pubmed.ncbi.nlm.nih.gov/26159649/",
    },
    {
      id: "chiew-apap",
      citation: "Chiew AL, et al. Updated guidelines for the management of paracetamol poisoning in Australia and New Zealand. Medical Journal of Australia. 2020.",
      url: "https://pubmed.ncbi.nlm.nih.gov/31786822/",
    },
    { id: "mha", citation: "Mental Health Act, R.S.O. 1990, c. M.7. Ontario.", url: "https://www.ontario.ca/laws/statute/90m07" },
    {
      id: "cpsi-suicide",
      citation: "Mental Health Commission of Canada and Canadian Patient Safety Institute. Suicide Risk Assessment Toolkit. A resource for healthcare workers and organizations. 2021.",
      url: "https://www.mentalhealthcommission.ca/wp-content/uploads/drupal/2021-01/mhcc_cpsi_suicide_risk_assessment_toolkit_eng.pdf",
    },
  ],
  reviewed: false,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 2,
};
