// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const trauma: OralCase = {
  id: "trauma-motorcycle",
  title: "Motorcycle collision at a regional hospital",
  blueprint: "trauma",
  alsoCovers: ["resus", "systems"],
  priorityTopic: "multiple-trauma",
  keyFeatures: [
    { topic: "multiple-trauma", n: 1 },
    { topic: "multiple-trauma", n: 2 },
    { topic: "multiple-trauma", n: 6 },
    { topic: "multiple-trauma", n: 7 },
    { topic: "multiple-trauma", n: 8 },
    { topic: "airway", n: 4 },
  ],
  summary: "A 27 year old motorcyclist arrives by ground ambulance to a hospital that is not a trauma centre.",
  durationMinutes: 12,
  stem:
    "You are working in the emergency department of a community hospital when the following patient arrives. It is not a trauma centre, and the lead trauma hospital is 70 minutes away by Ornge helicopter. " +
    "A 27 year old man arrives by ambulance 40 minutes after his motorcycle hit a guardrail at highway speed.",
  card: {
    vitals: {
      temperature: "35.4°C",
      pulse: "136/minute",
      resp: "30/minute",
      bp: "76/48 mmHg",
      o2sat: "89% on a non rebreather mask",
      weight: "85 kg (187 lb), estimated",
    },
    medications: "None",
    allergies: "None",
  },
  findings: [
    {
      id: "hpi",
      label: "Injury and prehospital history",
      result:
        "His motorcycle hit a guardrail at highway speed about 40 minutes before arrival. He says his chest and his hips hurt. " +
        "Paramedics gave 500 mL of normal saline and placed a cervical collar. No tranexamic acid was given.",
    },
    { id: "airway", label: "Airway", result: "Talking in short sentences. No stridor. No blood in the mouth. Cervical collar in place." },
    {
      id: "chest",
      label: "Breathing and chest exam",
      result:
        "Trachea midline. Reduced air entry on the left with dullness at the left base. Subcutaneous emphysema over the left lateral chest. " +
        "Crepitus over left ribs 4 to 8. No flail segment. Right chest normal.",
    },
    {
      id: "circulation",
      label: "Circulation",
      result: "Cool and pale peripheries. Weak radial pulses. Capillary refill 4 seconds. No external hemorrhage apart from abrasions. Neck veins flat.",
    },
    {
      id: "pelvis",
      label: "Pelvis and perineum",
      result:
        "Pain on gentle palpation of the pelvis. It is not sprung. Scrotal swelling and bruising. No blood at the urethral meatus. Legs equal in length.",
    },
    {
      id: "efast",
      label: "eFAST",
      result:
        "Free fluid in Morison pouch and in the splenorenal space. No pericardial effusion. Lung sliding absent over the upper left anterior chest. " +
        "Large anechoic collection above the left diaphragm. Right lung sliding present with no effusion.",
    },
    {
      id: "cxr",
      label: "Chest X ray",
      result: "Large left hemopneumothorax with fractures of left ribs 4 to 8. Mediastinum of normal width. Right lung clear.",
    },
    {
      id: "pelvic-xray",
      label: "Pelvic X ray",
      result: "Pubic symphysis diastasis of 4 cm. Widening of the right sacroiliac joint. Consistent with an open book pelvic fracture.",
    },
    {
      id: "disability",
      label: "Disability",
      result: "GCS 13 (E3 V4 M6). Pupils 3 mm, equal and reactive. Moves all four limbs. Left temporal scalp hematoma. He cannot remember the crash.",
    },
    {
      id: "exposure",
      label: "Exposure and secondary survey",
      result:
        "Temperature 35.4. Abdomen distended and tender in the left upper quadrant with guarding. Abrasions on the left flank. " +
        "Log roll shows no step off. No limb deformities. Helmet was cracked on the left side per paramedics.",
    },
    {
      id: "ample",
      label: "AMPLE history",
      result: "No allergies. No medications. Healthy. Last meal 3 hours ago.",
    },
    {
      id: "friend",
      label: "Collateral from his friend",
      result: "He had two beers earlier in the evening.",
    },
    {
      id: "labs",
      label: "Blood gas and labs",
      result:
        "pH 7.21. Base excess minus 9. Lactate 6.4 mmol/L. Hemoglobin 98 g/L. Platelets 188 x 10^9/L. INR 1.4. Fibrinogen 1.3 g/L. " +
        "Capillary glucose at triage 8.4 mmol/L. Ionized calcium 1.02 mmol/L. Potassium 4.2 mmol/L. Ethanol 12 mmol/L.",
    },
    {
      id: "chest-tube",
      label: "Chest tube output",
      result: "The left chest tube drained 1,100 mL of blood immediately. Another 180 mL collects over the next 30 minutes.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "Resus",
      text:
        "He is on the stretcher in resus. Triage made him CTAS 1. His GCS is 13. He is pale and sweaty. You have two nurses, a respiratory therapist and a lab tech. " +
        "CT is available. The general surgeon on call is at home, about 40 minutes away. The blood bank holds 4 units of O negative and 6 units of O positive red cells. " +
        "Frozen plasma takes about 25 minutes to thaw. Fibrinogen concentrate is stocked. The nurse asks, 'The team is here. What do you want?'",
      next: "q-primary",
    },
    {
      kind: "question",
      id: "q-primary",
      phase: "Primary survey",
      prompt: "Take me through your primary survey. How do you run the team, and what bedside imaging do you want?",
      seconds: 115,
      modelAnswer: [
        "Assign roles out loud. Use closed loop communication.",
        "Airway with cervical spine protection. Breathing. Circulation. Disability. Exposure.",
        "Two large bore IVs or IO. Warm the patient and all fluids and products.",
        "eFAST, portable chest X ray and pelvic X ray in resus.",
        "Do interventions as you find problems, not after the survey.",
        "AMPLE history, mechanism, prehospital fluids and tranexamic acid, and head injury symptoms.",
        "Secondary survey with log roll, perineum and a neurological exam once the primary survey is done.",
      ],
      rubric: ["tr-p1", "tr-p4", "tr-p5", "tr-a1", "tr-a2", "tr-a3", "tr-x1"],
      next: "q-chest",
    },
    {
      kind: "question",
      id: "q-chest",
      phase: "Breathing",
      prompt: "His left chest is dull with reduced air entry and subcutaneous emphysema. SpO2 is 89 percent. What will you do, and how?",
      seconds: 57,
      modelAnswer: [
        "Left hemopneumothorax until proven otherwise.",
        "Finger thoracostomy in the 4th or 5th intercostal space, mid axillary line.",
        "Then a chest tube on the same side.",
        "Note the initial output and hourly output.",
      ],
      rubric: ["tr-p2"],
      choices: [
        { id: "c-tube", label: "I did a finger thoracostomy and placed a left chest tube.", next: "q-blood", quality: "strong", feedback: "Strong. Hypoxia, shock and unilateral signs mean you open the chest now. Finger thoracostomy then a chest tube in the 4th or 5th space, mid axillary line. Record the initial output. Over 1,500 mL is a massive hemothorax." },
        { id: "c-xray-first", label: "I waited for a chest X ray to confirm it first.", next: "s-xray-wait", quality: "partial", feedback: "Partial. A chest X ray should not delay decompression in a hypoxic, shocked patient. The clinical signs are enough. The examiner wanted a finger thoracostomy and chest tube during the primary survey." },
      ],
    },
    {
      kind: "say",
      id: "s-xray-wait",
      phase: "Ten minutes later",
      text: "The X ray tech is in another room. His SpO2 falls to 83 percent and his pressure to 68/40. You do a finger thoracostomy and place a chest tube.",
      next: "q-blood",
    },
    {
      kind: "question",
      id: "q-blood",
      phase: "Circulation",
      prompt: "What is your first blood product, how many units, and will you give more saline? What is your blood pressure target?",
      seconds: 57,
      modelAnswer: [
        "Activate the massive hemorrhage protocol now.",
        "Uncrossmatched O red cells. O positive is fine for an adult male.",
        "No more crystalloid.",
        "Red cells to plasma about 1 to 1, with platelets per protocol.",
        "Permissive hypotension, systolic about 80 to 90, until bleeding is controlled. His head injury looks mild now. Raise the target if his GCS falls.",
      ],
      rubric: ["tr-h1", "tr-h3", "tr-h6"],
      choices: [
        {
          id: "c-mhp",
          label: "I activated the massive hemorrhage protocol and gave uncrossmatched red cells, with no more saline.",
          next: "q-txa",
          quality: "strong", feedback: "Strong. Activate the massive hemorrhage protocol early and stop crystalloid. Uncrossmatched O red cells first, then plasma at about 1 to 1. O positive is acceptable for an adult male.",
        },
        { id: "c-saline", label: "I gave two more litres of warmed normal saline first.", next: "s-crystalloid", quality: "unsafe", feedback: "Unsafe. Crystalloid dilutes clotting factors and worsens acidosis and hypothermia. A patient with systolic under 90 and ongoing bleeding needs blood. The examiner wanted the massive hemorrhage protocol activated now." },
      ],
    },
    {
      kind: "say",
      id: "s-crystalloid",
      phase: "Twenty minutes later",
      text:
        "His pressure is 64/38. Hemoglobin is 72 g/L. INR is 1.9. Temperature is 34.8. Saline has diluted his clotting factors and cooled him. You activate the massive hemorrhage protocol.",
      next: "q-txa",
    },
    {
      kind: "question",
      id: "q-txa",
      phase: "Hemorrhage control",
      prompt: "When and how will you give tranexamic acid? Where exactly do you place the pelvic binder?",
      seconds: 57,
      modelAnswer: [
        "Tranexamic acid 1 g IV over 10 minutes now.",
        "Then 1 g IV over 8 hours.",
        "Only within 3 hours of injury. Benefit falls with every minute of delay.",
        "Pelvic binder centred over the greater trochanters.",
        "Not over the iliac crests.",
      ],
      rubric: ["tr-h2", "tr-p3"],
      choices: [
        {
          id: "c-txa-binder",
          label: "I gave tranexamic acid 1 g over 10 minutes and placed the binder over the greater trochanters.",
          next: "s-ct-request",
          quality: "strong", feedback: "Strong. Tranexamic acid 1 g over 10 minutes within 3 hours of injury, then 1 g over 8 hours. The binder belongs over the greater trochanters. Both are quick and reduce bleeding.",
        },
        { id: "c-crests", label: "I placed the binder at the level of the iliac crests.", next: "s-binder", quality: "partial", feedback: "Partial. A binder over the iliac crests does not close the pelvic ring. Centre it over the greater trochanters. Recheck the pelvic film after placement." },
        { id: "c-hold-txa", label: "I held tranexamic acid until CT confirmed where he was bleeding.", next: "s-txa-delay", quality: "unsafe", feedback: "Unsafe. Tranexamic acid works best when given early. Its benefit falls with every minute of delay and it may harm after 3 hours. Give 1 g IV over 10 minutes as soon as significant bleeding is suspected." },
      ],
    },
    {
      kind: "say",
      id: "s-binder",
      phase: "Pelvic X ray",
      text: "The repeat pelvic film shows the symphysis still widened. A binder over the iliac crests does not close the pelvic ring. You move it down to the greater trochanters.",
      next: "s-ct-request",
    },
    {
      kind: "say",
      id: "s-txa-delay",
      phase: "Later",
      text:
        "He is now close to 90 minutes from injury. The benefit of tranexamic acid falls with each minute of delay. After 3 hours it may cause harm. You give 1 g now.",
      next: "s-ct-request",
    },
    {
      kind: "say",
      id: "s-ct-request",
      phase: "Ongoing bleeding",
      text:
        "The left chest tube drained 1,100 mL of blood immediately. After 2 units of red cells his heart rate is 142 and pressure 70/42. " +
        "The radiologist phones and says, 'Send him for a CT pan scan before he leaves so the trauma centre has images. It will only take 15 minutes.'",
      next: "q-ct",
    },
    {
      kind: "question",
      id: "q-ct",
      phase: "Decision",
      prompt: "What do you say to the radiologist? Where is he bleeding from? Your local surgeon offers a damage control laparotomy here. How do you decide?",
      seconds: 86,
      modelAnswer: [
        "An unstable patient does not go to CT.",
        "Sources are chest, abdomen and pelvis.",
        "Call the lead trauma hospital now through CritiCall.",
        "Local damage control surgery versus immediate transfer is a shared decision with the trauma team leader and surgeon.",
        "Consider transfer time, surgeon skill and response to blood.",
        "Chest tube output of 180 mL in 30 minutes is over 200 mL/h. Ongoing output like this points to thoracotomy.",
      ],
      rubric: ["tr-d1", "tr-d2", "tr-d3"],
      choices: [
        { id: "c-no-ct", label: "I declined the CT and kept him in resus while I called the trauma centre.", next: "q-labs", quality: "strong", feedback: "Strong. An unstable patient does not leave resus for imaging. The CT will not change the need for transfer or surgery. Call the lead trauma hospital now and discuss local damage control." },
        { id: "c-send-ct", label: "I sent him to CT with a nurse.", next: "s-ct-crash", quality: "unsafe", feedback: "Unsafe. The CT scanner is the wrong place for a patient with systolic 70 who is still bleeding. Resuscitation stops while he is there. The examiner wanted you to decline and call the trauma centre." },
      ],
    },
    {
      kind: "say",
      id: "s-ct-crash",
      phase: "In the scanner",
      text:
        "Halfway through the scan his pressure falls to 52/30. The nurse cannot reach the rapid infuser. You bring him back to resus. The call to the trauma centre has been delayed 25 minutes.",
      next: "q-labs",
    },
    {
      kind: "question",
      id: "q-labs",
      phase: "Labs",
      prompt: "His ionized calcium is 1.02 mmol/L, fibrinogen 1.3 g/L and temperature 35.2. What do you give?",
      seconds: 57,
      modelAnswer: [
        "Calcium chloride 1 g IV, or calcium gluconate 3 g IV.",
        "Keep ionized calcium above 1.1 mmol/L.",
        "Fibrinogen concentrate 3 to 4 g or cryoprecipitate 10 units per local protocol for fibrinogen at or under 1.5 g/L.",
        "Warm blankets, fluid warmer and a warm room.",
      ],
      rubric: ["tr-h4", "tr-h5"],
      next: "s-ttl",
    },
    {
      kind: "say",
      id: "s-ttl",
      phase: "CritiCall",
      text: "The trauma team leader at the lead trauma hospital is on the line. She says, 'I have two minutes. Tell me about him.'",
      next: "q-handover",
    },
    {
      kind: "question",
      id: "q-handover",
      phase: "Handover",
      prompt: "Give me your handover.",
      seconds: 86,
      modelAnswer: [
        "Use a structure such as MIST or SBAR.",
        "Mechanism, time of injury and injuries found.",
        "Vital sign trend and response to blood.",
        "Products given, tranexamic acid time, calcium and fibrinogen.",
        "Chest tube output, eFAST and X ray findings.",
        "Ask what else they want before flight.",
      ],
      rubric: ["tr-c1", "tr-c2"],
      next: "s-herniation",
    },
    {
      kind: "say",
      id: "s-herniation",
      phase: "Twenty minutes before the helicopter",
      text: "His GCS drops to 7. His left pupil is 6 mm and does not react. Blood pressure is 88/54 after more blood.",
      next: "q-tbi",
    },
    {
      kind: "question",
      id: "q-tbi",
      phase: "Head injury",
      prompt: "How does this change your blood pressure target? Talk me through your intubation, with drugs and doses.",
      seconds: 86,
      modelAnswer: [
        "Signs of herniation. Head injury now changes the target.",
        "Systolic at least 110 mmHg at his age. Avoid any hypotension.",
        "Give blood before induction.",
        "Ketamine 0.5 to 1 mg/kg with rocuronium 1.2 to 1.6 mg/kg.",
        "Push dose vasopressor ready.",
        "Head up with spine precautions. Loosen the collar if it compresses the neck veins.",
      ],
      rubric: ["tr-t1", "tr-t2", "tr-t5"],
      choices: [
        {
          id: "c-raise-target",
          label: "I raised my systolic target to 110, gave blood first, then intubated with reduced dose ketamine and rocuronium.",
          next: "q-icp",
          quality: "strong", feedback: "Strong. Herniation signs change the target. Systolic at least 110 mmHg at age 27 protects the brain. Blood first, then reduced dose ketamine about 0.5 to 1 mg/kg and rocuronium 1.2 to 1.6 mg/kg.",
        },
        { id: "c-propofol", label: "I kept my systolic target at 80 and intubated with propofol.", next: "s-propofol", quality: "unsafe", feedback: "Unsafe. A single episode of systolic under 90 or SpO2 under 90 percent worsens brain injury outcome. Permissive hypotension no longer applies. Propofol in hemorrhagic shock risks arrest." },
      ],
    },
    {
      kind: "say",
      id: "s-propofol",
      phase: "After induction",
      text: "His pressure falls to 58/30 and his SpO2 dips to 84 percent. A single episode of hypotension or hypoxia worsens outcome in brain injury. You give push dose phenylephrine and more blood.",
      next: "q-icp",
    },
    {
      kind: "question",
      id: "q-icp",
      phase: "Intracranial pressure",
      prompt: "What will you give for raised intracranial pressure, what would you avoid, and what are your ventilation targets?",
      seconds: 57,
      modelAnswer: [
        "Hypertonic saline, e.g. 3 percent 250 mL IV.",
        "Avoid mannitol while he is hypotensive.",
        "SpO2 above 94 percent.",
        "pCO2 35 to 40.",
        "Brief hyperventilation only as a bridge to surgery for active herniation.",
      ],
      rubric: ["tr-t3", "tr-t4"],
      next: "q-partner",
    },
    {
      kind: "question",
      id: "q-partner",
      phase: "Family",
      prompt: "His partner has just arrived in the waiting room. What will you tell her?",
      seconds: 57,
      modelAnswer: [
        "Meet her in a private room with a nurse or social worker.",
        "Explain he has serious bleeding and a head injury.",
        "Tell her he is going by helicopter to the trauma centre.",
        "Be honest that he is critically ill.",
        "Give her a way to get there and a contact.",
      ],
      rubric: ["tr-c3"],
      next: "end",
    },
    { kind: "end", id: "end", text: "The Ornge crew arrives and takes over. That is the end of the case." },
  ],
  rubric: [
    {
      id: "tr-p1",
      competency: "leadership",
      criterion: "process",
      text: "Runs a structured primary survey with clear team roles and closed loop communication.",
      points: 2,
      teaching: "Say roles out loud at the start. Closed loop orders prevent missed or duplicated tasks.",
      source: "atls",
    },
    {
      id: "tr-p2",
      competency: "resuscitation",
      criterion: "management",
      text: "Decompresses and drains the left chest with finger thoracostomy and a chest tube.",
      points: 3,
      critical: true,
      teaching: "A hypoxic, shocked patient with unilateral signs needs the chest opened now. Do not wait for an X ray.",
      source: "atls",
    },
    {
      id: "tr-p3",
      competency: "resuscitation",
      criterion: "management",
      text: "Places a pelvic binder centred over the greater trochanters, not the iliac crests.",
      points: 2,
      critical: true,
      teaching: "The binder closes the pelvic ring only when it sits over the greater trochanters.",
      source: "atls",
    },
    {
      id: "tr-p4",
      competency: "resuscitation",
      criterion: "management",
      text: "Obtains two large bore IVs or IO and warms the patient and all products.",
      points: 1,
      teaching: "Hypothermia worsens coagulopathy. Warm everything from the start.",
      source: "eu-bleeding",
    },
    {
      id: "tr-p5",
      competency: "assessment",
      criterion: "physical",
      text: "Uses eFAST, chest X ray and pelvic X ray at the bedside to find the source.",
      points: 1,
      teaching: "Bedside imaging finds the source without leaving resus.",
      source: "atls",
    },
    {
      id: "tr-h1",
      competency: "resuscitation",
      criterion: "management",
      text: "Activates the massive hemorrhage protocol early and stops crystalloid in favour of blood.",
      points: 3,
      critical: true,
      teaching: "Crystalloid dilutes clotting factors and worsens acidosis and hypothermia. Bleeding patients need blood.",
      source: "eu-bleeding",
    },
    {
      id: "tr-h2",
      competency: "management",
      criterion: "management",
      text: "Gives tranexamic acid 1 g IV over 10 minutes within 3 hours of injury, then 1 g over 8 hours.",
      points: 3,
      critical: true,
      teaching: "Tranexamic acid reduces death from bleeding when given early. After 3 hours it may cause harm.",
      source: "crash2",
    },
    {
      id: "tr-h3",
      competency: "management",
      criterion: "management",
      text: "Targets a balanced ratio of red cells to plasma of about 1 to 1 with platelets per protocol.",
      points: 2,
      teaching: "Balanced transfusion treats trauma coagulopathy. Ask for plasma to be thawed as soon as you activate.",
      source: "proppr",
    },
    {
      id: "tr-h4",
      competency: "management",
      criterion: "management",
      text: "Replaces calcium, e.g. calcium chloride 1 g IV, to keep ionized calcium above 1.1 mmol/L.",
      points: 1,
      teaching: "Citrate in blood products binds calcium. Low calcium worsens clotting and contractility.",
      source: "eu-bleeding",
    },
    {
      id: "tr-h5",
      competency: "management",
      criterion: "management",
      text: "Replaces fibrinogen at or under 1.5 g/L, e.g. fibrinogen concentrate 3 to 4 g or cryoprecipitate 10 units per local protocol.",
      points: 1,
      teaching: "Fibrinogen falls first in trauma bleeding. Replace it early.",
      source: "eu-bleeding",
    },
    {
      id: "tr-h6",
      competency: "management",
      criterion: "management",
      text: "Uses permissive hypotension with systolic about 80 to 90 while there is no sign of severe brain injury.",
      points: 1,
      teaching: "A lower target limits bleeding until surgical control. It does not apply with severe brain injury, where the European guideline targets a mean arterial pressure of at least 80 mmHg.",
      source: "eu-bleeding",
    },
    {
      id: "tr-d1",
      competency: "disposition",
      criterion: "process",
      text: "Declines CT for a hemodynamically unstable patient and explains why.",
      points: 2,
      teaching: "The CT scanner is a dangerous place for an unstable patient. The images will not change the need for transfer.",
      source: "atls",
    },
    {
      id: "tr-d2",
      competency: "assessment",
      criterion: "physical",
      text: "Identifies chest, abdomen and pelvis as bleeding sources.",
      points: 1,
      teaching: "Think of the five places to bleed: chest, abdomen, pelvis, long bones and the floor. Chest tube output over 1,500 mL at once, or about 200 mL/h for 2 to 4 hours, suggests the need for thoracotomy.",
      source: "atls",
    },
    {
      id: "tr-d3",
      competency: "leadership",
      criterion: "process",
      text: "Discusses local damage control surgery versus immediate transfer with the trauma team leader and surgeon.",
      points: 1,
      teaching: "When transfer is long and the patient is unstable, local damage control can save a life. Decide together.",
      source: "atls",
    },
    {
      id: "tr-c1",
      competency: "communication",
      criterion: "process",
      text: "Calls the lead trauma hospital through CritiCall early, before imaging is complete.",
      points: 2,
      teaching: "Call as soon as you know he needs a trauma centre. Transfer time is part of resuscitation.",
      source: "atls",
    },
    {
      id: "tr-c2",
      competency: "communication",
      criterion: "process",
      text: "Gives a concise structured handover, e.g. MIST or SBAR, with vital sign trend, products and tranexamic acid time.",
      points: 2,
      teaching: "A short structured handover lets the receiving team prepare the right room and people.",
      source: "atls",
    },
    {
      id: "tr-c3",
      competency: "communication",
      criterion: "process",
      text: "Speaks to the partner honestly and compassionately in a private space.",
      points: 1,
      teaching: "Families remember the first conversation. Be honest and give a clear next step.",
      source: "atls",
    },
    {
      id: "tr-t1",
      competency: "management",
      criterion: "physical",
      text: "Recognizes herniation and raises the systolic target to at least 110 mmHg for his age.",
      points: 2,
      teaching: "In brain injury, hypotension reduces cerebral perfusion. The Brain Trauma Foundation targets systolic at least 110 mmHg for ages 15 to 49 and over 70, and at least 100 mmHg for ages 50 to 69.",
      source: "btf",
    },
    {
      id: "tr-t2",
      competency: "resuscitation",
      criterion: "management",
      text: "Resuscitates before intubation and uses reduced dose induction, e.g. ketamine 0.5 to 1 mg/kg with rocuronium 1.2 to 1.6 mg/kg.",
      points: 2,
      teaching: "Shocked patients arrest at induction. Resuscitate first, cut the induction dose and raise the paralytic dose.",
      source: "atls",
    },
    {
      id: "tr-t3",
      competency: "management",
      criterion: "management",
      text: "Gives hypertonic saline, e.g. 3 percent 250 mL IV, and avoids mannitol while hypotensive.",
      points: 1,
      teaching: "Mannitol causes diuresis and can worsen hypotension. Hypertonic saline supports volume.",
      source: "btf",
    },
    {
      id: "tr-t4",
      competency: "management",
      criterion: "management",
      text: "Targets SpO2 above 94 percent and pCO2 35 to 40, with brief hyperventilation only as a bridge.",
      points: 1,
      teaching: "Hyperventilation lowers pressure by causing vasoconstriction. Prolonged use causes brain ischemia.",
      source: "btf",
    },
    {
      id: "tr-t5",
      competency: "management",
      criterion: "management",
      text: "Elevates the head of the bed with spine precautions and keeps the collar from obstructing venous return.",
      points: 1,
      teaching: "Head up about 30 degrees and a loose collar help venous drainage from the brain.",
      source: "btf",
    },
    {
      id: "tr-a1",
      competency: "assessment",
      criterion: "history",
      text: "Takes an AMPLE history: allergies, medications, past illness, last meal and events, including alcohol.",
      points: 3,
      teaching: "AMPLE is quick and changes care. Anticoagulants, a full stomach and alcohol all matter for bleeding, airway and head injury assessment.",
      source: "atls",
    },
    {
      id: "tr-a2",
      competency: "assessment",
      criterion: "history",
      text: "Asks about the mechanism and prehospital care: speed, helmet damage, time of injury, fluids given and whether tranexamic acid was given.",
      points: 3,
      teaching: "Mechanism predicts injury pattern. The time of injury and whether tranexamic acid was given decide whether you can still give it within 3 hours.",
      source: "crash2",
    },
    {
      id: "tr-a3",
      competency: "assessment",
      criterion: "history",
      text: "Asks about head injury symptoms: loss of consciousness, amnesia, headache and vomiting.",
      points: 2,
      teaching: "Amnesia for the crash and a cracked helmet mean a real head injury. Its severity later decides whether permissive hypotension is still safe.",
      source: "btf",
    },
    {
      id: "tr-x1",
      competency: "assessment",
      criterion: "physical",
      text: "Completes a secondary survey with a log roll, perineal exam, and neurological exam with GCS and pupils.",
      points: 2,
      teaching: "The secondary survey finds injuries the primary survey misses. Scrotal bruising suggests a pelvic fracture. A baseline GCS and pupils let you spot herniation later.",
      source: "atls",
    },
  ],
  sources: [
    {
      id: "atls",
      citation: "American College of Surgeons Committee on Trauma. Advanced Trauma Life Support. 11th edition. 2025.",
      url: "https://www.facs.org/quality-programs/trauma/education/advanced-trauma-life-support/atls-11/",
    },
    {
      id: "eu-bleeding",
      citation: "Rossaint R, et al. The European guideline on management of major bleeding and coagulopathy following trauma. Sixth edition. Critical Care. 2023.",
      url: "https://link.springer.com/article/10.1186/s13054-023-04327-7",
    },
    {
      id: "crash2",
      citation: "CRASH-2 trial collaborators, Shakur H, et al. Effects of tranexamic acid on death, vascular occlusive events, and blood transfusion in trauma patients with significant haemorrhage (CRASH-2). The Lancet. 2010.",
      url: "https://pubmed.ncbi.nlm.nih.gov/20554319/",
    },
    {
      id: "proppr",
      citation: "Holcomb JB, et al. Transfusion of plasma, platelets, and red blood cells in a 1:1:1 vs a 1:1:2 ratio and mortality in patients with severe trauma. The PROPPR randomized clinical trial. JAMA. 2015.",
      url: "https://pubmed.ncbi.nlm.nih.gov/25647203/",
    },
    {
      id: "btf",
      citation: "Carney N, et al. Guidelines for the management of severe traumatic brain injury, fourth edition. Brain Trauma Foundation. Neurosurgery. 2017.",
      url: "https://pubmed.ncbi.nlm.nih.gov/27654000/",
    },
  ],
  reviewed: false,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 2,
};
