// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Preceptor", version: 1 } as const;

const S = {
  ccsStemi: { id: "ccs-stemi", citation: "Wong GC, Welsford M, Ainsworth C, et al. 2019 Canadian Cardiovascular Society/Canadian Association of Interventional Cardiology guidelines on the acute management of ST-elevation myocardial infarction: focused update on regionalization and reperfusion. Can J Cardiol. 2019." },
  ccsAntiplatelet: { id: "ccs-antiplatelet", citation: "Mehta SR, Bainey KR, Cantor WJ, et al. 2018 Canadian Cardiovascular Society/Canadian Association of Interventional Cardiology focused update of the guidelines for the use of antiplatelet therapy. Can J Cardiol. 2018." },
  ccsAntiplatelet2023: { id: "ccs-antiplatelet-2023", citation: "Bainey KR, Marquis-Gravel G, Belley-Côté E, et al. Canadian Cardiovascular Society/Canadian Association of Interventional Cardiology 2023 focused update of the guidelines for the use of antiplatelet therapy. Can J Cardiol. 2024." },
  esc: { id: "esc-acs", citation: "Byrne RA, Rossello X, Coughlan JJ, et al. 2023 ESC Guidelines for the management of acute coronary syndromes. Eur Heart J. 2023." },
  chestPain: { id: "aha-chest-pain", citation: "Gulati M, Levy PD, Mukherjee D, et al. 2021 AHA/ACC/ASE/CHEST/SAEM/SCCT/SCMR guideline for the evaluation and diagnosis of chest pain. Circulation. 2021." },
  acc2013: { id: "acc-stemi-2013", citation: "O'Gara PT, Kushner FG, Ascheim DD, et al. 2013 ACCF/AHA guideline for the management of ST-elevation myocardial infarction. Circulation. 2013." },
  heart: { id: "heart", citation: "Six AJ, Backus BE, Kelder JC. Chest pain in the emergency room: value of the HEART score. Neth Heart J. 2008." },
  heartVal: { id: "heart-validation", citation: "Backus BE, Six AJ, Kelder JC, et al. A prospective validation of the HEART score for chest pain patients at the emergency department. Int J Cardiol. 2013." },
  udmi: { id: "udmi", citation: "Thygesen K, Alpert JS, Jaffe AS, et al. Fourth universal definition of myocardial infarction (2018). Circulation. 2018." },
  smith: { id: "smith-sgarbossa", citation: "Smith SW, Dodd KW, Henry TD, et al. Diagnosis of ST-elevation myocardial infarction in the presence of left bundle branch block with the ST-elevation to S-wave ratio in a modified Sgarbossa rule. Ann Emerg Med. 2012." },
  wellens: { id: "wellens", citation: "de Zwaan C, Bär FW, Wellens HJ. Characteristic electrocardiographic pattern indicating a critical stenosis high in left anterior descending coronary artery in patients admitted because of impending myocardial infarction. Am Heart J. 1982." },
  pericard: { id: "esc-pericardial", citation: "Adler Y, Charron P, Imazio M, et al. 2015 ESC Guidelines for the diagnosis and management of pericardial diseases. Eur Heart J. 2015." },
  tox2023: { id: "aha-tox-2023", citation: "Lavonas EJ, Akpunonu PD, Arens AM, et al. 2023 American Heart Association focused update on the management of patients with cardiac arrest or life-threatening toxicity due to poisoning. Circulation. 2023." },
  cocaine: { id: "aha-cocaine", citation: "McCord J, Jneid H, Hollander JE, et al. Management of cocaine-associated chest pain and myocardial infarction: a scientific statement from the American Heart Association Acute Cardiac Care Committee. Circulation. 2008." },
  commit: { id: "commit", citation: "Chen ZM, Pan HC, Chen YP, et al. (COMMIT collaborative group). Early intravenous then oral metoprolol in 45,852 patients with acute myocardial infarction: randomised placebo-controlled trial. Lancet. 2005." },
  acls: { id: "aha-acls", citation: "Panchal AR, Bartos JA, Cabañas JG, et al. Part 3: adult basic and advanced life support. 2020 American Heart Association guidelines for cardiopulmonary resuscitation and emergency cardiovascular care. Circulation. 2020." },
  esc2023: { id: "esc-acs-2023", citation: "Byrne RA, Rossello X, Coughlan JJ, et al. 2023 ESC Guidelines for the management of acute coronary syndromes. Eur Heart J. 2023, volume 44, pages 3720 to 3826. Sections 3.3, 5 and 12.3.7 on cancer.", url: "https://doi.org/10.1093/eurheartj/ehad191" },
  culprit: { id: "culprit-shock", citation: "Thiele H, Akin I, Sandri M, et al. PCI strategies in patients with acute myocardial infarction and cardiogenic shock. N Engl J Med. 2017." },
} satisfies Record<string, Source>;

const TOPIC = "ischemic-heart-disease";

export const ISCHEMIC_HEART_DISEASE_SAMPS: Samp[] = [
  {
    id: "ischemic-heart-disease-01",
    topic: TOPIC,
    title: "Chest pain in a snowstorm",
    stem:
      "You work at a rural hospital without a catheterization laboratory. The nearest PCI centre is 3 hours away by road and air transport is grounded by a snowstorm. A 64-year-old man presents with 70 minutes of crushing chest pain and nausea. He has hypertension and smokes. Oxygen saturation is 96%. His ECG shows 3 mm ST elevation in II, III and aVF, with more elevation in III than in II, and ST depression in I and aVL.",
    vitals: { pulse: "58/minute", resp: "18/minute", bp: "104/64 mmHg", weight: "84 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What ECG findings do you look for to identify right ventricular involvement?",
        accept: [
          { id: "v4r", text: "ST elevation in right sided lead V4R", match: ["v4r", "right sided", "right side"] },
          { id: "iii", text: "ST elevation in III greater than in II", match: ["iii ii", "iii greater"] },
          { id: "v1", text: "ST elevation in V1 with an inferior STEMI", match: ["v1"] },
        ],
        explanation:
          "Right ventricular infarction complicates many inferior STEMIs from a proximal right coronary occlusion. ST elevation of 1 mm or more in V4R is the most useful sign. Greater elevation in III than II and ST elevation in V1 are clues on the standard ECG.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "acc-stemi-2013",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following reperfusion strategies is most appropriate for this patient?",
        options: [
          "Anticoagulation alone and transfer when the weather clears",
          "Tenecteplase only if the pain lasts more than 3 hours",
          "Tenecteplase within 30 minutes of arrival, then transfer",
          "Transfer by road for primary PCI",
          "Wait for the first troponin result before deciding",
        ],
        correct: 2,
        explanation:
          "Primary PCI is preferred only if first medical contact to device time can be kept within 120 minutes. Here it cannot. Fibrinolysis within 30 minutes of arrival, followed by transfer for angiography, is the pharmacoinvasive strategy recommended by the CCS.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        prompt: "What is the tenecteplase dose for this patient?",
        accept: [{ id: "dose", text: "Tenecteplase 45 mg IV bolus", match: ["tenecteplase 45 mg", "tenecteplase 45mg", "tnk 45 mg", "tnk 45mg", "45 mg"] }],
        unacceptable: [
          { text: "50 mg", match: ["50 mg", "50mg"] },
          { text: "40 mg", match: ["40 mg", "40mg"] },
        ],
        explanation:
          "Tenecteplase is dosed by weight in 5 mg steps from 30 mg under 60 kg to 50 mg at 90 kg or more. At 84 kg, in the 80 to 89 kg band, the dose is 45 mg. For patients aged 75 or older, STREAM-2 used half dose, and the 2023 ESC guideline and many Canadian regional protocols now advise it because of intracranial hemorrhage risk.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What absolute contraindications to fibrinolysis must you ask about?",
        accept: [
          { id: "ich", text: "Any prior intracranial hemorrhage", match: ["intracranial hemorrhage", "intracranial haemorrhage", "ich", "brain bleed", "hemorrhagic stroke"] },
          { id: "stroke", text: "Ischemic stroke within 3 months", match: ["stroke", "ischemic stroke"] },
          { id: "lesion", text: "Known cerebral vascular lesion such as an AVM", match: ["avm", "arteriovenous", "aneurysm", "vascular lesion"] },
          { id: "tumour", text: "Known intracranial neoplasm", match: ["tumour", "tumor", "neoplasm", "brain cancer", "brain mass"] },
          { id: "bleed", text: "Active internal bleeding or bleeding diathesis", match: ["active bleeding", "bleeding", "gi bleed", "bleed"] },
          { id: "dissection", text: "Suspected aortic dissection", match: ["dissection"] },
          { id: "trauma", text: "Significant head or facial trauma within 3 months", match: ["head trauma", "head injury", "facial trauma", "closed head"] },
          { id: "surg", text: "Intracranial or spinal surgery within 2 months", match: ["neurosurgery", "intracranial surgery", "spinal surgery", "brain surgery", "spine surgery"] },
          { id: "htn", text: "Severe uncontrolled hypertension unresponsive to treatment", match: ["uncontrolled hypertension", "severe hypertension", "uncontrolled blood pressure"] },
        ],
        unacceptable: [{ text: "Age over 75", match: ["over 75", "age 75"] }],
        explanation:
          "Always screen for these before fibrinolysis because intracranial hemorrhage is the most feared complication. An inferior STEMI can come from a dissection that involves the right coronary artery, so ask about tearing pain and check pulses and blood pressure in both arms. Advanced age raises bleeding risk and calls for dose reduction, but it is not a contraindication.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "acc-stemi-2013",
      },
      {
        id: "q5",
        kind: "short",
        required: 2,
        update: "Before you see him, a nurse gave nitroglycerin 0.4 mg SL for ongoing pain. Ten minutes later BP is 78/48 mmHg and pulse is 54/minute. His lungs are clear.",
        prompt: "What interventions do you perform now?",
        accept: [
          { id: "stop", text: "Stop nitrates", match: ["stop nitro", "hold nitro", "no more nitro", "stop nitroglycerin", "hold nitroglycerin", "no further nitro", "avoid nitrate", "stop nitrate", "hold nitrate", "no nitrate", "no nitro", "avoid nitro", "discontinue nitro", "discontinue nitrate", "withhold nitro", "withhold nitrate"] },
          { id: "fluid", text: "IV crystalloid bolus of 250 to 500 mL, repeated as needed", match: ["bolus", "fluid", "crystalloid", "saline", "ringer"] },
          { id: "legs", text: "Raise the legs", match: ["leg", "trendelenburg"] },
          { id: "atropine", text: "Atropine if symptomatic bradycardia", match: ["atropine"] },
          { id: "lysis", text: "Proceed with fibrinolysis without delay", match: ["tenecteplase", "reperfusion", "thrombolysis", "fibrinolysis", "tnk"] },
          { id: "ino", text: "Dobutamine or norepinephrine if hypotension persists", match: ["dobutamine", "norepinephrine", "inotrope", "vasopressor"] },
        ],
        unacceptable: [{ text: "Furosemide", match: ["furosemide", "lasix", "diuretic"], dangerous: true }],
        explanation:
          "Right ventricular infarction is preload dependent. Nitrates and diuretics can cause profound hypotension. Treat with fluids and stop nitrates. Reperfusion remains the definitive treatment.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "acc-stemi-2013",
      },
    ],
    sources: [S.ccsStemi, S.acc2013],
    ...META,
  },
  {
    id: "ischemic-heart-disease-02",
    topic: TOPIC,
    title: "Older woman who feels tired",
    stem:
      "A 79-year-old woman is brought in by her son with 2 days of fatigue, nausea and breathlessness on exertion. She denies chest pain. She has type 2 diabetes, hypertension and chronic kidney disease with a baseline eGFR of 48 mL/minute. Her lungs are clear. ECG shows sinus rhythm with 1.5 mm horizontal ST depression in V4 to V6, I and aVL. The first high sensitivity troponin T is 88 ng/L (99th percentile 14 ng/L).",
    vitals: { pulse: "96/minute", resp: "20/minute", bp: "152/84 mmHg", o2sat: "96% on room air", weight: "62 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What characteristics of this patient make an atypical presentation of ACS more likely?",
        accept: [
          { id: "age", text: "Older age", match: ["age", "older", "elderly", "79"] },
          { id: "sex", text: "Female sex", match: ["female", "woman", "sex"] },
          { id: "dm", text: "Diabetes", match: ["diabetes", "diabetic"] },
          { id: "ckd", text: "Chronic kidney disease", match: ["kidney", "renal", "ckd"] },
        ],
        explanation:
          "Older adults, women, people with diabetes and those with kidney disease often present without chest pain. Fatigue, dyspnea and nausea may be the only symptoms. These patients have higher mortality partly because the diagnosis is delayed.",
        keyFeature: { topic: TOPIC, n: 5 },
        source: "aha-chest-pain",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "Which tests do you repeat to complete her assessment, and when?",
        accept: [
          { id: "trop", text: "Repeat high sensitivity troponin at 1 to 3 hours per the local algorithm", match: ["troponin", "trop"] },
          { id: "ecg", text: "Repeat ECG within 15 to 30 minutes and with any new symptoms", match: ["ecg", "electrocardiogram", "ekg"] },
          { id: "st", text: "Continuous ST segment or cardiac monitoring", match: ["st segment monitoring", "continuous monitoring", "telemetry", "cardiac monitor"] },
        ],
        explanation:
          "A single troponin and ECG are a snapshot. Serial troponin measurement defines the rise and fall that confirms acute MI. Serial ECGs capture dynamic ischemia.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "esc-acs",
      },
      {
        id: "q3",
        kind: "single",
        update: "Her repeat troponin at 1 hour is 142 ng/L. She is pain free with stable vital signs.",
        prompt: "Which of the following management plans is most appropriate for her?",
        options: [
          "Admission for medical therapy without angiography",
          "Admit, antithrombotics, invasive angiography within 24 hours",
          "CT coronary angiography before discharge from the department",
          "Immediate catheterization laboratory activation",
          "Outpatient stress test within 1 week",
        ],
        correct: 1,
        explanation:
          "She has an NSTEMI with dynamic ST depression, which places her at high risk. An early invasive strategy within 24 hours is recommended. Age alone is not a reason to withhold angiography. Fibrinolysis does not help and causes harm in NSTE-ACS.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
    ],
    sources: [S.chestPain, S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-03",
    topic: TOPIC,
    title: "Young man with sharp chest pain after a cold",
    stem:
      "A 27-year-old man presents with 3 days of sharp central chest pain that is worse lying flat and with deep breaths, and better sitting forward. He had a cold 10 days ago. Oxygen saturation is 98%. His ECG shows 1.5 to 2 mm concave ST elevation in I, II, aVL, aVF and V2 to V6, with PR depression in the same leads, PR elevation in aVR and no reciprocal ST depression except in aVR. The first high sensitivity troponin is normal.",
    vitals: { temperature: "37.9°C", pulse: "98/minute", resp: "18/minute", bp: "124/76 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What ECG features favour pericarditis over STEMI?",
        accept: [
          { id: "diffuse", text: "Diffuse ST elevation not confined to one coronary territory", match: ["diffuse", "widespread", "multiple territories", "territory", "territorial"] },
          { id: "prd", text: "PR depression", match: ["pr depression"] },
          { id: "avr", text: "PR elevation in aVR", match: ["pr elevation", "pr avr", "elevated pr"] },
          { id: "recip", text: "No reciprocal ST depression apart from aVR and V1", match: ["reciprocal", "no st depression", "no reciprocal", "without reciprocal"] },
          { id: "concave", text: "Concave or saddle shaped ST elevation", match: ["concave", "saddle"] },
          { id: "spodick", text: "Downsloping TP segment (Spodick sign)", match: ["spodick", "downsloping tp", "tp segment"] },
          { id: "q", text: "No pathological Q waves", match: ["no q wave", "q wave", "absent q", "no pathological q"] },
        ],
        explanation:
          "Pericarditis causes diffuse concave ST elevation with PR depression and PR elevation in aVR. Reciprocal ST depression outside aVR and V1 strongly suggests STEMI instead. No single feature is perfect, so read the whole ECG in context.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "esc-pericardial",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What other conditions cause ST elevation and can mimic STEMI?",
        accept: [
          { id: "er", text: "Benign early repolarization", match: ["early repolarization", "early repolarisation", "j point"] },
          { id: "lvh", text: "Left ventricular hypertrophy", match: ["lvh", "left ventricular hypertrophy"] },
          { id: "lbbb", text: "Left bundle branch block", match: ["lbbb", "left bundle", "bundle branch"] },
          { id: "paced", text: "Ventricular paced rhythm", match: ["paced", "pacemaker", "pacing"] },
          { id: "aneurysm", text: "Left ventricular aneurysm", match: ["aneurysm"] },
          { id: "brugada", text: "Brugada pattern", match: ["brugada"] },
          { id: "k", text: "Hyperkalemia", match: ["hyperkalemia", "hyperkalaemia", "potassium"] },
          { id: "tako", text: "Takotsubo cardiomyopathy", match: ["takotsubo", "stress cardiomyopathy"] },
          { id: "myo", text: "Myocarditis", match: ["myocarditis"] },
          { id: "hypo", text: "Hypothermia with Osborn waves", match: ["hypothermia", "osborn"] },
        ],
        unacceptable: [{ text: "Pericarditis, already named in the question", match: ["pericarditis"] }],
        explanation:
          "Several conditions produce ST elevation without coronary occlusion. Recognizing them avoids unnecessary catheterization laboratory activation and fibrinolysis. When in doubt, serial ECGs, comparison with old tracings and bedside echo help.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "udmi",
      },
      {
        id: "q3",
        kind: "single",
        update: "The resident says that because the pain is pleuritic and positional, ACS is excluded and the troponin was unnecessary.",
        prompt: "Which of the following statements about the resident's reasoning is most accurate?",
        options: [
          "A normal first troponin excludes myocardial injury",
          "Pleuritic or positional pain lowers but does not exclude ACS",
          "Pleuritic, positional pain excludes ACS",
          "Reproducible chest wall tenderness, if present, excludes ACS",
          "Response to an NSAID would confirm pericarditis",
        ],
        correct: 1,
        explanation:
          "Pleuritic, positional and reproducible features reduce but do not remove the probability of ACS. Some patients with MI describe sharp or pleuritic pain. ECG and troponin testing are still required.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "aha-chest-pain",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "He is started on ibuprofen and colchicine. Two hours later he has new, heavier, pressure like pain.",
        prompt: "What findings on repeat testing would make you reconsider STEMI?",
        accept: [
          { id: "recip", text: "New reciprocal ST depression", match: ["reciprocal", "st depression"] },
          { id: "iii", text: "ST elevation greater in III than in II", match: ["iii ii", "iii greater"] },
          { id: "terr", text: "ST elevation localized to one coronary territory", match: ["localized", "localised", "one territory", "single territory", "regional", "territorial"] },
          { id: "q", text: "New Q waves", match: ["q wave"] },
          { id: "trop", text: "Rising troponin", match: ["troponin", "trop"] },
          { id: "rwma", text: "Regional wall motion abnormality on echo", match: ["wall motion", "rwma"] },
          { id: "dyn", text: "Evolving ST elevation that becomes convex or hyperacute T waves", match: ["dynamic", "evolving", "increasing st elevation", "convex", "tombstone", "hyperacute"] },
        ],
        explanation:
          "Pericarditis ECG changes evolve slowly over days. Rapidly changing, territorial ST elevation with reciprocal depression, a rising troponin or a regional wall motion abnormality points to STEMI. Serial testing continues until the diagnosis is secure.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "esc-pericardial",
      },
    ],
    sources: [S.pericard, S.udmi, S.chestPain],
    ...META,
  },
  {
    id: "ischemic-heart-disease-04",
    topic: TOPIC,
    title: "Pain free after morning chest pressure",
    stem:
      "A 52-year-old man presents at 0800 after 30 minutes of pressure like chest pain at rest this morning. He had two shorter episodes yesterday. He is now pain free. He smokes and has hypertension and dyslipidemia. His father had an MI at 50. Oxygen saturation is 98%. His ECG shows sinus rhythm with deep, symmetric T wave inversion in V2 and V3, preserved R wave progression, no Q waves and less than 1 mm ST elevation in V2. The first high sensitivity troponin I is 9 ng/L (99th percentile 26 ng/L).",
    vitals: { pulse: "74/minute", resp: "16/minute", bp: "138/84 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What is the ECG pattern, and which coronary lesion does it suggest?",
        accept: [
          { id: "wellens", text: "Wellens pattern", match: ["wellens", "wellen"] },
          { id: "lad", text: "Critical proximal left anterior descending stenosis", match: ["lad", "left anterior descending"] },
        ],
        explanation:
          "Deep symmetric or biphasic T waves in V2 and V3 in a pain free patient after angina is the Wellens pattern. It indicates a critical proximal LAD lesion. Many of these patients go on to a large anterior MI within days.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "wellens",
      },
      {
        id: "q2",
        kind: "single",
        update: "He asks to go home because the pain has settled and the troponin is normal.",
        prompt: "Which of the following is the most appropriate plan for him?",
        options: [
          "Admit to cardiology for early angiography, avoid stress test",
          "Discharge, outpatient stress test within 72 hours",
          "Exercise stress test in the department today",
          "Outpatient CT coronary angiography next month",
          "Repeat troponin at 2 hours, then discharge home if normal",
        ],
        correct: 0,
        explanation:
          "Pain resolution and a normal troponin do not exclude unstable angina. The Wellens pattern predicts a critical LAD stenosis, and stress testing can precipitate infarction. He needs admission and angiography.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "wellens",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What features of his presentation place him at high risk?",
        accept: [
          { id: "rest", text: "Pain at rest", match: ["rest"] },
          { id: "recur", text: "Recurrent or crescendo episodes", match: ["recurrent", "crescendo", "multiple episodes", "two episodes", "increasing", "repeated"] },
          { id: "ecg", text: "Ischemic T wave changes on ECG", match: ["t wave", "wellens", "ecg", "inversion"] },
          { id: "smoke", text: "Smoking", match: ["smoker", "smoking", "smokes"] },
          { id: "htn", text: "Hypertension", match: ["hypertension", "htn"] },
          { id: "lipid", text: "Dyslipidemia", match: ["dyslipidemia", "cholesterol", "lipid"] },
          { id: "fhx", text: "Family history of premature coronary disease", match: ["family history", "father"] },
          { id: "male", text: "Male sex and age over 45", match: ["male", "age"] },
        ],
        unacceptable: [{ text: "Normal troponin", match: ["normal troponin"] }],
        explanation:
          "Rest pain, a crescendo pattern and ischemic ECG changes make this a high risk unstable angina presentation even with a normal troponin. Multiple risk factors add to his pretest probability.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
    ],
    sources: [S.wellens, S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-05",
    topic: TOPIC,
    title: "Brief chest tightness at a desk",
    stem:
      "A 38-year-old woman presents 7 hours after a 20 minute episode of left sided chest tightness at rest while working at her desk. It resolved on its own and has not returned. She smokes half a pack a day and has no other risk factors. Oxygen saturation is 99%. Her ECG is normal. High sensitivity troponin I results at arrival and at 2 hours are both below the limit of detection.",
    vitals: { pulse: "76/minute", resp: "14/minute", bp: "122/78 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What are the components of the HEART score?",
        accept: [
          { id: "h", text: "History", match: ["history"] },
          { id: "e", text: "ECG", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "a", text: "Age", match: ["age"] },
          { id: "r", text: "Risk factors", match: ["risk factor"] },
          { id: "t", text: "Troponin", match: ["troponin", "trop"] },
        ],
        explanation:
          "HEART stands for History, ECG, Age, Risk factors and Troponin, each scored 0 to 2. A score of 0 to 3 identifies patients at low risk of major adverse cardiac events at 6 weeks.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "heart",
      },
      {
        id: "q2",
        kind: "single",
        update: "Her physician scores the history as moderately suspicious.",
        prompt: "Which of the following is her total HEART score based on these findings?",
        options: [
          "1",
          "2",
          "3",
          "4",
          "5",
        ],
        correct: 1,
        explanation:
          "History moderately suspicious scores 1. Normal ECG 0. Age under 45 scores 0. One risk factor (smoking) scores 1. Normal troponin 0. The total of 2 is low risk, which supports discharge with follow up.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "heart-validation",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What are the elements of your discharge plan?",
        accept: [
          { id: "fu", text: "Follow up with her family physician within 1 to 2 weeks", match: ["family physician", "family doctor", "gp", "primary care", "follow up"] },
          { id: "test", text: "Outpatient testing or rapid access chest pain clinic if symptoms recur or concern remains", match: ["stress test", "rapid access", "chest pain clinic", "cardiology", "outpatient testing", "ccta", "ct coronary"] },
          { id: "return", text: "Clear return precautions", match: ["return"] },
          { id: "smoke", text: "Smoking cessation", match: ["smoking", "cessation", "quit"] },
          { id: "rf", text: "Screen for other risk factors such as lipids and diabetes", match: ["lipid", "cholesterol", "a1c", "risk factor", "diabetes"] },
        ],
        unacceptable: [{ text: "Admit for inpatient stress testing", match: ["admit"] }],
        explanation:
          "Low risk patients can be discharged. They still need follow up, return instructions and risk factor management. Further testing is guided by recurrent symptoms or residual concern rather than done by reflex for everyone.",
        keyFeature: { topic: TOPIC, n: 8 },
        source: "aha-chest-pain",
      },
      {
        id: "q4",
        kind: "single",
        update: "She mentions the pain went away after she borrowed her husband's nitroglycerin spray.",
        prompt: "Which of the following statements about her response to nitroglycerin is most accurate?",
        options: [
          "Lack of relief would have excluded ACS",
          "Relief confirms angina and she needs admission to hospital",
          "Relief does not reliably separate cardiac from other pain",
          "Relief proves esophageal spasm and excludes ACS",
          "She now needs a CT pulmonary angiogram",
        ],
        correct: 2,
        explanation:
          "Response to nitroglycerin has poor diagnostic value in either direction. Esophageal spasm and other non cardiac pain may improve, and some ACS pain does not. Relief alone should not change her risk assessment. Decisions rest on the history, ECG and troponin.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "aha-chest-pain",
      },
    ],
    sources: [S.heart, S.heartVal, S.chestPain],
    ...META,
  },
  {
    id: "ischemic-heart-disease-06",
    topic: TOPIC,
    title: "Chest pain after a party",
    stem:
      "A 34-year-old man presents with 1 hour of chest pain that began 40 minutes after snorting cocaine at a party. He is agitated and sweaty. Oxygen saturation is 98%. His pupils are dilated. ECG shows sinus tachycardia with 1 mm ST depression in V4 to V6. Pulses are equal in both arms. Bedside echo shows no pericardial effusion and a normal aortic root.",
    vitals: { temperature: "37.8°C", pulse: "128/minute", resp: "22/minute", bp: "186/108 mmHg", weight: "80 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What medications do you give now?",
        accept: [
          { id: "benzo", text: "A benzodiazepine such as lorazepam or diazepam IV", match: ["benzodiazepine", "benzo", "lorazepam", "diazepam", "midazolam", "ativan", "valium"] },
          { id: "asa", text: "ASA 160 to 325 mg chewed", match: ["asa", "aspirin", "acetylsalicylic"] },
          { id: "ntg", text: "Nitroglycerin", match: ["nitroglycerin", "nitro", "ntg"] },
          { id: "ccb", text: "Calcium channel blocker such as diltiazem or verapamil, second line", match: ["verapamil", "diltiazem", "calcium channel"] },
          { id: "phent", text: "Phentolamine, second line", match: ["phentolamine"] },
        ],
        unacceptable: [
          { text: "A beta blocker such as metoprolol or labetalol", match: ["metoprolol", "propranolol", "esmolol", "atenolol", "labetalol", "beta blocker"] },
        ],
        explanation:
          "Benzodiazepines treat the sympathetic excess and relieve chest pain. ASA and nitroglycerin are given as for other possible ACS. The 2023 AHA update supports benzodiazepines and vasodilators first and calls beta blocker safety in cocaine toxicity controversial, so they earn no credit here.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "aha-tox-2023",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "By what mechanisms does cocaine cause myocardial ischemia?",
        accept: [
          { id: "spasm", text: "Coronary vasospasm", match: ["vasospasm", "spasm", "vasoconstriction"] },
          { id: "demand", text: "Increased oxygen demand from tachycardia and hypertension", match: ["demand", "tachycardia", "hypertension", "oxygen consumption"] },
          { id: "thromb", text: "Platelet activation and thrombosis", match: ["thrombosis", "thrombus", "platelet", "clot", "thrombogenic"] },
          { id: "athero", text: "Accelerated atherosclerosis", match: ["atherosclerosis", "atheroma", "plaque"] },
          { id: "dissect", text: "Coronary artery dissection", match: ["dissection"] },
        ],
        explanation:
          "Cocaine raises myocardial oxygen demand while reducing supply through vasospasm and thrombosis. Chronic use accelerates atherosclerosis. Young cocaine users can have true MI, so ACS must be considered despite their age.",
        keyFeature: { topic: TOPIC, n: 5 },
        source: "aha-cocaine",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "His symptoms settle after treatment.",
        prompt: "What are the elements of ongoing ACS testing?",
        accept: [
          { id: "ecg", text: "Serial ECGs", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "trop", text: "Serial troponins", match: ["troponin", "trop"] },
          { id: "mon", text: "Continuous cardiac monitoring", match: ["monitor", "telemetry", "monitoring"] },
        ],
        explanation:
          "Cocaine associated chest pain needs the same serial ECG and troponin testing as any possible ACS. Monitoring detects arrhythmias. Early ST changes may reflect ischemia or rate related changes, so repeat once he is calm.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "aha-cocaine",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Troponins at 0 and 2 hours are normal. Repeat ECGs are normal. He is pain free and calm.",
        prompt: "What are the elements of your discharge plan?",
        accept: [
          { id: "cess", text: "Cocaine cessation counselling and addiction referral", match: ["cocaine", "cessation", "addiction", "substance", "stop using"] },
          { id: "fu", text: "Follow up with a family physician", match: ["follow up", "family physician", "family doctor", "primary care"] },
          { id: "test", text: "Outpatient cardiac testing if symptoms recur", match: ["stress", "outpatient testing", "cardiology"] },
          { id: "return", text: "Return precautions", match: ["return"] },
        ],
        unacceptable: [{ text: "Start a beta blocker", match: ["metoprolol", "beta blocker"] }],
        explanation:
          "After a negative evaluation his short term risk is low. The most effective intervention is stopping cocaine. Follow up and return advice complete the plan. Avoid starting beta blockers in a person likely to use cocaine again.",
        keyFeature: { topic: TOPIC, n: 8 },
        source: "aha-cocaine",
      },
    ],
    sources: [S.cocaine, S.tox2023],
    ...META,
  },
  {
    id: "ischemic-heart-disease-07",
    topic: TOPIC,
    title: "Dizzy and weak at breakfast",
    stem:
      "An 81-year-old woman with type 2 diabetes is brought in by paramedics with dizziness and weakness that began 2 hours ago while she was making breakfast. She denies chest pain but says she feels unwell. Oxygen saturation is 94%. She is pale and clammy but alert. Her ECG shows complete heart block with a narrow complex escape at 36/minute and 2 mm ST elevation in II, III and aVF. Your hospital has a catheterization laboratory on site.",
    vitals: { pulse: "36/minute", resp: "20/minute", bp: "82/48 mmHg", weight: "58 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of her presentation should make you think of ACS despite the absence of chest pain?",
        accept: [
          { id: "age", text: "Older age", match: ["age", "older", "elderly", "81"] },
          { id: "dm", text: "Diabetes", match: ["diabetes", "diabetic"] },
          { id: "sex", text: "Female sex", match: ["female", "woman"] },
          { id: "clammy", text: "Pallor and diaphoresis", match: ["clammy", "diaphoresis", "diaphoretic", "sweaty", "pale", "pallor"] },
          { id: "block", text: "New bradycardia or heart block", match: ["heart block", "bradycardia", "av block"] },
          { id: "hypo", text: "Hypotension", match: ["hypotension", "shock"] },
          { id: "ste", text: "Inferior ST elevation", match: ["st elevation"] },
        ],
        explanation:
          "Older women with diabetes often present with dizziness, weakness or dyspnea rather than chest pain. New heart block with hypotension and diaphoresis should trigger an immediate ECG. Delayed recognition is a common cause of harm.",
        keyFeature: { topic: TOPIC, n: 5 },
        source: "aha-chest-pain",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "Atropine 1 mg IV given twice has no effect. BP is 78/44 mmHg.",
        prompt: "What interventions support her heart rate while the catheterization laboratory is prepared?",
        accept: [
          { id: "tv", text: "Transvenous pacing", match: ["transvenous"] },
          { id: "tcp", text: "Transcutaneous pacing with analgesia and sedation", match: ["transcutaneous", "pacing", "pacer", "tcp"] },
          { id: "epi", text: "Epinephrine infusion 2 to 10 mcg/min", match: ["epinephrine", "adrenaline"] },
          { id: "dopa", text: "Dopamine infusion 5 to 20 mcg/kg/min", match: ["dopamine"] },
        ],
        unacceptable: [{ text: "Isoproterenol", match: ["isoproterenol", "isuprel"] }],
        explanation:
          "When atropine fails, use transcutaneous pacing or a chronotropic infusion such as epinephrine or dopamine. Confirm mechanical capture with a pulse and give analgesia. Isoproterenol raises myocardial oxygen demand and is avoided in active ischemia.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "aha-acls",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following reperfusion strategies is most appropriate for her?",
        options: [
          "Emergency primary PCI with temporary pacing as needed",
          "Medical therapy and angiography within 24 hours",
          "Permanent pacemaker first, then angiography the next day",
          "Tenecteplase now, then angiography tomorrow",
          "Wait for the first troponin before deciding",
        ],
        correct: 0,
        explanation:
          "Primary PCI is the best reperfusion when a catheterization laboratory is on site. Heart block in inferior STEMI usually comes from right coronary occlusion and often resolves after reperfusion. A permanent pacemaker is premature.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
    ],
    sources: [S.chestPain, S.acls, S.ccsStemi],
    ...META,
  },
  {
    id: "ischemic-heart-disease-08",
    topic: TOPIC,
    title: "Epigastric pain labelled gastritis",
    stem:
      "A 58-year-old man presents with 90 minutes of epigastric pain, nausea and vomiting. Triage sent him to the minor treatment area with a note of gastritis. He has hypertension and dyslipidemia. Oxygen saturation is 97%. His ECG shows 2.5 mm horizontal ST depression in V1 to V3 with upright T waves and a tall R wave in V2. There is no ST elevation in the standard 12 leads. Your hospital has a catheterization laboratory on site.",
    vitals: { pulse: "88/minute", resp: "18/minute", bp: "146/90 mmHg", weight: "92 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of this ECG suggest posterior STEMI?",
        accept: [
          { id: "std", text: "Horizontal ST depression in V1 to V3", match: ["st depression", "horizontal"] },
          { id: "r", text: "Tall R wave in V1 or V2 with R to S ratio above 1", match: ["tall r", "r wave", "dominant r", "r/s"] },
          { id: "t", text: "Upright T waves in V1 to V3", match: ["upright t", "positive t", "tall t"] },
        ],
        explanation:
          "Posterior wall injury is seen in reverse from the anterior leads. ST depression in V1 to V3 with upright T waves and a tall R wave is its mirror image. It is often missed and labelled as anterior ischemia.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "esc-acs",
      },
      {
        id: "q2",
        kind: "short",
        required: 1,
        prompt: "Which additional ECG leads do you record next?",
        accept: [{ id: "post", text: "Posterior leads V7 to V9", match: ["v7", "v8", "v9", "posterior lead"] }],
        explanation:
          "Posterior leads V7 to V9 confirm posterior STEMI. ST elevation of 0.5 mm or more is diagnostic, or 1 mm or more in men under 40. Recording them takes seconds and changes management.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "udmi",
      },
      {
        id: "q3",
        kind: "single",
        update: "Leads V7 to V9 show 1 mm ST elevation.",
        prompt: "Which of the following is the most appropriate management for him?",
        options: [
          "Activate the catheterization laboratory for primary PCI",
          "CT angiogram of the aorta first",
          "Repeat troponin in 2 hours before deciding",
          "Tenecteplase now, then routine angiography",
          "Treat as NSTEMI with invasive angiography within 24 hours",
        ],
        correct: 0,
        explanation:
          "Posterior STEMI is a STEMI equivalent from an occluded circumflex or right coronary artery. It needs emergency reperfusion. With a catheterization laboratory on site, primary PCI is preferred over fibrinolysis.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What features in his history should have prompted an ECG at triage despite the impression of gastritis?",
        accept: [
          { id: "age", text: "Man aged over 50", match: ["age", "male", "man", "58"] },
          { id: "htn", text: "Hypertension", match: ["hypertension", "htn"] },
          { id: "lipid", text: "Dyslipidemia", match: ["dyslipidemia", "cholesterol", "lipid"] },
          { id: "epi", text: "Epigastric pain, a recognized anginal equivalent", match: ["epigastric", "anginal equivalent"] },
          { id: "nv", text: "Nausea and vomiting with the pain", match: ["nausea", "vomiting"] },
          { id: "rf", text: "Cardiac risk factors", match: ["risk factor"] },
        ],
        explanation:
          "Epigastric pain with nausea in a middle aged man with risk factors is a classic atypical ACS presentation. Many EDs require an ECG within 10 minutes for upper abdominal pain in adults over a set age for this reason.",
        keyFeature: { topic: TOPIC, n: 5 },
        source: "aha-chest-pain",
      },
    ],
    sources: [S.esc, S.udmi, S.ccsStemi, S.chestPain],
    ...META,
  },
  {
    id: "ischemic-heart-disease-09",
    topic: TOPIC,
    title: "Chest pain with an old bundle branch block",
    stem:
      "You work at a community hospital. The regional PCI centre is 40 minutes away by land ambulance and accepts direct transfers to its catheterization laboratory. A 69-year-old man presents with 45 minutes of crushing chest pain and diaphoresis. He has a known left bundle branch block on an ECG from last year. Oxygen saturation is 95%. Today's ECG shows his known LBBB with 2 mm ST elevation in V5, V6 and I, in the same direction as the QRS.",
    vitals: { pulse: "92/minute", resp: "20/minute", bp: "138/84 mmHg", weight: "86 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What ECG criteria identify acute MI in the presence of LBBB?",
        accept: [
          { id: "ce", text: "Concordant ST elevation of 1 mm or more", match: ["concordant st elevation", "concordant elevation", "concordant ste"] },
          { id: "cd", text: "Concordant ST depression of 1 mm or more in V1 to V3", match: ["concordant st depression", "concordant depression", "st depression v1"] },
          { id: "disc", text: "Excessively discordant ST elevation, 25% or more of the preceding S wave depth", match: ["discordant", "25%", "ratio", "5 mm"] },
        ],
        explanation:
          "Sgarbossa criteria identify MI in LBBB. The Smith modification replaces the 5 mm discordance rule with an ST to S ratio of 25% or more, which improves sensitivity. Concordant ST elevation is the most specific finding.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "smith-sgarbossa",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate management for him?",
        options: [
          "CT coronary angiography in your department",
          "Serial troponins and admission to your hospital",
          "Tenecteplase in your department",
          "Transfer directly to the PCI laboratory for primary PCI",
          "Wait for cardiology to compare with the old ECG tomorrow",
        ],
        correct: 3,
        explanation:
          "He meets criteria for acute MI. With a 40 minute transfer, first medical contact to device time is well within 120 minutes, so primary PCI is preferred. Direct transfer to the catheterization laboratory avoids delay in the receiving ED.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "Suppose instead his ECG showed LBBB without Sgarbossa criteria and he was pain free and stable.",
        prompt: "What steps would resolve the diagnosis?",
        accept: [
          { id: "ecg", text: "Serial ECGs compared with the old tracing", match: ["ecg", "ekg", "compare"] },
          { id: "trop", text: "Serial troponins", match: ["troponin", "trop"] },
          { id: "echo", text: "Bedside echo for a regional wall motion abnormality", match: ["echo", "wall motion", "pocus", "ultrasound"] },
          { id: "cards", text: "Cardiology consultation", match: ["cardiology", "cardiologist"] },
        ],
        explanation:
          "An old LBBB alone is not a STEMI equivalent. Stable patients without Sgarbossa criteria are evaluated with serial ECGs and troponins like any other possible ACS. Echo can add evidence of regional ischemia.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "esc-acs",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What clinical features call for immediate angiography in suspected ACS with LBBB, even without diagnostic ECG criteria?",
        accept: [
          { id: "shock", text: "Hemodynamic instability or cardiogenic shock", match: ["shock", "hypotension", "unstable", "instability"] },
          { id: "pain", text: "Refractory or recurrent ischemic pain", match: ["refractory", "ongoing pain", "persistent pain", "recurrent pain"] },
          { id: "arrhythmia", text: "Life threatening arrhythmia or cardiac arrest", match: ["arrhythmia", "ventricular tachycardia", "vt", "vf", "arrest", "ventricular fibrillation"] },
          { id: "hf", text: "Acute heart failure", match: ["heart failure", "pulmonary edema"] },
          { id: "mech", text: "Mechanical complication such as new mitral regurgitation", match: ["mechanical complication", "new murmur", "papillary", "septal rupture", "mitral regurgitation"] },
        ],
        unacceptable: [{ text: "New LBBB alone", match: ["new lbbb", "lbbb alone"] }],
        explanation:
          "Very high risk features call for immediate angiography whatever the ECG shows. A new or presumed new LBBB alone no longer triggers catheterization laboratory activation in a stable patient.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
    ],
    sources: [S.smith, S.ccsStemi, S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-10",
    topic: TOPIC,
    title: "Burning discomfort after supper",
    stem:
      "A 61-year-old woman with type 2 diabetes presents at 2100 with 90 minutes of burning lower chest and upper abdominal discomfort that began after supper. She had two similar episodes this week. Oxygen saturation is 98%. The discomfort settled 20 minutes after an oral antacid and viscous lidocaine mixture. She is tender over the left costochondral junctions. Her ECG shows flat T waves in V5 and V6, with no old ECG for comparison. The first high sensitivity troponin I, drawn 1 hour after onset, is 11 ng/L (female 99th percentile 16 ng/L). The resident plans to discharge her with a diagnosis of reflux.",
    vitals: { pulse: "84/minute", resp: "16/minute", bp: "148/88 mmHg", weight: "88 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "Why is this plan unsafe?",
        accept: [
          { id: "gi", text: "Relief with a GI cocktail does not exclude ACS", match: ["antacid", "gi cocktail", "pink lady", "lidocaine", "cocktail"] },
          { id: "cw", text: "Chest wall tenderness does not exclude ACS", match: ["tender", "tenderness", "chest wall"] },
          { id: "trop", text: "A single troponin 1 hour after onset is too early to rule out MI", match: ["troponin", "too early", "single"] },
          { id: "res", text: "Resolution of pain does not exclude ACS", match: ["resolution", "resolved", "pain free", "settled"] },
          { id: "atyp", text: "She is a woman with diabetes, at risk of atypical presentation", match: ["diabetes", "diabetic", "woman", "female"] },
          { id: "recur", text: "Recurrent episodes this week suggest unstable angina", match: ["recurrent", "episodes", "crescendo", "this week", "unstable angina"] },
          { id: "ecg", text: "Nonspecific T wave changes need serial ECGs", match: ["ecg", "t wave"] },
        ],
        explanation:
          "Response to a GI cocktail, chest wall tenderness and pain resolution all have little diagnostic value for excluding ACS. A single early troponin cannot rule out MI. A diabetic woman with recurrent episodes needs a complete workup.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "aha-chest-pain",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What steps complete her ACS testing?",
        accept: [
          { id: "trop", text: "Repeat high sensitivity troponin per the local algorithm", match: ["troponin", "trop"] },
          { id: "ecg", text: "Repeat ECG, and with any recurrent symptoms", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "mon", text: "Cardiac monitoring while in the ED", match: ["monitor", "telemetry", "monitoring"] },
        ],
        explanation:
          "Validated high sensitivity troponin pathways need a second sample, usually at 1 to 3 hours, unless the patient presents more than 3 hours after onset with a very low first value. Serial ECGs look for evolving changes.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "esc-acs",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What anginal equivalent symptoms do you ask about in a patient like her?",
        accept: [
          { id: "dysp", text: "Dyspnea", match: ["dyspnea", "shortness of breath", "breathless", "sob"] },
          { id: "fat", text: "Fatigue or weakness", match: ["fatigue", "weakness", "tired"] },
          { id: "nv", text: "Nausea or vomiting", match: ["nausea", "vomiting"] },
          { id: "sweat", text: "Diaphoresis", match: ["diaphoresis", "sweat", "sweating", "clammy"] },
          { id: "epi", text: "Epigastric pain or indigestion", match: ["epigastric", "indigestion", "heartburn"] },
          { id: "sync", text: "Syncope, presyncope or dizziness", match: ["syncope", "dizziness", "lightheaded", "presyncope", "dizzy"] },
          { id: "rad", text: "Jaw, neck, arm, shoulder or back discomfort", match: ["jaw", "arm", "back", "shoulder", "neck"] },
          { id: "ex", text: "Reduced exercise tolerance", match: ["exercise", "exertion"] },
        ],
        explanation:
          "Women, older adults and people with diabetes often report anginal equivalents rather than chest pressure. Asking about them directly finds ACS that a chest pain focused history misses.",
        keyFeature: { topic: TOPIC, n: 5 },
        source: "aha-chest-pain",
      },
      {
        id: "q4",
        kind: "single",
        update: "Her repeat troponin at 3 hours is 64 ng/L. The ECG is unchanged. She is pain free.",
        prompt: "Which of the following is the most appropriate disposition for her?",
        options: [
          "Admit, antithrombotics, invasive angiography within 24 hours",
          "Discharge with an outpatient stress test",
          "Immediate catheterization laboratory activation",
          "Observation overnight, then an exercise stress test tomorrow",
          "Repeat troponin in 6 hours and decide then",
        ],
        correct: 0,
        explanation:
          "A rise above the 99th percentile with a significant change in a patient with ischemic symptoms is an NSTEMI. A confirmed NSTEMI is high risk and warrants an early invasive strategy within 24 hours. Immediate angiography is for very high risk features such as instability or refractory pain.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
    ],
    sources: [S.chestPain, S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-11",
    topic: TOPIC,
    title: "Chest pain weeks after a stroke",
    stem:
      "You work at a rural hospital. The nearest PCI centre is 2 hours away by critical care land transport. A 67-year-old man presents with 50 minutes of chest pain. Five weeks ago he had an ischemic stroke with mild residual left hand weakness. Oxygen saturation is 96%. His ECG shows 3 mm ST elevation in V1 to V4.",
    vitals: { pulse: "96/minute", resp: "20/minute", bp: "142/86 mmHg", weight: "78 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following reperfusion strategies is most appropriate for him?",
        options: [
          "Anticoagulation and transfer tomorrow",
          "Full dose tenecteplase now, then transfer for angiography",
          "Half dose tenecteplase now, then transfer",
          "Immediate transfer for primary PCI despite the delay",
          "Medical management only, no reperfusion",
        ],
        correct: 3,
        explanation:
          "Ischemic stroke within 3 months is an absolute contraindication to fibrinolysis, at any dose. Primary PCI is then the only reperfusion option and remains beneficial even with a longer delay. Arrange the fastest possible transfer.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q2",
        kind: "menu",
        select: 3,
        prompt: "Which of the following medications do you give before transfer for primary PCI?",
        options: [
          "ASA 160 mg chewed",
          "ASA 81 mg enteric coated, swallowed",
          "Clopidogrel 75 mg PO",
          "Enoxaparin 1 mg/kg SC with tenecteplase",
          "Fondaparinux 2.5 mg SC",
          "Metoprolol 5 mg IV",
          "Prasugrel 60 mg PO",
          "Ticagrelor 180 mg PO",
          "Unfractionated heparin 70 units/kg IV bolus",
        ],
        correct: [0, 7, 8],
        explanation:
          "Give chewed ASA, a ticagrelor load and unfractionated heparin before primary PCI. Prasugrel is contraindicated after any stroke or TIA because of intracranial bleeding. Fondaparinux alone is avoided in primary PCI because of catheter thrombosis. Clopidogrel 75 mg is a maintenance dose, not a load.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "ccs-antiplatelet-2023",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the minimum ST elevation in V2 and V3 that meets STEMI criteria for a man of his age?",
        options: [
          "0.5 mm",
          "1 mm",
          "1.5 mm",
          "2 mm",
          "2.5 mm",
        ],
        correct: 3,
        explanation:
          "In V2 and V3 the threshold is 2 mm for men 40 or older, 2.5 mm for men under 40 and 1.5 mm for women. In all other leads it is 1 mm in two contiguous leads.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "udmi",
      },
    ],
    sources: [S.ccsStemi, S.ccsAntiplatelet2023, S.udmi],
    ...META,
  },
  {
    id: "ischemic-heart-disease-12",
    topic: TOPIC,
    title: "Chest pain with cold, mottled legs",
    stem:
      "A 74-year-old man arrives at your PCI capable hospital with 5 hours of chest pain and shortness of breath. He is cool and mottled to the knees with crackles to the mid lung fields. Lactate is 4.2 mmol/L. His ECG shows sinus tachycardia with 4 mm ST elevation in V1 to V5. The resident suggests IV metoprolol for his heart rate.",
    vitals: { pulse: "118/minute", resp: "30/minute", bp: "84/56 mmHg", o2sat: "89% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "Why is IV metoprolol contraindicated?",
        accept: [
          { id: "hypo", text: "Hypotension and cardiogenic shock", match: ["shock", "hypotension", "low blood pressure", "sbp", "blood pressure"] },
          { id: "hf", text: "Heart failure with pulmonary edema (Killip class III)", match: ["heart failure", "pulmonary edema", "crackles", "killip", "congestion"] },
          { id: "comp", text: "His tachycardia is compensatory for low stroke volume", match: ["compensatory", "tachycardia", "heart rate", "stroke volume"] },
          { id: "age", text: "Age over 70, a risk factor for beta blocker induced shock", match: ["age", "over 70"] },
          { id: "perf", text: "Signs of hypoperfusion such as mottling and high lactate", match: ["mottled", "mottling", "hypoperfusion", "lactate", "low output"] },
        ],
        explanation:
          "In COMMIT, early IV beta blockade increased cardiogenic shock, mainly in patients who were older, hypotensive, tachycardic or in heart failure. Here the tachycardia is keeping him alive. Beta blockers are started later, once he is stable.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "commit",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following reperfusion strategies is most appropriate for him?",
        options: [
          "Emergency angiography with PCI of all significant lesions",
          "Emergency angiography with PCI of the culprit artery",
          "Medical stabilization and angiography in 24 to 48 hours",
          "Surgical referral for CABG before any angiography",
          "Tenecteplase now and admission to the ICU",
        ],
        correct: 1,
        explanation:
          "Cardiogenic shock from STEMI needs emergency revascularization regardless of time from onset. In CULPRIT-SHOCK, culprit only PCI had lower death or renal failure at 30 days than immediate multivessel PCI. Fibrinolysis works poorly in shock.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "culprit-shock",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What features of his presentation predict high mortality?",
        accept: [
          { id: "age", text: "Older age", match: ["age", "74", "older", "elderly"] },
          { id: "bp", text: "Hypotension", match: ["hypotension", "blood pressure", "shock"] },
          { id: "hr", text: "Tachycardia", match: ["tachycardia", "heart rate"] },
          { id: "killip", text: "Heart failure, Killip class III", match: ["killip", "heart failure", "crackles", "pulmonary edema"] },
          { id: "ant", text: "Large anterior infarct", match: ["anterior", "lad", "large infarct"] },
          { id: "lac", text: "Hypoperfusion with high lactate and mottling", match: ["lactate", "mottled", "mottling", "hypoperfusion"] },
          { id: "hypox", text: "Hypoxemia", match: ["hypoxia", "hypoxemia", "oxygen", "saturation"] },
          { id: "delay", text: "Delayed presentation", match: ["delay", "delayed", "5 hour", "late presentation"] },
        ],
        explanation:
          "Age, systolic pressure, heart rate and Killip class are among the strongest predictors of death in STEMI, as in the GRACE and TIMI scores. A large anterior infarct with hypoperfusion places him in the highest risk group.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
    ],
    sources: [S.commit, S.culprit, S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-13",
    topic: TOPIC,
    alsoTopics: ["chest-pain"],
    title: "Heaviness eight days after an infusion",
    stem:
      "You are working in a hospital with a catheterization laboratory. A 63-year-old woman presents to the emergency department with 40 minutes of central chest heaviness and nausea that began while she was resting. She has stage III ovarian cancer. She had surgery 3 months ago and is now receiving carboplatin, paclitaxel and bevacizumab, last given 8 days ago. Her oncologist's most recent note describes treatment with curative intent. She has hypertension and takes amlodipine. Her first ECG, recorded 7 minutes after arrival, shows sinus rhythm with 0.5 mm ST depression in I and aVL and no ST elevation. Her pain continues.",
    vitals: { temperature: "36.9°C", pulse: "92/minute", resp: "18/minute", bp: "148/86 mmHg", o2sat: "97% on room air", weight: "68 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What testing do you arrange while her pain continues?",
        accept: [
          { id: "repeat", text: "Repeat 12-lead ECG every 15 to 30 minutes and with any change in symptoms", match: ["repeat ecg", "serial ecg", "ecg every", "another ecg", "second ecg", "repeat 12 lead", "serial 12 lead", "ecg in 15", "ecg in 10", "ecg in 20", "ecg in 30", "ecg q15"] },
          { id: "leads", text: "Additional leads V3R, V4R and V7 to V9", match: ["v4r", "v3r", "v7", "v8", "v9", "posterior lead", "right sided lead", "right sided ecg", "posterior ecg", "extra lead", "additional lead"] },
          { id: "trop", text: "High-sensitivity troponin now and repeated at 1 or 2 hours", match: ["troponin", "hs tnt", "hs tni", "hstn"] },
          { id: "monitor", text: "Continuous ECG monitoring with defibrillator pads available", match: ["continuous monitor", "cardiac monitor", "telemetry", "continuous ecg", "defibrillator", "defib pad", "st monitoring"] },
          { id: "cbc", text: "CBC with platelet count, given her recent chemotherapy", match: ["cbc", "platelet", "complete blood count", "blood count", "hemoglobin"] },
          { id: "echo", text: "Bedside echocardiography for a regional wall motion abnormality", match: ["echo", "pocus", "wall motion", "echocardiogram", "echocardiography", "cardiac ultrasound"] },
        ],
        unacceptable: [{ text: "A single troponin to rule out infarction", match: ["single troponin", "one troponin"] }],
        explanation:
          "Ongoing pain with a nondiagnostic first ECG calls for repeated ECGs and testing run in parallel. ESC 2023 recommends an additional 12-lead ECG with recurrent symptoms or diagnostic uncertainty, and leads V3R, V4R and V7 to V9 when occlusion is suspected and the standard leads are inconclusive. It also recommends continuous monitoring and high-sensitivity troponin on a 0 h and 1 h or 2 h algorithm. A single-sample rule-out applies only when pain began more than 3 hours before the first troponin, and her pain began 40 minutes ago. Her ST depression in I and aVL may be an early reciprocal change. A CBC matters because recent chemotherapy can lower her platelet count, which changes the antiplatelet choice.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "esc-acs-2023",
      },
      {
        id: "q2",
        kind: "single",
        update: "At 25 minutes, the repeat ECG shows 3 mm ST elevation in II, III and aVF with ST depression in I and aVL. Platelets are 42 x 10^9/L and hemoglobin is 104 g/L. She asks whether her cancer means she should not have a procedure.",
        prompt: "Which of the following reperfusion strategies is most appropriate for her?",
        options: [
          "Admit for medical therapy because of her cancer",
          "Angiography within 24 hours once platelets recover",
          "Palliative care assessment before any procedure",
          "Tenecteplase now in the emergency department",
          "Urgent primary PCI through cath lab activation",
        ],
        correct: 4,
        explanation:
          "Her ECG now shows an inferior STEMI in a hospital that can do PCI, so primary PCI is the reperfusion strategy. ESC 2023 recommends an invasive strategy for patients with cancer and high-risk ACS whose expected survival is 6 months or more, and her cancer is being treated with curative intent. Medical therapy alone, or palliative assessment first, fits a prognosis under 6 months or a very high bleeding risk, which is not her situation. Waiting 24 hours for platelets to recover leaves the artery occluded. Fibrinolysis is used when primary PCI cannot happen within 120 minutes, which does not apply here.",
        keyFeature: { topic: TOPIC, n: 6 },
        source: "esc-acs-2023",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "The interventional cardiologist accepts her and asks what her cancer care changes about the usual antithrombotic plan.",
        prompt: "What changes to the usual antithrombotic plan for primary PCI does her cancer care require?",
        accept: [
          { id: "clop", text: "Clopidogrel as the P2Y12 inhibitor rather than ticagrelor or prasugrel", match: ["clopidogrel", "plavix"] },
          { id: "hold", text: "Temporary interruption of bevacizumab, agreed with her oncologist", match: ["bevacizumab", "hold chemotherapy", "interrupt chemotherapy", "pause chemotherapy", "stop chemotherapy", "hold cancer therapy", "interrupt cancer therapy", "stop cancer therapy", "pause cancer therapy"] },
          { id: "ddi", text: "Check interactions between the P2Y12 inhibitor and her cancer drugs", match: ["interaction", "cyp"] },
          { id: "hbr", text: "Treat her as high bleeding risk because of active cancer", match: ["bleeding risk", "high bleeding", "hbr"] },
        ],
        unacceptable: [
          { text: "Ticagrelor loading dose", match: ["ticagrelor 180", "ticagrelor loading", "load with ticagrelor", "brilinta 180"] },
          { text: "Prasugrel loading dose", match: ["prasugrel 60", "prasugrel loading", "load with prasugrel", "effient"] },
          { text: "Withhold all antiplatelet therapy", match: ["no antiplatelet", "withhold antiplatelet", "avoid antiplatelet"] },
        ],
        explanation:
          "Her platelet count of 42 x 10^9/L is below the 50 x 10^9/L level under which ESC 2023 advises against prasugrel or ticagrelor. It is above the levels for ASA (10 x 10^9/L) and clopidogrel (30 x 10^9/L), so both can still be given. Active cancer diagnosed in the past 12 months also makes her high bleeding risk, and ESC names clopidogrel the preferred P2Y12 inhibitor in active cancer. Bevacizumab is listed among cancer drugs with a high risk of ACS, and a temporary interruption is recommended when a cancer drug may have contributed. Interactions between P2Y12 inhibitors and cancer drugs should be checked. Withholding all antiplatelet therapy is not supported at her platelet count.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "esc-acs-2023",
      },
    ],
    sources: [S.esc2023],
    ...META,
    version: 2,
    reviewed: false,
  },
  {
    id: "ischemic-heart-disease-14",
    topic: TOPIC,
    title: "Crushing pain with widespread ST depression",
    stem:
      "A 66-year-old man presents with 1 hour of crushing chest pain and diaphoresis. He has diabetes and hypertension. Oxygen saturation is 95%. His ECG shows sinus rhythm with 2 mm ST elevation in aVR, 1 mm ST elevation in V1 and 2 mm horizontal ST depression in I, II, aVF and V4 to V6. The first high sensitivity troponin T is 54 ng/L.",
    vitals: { pulse: "98/minute", resp: "22/minute", bp: "102/68 mmHg", weight: "90 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What coronary lesions or processes does this ECG pattern suggest?",
        accept: [
          { id: "lm", text: "Left main coronary artery occlusion or stenosis", match: ["left main", "lmca"] },
          { id: "lad", text: "Proximal LAD occlusion", match: ["lad", "left anterior descending"] },
          { id: "mv", text: "Severe three vessel disease", match: ["multivessel", "multi vessel", "three vessel", "triple vessel", "3 vessel"] },
          { id: "sub", text: "Diffuse subendocardial ischemia", match: ["subendocardial", "diffuse ischemia"] },
        ],
        explanation:
          "ST elevation in aVR with widespread ST depression reflects diffuse subendocardial ischemia. In a patient with ongoing pain this suggests left main, proximal LAD or three vessel disease. It is a high risk pattern even though it does not meet classic STEMI criteria.",
        keyFeature: { topic: TOPIC, n: 2 },
        source: "esc-acs",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "After sublingual nitroglycerin his pain resolves and the ST changes largely normalize. A colleague suggests an outpatient angiogram.",
        prompt: "Why is this plan unsafe?",
        accept: [
          { id: "res", text: "Pain relief with nitroglycerin does not exclude ACS", match: ["resolution", "resolved", "pain free", "nitro", "nitroglycerin"] },
          { id: "dyn", text: "Dynamic ST changes mark him as high risk", match: ["dynamic", "transient", "st change", "ecg change"] },
          { id: "trop", text: "His troponin is already elevated", match: ["troponin"] },
          { id: "lm", text: "The pattern suggests left main or multivessel disease", match: ["left main", "multivessel", "lad", "three vessel"] },
          { id: "dm", text: "Diabetes and other risk factors", match: ["diabetes", "diabetic", "risk factor"] },
          { id: "bp", text: "Borderline low blood pressure", match: ["hypotension", "blood pressure"] },
        ],
        explanation:
          "Resolution of pain after nitroglycerin does not rule out ACS. Transient ST changes with a raised troponin define a high risk NSTE-ACS that needs inpatient care and early angiography.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "esc-acs",
      },
      {
        id: "q3",
        kind: "single",
        update: "Twenty minutes later the pain returns with the same ECG changes. BP 92/60 mmHg.",
        prompt: "Which of the following is the most appropriate management for him now?",
        options: [
          "Immediate invasive angiography, within 2 hours",
          "Invasive angiography within 24 hours",
          "Invasive angiography within 72 hours",
          "Stress test once the pain settles",
          "Tenecteplase now, then transfer for angiography",
        ],
        correct: 0,
        explanation:
          "Recurrent refractory pain with hemodynamic compromise and ST elevation in aVR is very high risk NSTE-ACS. Immediate angiography is recommended. Fibrinolysis is not indicated without STEMI criteria.",
        keyFeature: { topic: TOPIC, n: 3 },
        source: "esc-acs",
      },
      {
        id: "q4",
        kind: "short",
        required: 1,
        update: "The interventional cardiologist asks you to hold the P2Y12 inhibitor load until the coronary anatomy is known.",
        prompt: "What is the main reason for this request?",
        accept: [{ id: "cabg", text: "He may need urgent CABG, which a P2Y12 inhibitor would delay or complicate with bleeding", match: ["cabg", "bypass", "surgery", "surgical", "bleeding"] }],
        explanation:
          "Left main or three vessel disease is often treated with CABG. Ticagrelor and clopidogrel raise surgical bleeding and usually require a washout period. In NSTE-ACS with early angiography planned, the 2023 ESC guideline advises against routine P2Y12 pretreatment, so the load is given once the anatomy is known.",
        keyFeature: { topic: TOPIC, n: 7 },
        source: "esc-acs",
      },
    ],
    sources: [S.esc],
    ...META,
  },
  {
    id: "ischemic-heart-disease-15",
    topic: TOPIC,
    title: "Chest tightness while shovelling snow",
    stem:
      "A 47-year-old man presents at 1500 with chest tightness that began 1 hour ago while shovelling snow and eased after 5 minutes of rest. Over the past 3 weeks he has had similar brief episodes when walking up a steep hill, each relieved by rest. He has never had pain at rest. He has hypertension and dyslipidemia. Oxygen saturation is 98%. He is pain free.",
    vitals: { pulse: "72/minute", resp: "14/minute", bp: "136/84 mmHg", weight: "94 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What tests do you order immediately?",
        accept: [
          { id: "ecg", text: "12 lead ECG within 10 minutes of arrival", match: ["ecg", "ekg", "electrocardiogram"] },
          { id: "trop", text: "High sensitivity troponin", match: ["troponin", "trop"] },
          { id: "cxr", text: "Chest X-ray", match: ["chest x ray", "cxr", "chest xray"] },
          { id: "cbc", text: "CBC", match: ["cbc", "hemoglobin"] },
          { id: "lytes", text: "Electrolytes and creatinine", match: ["creatinine", "electrolyte"] },
        ],
        explanation:
          "Every patient with possible ACS needs an ECG within 10 minutes and an early troponin. A chest X-ray and basic blood work look for other causes and baseline values.",
        keyFeature: { topic: TOPIC, n: 1 },
        source: "aha-chest-pain",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "His ECG is normal. A high sensitivity troponin I drawn 70 minutes after symptom onset is 4 ng/L (99th percentile 26 ng/L). He wants to leave.",
        prompt: "Why does this single result not yet rule out ACS?",
        accept: [
          { id: "early", text: "It was drawn too soon after symptom onset", match: ["too early", "early", "70 minute", "onset", "3 hour", "too soon"] },
          { id: "serial", text: "A second sample is needed to look for a change", match: ["repeat", "serial", "delta", "second"] },
          { id: "ua", text: "Troponin can be normal in unstable angina", match: ["unstable angina", "angina"] },
          { id: "ecg", text: "A single normal ECG does not exclude ischemia", match: ["ecg"] },
        ],
        explanation:
          "A single very low troponin rules out MI only when drawn more than 3 hours after onset. Earlier samples need a repeat at 1 to 3 hours to measure the change. Troponin cannot exclude unstable angina, which is judged on the history.",
        keyFeature: { topic: TOPIC, n: 4 },
        source: "esc-acs",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "Repeat troponin at 2 hours is unchanged and his repeat ECG is normal. He remains pain free.",
        prompt: "What are the elements of your discharge plan?",
        accept: [
          { id: "test", text: "Expedited outpatient testing such as stress testing or CT coronary angiography", match: ["stress", "ccta", "ct coronary", "ct angiogram", "myocardial perfusion", "functional testing", "outpatient testing"] },
          { id: "ref", text: "Referral to cardiology or a rapid access chest pain clinic", match: ["cardiology", "cardiologist", "rapid access", "chest pain clinic"] },
          { id: "asa", text: "Daily ASA 81 mg", match: ["asa", "aspirin"] },
          { id: "ntg", text: "Sublingual nitroglycerin with instructions for use", match: ["nitroglycerin", "nitro", "ntg"] },
          { id: "avoid", text: "Avoid heavy exertion such as shovelling until assessed", match: ["avoid exertion", "avoid heavy", "avoid shovel", "exertion", "shovel", "shovelling", "activity"] },
          { id: "return", text: "Clear return and 911 instructions", match: ["return", "911"] },
          { id: "rf", text: "Risk factor management including statin and blood pressure control", match: ["statin", "atorvastatin", "risk factor", "lipid", "blood pressure"] },
          { id: "fp", text: "Follow up with his family physician", match: ["family physician", "family doctor", "primary care"] },
        ],
        explanation:
          "New exertional angina with negative serial troponins is low short term risk but not a resolved diagnosis. He needs prompt outpatient investigation, empiric antianginal and antiplatelet therapy and clear instructions until coronary disease is confirmed or excluded.",
        keyFeature: { topic: TOPIC, n: 8 },
        source: "aha-chest-pain",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What features of recurrent symptoms should prompt him to call 911 rather than wait for his appointment?",
        accept: [
          { id: "rest", text: "Pain at rest", match: ["rest"] },
          { id: "long", text: "Pain lasting more than 15 to 20 minutes", match: ["20 minute", "15 minute", "prolonged", "longer", "persistent", "lasting"] },
          { id: "ntg", text: "Pain not relieved by nitroglycerin", match: ["not relieved", "unrelieved", "nitro", "nitroglycerin", "no relief", "no response"] },
          { id: "cresc", text: "Episodes becoming more frequent or brought on by less effort", match: ["frequency", "frequent", "less exertion", "less effort", "crescendo", "worsening", "increasing"] },
          { id: "assoc", text: "Syncope, marked dyspnea or sweating with the pain", match: ["syncope", "faint", "shortness of breath", "sweat", "sweating", "diaphoresis"] },
        ],
        explanation:
          "Rest pain, prolonged pain, pain unrelieved by nitroglycerin or a crescendo pattern means possible unstable angina or MI. Clear instructions are part of safe follow up for low risk patients.",
        keyFeature: { topic: TOPIC, n: 8 },
        source: "aha-chest-pain",
      },
    ],
    sources: [S.chestPain, S.esc],
    ...META,
  },
];
