// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { KeyItem, Samp, UnacceptableItem } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Draft for review by Arjan Dhoot, MD", version: 1 } as const;

const k = (id: string, text: string, ...match: string[]): KeyItem => ({ id, text, match });
const no = (text: string, ...match: string[]): UnacceptableItem => ({ text, match });
const harm = (text: string, ...match: string[]): UnacceptableItem => ({ text, match, dangerous: true });

const S = {
  cosGlaucoma: {
    id: "cos-glaucoma",
    citation:
      "Canadian Ophthalmological Society Glaucoma Clinical Practice Guideline Expert Committee. Canadian Ophthalmological Society evidence-based clinical practice guidelines for the management of glaucoma in the adult eye. Can J Ophthalmol. 2009.",
  },
  aaoPac: { id: "aao-pac", citation: "Gedde SJ, et al. Primary angle closure disease Preferred Practice Pattern. American Academy of Ophthalmology. Ophthalmology. 2021." },
  aaoConj: { id: "aao-conj", citation: "American Academy of Ophthalmology Cornea/External Disease Committee. Conjunctivitis Preferred Practice Pattern. Ophthalmology. 2024." },
  aaoKeratitis: { id: "aao-keratitis", citation: "American Academy of Ophthalmology Cornea/External Disease Committee. Bacterial keratitis Preferred Practice Pattern. Ophthalmology. 2024." },
  aaoRao: { id: "aao-rao", citation: "Flaxel CJ, et al. Retinal and ophthalmic artery occlusions Preferred Practice Pattern. American Academy of Ophthalmology. Ophthalmology. 2020." },
  aaoPvd: {
    id: "aao-pvd",
    citation: "Flaxel CJ, et al. Posterior vitreous detachment, retinal breaks and lattice degeneration Preferred Practice Pattern. American Academy of Ophthalmology. Ophthalmology. 2020.",
  },
  hsv: {
    id: "aao-hsv",
    citation: "White ML, Chodosh J. Herpes simplex virus keratitis. A treatment guideline. American Academy of Ophthalmology. 2014.",
  },
  ahaCrao: {
    id: "aha-crao",
    citation: "Mac Grory B, et al. Management of central retinal artery occlusion. A scientific statement from the American Heart Association. Stroke. 2021.",
  },
  csbpr: {
    id: "csbpr",
    citation: "Heran M, et al. Canadian Stroke Best Practice Recommendations. Acute stroke management, 7th edition practice guidelines update. Heart and Stroke Foundation of Canada. Can J Neurol Sci. 2022.",
  },
  acrGca: {
    id: "acr-gca",
    citation:
      "Maz M, et al. 2021 American College of Rheumatology/Vasculitis Foundation guideline for the management of giant cell arteritis and Takayasu arteritis. Arthritis Rheumatol. 2021.",
  },
  bsrGca: {
    id: "bsr-gca",
    citation: "Mackie SL, et al. British Society for Rheumatology guideline on diagnosis and treatment of giant cell arteritis. Rheumatology (Oxford). 2020.",
  },
  rosen: {
    id: "rosen",
    citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. 10th ed. Elsevier. 2023. Chapter on ophthalmology.",
  },
  tintinalli: {
    id: "tintinalli",
    citation: "Tintinalli JE, Ma OJ, Yealy DM, Meckler GD, Stapczynski JS, Cline DM, Thomas SH, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. 9th ed. McGraw Hill. 2020. Chapter 122, Eye Emergencies in Infants and Children. Chapter 239, Thrombotics and Antithrombotics. Chapter 241, Eye Emergencies.",
  },
} satisfies Record<string, Source>;

const VA = k("va", "Visual acuity in each eye", "visual acuity", "va", "acuity", "snellen");

export const EYE_SAMPS: Samp[] = [
  {
    id: "eye-01",
    topic: "eye",
    alsoTopics: ["headache"],
    title: "Headache and vomiting after an evening out",
    stem:
      "A 67-year-old woman arrives at 23:10 with 3 hours of severe right eye pain, right frontal headache and two episodes of vomiting. The pain began while she was watching a film in a dark theatre. She now sees coloured halos around lights. She takes hydrochlorothiazide. Yesterday she started an over the counter cold remedy that contains diphenhydramine. She has worn glasses for farsightedness since her forties. The right eye is diffusely red. The triage note reads migraine with conjunctivitis.",
    vitals: { temperature: "36.8°C", pulse: "96/minute", resp: "18/minute", bp: "172/94 mmHg", o2sat: "98% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "Before you accept the triage impression, what findings would you examine for and document in the right eye?",
        accept: [
          VA,
          k("iop", "Intraocular pressure by tonometry", "intraocular pressure", "iop", "tonometry", "tonopen", "tono pen"),
          k("pupil", "Pupil size and reactivity, looking for a fixed mid position pupil", "pupil"),
          k("cornea", "Corneal clouding or edema on slit lamp", "cornea", "corneal"),
          k("ac", "Anterior chamber depth", "anterior chamber", "shallow chamber"),
          k("flush", "Ciliary flush at the limbus", "ciliary flush", "perilimbal", "limbal flush"),
        ],
        unacceptable: [
          harm("Dilate the pupil with mydriatic drops", "give tropicamide", "instil tropicamide", "instill tropicamide", "give mydriatic", "instil mydriatic", "instill mydriatic", "give cyclopentolate", "give phenylephrine drop"),
          no("Dilated fundus examination", "dilated fundus", "dilating drop", "mydriatic drop", "tropicamide"),
        ],
        explanation:
          "Visual acuity comes first in every eye complaint. A red painful eye with halos, vomiting and a fixed mid dilated pupil is acute angle closure until IOP says otherwise. Corneal haze and a shallow chamber support it. Dilating drops can worsen the angle closure and must be avoided.",
        keyFeature: { topic: "eye", n: 3 },
        source: "aao-pac",
      },
      {
        id: "q2",
        kind: "menu",
        select: 3,
        update:
          "Right visual acuity is 20/200 and left is 20/30. The right pupil is 5 mm and nonreactive. The right cornea is hazy and the anterior chamber is shallow. IOP is 62 mmHg on the right and 17 mmHg on the left. She has no asthma, no heart block and no sulfonamide allergy.",
        prompt: "Which of the following medications should she receive now for her right eye?",
        options: [
          "Acetazolamide 5 g IV",
          "Acetazolamide 500 mg IV",
          "Apraclonidine 1% one drop to the right eye",
          "Cyclopentolate 1% one drop to the right eye",
          "Moxifloxacin 0.5% one drop every hour",
          "Phenylephrine 2.5% one drop to the right eye",
          "Pilocarpine 4% every 5 minutes for one hour",
          "Prednisone 60 mg PO",
          "Tetracaine 0.5% drops to take home",
          "Timolol 0.5% one drop to the right eye",
        ],
        correct: [1, 2, 9],
        explanation:
          "First line therapy lowers aqueous production with a topical beta blocker, an alpha agonist and a carbonic anhydrase inhibitor. Acetazolamide 500 mg IV or PO is the usual adult dose. Low strength pilocarpine is added once the pressure starts to fall. Intensive high strength pilocarpine can worsen the block, and a cycloplegic is contraindicated.",
        keyFeature: { topic: "eye", n: 1 },
        source: "cos-glaucoma",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What features of her history predisposed her to this presentation?",
        accept: [
          k("dark", "Dim light in the theatre causing pupil dilation", "dark", "dim light", "theatre", "theater", "low light"),
          k("anticholinergic", "Diphenhydramine, an anticholinergic antihistamine", "diphenhydramine", "anticholinergic", "antihistamine", "cold remedy"),
          k("hyperopia", "Hyperopia with a short eye and crowded angle", "hyperopia", "farsighted", "hyperope", "farsightedness"),
          k("age", "Older age with a thickening lens", "age", "older", "elderly"),
          k("sex", "Female sex", "female", "woman", "women"),
        ],
        explanation:
          "Angle closure is favoured by a small hyperopic eye, age, female sex and anything that dilates the pupil. Dim light and anticholinergic drugs such as diphenhydramine are classic triggers. Sulfonamide drugs such as topiramate and, rarely, thiazides cause a different bilateral form from ciliary body swelling, usually soon after starting the drug. Her long standing thiazide does not explain a unilateral pupil block attack.",
        keyFeature: { topic: "eye", n: 2 },
        source: "aao-pac",
      },
      {
        id: "q4",
        kind: "single",
        update: "One hour after treatment the right IOP is 34 mmHg and the pain is easing.",
        prompt: "Which of the following is the most appropriate disposition for this patient?",
        options: [
          "Admit to internal medicine for blood pressure control",
          "CT head to exclude a subarachnoid hemorrhage",
          "Discharge on timolol drops with ophthalmology in one week",
          "Lumbar puncture to exclude meningitis",
          "Urgent ophthalmology today for laser peripheral iridotomy",
        ],
        correct: 4,
        explanation:
          "Medical therapy only buys time. Definitive treatment is laser peripheral iridotomy, and the fellow eye usually needs prophylactic laser because it shares the same anatomy. The history and findings explain the headache, so CT and LP only delay care. The elevated BP reflects pain and vomiting.",
        keyFeature: { topic: "headache", n: 4 },
        source: "cos-glaucoma",
      },
    ],
    sources: [S.aaoPac, S.cosGlaucoma],
    ...META,
  },
  {
    id: "eye-02",
    topic: "eye",
    title: "Student with a sore eye after a walk in clinic visit",
    stem:
      "A 23-year-old university student has 2 days of right eye pain, redness, tearing and light sensitivity. She wears soft monthly contact lenses and often sleeps in them on weekends. A walk in clinic diagnosed conjunctivitis yesterday and prescribed polymyxin B and trimethoprim drops. The pain is worse today. Vital signs are normal. Visual acuity is 20/80 in the right eye and 20/20 in the left eye with glasses.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What slit lamp findings would indicate a diagnosis more serious than conjunctivitis?",
        accept: [
          k("infiltrate", "Corneal infiltrate or white opacity", "infiltrate", "opacity", "white spot", "ulcer"),
          k("stain", "Epithelial defect staining with fluorescein", "fluorescein", "staining", "epithelial defect"),
          k("cells", "Anterior chamber cells or flare", "anterior chamber cell", "ac cell", "flare", "cell and flare"),
          k("hypopyon", "Hypopyon", "hypopyon"),
          k("flush", "Ciliary flush", "ciliary flush", "limbal flush", "perilimbal"),
          k("edema", "Stromal edema or corneal haze", "stromal edema", "corneal edema", "haze"),
          k("fb", "Retained foreign body or lens fragment", "foreign body", "lens fragment"),
        ],
        explanation:
          "Pain, photophobia and reduced vision in a contact lens wearer mean keratitis until proven otherwise. Conjunctivitis should not reduce acuity or cause an infiltrate, a staining defect or anterior chamber reaction. A hypopyon signals a severe infection.",
        keyFeature: { topic: "eye", n: 1 },
        source: "aao-keratitis",
      },
      {
        id: "q2",
        kind: "single",
        update: "Slit lamp shows a 2 mm white paracentral corneal infiltrate with an overlying fluorescein staining epithelial defect and 1+ anterior chamber cells. There is no hypopyon.",
        prompt: "Which of the following organisms must your empiric therapy cover above all in this patient?",
        options: [
          "Candida albicans",
          "Chlamydia trachomatis",
          "Human adenovirus",
          "Pseudomonas aeruginosa",
          "Streptococcus pyogenes",
        ],
        correct: 3,
        explanation:
          "Pseudomonas is the key pathogen in contact lens associated keratitis and can perforate the cornea within days. Topical fluoroquinolones cover it. Acanthamoeba and fungi are rarer and are considered when a lesion fails to respond.",
        keyFeature: { topic: "eye", n: 1 },
        source: "aao-keratitis",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What are the parts of your emergency department management?",
        accept: [
          k("stoplens", "Stop contact lens wear", "stop contact", "no contact", "discontinue contact", "remove contact", "stop lens", "no lens"),
          k("fq", "Topical fluoroquinolone such as moxifloxacin every hour while awake", "fluoroquinolone", "moxifloxacin", "ciprofloxacin", "ofloxacin", "gatifloxacin", "besifloxacin"),
          k("ophtho", "Ophthalmology assessment within 24 hours for scraping and culture", "ophthalmology", "ophthalmologist", "eye specialist"),
          k("case", "Send the lenses and case for culture", "lens case", "lense case", "case for culture", "culture the case", "culture lens", "culture lense", "culture the lense", "culture contact"),
          k("cyclo", "Cycloplegic drop such as cyclopentolate for pain", "cycloplegic", "cyclopentolate", "homatropine"),
          k("analgesia", "Oral analgesia", "analgesia", "acetaminophen", "ibuprofen", "oral pain"),
        ],
        unacceptable: [
          harm("Patch the eye", "patch the eye", "apply patch", "apply a patch", "place patch", "pressure patch the"),
          harm("Start a topical steroid", "start steroid", "give steroid", "prescribe steroid", "add steroid", "start dexamethasone", "start prednisolone", "prescribe dexamethasone", "prescribe prednisolone", "tobradex"),
          no("Eye patch or topical steroid", "eye patch", "pressure patch", "steroid drop", "topical steroid", "dexamethasone", "prednisolone"),
          no("Topical anaesthetic drops for home use", "tetracaine home", "anesthetic home", "anaesthetic home", "proparacaine home"),
        ],
        explanation:
          "Stop lens wear, start frequent topical fluoroquinolone and arrange ophthalmology within 24 hours for culture. Patching a contact lens related lesion promotes Pseudomonas growth. Steroids before the organism is controlled can lead to melt. Home anaesthetic drops delay healing and mask worsening.",
        keyFeature: { topic: "eye", n: 3 },
        source: "aao-keratitis",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What habits or exposures would you ask about that raise the risk of this infection?",
        accept: [
          k("overnight", "Overnight or extended lens wear", "overnight", "sleeping in", "sleep in", "extended wear"),
          k("water", "Swimming, showering or hot tubs while wearing lenses", "swimming", "shower", "hot tub", "swim"),
          k("tap", "Rinsing lenses or case with tap water", "tap water", "rinse"),
          k("overuse", "Wearing lenses beyond the replacement schedule", "beyond replacement", "overuse", "overwear", "replacement schedule"),
          k("hygiene", "Poor case hygiene or topping up solution", "case hygiene", "topping up", "hygiene"),
          k("steroiduse", "Recent topical steroid use", "recent steroid", "steroid use"),
        ],
        explanation:
          "Overnight wear is the strongest modifiable risk factor for microbial keratitis. Water exposure raises the risk of Acanthamoeba. These answers also guide counselling to prevent recurrence.",
        keyFeature: { topic: "eye", n: 2 },
        source: "rosen",
      },
    ],
    sources: [S.aaoKeratitis, S.rosen],
    ...META,
  },
  {
    id: "eye-03",
    topic: "eye",
    title: "Red eye worsening on prescribed drops",
    stem:
      "A 41-year-old man has had a red, watery left eye for 5 days. A walk in clinic prescribed tobramycin and dexamethasone drops 3 days ago. Since then the eye is more painful and light sensitive and his vision is blurred. He gets cold sores a few times a year. Vital signs are normal. Visual acuity is 20/60 in the left eye and 20/20 in the right.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of this presentation argue against simple conjunctivitis?",
        accept: [
          k("vision", "Reduced visual acuity", "reduced vision", "blurred", "decreased vision", "reduced acuity", "20/60", "visual acuity"),
          k("photo", "Photophobia", "photophobia", "light sensitive", "light sensitivity"),
          k("pain", "Significant eye pain", "pain", "painful"),
          k("hsv", "History of recurrent cold sores", "cold sore", "hsv", "herpes"),
          k("worse", "Worsening on a topical steroid", "worse on", "worsening", "steroid"),
          k("unilateral", "Persistent unilateral involvement", "unilateral", "one eye"),
        ],
        explanation:
          "Conjunctivitis causes irritation and discharge but not true pain, photophobia or loss of acuity. Those features point to corneal or intraocular disease. Worsening on a steroid combination with a history of cold sores strongly suggests herpes simplex keratitis.",
        keyFeature: { topic: "eye", n: 1 },
        source: "aao-conj",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "Fluorescein shows a branching epithelial lesion with terminal bulbs in the central cornea. Corneal sensation is reduced. The anterior chamber is quiet.",
        prompt: "What are the steps in your management?",
        accept: [
          k("stopster", "Stop the tobramycin and dexamethasone drops", "stop dexamethasone", "stop steroid", "stop tobradex", "stop tobramycin", "stop the drop", "discontinue steroid", "discontinue dexamethasone", "discontinue the drop", "discontinue tobradex", "hold steroid", "hold dexamethasone", "hold tobradex"),
          k("oral", "Oral antiviral such as acyclovir 400 mg five times daily or valacyclovir", "acyclovir", "valacyclovir", "famciclovir", "oral antiviral"),
          k("topical", "Topical antiviral such as ganciclovir gel or trifluridine drops", "ganciclovir", "trifluridine", "topical antiviral"),
          k("ophtho", "Ophthalmology follow up within 24 to 48 hours", "ophthalmology", "ophthalmologist"),
          k("lube", "Lubricating drops for comfort", "lubricant", "artificial tear", "lubricating"),
        ],
        unacceptable: [
          harm("Continue or increase the steroid drops", "continue steroid", "increase steroid", "continue dexamethasone", "continue tobradex", "more steroid"),
          no("Topical antibiotic as sole treatment", "antibiotic only"),
        ],
        explanation:
          "Dendritic epithelial keratitis needs an oral or topical antiviral and the steroid stopped. Topical steroids feed active epithelial HSV and can convert a dendrite into a large geographic ulcer. Ophthalmology should review within a day or two.",
        keyFeature: { topic: "eye", n: 4 },
        source: "aao-hsv",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What complications can unsupervised topical steroids cause in this patient?",
        accept: [
          k("geographic", "Enlarging geographic ulcer", "geographic", "enlarging ulcer", "worse ulcer", "worsening ulcer"),
          k("scar", "Stromal keratitis and corneal scarring", "scar", "scarring", "stromal"),
          k("perf", "Corneal thinning, melt or perforation", "perforation", "melt", "thinning"),
          k("iop", "Raised intraocular pressure or steroid glaucoma", "intraocular pressure", "iop", "glaucoma"),
          k("cataract", "Cataract", "cataract"),
          k("super", "Bacterial or fungal superinfection", "superinfection", "fungal", "bacterial"),
        ],
        explanation:
          "Steroids enhance viral replication in the epithelium and slow healing. The result can be a geographic ulcer, scarring or perforation. Longer use adds raised IOP and cataract. Emergency physicians should not start topical steroids for a presumed viral red eye.",
        keyFeature: { topic: "eye", n: 4 },
        source: "aao-hsv",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following oral regimens is most appropriate for this epithelial disease?",
        options: [
          "Acyclovir 200 mg daily for 3 days",
          "Acyclovir 400 mg five times daily, 7 to 10 days",
          "Cephalexin 500 mg four times daily for 7 days",
          "Oseltamivir 75 mg twice daily for 5 days",
          "Valacyclovir 500 mg once daily for 3 days",
        ],
        correct: 1,
        explanation:
          "Acyclovir 400 mg five times daily is a standard oral regimen for HSV epithelial keratitis. Valacyclovir 500 mg two or three times daily is an alternative. Once daily or short courses are suppression doses and undertreat active disease.",
        keyFeature: { topic: "eye", n: 4 },
        source: "aao-hsv",
      },
    ],
    sources: [S.aaoConj, S.hsv],
    ...META,
  },
  {
    id: "eye-04",
    topic: "eye",
    title: "Daycare worker with two red eyes",
    stem:
      "A 29-year-old daycare worker has had 3 days of redness and watery discharge, first in the right eye and now the left. Her eyes feel gritty. She had a sore throat last week. Several children at work have red eyes. She has no photophobia and thinks her vision is normal. She does not wear contact lenses. Vital signs are normal. A small tender preauricular node is felt on the right. She asks for the strong drops a friend received for the same problem.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What elements of the eye examination do you need before diagnosing viral conjunctivitis?",
        accept: [
          VA,
          k("fluor", "Fluorescein staining of the cornea", "fluorescein", "staining"),
          k("cornea", "Slit lamp examination of the cornea for infiltrates or dendrites", "infiltrate", "dendrite", "slit lamp"),
          k("ac", "Anterior chamber for cells and flare", "anterior chamber", "cell and flare", "ac cell"),
          k("pupil", "Pupil size and reactivity", "pupil"),
          k("iop", "Intraocular pressure", "intraocular pressure", "iop", "tonometry"),
          k("evert", "Lid eversion for follicles or a foreign body", "evert", "eversion", "follicle"),
        ],
        explanation:
          "Acuity is measured first in every eye complaint. A slit lamp with fluorescein excludes keratitis, dendrites and foreign bodies. A normal pupil, quiet chamber and normal pressure exclude iritis and glaucoma. Only then is conjunctivitis a safe label.",
        keyFeature: { topic: "eye", n: 3 },
        source: "aao-conj",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update:
          "Acuity is 20/20 in both eyes. There are conjunctival follicles and injection. There is no corneal staining or infiltrate, the anterior chamber is quiet and the pupils are normal.",
        prompt: "She again asks for a steroid and antibiotic combination drop. What are the reasons to decline?",
        accept: [
          k("hsv", "It can worsen an unrecognized herpes simplex infection", "herpes", "hsv"),
          k("shed", "It can prolong viral replication and shedding", "prolong", "shedding", "replication"),
          k("iop", "It can raise intraocular pressure", "intraocular pressure", "iop", "glaucoma"),
          k("cataract", "It can cause cataract", "cataract"),
          k("nobenefit", "The illness is self limited and gains no benefit from antibiotic or steroid", "self limited", "no benefit", "not needed", "unnecessary", "viral"),
          k("super", "It can promote bacterial or fungal superinfection", "superinfection", "fungal"),
        ],
        explanation:
          "Adenoviral conjunctivitis resolves on its own over one to three weeks. Topical steroids can prolong viral shedding, worsen missed HSV and raise IOP. They are reserved for ophthalmology in selected cases with membranes or vision reducing infiltrates.",
        keyFeature: { topic: "eye", n: 4 },
        source: "aao-conj",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What instructions would you give her?",
        accept: [
          k("cold", "Cold compresses", "cold compress", "cold compresses", "cool compresses", "compresses", "compress", "ice pack"),
          k("tears", "Artificial tears", "artificial tear", "lubricant", "lubricating"),
          k("hands", "Frequent hand washing", "hand washing", "hand hygiene", "wash hand", "handwashing"),
          k("share", "Do not share towels, pillows or makeup", "not share", "dont share", "don share", "no sharing", "avoid sharing", "own towel", "separate towel", "towel", "pillow", "makeup"),
          k("work", "Stay off work while the eyes are red and discharging", "off work", "stay home", "no work", "time off", "contagious", "exclude from work", "away from work"),
          k("return", "Return for pain, light sensitivity or reduced vision", "return", "come back"),
        ],
        unacceptable: [no("Topical antibiotic drops", "antibiotic drop", "antibiotic ointment")],
        explanation:
          "Care is supportive with cold compresses and lubricants. The virus is highly contagious for up to two weeks, so hygiene and time away from a daycare matter. Return precautions catch the corneal infiltrates that can follow.",
        keyFeature: { topic: "eye", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "menu",
        select: 1,
        prompt: "Which of the following medications should be prescribed for her red eyes?",
        options: [
          "Acyclovir 400 mg PO five times daily",
          "Erythromycin ointment",
          "Moxifloxacin 0.5% drops",
          "Polymyxin B and trimethoprim drops",
          "Prednisolone acetate 1% drops",
          "Tobramycin and dexamethasone drops",
          "None",
        ],
        correct: [6],
        explanation:
          "Uncomplicated adenoviral conjunctivitis needs no antibiotic, antiviral or steroid. Acyclovir has no activity against adenovirus. Unneeded antibiotics add cost, allergy and resistance without speeding recovery.",
        keyFeature: { topic: "eye", n: 4 },
        source: "aao-conj",
      },
    ],
    sources: [S.aaoConj, S.tintinalli],
    ...META,
  },
  {
    id: "eye-05",
    topic: "eye",
    title: "Forehead rash and a watery eye",
    stem:
      "A 74-year-old man has 4 days of burning pain over the left forehead. Yesterday a vesicular rash appeared on the left forehead, upper eyelid and tip of the nose. Today his left eye is red and watery. He takes methotrexate for rheumatoid arthritis. Visual acuity is 20/40 in the left eye and 20/25 in the right.",
    vitals: { temperature: "37.4°C", pulse: "84/minute", bp: "146/82 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What further history elements would you obtain?",
        accept: [
          k("onset", "Time since rash onset", "onset", "how long", "timing", "72 hour", "when the rash"),
          k("vision", "Change in vision", "vision change", "blurred", "change in vision", "visual change", "vision loss"),
          k("photo", "Photophobia or deep eye pain", "photophobia", "eye pain", "light sensitivity"),
          k("immuno", "Other immunosuppression such as prednisone, biologics, HIV or cancer", "immunosuppression", "immunocompromised", "biologic", "hiv", "cancer", "prednisone"),
          k("vaccine", "Prior zoster vaccination", "vaccine", "vaccination", "shingrix"),
          k("prior", "Prior eye disease or eye surgery", "prior eye", "previous eye", "eye surgery"),
          k("contacts", "Contact with pregnant, newborn or immunocompromised people", "pregnant", "newborn", "contact with"),
        ],
        explanation:
          "Timing guides antiviral benefit, although eye involvement warrants treatment even after 72 hours. Vision change and photophobia suggest keratitis or uveitis. Immunosuppression such as methotrexate raises the risk of severe or disseminated disease.",
        keyFeature: { topic: "eye", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following best describes the main significance of the lesion on the tip of the nose?",
        options: [
          "Bacterial superinfection of the vesicles",
          "Disseminated zoster that requires isolation",
          "Involvement of the maxillary division",
          "Nasociliary branch involvement predicting eye involvement",
          "No clinical significance for the eye",
        ],
        correct: 3,
        explanation:
          "The nasociliary nerve supplies the nasal tip and the globe. A lesion there, Hutchinson sign, markedly raises the chance of eye involvement. Every patient with ophthalmic zoster still needs a slit lamp examination.",
        keyFeature: { topic: "eye", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "Slit lamp shows faintly staining pseudodendrites and 1+ anterior chamber cells. IOP is 24 mmHg on the left.",
        prompt: "What are the parts of your treatment plan, including the drug, dose and route for any antiviral?",
        accept: [
          k("vala", "Valacyclovir 1 g PO three times daily for 7 days", "valacyclovir 1 g", "valacyclovir 1000 mg", "valacyclovir 1g"),
          k("famci", "Famciclovir 500 mg PO three times daily for 7 days", "famciclovir 500 mg", "famciclovir 500mg"),
          k("acyclo", "Acyclovir 800 mg PO five times daily for 7 days", "acyclovir 800 mg", "acyclovir 800mg"),
          k("ophtho", "Ophthalmology assessment within 24 hours", "ophthalmology", "ophthalmologist"),
          k("analgesia", "Analgesia for acute neuritis", "analgesia", "acetaminophen", "pain control", "gabapentin"),
          k("lube", "Lubricating drops", "lubricant", "artificial tear", "lubricating"),
        ],
        unacceptable: [
          no("Topical steroid started in the emergency department", "topical steroid", "prednisolone", "steroid drop", "dexamethasone"),
          no("Topical acyclovir cream in the eye", "acyclovir cream"),
        ],
        explanation:
          "Oral antivirals at zoster doses reduce ocular complications. Acyclovir at herpes simplex doses is too low. Uveitis in zoster may later need topical steroid, but that decision belongs to ophthalmology after assessment. Starting steroid drops from the emergency department risks worsening viral epithelial disease.",
        keyFeature: { topic: "eye", n: 4 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What other issues would you address before discharge?",
        accept: [
          k("mtx", "Discuss holding methotrexate with his rheumatologist", "methotrexate", "hold methotrexate", "stop methotrexate", "withhold methotrexate", "rheumatologist"),
          k("isolate", "Avoid contact with pregnant, newborn or immunocompromised people until crusted", "avoid contact", "no contact", "pregnant", "newborn", "crusted", "contact"),
          k("phn", "Plan for pain and postherpetic neuralgia", "postherpetic", "neuralgia", "pain"),
          k("followup", "Confirmed ophthalmology follow up and IOP recheck", "follow up", "followup", "ophthalmology", "iop"),
          k("vaccine", "Recombinant zoster vaccine after recovery", "vaccine", "shingrix"),
          k("return", "Return for worsening vision or eye pain", "return", "worsening vision"),
        ],
        explanation:
          "Immunosuppression may need adjustment during active infection. Vesicular lesions are contagious to people without immunity. Pain control and firm eye follow up prevent the two commonest harms of ophthalmic zoster.",
        keyFeature: { topic: "eye", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },
  {
    id: "eye-06",
    topic: "eye",
    title: "Young man with a painful blurry eye",
    stem:
      "A 34-year-old man has 2 days of a deep ache in the right eye with redness, light sensitivity and blurred vision. He has had low back pain and morning stiffness for years that improves with activity. He had a similar episode in the left eye 2 years ago that settled on its own. He does not wear contact lenses and has had no trauma. Vital signs are normal. Visual acuity is 20/50 in the right eye and 20/20 in the left.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What examination findings would support your leading diagnosis?",
        accept: [
          k("flush", "Ciliary flush", "ciliary flush", "perilimbal", "limbal flush"),
          k("cells", "Anterior chamber cells", "anterior chamber cell", "ac cell", "cells"),
          k("flare", "Anterior chamber flare", "flare"),
          k("kp", "Keratic precipitates", "keratic precipitate", "kp"),
          k("pupil", "Small or irregular pupil from posterior synechiae", "synechia", "synechiae", "irregular pupil", "small pupil", "miosis", "miotic"),
          k("consensual", "Consensual photophobia when light is shone in the other eye", "consensual"),
          k("hypopyon", "Hypopyon", "hypopyon"),
        ],
        explanation:
          "Acute anterior uveitis causes perilimbal flush, photophobia and reduced acuity. The slit lamp shows cells and flare, often with keratic precipitates. Consensual photophobia helps separate it from conjunctivitis at the bedside.",
        keyFeature: { topic: "eye", n: 3 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What systemic conditions would you ask about?",
        accept: [
          k("as", "Ankylosing spondylitis or axial spondyloarthritis", "ankylosing", "spondylitis", "spondyloarthritis", "spondyloarthropathy"),
          k("ibd", "Inflammatory bowel disease", "inflammatory bowel", "ibd", "crohn", "ulcerative colitis"),
          k("psoriasis", "Psoriasis or psoriatic arthritis", "psoriasis", "psoriatic"),
          k("reactive", "Reactive arthritis", "reactive arthritis", "reiter"),
          k("sarcoid", "Sarcoidosis", "sarcoidosis", "sarcoid"),
          k("syphilis", "Syphilis", "syphilis"),
          k("tb", "Tuberculosis", "tuberculosis", "tb"),
          k("hla", "HLA B27 associated disease", "hla b27", "b27"),
          k("behcet", "Behcet disease", "behcet"),
        ],
        explanation:
          "Inflammatory back pain with recurrent alternating anterior uveitis is typical of HLA B27 spondyloarthritis. Asking about bowel, skin and joint disease can uncover an undiagnosed cause. Infectious causes such as syphilis change treatment.",
        keyFeature: { topic: "eye", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "Slit lamp shows 2+ cells with flare and a few fine keratic precipitates. There is no corneal staining. IOP is 14 mmHg.",
        prompt: "Which of the following treatments are appropriate for his right eye now?",
        options: [
          "Acyclovir 800 mg PO five times daily",
          "Cyclopentolate 1% one drop three times daily",
          "Moxifloxacin 0.5% drops four times daily",
          "Pilocarpine 2% drops four times daily",
          "Prednisolone acetate 1% drops after ophthalmology input",
          "Pressure patch for 24 hours",
          "Tetracaine drops for home use",
          "Timolol 0.5% drops twice daily",
        ],
        correct: [1, 4],
        explanation:
          "A cycloplegic relieves ciliary spasm and prevents synechiae. A topical steroid is the mainstay once infection is excluded, ideally started with ophthalmology input and follow up. Pilocarpine constricts the pupil and promotes synechiae. Antibiotics play no role.",
        keyFeature: { topic: "eye", n: 3 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following follow up arrangements is most appropriate for this patient?",
        options: [
          "Family physician in 2 weeks",
          "Ophthalmology within 24 to 48 hours",
          "Repeat ED visit in one week",
          "Rheumatology in 3 months with no eye follow up",
          "No follow up if symptoms settle",
        ],
        correct: 1,
        explanation:
          "Anterior uveitis needs slit lamp monitoring of inflammation and IOP during steroid therapy. Misdiagnosis as conjunctivitis without follow up risks synechiae, glaucoma and cataract. Rheumatology referral is useful but does not replace eye follow up.",
        keyFeature: { topic: "eye", n: 1 },
        source: "tintinalli",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },
  {
    id: "eye-07",
    topic: "eye",
    alsoTopics: ["headache"],
    title: "Older woman who woke unable to see",
    stem:
      "A 77-year-old woman woke today unable to see out of her left eye. There is no eye pain. She has hypertension and hypothyroidism. Visual acuity is counting fingers at 1 metre in the left eye and 20/30 in the right.",
    vitals: { temperature: "37.6°C", pulse: "82/minute", resp: "16/minute", bp: "154/80 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What symptoms would you specifically ask about?",
        accept: [
          k("ha", "New headache or temple pain", "headache", "temple", "temporal"),
          k("jaw", "Jaw claudication", "jaw", "claudication", "chewing"),
          k("scalp", "Scalp tenderness", "scalp"),
          k("pmr", "Shoulder or hip girdle stiffness", "shoulder", "hip", "girdle", "polymyalgia", "pmr"),
          k("constitutional", "Fever, weight loss, night sweats or fatigue", "weight loss", "fever", "night sweat", "fatigue", "constitutional"),
          k("amaurosis", "Earlier transient vision loss or double vision", "transient", "amaurosis", "diplopia", "double vision"),
          k("rd", "Flashes, floaters or a curtain", "flash", "flashes", "floater", "curtain"),
        ],
        explanation:
          "Painless monocular vision loss in an older adult needs a targeted history for giant cell arteritis. Jaw claudication, scalp tenderness and polymyalgia symptoms raise the likelihood sharply. Transient episodes beforehand often precede permanent loss. Flashes and floaters point instead to the retina.",
        keyFeature: { topic: "eye", n: 2 },
        source: "bsr-gca",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update:
          "She reports 3 weeks of left temple headache, pain when chewing, stiff shoulders and a 4 kg weight loss. Last week her left vision greyed out twice for a minute. There is a left relative afferent pupillary defect. The left optic disc is pale and swollen. The left temporal artery is tender with a weak pulse.",
        prompt: "What blood tests support your diagnosis?",
        accept: [
          k("esr", "Erythrocyte sedimentation rate", "esr", "sedimentation"),
          k("crp", "C reactive protein", "crp", "c reactive"),
          k("plt", "CBC for thrombocytosis and anemia", "cbc", "platelet", "complete blood count", "thrombocytosis"),
        ],
        explanation:
          "ESR and CRP are raised in most patients and together are more sensitive than either alone. Thrombocytosis adds to the probability. Normal values lower but do not exclude the diagnosis when the clinical picture is strong.",
        keyFeature: { topic: "headache", n: 4 },
        source: "bsr-gca",
      },
      {
        id: "q3",
        kind: "short",
        required: 1,
        prompt: "What corticosteroid do you start now, including the drug, dose and route?",
        accept: [
          k("ivmp", "Methylprednisolone 500 to 1000 mg IV daily for 3 days", "methylprednisolone 1000 mg", "methylprednisolone 1 g", "methylprednisolone 500 mg", "methylprednisolone 1g", "methylprednisolone 1000mg", "methylprednisolone 500mg", "solumedrol 1 g", "solumedrol 1g", "solumedrol 1000 mg", "solumedrol 500 mg"),
          k("pred", "Prednisone 1 mg/kg PO daily up to 60 mg", "prednisone 60 mg", "prednisone 60mg", "prednisone 1 mg/kg"),
        ],
        unacceptable: [
          harm("Hold steroids until the biopsy is done", "await biopsy", "wait for biopsy", "until biopsy", "delay steroid", "defer steroid", "steroid after biopsy result"),
          no("Low dose prednisone", "prednisone 20", "prednisone 10", "prednisone 15"),
        ],
        explanation:
          "With visual loss, IV pulse methylprednisolone is favoured by many guidelines, and oral prednisone 60 mg is an accepted alternative. The goal is to protect the other eye, which can be lost within days. Biopsy remains diagnostic for 1 to 2 weeks after starting steroids, so never delay treatment for it.",
        keyFeature: { topic: "eye", n: 2 },
        source: "acr-gca",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What arrangements would you make before she leaves the emergency department?",
        accept: [
          k("biopsy", "Temporal artery biopsy or vascular ultrasound within 1 to 2 weeks", "biopsy", "ultrasound"),
          k("ophtho", "Urgent ophthalmology assessment", "ophthalmology", "ophthalmologist"),
          k("rheum", "Rheumatology referral", "rheumatology", "rheumatologist"),
          k("admit", "Admission for IV steroids", "admit", "admission"),
          k("gi", "Gastric protection such as a PPI", "ppi", "proton pump", "pantoprazole", "gastric protection"),
          k("bone", "Bone protection with calcium, vitamin D and a bisphosphonate", "bone", "calcium", "vitamin d", "bisphosphonate"),
          k("glucose", "Glucose and blood pressure monitoring on steroids", "glucose", "sugar"),
        ],
        explanation:
          "Tissue or imaging confirmation is needed for a long steroid course and should happen within about two weeks. Specialist follow up guides tapering and steroid sparing therapy. High dose steroids in an older adult need gastric, bone and glucose protection.",
        keyFeature: { topic: "eye", n: 2 },
        source: "bsr-gca",
      },
    ],
    sources: [S.bsrGca, S.acrGca],
    ...META,
  },
  {
    id: "eye-08",
    topic: "eye",
    alsoTopics: ["cva"],
    title: "Sudden painless loss of vision while reading",
    stem:
      "A 68-year-old man lost the vision in his right eye suddenly 80 minutes ago while reading the newspaper. There is no pain. He has hypertension, type 2 diabetes and smokes. His pulse is irregularly irregular. Visual acuity is light perception in the right eye and 20/25 in the left. There is a right relative afferent pupillary defect. The right retina looks pale with a cherry red spot at the macula.",
    vitals: { temperature: "36.7°C", pulse: "88/minute irregular", resp: "16/minute", bp: "178/96 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step in his management?",
        options: [
          "Anterior chamber paracentesis in the emergency department",
          "Ocular massage and discharge for review tomorrow",
          "Oral acetazolamide and discharge home",
          "Outpatient MRI of the orbits",
          "Urgent stroke team assessment and vascular imaging",
        ],
        correct: 4,
        explanation:
          "Central retinal artery occlusion is an ocular stroke. It carries a high early risk of cerebral stroke and shares the same causes. Current guidance treats it through the stroke pathway for rapid assessment and workup. Some centres consider thrombolysis within 4.5 hours, but randomized trials have not shown clear benefit. Ocular massage and paracentesis have no proven benefit.",
        keyFeature: { topic: "cva", n: 3 },
        source: "aha-crao",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What investigations should be done promptly?",
        accept: [
          k("cta", "CT angiogram of head and neck", "ct angiogram", "cta", "carotid", "angiography"),
          k("ct", "Noncontrast CT head", "ct head", "noncontrast ct"),
          k("ecg", "ECG and cardiac monitoring for atrial fibrillation", "ecg", "ekg", "monitor", "telemetry"),
          k("esr", "ESR and CRP to exclude giant cell arteritis", "esr", "crp", "sedimentation"),
          k("glucose", "Glucose", "glucose"),
          k("cbc", "CBC and coagulation studies", "cbc", "inr", "coagulation", "ptt"),
          k("echo", "Echocardiogram", "echocardiogram", "echo", "tte"),
          k("lipids", "Lipids and HbA1c", "lipid", "a1c"),
        ],
        explanation:
          "The workup mirrors ischemic stroke. Carotid disease and atrial fibrillation are the commonest embolic sources, and this patient has an irregular pulse. ESR and CRP are essential in anyone over 50 because arteritic occlusion needs steroids, not thrombolysis.",
        keyFeature: { topic: "cva", n: 3 },
        source: "csbpr",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What symptoms must you ask about to exclude an arteritic cause?",
        accept: [
          k("ha", "New headache", "headache"),
          k("jaw", "Jaw claudication", "jaw", "claudication"),
          k("scalp", "Scalp tenderness", "scalp"),
          k("pmr", "Shoulder or hip girdle pain and stiffness", "shoulder", "hip", "polymyalgia", "pmr"),
          k("const", "Fever, weight loss or night sweats", "fever", "weight loss", "night sweat", "constitutional"),
        ],
        explanation:
          "About one in twenty central retinal artery occlusions is caused by giant cell arteritis. Missing it exposes the other eye to rapid loss. A focused history plus ESR and CRP is the minimum screen.",
        keyFeature: { topic: "eye", n: 2 },
        source: "aao-rao",
      },
    ],
    sources: [S.ahaCrao, S.csbpr, S.aaoRao],
    ...META,
  },
  {
    id: "eye-09",
    topic: "eye",
    title: "Flashing lights and a shadow",
    stem:
      "A 57-year-old man has had flashing lights and many new floaters in his right eye for 2 days. Today a dark shadow is spreading up from the bottom of his vision in that eye. He has no pain. He is very nearsighted and had cataract surgery in the right eye one year ago. Vital signs are normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What features of his history raise the risk of his likely diagnosis?",
        accept: [
          k("myopia", "High myopia", "myopia", "nearsighted", "myopic"),
          k("cataract", "Previous cataract surgery", "cataract"),
          k("age", "Age over 50", "age", "older"),
          k("trauma", "Previous eye trauma", "trauma"),
          k("family", "Family history of retinal detachment", "family"),
        ],
        explanation:
          "Myopia and prior cataract surgery are the strongest common risk factors for rhegmatogenous retinal detachment. Age related vitreous detachment causes the flashes and floaters. The spreading shadow means the retina itself is detaching.",
        keyFeature: { topic: "eye", n: 2 },
        source: "aao-pvd",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What parts of the eye examination would you document?",
        accept: [
          VA,
          k("fields", "Confrontation visual fields", "visual field", "confrontation", "field"),
          k("rapd", "Pupils for a relative afferent pupillary defect", "rapd", "afferent", "pupil"),
          k("iop", "Intraocular pressure", "intraocular pressure", "iop", "tonometry"),
          k("shafer", "Pigment in the anterior vitreous on slit lamp", "pigment", "tobacco dust", "shafer", "vitreou"),
          k("fundus", "Fundoscopy or ocular ultrasound", "fundoscopy", "fundus", "ultrasound", "pocus", "ophthalmoscopy"),
        ],
        explanation:
          "Acuity tells you whether central vision, and so the macula, is still working. Field testing maps the detachment. Pigment cells in the anterior vitreous suggest a retinal tear. Bedside ultrasound is useful when the fundus cannot be seen well.",
        keyFeature: { topic: "eye", n: 3 },
        source: "aao-pvd",
      },
      {
        id: "q3",
        kind: "single",
        update: "Right acuity is 20/25. There is an inferior field defect in the right eye. Point of care ocular ultrasound shows a bright undulating membrane in the posterior globe.",
        prompt: "Which of the following ultrasound features best distinguishes retinal detachment from posterior vitreous detachment?",
        options: [
          "Diffuse low level echoes fill the vitreous",
          "The membrane is thin and faint at low gain",
          "The membrane moves with eye movement",
          "The membrane remains tethered to the optic disc",
          "The optic nerve sheath is wider than 5 mm",
        ],
        correct: 3,
        explanation:
          "The retina is anchored at the optic disc, so a detached retina stays tethered there. A vitreous detachment is thinner, usually does not insert at the disc and swings more freely. Diffuse low echoes suggest vitreous hemorrhage.",
        keyFeature: { topic: "eye", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following dispositions is most appropriate for this patient?",
        options: [
          "CT head and neurology consult",
          "Discharge with advice to return if vision worsens",
          "Routine ophthalmology referral within 2 weeks",
          "Same day assessment only if acuity falls below 20/200",
          "Same day ophthalmology or retina assessment",
        ],
        correct: 4,
        explanation:
          "Good acuity suggests the macula is still attached. Urgent repair can preserve central vision, so this is the most time sensitive form of detachment. Once the macula detaches, the visual outcome is worse regardless of how fast surgery follows.",
        keyFeature: { topic: "eye", n: 3 },
        source: "aao-pvd",
      },
    ],
    sources: [S.aaoPvd, S.tintinalli],
    ...META,
  },
  {
    id: "eye-10",
    topic: "eye",
    title: "Teen struck in the eye at hockey",
    stem:
      "A 15-year-old boy was hit in the left eye by a hockey puck 2 hours ago. His helmet had no visor. He has left eye pain and blurred vision. His father, who brought him, has sickle cell trait. There is moderate left periorbital swelling and a lateral subconjunctival hemorrhage. The triage nurse has labelled this a bruised eye.",
    vitals: { temperature: "36.8°C", pulse: "90/minute", resp: "16/minute", bp: "124/72 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What assessments would you perform before accepting the triage label?",
        accept: [
          VA,
          k("hyphema", "Slit lamp for hyphema or microhyphema", "hyphema", "microhyphema", "slit lamp", "red cell"),
          k("pupil", "Pupil shape and reactivity", "pupil"),
          k("seidel", "Seidel test for an open globe", "seidel", "open globe", "rupture"),
          k("iop", "Intraocular pressure once an open globe is excluded", "intraocular pressure", "iop"),
          k("eom", "Extraocular movements and diplopia for orbital floor fracture", "extraocular", "eom", "diplopia", "entrapment", "upgaze"),
          k("sensation", "Infraorbital sensation", "infraorbital", "cheek numbness", "sensation"),
          k("fundus", "Fundoscopy for retinal injury", "fundus", "fundoscopy", "retina"),
        ],
        explanation:
          "A subconjunctival hemorrhage after blunt trauma is a marker of force. Every such eye needs acuity and a slit lamp look for hyphema, because suspended red cells are invisible to the naked eye. Open globe, orbital fracture and retinal injury must also be excluded.",
        keyFeature: { topic: "eye", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "Left acuity is 20/40. Slit lamp shows red cells suspended in the anterior chamber without a layered clot. Seidel test is negative. IOP is 26 mmHg. Eye movements are full.",
        prompt: "What are the parts of your management?",
        accept: [
          k("hob", "Elevate the head of the bed 30 to 45 degrees", "elevate", "head of bed", "head up", "upright"),
          k("shield", "Rigid eye shield", "shield"),
          k("avoidnsaid", "Avoid NSAIDs and antiplatelet drugs", "avoid nsaid", "no nsaid", "avoid ibuprofen", "avoid aspirin", "avoid asa", "no asa", "no aspirin", "avoid antiplatelet", "no ibuprofen", "avoid anti inflammatory", "not nsaid", "avoid ketorolac", "no ketorolac"),
          k("acet", "Acetaminophen for pain", "acetaminophen", "tylenol"),
          k("antiemetic", "Antiemetic if nauseated", "antiemetic", "ondansetron"),
          k("ophtho", "Ophthalmology assessment within 24 hours", "ophthalmology", "ophthalmologist"),
          k("rest", "Rest and no sports until cleared", "rest", "no sport", "activity"),
          k("cyclo", "Cycloplegic as directed by ophthalmology", "cycloplegic", "cyclopentolate", "atropine"),
        ],
        unacceptable: [
          no("NSAID for pain", "give ketorolac", "ketorolac 10", "ketorolac 15", "ketorolac 30", "naproxen 250", "naproxen 500", "ibuprofen 400", "ibuprofen 600", "give nsaid", "give ibuprofen", "give naproxen"),
          no("Pressure patch", "pressure patch"),
        ],
        explanation:
          "Management aims to limit rebleeding and pressure spikes. Head elevation lets cells settle, a shield protects the eye and NSAIDs are avoided. Ophthalmology should see him within a day and follow him closely over the first 5 days when rebleeding peaks.",
        keyFeature: { topic: "eye", n: 5 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "His sickle status is unknown. How would a positive sickle screen change management?",
        accept: [
          k("iop", "Higher risk of IOP elevation and optic nerve damage at lower pressures", "optic nerve", "lower pressure", "higher iop", "pressure spike", "iop"),
          k("cai", "Avoid carbonic anhydrase inhibitors such as acetazolamide", "avoid acetazolamide", "no acetazolamide", "not acetazolamide", "acetazolamide contraindicated", "avoid carbonic anhydrase", "no carbonic anhydrase", "carbonic anhydrase contraindicated", "avoid cai", "no cai"),
          k("osmotic", "Avoid hyperosmotic agents such as mannitol", "avoid mannitol", "no mannitol", "not mannitol", "mannitol contraindicated", "avoid hyperosmotic", "avoid osmotic", "no osmotic", "no hyperosmotic", "osmotic contraindicated"),
          k("surgery", "Lower threshold for surgical anterior chamber washout", "washout", "surgical", "surgery"),
          k("closer", "Closer ophthalmology follow up", "closer", "more frequent", "admit"),
        ],
        explanation:
          "Sickled cells block the trabecular meshwork and the optic nerve tolerates pressure poorly in sickle disease or trait. Acetazolamide and osmotic agents promote sickling. Every Black patient or patient with a family history of sickle disease with a hyphema should be screened.",
        keyFeature: { topic: "eye", n: 5 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What symptoms should prompt his return to the emergency department?",
        accept: [
          k("vision", "Worsening vision", "vision", "blurry", "blurred"),
          k("pain", "Increasing eye pain", "pain"),
          k("vomit", "Nausea or vomiting", "nausea", "vomit"),
          k("ha", "Headache", "headache"),
          k("blood", "More blood visible in the eye", "more blood", "blood"),
        ],
        explanation:
          "Rebleeding and pressure rise present with new pain, nausea, headache or falling vision. These can occur 2 to 5 days after injury, often after the patient feels better.",
        keyFeature: { topic: "eye", n: 5 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.rosen],
    ...META,
  },
  {
    id: "eye-11",
    topic: "eye",
    alsoTopics: ["multiple-trauma"],
    title: "Anticoagulated woman after a fall",
    stem:
      "An 82-year-old woman fell in her kitchen one hour ago and struck her left orbit on the counter. She takes apixaban 5 mg twice daily for atrial fibrillation. Her last dose was this morning. She has severe left eye pain and nausea. Her oxygen saturation is 96% and her GCS is 15. The left lids are tense and swollen. The left globe is proptotic with diffuse subconjunctival hemorrhage and restricted movement in all directions. Left visual acuity is hand motion. Right is 20/40. There is a left relative afferent pupillary defect. Left IOP is 54 mmHg.",
    vitals: { pulse: "94/minute irregular", resp: "18/minute", bp: "158/84 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step for her left eye?",
        options: [
          "Consult ophthalmology and await their arrival first",
          "CT orbits, then decide on treatment",
          "Lateral canthotomy and inferior cantholysis now",
          "Mannitol IV and reassess in one hour",
          "Timolol drops as the only treatment",
        ],
        correct: 2,
        explanation:
          "Orbital compartment syndrome can cause permanent vision loss within about 90 minutes. Reduced acuity, an afferent defect and very high IOP after trauma are indications to decompress at the bedside. Imaging and specialist arrival must not delay it. Medical therapy is only an adjunct.",
        keyFeature: { topic: "eye", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What findings in this patient are indications for the procedure?",
        accept: [
          k("va", "Decreased visual acuity", "acuity", "hand motion", "vision"),
          k("rapd", "Relative afferent pupillary defect", "rapd", "afferent"),
          k("iop", "IOP above 40 mmHg", "iop", "intraocular pressure", "pressure 54", "54"),
          k("proptosis", "Proptosis", "proptosis", "proptotic"),
          k("eom", "Restricted eye movements", "restricted", "ophthalmoplegia", "eye movement", "eom"),
          k("tense", "Tense lids or a rock hard globe", "tense", "rock hard", "hard globe"),
        ],
        explanation:
          "The diagnosis is clinical. Loss of acuity, an afferent defect, proptosis with tense lids and IOP over 40 mmHg define the need to decompress. Measured acuity and IOP document the indication and the response.",
        keyFeature: { topic: "eye", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What steps would you take to manage her anticoagulation?",
        accept: [
          k("pcc", "Prothrombin complex concentrate, for example 50 units/kg or a fixed 2000 units", "pcc", "prothrombin complex", "octaplex", "beriplex"),
          k("andexanet", "Andexanet alfa where available", "andexanet"),
          k("hold", "Hold apixaban", "hold apixaban", "stop apixaban", "hold anticoagulant", "stop anticoagulant", "discontinue apixaban", "withhold apixaban", "hold doac", "stop doac", "hold eliquis", "stop eliquis"),
          k("level", "Confirm last dose timing or anti Xa level", "anti xa", "last dose", "xa level"),
          k("ct", "CT head for intracranial hemorrhage", "ct head", "intracranial"),
        ],
        unacceptable: [no("Vitamin K alone", "vitamin k"), no("Protamine", "protamine")],
        explanation:
          "A vision threatening bleed on a factor Xa inhibitor warrants reversal. Prothrombin complex concentrate is widely used in Canada, and andexanet is an option where available. Vitamin K and protamine do not reverse apixaban. An anticoagulated older adult with head trauma also needs CT head.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "After decompression the left IOP is 28 mmHg and acuity is counting fingers.",
        prompt: "Given the subconjunctival hemorrhage, what other ocular injuries would you look for on slit lamp and fundus examination?",
        accept: [
          k("hyphema", "Hyphema", "hyphema"),
          k("globe", "Open globe injury", "open globe", "rupture", "seidel", "laceration"),
          k("lens", "Lens dislocation", "lens"),
          k("iris", "Traumatic iritis or iris injury", "iritis", "iris", "iridodialysis"),
          k("abrasion", "Corneal abrasion", "abrasion"),
          k("retina", "Retinal detachment or commotio retinae", "retinal", "commotio", "vitreous hemorrhage"),
        ],
        explanation:
          "Traumatic subconjunctival hemorrhage should always prompt a search for hyphema, including a microhyphema seen only on slit lamp. Blunt force severe enough to cause orbital hemorrhage can also rupture the globe or injure the lens and retina.",
        keyFeature: { topic: "eye", n: 5 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.rosen],
    ...META,
  },
  {
    id: "eye-12",
    topic: "eye",
    title: "Splash at work",
    stem:
      "A 31-year-old man arrives 10 minutes after a commercial drain cleaner splashed into his right eye at work. He rinsed it briefly at a sink. He is in severe pain and cannot open the eye. The triage nurse wants to check his visual acuity before anything else.",
    vitals: { pulse: "104/minute", resp: "20/minute", bp: "138/86 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate first action for this patient?",
        options: [
          "Check the tear pH and await the result before irrigating",
          "Complete a slit lamp examination first",
          "Instil topical anaesthetic and irrigate copiously now",
          "Measure visual acuity before any treatment",
          "Neutralize the eye with a dilute acid solution",
        ],
        correct: 2,
        explanation:
          "Chemical injury is the one eye emergency where treatment comes before acuity. Alkali penetrates within minutes. Irrigate first and measure acuity afterwards. Neutralizing agents cause further heat and injury.",
        keyFeature: { topic: "eye", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What are the key details of how you will irrigate and when you will stop?",
        accept: [
          k("volume", "At least 1 to 2 litres per eye", "litre", "liter", "2 l", "1 l", "volume"),
          k("fluid", "Normal saline, Ringer lactate or tap water if nothing else", "saline", "ringer", "lactate", "tap water"),
          k("morgan", "Morgan lens or irrigation through IV tubing with lids retracted", "morgan", "tubing", "lid retractor", "speculum"),
          k("ph", "Continue until pH is 7.0 to 7.5", "ph"),
          k("wait", "Recheck pH 5 to 10 minutes after pausing", "recheck", "wait", "pause", "repeat ph"),
          k("fornix", "Evert the lids and sweep the fornices for particles", "fornice", "fornix", "evert", "particle", "sweep"),
        ],
        explanation:
          "Irrigate with large volumes using a Morgan lens or tubing. Check pH after a pause so that alkali leaching from tissue is not missed. Particles trapped in the fornices keep releasing chemical and must be removed.",
        keyFeature: { topic: "eye", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "After 4 litres the pH is stable at 7.2. Right acuity is 20/70. Slit lamp shows a large epithelial defect and white blanching of the limbus over 3 clock hours.",
        prompt: "What history details about the exposure would you now obtain?",
        accept: [
          k("agent", "The exact product and chemical, with the safety data sheet", "product", "chemical", "safety data", "sds", "msds", "agent"),
          k("conc", "Concentration of the chemical", "concentration"),
          k("time", "Time and duration of exposure before irrigation", "time", "duration"),
          k("firstaid", "First aid given at the scene", "first aid", "rinse", "rinsed"),
          k("other", "Other exposures such as skin, inhalation or ingestion", "skin", "inhalation", "ingestion", "other exposure"),
          k("lens", "Contact lens wear", "contact lens", "contact lenses"),
          k("ppe", "Eye protection worn", "protection", "goggle", "ppe"),
        ],
        explanation:
          "The agent, concentration and contact time predict severity. Drain cleaners often contain sodium hydroxide, a strong alkali. Other exposures and workplace details matter for complete care and for workers compensation reporting.",
        keyFeature: { topic: "eye", n: 2 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What further management steps would you take?",
        accept: [
          k("ophtho", "Same day ophthalmology assessment because limbal ischemia predicts a poor outcome", "ophthalmology", "ophthalmologist"),
          k("abx", "Topical antibiotic such as erythromycin ointment", "antibiotic", "erythromycin", "moxifloxacin"),
          k("cyclo", "Cycloplegic for pain", "cycloplegic", "cyclopentolate"),
          k("analgesia", "Oral analgesia", "analgesia", "acetaminophen", "opioid", "hydromorphone", "morphine"),
          k("tetanus", "Tetanus update if due", "tetanus"),
          k("iop", "Check IOP", "iop", "intraocular pressure"),
        ],
        unacceptable: [no("Topical anaesthetic for home use", "anaesthetic home", "anesthetic home", "tetracaine home", "proparacaine home")],
        explanation:
          "Limbal blanching signals stem cell ischemia and a risk of chronic surface failure. Ophthalmology should see him the same day. Supportive care includes antibiotic cover, cycloplegia and adequate oral analgesia.",
        keyFeature: { topic: "eye", n: 3 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.rosen],
    ...META,
  },
  {
    id: "eye-13",
    topic: "eye",
    title: "Something flew into the eye in the workshop",
    stem:
      "A 44-year-old man was striking a steel chisel with a hammer in his garage 3 hours ago when he felt something hit his left eye. He has mild pain and blurry vision. He was not wearing safety glasses. His last tetanus shot was over 10 years ago. Vital signs are normal. There is a small inferotemporal subconjunctival hemorrhage in the left eye.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What parts of the history affect your risk assessment?",
        accept: [
          k("mech", "Metal on metal, high velocity mechanism", "metal on metal", "high velocity", "hammer", "chisel", "mechanism"),
          k("protection", "Eye protection worn or not", "protection", "safety glass", "safety glasses", "goggle", "goggles"),
          k("vision", "Change in vision", "vision"),
          k("tetanus", "Tetanus immunization status", "tetanus"),
          k("time", "Time since injury", "time since", "timing"),
          k("surgery", "Prior eye surgery", "prior eye", "eye surgery"),
          k("food", "Last oral intake in case of surgery", "last meal", "npo", "oral intake", "ate"),
        ],
        explanation:
          "Hammering metal on metal can launch tiny high speed fragments that penetrate the globe with little pain. The mechanism alone should prompt a search for an intraocular foreign body. Tetanus status and last meal matter if surgery follows.",
        keyFeature: { topic: "eye", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What examination findings would suggest an open globe?",
        accept: [
          k("pupil", "Peaked or teardrop pupil", "peaked", "teardrop", "tear drop", "irregular pupil"),
          k("seidel", "Positive Seidel test", "seidel"),
          k("ac", "Abnormal anterior chamber depth", "anterior chamber", "shallow", "deep chamber"),
          k("hyphema", "Hyphema", "hyphema"),
          k("va", "Reduced visual acuity", "acuity", "reduced vision"),
          k("uvea", "Prolapsed uveal tissue", "uveal", "prolapse", "extrusion"),
          k("sch", "Extensive or bullous subconjunctival hemorrhage", "bullous", "360", "extensive"),
          k("lac", "Visible corneal or scleral laceration", "laceration", "wound"),
        ],
        unacceptable: [
          harm("Measure intraocular pressure by tonometry", "perform tonometry", "do tonometry", "measure iop", "check iop", "measure intraocular pressure", "check intraocular pressure"),
          no("Tonometry", "tonometry", "tonopen", "tono pen"),
        ],
        explanation:
          "A subconjunctival hemorrhage after trauma must prompt a slit lamp search for hyphema and penetration. A teardrop pupil points toward the wound. Tonometry puts pressure on the globe and is avoided when an open globe is suspected.",
        keyFeature: { topic: "eye", n: 5 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "Left acuity is 20/60. There is a 1 mm full thickness corneal laceration with a positive Seidel test, a teardrop pupil and a microhyphema.",
        prompt: "Which of the following imaging studies is most appropriate for this patient?",
        options: [
          "MRI orbits without contrast",
          "Noncontrast CT orbits with thin cuts",
          "Ocular ultrasound with firm probe pressure",
          "Plain orbital X rays alone",
          "No imaging is needed",
        ],
        correct: 1,
        explanation:
          "Thin cut CT finds and localizes metallic foreign bodies. MRI is contraindicated when a metal fragment is possible. Ultrasound with pressure on an open globe risks extrusion of contents.",
        keyFeature: { topic: "eye", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What further management steps would you take?",
        accept: [
          k("shield", "Rigid shield without pressure", "shield"),
          k("abx", "IV antibiotics such as vancomycin with ceftazidime, or a fluoroquinolone", "antibiotic", "vancomycin", "ceftazidime", "moxifloxacin", "levofloxacin"),
          k("tetanus", "Tetanus booster", "tetanus", "tdap"),
          k("antiemetic", "Antiemetic to prevent vomiting", "antiemetic", "ondansetron"),
          k("analgesia", "IV analgesia", "analgesia", "morphine", "hydromorphone", "fentanyl"),
          k("npo", "Keep NPO", "npo", "nil by mouth", "fasting"),
          k("ophtho", "Emergent ophthalmology consult", "ophthalmology", "ophthalmologist"),
          k("hob", "Elevate the head of the bed", "elevate", "head of bed"),
        ],
        unacceptable: [
          harm("Pressure patch", "apply pressure patch", "apply a pressure patch", "place pressure patch", "place a pressure patch"),
          harm("Remove the foreign body in the emergency department", "remove foreign body in the emergency", "remove foreign body in ed", "remove foreign body at bedside", "remove foreign body at the bedside", "remove foreign body slit lamp", "remove foreign body with needle"),
          no("Pressure patch or foreign body removal", "pressure patch", "remove the foreign body", "remove foreign body"),
        ],
        explanation:
          "Protect the globe with a rigid shield and prevent vomiting and straining. Give systemic antibiotics to reduce endophthalmitis risk and update tetanus. Removal of an intraocular fragment belongs in the operating room.",
        keyFeature: { topic: "eye", n: 1 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli, S.rosen],
    ...META,
  },
  {
    id: "eye-14",
    topic: "eye",
    alsoTopics: ["infectious-diseases"],
    title: "Child with a swollen eyelid and fever",
    stem:
      "A 7-year-old boy has had 5 days of cold symptoms and 2 days of increasing left eyelid swelling and redness. His family physician called it conjunctivitis with lid swelling and started antibiotic drops yesterday. Today he has a fever and a headache. Both left eyelids are swollen and red, and the conjunctiva is swollen.",
    vitals: { temperature: "39.1°C", pulse: "128/minute", resp: "22/minute", bp: "102/64 mmHg", o2sat: "98% on room air", weight: "24 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What findings would suggest orbital rather than preseptal infection?",
        accept: [
          k("proptosis", "Proptosis", "proptosis", "proptotic", "bulging"),
          k("paineom", "Pain with eye movement", "pain with eye movement", "pain on eye movement", "painful eye movement", "pain with movement"),
          k("restricted", "Restricted eye movements or diplopia", "restricted", "ophthalmoplegia", "diplopia", "double vision"),
          k("va", "Reduced visual acuity", "acuity", "reduced vision"),
          k("rapd", "Relative afferent pupillary defect", "rapd", "afferent"),
          k("chemosis", "Marked chemosis", "chemosis"),
        ],
        explanation:
          "Proptosis, painful or restricted movement, reduced acuity and an afferent defect mean infection behind the septum. Lid swelling alone does not. A swollen lid with fever should never be dismissed as conjunctivitis.",
        keyFeature: { topic: "eye", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        update: "He has mild proptosis and pain on upgaze. Acuity with a picture chart is 20/40 in the left eye and 20/25 in the right. There is no afferent defect.",
        prompt: "Which of the following imaging studies is most appropriate for this child?",
        options: [
          "CT orbits and sinuses with IV contrast",
          "Noncontrast CT of the head",
          "Outpatient MRI of the brain",
          "Plain X rays of the sinuses",
          "No imaging, treat and reassess",
        ],
        correct: 0,
        explanation:
          "Contrast CT confirms orbital involvement and looks for a subperiosteal abscess that may need drainage. MRI is an alternative where rapidly available. Plain films add nothing.",
        keyFeature: { topic: "eye", n: 3 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What are the parts of your treatment plan?",
        accept: [
          k("ceftriaxone", "IV ceftriaxone", "ceftriaxone", "cefotaxime"),
          k("vanco", "IV vancomycin when severe or MRSA is a concern", "vancomycin", "mrsa"),
          k("metro", "Metronidazole if intracranial extension is suspected", "metronidazole"),
          k("ophtho", "Ophthalmology consult", "ophthalmology", "ophthalmologist"),
          k("ent", "ENT consult", "ent", "otolaryngology"),
          k("admit", "Admit for IV therapy and serial eye checks", "admit", "admission"),
          k("antipyretic", "Antipyretic and analgesia", "acetaminophen", "antipyretic", "analgesia", "ibuprofen"),
        ],
        unacceptable: [no("Oral antibiotics and discharge", "oral antibiotic"), no("Continue drops alone", "drops alone")],
        explanation:
          "Orbital cellulitis in a child needs admission, IV antibiotics covering sinus pathogens and joint ophthalmology and ENT care. Vancomycin is added for severe disease or MRSA risk. Serial acuity checks detect optic nerve compromise early.",
        keyFeature: { topic: "infectious-diseases", n: 8 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What complications would you monitor for?",
        accept: [
          k("abscess", "Subperiosteal or orbital abscess", "abscess"),
          k("cst", "Cavernous sinus thrombosis", "cavernous"),
          k("mening", "Meningitis", "meningitis"),
          k("brain", "Intracranial abscess or empyema", "intracranial", "empyema", "brain"),
          k("vision", "Optic neuropathy and vision loss", "optic", "vision loss", "blindness"),
        ],
        explanation:
          "Infection can spread along valveless orbital veins to the cavernous sinus and meninges. A new headache, bilateral signs or altered mental status warrant urgent repeat imaging.",
        keyFeature: { topic: "infectious-diseases", n: 4 },
        source: "tintinalli",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },
  {
    id: "eye-15",
    topic: "eye",
    title: "Red eye a few days after a procedure",
    stem:
      "A 79-year-old woman has increasing ache and redness in her right eye since yesterday. Her vision in that eye is much worse. Her family physician suspected pink eye on the phone and suggested she come in for drops. Visual acuity is hand motion in the right eye and 20/40 in the left.",
    vitals: { temperature: "37.3°C", pulse: "86/minute", bp: "148/78 mmHg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What history questions could change your diagnosis?",
        accept: [
          k("surgery", "Recent eye surgery such as cataract surgery", "surgery", "cataract", "operation"),
          k("injection", "Recent intravitreal injection", "injection", "intravitreal"),
          k("trauma", "Recent eye trauma", "trauma", "injury"),
          k("drops", "Current eye drops and adherence", "drop", "adherence"),
          k("immuno", "Diabetes or immunosuppression", "diabetes", "immunosuppression", "immunocompromised"),
          k("bacteremia", "Recent bacteremia, IV drug use or indwelling line", "bacteremia", "drug use", "line", "endocarditis"),
        ],
        explanation:
          "Pain and marked vision loss in a red eye are never pink eye. Recent surgery, an injection or trauma point to endophthalmitis. Endogenous cases arise from bacteremia.",
        keyFeature: { topic: "eye", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "She had cataract surgery in the right eye 4 days ago. The right lid is swollen. There is diffuse injection, a hazy cornea and a 2 mm layered hypopyon.",
        prompt: "What findings in this case exclude conjunctivitis?",
        accept: [
          k("hypopyon", "Hypopyon", "hypopyon"),
          k("va", "Severely reduced visual acuity", "acuity", "hand motion", "vision"),
          k("pain", "Eye pain", "pain", "ache"),
          k("surgery", "Recent intraocular surgery", "surgery", "cataract"),
          k("cornea", "Corneal haze", "cornea", "haze"),
          k("ac", "Anterior chamber inflammation", "anterior chamber", "cells", "flare"),
        ],
        explanation:
          "Conjunctivitis spares acuity and the anterior chamber. A hypopyon with profound vision loss days after cataract surgery is acute postoperative endophthalmitis until proven otherwise.",
        keyFeature: { topic: "eye", n: 1 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step for this patient?",
        options: [
          "Admit to internal medicine for IV antibiotics alone",
          "CT of the orbits with IV contrast",
          "Emergent ophthalmology for tap and intravitreal antibiotics",
          "Hourly moxifloxacin drops with ophthalmology review tomorrow",
          "Topical prednisolone acetate every hour",
        ],
        correct: 2,
        explanation:
          "Vision outcome depends on rapid intravitreal antibiotics after a vitreous sample. Topical drops do not reach therapeutic levels in the vitreous. IV antibiotics alone are inadequate for postoperative endophthalmitis.",
        keyFeature: { topic: "eye", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What other procedures or events can precede this condition?",
        accept: [
          k("antivegf", "Intravitreal injection such as anti VEGF therapy", "intravitreal", "anti vegf", "injection"),
          k("glaucoma", "Glaucoma surgery with a filtering bleb", "glaucoma", "bleb", "trabeculectomy"),
          k("trauma", "Penetrating eye trauma", "penetrating", "trauma", "open globe"),
          k("graft", "Corneal transplant", "corneal transplant", "keratoplasty", "graft"),
          k("endogenous", "Bacteremia or fungemia, for example with IV drug use", "bacteremia", "fungemia", "drug use", "endocarditis", "candida"),
          k("vitrectomy", "Vitrectomy or retinal surgery", "vitrectomy", "retinal surgery"),
        ],
        explanation:
          "Any breach of the globe can seed the eye. Intravitreal injections are now a common cause. Endogenous endophthalmitis should prompt a search for bacteremia or fungemia.",
        keyFeature: { topic: "eye", n: 1 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },
];
