// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: true, author: "Draft for review by Arjan Dhoot, MD", version: 1 } as const;

const S = {
  atls: { id: "atls", citation: "American College of Surgeons Committee on Trauma. Advanced Trauma Life Support (ATLS) Student Course Manual. 11th edition. Chicago: American College of Surgeons. 2025.", url: "https://www.facs.org/quality-programs/trauma/education/advanced-trauma-life-support/atls-11/" },
  crash2: { id: "crash2", citation: "CRASH-2 trial collaborators. Effects of tranexamic acid on death, vascular occlusive events, and blood transfusion in trauma patients with significant haemorrhage (CRASH-2): a randomised, placebo-controlled trial. Lancet. 2010." },
  proppr: { id: "proppr", citation: "Holcomb JB, et al. Transfusion of plasma, platelets, and red blood cells in a 1:1:1 vs a 1:1:2 ratio and mortality in patients with severe trauma: the PROPPR randomized clinical trial. JAMA. 2015." },
  euro: { id: "euro-bleeding", citation: "Rossaint R, et al. The European guideline on management of major bleeding and coagulopathy following trauma. Sixth edition. Crit Care. 2023." },
  east: { id: "east-edt", citation: "Seamon MJ, et al. An evidence-based approach to patient selection for emergency department thoracotomy: a practice management guideline from the Eastern Association for the Surgery of Trauma. J Trauma Acute Care Surg. 2015." },
  sogc: { id: "sogc-trauma", citation: "Jain V, Chari R, Maslovitz S, et al. Guidelines for the management of a pregnant trauma patient. SOGC Clinical Practice Guideline No. 325. J Obstet Gynaecol Can. 2015." },
  ahaPreg: { id: "aha-pregnancy", citation: "Jeejeebhoy FM, et al. Cardiac arrest in pregnancy: a scientific statement from the American Heart Association. Circulation. 2015." },
  thrombosisCanada: { id: "thrombosis-canada", citation: "Thrombosis Canada. Clinical guide: NOACs/DOACs: management of bleeding. 2020.", url: "https://thrombosiscanada.ca/hcp/practice/clinical_guides?language=en-ca&guideID=MANAGEMENTOFBLEEDINGINPATIENTS" },
  ccr: { id: "ccr", citation: "Stiell IG, et al. The Canadian C-spine rule for radiography in alert and stable trauma patients. JAMA. 2001." },
  ccthr: { id: "ccthr", citation: "Stiell IG, et al. The Canadian CT Head Rule for patients with minor head injury. Lancet. 2001." },
  wfh: { id: "wfh", citation: "Srivastava A, et al. WFH Guidelines for the Management of Hemophilia, 3rd edition. Haemophilia. 2020." },
  hcca: { id: "hcca", citation: "Health Care Consent Act, 1996, S.O. 1996, c. 2 (Ontario)." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, Erickson TB, Wilcox SR, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. 10th ed. Elsevier. 2023. Chapters on multiple trauma, orthopaedic injuries and air medical transport." },
  cafg: { id: "cafg", citation: "Law JA, et al. Canadian Airway Focus Group updated consensus-based recommendations for management of the difficult airway. Part 1. Can J Anaesth. 2021." },
  rcpch: { id: "rcpch-txa", citation: "Royal College of Paediatrics and Child Health. Major trauma and the use of tranexamic acid in children. Evidence statement. 2012." },
  apsa: { id: "apsa", citation: "Gates RL, Price M, Cameron DB, et al. Non-operative management of solid organ injuries in children: an American Pediatric Surgical Association Outcomes and Evidence Based Practice Committee systematic review. J Pediatr Surg. 2019." },
  btf: { id: "btf", citation: "Carney N, et al. Guidelines for the management of severe traumatic brain injury, fourth edition. Neurosurgery. 2017." },
  hicks: { id: "hicks", citation: "Hicks C, Petrosoniak A. The human factor: optimizing trauma team performance in dynamic clinical environments. Emerg Med Clin North Am. 2018." },
  hypothermia: { id: "hypothermia", citation: "Brown DJA, Brugger H, Boyd J, Paal P. Accidental hypothermia. N Engl J Med. 2012." },
  mills: { id: "mills-abi", citation: "Mills WJ, Barei DP, McNair P. The value of the ankle-brachial index for diagnosing arterial injury after knee dislocation: a prospective study. J Trauma. 2004." },
  who: { id: "who-ipv", citation: "World Health Organization. Responding to intimate partner violence and sexual violence against women: WHO clinical and policy guidelines. 2013." },
} satisfies Record<string, Source>;

export const MULTIPLE_TRAUMA_SAMPS: Samp[] = [
  /* 01 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-01",
    topic: "multiple-trauma",
    title: "Motorcyclist after a highway collision",
    stem:
      "A 34-year-old man is brought in by paramedics 25 minutes after his motorcycle struck a car at highway speed. He is in a cervical collar. He is anxious and says he cannot breathe. GCS 15. His weight is estimated. Breath sounds are absent on the right and the trachea is deviated to the left. There is bruising over the perineum and the right leg is shortened and externally rotated. Your team is two nurses and a respiratory therapist.",
    vitals: { temperature: "35.4°C", pulse: "132/minute", resp: "34/minute", bp: "78/50 mmHg", o2sat: "84% on a non-rebreather mask", weight: "85 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What critical interventions do you perform during the primary survey?",
        accept: [
          { id: "decompress", text: "Decompress the right chest by finger or needle thoracostomy, then a chest tube", match: ["decompress", "decompression", "thoracostomy", "chest tube", "chest drain"] },
          { id: "binder", text: "Apply a pelvic binder centred over the greater trochanters", match: ["binder", "pelvic sheet", "bind pelvis", "binding"] },
          { id: "blood", text: "Transfuse uncrossmatched red cells and activate the massive transfusion protocol", match: ["transfuse", "transfusion", "mtp", "prbc", "packed red", "uncrossmatched", "red cell", "o negative", "o positive"] },
          { id: "spine", text: "Maintain spinal motion restriction", match: ["spinal motion", "collar", "c spine", "cervical spine", "immobilization", "immobilize", "immobilise"] },
          { id: "access", text: "Two large bore IV lines or intraosseous access", match: ["large bore", "intraosseous", "io access", "two iv"] },
          { id: "txa", text: "Tranexamic acid 1 g IV", match: ["txa", "tranexamic"] },
          { id: "warm", text: "Prevent hypothermia with warmed products and blankets", match: ["warm", "warmed", "hypothermia", "blanket"] },
        ],
        unacceptable: [
          { text: "Chest X-ray to confirm the pneumothorax before decompression", match: ["wait for cxr", "wait for x ray", "wait for chest x ray", "wait for imaging"], dangerous: true },
          { text: "Spring or rock the pelvis to test stability", match: ["spring", "rock pelvis", "rock the pelvis"] },
        ],
        explanation:
          "Hypotension, hypoxia, absent breath sounds and tracheal deviation make this a clinical tension pneumothorax. Decompress without waiting for imaging. The perineal bruising and leg position suggest an unstable pelvic fracture, so bind the pelvis and start blood early. Repeated pelvic springing can dislodge clot and adds nothing.",
        keyFeature: { topic: "multiple-trauma", n: 1 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "single",
        update:
          "After finger thoracostomy there is a rush of air. SpO2 rises to 94%. A pelvic binder is on. He has received 2 units of red cells. HR 128, BP 84/52. eFAST shows no free fluid in the abdomen and no pericardial effusion. The portable pelvis film shows an open book fracture with sacroiliac widening.",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "Laparotomy for presumed intra-abdominal bleeding",
          "Removal of the binder briefly to confirm pelvic instability",
          "Traction splint to the right leg before other steps",
          "Transfer to CT for a whole body trauma scan",
          "Transfusion and angioembolization or preperitoneal packing",
        ],
        correct: 4,
        explanation:
          "He remains in shock with a negative eFAST and an unstable pelvic fracture, so the pelvis is the likely source. Definitive haemorrhage control by angioembolization or preperitoneal packing takes priority. CT in a patient who is not responding to transfusion is unsafe. A negative eFAST argues against a laparotomy as the first move.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "What targets or end points do you use to guide ongoing blood product resuscitation?",
        accept: [
          { id: "sbp", text: "Permissive hypotension with systolic BP about 80 to 90 mmHg until bleeding is controlled", match: ["permissive", "sbp 80", "sbp 90", "systolic 80", "systolic 90", "map 50", "map 60", "map 65"] },
          { id: "ratio", text: "Balanced ratio of plasma, platelets and red cells", match: ["ratio", "balanced", "plasma"] },
          { id: "ca", text: "Ionized calcium above 1.1 mmol/L", match: ["calcium"] },
          { id: "fib", text: "Fibrinogen above 1.5 g/L", match: ["fibrinogen", "cryo", "cryoprecipitate"] },
          { id: "plt", text: "Platelets above 50 x 10^9/L (above 100 with head injury)", match: ["platelet"] },
          { id: "inr", text: "INR below 1.5", match: ["inr"] },
          { id: "temp", text: "Core temperature above 35°C", match: ["temperature", "normothermia", "hypothermia"] },
          { id: "lactate", text: "Falling lactate or base deficit", match: ["lactate", "base deficit", "base excess"] },
          { id: "vet", text: "Viscoelastic testing such as ROTEM or TEG", match: ["rotem", "teg", "viscoelastic", "thromboelastography"] },
          { id: "uo", text: "Urine output at least 0.5 mL/kg/h", match: ["urine output"] },
        ],
        unacceptable: [{ text: "Normalize blood pressure (systolic above 120 mmHg)", match: ["normalize blood pressure", "normal blood pressure", "sbp 120", "systolic 120"] }],
        explanation:
          "Damage control resuscitation targets a low normal pressure until haemorrhage is controlled, with balanced products and correction of the lethal triad. Calcium, fibrinogen, platelets and temperature are specific, measurable goals. Chasing a normal blood pressure before haemostasis increases bleeding.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "euro-bleeding",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What tasks do you delegate to run in parallel while you perform the finger thoracostomy?",
        accept: [
          { id: "binder", text: "A nurse applies the pelvic binder", match: ["binder", "pelvic sheet", "bind pelvis"] },
          { id: "blood", text: "A nurse hangs blood on a rapid infuser and activates the massive transfusion protocol", match: ["blood", "mtp", "massive transfusion", "rapid infuser", "transfuse"] },
          { id: "airway", text: "The respiratory therapist manages oxygen and prepares for airway support", match: ["airway", "oxygen", "respiratory therapist", "rt"] },
          { id: "xray", text: "Order a portable chest and pelvis X-ray", match: ["x ray", "xray", "cxr", "portable"] },
          { id: "call", text: "Call the trauma surgeon and interventional radiology", match: ["surgeon", "surgery", "interventional radiology", "call for help"] },
          { id: "access", text: "Obtain IV or intraosseous access and send blood work", match: ["iv access", "intraosseous", "io", "large bore", "bloodwork", "blood work"] },
          { id: "record", text: "Assign a recorder to document times and interventions", match: ["recorder", "scribe", "document"] },
        ],
        explanation:
          "A trauma leader who performs a procedure must still direct the room. Binding the pelvis, starting blood and ordering imaging can all happen during decompression. Clear, named tasks with closed loop confirmation keep the resuscitation moving in parallel rather than in sequence.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.euro],
    ...META,
  },

  /* 02 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-02",
    topic: "multiple-trauma",
    title: "Stab wound to the anterior chest",
    stem:
      "A 24-year-old man walks into triage holding a towel against a single stab wound at the left fourth intercostal space just lateral to the sternum. He is pale and sweaty. GCS 15. His weight is estimated. Breath sounds are equal. You are at a Level 1 trauma centre and cardiac surgery is in house.",
    vitals: { pulse: "118/minute", resp: "26/minute", bp: "104/88 mmHg", o2sat: "97% on room air", weight: "70 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        update:
          "Ten minutes later he becomes restless and tries to climb off the stretcher. HR 134, BP 90/80. His neck veins are now distended. Breath sounds remain equal and the trachea is midline.",
        prompt: "Which of the following is the most likely cause of this change?",
        options: [
          "Acute anxiety reaction",
          "Intercostal artery bleeding",
          "Massive hemothorax",
          "Pericardial tamponade",
          "Tension pneumothorax",
        ],
        correct: 3,
        explanation:
          "A precordial wound with a narrowing pulse pressure, rising heart rate, distended neck veins and new agitation points to tamponade. Equal breath sounds and a midline trachea argue against tension pneumothorax and massive hemothorax. Agitation here is a sign of falling cerebral perfusion, not anxiety.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What further bedside findings would support your diagnosis?",
        accept: [
          { id: "fast", text: "Pericardial fluid on the cardiac view of eFAST", match: ["pericardial fluid", "pericardial effusion", "efast", "fast positive", "fast pericardial", "ultrasound", "pocus", "echo"] },
          { id: "rv", text: "Right ventricular diastolic collapse on ultrasound", match: ["collapse", "rv"] },
          { id: "muffled", text: "Muffled heart sounds", match: ["muffled", "distant heart"] },
          { id: "pulsus", text: "Pulsus paradoxus", match: ["pulsus", "paradoxus"] },
          { id: "kussmaul", text: "Kussmaul sign", match: ["kussmaul"] },
          { id: "ecg", text: "Low voltage or electrical alternans on ECG", match: ["alternans", "low voltage"] },
          { id: "ivc", text: "Plethoric IVC without respiratory variation", match: ["ivc", "plethoric", "vena cava"] },
        ],
        explanation:
          "Beck triad is often incomplete in trauma. The cardiac window of eFAST is the fastest and most reliable test. Right ventricular diastolic collapse and a plethoric IVC show that the effusion is causing physiologic compromise.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "eFAST shows a pericardial effusion with right ventricular collapse. BP is 76/60. The cardiac surgeon is on the way and the operating room can be ready in 10 minutes.",
        prompt: "Which of the following actions are most appropriate for him now?",
        options: [
          "CT of the chest before surgery",
          "Furosemide 40 mg IV",
          "Immediate operating room decompression and repair",
          "Needle decompression of the left chest",
          "Norepinephrine infusion to a MAP of 65 mmHg",
          "Observe with serial eFAST every 15 minutes",
          "Rapid sequence intubation before transfer",
          "Warmed blood transfusion",
        ],
        correct: [2, 7],
        explanation:
          "Traumatic tamponade needs immediate surgical decompression and repair in the operating room. Warmed blood supports preload while the team moves. Induction and positive pressure ventilation can precipitate arrest in tamponade, so intubate in the operating room with the surgeon ready if possible. Pericardiocentesis is only a bridge and often fails with clotted blood.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "Before he reaches the operating room he loses his pulse. CPR is started. It has been under two minutes.",
        prompt: "What tasks do you delegate to others while you perform a resuscitative thoracotomy?",
        accept: [
          { id: "cpr", text: "Chest compressions until the chest is opened", match: ["compression", "cpr"] },
          { id: "airway", text: "Intubate and ventilate", match: ["intubate", "intubation", "airway", "ventilate", "bag"] },
          { id: "right", text: "Right finger thoracostomy or clamshell extension", match: ["right finger", "right thoracostomy", "right chest", "clamshell", "bilateral"] },
          { id: "blood", text: "Massive transfusion through a rapid infuser", match: ["blood", "mtp", "massive transfusion", "rapid infuser", "transfuse"] },
          { id: "tray", text: "Open the thoracotomy tray and prepare suction and lighting", match: ["tray", "suction", "instruments", "kit"] },
          { id: "call", text: "Tell the surgeon and operating room that he arrested", match: ["surgeon", "operating room"] },
          { id: "time", text: "Recorder calls out elapsed arrest time", match: ["recorder", "timekeeper", "scribe", "elapsed time", "arrest time", "keep time", "track time", "call out time"] },
        ],
        explanation:
          "Resuscitative thoracotomy is indicated for penetrating thoracic trauma with arrest and less than about 15 minutes of CPR. The procedure takes the leader's hands, so airway, compressions, blood and timekeeping must be assigned by name. Parallel work shortens time to release of tamponade.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "east-edt",
      },
    ],
    sources: [S.atls, S.east],
    ...META,
  },

  /* 03 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-03",
    topic: "multiple-trauma",
    alsoTopics: ["shock"],
    title: "Restrained driver in the third trimester",
    stem:
      "A 29-year-old woman, G2P1 at 31 weeks, was the restrained driver in a T-bone collision at 60 km/h. She has abdominal pain. GCS 15. There is a seatbelt mark across the lower abdomen. The uterine fundus is above the umbilicus and tender.",
    vitals: { pulse: "108/minute", resp: "22/minute", bp: "100/62 mmHg", o2sat: "98% on room air", weight: "78 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "In what ways does pregnancy change your primary survey and early resuscitation?",
        accept: [
          { id: "lud", text: "Manual left uterine displacement or left lateral tilt", match: ["uterine displacement", "left lateral", "tilt", "displace uterus", "wedge"] },
          { id: "o2", text: "Supplemental oxygen to keep SpO2 above 95%", match: ["oxygen", "spo2", "saturation"] },
          { id: "vol", text: "Treat early as hemorrhage because signs of shock are delayed", match: ["delayed", "hypovolemia", "hidden", "masked", "blood loss", "early blood"] },
          { id: "access", text: "Large bore IV access above the diaphragm", match: ["large bore", "above the diaphragm", "upper extremity"] },
          { id: "ob", text: "Early obstetric team involvement and fetal heart assessment", match: ["obstetric", "obstetrician", "fetal", "ob"] },
          { id: "oneg", text: "Use O negative blood if uncrossmatched blood is needed", match: ["o negative", "rh negative blood"] },
          { id: "aspiration", text: "Anticipate aspiration risk and consider gastric decompression", match: ["aspiration", "gastric"] },
          { id: "chest", text: "Place chest tubes one or two interspaces higher", match: ["interspace", "chest tube higher", "higher chest tube"] },
        ],
        unacceptable: [{ text: "Avoid CT or X-rays because of fetal radiation", match: ["avoid ct", "no ct", "avoid x ray", "avoid imaging", "avoid radiation"] }],
        explanation:
          "Aortocaval compression can cut cardiac output sharply once the uterus reaches the umbilicus, so displace it to the left. Pregnancy expands blood volume and blunts early signs of shock. Resuscitating the mother is the best treatment for the fetus. Needed imaging must not be withheld for radiation concerns.",
        keyFeature: { topic: "multiple-trauma", n: 1 },
        source: "sogc-trauma",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following statements about her vital signs is most accurate?",
        options: [
          "Fetal heart rate change is a late sign of hypovolemia",
          "Hypotension at this stage is due to supine positioning alone",
          "Possible hemorrhage, as 30% loss may precede hypotension",
          "They are normal for 31 weeks, no action needed",
          "Vasopressors are first line for hypotension in pregnancy",
        ],
        correct: 2,
        explanation:
          "Blood volume expansion in pregnancy means she may lose 30% or more of her volume before she becomes hypotensive, so treat these vital signs as possible hemorrhage. A resting heart rate of 108 is higher than expected in pregnancy and may be early shock. The uterine circulation is shunted early, so fetal distress can be the first sign of maternal hypovolemia. Vasopressors reduce uterine perfusion and are not a substitute for volume and blood.",
        keyFeature: { topic: "shock", n: 1 },
        source: "sogc-trauma",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update:
          "She stabilizes after 1 L of crystalloid. eFAST is negative. Her blood type is O negative. Fetal heart rate is 150. She has a contraction every 5 minutes.",
        prompt: "What are the pregnancy specific elements of her ongoing management?",
        accept: [
          { id: "ctg", text: "Continuous fetal heart and uterine monitoring for at least 4 hours", match: ["fetal monitoring", "ctg", "cardiotocography", "tocometry", "electronic fetal", "fetal heart", "uterine monitoring", "4 hour"] },
          { id: "rhig", text: "Rh immune globulin 300 mcg IM", match: ["rh immune globulin", "rhig", "winrho", "anti d", "rhogam", "rh immunoglobulin"] },
          { id: "kb", text: "Kleihauer Betke test to quantify fetomaternal hemorrhage", match: ["kleihauer", "fetomaternal", "flow cytometry"] },
          { id: "ob", text: "Obstetric consultation in person", match: ["obstetric", "obstetrician", "ob consult"] },
          { id: "abruption", text: "Assess for placental abruption", match: ["abruption"] },
          { id: "steroid", text: "Antenatal corticosteroids if preterm delivery is likely", match: ["betamethasone", "antenatal steroid", "antenatal corticosteroid", "dexamethasone"] },
          { id: "us", text: "Obstetric ultrasound for placenta and fetal wellbeing", match: ["obstetric ultrasound", "placenta"] },
          { id: "ipv", text: "Screen privately for intimate partner violence", match: ["partner violence", "ipv", "domestic"] },
        ],
        unacceptable: [{ text: "Discharge home because eFAST is negative", match: ["discharge now", "discharge immediately", "immediate discharge", "send home now", "discharge because efast"], dangerous: true }],
        explanation:
          "Contractions after blunt trauma may herald abruption, which can occur with a normal eFAST and even minor maternal injury. Monitor for at least 4 hours, longer with contractions or tenderness. An Rh negative mother needs Rh immune globulin, with the Kleihauer Betke result guiding extra doses.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "sogc-trauma",
      },
      {
        id: "q4",
        kind: "single",
        update: "Thirty minutes later she suddenly becomes pulseless. CPR is under way with manual uterine displacement.",
        prompt: "Which of the following is the most appropriate additional action?",
        options: [
          "Continue CPR for 20 minutes before considering delivery",
          "Magnesium sulfate 4 g IV loading dose",
          "Resuscitative hysterotomy, delivery within about 5 minutes",
          "Transfer to the operating room with CPR in progress",
          "Wait for the obstetrician before starting any operative step",
        ],
        correct: 2,
        explanation:
          "With the fundus at or above the umbilicus, emptying the uterus relieves aortocaval compression and improves maternal resuscitation. Start the resuscitative hysterotomy by 4 minutes after arrest and aim for delivery by about 5 minutes. Do it where the arrest occurs. Moving the patient delays the procedure and degrades CPR.",
        keyFeature: { topic: "multiple-trauma", n: 1 },
        source: "aha-pregnancy",
      },
    ],
    sources: [S.sogc, S.ahaPreg],
    ...META,
  },

  /* 04 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-04",
    topic: "multiple-trauma",
    title: "Older woman after a fall down stairs",
    stem:
      "An 81-year-old woman fell down six stairs at home. She takes apixaban 5 mg twice daily for atrial fibrillation and metoprolol. GCS 14 (confused). She has a bleeding scalp laceration and left lateral chest wall tenderness. Her daughter says she lives alone and was independent.",
    vitals: { pulse: "78/minute", resp: "22/minute", bp: "146/80 mmHg", o2sat: "92% on room air", weight: "58 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features of her history change your assessment or management?",
        accept: [
          { id: "doac", text: "Apixaban raises the risk of intracranial and other bleeding", match: ["apixaban", "anticoagulant", "anticoagulation", "doac", "eliquis", "blood thinner"] },
          { id: "bb", text: "Metoprolol can mask tachycardia in shock", match: ["beta blocker", "metoprolol", "mask"] },
          { id: "age", text: "Older age with low physiologic reserve and risk of undertriage", match: ["age", "elderly", "older", "geriatric", "frailty", "reserve"] },
          { id: "ad", text: "Advance directive and goals of care", match: ["advance directive", "goals of care", "code status", "level of care", "wishes"] },
          { id: "cause", text: "Possible medical cause of the fall such as syncope, arrhythmia or stroke", match: ["syncope", "cause of fall", "why she fell", "arrhythmia", "stroke"] },
          { id: "baseline", text: "Baseline cognition to interpret her confusion", match: ["baseline", "dementia", "cognition"] },
          { id: "timing", text: "Time of the last apixaban dose", match: ["last dose"] },
          { id: "renal", text: "Renal function affecting drug clearance", match: ["renal", "creatinine", "kidney"] },
        ],
        explanation:
          "Older trauma patients are undertriaged because they look stable. Anticoagulants, beta blockers and limited reserve change both the risk and the signs. Always ask why an older adult fell, because the cause may need treatment as urgently as the injury.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Which of the following imaging studies are indicated for her at this time?",
        options: [
          "CT angiogram of the neck",
          "CT cervical spine",
          "CT head without contrast",
          "MRI of the brain",
          "Skull X-ray series",
          "Three view plain cervical spine films",
          "No imaging if Canadian CT Head Rule low risk",
        ],
        correct: [1, 2],
        explanation:
          "Patients on anticoagulants were excluded from the Canadian CT Head Rule and need CT head after any head injury. Age 65 or older is a high risk factor in the Canadian C-spine Rule, so CT of the cervical spine is indicated. Plain films miss too many injuries in older adults.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "ccr",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "CT shows an 8 mm acute subdural hematoma without midline shift and three left rib fractures with a small pneumothorax. Her last apixaban dose was 3 hours ago.",
        prompt: "What treatments do you give to address her anticoagulation?",
        accept: [
          { id: "pcc", text: "Four factor prothrombin complex concentrate (Octaplex or Beriplex)", match: ["pcc", "prothrombin complex", "octaplex", "beriplex"] },
          { id: "andexanet", text: "Andexanet alfa where available", match: ["andexanet", "andexxa", "ondexxya"] },
          { id: "txa", text: "Tranexamic acid", match: ["txa", "tranexamic"] },
          { id: "hold", text: "Hold further apixaban", match: ["hold apixaban", "stop apixaban", "discontinue", "hold anticoagulant", "stop anticoagulant"] },
        ],
        unacceptable: [
          { text: "Vitamin K", match: ["vitamin k"] },
          { text: "Frozen plasma", match: ["ffp", "fresh frozen plasma", "frozen plasma"] },
          { text: "Idarucizumab", match: ["idarucizumab", "praxbind"] },
          { text: "Protamine", match: ["protamine"] },
        ],
        explanation:
          "Intracranial hemorrhage on a factor Xa inhibitor is life threatening bleeding. PCC is the usual Canadian option, and andexanet is the specific reversal agent where available. Vitamin K and plasma do not reverse apixaban. Idarucizumab reverses dabigatran only.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "thrombosis-canada",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "Two hours later, after IV hydromorphone for rib pain, she is harder to rouse. RR 30 and shallow, SpO2 88% on 4 L/min. HR 84, BP 128/70.",
        prompt: "What are the possible causes of her deterioration?",
        accept: [
          { id: "sdh", text: "Expanding subdural hematoma", match: ["subdural", "intracranial", "head bleed", "ich", "expanding hematoma"] },
          { id: "ptx", text: "Enlarging or tension pneumothorax", match: ["pneumothorax", "tension"] },
          { id: "htx", text: "Hemothorax", match: ["hemothorax", "haemothorax"] },
          { id: "opioid", text: "Opioid oversedation with hypoventilation", match: ["opioid", "oversedation", "narcotic", "hydromorphone", "sedation"] },
          { id: "splint", text: "Splinting from rib fracture pain causing hypoventilation and atelectasis", match: ["splinting", "atelectasis", "hypoventilation", "pain"] },
          { id: "contusion", text: "Pulmonary contusion", match: ["contusion"] },
          { id: "co2", text: "Hypercapnia", match: ["hypercapnia", "co2", "carbon dioxide"] },
          { id: "bleed", text: "Occult hemorrhage such as splenic injury masked by the beta blocker", match: ["spleen", "splenic", "hemorrhage", "haemorrhage", "occult bleeding"] },
          { id: "asp", text: "Aspiration", match: ["aspiration"] },
          { id: "seizure", text: "Nonconvulsive seizure", match: ["seizure"] },
        ],
        explanation:
          "Falling consciousness with a rising respiratory rate in an anticoagulated older adult demands a structured search, not an assumption of drug effect. Hematoma expansion, an enlarging pneumothorax and hypoventilation from pain or opioids can coexist. A beta blocker can hide the tachycardia of occult bleeding.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.ccr, S.thrombosisCanada],
    ...META,
  },

  /* 05 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-05",
    topic: "multiple-trauma",
    title: "Teen off a dirt bike",
    stem:
      "A 17-year-old boy with severe hemophilia A was thrown from a dirt bike at a trail park. He was helmeted. He had a brief loss of consciousness and walked to the ambulance. GCS 15. He has a headache and has vomited once. SpO2 is 99%. He has neck pain but no midline tenderness. He carries a factor first card.",
    vitals: { pulse: "96/minute", resp: "18/minute", bp: "128/72 mmHg", weight: "60 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "CT head first, then factor replacement if bleeding is seen",
          "Desmopressin 0.3 mcg/kg IV before imaging",
          "Factor VIII 50 IU/kg (3000 IU) IV before imaging",
          "Frozen plasma 15 mL/kg IV before imaging",
          "Observe for 4 hours and image if symptoms worsen",
        ],
        correct: 2,
        explanation:
          "In severe hemophilia any significant head injury is treated as a bleed. Raise the factor level toward 100% before imaging. Each IU/kg of factor VIII raises the level by about 2%, so 50 IU/kg is the usual dose. Desmopressin only helps mild hemophilia A, and plasma is a poor substitute for concentrate.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "wfh",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What other history do you need because of his hemophilia?",
        accept: [
          { id: "inhibitor", text: "Whether he has an inhibitor", match: ["inhibitor"] },
          { id: "product", text: "His usual factor product, dose and time of last prophylaxis", match: ["product", "last dose", "prophylaxis", "usual dose", "last infusion"] },
          { id: "emici", text: "Whether he takes emicizumab", match: ["emicizumab", "hemlibra"] },
          { id: "htc", text: "Contact for his hemophilia treatment centre or hematologist", match: ["treatment centre", "treatment center", "hematologist", "hematology", "haematology"] },
          { id: "level", text: "Baseline factor level and severity", match: ["baseline", "severity", "factor level"] },
        ],
        explanation:
          "An inhibitor makes factor VIII ineffective and requires bypassing agents. Emicizumab changes both the bleeding risk and the interpretation of coagulation tests. The treatment centre knows his history and should guide ongoing dosing.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "wfh",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate approach to his cervical spine?",
        options: [
          "CT cervical spine",
          "MRI cervical spine",
          "Rotation testing to 45 degrees",
          "Three view plain films",
          "No imaging and clinical clearance",
        ],
        correct: 0,
        explanation:
          "Under the Canadian C-spine Rule a crash on a motorized recreational vehicle is a dangerous mechanism and a high risk factor. High risk patients go straight to imaging without range of motion testing. Being ambulatory is a low risk factor only when no high risk factor is present. CT is the preferred study.",
        keyFeature: { topic: "multiple-trauma", n: 1 },
        source: "ccr",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        update: "CT head and cervical spine are normal. He has received factor VIII.",
        prompt: "What hemophilia related injuries or complications do you look for on the secondary survey?",
        accept: [
          { id: "joint", text: "Hemarthrosis", match: ["hemarthrosis", "haemarthrosis", "joint bleed", "joint"] },
          { id: "psoas", text: "Iliopsoas hematoma", match: ["iliopsoas", "psoas"] },
          { id: "compartment", text: "Muscle bleed with compartment syndrome", match: ["compartment", "muscle bleed"] },
          { id: "rp", text: "Retroperitoneal or intra-abdominal bleeding", match: ["retroperitoneal", "abdominal", "spleen", "splenic", "liver"] },
          { id: "neck", text: "Neck or tongue hematoma threatening the airway", match: ["neck hematoma", "airway", "tongue", "retropharyngeal"] },
          { id: "delayed", text: "Delayed intracranial hemorrhage", match: ["delayed", "intracranial"] },
          { id: "urine", text: "Hematuria or renal bleeding", match: ["hematuria", "haematuria", "renal"] },
        ],
        explanation:
          "Bleeding in hemophilia is often deep and delayed. Iliopsoas bleeds can mimic hip injury and cause femoral nerve palsy. Muscle bleeds can cause compartment syndrome. A normal first CT does not exclude a later intracranial bleed, so plan observation and repeat dosing with the treatment centre.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "wfh",
      },
    ],
    sources: [S.wfh, S.ccr],
    ...META,
  },

  /* 06 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-06",
    topic: "multiple-trauma",
    title: "Logger awaiting a fixed wing transfer",
    stem:
      "You work in a rural hospital in northern Ontario. A 45-year-old logger was struck by a falling tree. You intubated him for a GCS of 7. He has bilateral periorbital bruising and clear fluid from the right ear. Chest X-ray shows a 2 cm left apical pneumothorax. He has a closed mid-shaft right femur fracture. A fixed wing air ambulance will fly him 90 minutes to the trauma centre.",
    vitals: { pulse: "104/minute", bp: "128/76 mmHg", o2sat: "96% on FiO2 0.5", weight: "95 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 4,
        prompt: "What steps do you take to prepare him for a safe flight?",
        accept: [
          { id: "tube", text: "Place a chest tube for the pneumothorax before departure", match: ["chest tube", "thoracostomy", "chest drain"] },
          { id: "og", text: "Orogastric tube to decompress the stomach", match: ["orogastric", "og tube", "gastric tube", "og"] },
          { id: "foley", text: "Urinary catheter", match: ["urinary catheter", "foley", "catheter"] },
          { id: "splint", text: "Traction splint for the femur", match: ["traction", "splint"] },
          { id: "ett", text: "Secure the tube and confirm with waveform capnography", match: ["capnography", "etco2", "end tidal", "secure the tube", "secure ett", "tube tie"] },
          { id: "cuff", text: "Fill the cuff with saline or monitor cuff pressure", match: ["cuff"] },
          { id: "sed", text: "Continuous sedation and analgesia infusions", match: ["sedation", "analgesia", "infusion"] },
          { id: "iv", text: "Two secure IV lines", match: ["two iv", "iv line", "secure iv", "large bore"] },
          { id: "smr", text: "Spinal motion restriction on a vacuum mattress", match: ["spinal", "collar", "vacuum mattress", "spine"] },
          { id: "docs", text: "Send copies of imaging, records and a physician to physician handover", match: ["imaging", "document", "chart", "handover", "records"] },
          { id: "warm", text: "Keep him warm", match: ["warm", "hypothermia", "blanket"] },
          { id: "blood", text: "Blood products available en route", match: ["blood product", "prbc", "blood for transport", "blood on board"] },
        ],
        unacceptable: [{ text: "Nasogastric tube", match: ["nasogastric", "ng"], dangerous: true }],
        explanation:
          "Anticipate every intervention that would be hard to perform in a cramped aircraft. A pneumothorax will expand as cabin pressure falls, so drain it before flight. Raccoon eyes and otorrhea suggest a basal skull fracture, so the gastric tube must go through the mouth. A nasal tube can enter the cranial vault.",
        keyFeature: { topic: "multiple-trauma", n: 8 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Which of the following physiologic effects of altitude are most relevant to this patient?",
        options: [
          "A pressurized cabin removes all altitude effects",
          "Cabin pressure rises above sea level pressure during flight",
          "Gas volumes shrink, so pneumothoraces matter less",
          "Oxygen saturation is unaffected in ventilated patients",
          "Partial pressure of oxygen falls, so oxygen needs may rise",
          "Trapped gas expands as cabin pressure falls",
        ],
        correct: [4, 5],
        explanation:
          "Boyle law means gas in a pneumothorax, the stomach, an endotracheal tube cuff and air splints expands as ambient pressure falls. Pressurized cabins are usually held near 1500 to 2500 m, not sea level. The lower partial pressure of oxygen means a ventilated patient may need a higher FiO2 or PEEP.",
        keyFeature: { topic: "multiple-trauma", n: 8 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "While the chest tube is being set up, his SpO2 falls to 85%. The ventilator alarms for high peak pressure. BP is 86/50.",
        prompt: "What causes do you check for right away?",
        accept: [
          { id: "disp", text: "Tube displacement into the esophagus or a mainstem bronchus", match: ["displace", "displacement", "dislodge", "esophageal", "oesophageal", "mainstem", "migrated", "migration"] },
          { id: "obs", text: "Tube obstruction by secretions, blood or kinking", match: ["obstruct", "obstruction", "plug", "kink", "secretion"] },
          { id: "ptx", text: "Tension pneumothorax", match: ["pneumothorax", "tension"] },
          { id: "equip", text: "Equipment failure such as ventilator or oxygen supply", match: ["equipment", "ventilator", "oxygen supply", "circuit", "disconnect"] },
          { id: "stack", text: "Breath stacking or auto PEEP", match: ["stacking", "auto peep", "autopeep"] },
          { id: "htx", text: "Hemothorax", match: ["hemothorax", "haemothorax"] },
        ],
        explanation:
          "The DOPE approach covers displacement, obstruction, pneumothorax and equipment. With positive pressure ventilation a small pneumothorax can become a tension pneumothorax quickly, and hypotension with high peak pressure makes it most likely here. Disconnect from the ventilator, bag by hand and decompress if needed.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.rosen],
    ...META,
  },

  /* 07 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-07",
    topic: "multiple-trauma",
    title: "Bleeding patient who declines blood",
    stem:
      "A 38-year-old woman was the passenger in a rollover. She is alert and oriented. GCS 15. SpO2 is 97%. eFAST shows free fluid in the left upper quadrant. She tells you she is a Jehovah's Witness and will not accept blood. She shows you a signed advance directive card that refuses whole blood, red cells, plasma and platelets.",
    vitals: { pulse: "124/minute", resp: "24/minute", bp: "86/54 mmHg", weight: "62 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What steps do you take in assessing and documenting her refusal?",
        accept: [
          { id: "capacity", text: "Assess her capacity to refuse", match: ["capacity", "capable"] },
          { id: "informed", text: "Explain the risk of death and confirm she understands", match: ["risk", "death", "informed", "understand"] },
          { id: "private", text: "Speak with her privately to confirm the refusal is voluntary", match: ["private", "alone", "coercion", "voluntary", "pressure"] },
          { id: "fractions", text: "Clarify which fractions and techniques she accepts, such as albumin, cryoprecipitate, PCC or cell salvage", match: ["fraction", "cell saver", "cell salvage", "accept", "albumin", "cryoprecipitate"] },
          { id: "doc", text: "Document the discussion and the card in the chart", match: ["document", "chart", "record"] },
          { id: "liaison", text: "Offer contact with the hospital liaison committee if she wishes", match: ["liaison", "elder"] },
        ],
        explanation:
          "A capable adult can refuse any treatment, including life saving blood. Your duty is to confirm capacity, give clear information about the risk, and make sure the choice is her own. Many Witnesses accept some fractions or cell salvage, so ask specifically and document exactly what she accepts.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "hcca",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What blood sparing measures do you use?",
        accept: [
          { id: "txa", text: "Tranexamic acid 1 g IV over 10 minutes then 1 g over 8 hours", match: ["txa", "tranexamic"] },
          { id: "surgery", text: "Urgent surgical or angiographic control of the spleen", match: ["surgical", "angiographic", "splenectomy", "surgery", "operating room", "embolization", "angioembolization", "interventional radiology", "laparotomy", "surgeon"] },
          { id: "permissive", text: "Permissive hypotension", match: ["permissive"] },
          { id: "phleb", text: "Minimize blood draws and use small volume tubes", match: ["phlebotomy", "blood draw", "small tube", "paediatric tube", "pediatric tube"] },
          { id: "salvage", text: "Cell salvage if she accepts it", match: ["cell salvage", "cell saver"] },
          { id: "warm", text: "Prevent hypothermia and acidosis", match: ["warm", "hypothermia"] },
          { id: "factor", text: "Fibrinogen concentrate or PCC if acceptable to her", match: ["fibrinogen", "pcc", "prothrombin"] },
          { id: "epo", text: "Erythropoietin and IV iron later in the course", match: ["erythropoietin", "epo", "iron"] },
        ],
        explanation:
          "Without transfusion the priority is rapid haemorrhage control. Tranexamic acid reduces death from bleeding when given within 3 hours of injury. Limiting crystalloid, avoiding hypothermia and minimizing phlebotomy protect her remaining red cell mass.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "crash2",
      },
      {
        id: "q3",
        kind: "single",
        update: "On the way to the operating room she becomes unresponsive. Her husband, who is not a Witness, begs you to transfuse her.",
        prompt: "Which of the following is the most appropriate action in Ontario?",
        options: [
          "Continue to withhold blood",
          "Seek an urgent court order first",
          "Stop all resuscitation",
          "Transfuse under the emergency exception",
          "Transfuse with consent from her husband",
        ],
        correct: 0,
        explanation:
          "Continue to withhold blood because her prior capable wish applies to this situation. Under the Health Care Consent Act a known prior capable wish that applies to the circumstances must be followed, and the emergency exception does not override it. Her husband cannot consent to a treatment she refused while capable. Her refusal was informed, recent and specific to this situation. She still receives every other treatment she has not refused.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "hcca",
      },
    ],
    sources: [S.hcca, S.crash2],
    ...META,
  },

  /* 08 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-08",
    topic: "multiple-trauma",
    alsoTopics: ["airway"],
    title: "Ejected driver after intubation",
    stem:
      "A 28-year-old man was ejected in a rollover. On arrival GCS is 6. His vital signs on arrival are listed below. You perform rapid sequence intubation. The tube is at 23 cm at the teeth and waveform capnography is present.",
    vitals: { pulse: "118/minute", resp: "10/minute", bp: "112/70 mmHg", o2sat: "91% on a bag valve mask", weight: "90 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        update:
          "Five minutes later SpO2 is 82%, HR 138, BP 74/40. Peak airway pressure is 42 cm H2O. Breath sounds are absent on the left.",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "Finger thoracostomy, left fifth space, midaxillary line",
          "Increase PEEP to improve oxygenation",
          "Obtain a portable chest X-ray before needle decompression",
          "Start a norepinephrine infusion",
          "Withdraw the tube 3 cm and reassess",
        ],
        correct: 0,
        explanation:
          "Positive pressure ventilation can turn a simple pneumothorax into tension within minutes. Hypotension, high airway pressure and absent breath sounds need immediate decompression by finger thoracostomy in the left fifth intercostal space at the midaxillary line. The tube depth is appropriate and capnography confirms tracheal placement. Increasing PEEP would make the tension worse.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "After decompression and a chest tube he improves. SpO2 97%, BP 112/68.",
        prompt: "How do you confirm and monitor correct tube position?",
        accept: [
          { id: "etco2", text: "Continuous waveform capnography", match: ["capnography", "etco2", "end tidal", "capnograph"] },
          { id: "cxr", text: "Chest X-ray with the tip 2 to 4 cm above the carina", match: ["chest x ray", "cxr", "xray", "carina"] },
          { id: "ausc", text: "Bilateral auscultation", match: ["auscultation", "auscultate", "breath sound"] },
          { id: "us", text: "Ultrasound for bilateral lung sliding", match: ["ultrasound", "lung sliding", "pocus"] },
          { id: "depth", text: "Record and recheck the depth at the teeth", match: ["depth", "cm at the teeth", "cm at the lip"] },
          { id: "abg", text: "Arterial blood gas", match: ["abg", "blood gas"] },
          { id: "spo2", text: "Continuous pulse oximetry", match: ["oximetry", "spo2", "saturation"] },
        ],
        explanation:
          "Waveform capnography is the most reliable confirmation of tracheal placement and should stay on through transport. It does not show depth, so check a chest X-ray and record the depth. Tubes migrate with head movement and log rolling.",
        keyFeature: { topic: "airway", n: 6 },
        source: "cafg",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "He has now received 6 units of red cells and 4 of plasma. His CT is complete.",
        prompt: "What iatrogenic complications do you check for?",
        accept: [
          { id: "hypothermia", text: "Hypothermia", match: ["hypothermia", "temperature"] },
          { id: "ca", text: "Hypocalcemia from citrate in blood products", match: ["calcium", "hypocalcemia", "hypocalcaemia", "citrate"] },
          { id: "k", text: "Hyperkalemia", match: ["hyperkalemia", "hyperkalaemia", "potassium"] },
          { id: "pressure", text: "Pressure injury from the spine board or collar", match: ["pressure injury", "pressure ulcer", "pressure sore", "backboard", "spine board", "board"] },
          { id: "collar", text: "Tight collar impairing venous drainage and raising ICP", match: ["collar"] },
          { id: "tube", text: "Tube or chest tube malposition", match: ["malposition", "mainstem", "tube position"] },
          { id: "coag", text: "Dilutional coagulopathy", match: ["coagulopathy", "dilutional"] },
          { id: "extrav", text: "Extravasation from IV or IO lines", match: ["extravasation", "infiltration", "infiltrated"] },
          { id: "reaction", text: "Transfusion reaction or TACO", match: ["transfusion reaction", "taco", "trali"] },
          { id: "gastric", text: "Gastric distension from bagging", match: ["gastric distension", "gastric distention", "gastric"] },
        ],
        explanation:
          "Resuscitation causes its own injuries. Cold products and exposure cause hypothermia, which worsens coagulopathy. Citrate lowers ionized calcium. Rigid boards cause pressure injury within hours and should be removed as soon as possible.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "What easily missed injuries must the secondary survey target in this unconscious patient?",
        accept: [
          { id: "tl", text: "Thoracolumbar spine fracture", match: ["thoracolumbar", "thoracic spine", "lumbar spine", "back"] },
          { id: "bcvi", text: "Blunt carotid or vertebral artery injury", match: ["carotid", "vertebral artery", "cerebrovascular", "bcvi"] },
          { id: "scalp", text: "Bleeding scalp laceration", match: ["scalp"] },
          { id: "bowel", text: "Hollow viscus or mesenteric injury", match: ["bowel", "hollow viscus", "mesenteric"] },
          { id: "distal", text: "Hand, wrist, foot or ankle fractures", match: ["hand", "foot", "feet", "wrist", "ankle", "finger"] },
          { id: "perineum", text: "Perineal, rectal or urethral injury", match: ["perineum", "perineal", "rectal", "urethral"] },
          { id: "diaphragm", text: "Diaphragm rupture", match: ["diaphragm"] },
          { id: "aorta", text: "Blunt aortic injury", match: ["aorta", "aortic"] },
          { id: "eye", text: "Globe injury", match: ["globe", "eye"] },
          { id: "compartment", text: "Compartment syndrome", match: ["compartment"] },
        ],
        explanation:
          "An unconscious patient cannot report pain, so injuries are found only by a complete head to toe and log roll exam. Distal extremity fractures and spine injuries are the classic misses. Plan a tertiary survey within 24 hours once he can be examined again.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.cafg],
    ...META,
  },

  /* 09 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-09",
    topic: "multiple-trauma",
    alsoTopics: ["shock"],
    title: "Child struck by a car",
    stem:
      "A 6-year-old boy was struck by a car at about 40 km/h while crossing the street. He is crying and says his tummy hurts. GCS 14. Capillary refill is 4 seconds and his hands and feet are cool. There is bruising over the left upper quadrant. You work in a community hospital.",
    vitals: { pulse: "148/minute", resp: "32/minute", bp: "88/56 mmHg", o2sat: "98% on oxygen", weight: "22 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        update:
          "His systolic pressure is normal for age.",
        prompt: "What findings show that he is in shock?",
        accept: [
          { id: "hr", text: "Tachycardia of 148", match: ["tachycardia", "heart rate", "hr 148", "148"] },
          { id: "crt", text: "Capillary refill of 4 seconds", match: ["capillary refill", "cap refill", "crt"] },
          { id: "cool", text: "Cool extremities", match: ["cool", "cold", "mottled", "mottling"] },
          { id: "rr", text: "Tachypnea", match: ["tachypnea", "tachypnoea", "respiratory rate"] },
          { id: "loc", text: "Decreased level of consciousness with GCS 14", match: ["gcs", "mental status", "confused", "confusion", "decreased level"] },
        ],
        unacceptable: [{ text: "Normal blood pressure means he is not in shock", match: ["not in shock"] }],
        explanation:
          "Children maintain systolic pressure until they have lost 30 to 40% of blood volume. Tachycardia and poor perfusion are the early signs. The lower limit of systolic pressure at 6 years is about 70 plus twice the age, or 82 mmHg, so hypotension is a late finding.",
        keyFeature: { topic: "shock", n: 1 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Which of the following initial resuscitation orders are most appropriate for this child?",
        options: [
          "Albumin 5% 20 mL/kg IV",
          "Dextrose 10% 5 mL/kg IV",
          "Norepinephrine 0.1 mcg/kg/min",
          "Normal saline 60 mL/kg over 15 minutes",
          "Normal saline 20 mL/kg repeated until the BP is normal",
          "Tranexamic acid 1 g IV over 10 minutes",
          "Tranexamic acid 15 mg/kg (330 mg) IV over 10 minutes",
          "Warmed packed red cells 10 mL/kg (220 mL)",
        ],
        correct: [6, 7],
        explanation:
          "A child in hemorrhagic shock needs blood early, given in 10 mL/kg aliquots and warmed. Paediatric tranexamic acid is 15 mg/kg to a maximum of 1 g, followed by 2 mg/kg/h over 8 hours. A fixed 1 g dose is 45 mg/kg here. Repeated crystalloid dilutes clotting factors and vasopressors do not treat hypovolemia.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "rcpch-txa",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What measures do you take to prevent iatrogenic hypothermia in this child?",
        accept: [
          { id: "fluids", text: "Warm all fluids and blood through a fluid warmer", match: ["warmer", "warm fluid", "warmed", "fluid warmer", "warm blood", "warm product"] },
          { id: "room", text: "Warm the resuscitation room", match: ["room temperature", "warm room", "ambient", "thermostat", "warm the room"] },
          { id: "blanket", text: "Forced air warming blanket", match: ["bair hugger", "forced air", "warming blanket", "blanket"] },
          { id: "cover", text: "Cover him after each part of the exam", match: ["cover", "exposure", "expose", "avoid exposure", "limit exposure", "minimize exposure"] },
          { id: "radiant", text: "Overhead radiant warmer", match: ["radiant", "overhead"] },
          { id: "probe", text: "Monitor core temperature", match: ["core temp", "temperature probe", "monitor temperature", "core temperature"] },
        ],
        explanation:
          "Children have a large surface area for their mass and lose heat fast when exposed. Hypothermia worsens coagulopathy and acidosis. Warm the room before arrival, warm everything infused and cover the child between exams.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "single",
        update: "After 20 mL/kg of red cells his HR is 118 and BP 100/62. He is warm and alert. CT shows a grade IV splenic laceration without active contrast extravasation.",
        prompt: "Which of the following is the most appropriate management plan for him?",
        options: [
          "Diagnostic laparoscopy before transfer",
          "Discharge home with return instructions",
          "Immediate splenectomy by a general surgeon at this hospital",
          "Nonoperative management at a paediatric trauma centre",
          "Routine angioembolization of the splenic injury",
        ],
        correct: 3,
        explanation:
          "Most children with blunt splenic injury are managed without surgery, and the decision is driven by physiology rather than CT grade. He has responded to transfusion, so arrange transfer to a paediatric trauma centre with a surgeon aware, for monitoring and serial examinations. Failure of nonoperative management usually shows as ongoing transfusion need.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "apsa",
      },
    ],
    sources: [S.atls, S.rcpch, S.apsa],
    ...META,
  },

  /* 10 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-10",
    topic: "multiple-trauma",
    alsoTopics: ["msk"],
    title: "Roofer after a fall",
    stem:
      "A 42-year-old roofer fell about 5 m and landed on his feet. He complains of severe pain in both heels and in his lower back. GCS 15. SpO2 is 98%. His airway, breathing and circulation are intact and the primary survey is otherwise unremarkable.",
    vitals: { pulse: "102/minute", resp: "20/minute", bp: "132/84 mmHg", weight: "88 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What injuries do you specifically look for given this mechanism?",
        accept: [
          { id: "spine", text: "Thoracolumbar burst fracture", match: ["lumbar", "thoracolumbar", "spine", "burst", "vertebral"] },
          { id: "calc", text: "Bilateral calcaneal fractures", match: ["calcaneal", "calcaneus", "calcaneum", "heel"] },
          { id: "plateau", text: "Tibial plateau fracture", match: ["tibial plateau", "plateau", "tibia"] },
          { id: "pelvis", text: "Pelvic, acetabular or hip fracture", match: ["pelvic", "pelvis", "acetabular", "acetabulum", "hip", "femoral neck"] },
          { id: "wrist", text: "Wrist fractures from an outstretched hand", match: ["wrist", "radius", "scaphoid"] },
          { id: "deceleration", text: "Renal or aortic deceleration injury", match: ["renal", "kidney", "aortic", "aorta"] },
          { id: "pilon", text: "Tibial pilon or talus fracture", match: ["pilon", "talus", "talar"] },
        ],
        explanation:
          "Axial loading through the heels transmits force up the leg to the spine. About one in ten calcaneal fractures has an associated spinal fracture. The pain of the heels can distract from the spine, so image both.",
        keyFeature: { topic: "msk", n: 1 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "What parts of the secondary survey must you include to find these injuries?",
        accept: [
          { id: "logroll", text: "Log roll and palpate the entire spine", match: ["log roll", "palpate spine", "spine palpation", "back", "logroll"] },
          { id: "neuro", text: "Full neurologic exam including perianal sensation and rectal tone", match: ["neuro", "neurologic", "neurological", "rectal", "perianal", "saddle"] },
          { id: "nv", text: "Distal pulses and neurovascular status of both feet", match: ["pulse", "neurovascular", "capillary refill"] },
          { id: "pelvis", text: "Examine the pelvis and hips", match: ["pelvis", "pelvic", "hip"] },
          { id: "joints", text: "Examine every joint from wrist to ankle", match: ["joint", "wrist", "knee", "ankle"] },
        ],
        explanation:
          "The log roll with palpation of every spinous process finds occult spine injuries. A careful neurologic exam including sacral function detects cord or cauda equina injury. Examining every joint avoids missing fractures masked by the painful heels.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "X-rays show a comminuted right calcaneal fracture and an L1 burst fracture without neurologic deficit. Six hours later his right foot pain is severe despite IV opioids. The foot is tense and passive toe dorsiflexion is very painful.",
        prompt: "What are your management steps now?",
        accept: [
          { id: "ortho", text: "Urgent orthopaedic consultation for possible fasciotomy", match: ["fasciotomy", "orthopedic", "orthopaedic", "ortho", "surgery", "surgeon"] },
          { id: "pressure", text: "Measure compartment pressures", match: ["compartment pressure", "pressure measurement", "stryker", "measure pressure"] },
          { id: "remove", text: "Remove or split any constrictive dressing or splint", match: ["remove", "loosen", "bivalve", "split"] },
          { id: "level", text: "Keep the foot at heart level", match: ["heart level"] },
          { id: "bp", text: "Avoid hypotension to maintain perfusion", match: ["avoid hypotension", "prevent hypotension", "treat hypotension", "no hypotension", "perfusion", "maintain blood pressure"] },
        ],
        unacceptable: [{ text: "Elevate the foot above the heart", match: ["elevate above", "elevation above", "elevate the foot", "elevate the leg", "elevate limb", "elevate foot"] }],
        explanation:
          "Pain out of proportion and pain on passive stretch are early signs of compartment syndrome. Calcaneal fractures can cause a foot compartment syndrome. Elevation above the heart lowers perfusion pressure. Surgery is the definitive treatment.",
        keyFeature: { topic: "msk", n: 7 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "What questions about the circumstances of the fall could change your management?",
        accept: [
          { id: "syncope", text: "Did he feel faint, have chest pain or palpitations before falling", match: ["syncope", "faint", "lightheaded", "dizzy", "prodrome", "chest pain", "palpitation", "passed out"] },
          { id: "etoh", text: "Alcohol or drug use", match: ["alcohol", "drug", "intoxication", "substance"] },
          { id: "meds", text: "Anticoagulant or antiplatelet use", match: ["anticoagulant", "blood thinner", "antiplatelet"] },
          { id: "seizure", text: "Possible seizure", match: ["seizure"] },
          { id: "glucose", text: "Diabetes and possible hypoglycemia", match: ["hypoglycemia", "hypoglycaemia", "diabetes", "sugar"] },
          { id: "work", text: "Workplace injury with safety equipment and reporting to the compensation board", match: ["wsib", "workplace", "harness", "work"] },
        ],
        explanation:
          "A medical event can cause a fall from height, and it may need its own treatment. Intoxication and anticoagulants change the risk of occult injury. A workplace fall also triggers reporting obligations to the provincial compensation board.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "atls",
      },
    ],
    sources: [S.atls, S.rosen],
    ...META,
  },

  /* 11 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-11",
    topic: "multiple-trauma",
    title: "Gunshot wound to the abdomen",
    stem:
      "A 22-year-old man arrives by private car with a single gunshot wound to the left upper quadrant. There is no exit wound. He is confused. GCS 14. SpO2 is 96%. There are no signs of head injury. You are at a Level 1 trauma centre.",
    vitals: { pulse: "134/minute", resp: "28/minute", bp: "76/48 mmHg", weight: "75 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What are the components of your initial hemorrhagic shock resuscitation, including specific products or drugs?",
        accept: [
          { id: "mtp", text: "Activate the massive transfusion protocol", match: ["massive transfusion", "mtp"] },
          { id: "rbc", text: "Uncrossmatched O red cells", match: ["o negative", "o positive", "uncrossmatched", "prbc", "packed red", "red cell"] },
          { id: "plasma", text: "Early plasma and platelets in a balanced ratio", match: ["plasma", "balanced", "ratio", "platelet"] },
          { id: "txa", text: "Tranexamic acid 1 g IV over 10 minutes, then 1 g over 8 hours", match: ["txa", "tranexamic"] },
          { id: "ca", text: "Calcium chloride 1 g IV", match: ["calcium"] },
          { id: "permissive", text: "Permissive hypotension with systolic BP 80 to 90 mmHg", match: ["permissive", "sbp 80", "sbp 90", "systolic 80", "systolic 90"] },
          { id: "cryst", text: "Limit crystalloid", match: ["limit crystalloid", "minimize crystalloid", "minimise crystalloid", "avoid crystalloid", "no crystalloid"] },
          { id: "warm", text: "Warm all products through a rapid infuser", match: ["warm", "rapid infuser", "warmer"] },
        ],
        unacceptable: [
          { text: "Vasopressors to raise the blood pressure", match: ["norepinephrine", "vasopressor", "pressor", "levophed", "phenylephrine"] },
          { text: "Two litres of crystalloid first", match: ["2 l", "2 litre", "2 liter", "two litre", "two liter", "2l"] },
        ],
        explanation:
          "Damage control resuscitation replaces lost blood with blood. Balanced ratios of plasma, platelets and red cells, early tranexamic acid and calcium limit coagulopathy. Large crystalloid volumes and early vasopressors are associated with more bleeding and worse outcomes.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "proppr",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step?",
        options: [
          "Bedside local wound exploration",
          "CT abdomen and pelvis with contrast",
          "Diagnostic peritoneal lavage",
          "Immediate laparotomy in the operating room",
          "Serial abdominal exams in the emergency department",
        ],
        correct: 3,
        explanation:
          "A hypotensive patient with a gunshot wound to the abdomen needs surgical haemorrhage control now. Imaging and further tests delay the one intervention that will save him. Resuscitation continues on the way to and in the operating room.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "Forty minutes into the protocol he has received 10 units of red cells, 10 of plasma and 2 doses of platelets. Ionized calcium 0.88 mmol/L, fibrinogen 1.1 g/L, INR 1.8, temperature 34.8°C, pH 7.14.",
        prompt: "What targeted corrections do you make, including the product or drug?",
        accept: [
          { id: "ca", text: "Calcium chloride 1 g IV or calcium gluconate 3 g IV", match: ["calcium"] },
          { id: "fib", text: "Cryoprecipitate or fibrinogen concentrate", match: ["cryo", "cryoprecipitate", "fibrinogen"] },
          { id: "warm", text: "Active warming with a forced air blanket and warmed products", match: ["warm", "bair hugger", "forced air", "hypothermia", "rewarm"] },
          { id: "plasma", text: "More plasma to correct the INR", match: ["plasma", "ffp", "pcc", "prothrombin"] },
        ],
        explanation:
          "Each unit of blood carries citrate that binds calcium, and ionized calcium below 1.1 mmol/L impairs clotting and contractility. Fibrinogen is the first factor to fall and should be kept above 1.5 g/L. Hypothermia below 35°C and acidosis both worsen coagulopathy.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "euro-bleeding",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update:
          "The resuscitation room is crowded and noisy.",
        prompt: "What do you do as team leader to keep the team effective?",
        accept: [
          { id: "closed", text: "Use closed loop communication", match: ["closed loop"] },
          { id: "summary", text: "Give regular out loud summaries of the situation and plan", match: ["summaries", "summary", "summarize", "summarise", "update", "huddle", "share plan", "shared mental model"] },
          { id: "roles", text: "Assign and name each role", match: ["role", "assign", "name"] },
          { id: "blood", text: "Assign one nurse to coordinate blood products", match: ["coordinate blood", "blood product", "blood coordinator", "mtp nurse", "dedicated nurse", "runner"] },
          { id: "record", text: "Have a recorder track products and times", match: ["recorder", "scribe", "track"] },
          { id: "quiet", text: "Control noise and remove people who are not needed", match: ["quiet", "noise", "crowd", "remove extra", "limit people"] },
          { id: "help", text: "Call for more help early", match: ["call for help", "more help", "backup"] },
        ],
        explanation:
          "Crowding and noise cause missed orders and duplicated work. Named roles, closed loop orders and periodic summaries keep everyone on one plan. A dedicated nurse for blood products prevents gaps in the massive transfusion protocol.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "hicks",
      },
    ],
    sources: [S.proppr, S.atls, S.euro, S.hicks],
    ...META,
  },

  /* 12 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-12",
    topic: "multiple-trauma",
    title: "Head-on collision with a dilating pupil",
    stem:
      "A 55-year-old man was the driver in a head-on collision. GCS 7 (E1 V2 M4). His right pupil is 6 mm and sluggish, the left is 3 mm and reactive. He has been intubated. SpO2 is 97%. eFAST shows free fluid in the left upper quadrant.",
    vitals: { pulse: "112/minute", bp: "94/60 mmHg", weight: "80 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "What resuscitation targets differ because of his head injury?",
        accept: [
          { id: "sbp", text: "Systolic BP at least 100 mmHg for his age", match: ["sbp 100", "systolic 100", "sbp 110", "systolic 110", "map 80", "map 85", "map 90"] },
          { id: "o2", text: "Avoid hypoxia with SpO2 above 94%", match: ["avoid hypoxia", "no hypoxia", "hypoxia", "spo2", "oxygen saturation", "pao2", "oxygenation"] },
          { id: "co2", text: "Normocapnia with PaCO2 35 to 40 mmHg", match: ["pco2", "paco2", "normocapnia", "etco2", "co2"] },
          { id: "glucose", text: "Normal glucose", match: ["glucose", "hypoglycemia", "hyperglycemia"] },
          { id: "sodium", text: "Avoid hyponatremia", match: ["avoid hyponatremia", "sodium", "hyponatremia", "hyponatraemia"] },
          { id: "temp", text: "Avoid hyperthermia", match: ["avoid hyperthermia", "avoid fever", "hyperthermia", "fever", "normothermia"] },
        ],
        unacceptable: [{ text: "Permissive hypotension with systolic BP 80 to 90 mmHg", match: ["permissive", "sbp 80 90", "systolic 80 90"], dangerous: true }],
        explanation:
          "A single episode of hypotension or hypoxia roughly doubles mortality after severe brain injury. Guidelines target systolic pressure of at least 100 mmHg at age 50 to 69 and at least 110 mmHg at age 15 to 49 or over 70. Permissive hypotension is harmful here even though he is also bleeding.",
        keyFeature: { topic: "multiple-trauma", n: 6 },
        source: "btf",
      },
      {
        id: "q2",
        kind: "single",
        update: "After 2 units of red cells his BP is 84/50.",
        prompt: "Which of the following is the most appropriate priority at this point?",
        options: [
          "Burr holes in the emergency department",
          "CT head first, then laparotomy once imaged",
          "Hyperventilate to PaCO2 25 mmHg, then straight to CT scanner",
          "Laparotomy now, hyperosmolar therapy, neurosurgery aware",
          "Mannitol 1 g/kg before any further blood",
        ],
        correct: 3,
        explanation:
          "Ongoing hypotension causes secondary brain injury, so laparotomy for haemorrhage control comes first. Neurosurgery can plan in parallel and treat raised pressure in the operating room. CT in an unstable patient is unsafe. Mannitol causes diuresis and worsens hypovolemia.",
        keyFeature: { topic: "multiple-trauma", n: 2 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What measures do you use to treat suspected raised intracranial pressure on the way to the operating room?",
        accept: [
          { id: "hts", text: "Hypertonic saline, for example 3% 250 mL or 23.4% 30 mL", match: ["hypertonic", "3% saline", "23.4%"] },
          { id: "hob", text: "Head of bed at 30 degrees or reverse Trendelenburg", match: ["head of bed", "reverse trendelenburg", "elevate head", "30 degree", "head up"] },
          { id: "hv", text: "Brief hyperventilation to PaCO2 30 to 35 mmHg as a bridge", match: ["hyperventilate", "hyperventilation"] },
          { id: "collar", text: "Loosen the collar and tube ties", match: ["collar", "tube tie"] },
          { id: "sed", text: "Adequate sedation and analgesia", match: ["sedation", "sedate", "analgesia"] },
        ],
        unacceptable: [
          { text: "Corticosteroids", match: ["dexamethasone", "steroid", "methylprednisolone"], dangerous: true },
          { text: "Mannitol while hypotensive", match: ["mannitol"] },
        ],
        explanation:
          "Hypertonic saline lowers intracranial pressure while supporting intravascular volume, which suits a bleeding patient. Head elevation and removing venous obstruction are simple and effective. Steroids increase mortality after brain injury. Mannitol can worsen hypotension.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "btf",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "His wife arrives. She says he signed an advance directive last year saying he would not want life support.",
        prompt: "What steps do you take before changing the plan of care?",
        accept: [
          { id: "read", text: "Read the actual document", match: ["read", "review", "see the document", "copy", "document"] },
          { id: "applies", text: "Decide whether it applies to this situation", match: ["applies", "applicable", "circumstance", "situation", "specific"] },
          { id: "sdm", text: "Talk with his substitute decision maker about his wishes and values", match: ["substitute decision maker", "sdm", "wife", "values", "wishes"] },
          { id: "continue", text: "Continue resuscitation while this is clarified", match: ["continue"] },
          { id: "help", text: "Involve a senior colleague, ethics or palliative care", match: ["ethics", "palliative", "colleague"] },
        ],
        explanation:
          "A statement about life support written for a chronic illness may not apply to a sudden, possibly survivable injury. Read it, decide whether it fits this situation and speak with his substitute decision maker. Keep treating while you clarify, because stopping cannot be undone.",
        keyFeature: { topic: "multiple-trauma", n: 4 },
        source: "hcca",
      },
    ],
    sources: [S.btf, S.atls, S.hcca],
    ...META,
  },

  /* 13 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-13",
    topic: "multiple-trauma",
    title: "Five minute warning from paramedics",
    stem:
      "Paramedics call ahead to your Level 2 trauma centre. They are 5 minutes away with a 30-year-old cyclist struck by a truck. HR 140, BP 70 by palpation, GCS 9. There is an open right thigh wound that is bleeding heavily despite a pressure dressing, and crepitus over the left chest. You have two nurses, a respiratory therapist, a second emergency physician and a recorder.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What do you do before the patient arrives?",
        accept: [
          { id: "roles", text: "Assign roles to each team member", match: ["role", "assign", "allocate"] },
          { id: "ppe", text: "Everyone in personal protective equipment", match: ["ppe", "protective", "gown"] },
          { id: "mtp", text: "Activate the massive transfusion protocol and prime the rapid infuser", match: ["mtp", "massive transfusion", "blood", "rapid infuser"] },
          { id: "airway", text: "Prepare airway equipment and RSI drugs", match: ["airway", "rsi", "intubation"] },
          { id: "surgeon", text: "Call the trauma surgeon and alert the operating room and CT", match: ["surgeon", "operating room", "notify ct", "call ct", "surgery"] },
          { id: "chest", text: "Set up a thoracostomy tray", match: ["chest tube", "thoracostomy"] },
          { id: "tq", text: "Have a tourniquet and pelvic binder ready", match: ["tourniquet", "binder"] },
          { id: "brief", text: "Brief the team on the plan", match: ["brief", "briefing", "huddle", "plan"] },
          { id: "warm", text: "Warm the room and fluids", match: ["warm"] },
        ],
        explanation:
          "A two minute team briefing turns a group into a team. Pre-assigned roles, blood on the infuser and airway drugs drawn up mean critical actions start on arrival. The surgeon and operating room need the same early warning.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "hicks",
      },
      {
        id: "q2",
        kind: "menu",
        select: 3,
        update:
          "You decide to perform rapid sequence intubation.",
        prompt: "Which of the following tasks do you delegate to happen at the same time as the intubation?",
        options: [
          "A nurse applies direct thigh pressure or a tourniquet",
          "A nurse inserts a urinary catheter",
          "A nurse runs uncrossmatched blood through the rapid infuser",
          "The radiology technician takes a lateral C-spine film",
          "The recorder leaves to call the family",
          "The respiratory therapist draws an arterial blood gas",
          "The second physician prepares a left finger thoracostomy",
          "The second physician surveys the extremities",
        ],
        correct: [0, 2, 6],
        explanation:
          "Bleeding control, blood and chest decompression are the priorities that must continue during intubation. Positive pressure can convert a pneumothorax to tension, so the second physician is ready to perform a left finger thoracostomy if he deteriorates with ventilation. Tasks that do not change the next five minutes should wait.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update:
          "Blood continues to pour from the thigh wound despite direct pressure.",
        prompt: "What steps do you take to control the bleeding?",
        accept: [
          { id: "tq", text: "Apply a tourniquet proximal to the wound", match: ["tourniquet", "stop bleeding tourniquet", "stop the bleeding tourniquet"] },
          { id: "pack", text: "Pack the wound with hemostatic gauze and hold pressure", match: ["packing", "pack", "hemostatic", "haemostatic", "combat gauze", "gauze"] },
          { id: "groin", text: "Direct pressure on the femoral artery in the groin", match: ["femoral artery", "groin pressure", "proximal pressure", "groin", "hold pressure groin", "hold pressure femoral"] },
          { id: "splint", text: "Realign and splint the femur", match: ["traction", "splint", "realign"] },
          { id: "surgeon", text: "Urgent vascular or trauma surgery", match: ["vascular", "surgeon", "operating room"] },
          { id: "txa", text: "Tranexamic acid", match: ["txa", "tranexamic"] },
        ],
        unacceptable: [{ text: "Blind clamping in the wound", match: ["clamp", "hemostat"] }],
        explanation:
          "Exsanguinating limb haemorrhage is controlled before or alongside the airway. A tourniquet placed high on the thigh is fast and effective. Wound packing and groin pressure are alternatives when a tourniquet cannot be placed. Blind clamping injures nerves and rarely works.",
        keyFeature: { topic: "multiple-trauma", n: 1 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "The patient goes to the operating room 25 minutes after arrival.",
        prompt: "What actions do you take to support the team after the resuscitation?",
        accept: [
          { id: "debrief", text: "Brief hot debrief of what went well and what to change", match: ["debrief"] },
          { id: "wellness", text: "Check on team members' wellbeing and offer peer support", match: ["wellbeing", "well being", "support", "wellness", "check in"] },
          { id: "qi", text: "Flag system issues for quality review", match: ["quality", "qi", "review", "system"] },
          { id: "thanks", text: "Thank the team", match: ["thank"] },
          { id: "doc", text: "Complete documentation with the recorder", match: ["document", "documentation"] },
        ],
        explanation:
          "A short debrief captures lessons while they are fresh and supports staff after a stressful case. System problems such as delays in blood should go to quality review. Leadership includes caring for the team afterwards.",
        keyFeature: { topic: "multiple-trauma", n: 7 },
        source: "hicks",
      },
    ],
    sources: [S.hicks, S.atls],
    ...META,
  },

  /* 14 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-14",
    topic: "multiple-trauma",
    alsoTopics: ["environmental"],
    title: "Snowmobiler found hours after a crash",
    stem:
      "A 52-year-old man crashed his snowmobile into a tree and was found 3 hours later in the snow. He is drowsy but answers questions. GCS 13. SpO2 is 94%. Core temperature is measured by bladder probe. He is not shivering. His right knee is grossly deformed. You work in a regional hospital and a helicopter can take him to the trauma centre.",
    vitals: { temperature: "31.8°C core", pulse: "58/minute", resp: "12/minute", bp: "96/60 mmHg", weight: "100 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What rewarming or monitoring measures do you start now?",
        accept: [
          { id: "wet", text: "Remove wet clothing", match: ["wet clothing", "remove wet", "dry", "wet cloth"] },
          { id: "forced", text: "Active external rewarming with forced air or warming blankets", match: ["forced air", "bair hugger", "warming blanket", "active external", "heating pad", "warm blanket"] },
          { id: "fluids", text: "Warmed IV fluids at 40 to 42°C", match: ["warm fluid", "warmed fluid", "warmed iv", "warm iv", "heated fluid", "warm saline"] },
          { id: "o2", text: "Warmed humidified oxygen", match: ["humidified", "warm oxygen"] },
          { id: "gentle", text: "Gentle handling to avoid triggering arrhythmia", match: ["gentle", "minimal movement", "handle"] },
          { id: "probe", text: "Continuous core temperature with an esophageal or bladder probe", match: ["esophageal", "oesophageal", "core temperature", "bladder", "rectal probe"] },
          { id: "monitor", text: "Continuous cardiac monitoring", match: ["cardiac monitor", "cardiac monitoring", "monitoring", "ecg", "telemetry", "monitor"] },
        ],
        explanation:
          "At 31.8°C without shivering he has moderate hypothermia and needs active external and minimally invasive rewarming. Rough handling can precipitate ventricular fibrillation. Monitor core temperature continuously, because peripheral readings are unreliable. Extracorporeal rewarming is reserved for arrest or instability.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "hypothermia",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "On secondary survey the right knee is grossly unstable in all directions. The dorsalis pedis pulse is faint. The foot is cool, as are both hands.",
        prompt: "How do you assess for arterial injury?",
        accept: [
          { id: "abi", text: "Ankle brachial index", match: ["ankle brachial", "abi", "arterial pressure index", "api"] },
          { id: "cta", text: "CT angiography", match: ["ct angiogram", "cta", "angiography", "angiogram", "ct angiography"] },
          { id: "doppler", text: "Doppler signals compared with the other side", match: ["doppler"] },
          { id: "serial", text: "Serial neurovascular exams", match: ["serial", "neurovascular", "repeat pulse"] },
          { id: "vascular", text: "Vascular surgery consultation", match: ["vascular surgery", "vascular surgeon"] },
        ],
        unacceptable: [{ text: "A palpable pulse excludes arterial injury", match: ["palpable pulse excludes", "pulse rules out", "pulse excludes"] }],
        explanation:
          "Knee dislocations often reduce spontaneously and popliteal artery injury is easily missed. A faint pulse cannot be blamed on hypothermia alone. An ankle brachial index below 0.9 needs CT angiography. A normal pulse does not exclude intimal injury.",
        keyFeature: { topic: "multiple-trauma", n: 3 },
        source: "mills-abi",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate way to immobilize his leg for the helicopter transfer?",
        options: [
          "Air splint to the whole leg, fully inflated before takeoff",
          "Circumferential plaster cast from thigh to ankle",
          "Long leg posterior splint, knee in slight flexion",
          "Traction splint to the right leg",
          "No splint, to allow pulse checks",
        ],
        correct: 2,
        explanation:
          "A traction splint is contraindicated with a knee injury because it distracts the unstable joint. A long leg posterior splint in slight flexion keeps the knee reduced while allowing pulse checks. Record neurovascular status before and after splinting. A fully inflated air splint will expand with altitude and can cause ischemia. Circumferential casts hide compartment syndrome.",
        keyFeature: { topic: "multiple-trauma", n: 8 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "After 40 minutes of rewarming his temperature is 33.5°C. BP falls to 76/40 and HR is 110.",
        prompt: "What are the possible causes of his hypotension?",
        accept: [
          { id: "rewarm", text: "Rewarming vasodilation", match: ["rewarming", "vasodilation", "afterdrop", "vasodilatation"] },
          { id: "bleed", text: "Occult hemorrhage now unmasked", match: ["hemorrhage", "haemorrhage", "bleeding", "blood loss"] },
          { id: "cold", text: "Hypovolemia from cold diuresis", match: ["cold diuresis", "hypovolemia", "hypovolaemia", "dehydration"] },
          { id: "arrhythmia", text: "Arrhythmia such as atrial fibrillation", match: ["arrhythmia", "atrial fibrillation", "dysrhythmia"] },
          { id: "spinal", text: "Neurogenic shock from spinal cord injury", match: ["neurogenic", "spinal"] },
          { id: "k", text: "Hyperkalemia from rhabdomyolysis", match: ["hyperkalemia", "hyperkalaemia", "potassium", "rhabdomyolysis"] },
          { id: "ptx", text: "Tension pneumothorax", match: ["pneumothorax"] },
        ],
        explanation:
          "Cold causes vasoconstriction and diuresis that can hide blood loss. As he rewarms, vessels dilate and occult hemorrhage becomes apparent. A rising heart rate in a patient who was bradycardic from cold is a warning sign. Reassess for bleeding before blaming rewarming alone.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "hypothermia",
      },
    ],
    sources: [S.hypothermia, S.mills, S.atls],
    ...META,
  },

  /* 15 ------------------------------------------------------------------ */
  {
    id: "multiple-trauma-15",
    topic: "multiple-trauma",
    alsoTopics: ["abuse-domestic"],
    title: "Young woman who fell down the stairs",
    stem:
      "A 26-year-old woman says she fell down the stairs at home last night. Her partner brought her in and answers most questions for her. GCS 15. SpO2 is 97%. She has left lower rib tenderness, left upper quadrant tenderness and bruises of several colours on her upper arms, neck and back.",
    vitals: { pulse: "110/minute", resp: "22/minute", bp: "104/70 mmHg", weight: "58 kg" },
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "What features suggest intimate partner violence?",
        accept: [
          { id: "ages", text: "Bruises of different ages", match: ["different age", "various age", "different stage", "old bruise", "healing", "several colour", "different colour", "different color"] },
          { id: "pattern", text: "Injury pattern not consistent with the story", match: ["inconsistent", "not consistent", "does not match", "not match", "mechanism", "story"] },
          { id: "partner", text: "Partner answering for her or controlling the visit", match: ["partner", "controlling", "answer"] },
          { id: "delay", text: "Delay in presentation", match: ["delay", "delayed", "last night"] },
          { id: "central", text: "Injuries to the neck, trunk and upper arms", match: ["central", "neck", "upper arm", "grab", "trunk"] },
          { id: "strangle", text: "Neck bruising suggesting strangulation", match: ["strangulation", "choking", "strangled"] },
          { id: "repeat", text: "Repeat ED visits for injury", match: ["repeat", "prior visit", "previous visit"] },
        ],
        explanation:
          "A fall down stairs usually injures bony prominences and extremities. Bruises of different ages on the arms, neck and back suggest grabbing and repeated assaults. A partner who will not leave and answers for the patient is a recognized warning sign.",
        keyFeature: { topic: "abuse-domestic", n: 2 },
        source: "who-ipv",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "What steps do you take to identify and document all of her current and past injuries?",
        accept: [
          { id: "fullexam", text: "Complete head to toe exam with her fully undressed", match: ["head to toe", "full exam", "undressed", "complete exam", "full body"] },
          { id: "neck", text: "Examine the neck and ask about strangulation, and image the neck vessels if present", match: ["strangulation", "neck", "choking"] },
          { id: "photos", text: "Photographs or body diagrams with her consent", match: ["photo", "photograph", "diagram", "body map"] },
          { id: "old", text: "Review old charts and prior imaging", match: ["old chart", "prior imaging", "previous imaging", "old record", "prior visit", "previous visit", "old x ray"] },
          { id: "hcg", text: "Pregnancy test", match: ["pregnancy test", "hcg", "bhcg"] },
          { id: "ct", text: "CT of the abdomen for splenic injury", match: ["ct abdomen", "ct"] },
          { id: "xray", text: "Imaging of old deformities or tender areas for healing fractures", match: ["healing fracture", "old fracture"] },
        ],
        explanation:
          "Victims often disclose only part of their injuries. A full exam, attention to strangulation and a review of old visits reveal the pattern. Careful documentation with body maps or photographs helps her later if she chooses to report. A pregnancy test matters because violence often escalates in pregnancy.",
        keyFeature: { topic: "abuse-domestic", n: 3 },
        source: "who-ipv",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "What steps make a safe disclosure more likely?",
        accept: [
          { id: "alone", text: "Interview her alone, away from her partner", match: ["alone", "private", "separate", "without partner", "away from partner"] },
          { id: "interp", text: "Use a professional interpreter, never the partner", match: ["interpreter"] },
          { id: "direct", text: "Ask directly in a nonjudgmental way", match: ["nonjudgmental", "non judgmental", "direct", "empathic"] },
          { id: "confid", text: "Explain confidentiality and its limits", match: ["confidential", "confidentiality"] },
          { id: "pretext", text: "Use a routine reason such as imaging to separate them", match: ["bathroom", "x ray", "imaging", "pretext"] },
        ],
        explanation:
          "Disclosure is unlikely with the partner in the room. Create a routine reason to see her alone and ask plainly. Explain that what she tells you is confidential. The main limits are a child who may need protection and an imminent risk of serious harm or death.",
        keyFeature: { topic: "abuse-domestic", n: 4 },
        source: "who-ipv",
      },
      {
        id: "q4",
        kind: "single",
        update: "While waiting for CT she becomes pale and restless. HR 132, BP 94/80.",
        prompt: "Which of the following is the most appropriate action at this time?",
        options: [
          "Lorazepam 1 mg sublingual for agitation",
          "Metoprolol 5 mg IV for the tachycardia",
          "Proceed with CT as planned without monitoring",
          "Reassure her that the symptoms are anxiety about her partner",
          "Resuscitation room, blood, repeat eFAST, call trauma surgeon",
        ],
        correct: 4,
        explanation:
          "A narrowing pulse pressure, rising heart rate and restlessness signal hemorrhagic shock, here most likely from a delayed splenic bleed. She is no longer safe for CT. Return her to the resuscitation room, start blood, repeat the eFAST and call the trauma surgeon. Attributing the change to anxiety is a classic and dangerous error.",
        keyFeature: { topic: "multiple-trauma", n: 5 },
        source: "atls",
      },
    ],
    sources: [S.who, S.atls],
    ...META,
  },
];
