// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const AUTHOR = "Draft for review by Arjan Dhoot, MD";
const kf = (n: number) => ({ topic: "delirium-agitation", n });

/* Sources ---------------------------------------------------------------- */

const SRC_CCSMH: Source = {
  id: "ccsmh",
  citation: "Canadian Coalition for Seniors' Mental Health. National guidelines for seniors' mental health. The assessment and treatment of delirium. 2006, updated 2014.",
  url: "https://ccsmh.ca/wp-content/uploads/2016/03/2014-ccsmh-Guideline-Update-Delirium.pdf",
};
const SRC_4AT: Source = {
  id: "4at",
  citation: "Tieges Z, Maclullich AMJ, Anand A, et al. Diagnostic accuracy of the 4AT for delirium detection in older adults. Systematic review and meta-analysis. Age and Ageing 2021.",
  url: "https://pubmed.ncbi.nlm.nih.gov/33951145/",
};
const SRC_APPELBAUM: Source = {
  id: "appelbaum",
  citation: "Appelbaum PS. Assessment of patients' competence to consent to treatment. New England Journal of Medicine 2007.",
  url: "https://doi.org/10.1056/NEJMcp074045",
};
const SRC_BEERS: Source = {
  id: "beers-2023",
  citation: "American Geriatrics Society Beers Criteria Update Expert Panel. American Geriatrics Society 2023 updated AGS Beers Criteria for potentially inappropriate medication use in older adults. Journal of the American Geriatrics Society 2023.",
  url: "https://doi.org/10.1111/jgs.18372",
};
const SRC_MAUDSLEY: Source = {
  id: "maudsley",
  citation: "Taylor DM, Barnes TRE, Young AH. The Maudsley Prescribing Guidelines in Psychiatry. 14th edition. Wiley Blackwell. 2021.",
};
const SRC_GERSON: Source = {
  id: "gerson-beta-peds",
  citation: "Gerson R, Malas N, Feuer V, et al. Best practices for evaluation and treatment of agitated children and adolescents (BETA) in the emergency department. Consensus statement of the American Association for Emergency Psychiatry. Western Journal of Emergency Medicine 2019.",
  url: "https://pubmed.ncbi.nlm.nih.gov/30881565/",
};
const SRC_ATA: Source = {
  id: "ata-2016",
  citation: "Ross DS, Burch HB, Cooper DS, et al. 2016 American Thyroid Association guidelines for diagnosis and management of hyperthyroidism and other causes of thyrotoxicosis. Thyroid 2016.",
  url: "https://doi.org/10.1089/thy.2016.0229",
};
const SRC_GRAUS: Source = {
  id: "graus-2016",
  citation: "Graus F, Titulaer MJ, Balu R, et al. A clinical approach to diagnosis of autoimmune encephalitis. Lancet Neurology 2016.",
  url: "https://doi.org/10.1016/S1474-4422(15)00401-9",
};
const SRC_LEJUSTE: Source = {
  id: "lejuste-2016",
  citation: "Lejuste F, Thomas L, Picard G, et al. Neuroleptic intolerance in patients with anti-NMDAR encephalitis. Neurology Neuroimmunology and Neuroinflammation 2016.",
  url: "https://pubmed.ncbi.nlm.nih.gov/27606355/",
};

const SRC_SOYKA: Source = {
  id: "soyka-2017",
  citation: "Soyka M. Treatment of benzodiazepine dependence. New England Journal of Medicine 2017.",
  url: "https://doi.org/10.1056/NEJMra1611832",
};
const SRC_CAM: Source = {
  id: "cam",
  citation: "Inouye SK, van Dyck CH, Alessi CA, et al. Clarifying confusion. The confusion assessment method. A new method for detection of delirium. Annals of Internal Medicine 1990.",
  url: "https://doi.org/10.7326/0003-4819-113-12-941",
};
const SRC_INOUYE_2006: Source = {
  id: "inouye-2006",
  citation: "Inouye SK. Delirium in older persons. New England Journal of Medicine 2006.",
  url: "https://pubmed.ncbi.nlm.nih.gov/16540616/",
};
const SRC_BETA_DEESC: Source = {
  id: "beta-deesc",
  citation: "Richmond JS, Berlin JS, Fishkind AB, et al. Verbal de-escalation of the agitated patient. Consensus statement of the American Association for Emergency Psychiatry Project BETA De-escalation Workgroup. Western Journal of Emergency Medicine 2012.",
  url: "https://pubmed.ncbi.nlm.nih.gov/22461917/",
};
const SRC_BETA_PHARM: Source = {
  id: "beta-pharm",
  citation: "Wilson MP, Pepper D, Currier GW, et al. The psychopharmacology of agitation. Consensus statement of the American Association for Emergency Psychiatry Project BETA Psychopharmacology Workgroup. Western Journal of Emergency Medicine 2012.",
  url: "https://pubmed.ncbi.nlm.nih.gov/22461918/",
};
const SRC_BC_HCCA: Source = {
  id: "bc-hcca",
  citation: "Health Care (Consent) and Care Facility (Admission) Act, RSBC 1996, c 181. Province of British Columbia. 1996, as amended.",
  url: "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96181_01",
};
const SRC_VILSTRUP: Source = {
  id: "aasld-easl-he",
  citation: "Vilstrup H, Amodio P, Bajaj J, et al. Hepatic encephalopathy in chronic liver disease. 2014 practice guideline by the American Association for the Study of Liver Diseases and the European Association for the Study of the Liver. Hepatology 2014.",
  url: "https://doi.org/10.1002/hep.27210",
};
const SRC_NS_PDA: Source = {
  id: "ns-pda",
  citation: "Personal Directives Act, SNS 2008, c 8. Province of Nova Scotia. 2008, as amended.",
  url: "https://www.canlii.org/en/ns/laws/stat/sns-2008-c-8/latest/sns-2008-c-8.html",
};
const SRC_CCQ: Source = {
  id: "ccq",
  citation: "Civil Code of Québec, CQLR c CCQ-1991, articles 11 to 16. Province of Quebec. 1991, as amended.",
  url: "https://www.legisquebec.gouv.qc.ca/en/document/cs/CCQ-1991",
};

const SRC_GALLAGHER: Source = {
  id: "gallagher-2007",
  citation: "Gallagher R. Opioid-induced neurotoxicity. Canadian Family Physician 2007.",
  url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC1949075/",
};
const SRC_BERGINK: Source = {
  id: "bergink-2016",
  citation: "Bergink V, Rasgon N, Wisner KL. Postpartum psychosis. Madness, mania, and melancholia in motherhood. American Journal of Psychiatry 2016.",
  url: "https://doi.org/10.1176/appi.ajp.2016.16040454",
};
const SRC_BC_MHA: Source = {
  id: "bc-mha",
  citation: "Mental Health Act, RSBC 1996, c 288. Province of British Columbia. 1996, as amended.",
  url: "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96288_01",
};
const SRC_KNOX: Source = {
  id: "knox-2012",
  citation: "Knox DK, Holloman GH Jr. Use and avoidance of seclusion and restraint. Consensus statement of the American Association for Emergency Psychiatry Project BETA Seclusion and Restraint Workgroup. Western Journal of Emergency Medicine 2012.",
  url: "https://pubmed.ncbi.nlm.nih.gov/22461919/",
};

export const DELIRIUM_AGITATION_S34: Samp[] = [
  /* 16 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-16",
    topic: "delirium-agitation",
    title: "Sleepy and not herself",
    stem: "An 86-year-old woman is brought to the emergency department by her son because she has been sleepy and not herself for 3 days. She sits quietly, answers slowly and dozes off in the middle of sentences. Her son says she lives alone, manages her own pills and banking, and finished the newspaper crossword every day until last week. Eight days ago her family physician started pregabalin 150 mg twice daily for postherpetic neuralgia. She also takes amlodipine and has chronic kidney disease with a baseline eGFR of 24 mL/minute. She is oriented to place but not to the date. She cannot recite the months of the year backward past October. She recalls one of three words at 5 minutes. There is no focal neurological deficit. Capillary glucose is 6.1 mmol/L.",
    vitals: { temperature: "36.8°C oral", pulse: "72/minute", resp: "14/minute", bp: "138/76 mmHg", o2sat: "96% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following findings best distinguishes delirium from dementia in this patient?",
        options: ["Age of 86 years with kidney disease", "Decline from an intact baseline in days", "Disorientation to the current date", "Poor recall of three words at 5 minutes", "Slow speech with long pauses"],
        correct: 1,
        explanation: "Her son describes a woman who ran her own affairs and did the crossword until last week, and who changed over 3 days. An acute change from a known baseline, together with inattention on the months backward, is what defines delirium. Disorientation to the date and poor word recall occur in both delirium and dementia, so they cannot separate them. Advanced age and kidney disease are risk factors, not distinguishing features. Slow speech is also seen with depression and with dementia.",
        keyFeature: kf(1),
        source: "ccsmh",
      },
      {
        id: "q2",
        kind: "single",
        update: "Sodium is 138 mmol/L, calcium 2.34 mmol/L and creatinine 168 umol/L, unchanged from her baseline. The CBC, urinalysis and chest radiograph are normal.",
        prompt: "Which of the following is the most likely cause of her current presentation?",
        options: ["Hyponatremia from reduced oral intake", "Major depression with psychomotor slowing", "Occult urinary tract infection", "Pregabalin accumulation in kidney disease", "Progression of an undiagnosed dementia"],
        correct: 3,
        explanation: "Pregabalin is cleared almost entirely by the kidneys, and with an eGFR of 24 mL/minute her dose of 300 mg a day is about double the usual maximum of 150 mg a day for this level of function. Sedation and confusion that began within days of starting it fit accumulation. The 2023 Beers Criteria advise reducing the dose of gabapentinoids when kidney function is reduced. Her sodium and urinalysis are normal. Depression and dementia do not produce a change over 3 days with drowsiness and inattention.",
        keyFeature: kf(2),
        source: "beers-2023",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate management of her delirium now?",
        options: ["Change pregabalin to gabapentin 300 mg TID", "haloperidol 0.5 mg PO twice daily", "Hold pregabalin and treat pain otherwise", "quetiapine 25 mg PO at bedtime", "Start donepezil 5 mg PO daily"],
        correct: 2,
        explanation: "Treating delirium means removing its cause, so the pregabalin is held and her neuralgia is managed with measures that do not depend on kidney clearance, such as a topical agent. Gabapentin is also renally cleared and sedating, so switching to it repeats the problem. Her delirium is hypoactive and she is not distressed or unsafe, so an antipsychotic such as haloperidol or quetiapine adds sedation without benefit. The Canadian Coalition for Seniors' Mental Health does not recommend cholinesterase inhibitors to treat delirium.",
        keyFeature: kf(2),
        source: "ccsmh",
      },
      {
        id: "q4",
        kind: "single",
        update: "She says she wants to go home tonight. When asked, she cannot say what could happen if she is alone at home while this drowsy, and repeats that she is fine.",
        prompt: "Which of the following best describes her capacity to make this discharge decision?",
        options: ["Capable, as she expresses a clear choice", "Capable, as she knows she is in hospital", "Incapable, as delirium removes capacity", "Incapable, as she cannot weigh the risks", "Undetermined until psychiatry assesses her"],
        correct: 3,
        explanation: "Capacity is specific to the decision and needs four abilities: to express a choice, to understand the information, to appreciate how it applies to her, and to reason about the options. She states a choice, but she cannot say what could happen if she goes home in this state, so she fails appreciation and reasoning. Knowing where she is shows orientation, not capacity. A diagnosis of delirium does not by itself remove capacity. The treating emergency physician can make this assessment without waiting for psychiatry.",
        keyFeature: kf(5),
        source: "appelbaum",
      },
    ],
    sources: [SRC_CCSMH, SRC_BEERS, SRC_APPELBAUM],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 17 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-17",
    topic: "delirium-agitation",
    title: "Drooling and drowsy at the group home",
    stem: "A 38-year-old woman is brought to the emergency department by staff from her group home for 2 days of confusion. She has schizophrenia, stable for 6 years on clozapine 400 mg at bedtime. She smoked 25 cigarettes a day until she moved into the smoke-free home 12 days ago. Staff say she has been drooling, fell asleep twice at meals and yesterday could not find her own room. When stressed she sometimes hears voices, and she did so last night. She is drowsy but rousable, drifts off during questions and cannot spell WORLD backward. There are brief jerks of both arms. Muscle tone is normal. Capillary glucose is 5.4 mmol/L.",
    vitals: { temperature: "37.1°C oral", pulse: "118/minute", resp: "16/minute", bp: "96/58 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following findings best indicates delirium rather than a relapse of her schizophrenia?",
        options: ["Auditory hallucinations when stressed", "Drowsiness with impaired attention", "Flat affect with little speech", "Paranoid ideas about her caregivers", "Withdrawal from group activities"],
        correct: 1,
        explanation: "A reduced level of arousal and inattention, shown by drowsiness, drifting off during questions and failing WORLD backward, are core features of delirium and are not typical of a psychotic relapse. Voices under stress are part of her usual illness. Flat affect, paranoid ideas and social withdrawal are positive or negative symptoms of schizophrenia and occur with a clear sensorium. Labelling her confusion as relapse risks missing a medical cause.",
        keyFeature: kf(1),
        source: "ccsmh",
      },
      {
        id: "q2",
        kind: "single",
        update: "Neutrophils are 5.8 x 10^9/L. Sodium is 139 mmol/L. Troponin and creatine kinase are normal.",
        prompt: "Which of the following is the most likely cause of her presentation?",
        options: ["Agranulocytosis with sepsis from clozapine", "Neuroleptic malignant syndrome", "Nicotine withdrawal delirium", "Rising clozapine level after smoking stopped", "Water intoxication with hyponatremia"],
        correct: 3,
        explanation: "Chemicals in tobacco smoke induce CYP1A2, the main enzyme that clears clozapine. When a heavy smoker stops, induction wanes over about 1 to 2 weeks and clozapine levels can rise by half or more on the same dose. Sedation, drooling, tachycardia, low blood pressure, myoclonus and delirium 12 days after she stopped fit toxicity. Her neutrophils are normal, her sodium is normal, and she has no fever, rigidity or raised creatine kinase to suggest neuroleptic malignant syndrome. Nicotine withdrawal causes irritability and craving, not myoclonus and drooling.",
        keyFeature: kf(2),
        source: "maudsley",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate next step in managing her clozapine?",
        options: ["Add glycopyrrolate for the hypersalivation", "Continue clozapine with nicotine patches", "Hold clozapine and send a drug level", "Restart clozapine at 400 mg in 2 days", "Switch to olanzapine 10 mg PO nightly"],
        correct: 2,
        explanation: "The drug is held while she is toxic and a clozapine level confirms the cause and guides the new dose, which is usually reduced by about a third to a half after smoking stops. Nicotine patches do not induce CYP1A2, because the inducers are the hydrocarbons in smoke, so continuing the same dose leaves the level high. Restarting at 400 mg repeats the toxicity, and after more than 48 hours off clozapine it must be titrated up again from a low dose. Glycopyrrolate treats one symptom only. Switching antipsychotics is a psychiatric decision for later.",
        keyFeature: kf(2),
        source: "maudsley",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following is the most important safety measure while she remains in the department?",
        options: ["Four point restraints to prevent falls", "Hallway bed near the nursing station", "Seclusion room with the door locked", "Security guard posted at the doorway", "Sitter with seizure precautions"],
        correct: 4,
        explanation: "Clozapine lowers the seizure threshold in a dose related way, and her myoclonus, drowsiness and drooling put her at risk of a seizure, a fall and aspiration. Constant observation with suction and padded rails lets staff act at once. Restraints add injury and aspiration risk in a drowsy patient and are not needed when she is not violent. A hallway bed gives only intermittent observation. Seclusion and a security guard address violence, which she has not shown, and leave her unobserved medically.",
        keyFeature: kf(3),
        source: "maudsley",
      },
    ],
    sources: [SRC_CCSMH, SRC_MAUDSLEY],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 18 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-18",
    topic: "delirium-agitation",
    title: "Head banging in a boy who speaks few words",
    stem: "A 13-year-old boy with autism spectrum disorder is brought to the emergency department by his mother for 2 days of screaming, head banging and hitting the right side of his face. He speaks a few words and uses a tablet to communicate. He usually settles with his weighted blanket and music. He takes risperidone 0.5 mg twice daily. He has refused solid food for 2 days but drinks juice. In the busy triage area he is rocking, covering his ears and has just struck a nurse. His mother is with him and can usually calm him.",
    vitals: { temperature: "37.9°C tympanic", pulse: "124/minute", resp: "22/minute", bp: "118/70 mmHg", o2sat: "99% on room air", weight: "45 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate first step to reduce his agitation?",
        options: ["Ask security to stand at his bedside", "Hold him still for an IM injection", "Move him to a quiet room with his mother", "olanzapine 5 mg IM in the triage area", "Place him in four point restraints"],
        correct: 2,
        explanation: "He is covering his ears in a noisy triage area, and he has a parent and comfort items that usually settle him. Pediatric consensus advises non-drug de-escalation first, with less stimulation and his caregiver, before any medication or restraint. Holding him for an injection or restraining him escalates distress and risks injury to him and staff. Security at the bedside adds another stranger and more stimulation. An IM antipsychotic in triage skips the step most likely to work.",
        keyFeature: kf(3),
        source: "gerson-beta-peds",
      },
      {
        id: "q2",
        kind: "single",
        update: "In a quiet room with music and his blanket he stops screaming but still presses his right cheek.",
        prompt: "Which of the following is the most important next step in assessing his change in behaviour?",
        options: ["Arrange a CT head without contrast", "Examine him for a source of pain", "Increase his daily risperidone dose", "Request urgent psychiatry consultation", "Send a urine drug screen"],
        correct: 1,
        explanation: "Youth with limited speech often show pain as agitation or self-injury. His blows are aimed at one side of his face, he has stopped eating solids and he has a low-grade fever, which point to a painful source such as a dental abscess or otitis. A careful examination with his mother's help comes before any other test. CT head is not needed without trauma or focal signs. Raising his risperidone or calling psychiatry treats behaviour without finding its cause. A drug screen is unlikely to help in this setting.",
        keyFeature: kf(2),
        source: "gerson-beta-peds",
      },
      {
        id: "q3",
        kind: "single",
        update: "He has a tender swelling over the right mandible and a fluctuant abscess beside a lower molar. He needs drainage but screams when approached. He will take liquid medicine from his mother.",
        prompt: "Which of the following is the most appropriate medication to settle him for the drainage?",
        options: ["haloperidol 2.5 mg IM", "ketamine 180 mg IM", "lorazepam 2 mg IM", "olanzapine 10 mg IM", "risperidone 0.5 mg PO"],
        correct: 4,
        explanation: "He will take oral medicine, and the pediatric consensus prefers oral before IM. For youth with autism it suggests an extra dose of the child's regular medicine, because they are prone to adverse effects such as paradoxical disinhibition with benzodiazepines. An extra 0.5 mg of risperidone brings his day to 1.5 mg, within the adolescent maximum of 2 to 3 mg. Ketamine at 4 mg/kg, or 180 mg for 45 kg, is for dangerous agitation when oral treatment fails. IM haloperidol or olanzapine is not needed in a child who accepts oral medicine.",
        keyFeature: kf(4),
        source: "gerson-beta-peds",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following best supports safe care for him during the rest of his stay?",
        options: ["Assign a different nurse every few hours", "Keep his mother and tablet with him", "Keep the lights bright for observation", "Place him in a shared room near others", "Remove his weighted blanket for safety"],
        correct: 1,
        explanation: "His mother knows his triggers and calming strategies, and his tablet is how he communicates, so keeping both with him lowers the chance of another violent episode and helps staff understand him. Changing nurses often adds unfamiliar faces. Bright light and a shared room increase the sensory load that set him off in triage. His weighted blanket is one of the tools that settles him, and removing it takes away a proven calming aid.",
        keyFeature: kf(3),
        source: "gerson-beta-peds",
      },
    ],
    sources: [SRC_GERSON],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 19 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-19",
    topic: "delirium-agitation",
    title: "Shouting at the television",
    stem: "A 44-year-old woman is brought to the emergency department by her husband for 1 day of agitation and confusion. She has Graves disease and stopped methimazole 2 months ago because of cost. For 3 days she has had vomiting, diarrhea, fever and a cough. Tonight she shouted that the television was talking to her and she is pulling at her clothes. She has no psychiatric history. She is tremulous, sweating and restless, and cannot say the days of the week backward. She has a diffuse goitre and lid lag. Her chest is clear and there is no leg edema. The monitor shows atrial fibrillation. Capillary glucose is 7.9 mmol/L.",
    vitals: { temperature: "39.6°C oral", pulse: "156/minute irregular", resp: "26/minute", bp: "148/62 mmHg", o2sat: "95% on room air", weight: "62 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following features most strongly favours delirium over a primary psychotic illness?",
        options: ["Auditory hallucinations from the television", "Belief that she is being watched", "Poor attention to days of the week backward", "Restlessness and pulling at her clothing", "Shouting and hostility toward her family"],
        correct: 2,
        explanation: "Inattention is the core feature of delirium, and she cannot keep her attention on a simple sequence such as the days backward. Hallucinations, paranoid beliefs, restlessness and hostility can all occur in primary psychosis and in delirium, so they do not separate the two. Her fever, tachycardia and atrial fibrillation also point to a medical cause, as does a first episode with no psychiatric history.",
        keyFeature: kf(1),
        source: "ata-2016",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is her Burch-Wartofsky Point Scale score?",
        options: ["80", "90", "100", "110", "120"],
        correct: 2,
        explanation: "Temperature 39.6°C scores 25. Delirium and psychosis are moderate central nervous system effects and score 20. Vomiting and diarrhea score 10. A heart rate of 140/minute or more scores 25. Heart failure scores 0, because her chest is clear and she has no edema. Atrial fibrillation scores 10 and a precipitant, here stopping methimazole with an infection, scores 10. The total is 25 + 20 + 10 + 25 + 0 + 10 + 10 = 100. A score of 45 or more is highly suggestive of thyroid storm. Scoring her confusion as mild agitation gives 90.",
        keyFeature: kf(2),
        source: "ata-2016",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following treatments should be given only after the thionamide has been started?",
        options: ["acetaminophen 650 mg PR", "hydrocortisone 100 mg IV", "normal saline 1 L IV", "potassium iodide 5 drops PO", "propranolol 60 mg PO"],
        correct: 3,
        explanation: "Iodine blocks release of stored thyroid hormone, but given first it can supply substrate for new hormone synthesis. The 2016 American Thyroid Association guideline advises giving it at least 1 hour after propylthiouracil or methimazole. Propranolol, glucocorticoid, fluids and acetaminophen do not depend on the thionamide and are started at once. Acetaminophen is preferred over salicylates, which can free thyroid hormone from its binding proteins.",
        keyFeature: kf(2),
        source: "ata-2016",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following investigations is most important to identify the precipitant of her crisis?",
        options: ["Chest radiograph", "CT head without contrast", "Free thyroxine level", "Thyroid ultrasound", "Urine drug screen"],
        correct: 0,
        explanation: "Thyroid storm is usually triggered by an event, and she has 3 days of cough and fever, so a chest radiograph looks for the pneumonia that needs treatment alongside the storm. A free thyroxine level confirms thyrotoxicosis but does not identify the trigger, and the level does not separate storm from uncomplicated thyrotoxicosis. CT head is not needed without trauma or focal signs. Thyroid ultrasound does not change emergency care. A drug screen is less likely to help given the clear history.",
        keyFeature: kf(2),
        source: "ata-2016",
      },
    ],
    sources: [SRC_ATA],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 20 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-20",
    topic: "delirium-agitation",
    title: "A teenager who thinks her parents are impostors",
    stem: "A 16-year-old girl is brought to the emergency department by her parents for 10 days of strange behaviour. It began a week after a flu-like illness with headache. She has become fearful, insists her parents are impostors and sleeps 2 hours a night. Over 2 days her speech has shrunk to a few words, and her mother has seen chewing movements of her lips and tongue lasting minutes. This morning she had a generalized seizure. She has no psychiatric history, and a urine drug screen at a walk-in clinic last week was negative. She stares, follows some commands and does not know the date.",
    vitals: { temperature: "37.8°C oral", pulse: "128/minute", resp: "18/minute", bp: "152/94 mmHg", o2sat: "98% on room air", weight: "54 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following features most strongly suggests a medical cause rather than primary psychosis?",
        options: ["Belief that her parents are impostors", "Fearfulness and very little sleep", "Onset during the teenage years", "Orofacial movements and a seizure", "Withdrawal from her friends"],
        correct: 3,
        explanation: "Orofacial dyskinesia and a seizure are neurological signs that primary psychosis does not produce, and with rapidly failing speech and disorientation they point to encephalitis. Delusions such as believing her parents are impostors, fearfulness, insomnia and withdrawal occur in both. Adolescence is a common age of onset for both primary psychosis and autoimmune encephalitis, so age does not separate them.",
        keyFeature: kf(1),
        source: "graus-2016",
      },
      {
        id: "q2",
        kind: "menu",
        prompt: "Which of the following investigations are most appropriate to establish the cause of her illness?",
        options: ["Carotid Doppler ultrasound", "Electroencephalogram", "Lumbar puncture for CSF analysis", "MRI of the brain", "Nerve conduction studies", "Pelvic ultrasound", "Serum lithium level", "Transthoracic echocardiogram"],
        select: 4,
        correct: [1, 2, 3, 5],
        explanation: "Suspected autoimmune encephalitis is assessed with MRI to exclude other causes, EEG for slowing or seizures, and CSF for pleocytosis and NMDA receptor antibodies. Anti-NMDA receptor encephalitis in young women is often linked to an ovarian teratoma, so pelvic imaging is part of the workup. Carotid Doppler and echocardiography look for embolic stroke, which does not fit a subacute psychiatric onset. Nerve conduction studies test peripheral nerves. She takes no lithium.",
        keyFeature: kf(2),
        source: "graus-2016",
      },
      {
        id: "q3",
        kind: "single",
        update: "MRI is normal. CSF has 28 white cells x 10^6/L, mostly lymphocytes, with normal glucose, and HSV PCR is negative. EEG shows extreme delta brush. Pelvic ultrasound shows a 4 cm ovarian mass containing fat and calcification.",
        prompt: "Which of the following is the most likely diagnosis for this patient?",
        options: ["Acute disseminated encephalomyelitis", "Anti-NMDA receptor encephalitis", "Early-onset schizophrenia", "Herpes simplex encephalitis", "Wilson disease with psychosis"],
        correct: 1,
        explanation: "Psychiatric symptoms followed by speech decline, dyskinesia, seizures and autonomic signs, with lymphocytic CSF, extreme delta brush on EEG and an ovarian teratoma, fit anti-NMDA receptor encephalitis. Extreme delta brush is a pattern seen almost only in this disease. Acute disseminated encephalomyelitis causes multifocal white matter lesions on MRI, and hers is normal. HSV PCR is negative. Schizophrenia does not cause seizures, CSF pleocytosis or a tumour. Wilson disease does not explain the CSF or EEG findings.",
        keyFeature: kf(2),
        source: "graus-2016",
      },
      {
        id: "q4",
        kind: "single",
        update: "While awaiting admission she becomes agitated, strikes at her mother and pulls at her IV. Calm talk with her parents at the bedside has not settled her.",
        prompt: "Which of the following is the most appropriate medication for her agitation?",
        options: ["droperidol 5 mg IM", "haloperidol 5 mg IM", "ketamine 50 mg IV", "lorazepam 2 mg IV", "olanzapine 10 mg IM"],
        correct: 3,
        explanation: "Patients with anti-NMDA receptor encephalitis often react badly to antipsychotics, with fever, rigidity, rhabdomyolysis and worsening dyskinesia that mimic neuroleptic malignant syndrome. A benzodiazepine calms her and also treats the seizures she has already had. Lorazepam 2 mg IV is a standard adolescent dose and well under a ceiling of 0.1 mg/kg, which is 5.4 mg for 54 kg. Droperidol, haloperidol and olanzapine carry the antipsychotic risk. Ketamine blocks the same NMDA receptor the antibodies target and can worsen psychosis.",
        keyFeature: kf(4),
        source: "lejuste-2016",
      },
    ],
    sources: [SRC_GRAUS, SRC_LEJUSTE],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 21 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-21",
    topic: "delirium-agitation",
    title: "Frightened and shaking after a long weekend",
    stem: "A 72-year-old woman is brought to the emergency department by her daughter for 2 days of confusion, shaking and fear. For 15 years she has taken lorazepam 1 mg in the afternoon and 2 mg at bedtime. Her prescription ran out 4 days ago over a long weekend. She has one glass of wine a week. Her only other medication is ramipril. She is sweating, has a coarse tremor of both hands, startles at every noise and says there are dogs in the room. She does not know the month and fails to count backward from 20. There is no clonus. Capillary glucose is 6.6 mmol/L.",
    vitals: { temperature: "37.9°C oral", pulse: "112/minute", resp: "20/minute", bp: "168/94 mmHg", o2sat: "97% on room air", weight: "60 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most likely cause of her delirium?",
        options: ["Alcohol withdrawal delirium", "Anticholinergic toxicity", "Lewy body dementia", "Serotonin toxicity", "Withdrawal from lorazepam"],
        correct: 4,
        explanation: "Abrupt loss of a benzodiazepine taken daily for 15 years, followed within days by tremor, sweating, startle, hallucinations, tachycardia and confusion, is sedative withdrawal. One glass of wine a week is too little for alcohol withdrawal. Anticholinergic toxicity causes dry skin, not sweating. She takes no serotonergic drug and has no clonus. Lewy body dementia progresses over months and does not explain an abrupt change after her pills ran out.",
        keyFeature: kf(2),
        source: "soyka-2017",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate first treatment for her?",
        options: ["lorazepam 1 mg IV", "melatonin 3 mg PO", "olanzapine 5 mg PO", "phenytoin 1 g IV", "quetiapine 25 mg PO"],
        correct: 0,
        explanation: "Sedative withdrawal is treated by giving back a benzodiazepine, which restores the missing GABA effect and prevents seizures. Lorazepam 1 mg IV can be repeated until she settles, and her usual 3 mg a day can then be resumed by mouth. Olanzapine and quetiapine lower the seizure threshold and do not treat withdrawal. Phenytoin does not prevent or stop withdrawal seizures. Melatonin has no role in active withdrawal.",
        keyFeature: kf(2),
        source: "soyka-2017",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following findings most clearly indicates delirium rather than anxiety from missing her medication?",
        options: ["Failing to count back from 20", "Fear and a sense of dread", "Insomnia for the past two nights", "Rapid pulse with sweating", "Startle response to noise"],
        correct: 0,
        explanation: "Inattention is the cardinal feature of delirium in the Confusion Assessment Method, and failing a simple sequence such as counting backward from 20 shows it. Fear, dread, insomnia, a rapid pulse, sweating and a heightened startle all occur in anxiety and in early withdrawal without any disturbance of attention or awareness. Her disorientation to the month adds to the evidence of delirium.",
        keyFeature: kf(1),
        source: "cam",
      },
      {
        id: "q4",
        kind: "single",
        update: "Her tremor and hallucinations settle over 24 hours on scheduled lorazepam. She is oriented and attentive the next day.",
        prompt: "Which of the following is the most appropriate long-term plan for her lorazepam?",
        options: ["Continue the same dose with no review", "Gradual taper over weeks to months", "Stop it now that the delirium has cleared", "Switch to zopiclone 7.5 mg at bedtime", "Taper to zero over 3 days in hospital"],
        correct: 1,
        explanation: "Long-term benzodiazepine use in an older adult raises the risk of falls, confusion and further withdrawal, so a slow taper over weeks to months, with support, is the safest course. Stopping now or over 3 days repeats the abrupt withdrawal that caused this delirium. Zopiclone acts on the same receptor and carries the same risks in older adults. Continuing unchanged leaves her exposed to the next missed refill.",
        keyFeature: kf(2),
        source: "soyka-2017",
      },
    ],
    sources: [SRC_SOYKA, SRC_CAM],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 22 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-22",
    topic: "delirium-agitation",
    title: "A knife in the waiting room",
    stem: "A 27-year-old man walks into the emergency department waiting room at 02:00 saying people are following him to kill him. He has used crystal methamphetamine for 4 days without sleep. He is pacing, sweating and shouting. A triage nurse saw a folding knife in his hand before he put it in his pocket. Other patients, including a mother with 2 young children, are seated nearby. When the nurse asks his name from a distance, he answers and says he knows he is in a hospital. He can give the date. His speech is rapid but coherent.",
    vitals: { temperature: "37.4°C tympanic", pulse: "122/minute", resp: "20/minute", bp: "158/96 mmHg", o2sat: "98% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate immediate action?",
        options: ["Ask him to hand the knife to the nurse", "Direct him to a closed exam room alone", "Have two staff hold him for a search", "olanzapine 10 mg IM while he is distracted", "Summon security and move others away"],
        correct: 4,
        explanation: "A paranoid man with a knife in a room full of bystanders is a threat to everyone present, so the first step is to move patients and staff out of reach and bring trained security, with police if needed, to secure the weapon. Asking him to hand over the knife or having staff hold him brings untrained people within reach of a blade. A closed room isolates him with a weapon and may trap staff who enter. An injection while he is armed puts the nurse at risk and is not the first priority.",
        keyFeature: kf(3),
        source: "beta-deesc",
      },
      {
        id: "q2",
        kind: "single",
        update: "Security secures the knife without injury. He agrees to talk with you in an interview room with an open door and security nearby.",
        prompt: "Which of the following best reflects recommended technique for verbal de-escalation with him?",
        options: ["Challenge his belief that he is followed", "Let several staff members talk at once", "Promise that he can leave once calm", "Respect a space of two arm lengths", "Stand close to show you are in control"],
        correct: 3,
        explanation: "The Project BETA de-escalation consensus lists respect for personal space, about two arm lengths, as the first step, because crowding feels threatening to a paranoid person. One person should speak, since several voices confuse and provoke. Arguing with a delusion escalates, and the advice is to agree or agree to disagree. A promise that cannot be kept erodes trust when it is broken. Standing close is provocative and places the clinician within striking range.",
        keyFeature: kf(3),
        source: "beta-deesc",
      },
      {
        id: "q3",
        kind: "single",
        update: "He says he wants help to feel calmer. He is still pacing but agrees to take a pill.",
        prompt: "Which of the following is the most appropriate medication for him now?",
        options: ["lorazepam 2 mg PO", "methotrimeprazine 25 mg IM", "olanzapine 10 mg IM", "quetiapine 100 mg PO", "zuclopenthixol acetate 50 mg IM"],
        correct: 0,
        explanation: "The Project BETA psychopharmacology consensus names benzodiazepines as first-line agents for agitation from stimulant intoxication, and it prefers the oral route when the patient cooperates. Olanzapine IM is unnecessary when he will take a tablet. Quetiapine carries a high risk of orthostatic hypotension in the emergency department. Methotrimeprazine is strongly anticholinergic and hypotensive. Zuclopenthixol acetate lasts 2 to 3 days and is not a first choice for undifferentiated or drug-induced agitation.",
        keyFeature: kf(4),
        source: "beta-pharm",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following findings argues most strongly against delirium in this patient?",
        options: ["Four days without any sleep", "Orientation and coherent speech", "Paranoid belief of being followed", "Pulse of 122/minute", "Sweating and constant pacing"],
        correct: 1,
        explanation: "He knows where he is, gives the date, answers coherently and holds his attention on the conversation, so he does not meet criteria for delirium, and his paranoia fits a stimulant psychosis with a clear sensorium. Sleep loss, tachycardia, sweating and pacing are signs of stimulant toxicity that occur with or without delirium. Paranoid beliefs can occur in both psychosis and delirium, so they do not separate them.",
        keyFeature: kf(1),
        source: "beta-pharm",
      },
    ],
    sources: [SRC_BETA_DEESC, SRC_BETA_PHARM],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 23 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-23",
    topic: "delirium-agitation",
    title: "Must go home to feed the cat",
    stem: "You are working in an emergency department in British Columbia. An 80-year-old man is brought in by ambulance with 3 days of cough and fever and 1 day of confusion. His neighbour of 30 years called the ambulance. He keeps pulling off his oxygen and says he must go home to feed his cat. He cannot keep track of your questions and his speech rambles from topic to topic. His wife died last year. His son lives nearby and visits weekly. His daughter lives in Ontario and they have not spoken in 5 years. He has no representative, personal guardian or advance directive. A chest radiograph shows right lower lobe consolidation.",
    vitals: { temperature: "38.7°C oral", pulse: "112/minute", resp: "28/minute", bp: "102/60 mmHg", o2sat: "88% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following combinations of features satisfies the Confusion Assessment Method for delirium?",
        options: ["Acute onset and altered consciousness only", "Acute onset, disorientation and hallucinations", "Acute onset, inattention and disorganized thinking", "Altered consciousness and disorganized thinking", "Inattention and altered consciousness only"],
        correct: 2,
        explanation: "The Confusion Assessment Method needs both acute onset or fluctuating course and inattention, plus either disorganized thinking or an altered level of consciousness. He changed over a day, cannot keep track of questions and rambles from topic to topic, so he meets it. Disorientation and hallucinations are common but are not criteria. Every other combination listed lacks acute onset, inattention or both, which are required.",
        keyFeature: kf(1),
        source: "cam",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Under the British Columbia Health Care (Consent) and Care Facility (Admission) Act, which of the following should be chosen as his temporary substitute decision maker?",
        options: ["Daughter living in Ontario", "Neighbour of 30 years", "Public Guardian and Trustee", "Son who visits him every week", "Treating emergency physician"],
        correct: 3,
        explanation: "With no spouse, representative or guardian, the provider chooses the first qualified person in the list in section 16, and a child comes before other relatives and close friends. A temporary substitute decision maker must have been in contact with the adult in the preceding 12 months, so his daughter does not qualify after 5 years without contact. The neighbour, as a close friend, ranks below his son. The Public Guardian and Trustee is used only when no qualified person is available. The physician cannot consent for the patient.",
        keyFeature: kf(5),
        source: "bc-hcca",
      },
      {
        id: "q3",
        kind: "single",
        update: "His son cannot be reached by phone. His saturation falls to 84% and he refuses antibiotics, saying he only wants to go home.",
        prompt: "Which of the following is the most appropriate action regarding his treatment?",
        options: ["Apply to court for a guardianship order", "Certify him under the Mental Health Act", "Delay treatment until his son is reached", "Honour his refusal and send him home", "Treat now as emergency health care"],
        correct: 4,
        explanation: "Section 12 allows health care without consent when it is needed without delay to preserve life or prevent serious harm, the adult appears incapable, no guardian or representative is available, and where practicable a second provider confirms. Falling saturation with pneumonia and delirium meets that test, and his refusal is not a capable one. Waiting for his son or a court order risks death. The Mental Health Act addresses admission for a mental disorder in a designated facility and does not authorize treatment of his pneumonia.",
        keyFeature: kf(5),
        source: "bc-hcca",
      },
      {
        id: "q4",
        kind: "single",
        update: "His son arrives 2 hours later and agrees to act as his decision maker.",
        prompt: "Which of the following must guide his son's decisions about further treatment?",
        options: ["Consult his sister before any decision", "Decide as he would for himself", "Defer to the treating physician's view", "Follow his father's current request to go home", "Follow wishes his father expressed when capable"],
        correct: 4,
        explanation: "Section 19 requires a temporary substitute decision maker to consult the adult as far as possible and to comply with instructions or wishes the adult expressed while capable. Only when those are unknown does the best interests test apply, which weighs his current wishes as one factor among several. His present request to go home is made while delirious and is not binding. The son must not substitute his own preferences, simply defer to the physician or seek his sister's approval.",
        keyFeature: kf(5),
        source: "bc-hcca",
      },
    ],
    sources: [SRC_CAM, SRC_BC_HCCA],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 24 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-24",
    topic: "delirium-agitation",
    title: "Up all night and striking out",
    stem: "You are working in an emergency department in Nova Scotia. A 61-year-old man with alcohol-related cirrhosis is brought in by his common-law partner of 12 years, who lives with him, for 2 days of confusion and sleeping by day. Today he swung at her and did not know where he was. He stopped drinking 6 months ago. He takes furosemide and spironolactone, and 5 days ago his family physician added lorazepam 1 mg at night for insomnia. He has not had a bowel movement for 4 days. He has jaundice, ascites and asterixis. Rectal examination shows hard brown stool without melena. He has an adult daughter from a first marriage and a brother. He has no personal directive.",
    vitals: { temperature: "36.9°C oral", pulse: "96/minute", resp: "18/minute", bp: "104/62 mmHg", o2sat: "96% on room air", weight: "78 kg" },
    questions: [
      {
        id: "q1",
        kind: "menu",
        update: "Hemoglobin is 124 g/L, unchanged from last month. Sodium is 134 mmol/L, potassium 4.1 mmol/L and creatinine 88 umol/L, all at baseline. Ascitic fluid has 90 neutrophils x 10^6/L. Urinalysis and chest radiograph are normal.",
        prompt: "Which of the following are the most likely contributors to his current confusion?",
        options: ["Alcohol withdrawal", "Constipation for 4 days", "Gastrointestinal bleeding", "Hypokalemia from diuretics", "Lorazepam at bedtime", "Spontaneous bacterial peritonitis", "Wernicke encephalopathy"],
        select: 2,
        correct: [1, 4],
        explanation: "Constipation raises gut ammonia absorption and is a recognized precipitant of hepatic encephalopathy, and a new nightly benzodiazepine can worsen or mimic it. His hemoglobin is stable with no melena, so bleeding is unlikely. His potassium and creatinine are normal, which argues against diuretic excess. An ascitic neutrophil count of 90 x 10^6/L is below the 250 threshold for spontaneous bacterial peritonitis. He stopped drinking 6 months ago, and he has no eye signs or ataxia to suggest Wernicke encephalopathy.",
        keyFeature: kf(2),
        source: "aasld-easl-he",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate initial treatment for his encephalopathy?",
        options: ["flumazenil 0.2 mg IV", "lactulose 25 mL PO every 1 to 2 hours", "metronidazole 500 mg PO twice daily", "neomycin 1 g PO every 6 hours", "rifaximin 550 mg PO twice daily alone"],
        correct: 1,
        explanation: "The AASLD and EASL guideline treats an episode of overt hepatic encephalopathy with lactulose 25 mL every 1 to 2 hours until at least two soft stools are passed, which also relieves his constipation. Rifaximin is added to lactulose to prevent recurrence, not used alone first. Neomycin and metronidazole are alternatives whose kidney, ear and nerve toxicity limit their use. Flumazenil gives only a brief improvement, and the lorazepam is better stopped.",
        keyFeature: kf(2),
        source: "aasld-easl-he",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Under the Nova Scotia Personal Directives Act, which of the following is his statutory decision maker?",
        options: ["Adult daughter from his first marriage", "Brother who lives in the same town", "Partner he has lived with for 12 years", "Public Trustee of Nova Scotia", "Treating emergency physician"],
        correct: 2,
        explanation: "With no personal directive, the Act names a statutory decision maker from a ranked list that starts with the spouse, and spouse includes a common-law partner who is cohabiting with him. His partner of 12 years therefore comes before his adult child, then parents and siblings. The Public Trustee is the last resort when no relative is available and willing. The treating physician cannot give substitute consent.",
        keyFeature: kf(5),
        source: "ns-pda",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following examination findings best supports hepatic encephalopathy as the cause of his delirium?",
        options: ["Asterixis of the outstretched hands", "Distended abdomen with ascites", "Jaundice of the skin and sclerae", "Palmar erythema and spider angiomas", "Reversal of the sleep and wake cycle"],
        correct: 0,
        explanation: "Asterixis is a sign of metabolic encephalopathy and appears in the early and middle stages of overt hepatic encephalopathy. It is not specific, since uremia and carbon dioxide retention also cause it, but his kidney function and saturation are normal. Ascites, jaundice, palmar erythema and spider angiomas show that he has cirrhosis, not that his brain is affected. Sleep and wake reversal is common in any delirium.",
        keyFeature: kf(2),
        source: "aasld-easl-he",
      },
    ],
    sources: [SRC_VILSTRUP, SRC_NS_PDA],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 25 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-25",
    topic: "delirium-agitation",
    title: "Wandering the halls at night",
    stem: "You are working in an emergency department in Quebec. An 88-year-old woman is brought by ambulance from her seniors' residence with 6 hours of new confusion and restlessness. Staff found her wandering the hallway at 03:00, which she has never done. She has mild vascular dementia, type 2 diabetes and hypertension. At baseline she walks with a walker and chats with staff. Her husband of 60 years lives with her at the residence. She has no protection mandate, tutor or advance medical directive. She denies pain. She is pale and sweaty, cannot count backward from 10 and has crackles at both lung bases. Capillary glucose is 11.2 mmol/L.",
    vitals: { temperature: "36.6°C oral", pulse: "104/minute", resp: "24/minute", bp: "104/66 mmHg", o2sat: "91% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following investigations is most important for her now?",
        options: ["ECG with serial troponin", "Lumbar puncture", "Serum ammonia level", "Thyroid-stimulating hormone", "Urinalysis with culture"],
        correct: 0,
        explanation: "Delirium is often the only sign of serious illness in older adults, and myocardial infarction is a classic silent cause. Sweating, pallor, tachycardia, a low-normal blood pressure and new bibasilar crackles point to a cardiac cause, so an ECG is needed at once. Lumbar puncture is not indicated without fever or meningism. Ammonia is unhelpful without liver disease. TSH can wait. A urinalysis risks anchoring on bacteriuria, which is common in older women and does not explain her findings.",
        keyFeature: kf(2),
        source: "inouye-2006",
      },
      {
        id: "q2",
        kind: "single",
        update: "The ECG shows 3 mm ST elevation in V1 to V4. Cardiology accepts her for primary PCI. She cannot understand or retain an explanation of the procedure.",
        prompt: "Under the Civil Code of Québec, which of the following should be asked to consent to PCI on her behalf?",
        options: ["A judge of the Superior Court", "Daughter who visits her daily", "Husband of 60 years", "The cardiologist on call", "The Public Curator of Québec"],
        correct: 2,
        explanation: "Article 15 says that when an adult is incapable of consenting to care and has no advance medical directive, mandatary or tutor, consent is given by the married, civil union or de facto spouse. Only when there is no spouse, or the spouse is prevented, does consent pass to a close relative such as her daughter or a person with a special interest. Court authorization is needed when the substitute refuses without justification or the patient categorically refuses. The Public Curator and the treating physician do not consent in this situation.",
        keyFeature: kf(5),
        source: "ccq",
      },
      {
        id: "q3",
        kind: "single",
        update: "Her husband is out at an appointment and does not answer his phone. Her daughter's phone goes to voicemail. The catheterization team is ready.",
        prompt: "Which of the following is the most appropriate action regarding consent for her PCI?",
        options: ["Apply to the court for authorization", "Ask residence staff to consent for her", "Delay PCI until her husband is reached", "Obtain consent from the patient herself", "Proceed with PCI as emergency care"],
        correct: 4,
        explanation: "Article 13 says consent is not required in an emergency when life is in danger or integrity is threatened and consent cannot be obtained in due time. An anterior STEMI with falling saturation meets this, and delay loses myocardium. Residence staff have no authority to consent. Her own agreement is not valid because she cannot understand the procedure. A court application takes far too long. The exception does not apply to care that is unusual, useless or intolerable in its consequences, which primary PCI is not.",
        keyFeature: kf(5),
        source: "ccq",
      },
      {
        id: "q4",
        kind: "single",
        update: "While awaiting transfer she tries to pull off her ECG leads and climb off the stretcher.",
        prompt: "Which of the following is the most appropriate first measure to keep her safe before transfer?",
        options: ["Apply wrist restraints for the transfer", "Give lorazepam 1 mg IV before transfer", "Keep a nurse at her side", "Lower the lights and leave her to rest", "Raise all four bed rails"],
        correct: 2,
        explanation: "A nurse at her side who reorients and reassures her keeps her safe without adding a new cause of delirium. Physical restraints are themselves a precipitating factor for delirium and raise the risk of injury. Benzodiazepines can worsen and prolong delirium in older adults and add respiratory depression before a procedure. Leaving her alone in the dark invites a fall. Four raised rails give her something to climb over and increase the height of a fall.",
        keyFeature: kf(3),
        source: "inouye-2006",
      },
    ],
    sources: [SRC_INOUYE_2006, SRC_CCQ],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 26 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-26",
    topic: "delirium-agitation",
    title: "Seeing people who are not there",
    stem: "A 74-year-old man with prostate cancer metastatic to bone is brought to the emergency department by his wife. His palliative care physician raised his long-acting morphine to 90 mg twice daily 6 days ago for hip pain. For 3 days he has vomited most of his fluids. For 2 days he has seen strangers in the bedroom, jerked awake repeatedly and cried out when his wife touches his skin. Tonight he pushed her away and tried to leave the house. He is drowsy but rousable, follows commands inconsistently and has frequent multifocal myoclonic jerks. His mucous membranes are dry. There is no focal deficit.",
    vitals: { temperature: "37.2°C oral", pulse: "108/minute", resp: "16/minute", bp: "102/64 mmHg", o2sat: "95% on room air", weight: "64 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following investigations is most useful for finding the cause of his delirium now?",
        options: ["Blood cultures from two sites", "Calcium and creatinine levels", "CT head with contrast", "EEG to look for seizures", "Serum morphine level"],
        correct: 1,
        explanation: "Two common reversible causes of delirium in a man with bone metastases and 3 days of vomiting are hypercalcemia and kidney injury, and kidney injury lets morphine metabolites accumulate. Calcium and creatinine answer both questions. He has no fever or source for blood cultures. CT head is not needed without a focal deficit. His jerks are myoclonus with preserved rousability, not seizures. Serum morphine levels are not used clinically and do not measure the toxic metabolites.",
        keyFeature: kf(2),
        source: "gallagher-2007",
      },
      {
        id: "q2",
        kind: "single",
        update: "Corrected calcium is 2.38 mmol/L. Creatinine is 212 umol/L, up from 95 umol/L a month ago. Sodium and glucose are normal.",
        prompt: "Which of the following is the most likely cause of his delirium?",
        options: ["Brain metastases with edema", "Hypercalcemia of malignancy", "Morphine metabolite buildup", "Nonconvulsive status epilepticus", "Terminal delirium of dying"],
        correct: 2,
        explanation: "Opioid-induced neurotoxicity causes hallucinations, myoclonus, hyperalgesia and delirium, and it is more likely with opioids that have active metabolites, such as morphine, when the dose rises and dehydration or kidney injury reduces clearance. All of these apply to him. His calcium is normal. He has no focal signs to suggest metastases. Terminal delirium is a diagnosis of exclusion and should not be assumed when a reversible cause is present.",
        keyFeature: kf(2),
        source: "gallagher-2007",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate management of his delirium?",
        options: ["Add lorazepam for the myoclonus", "Give naloxone 0.4 mg IV", "Increase morphine for his pain", "Rehydrate and rotate the opioid", "Stop all opioids until he is clear"],
        correct: 3,
        explanation: "Management of opioid-induced neurotoxicity is to rotate to a different opioid and to rehydrate, which clears the accumulated metabolites while keeping his pain controlled. Opioids should not be stopped when they are needed for pain, and stopping would leave his bone pain untreated. More morphine adds to the toxic load. Naloxone would reverse his analgesia and does not treat neuroexcitatory toxicity. Lorazepam can add sedation and worsen delirium.",
        keyFeature: kf(2),
        source: "gallagher-2007",
      },
      {
        id: "q4",
        kind: "single",
        update: "After 36 hours of fluids and a new opioid he is calm, oriented and attentive. He understands the plan and its risks, and asks to go home with palliative home care rather than be admitted.",
        prompt: "Which of the following is the most appropriate response to his request?",
        options: ["Accept his choice and arrange home care", "Admit him because he was delirious recently", "Ask his wife to consent to admission", "Certify him under the Mental Health Act", "Delay discharge for a psychiatry opinion"],
        correct: 0,
        explanation: "Capacity is judged at the time of the decision. He now understands the information, appreciates how it applies to him, reasons about it and states a clear choice, so his decision stands. A recent delirium does not remove capacity once it has cleared. His wife has no authority to consent while he is capable. He has no mental disorder that would meet mental health act criteria. A psychiatry opinion is not required when the treating physician finds him capable.",
        keyFeature: kf(5),
        source: "appelbaum",
      },
    ],
    sources: [SRC_GALLAGHER, SRC_APPELBAUM],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 27 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-27",
    topic: "delirium-agitation",
    title: "Eight days after her first baby",
    stem: "You are working in an emergency department in British Columbia. The hospital is a designated facility under the Mental Health Act. A 29-year-old woman is brought in by her husband 8 days after the birth of her first child. For 3 days she has barely slept, talks rapidly and says the baby has been replaced by a demon. At times she seems perplexed and asks what day it is, then an hour later seems clear. Pregnancy and delivery were uncomplicated. She has no psychiatric history, and her mother has bipolar disorder. She is breastfeeding. The baby is at home with her mother-in-law. She has no headache, no edema and no focal deficit. Urine protein is negative. Capillary glucose is 5.2 mmol/L.",
    vitals: { temperature: "36.9°C oral", pulse: "96/minute", resp: "16/minute", bp: "124/78 mmHg", o2sat: "99% on room air" },
    questions: [
      {
        id: "q1",
        kind: "menu",
        prompt: "Which of the following are the most appropriate initial tests to look for a treatable medical cause?",
        options: ["Beta-hCG level", "CT head without contrast", "Electrolytes and calcium", "Lumbar puncture", "Pelvic ultrasound", "Serum prolactin level", "Thyroid function tests"],
        select: 2,
        correct: [2, 6],
        explanation: "Postpartum psychosis is a diagnosis made after excluding medical causes, and autoimmune thyroiditis, electrolyte disturbance such as hypercalcemia or hyponatremia, and infection are among the treatable ones. Thyroid function and electrolytes with calcium belong in the first panel. Beta-hCG is expected to be positive 8 days after delivery. CT and lumbar puncture are reserved for neurological signs, fever or an atypical course, which she does not have. Prolactin is high with breastfeeding and changes nothing. Pelvic ultrasound has no role without bleeding or fever.",
        keyFeature: kf(2),
        source: "bergink-2016",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most important measure to keep her infant safe during her care?",
        options: ["Allow her home if she promises safety", "Bring the baby in to feed on demand", "Discharge her home with her husband", "Report the family to child protection", "Supervised contact only with her baby"],
        correct: 4,
        explanation: "Postpartum psychosis carries a risk of infanticide, and her belief that the baby is a demon makes that risk real. Any contact should be supervised by another adult until she is treated. Bringing the baby for feeding on demand leaves them alone together. A promise of safety from a psychotic patient is not reliable, and discharge home, even with her husband, is unsafe at this stage. The baby is safe with his grandmother, so a report to child protection is not the first step.",
        keyFeature: kf(3),
        source: "bergink-2016",
      },
      {
        id: "q3",
        kind: "single",
        update: "She insists on going home to save the baby and walks toward the exit. She says nothing is wrong with her and refuses admission.",
        prompt: "Under the British Columbia Mental Health Act, which of the following allows her to be admitted and detained for up to 48 hours?",
        options: ["Court order from a provincial judge", "Husband's consent as next of kin", "Police apprehension under section 28", "Single physician's medical certificate", "Two certificates before any detention"],
        correct: 3,
        explanation: "Section 22 allows a designated facility to admit and detain a person for up to 48 hours on one medical certificate, completed after examination by a physician who believes the person has a mental disorder, needs treatment, needs care to prevent substantial deterioration or for protection, and cannot suitably be a voluntary patient. A second certificate is needed only to continue beyond 48 hours. Section 28 lets police bring a person for examination and does not admit her. No court order or family consent is needed.",
        keyFeature: kf(5),
        source: "bc-mha",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following findings would most suggest a medical cause rather than postpartum psychosis?",
        options: ["Belief that the baby is possessed", "Family history of bipolar disorder", "Fluctuating perplexity and confusion", "New seizure with a fever", "Onset within 2 weeks of delivery"],
        correct: 3,
        explanation: "A seizure with fever points to encephalitis, including anti-NMDA receptor encephalitis, which can present after birth with psychosis. Perplexity and waxing and waning confusion are characteristic of postpartum psychosis itself, so they do not separate it from a medical cause. Delusions about the baby, onset within the first weeks and a family history of bipolar disorder are typical features and risk factors of postpartum psychosis.",
        keyFeature: kf(1),
        source: "bergink-2016",
      },
    ],
    sources: [SRC_BERGINK, SRC_BC_MHA],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 28 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-28",
    topic: "delirium-agitation",
    title: "After the restraints went on",
    stem: "A 34-year-old man with schizophrenia is brought to the emergency department by police after threatening his neighbours with a hammer. He stopped his medications a month ago. He has no alcohol or drug use and a glucose of 5.9 mmol/L. In the department he punched a security guard. Verbal de-escalation and an offer of oral medication failed. He was placed in four point restraints, supine, and given haloperidol 5 mg IM and lorazepam 2 mg IM at 21:00. He is now quiet and lying still with his eyes closed. He has never taken haloperidol before.",
    vitals: { temperature: "37.0°C oral", pulse: "98/minute", resp: "16/minute", bp: "138/84 mmHg", o2sat: "97% on room air", weight: "82 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate monitoring while he remains in restraints?",
        options: ["Check him when he calls out", "Constant observation with vital signs", "Hourly checks through the door window", "Pulse oximetry only if he falls asleep", "Vital signs once per nursing shift"],
        correct: 1,
        explanation: "A restrained patient who has received a sedating antipsychotic and a benzodiazepine can lose his airway, aspirate or develop dangerous heat, heart rhythm or muscle breakdown problems without calling out. He needs continuous observation with regular vital signs and pulse oximetry, and a face-to-face physician evaluation within the first hour. Checks through a window, once a shift or only when he calls out would miss deterioration. Oximetry is needed from the start because the drugs, not sleep, cause the risk.",
        keyFeature: kf(4),
        source: "knox-2012",
      },
      {
        id: "q2",
        kind: "single",
        update: "At 22:30 he is awake and calm. He apologizes, says he will not hurt anyone and asks to be untied. He answers questions appropriately.",
        prompt: "Which of the following is the most appropriate next step regarding his restraints?",
        options: ["Begin release with staff at the bedside", "Give more haloperidol before release", "Keep restraints until morning rounds", "Keep restraints until psychiatry sees him", "Remove all four and leave the room"],
        correct: 0,
        explanation: "Restraint is kept for the shortest time possible and ended once the patient has regained control, which he has. Releasing him in steps with enough staff present protects him and the team if he becomes agitated again. Keeping him restrained until rounds or a psychiatry visit prolongs a traumatic intervention with no safety benefit. More haloperidol in a calm patient adds side effects. Removing all restraints and leaving him alone gives no chance to reassess.",
        keyFeature: kf(4),
        source: "knox-2012",
      },
      {
        id: "q3",
        kind: "single",
        update: "At 23:30 he is out of restraints. He paces, cannot sit still, says his legs feel as if they must move and asks for help. He is not threatening anyone. Temperature is 37.1°C and muscle tone is normal.",
        prompt: "Which of the following is the most likely explanation for his restlessness?",
        options: ["Akathisia from haloperidol", "Benzodiazepine paradoxical reaction", "Emerging alcohol withdrawal", "Neuroleptic malignant syndrome", "Worsening psychotic agitation"],
        correct: 0,
        explanation: "Akathisia is an inner urge to move with pacing and inability to sit still, and it often appears within hours of a first dose of a high potency antipsychotic such as haloperidol. His distress about his legs and his request for help, without threats, fit it better than a return of psychotic agitation. Mistaking akathisia for agitation and giving more haloperidol makes it worse. Neuroleptic malignant syndrome needs fever and rigidity, which he lacks. He does not drink, and paradoxical benzodiazepine reactions cause disinhibition rather than this motor restlessness.",
        keyFeature: kf(4),
        source: "maudsley",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following is the most appropriate treatment for his restlessness?",
        options: ["haloperidol 5 mg IM", "ketamine 1 mg/kg IV", "olanzapine 10 mg IM", "propranolol 20 mg PO", "Reapply four point restraints"],
        correct: 3,
        explanation: "A low dose of a beta blocker such as propranolol is a standard treatment for acute akathisia, along with reducing or stopping the causative antipsychotic. A further dose of haloperidol would worsen it. Olanzapine IM is not advised within an hour or two of a parenteral benzodiazepine because of the risk of cardiorespiratory depression, and it is still a dopamine blocker. Ketamine is for dangerous agitation. Restraint in a cooperative man who is asking for help is not justified and increases his distress.",
        keyFeature: kf(4),
        source: "maudsley",
      },
    ],
    sources: [SRC_KNOX, SRC_MAUDSLEY],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 29 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-29",
    topic: "delirium-agitation",
    title: "A father shouting in the resuscitation room",
    stem: "A 3-year-old boy is in the resuscitation room after a 12-minute febrile seizure that stopped with intranasal midazolam. He is now sleepy but breathing well. His father, who smells of alcohol, is shouting that the nurses are killing his son and has just shoved a respiratory therapist against the wall. The boy's mother is crying at the bedside and asks staff to help. Families in nearby cubicles are watching. The father has not been injured and is not a patient.",
    vitals: { temperature: "39.4°C rectal", pulse: "150/minute", resp: "28/minute", bp: "96/58 mmHg", o2sat: "98% on room air", weight: "14 kg" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following is the most appropriate immediate response to the father?",
        options: ["Ask his wife to settle him down", "Call security and assign one person to talk", "Ignore him and carry on with care", "Offer him a sedative by mouth", "Order him out in a firm loud voice"],
        correct: 1,
        explanation: "He has already assaulted a staff member, so security is called at once to protect staff, the child and other families, while one calm staff member engages him so that he hears a single voice. Asking his distressed wife to manage him places her at risk. Ignoring him lets the danger grow. He is not a patient, so offering him a sedative is not appropriate. A loud, confrontational order is provocative and tends to escalate.",
        keyFeature: kf(3),
        source: "beta-deesc",
      },
      {
        id: "q2",
        kind: "single",
        update: "Security arrives. He is still shouting but agrees to step into a family room with the charge nurse.",
        prompt: "Which of the following statements best acknowledges his feelings during de-escalation?",
        options: ["That must have been terrifying to watch", "Trust us, we are the professionals here", "Unless you calm down, security will act", "You have been drinking and cannot stay", "Your son is fine and there is no worry"],
        correct: 0,
        explanation: "Naming the feeling behind the anger, here terror at watching his son seize, is a core step in verbal de-escalation and often lowers arousal quickly. A statement about his drinking is provocative. An appeal to professional authority dismisses his fear. False reassurance that nothing is wrong is untrue after a prolonged seizure and loses his trust. A threat of force may be needed later as a clear limit, but it is not the way to open the conversation.",
        keyFeature: kf(3),
        source: "beta-deesc",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which of the following is the most appropriate limit to set with him once he is calmer?",
        options: ["Free to act as he wishes as a parent", "Leave now and not return tonight", "Stay only after police have charged him", "Wait outside until his son is discharged", "Welcome at the bedside while he stays calm"],
        correct: 4,
        explanation: "Clear, respectful limits tied to behaviour give him a way to stay with his son, which is what he wants, while protecting staff. He can return to the bedside while he remains calm. Allowing him to act as he wishes ignores the assault. Banning him for the night or until discharge punishes rather than de-escalates and removes support from his son and wife. Whether to involve police is the injured staff member's decision and should not be a condition of seeing his child.",
        keyFeature: kf(3),
        source: "beta-deesc",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following is the most appropriate step for the team after this incident?",
        options: ["Debrief the team and report the event", "Discuss it only if someone was injured", "Forbid the father from any future visits", "Take no action since the child is well", "Wait for a staff complaint before review"],
        correct: 0,
        explanation: "Debriefing lets staff process the event and identify what to change, and an incident report documents the assault and supports the injured therapist. Workplace violence toward health care staff is common and causes lasting psychological harm, so it should be reviewed whether or not there was a physical injury. Waiting for a complaint or taking no action lets the problem recur. A permanent ban on visiting is not a proportionate response to one supervised visit.",
        keyFeature: kf(3),
        source: "knox-2012",
      },
    ],
    sources: [SRC_BETA_DEESC, SRC_KNOX],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
  /* 30 ------------------------------------------------------------------ */
  {
    id: "delirium-agitation-30",
    topic: "delirium-agitation",
    title: "Hit an aide during the morning bath",
    stem: "A 78-year-old man with moderate Alzheimer disease is sent from his long-term care home because he struck a care aide during his morning bath. Staff say he has resisted baths for months and becomes upset when rushed, but is otherwise pleasant, eats well and joins activities. They have noticed no change in his alertness, sleep or attention. He takes donepezil. In the department he is calm and alert, follows the conversation and recites the days of the week backward without error, though he does not know the date. He has no pain on examination, and the examination is otherwise normal. Capillary glucose is 6.4 mmol/L.",
    vitals: { temperature: "36.7°C oral", pulse: "74/minute", resp: "14/minute", bp: "132/78 mmHg", o2sat: "97% on room air" },
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which of the following findings best supports that he does not have delirium?",
        options: ["Calm manner in the department", "Good appetite at the home", "Known Alzheimer disease", "Normal attention and alertness", "Stable vital signs"],
        correct: 3,
        explanation: "Inattention and a disturbed level of alertness are required for delirium, and he is alert and recites the days backward without error, with no change noticed by staff. A calm manner in the department proves little, because delirium fluctuates. A good appetite and normal vital signs are reassuring but do not test the core features. Alzheimer disease is a risk factor for delirium, not evidence against it.",
        keyFeature: kf(1),
        source: "cam",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which of the following is the most appropriate recommendation to his care home?",
        options: ["Adapt bathing to his preferences", "Apply a lap belt restraint during baths", "Start risperidone before each bath", "Transfer him to a secure psychiatric unit", "Use two aides to hold him during baths"],
        correct: 0,
        explanation: "His aggression occurs only when he is rushed through a bath, so a person-centred change, such as a different time, a sponge bath, a slower pace or a familiar aide, removes the trigger. Holding him or using a restraint increases fear and the chance of injury to him and the aides. The Beers Criteria advise against antipsychotics for behavioural symptoms of dementia unless non-drug measures have failed and there is a risk of substantial harm. Transfer to a psychiatric unit is not needed for a single triggered behaviour.",
        keyFeature: kf(3),
        source: "beers-2023",
      },
      {
        id: "q3",
        kind: "single",
        update: "Six weeks later he returns. Despite a new bathing plan he has struck two aides and a resident, causing a fractured wrist, and his aggression now occurs at other times of day. A repeat assessment finds no delirium or pain.",
        prompt: "Which of the following is the most appropriate medication to trial for his aggression?",
        options: ["diphenhydramine 25 mg PO at bedtime", "haloperidol 5 mg PO twice daily", "lorazepam 1 mg PO three times daily", "quetiapine 100 mg PO at bedtime", "risperidone 0.25 mg PO twice daily"],
        correct: 4,
        explanation: "Non-drug measures have failed and he is causing substantial harm to others, which is the situation where the Beers Criteria accept an antipsychotic. Low dose risperidone, starting at 0.25 mg twice daily, is the antipsychotic most studied for aggression in Alzheimer disease, and it should be reviewed often and tapered when possible. Haloperidol 5 mg twice daily is a high dose for a frail older man. Lorazepam and diphenhydramine cause falls and confusion and appear on the Beers list. Quetiapine at 100 mg mainly sedates and causes orthostatic hypotension.",
        keyFeature: kf(4),
        source: "beers-2023",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which of the following risks must be discussed with his substitute decision maker before starting it?",
        options: ["Agranulocytosis requiring blood tests", "Dependence with withdrawal seizures", "Permanent hearing loss", "Stroke and higher mortality", "Sudden liver failure"],
        correct: 3,
        explanation: "Antipsychotics in older adults with dementia increase the risk of stroke, cognitive decline and death, which is why the Beers Criteria restrict their use, so informed consent must include these risks. Agranulocytosis with mandatory blood monitoring applies to clozapine. Dependence and withdrawal seizures are risks of benzodiazepines. Hearing loss and sudden liver failure are not recognized effects of risperidone.",
        keyFeature: kf(5),
        source: "beers-2023",
      },
    ],
    sources: [SRC_CAM, SRC_BEERS],
    reviewed: false,
    author: AUTHOR,
    version: 1,
  },
];
