import type { OralCase } from "@/engine/types";
import { BANK_BLOB } from "./generated/encoded";

/**
 * Decodes the obfuscated case snapshot generated by
 * scripts/build-bank-cache.mjs. Mirrors that script's xor() exactly — keep
 * the two in sync. Not encryption, see that script's header comment.
 *
 * Runs fully offline: base64 + XOR + JSON.parse, no fetch, no native API.
 */
const KEY = "preceptor-ccfpem-cases-v1";

function fromBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function xor(bytes: Uint8Array, key: string): Uint8Array {
  const keyBytes = new TextEncoder().encode(key);
  const out = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) out[i] = bytes[i] ^ keyBytes[i % keyBytes.length];
  return out;
}

let cached: OralCase[] | null = null;

/** The shipped case bank, decoded once and cached for the life of the page. */
export function decodedCases(): OralCase[] {
  if (!cached) {
    const json = new TextDecoder().decode(xor(fromBase64(BANK_BLOB), KEY));
    cached = JSON.parse(json) as OralCase[];
  }
  return cached;
}
