// DRAFT. Clinical content written for simulation only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { OralCase } from "@/engine/types";

export const overdose: OralCase = {
  id: "overdose-mixed",
  title: "A drowsy woman found at home",
  domain: "Toxicology",
  summary: "A 34 year old woman brought in by ambulance after her partner found her drowsy with empty pill packages.",
  durationMinutes: 15,
  stem:
    "You are working in a mid sized community emergency department in Ontario. There is an ICU on site. " +
    "Leanne Moreau is 34 years old. Her partner found her drowsy on the couch about an hour ago with empty blister packs and an empty wine bottle. " +
    "She was last seen well about 5 hours before that. " +
    "Triage vitals: heart rate 124, blood pressure 96/58, respiratory rate 16, SpO2 95 percent on room air, temperature 37.8, capillary glucose 6.1 mmol/L. Estimated weight 60 kg. CTAS 1. " +
    "The nurse says: 'Paramedics say she was talking in the truck but she is getting sleepier. The monitor rhythm looks wide to me. Her partner brought the packages. They are in a bag at the desk.'",
  findings: [
    {
      id: "ecg",
      label: "ECG",
      result: "Sinus tachycardia at 124. QRS 132 ms. Terminal R wave in aVR of 4 mm. Terminal 40 ms axis deviated to the right. QTc 510 ms. No Brugada pattern.",
    },
    {
      id: "exam",
      label: "Physical exam",
      result:
        "GCS 12 (E3 V4 M5). Pupils 6 mm and sluggish. Skin flushed and dry. Mucous membranes dry. Bowel sounds reduced. Bladder palpable. " +
        "Reflexes normal. No clonus. No rigidity. No signs of trauma. Gag present.",
    },
    {
      id: "packages",
      label: "Pill packages",
      result:
        "Amitriptyline 50 mg, 60 tablets dispensed 10 days ago, 38 missing. Acetaminophen 500 mg, a bottle of 100 that is about half empty. An empty 750 mL bottle of wine.",
    },
    {
      id: "partner",
      label: "Collateral from partner",
      result:
        "She has depression and chronic back pain. Amitriptyline was started 6 months ago. She lost her job last month. " +
        "She took an overdose of sertraline 2 years ago. He found a note on the counter that says 'I am sorry. I cannot keep doing this.' " +
        "No other known medications. No drug use that he knows of.",
    },
    { id: "vbg", label: "Venous blood gas", result: "pH 7.29. pCO2 48 mmHg. Bicarbonate 22 mmol/L. Lactate 2.9 mmol/L." },
    {
      id: "chem",
      label: "Electrolytes and chemistry",
      result:
        "Sodium 138 mmol/L. Potassium 3.6 mmol/L. Chloride 104 mmol/L. Bicarbonate 21 mmol/L. Anion gap 13. Creatinine 72 µmol/L. Glucose 6.1 mmol/L. CK 210 U/L.",
    },
    { id: "apap", label: "Acetaminophen level", result: "Acetaminophen 412 µmol/L. Time of ingestion unknown." },
    { id: "other-tox", label: "Salicylate, ethanol and osmolality", result: "Salicylate undetectable. Ethanol 18 mmol/L. Serum osmolality 306 mOsm/kg." },
    { id: "lft", label: "Liver function and INR", result: "ALT 38 U/L. AST 41 U/L. Bilirubin 12 µmol/L. INR 1.0." },
    { id: "hcg", label: "Pregnancy test", result: "Serum beta hCG negative." },
    { id: "bladder", label: "Bladder scan", result: "Bladder scan shows 650 mL of urine." },
    {
      id: "poison-centre",
      label: "Ontario Poison Centre advice",
      result:
        "The specialist agrees with bicarbonate targets of QRS under 100 ms and pH 7.50 to 7.55. " +
        "They recommend acetylcysteine now, benzodiazepines for seizures, and a call back if hypotension persists despite bicarbonate and norepinephrine. They will review lipid emulsion if she arrests.",
    },
  ],
  start: "s-open",
  nodes: [
    {
      kind: "say",
      id: "s-open",
      phase: "Resus",
      text: "She is in resus on the monitor. The nurse hands you the ECG.",
      next: "q-ecg",
    },
    {
      kind: "question",
      id: "q-ecg",
      phase: "Initial assessment",
      prompt: "Interpret this ECG. What has she taken, how much, and which features predict complications?",
      seconds: 60,
      modelAnswer: [
        "Sinus tachycardia with QRS 132 ms and a terminal R in aVR of 4 mm.",
        "Pattern of sodium channel blockade from a tricyclic.",
        "QRS over 100 ms predicts seizures. QRS over 160 ms predicts ventricular dysrhythmias.",
        "Amitriptyline about 1,900 mg, roughly 30 mg/kg. That is a severe ingestion.",
        "Anticholinergic toxidrome on exam.",
      ],
      rubric: ["od-r1", "od-t1"],
      next: "q-bicarb",
    },
    {
      kind: "question",
      id: "q-bicarb",
      phase: "Treatment",
      prompt: "What do you give now? What dose, how often, and what is your endpoint?",
      seconds: 60,
      modelAnswer: [
        "Sodium bicarbonate 1 to 2 mEq/kg IV push, 60 to 120 mEq.",
        "That is one to two 50 mL ampoules of 8.4 percent.",
        "Repeat every 3 to 5 minutes until QRS is under 100 ms or pH is 7.50 to 7.55.",
        "Then an infusion, e.g. 150 mEq in 1 L D5W at 150 to 250 mL/h.",
        "Monitor potassium, sodium and pH.",
      ],
      rubric: ["od-r2", "od-r3"],
      choices: [
        { id: "c-bolus", label: "I gave sodium bicarbonate 1 to 2 mEq/kg IV push and repeated it to narrow the QRS.", next: "q-workup", quality: "strong" },
        { id: "c-infusion-only", label: "I started a bicarbonate infusion without a bolus.", next: "s-slow-bicarb", quality: "partial" },
        { id: "c-amio", label: "I gave amiodarone for the wide complex rhythm.", next: "s-amio", quality: "unsafe" },
      ],
    },
    {
      kind: "say",
      id: "s-slow-bicarb",
      phase: "Fifteen minutes later",
      text: "The QRS is 136 ms. She has a 6 beat run of wide complex tachycardia. An infusion alone is too slow to reverse sodium channel blockade. You push 100 mEq.",
      next: "q-workup",
    },
    {
      kind: "say",
      id: "s-amio",
      phase: "Five minutes later",
      text:
        "Her blood pressure falls to 72/40. The QRS widens to 150 ms and she has a run of ventricular tachycardia. Amiodarone adds sodium and potassium channel blockade. You push 100 mEq of bicarbonate.",
      next: "q-workup",
    },
    {
      kind: "question",
      id: "q-workup",
      phase: "Workup",
      prompt: "What bloodwork do you want? Who will you call? Will you give activated charcoal?",
      seconds: 60,
      modelAnswer: [
        "Acetaminophen, salicylate, ethanol, gas, electrolytes, liver tests, INR and pregnancy test.",
        "Collateral from her partner about the pills, timing, note and past attempts.",
        "Call the Ontario Poison Centre early.",
        "No charcoal while her airway is unprotected and her level of consciousness is falling.",
        "Consider charcoal after intubation with poison centre advice.",
      ],
      rubric: ["od-t2", "od-t5", "od-c1", "od-c2"],
      next: "s-seizure",
    },
    {
      kind: "say",
      id: "s-seizure",
      phase: "Ten minutes later",
      text: "Her QRS narrowed to 108 ms after bicarbonate. Now she has a generalized tonic clonic seizure. SpO2 falls to 86 percent. The QRS on the monitor looks wider again.",
      next: "q-seizure",
    },
    {
      kind: "question",
      id: "q-seizure",
      phase: "Seizure",
      prompt: "Which drug and dose will you use for the seizure? Is there any drug you would avoid? What else do you give?",
      seconds: 60,
      modelAnswer: [
        "Lorazepam 2 to 4 mg IV or midazolam 5 mg IV, repeated as needed.",
        "Avoid phenytoin. It is a sodium channel blocker and does not work for toxic seizures.",
        "Phenobarbital or propofol for refractory seizures, with airway control.",
        "Give more bicarbonate. Seizure acidosis worsens cardiotoxicity.",
      ],
      rubric: ["od-s1", "od-s2"],
      choices: [
        { id: "c-benzo", label: "I gave lorazepam 2 mg IV, repeated it, and gave more bicarbonate.", next: "q-intubate", quality: "strong" },
        { id: "c-phenytoin", label: "I loaded phenytoin after the first dose of lorazepam.", next: "s-phenytoin", quality: "unsafe" },
      ],
    },
    {
      kind: "say",
      id: "s-phenytoin",
      phase: "During the infusion",
      text: "Her QRS widens to 164 ms and her blood pressure falls to 68/36. The seizure continues. You stop the phenytoin, give more lorazepam and push bicarbonate.",
      next: "q-intubate",
    },
    {
      kind: "question",
      id: "q-intubate",
      phase: "Airway",
      prompt: "The seizure stops but her GCS is now 6. Talk me through your intubation and drug doses.",
      seconds: 90,
      modelAnswer: [
        "Intubate for airway protection.",
        "Give a bicarbonate bolus just before induction.",
        "Preoxygenate well and keep apnea as short as possible.",
        "Reduced dose induction in hypotension, e.g. ketamine 0.5 to 1 mg/kg.",
        "Rocuronium 1.2 to 1.5 mg/kg.",
        "Push dose vasopressor ready.",
      ],
      rubric: ["od-s3", "od-s4"],
      choices: [
        {
          id: "c-bicarb-first",
          label: "I gave a bicarbonate bolus, preoxygenated, used reduced dose ketamine with rocuronium, and kept apnea short.",
          next: "q-vent",
          quality: "strong",
        },
        { id: "c-tube-first", label: "I intubated first and planned more bicarbonate once she was on the ventilator.", next: "s-tube-first", quality: "unsafe" },
      ],
    },
    {
      kind: "say",
      id: "s-tube-first",
      phase: "During intubation",
      text:
        "The first attempt takes 70 seconds. Her pCO2 rises and her pH falls. The QRS widens to 172 ms and she goes into ventricular tachycardia with a pulse. You push 150 mEq of bicarbonate and the rhythm narrows.",
      next: "q-vent",
    },
    {
      kind: "question",
      id: "q-vent",
      phase: "Ventilation",
      prompt: "How will you set the ventilator, and why does it matter in this ingestion?",
      seconds: 45,
      modelAnswer: [
        "Match or exceed her pre intubation minute ventilation.",
        "Tidal volume 6 to 8 mL/kg ideal body weight with a high rate, e.g. 24 to 30.",
        "Target pH 7.50 to 7.55 with a gas soon after intubation.",
        "Respiratory acidosis increases free drug and worsens sodium channel blockade.",
      ],
      rubric: ["od-s5"],
      next: "s-hypotension",
    },
    {
      kind: "say",
      id: "s-hypotension",
      phase: "After intubation",
      text: "Her blood pressure is 74/40. The QRS is 148 ms.",
      next: "q-hypotension",
    },
    {
      kind: "question",
      id: "q-hypotension",
      phase: "Hypotension",
      prompt: "What now? If she keeps deteriorating, what else is available?",
      seconds: 60,
      modelAnswer: [
        "More bicarbonate boluses toward QRS under 100 ms.",
        "Crystalloid bolus.",
        "Norepinephrine infusion.",
        "Hypertonic saline if pH is already high.",
        "Lipid emulsion and ECMO as rescue, with poison centre input.",
      ],
      rubric: ["od-r4"],
      next: "s-apap",
    },
    {
      kind: "say",
      id: "s-apap",
      phase: "New result",
      text:
        "With more bicarbonate and norepinephrine at 0.1 mcg/kg/min her pressure is 102/60 and the QRS is 104 ms. " +
        "The lab calls. Her acetaminophen level is 412 µmol/L. Her partner is still not sure when she took the pills.",
      next: "q-apap",
    },
    {
      kind: "question",
      id: "q-apap",
      phase: "Co ingestion",
      prompt: "How do you interpret this level? What will you give, and where does she go from here?",
      seconds: 60,
      modelAnswer: [
        "The nomogram cannot be used when the time of ingestion is unknown.",
        "A detectable level with an unknown time means start acetylcysteine now.",
        "200 mg/kg over 4 hours then 100 mg/kg over 16 hours, or the three bag regimen.",
        "Check liver tests and INR at the end of the infusion before stopping.",
        "Admit to ICU with a handover of bicarbonate targets and acetylcysteine timing.",
      ],
      rubric: ["od-t3", "od-t4", "od-c3"],
      choices: [
        { id: "c-nac", label: "I started acetylcysteine now because the level is detectable and the time is unknown.", next: "s-later", quality: "strong" },
        { id: "c-repeat", label: "I planned to repeat the level in four hours and plot it on the nomogram.", next: "s-no-nac", quality: "unsafe" },
      ],
    },
    {
      kind: "say",
      id: "s-no-nac",
      phase: "Poison centre call",
      text:
        "The poison centre specialist says the nomogram does not apply with an unknown ingestion time. She could be more than 8 hours out, when delay raises the risk of liver injury. They advise starting acetylcysteine now. You start it.",
      next: "s-later",
    },
    {
      kind: "say",
      id: "s-later",
      phase: "Two days later",
      text:
        "You are back on shift. She was extubated in the ICU yesterday. Her QRS is 88 ms, acetaminophen is undetectable and ALT is 44. " +
        "She is in your ED observation area waiting for psychiatry in the morning. She is dressed and says, 'I am fine now. I am going home.' Her partner is not here.",
      next: "q-risk",
    },
    {
      kind: "question",
      id: "q-risk",
      phase: "Risk and capacity",
      prompt: "How will you assess her suicide risk and her capacity to refuse psychiatric assessment?",
      seconds: 90,
      modelAnswer: [
        "Ask directly about intent, plan and whether she regrets surviving.",
        "Weigh the note, the severity of the ingestion, the prior attempt, the job loss and her supports.",
        "Assess capacity: understanding, appreciation of risk, reasoning and a stable choice.",
        "Get collateral from her partner with her consent, or without it if needed to prevent serious harm.",
      ],
      rubric: ["od-m1"],
      next: "q-form1",
    },
    {
      kind: "question",
      id: "q-form1",
      phase: "Leaving",
      prompt: "She walks toward the exit. What legal authority do you have to keep her, what paperwork is needed, and what must she be given?",
      seconds: 90,
      modelAnswer: [
        "Keep her safe now, using the least restrictive means.",
        "Form 1 under the Ontario Mental Health Act when the criteria are met.",
        "Form 1 allows detention up to 72 hours for psychiatric assessment.",
        "The physician must have examined her within the past 7 days.",
        "Give her a Form 42 and explain her rights.",
        "Close observation and removal of means of self harm.",
      ],
      rubric: ["od-m2", "od-m3", "od-m4", "od-m5"],
      choices: [
        {
          id: "c-form1",
          label: "I kept her safely, completed a Form 1, gave her a Form 42 and arranged close observation.",
          next: "end",
          quality: "strong",
        },
        {
          id: "c-let-go",
          label: "She seemed calm and said she felt fine, so I let her go with a crisis line number.",
          next: "s-left",
          quality: "unsafe",
        },
      ],
    },
    {
      kind: "say",
      id: "s-left",
      phase: "Three hours later",
      text:
        "Her partner phones the department. She has not come home and is not answering her phone. Police are asked to do a wellness check. Her risk factors were high and she had not been assessed by psychiatry.",
      next: "end",
    },
    { kind: "end", id: "end", text: "That is the end of the case." },
  ],
  domains: [
    { id: "resus", name: "Resuscitation and stabilization" },
    { id: "airway", name: "Seizure and airway management" },
    { id: "tox", name: "Diagnosis and co ingestion" },
    { id: "comm", name: "Communication and collaboration" },
    { id: "safety", name: "Mental health, capacity and safety" },
  ],
  rubric: [
    {
      id: "od-r1",
      domain: "resus",
      text: "Identifies QRS over 100 ms and terminal R in aVR over 3 mm as signs of sodium channel blockade.",
      points: 2,
      teaching: "In tricyclic toxicity, QRS width predicts seizures and dysrhythmias better than the drug level does.",
    },
    {
      id: "od-r2",
      domain: "resus",
      text: "Gives sodium bicarbonate 1 to 2 mEq/kg IV bolus (60 to 120 mEq), repeated to QRS under 100 ms or pH 7.50 to 7.55.",
      points: 3,
      critical: true,
      teaching: "The sodium load and alkalemia overcome sodium channel blockade. Bolus first. An infusion alone is too slow.",
    },
    {
      id: "od-r3",
      domain: "resus",
      text: "Starts a bicarbonate infusion, e.g. 150 mEq in 1 L D5W at 150 to 250 mL/h, and monitors potassium, sodium and pH.",
      points: 1,
      teaching: "Alkalinization drives potassium into cells. Check electrolytes and gas often and replace potassium.",
    },
    {
      id: "od-r4",
      domain: "resus",
      text: "Treats hypotension with fluid, more bicarbonate and norepinephrine, and knows lipid emulsion and ECMO are rescue options.",
      points: 2,
      teaching: "Refractory tricyclic shock may respond to lipid emulsion or need ECMO. Involve the poison centre early.",
    },
    {
      id: "od-s1",
      domain: "airway",
      text: "Treats the seizure with a benzodiazepine, e.g. lorazepam 2 to 4 mg IV or midazolam 5 mg IV, and avoids phenytoin.",
      points: 3,
      critical: true,
      teaching: "Phenytoin blocks sodium channels and can worsen cardiotoxicity. Benzodiazepines are first line for toxic seizures.",
    },
    {
      id: "od-s2",
      domain: "airway",
      text: "Gives additional bicarbonate after the seizure because acidosis worsens toxicity.",
      points: 1,
      teaching: "Seizures cause lactic acidosis. A lower pH increases free tricyclic and widens the QRS.",
    },
    {
      id: "od-s3",
      domain: "airway",
      text: "Gives a bicarbonate bolus before induction and minimizes apnea time.",
      points: 2,
      teaching: "During apnea the pCO2 rises and pH falls. A pre induction bolus buys protection.",
    },
    {
      id: "od-s4",
      domain: "airway",
      text: "Uses reduced dose induction in hypotension, e.g. ketamine 0.5 to 1 mg/kg, with rocuronium 1.2 to 1.5 mg/kg.",
      points: 1,
      teaching: "A hypotensive patient needs less induction agent. Full dose paralysis gives the best first pass conditions.",
    },
    {
      id: "od-s5",
      domain: "airway",
      text: "Sets a high respiratory rate after intubation to avoid respiratory acidosis and targets pH 7.50 to 7.55.",
      points: 2,
      teaching: "The ventilator must match the patient's own high minute ventilation. Check a gas soon after.",
    },
    {
      id: "od-t1",
      domain: "tox",
      text: "Estimates the amitriptyline dose per kg and recognizes it as severe.",
      points: 1,
      teaching: "Tricyclic ingestions over about 10 mg/kg can be life threatening.",
    },
    {
      id: "od-t2",
      domain: "tox",
      text: "Sends acetaminophen, salicylate, ethanol, pregnancy test and electrolytes.",
      points: 1,
      teaching: "Every intentional overdose needs an acetaminophen level. Co ingestions are common and often silent early.",
    },
    {
      id: "od-t3",
      domain: "tox",
      text: "Starts acetylcysteine for a detectable acetaminophen level with an unknown time of ingestion.",
      points: 3,
      critical: true,
      teaching: "The nomogram needs a known time. If the time is unknown and the level is detectable, treat.",
    },
    {
      id: "od-t4",
      domain: "tox",
      text: "States a correct acetylcysteine regimen, e.g. 200 mg/kg over 4 hours then 100 mg/kg over 16 hours, or the three bag regimen.",
      points: 2,
      teaching: "Know one regimen well. Recheck liver tests and INR before stopping the infusion.",
    },
    {
      id: "od-t5",
      domain: "tox",
      text: "Gives activated charcoal only if the airway is protected and after discussion with the poison centre.",
      points: 1,
      teaching: "Charcoal in a drowsy patient who is about to seize risks aspiration. Protect the airway first.",
    },
    {
      id: "od-c1",
      domain: "comm",
      text: "Calls the Ontario Poison Centre early.",
      points: 1,
      teaching: "The poison centre gives real time advice on targets, rescue therapies and co ingestions.",
    },
    {
      id: "od-c2",
      domain: "comm",
      text: "Obtains collateral from the partner including the note and prior attempt.",
      points: 1,
      teaching: "Collateral shapes both the medical plan and the later suicide risk assessment.",
    },
    {
      id: "od-c3",
      domain: "comm",
      text: "Admits to ICU with a clear handover of bicarbonate targets and acetylcysteine timing.",
      points: 1,
      teaching: "State the QRS and pH targets and the start time of each acetylcysteine bag.",
    },
    {
      id: "od-m1",
      domain: "safety",
      text: "Performs a structured suicide risk assessment including intent, plan, note, prior attempt and supports.",
      points: 2,
      teaching: "A calm patient after a serious attempt can still be at high risk. Ask directly about intent.",
    },
    {
      id: "od-m2",
      domain: "safety",
      text: "Does not let her leave and uses a Form 1 under the Ontario Mental Health Act when criteria are met.",
      points: 3,
      critical: true,
      teaching: "A recent serious attempt with a note is high risk. A Form 1 allows safe assessment by psychiatry.",
    },
    {
      id: "od-m3",
      domain: "safety",
      text: "Knows a Form 1 allows detention up to 72 hours for psychiatric assessment and requires an exam within the past 7 days.",
      points: 1,
      teaching: "The form must be completed by a physician who personally examined the patient in the past 7 days.",
    },
    {
      id: "od-m4",
      domain: "safety",
      text: "Gives her a Form 42 and explains her rights.",
      points: 1,
      teaching: "Form 42 tells the patient why she is held and that she can speak to a lawyer.",
    },
    {
      id: "od-m5",
      domain: "safety",
      text: "Uses the least restrictive measures, arranges close observation, and removes means of self harm.",
      points: 1,
      teaching: "Start with talking and observation. Use restraint only when needed for safety.",
    },
  ],
  passThreshold: 0.6,
  reviewed: false,
  author: "Draft for review by Arjan Dhoot, MD",
  version: 1,
};
