// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: false, author: "Draft for review by Arjan Dhoot, MD", version: 1 } as const;

const S = {
  alsPcs: { id: "als-pcs", citation: "Ontario Ministry of Health. Advanced Life Support Patient Care Standards, including the base hospital medical directives." },
  blsPcs: { id: "bls-pcs", citation: "Ontario Ministry of Health. Basic Life Support Patient Care Standards, including the paramedic prompt cards for stroke, STEMI and field trauma triage." },
  hcca: { id: "hcca", citation: "Health Care Consent Act, 1996, S.O. 1996, c. 2, Sched. A (Ontario)." },
  criticall: { id: "criticall", citation: "CritiCall Ontario. Emergency consultation and referral service for Ontario hospitals." },
  ornge: { id: "ornge", citation: "Ornge. Air ambulance and critical care transport service for Ontario." },
  ccsStemi: { id: "ccs-stemi", citation: "Canadian Cardiovascular Society and Canadian Association of Interventional Cardiology. Guidelines on the acute management of ST-elevation myocardial infarction. Focused update on regionalization and reperfusion. Can J Cardiol. 2019.", url: "https://pubmed.ncbi.nlm.nih.gov/30760415/" },
  csbpr: { id: "csbpr", citation: "Heart and Stroke Foundation of Canada. Canadian Stroke Best Practice Recommendations. Acute stroke management." },
  fieldTriage: { id: "field-triage", citation: "American College of Surgeons Committee on Trauma. National Guideline for the Field Triage of Injured Patients." },
  atls: { id: "atls", citation: "American College of Surgeons Committee on Trauma. Advanced Trauma Life Support Student Course Manual. Chapter on transfer to definitive care." },
  btf: { id: "btf", citation: "Brain Trauma Foundation. Guidelines for the management of severe traumatic brain injury." },
  tor: { id: "tor", citation: "Morrison LJ, et al. Validation of a rule for termination of resuscitation in out-of-hospital cardiac arrest. N Engl J Med. 2006." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. Elsevier. Chapters on emergency medical services, air medical transport and disaster preparedness." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, et al, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. McGraw Hill. Chapters on prehospital care, mass gatherings, disasters and hazardous materials." },
  start: { id: "start", citation: "Benson M, Koenig KL, Schultz CH. Disaster triage: START, then SAVE. A new method of dynamic triage for victims of a catastrophic earthquake. Prehosp Disaster Med. 1996." },
  ohaCodes: { id: "oha-codes", citation: "Ontario Hospital Association. Emergency management toolkit and standardized hospital emergency codes." },
  trekkDka: { id: "trekk-dka", citation: "TREKK (Translating Emergency Knowledge for Kids). Bottom line recommendations. Diabetic ketoacidosis." },
  dcPeds: { id: "dc-peds", citation: "Diabetes Canada Clinical Practice Guidelines. Type 1 diabetes in children and adolescents." },
  uhms: { id: "uhms", citation: "Undersea and Hyperbaric Medical Society. Hyperbaric oxygen therapy indications. Carbon monoxide poisoning." },
  weaver: { id: "weaver", citation: "Weaver LK, et al. Hyperbaric oxygen for acute carbon monoxide poisoning. N Engl J Med. 2002." },
} satisfies Record<string, Source>;

export const EMS_SAMPS: Samp[] = [
  /* 01 ------------------------------------------------------------------ */
  {
    id: "ems-01",
    topic: "ems",
    alsoTopics: ["ischemic-heart-disease"],
    title: "Patch from a residence with chest pain",
    stem:
      "You are the emergency physician at a community hospital with no cardiac catheterization laboratory. The regional PCI centre is 35 minutes away by land. An advanced care paramedic crew patches to you from a home 10 minutes from your hospital. The patient is a 61 year old man with 40 minutes of crushing retrosternal pain. HR 88, BP 142/86, RR 20, SpO2 96% on room air. The paramedic reads the 12 lead ECG as 3 mm ST elevation in II, III and aVF with ST depression in I and aVL.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate direction to the crew? Select one.",
        options: [
          "Transport to your emergency department for fibrinolysis",
          "Bypass your hospital and transport directly to the PCI centre with cath lab pre-activation",
          "Transport to your emergency department for a physician confirmed ECG first",
          "Remain on scene and request an air ambulance",
          "Transport to your emergency department and arrange interfacility transfer after assessment",
        ],
        correct: 1,
        explanation:
          "Primary PCI is preferred when first medical contact to device time can be kept within 90 minutes. A 35 minute transport easily allows this. Stopping at a non-PCI hospital adds delay without benefit. Field STEMI bypass with pre-activation is the core of Canadian STEMI regionalization.",
        keyFeature: { topic: "ems", n: 1 },
        source: "ccs-stemi",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "The paramedic asks about giving nitroglycerin. List TWO pieces of information you need first.",
        accept: [
          { id: "sbp", text: "Current systolic blood pressure", match: ["blood pressure", "sbp", "systolic", "bp"] },
          { id: "pde5", text: "Recent phosphodiesterase 5 inhibitor use such as sildenafil or tadalafil", match: ["phosphodiesterase", "pde5", "pde", "sildenafil", "tadalafil", "vardenafil", "viagra", "erectile", "no pde5", "no sildenafil", "no viagra", "no tadalafil"] },
          { id: "rv", text: "Right sided ECG to look for right ventricular infarction", match: ["right sided", "v4r", "right ventricular", "rv infarct", "rv involvement", "no rv infarct", "no right ventricular"] },
          { id: "hr", text: "Heart rate, looking for bradycardia", match: ["heart rate", "bradycardia", "pulse"] },
        ],
        unacceptable: [{ text: "Troponin result", match: ["troponin"] }],
        explanation:
          "Inferior STEMI carries a real risk of right ventricular infarction, where nitrates drop preload and can cause profound hypotension. Hypotension and recent PDE5 inhibitor use are contraindications. A right sided V4 lead is quick in the field. A troponin has no role in this decision.",
        keyFeature: { topic: "ems", n: 1 },
        source: "als-pcs",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "One nitroglycerin spray was given before your call. En route the paramedic calls back. HR is 46 and BP 82/50. The patient is pale and lightheaded.",
        prompt: "List TWO field interventions you direct now.",
        accept: [
          { id: "stop", text: "Hold further nitroglycerin", match: ["stop nitro", "hold nitro", "no more nitro", "stop nitroglycerin", "hold nitroglycerin", "no further nitro", "no further nitroglycerin", "no more nitroglycerin", "no nitroglycerin", "no nitro", "stop nitrate", "hold nitrate", "no nitrate", "no further nitrate"] },
          { id: "fluid", text: "Normal saline bolus, for example 250 to 500 mL IV", match: ["fluid", "saline", "bolus", "ringer"] },
          { id: "atropine", text: "Atropine IV for symptomatic bradycardia", match: ["atropine"] },
          { id: "supine", text: "Lay the patient supine and raise the legs", match: ["supine", "legs", "trendelenburg", "lie flat"] },
          { id: "pace", text: "Apply pads and prepare transcutaneous pacing if atropine fails", match: ["pacing", "pace"] },
        ],
        unacceptable: [{ text: "Another dose of nitroglycerin", match: ["repeat nitro", "another nitro", "second nitro", "repeat nitroglycerin", "another nitroglycerin", "second nitroglycerin", "more nitroglycerin", "repeat nitrate", "another nitrate"], dangerous: true }],
        explanation:
          "Hypotension and bradycardia after a nitrate in inferior STEMI suggest right ventricular involvement and a vagal reflex. Treat with volume, atropine and positioning. More nitrate would deepen shock. Pacing is the backup if atropine fails.",
        keyFeature: { topic: "ems", n: 1 },
        source: "als-pcs",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO time points the crew must relay to the PCI team at handover.",
        accept: [
          { id: "onset", text: "Symptom onset time", match: ["onset", "pain started", "symptom start"] },
          { id: "fmc", text: "Time of first medical contact", match: ["first medical contact", "first contact", "fmc", "patient contact", "arrival on scene"] },
          { id: "ecg", text: "Time of the first diagnostic ECG", match: ["ecg", "12 lead"] },
          { id: "meds", text: "Times and doses of ASA and nitroglycerin given", match: ["asa", "aspirin", "nitroglycerin", "nitro", "medication"] },
          { id: "change", text: "Time of the hypotensive bradycardic episode and response", match: ["hypotension", "hypotensive", "bradycardia", "bradycardic", "deterioration", "episode"] },
        ],
        explanation:
          "Reperfusion decisions and quality metrics depend on onset and first contact times that only the crew witnessed. Treatments and deterioration en route are also information only EMS holds. Missing them leads to repeat dosing or a missed right ventricular infarction.",
        keyFeature: { topic: "ems", n: 2 },
        source: "ccs-stemi",
      },
    ],
    sources: [S.ccsStemi, S.alsPcs],
    ...META,
  },

  /* 02 ------------------------------------------------------------------ */
  {
    id: "ems-02",
    topic: "ems",
    alsoTopics: ["cva"],
    title: "Highway patch with sudden weakness",
    stem:
      "You work in a small rural emergency department with no CT scanner. A primary care paramedic crew patches from a highway rest stop. A 72 year old woman developed sudden right arm and face weakness and difficulty speaking. Her husband says she was last seen well 70 minutes ago. HR 92 irregular, BP 188/102, SpO2 95% on room air, glucose 6.2 mmol/L. The crew's large vessel occlusion screen is positive with left gaze deviation, aphasia and a dense right arm. Your ED is 15 minutes away. The regional comprehensive stroke centre that offers thrombolysis and thrombectomy is 45 minutes away.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate direction? Select one.",
        options: [
          "Transport to your emergency department for assessment first",
          "Transport directly to the comprehensive stroke centre with pre-notification",
          "Remain on scene until an air ambulance arrives",
          "Transport to your emergency department and arrange CT at another site",
          "Give ASA 160 mg chewed and transport to the nearest hospital",
        ],
        correct: 1,
        explanation:
          "She meets field criteria for the acute stroke protocol with a positive LVO screen and is well inside the treatment window. Your hospital cannot image or treat her, so stopping only delays reperfusion. Direct transport with pre-notification lets the stroke team meet her at the door.",
        keyFeature: { topic: "ems", n: 1 },
        source: "csbpr",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE things you ask the crew to confirm or bring before leaving the scene.",
        accept: [
          { id: "lkw", text: "Exact last known well time", match: ["last known well", "last seen well", "lkw", "onset time", "time of onset"] },
          { id: "witness", text: "Bring the husband or get his phone number for the stroke team", match: ["husband", "witness", "phone number", "contact number", "family"] },
          { id: "anticoag", text: "Anticoagulant use, ideally the medication list or bottles", match: ["anticoagulant", "blood thinner", "warfarin", "doac", "apixaban", "rivaroxaban", "dabigatran", "medication list", "med list", "medication"] },
          { id: "baseline", text: "Baseline function and independence", match: ["baseline", "premorbid", "functional status"] },
          { id: "history", text: "Recent surgery, bleeding, seizure or head injury", match: ["surgery", "bleeding", "seizure", "head injury", "trauma"] },
          { id: "weight", text: "Estimated weight", match: ["weight"] },
        ],
        explanation:
          "Thrombolysis and thrombectomy decisions depend on onset time, anticoagulant use and baseline function. The husband is the only reliable witness, so he or his number must travel with her. The paramedics are the only people who can secure this information now.",
        keyFeature: { topic: "ems", n: 2 },
        source: "csbpr",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO en route instructions for this patient.",
        accept: [
          { id: "npo", text: "Nothing by mouth until a swallow screen is done", match: ["npo", "nothing by mouth", "nil by mouth", "swallow"] },
          { id: "iv", text: "IV access if within scope without delaying transport", match: ["iv access", "intravenous access", "iv line"] },
          { id: "glucose", text: "Recheck glucose if she changes", match: ["glucose", "sugar"] },
          { id: "o2", text: "Oxygen only if SpO2 falls below about 94%", match: ["oxygen", "o2", "saturation"] },
          { id: "prenotify", text: "Pre-notify the stroke centre with ETA and findings", match: ["notify", "prenotify", "pre notify", "alert", "patch"] },
          { id: "bp", text: "Do not lower blood pressure in the field", match: ["not lower", "don lower", "dont lower", "avoid lowering", "not treat blood pressure", "not treat bp", "don treat bp", "permissive hypertension", "no antihypertensive"] },
          { id: "position", text: "Protect the airway and position on her side if vomiting", match: ["airway", "lateral", "recovery position"] },
          { id: "noasa", text: "No ASA or other antithrombotic until imaging excludes hemorrhage", match: ["no asa", "avoid asa", "hold asa", "withhold asa", "no aspirin", "avoid aspirin", "hold aspirin", "no antiplatelet", "no antithrombotic"] },
        ],
        unacceptable: [
          { text: "ASA before imaging", match: ["asa", "aspirin"], dangerous: true },
          { text: "Lower the blood pressure in the field", match: ["lower blood pressure", "nitro", "antihypertensive", "reduce bp", "lower bp"] },
        ],
        explanation:
          "Keep her NPO, monitor glucose and airway, and pre-notify. ASA before CT can harm a patient with hemorrhage and delays nothing useful. Field blood pressure is not treated. In hospital it is lowered below 185/110 only if thrombolysis is planned.",
        keyFeature: { topic: "ems", n: 1 },
        source: "csbpr",
      },
      {
        id: "q4",
        kind: "single",
        update: "Twenty minutes into transport the crew calls back. She had a generalized seizure that has now stopped, but she is snoring, SpO2 is 84% despite an oral airway and bag valve mask, and she has vomited. The stroke centre is still 25 minutes away. Your ED is 10 minutes away.",
        prompt: "Which is the most appropriate direction? Select one.",
        options: [
          "Continue to the stroke centre because thrombectomy is time critical",
          "Divert to your emergency department for airway management",
          "Stop the ambulance and wait for an advanced care paramedic intercept",
          "Continue to the stroke centre and give oral glucose",
          "Return to the rest stop and request air ambulance",
        ],
        correct: 1,
        explanation:
          "An airway that primary care paramedics cannot maintain is an indication to go to the closest emergency department. Hypoxia will harm the brain far more than a brief delay to thrombectomy. Your team should prepare suction and intubation equipment and arrange onward transfer after stabilization.",
        keyFeature: { topic: "ems", n: 1 },
        source: "bls-pcs",
      },
    ],
    sources: [S.csbpr, S.blsPcs],
    ...META,
  },

  /* 03 ------------------------------------------------------------------ */
  {
    id: "ems-03",
    topic: "ems",
    alsoTopics: ["multiple-trauma"],
    title: "Incoming patients from a highway collision",
    stem:
      "You are the emergency physician at a lead trauma hospital at 0200. An advanced care paramedic crew patches to report a single vehicle rollover on the highway. Their patient is a 28 year old man who was ejected. GCS 8, HR 132, BP 78/40, RR 28, SpO2 90% on high flow oxygen. A second crew is bringing the driver, who has a femur deformity but stable vital signs. ETA for the first patient is 12 minutes.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE further pieces of information you want from the crew during this patch.",
        accept: [
          { id: "injuries", text: "Injuries found, such as chest, abdomen, pelvis or long bone", match: ["injuries", "injury", "chest", "abdomen", "pelvi"] },
          { id: "treatment", text: "Treatments given, such as fluids, airway adjunct or pelvic binder", match: ["treatment", "fluid", "intervention", "binder", "given"] },
          { id: "airway", text: "Airway status and whether they can oxygenate and ventilate", match: ["airway", "intubate", "intubation", "intubated", "ventilate", "ventilation", "ventilator"] },
          { id: "trend", text: "Trend in vital signs and GCS since the scene", match: ["trend", "change", "repeat vital", "improving", "worsening"] },
          { id: "mech", text: "Mechanism details such as speed, ejection distance or deaths at scene", match: ["mechanism", "speed", "ejection", "death", "extrication"] },
          { id: "age", text: "Age, sex and known history or anticoagulants", match: ["age", "anticoagulant", "history", "medication"] },
          { id: "count", text: "Total number of patients and their ETAs", match: ["number of patient", "how many", "eta", "other patient"] },
        ],
        explanation:
          "A structured report such as MIST covers mechanism, injuries, signs and treatment. Knowing whether the airway is failing and whether the patient is responding to fluids decides who meets him at the door. The number of patients and ETAs shapes how many teams you need.",
        keyFeature: { topic: "ems", n: 1 },
        source: "atls",
      },
      {
        id: "q2",
        kind: "short",
        required: 4,
        prompt: "List FOUR actions to prepare your department and hospital before the first patient arrives.",
        accept: [
          { id: "team", text: "Activate the trauma team", match: ["trauma team", "trauma code", "activate trauma"] },
          { id: "mtp", text: "Activate the massive haemorrhage protocol with uncrossmatched O blood in the room", match: ["massive", "mhp", "mtp", "o negative", "o neg", "uncrossmatched", "blood"] },
          { id: "or", text: "Notify the trauma surgeon and the operating room", match: ["operating room", "surgeon", "surgery", "notify or"] },
          { id: "airway", text: "Prepare RSI drugs and difficult airway equipment", match: ["airway", "rsi", "intubation", "video laryngoscope"] },
          { id: "bay", text: "Assign separate resuscitation bays and teams for both patients", match: ["bay", "room", "second team", "two team"] },
          { id: "staff", text: "Call in backup physician, anesthesia or respiratory therapy", match: ["backup", "back up", "anesthesia", "anaesthesia", "respiratory therap", "call in"] },
          { id: "ct", text: "Alert CT and radiology", match: ["ct", "radiology", "imaging"] },
          { id: "infuser", text: "Rapid infuser, warmer and chest tube tray ready", match: ["rapid infuser", "level 1", "warmer", "chest tube", "thoracostomy"] },
          { id: "icu", text: "Notify ICU", match: ["icu", "intensive care"] },
          { id: "txa", text: "Tranexamic acid ready", match: ["tranexamic", "txa"] },
        ],
        explanation:
          "A hypotensive, hypoxic, head injured patient needs a full team, blood and a surgeon on arrival. At 0200 your in-house resources are thin, so early calls for backup matter. The second patient needs a separate space and team so the first resuscitation is not diluted.",
        keyFeature: { topic: "ems", n: 1 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "The patient arrives. The paramedic gives a brief handover while your team moves him to the stretcher.",
        prompt: "List THREE pieces of information that only the paramedics can give you.",
        accept: [
          { id: "scene", text: "Scene findings such as vehicle damage, intrusion or ejection distance", match: ["scene", "vehicle", "intrusion", "ejection", "damage", "rollover"] },
          { id: "gcs", text: "GCS at scene and any lucid interval", match: ["gcs", "level of consciousness", "loc", "lucid", "initial neuro", "initial neurological", "initial neurologic"] },
          { id: "vitals", text: "First set of vital signs and how they changed", match: ["vital", "initial blood pressure", "trend", "changed"] },
          { id: "tx", text: "Treatments given and response, including fluid volume", match: ["treatment", "fluid", "given", "response", "medication"] },
          { id: "time", text: "Time of injury and extrication time", match: ["time of injury", "extrication", "time"] },
          { id: "restraint", text: "Seatbelt use and airbag deployment", match: ["seatbelt", "seat belt", "restraint", "airbag"] },
          { id: "others", text: "Condition of other occupants, including any death at scene", match: ["death", "other occupant", "fatality", "driver"] },
          { id: "motor", text: "Early neurological exam such as limb movement before sedation", match: ["moving limb", "limb", "motor", "movement"] },
        ],
        explanation:
          "Scene details, initial neurological status and response to prehospital treatment cannot be recovered once the crew leaves. A lucid interval or a fall in GCS points toward an expanding intracranial lesion. A death in the same vehicle is a marker of high energy.",
        keyFeature: { topic: "ems", n: 2 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which finding reported by the crew is a field triage criterion that on its own justifies bypass to a trauma centre? Select one.",
        options: [
          "Age over 55",
          "Ejection from the vehicle",
          "Isolated closed wrist fracture",
          "Intoxication",
          "Vehicle speed of 50 km/h",
        ],
        correct: 1,
        explanation:
          "Ejection is a high risk mechanism criterion in field triage guidelines. Age and intoxication are special considerations that lower the threshold but do not mandate bypass alone. The physiological criteria this patient also meets, GCS and hypotension, are the strongest triggers.",
        keyFeature: { topic: "ems", n: 1 },
        source: "field-triage",
      },
    ],
    sources: [S.atls, S.fieldTriage],
    ...META,
  },

  /* 04 ------------------------------------------------------------------ */
  {
    id: "ems-04",
    topic: "ems",
    title: "Request for direction during a home resuscitation",
    stem:
      "You are the base hospital physician on call. An advanced care paramedic crew patches from a rural home 40 minutes from the nearest hospital. A 68 year old man collapsed in his garage. His wife found him and called 911, but no one started CPR. The first rhythm was asystole. After 22 minutes of resuscitation with a supraglottic airway, three doses of epinephrine and no shocks, he remains in asystole. End tidal CO2 is 8 mmHg. The garage is heated and he is warm to touch. No vehicle or fuel burning appliance was running. The crew asks for direction.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate direction? Select one.",
        options: [
          "Authorize termination of resuscitation in the home",
          "Load and transport with ongoing CPR",
          "Continue resuscitation on scene for another 20 minutes",
          "Give sodium bicarbonate and reassess",
          "Request a helicopter for ECPR",
        ],
        correct: 0,
        explanation:
          "He meets the validated termination of resuscitation rule. The arrest was not witnessed by EMS, no shock was delivered and there has been no return of circulation. Transport with CPR in a moving vehicle gives poor quality compressions and a negligible chance of survival. Refractory asystole with low end tidal CO2 does not qualify for ECPR.",
        keyFeature: { topic: "ems", n: 1 },
        source: "tor",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE features of this arrest that support termination.",
        accept: [
          { id: "notems", text: "Arrest not witnessed by EMS", match: ["not witnessed by ems", "not ems witnessed", "unwitnessed by ems", "unwitnessed", "not witnessed"] },
          { id: "noshock", text: "No shock delivered", match: ["no shock", "not shocked", "non shockable", "nonshockable", "asystole"] },
          { id: "norosc", text: "No return of spontaneous circulation", match: ["no rosc", "no return", "never had rosc", "without rosc"] },
          { id: "nocpr", text: "No bystander CPR", match: ["no bystander", "bystander"] },
          { id: "etco2", text: "End tidal CO2 below 10 mmHg after 20 minutes", match: ["etco2", "end tidal", "co2", "capnography"] },
          { id: "duration", text: "More than 20 minutes of advanced resuscitation", match: ["20 minute", "22 minute", "duration", "prolonged"] },
        ],
        explanation:
          "The BLS rule uses three criteria: not EMS witnessed, no shock and no ROSC. The ALS rule adds no bystander witness and no bystander CPR. Persistently low end tidal CO2 after 20 minutes adds prognostic weight.",
        keyFeature: { topic: "ems", n: 1 },
        source: "tor",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO circumstances that would make you continue resuscitation and transport instead.",
        accept: [
          { id: "hypo", text: "Hypothermia", match: ["hypothermia", "hypothermic", "cold"] },
          { id: "tox", text: "Suspected poisoning or overdose", match: ["overdose", "poison", "tox", "toxic", "toxicity", "ingestion"] },
          { id: "preg", text: "Pregnancy", match: ["pregnant", "pregnancy"] },
          { id: "emswit", text: "Arrest witnessed by paramedics", match: ["ems witnessed", "witnessed by ems", "paramedic witnessed", "witnessed by paramedic"] },
          { id: "vf", text: "Shockable rhythm or any shock delivered", match: ["shockable", "vf", "ventricular fibrillation", "shock"] },
          { id: "rosc", text: "Any return of spontaneous circulation", match: ["rosc", "return of spontaneous"] },
          { id: "drown", text: "Drowning or asphyxia in a young patient", match: ["drowning", "drowned", "drown", "asphyxia", "hanging"] },
          { id: "safety", text: "Unsafe scene or family distress that prevents termination", match: ["unsafe", "safety", "hostile"] },
        ],
        unacceptable: [{ text: "Family asks for everything to be done", match: ["family wishe", "family request"] }],
        explanation:
          "Hypothermia and poisoning are reversible causes where prolonged resuscitation can succeed. Pregnancy changes the goals. Any shock, EMS witnessed arrest or ROSC means the rule is not met. Family wishes deserve a careful conversation but do not change the physiology.",
        keyFeature: { topic: "ems", n: 1 },
        source: "als-pcs",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "You authorize termination of resuscitation.",
        prompt: "List TWO further instructions you give the crew.",
        accept: [
          { id: "doc", text: "Document the time of death and your name as the authorizing physician", match: ["document", "time of death", "physician name", "record"] },
          { id: "family", text: "Support the wife and arrange someone to stay with her", match: ["wife", "family", "support", "bereavement", "grief"] },
          { id: "coroner", text: "Notify police or the coroner as required for a sudden death", match: ["coroner", "police"] },
          { id: "devices", text: "Leave airway and IV devices in place for the coroner", match: ["leave device", "leave airway", "leave tube", "leave line", "in place"] },
          { id: "debrief", text: "Offer a crew debrief", match: ["debrief"] },
        ],
        explanation:
          "Termination is a clinical and legal act. Record time and authorizing physician, involve police or coroner for an unexpected death, and leave devices in place. The wife should not be left alone in the home.",
        keyFeature: { topic: "ems", n: 1 },
        source: "als-pcs",
      },
    ],
    sources: [S.tor, S.alsPcs],
    ...META,
  },

  /* 05 ------------------------------------------------------------------ */
  {
    id: "ems-05",
    topic: "ems",
    title: "A patient who wants the crew to leave",
    stem:
      "You are the base hospital physician in Ontario. A primary care paramedic crew patches from a home. A 58 year old man with type 2 diabetes was found confused and sweaty by his wife. Glucose was 1.9 mmol/L. He received glucagon 1 mg IM and then oral glucose gel. Twenty minutes later he is alert and oriented, glucose 5.8 mmol/L, and he wants the crew to leave. His medications are glyburide and metformin. He skipped lunch after taking glyburide.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO abilities he must show to be capable of refusing transport.",
        accept: [
          { id: "understand", text: "Understand the information relevant to the decision", match: ["understand"] },
          { id: "appreciate", text: "Appreciate the reasonably foreseeable consequences of refusing", match: ["appreciate", "consequence"] },
          { id: "communicate", text: "Communicate a clear and consistent choice", match: ["communicate", "express a choice", "consistent choice"] },
          { id: "reason", text: "Reason with the information and weigh options", match: ["reason", "weigh", "manipulate"] },
        ],
        unacceptable: [{ text: "Being alert and oriented", match: ["oriented", "orientation", "alert"] }],
        explanation:
          "The Health Care Consent Act defines capacity as the ability to understand relevant information and to appreciate the reasonably foreseeable consequences of a decision. Clinical capacity frameworks used across Canada add communicating a consistent choice and reasoning with the information. Orientation alone does not establish capacity.",
        keyFeature: { topic: "ems", n: 1 },
        source: "hcca",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate advice to the crew? Select one.",
        options: [
          "Release him after he eats a meal, since glucose is now normal",
          "Strongly advise transport for observation because recurrent hypoglycemia is likely",
          "Give a second dose of glucagon, then release him",
          "Release him if his wife agrees to check his glucose in the morning",
          "Transport him against his will because he is diabetic",
        ],
        correct: 1,
        explanation:
          "Sulfonylureas cause prolonged and recurrent hypoglycemia. Glucagon effect lasts well under an hour and hepatic glycogen may be depleted. Treat and release is unsafe in sulfonylurea hypoglycemia, so the crew should recommend ED observation.",
        keyFeature: { topic: "ems", n: 1 },
        source: "als-pcs",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "You speak to him on the patch. He understands the risk and the consequences and still refuses. He is capable.",
        prompt: "List THREE instructions you give the crew before they leave.",
        accept: [
          { id: "meal", text: "Ensure he eats a meal with complex carbohydrate before they leave", match: ["eat", "meal", "carbohydrate", "food"] },
          { id: "adult", text: "Confirm a responsible adult will stay with him", match: ["adult", "wife", "stay with", "not alone"] },
          { id: "return", text: "Clear instructions to call 911 if symptoms recur", match: ["call 911", "call back", "return", "911"] },
          { id: "glucose", text: "Frequent glucose checks overnight", match: ["glucose check", "check glucose", "monitor glucose", "check sugar", "monitor sugar", "fingerstick"] },
          { id: "hold", text: "Hold glyburide until reviewed by his physician", match: ["hold glyburide", "stop glyburide", "hold sulfonylurea", "stop sulfonylurea"] },
          { id: "doc", text: "Document the refusal, capacity assessment and advice given, with his signature", match: ["document", "sign", "refusal form"] },
          { id: "followup", text: "Arrange follow up with his family physician", match: ["family physician", "follow up", "family doctor"] },
        ],
        explanation:
          "A capable patient may refuse. The goal becomes harm reduction: food, supervision, monitoring, stopping the sulfonylurea and a clear plan to call back. Careful documentation protects the patient and the crew.",
        keyFeature: { topic: "ems", n: 1 },
        source: "hcca",
      },
      {
        id: "q4",
        kind: "single",
        update: "Three hours later his wife calls 911 again. He is sweaty, combative and confused. Glucose is 2.0 mmol/L. He shouts at the crew to leave him alone.",
        prompt: "What is the legal basis for treating and transporting him now? Select one.",
        options: [
          "A Form 1 under the Mental Health Act",
          "Consent from his wife as substitute decision maker is required first",
          "Emergency treatment without consent, since he is incapable and delay would cause serious harm",
          "His earlier refusal must be respected",
          "Police apprehension is required before any treatment",
        ],
        correct: 2,
        explanation:
          "Under the Health Care Consent Act, treatment may be given without consent in an emergency when the person is incapable and delay would risk serious harm. His earlier capable refusal does not apply to this new incapable state. A Form 1 is a physician tool for mental disorder and does not apply here.",
        keyFeature: { topic: "ems", n: 1 },
        source: "hcca",
      },
    ],
    sources: [S.hcca, S.alsPcs],
    ...META,
  },

  /* 06 ------------------------------------------------------------------ */
  {
    id: "ems-06",
    topic: "ems",
    alsoTopics: ["tox"],
    title: "Handover from a hotel call",
    stem:
      "A paramedic crew brings in a 24 year old man found unresponsive on a hotel bathroom floor by a friend. He is now drowsy but rousable. HR 96, BP 118/72, RR 12, SpO2 93% on 2 L nasal prongs, glucose 6.4 mmol/L. His pupils are small. The crew is eager to leave for another call.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 4,
        prompt: "List FOUR pieces of information you want from the crew before they leave.",
        accept: [
          { id: "nalox", text: "Naloxone dose, route, timing and response", match: ["naloxone", "narcan"] },
          { id: "initial", text: "Initial vital signs including RR, SpO2 and GCS", match: ["initial", "first vital", "vital sign", "saturation", "respiratory rate", "gcs"] },
          { id: "found", text: "When he was last seen well and time found", match: ["last seen", "time found", "down time", "downtime", "how long"] },
          { id: "drugs", text: "Drugs, pills or paraphernalia found at the scene", match: ["paraphernalia", "pill", "drug", "bottle", "substance", "powder"] },
          { id: "bvm", text: "Whether he needed bag valve mask ventilation", match: ["bag", "bvm", "ventilate", "ventilation", "ventilator", "rescue breath"] },
          { id: "vomit", text: "Vomiting or possible aspiration", match: ["vomit", "aspiration", "aspirate"] },
          { id: "trauma", text: "Signs of a fall, head strike or long lie", match: ["fall", "head", "trauma", "lie", "position found"] },
          { id: "friend", text: "Friend's account and contact number", match: ["friend", "witness", "contact"] },
          { id: "note", text: "Any note or evidence of self harm", match: ["note", "self harm", "suicide", "suicidal"] },
        ],
        explanation:
          "Scene findings, how long he was down, initial oxygenation and the naloxone given are known only to the crew. A long lie raises concern for rhabdomyolysis and compartment syndrome. A note changes the risk assessment entirely.",
        keyFeature: { topic: "ems", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "The crew says he had RR 4 and SpO2 70% when found. He received naloxone 0.4 mg IM and 2 mg intranasal with only partial improvement in breathing after 10 minutes. His friend said the powder was sold as fentanyl.",
        prompt: "List TWO explanations for the partial response to naloxone that you must consider.",
        accept: [
          { id: "benzo", text: "Non-opioid sedative adulterant such as a novel benzodiazepine", match: ["benzodiazepine", "benzo", "etizolam", "bromazolam", "sedative"] },
          { id: "xylazine", text: "Xylazine or another veterinary sedative adulterant", match: ["xylazine", "alpha 2", "medetomidine", "veterinary"] },
          { id: "hypoxic", text: "Hypoxic brain injury from the period of hypoventilation", match: ["hypoxic", "anoxic", "brain injury"] },
          { id: "potent", text: "High potency or large opioid dose needing more naloxone", match: ["potent", "carfentanil", "more naloxone", "insufficient dose", "inadequate dose"] },
          { id: "head", text: "Head injury from the fall", match: ["head injury", "intracranial", "head trauma"] },
          { id: "aspiration", text: "Aspiration pneumonitis causing hypoxia", match: ["aspiration"] },
          { id: "coing", text: "Co-ingestion such as alcohol or other drugs", match: ["alcohol", "co ingestion", "coingestion", "other drug"] },
        ],
        explanation:
          "Canadian unregulated opioid supplies often contain benzodiazepine analogues or xylazine that naloxone does not reverse. A long hypoxic period can cause brain injury. Titrate naloxone to breathing and support ventilation rather than chasing full wakefulness.",
        keyFeature: { topic: "ems", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which additional piece of EMS information would most lengthen your observation period? Select one.",
        options: [
          "Naloxone was given intranasally",
          "A methadone bottle with his name was found in his bag",
          "He was found in a hotel rather than at home",
          "He vomited once in the ambulance and is now alert",
          "His friend also used the same powder and is well",
        ],
        correct: 1,
        explanation:
          "Methadone has a long and variable half life, so respiratory depression can recur hours after naloxone wears off. Observation should be extended, often with a naloxone infusion if doses are repeatedly needed. The route of naloxone and the setting do not change the observation period.",
        keyFeature: { topic: "ems", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },

  /* 07 ------------------------------------------------------------------ */
  {
    id: "ems-07",
    topic: "ems",
    alsoTopics: ["tox"],
    title: "Handover of an older woman found on the floor",
    stem:
      "A primary care paramedic crew brings in an 84 year old woman found on her kitchen floor by a neighbour this morning. She lives alone. She is drowsy, oriented to person only, and cannot say how long she was down. HR 104, BP 104/60, RR 20, SpO2 95% on room air, temperature 35.1 C.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 4,
        prompt: "List FOUR questions to ask the paramedics about the scene.",
        accept: [
          { id: "lastseen", text: "When she was last seen or heard from well", match: ["last seen", "last known", "last spoke", "how long", "down time", "downtime"] },
          { id: "temp", text: "Temperature inside the home", match: ["temperature", "cold", "heat", "thermostat"] },
          { id: "meds", text: "Medications found, including blister packs and missing pills", match: ["medication", "pill", "blister", "bottle", "dosette"] },
          { id: "position", text: "Position found, pressure areas, urine or stool", match: ["position", "pressure", "urine", "incontinence", "incontinent", "stool", "soiled"] },
          { id: "vomit", text: "Vomit, blood or signs of head strike", match: ["vomit", "blood", "head strike", "hit her head"] },
          { id: "alcohol", text: "Alcohol containers or other substances", match: ["alcohol", "substance", "bottle"] },
          { id: "home", text: "Condition of the home and food supply, suggesting self neglect", match: ["condition of home", "food", "neglect", "hoard", "clean"] },
          { id: "glucose", text: "Glucose at scene", match: ["glucose", "sugar"] },
          { id: "gas", text: "Fuel burning appliances, gas smell or CO alarm", match: ["gas", "co alarm", "carbon monoxide", "furnace", "heater"] },
          { id: "contacts", text: "Name and number of family or neighbour", match: ["family", "neighbour", "neighbor", "contact", "next of kin"] },
        ],
        explanation:
          "Time on the floor predicts rhabdomyolysis, pressure injury and hypothermia. The home environment reveals medication errors, self neglect and exposure risks. These details disappear once the crew leaves, and the patient cannot provide them.",
        keyFeature: { topic: "ems", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "The crew tells you the house was cold because the furnace was not working. The neighbour who found her had a headache and felt nauseated. A space heater was running in the kitchen.",
        prompt: "List THREE actions you take now.",
        accept: [
          { id: "cohb", text: "Measure carboxyhemoglobin on a venous or arterial co-oximetry gas", match: ["carboxyhemoglobin", "carboxyhaemoglobin", "cohb", "co level", "co oximetry", "carbon monoxide level"] },
          { id: "o2", text: "High flow oxygen by non-rebreather mask", match: ["non rebreather", "nonrebreather", "high flow oxygen", "100% oxygen", "100% o2", "nrb"] },
          { id: "neighbour", text: "Have the neighbour assessed for CO exposure", match: ["neighbour", "neighbor"] },
          { id: "fire", text: "Ask EMS or fire services to check the home and warn anyone else there", match: ["fire", "check the home", "check home", "gas company", "utility"] },
          { id: "ecg", text: "ECG and troponin to look for myocardial injury", match: ["ecg", "troponin"] },
          { id: "ck", text: "CK and renal function for rhabdomyolysis", match: ["ck", "creatine kinase", "rhabdo", "rhabdomyolysis"] },
          { id: "warm", text: "Rewarm with forced air warming", match: ["warm", "rewarm", "warming", "forced air"] },
        ],
        unacceptable: [{ text: "Rely on pulse oximetry to exclude CO poisoning", match: ["pulse oximetry normal", "spo2 normal"] }],
        explanation:
          "A fuel burning heater in a closed cold house and a symptomatic neighbour point to carbon monoxide. Pulse oximetry cannot detect carboxyhemoglobin, so a co-oximetry gas is needed. Others may still be exposed, so fire services should check the home.",
        keyFeature: { topic: "ems", n: 2 },
        source: "uhms",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Her carboxyhemoglobin is 24% and she remains confused after an hour of oxygen. Which is the most appropriate next step? Select one.",
        options: [
          "Continue non-rebreather oxygen and recheck the level in 6 hours",
          "Discuss hyperbaric oxygen with the regional hyperbaric centre",
          "Give hydroxocobalamin 5 g IV",
          "Intubate for hyperventilation",
          "Discharge once the level is below 10%",
        ],
        correct: 1,
        explanation:
          "Persistent neurological abnormality after CO exposure is an accepted indication to discuss hyperbaric oxygen. It may reduce delayed neurocognitive sequelae. Hydroxocobalamin is for cyanide, which is not expected from a space heater.",
        keyFeature: { topic: "tox", n: 2 },
        source: "weaver",
      },
    ],
    sources: [S.rosen, S.uhms, S.weaver],
    ...META,
  },

  /* 08 ------------------------------------------------------------------ */
  {
    id: "ems-08",
    topic: "ems",
    alsoTopics: ["multiple-trauma"],
    title: "A deteriorating hockey player in a rural hospital",
    stem:
      "You are working alone overnight in a rural hospital 250 km from the nearest neurosurgical centre. A 19 year old man fell backward at a hockey game and struck his head on the ice. He was briefly unconscious, then talking normally for an hour. Now his GCS is 9 (E2 V2 M5). Left pupil is 5 mm and sluggish. HR 64, BP 162/88, SpO2 96% on room air. CT shows a 2.5 cm left temporal epidural hematoma with 6 mm midline shift.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO calls you make to arrange definitive care.",
        accept: [
          { id: "criticall", text: "The provincial transfer and bed access line, such as CritiCall in Ontario, for an accepting bed", match: ["criticall", "critical call", "transfer centre", "transfer center", "transfer line", "bed access", "accepting bed", "patient transfer"] },
          { id: "neuro", text: "Neurosurgeon at the regional centre", match: ["neurosurgery", "neurosurgeon", "neurosurgical"] },
          { id: "ornge", text: "Ornge or the critical care transport service", match: ["ornge", "air ambulance", "critical care transport", "transport team", "flight"] },
          { id: "anesthesia", text: "Local anesthesia or a colleague to help with airway and transport", match: ["anesthesia", "anesthetist", "anesthesiologist", "anesthetic", "anaesthesia", "anaesthetist", "anaesthetic", "colleague", "backup", "back up"] },
        ],
        explanation:
          "A provincial transfer line, such as CritiCall in Ontario, links the referring physician to the neurosurgeon and secures a bed at once. Transport should be requested early, in parallel, because transport time is the main delay. Calling for local help lets you keep managing the patient.",
        keyFeature: { topic: "ems", n: 3 },
        source: "criticall",
      },
      {
        id: "q2",
        kind: "short",
        required: 4,
        prompt: "List FOUR things you do to prepare him for a long transfer.",
        accept: [
          { id: "intubate", text: "Intubate to protect the airway", match: ["intubate", "intubation", "intubated", "secure airway", "ett", "rsi"] },
          { id: "iv", text: "Two large bore IVs", match: ["two iv", "2 iv", "large bore", "iv access"] },
          { id: "og", text: "Orogastric tube", match: ["orogastric", "og tube", "ng tube", "nasogastric", "gastric tube"] },
          { id: "hob", text: "Head of bed up 30 degrees with neck neutral", match: ["head of bed", "30 degree", "elevate head", "hob"] },
          { id: "co2", text: "Continuous end tidal CO2 with PaCO2 target 35 to 40 mmHg", match: ["end tidal", "etco2", "capnography", "paco2", "normocapnia"] },
          { id: "bp", text: "Avoid hypotension, keeping systolic above 110 mmHg", match: ["avoid hypotension", "prevent hypotension", "no hypotension", "hypotension", "systolic", "blood pressure", "map", "sbp"] },
          { id: "hyperosm", text: "Hyperosmolar therapy with mannitol or hypertonic saline", match: ["mannitol", "hypertonic", "3% saline", "hyperosmolar", "23.4%"] },
          { id: "sedation", text: "Adequate sedation and analgesia after intubation", match: ["sedation", "analgesia", "propofol", "fentanyl"] },
          { id: "collar", text: "Cervical collar or spinal motion restriction", match: ["collar", "c spine", "cervical", "spinal"] },
          { id: "images", text: "Send CT images electronically and copies of the chart", match: ["image", "chart", "record", "pacs"] },
          { id: "cxr", text: "Chest X-ray to confirm tube position", match: ["chest x ray", "cxr", "tube position"] },
          { id: "glucose", text: "Avoid hypoxia and hypoglycemia", match: ["avoid hypoxia", "prevent hypoxia", "no hypoxia", "hypoxia", "oxygen", "avoid hypoglycemia", "glucose"] },
        ],
        explanation:
          "A falling GCS with a dilating pupil means he cannot protect his airway during hours of transport. Secure the airway and lines before departure, because procedures in a moving aircraft are hard. Avoid hypoxia, hypotension and hypercapnia, which all worsen secondary brain injury.",
        keyFeature: { topic: "ems", n: 3 },
        source: "atls",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        update: "While waiting for the aircraft, his left pupil becomes 7 mm and fixed and he develops extensor posturing.",
        prompt: "Select TWO appropriate immediate interventions.",
        options: [
          "Mannitol 1 g/kg IV",
          "Mannitol 0.1 g/kg IV",
          "Dexamethasone 10 mg IV",
          "Brief hyperventilation to PaCO2 30 to 35 mmHg",
          "Hyperventilation to PaCO2 20 mmHg",
          "Normal saline 2 L IV bolus to raise cerebral perfusion",
          "Phenytoin 20 mg/kg IV as the first step",
          "Lower systolic pressure to 120 mmHg with labetalol",
        ],
        correct: [0, 3],
        explanation:
          "Clinical herniation warrants hyperosmolar therapy and brief moderate hyperventilation as a bridge to surgery. Mannitol at 0.25 to 1 g/kg is effective. Steroids worsen outcome in head injury. Deep hyperventilation causes cerebral ischemia. A large normal saline bolus in a hypertensive patient does not treat herniation.",
        keyFeature: { topic: "ems", n: 3 },
        source: "btf",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO steps to reduce the risk of airway or tube problems during the flight.",
        accept: [
          { id: "secure", text: "Secure the tube well and document its depth", match: ["secure", "tie", "tape", "depth"] },
          { id: "etco2", text: "Continuous waveform capnography", match: ["capnography", "etco2", "end tidal"] },
          { id: "cuff", text: "Monitor cuff pressure or fill the cuff with saline for altitude", match: ["cuff"] },
          { id: "paralysis", text: "Adequate sedation and paralysis to prevent patient movement", match: ["paralys", "paralytic", "sedation", "rocuronium"] },
          { id: "cxr", text: "Confirm position on chest X-ray before departure", match: ["chest x ray", "cxr", "confirm position"] },
          { id: "suction", text: "Suction and a backup airway kit with the team", match: ["suction", "backup airway", "bougie", "supraglottic"] },
          { id: "og", text: "Gastric tube to decompress the stomach", match: ["gastric", "og", "ng"] },
        ],
        explanation:
          "Tube dislodgement during loading is a common transport event. Capnography detects it immediately. Gas in the cuff expands at cabin altitude, so pressure should be checked or the cuff filled with saline.",
        keyFeature: { topic: "ems", n: 3 },
        source: "ornge",
      },
    ],
    sources: [S.criticall, S.atls, S.btf, S.ornge],
    ...META,
  },

  /* 09 ------------------------------------------------------------------ */
  {
    id: "ems-09",
    topic: "ems",
    alsoTopics: ["multiple-trauma"],
    title: "A snowmobiler awaiting a flight",
    stem:
      "You are the physician at a small northern hospital. A 45 year old man rolled his snowmobile. He has right sided chest wall pain. HR 104, BP 128/80, RR 22, SpO2 94% on 4 L nasal prongs, temperature 35.4 C. Chest X-ray shows three right rib fractures and a 20% right pneumothorax. CT is not available. He needs transfer to a trauma centre by fixed wing aircraft, a 90 minute flight.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate management of the pneumothorax before flight? Select one.",
        options: [
          "Observe on oxygen, since he is stable",
          "Insert a chest tube before departure",
          "Needle decompression only if he deteriorates in flight",
          "Request that the flight crew carry a needle decompression kit",
          "Delay the flight 6 hours and repeat the chest X-ray",
        ],
        correct: 1,
        explanation:
          "Gas expands as cabin pressure falls, per Boyle's law. A pneumothorax that is stable on the ground can become a tension pneumothorax at altitude. Place a chest tube before departure, when conditions are controlled and the space is adequate.",
        keyFeature: { topic: "ems", n: 3 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "List TWO other air filled spaces or devices that need attention before a flight.",
        accept: [
          { id: "cuff", text: "Endotracheal tube cuff", match: ["cuff", "endotracheal", "ett"] },
          { id: "stomach", text: "Stomach, decompressed with a gastric tube", match: ["stomach", "gastric", "ng", "og"] },
          { id: "splint", text: "Air splints", match: ["air splint", "splint"] },
          { id: "bowel", text: "Bowel obstruction", match: ["bowel", "obstruction", "ileus"] },
          { id: "pneumoceph", text: "Pneumocephalus", match: ["pneumocephalus", "intracranial air"] },
          { id: "eye", text: "Intraocular gas after eye surgery or globe injury", match: ["eye", "ocular", "globe"] },
          { id: "iv", text: "IV bags and drip chambers, which need pressure bags or pumps", match: ["iv bag", "drip chamber", "pressure bag"] },
          { id: "middle", text: "Middle ear and sinuses", match: ["ear", "sinus"] },
        ],
        explanation:
          "Every closed gas space expands at altitude. Cuffs overinflate and damage the trachea, the stomach distends and splints tighten. Patients with gas in the eye or skull may need a sea level cabin.",
        keyFeature: { topic: "ems", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE other steps to prepare him for the flight.",
        accept: [
          { id: "iv", text: "Two IV lines", match: ["two iv", "2 iv", "iv access", "iv line", "large bore", "intravenous access", "second iv"] },
          { id: "analgesia", text: "Analgesia, such as IV opioid or a regional block", match: ["analgesia", "analgesic", "pain", "opioid", "fentanyl", "morphine", "hydromorphone", "block"] },
          { id: "warm", text: "Warm him and prevent further heat loss", match: ["warm", "blanket", "hypothermia", "hypothermic"] },
          { id: "secure", text: "Secure the chest tube and drainage system", match: ["secure chest tube", "heimlich", "drainage", "valve"] },
          { id: "repeat", text: "Repeat chest X-ray after the tube", match: ["repeat", "x ray", "xray", "cxr"] },
          { id: "spine", text: "Spinal assessment and motion restriction if indicated", match: ["spine", "spinal", "collar"] },
          { id: "survey", text: "Complete secondary survey and FAST for occult injury", match: ["secondary survey", "fast", "ultrasound", "abdomen"] },
          { id: "docs", text: "Send records, images and a physician to physician handover", match: ["record", "image", "handover", "documentation", "chart"] },
          { id: "criticall", text: "Confirm an accepting trauma team through CritiCall", match: ["criticall", "accept"] },
        ],
        explanation:
          "Rib fractures hurt and limit ventilation, and cold aircraft worsen hypothermia, which impairs coagulation. Look for occult injuries before he leaves, since options in flight are limited. Secure devices for loading and unloading.",
        keyFeature: { topic: "ems", n: 3 },
        source: "atls",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which patient most needs the cabin pressurized to sea level? Select one.",
        options: [
          "A diver with arterial gas embolism",
          "A patient with a stable pelvic fracture in a binder",
          "A patient with STEMI after fibrinolysis",
          "A child with DKA",
          "A patient with a femur fracture in traction",
        ],
        correct: 0,
        explanation:
          "In gas embolism and decompression illness, any drop in ambient pressure enlarges bubbles and worsens injury. These patients need a sea level cabin or very low altitude flight. The others tolerate usual cabin pressure with standard precautions.",
        keyFeature: { topic: "ems", n: 3 },
        source: "rosen",
      },
    ],
    sources: [S.rosen, S.atls],
    ...META,
  },

  /* 10 ------------------------------------------------------------------ */
  {
    id: "ems-10",
    topic: "ems",
    alsoTopics: ["ischemic-heart-disease"],
    title: "Chest pain far from a catheterization lab",
    stem:
      "You work in a hospital 2.5 hours by road from the nearest PCI centre. Air transport is grounded by weather. A 55 year old woman, 70 kg, walked in with 90 minutes of chest pain. ECG shows 4 mm ST elevation in V1 to V5. HR 96, BP 134/82. She has no bleeding history and no contraindications to fibrinolysis.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which is the most appropriate reperfusion strategy? Select one.",
        options: [
          "Land transfer for primary PCI",
          "Weight based tenecteplase now, then transfer",
          "Half dose tenecteplase now, then transfer",
          "Heparin infusion and transfer when the weather clears",
          "Tenecteplase only if pain persists after 1 hour",
        ],
        correct: 1,
        explanation:
          "When first medical contact to device time will exceed 120 minutes, give fibrinolysis within 30 minutes of arrival. Full weight based tenecteplase is used under 75 years of age. Half dose is used for age 75 and older in the pharmacoinvasive approach.",
        keyFeature: { topic: "ischemic-heart-disease", n: 6 },
        source: "ccs-stemi",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "List TWO antithrombotic medications to give with the fibrinolytic.",
        accept: [
          { id: "asa", text: "ASA 160 mg chewed", match: ["asa", "aspirin", "acetylsalicylic"] },
          { id: "clopidogrel", text: "Clopidogrel 300 mg loading dose (75 mg if over 75 years)", match: ["clopidogrel", "plavix"] },
          { id: "anticoag", text: "An anticoagulant: enoxaparin 30 mg IV then 1 mg/kg subcutaneously (maximum 100 mg for the first two doses), or unfractionated heparin bolus and infusion", match: ["enoxaparin", "lovenox", "low molecular weight heparin", "lmwh", "unfractionated heparin", "heparin", "ufh", "anticoagulant", "anticoagulation"] },
        ],
        unacceptable: [
          { text: "Prasugrel", match: ["prasugrel"] },
          { text: "Ticagrelor", match: ["ticagrelor"] },
        ],
        explanation:
          "ASA, clopidogrel and an anticoagulant are the evidence based adjuncts to fibrinolysis. Only one anticoagulant is given, and enoxaparin is preferred. At her age of 55 no dose adjustment is needed. Over 75, clopidogrel is 75 mg with no load and enoxaparin is 0.75 mg/kg SC with no IV bolus. Prasugrel and ticagrelor are not the recommended P2Y12 inhibitors at the time of fibrinolysis.",
        keyFeature: { topic: "ischemic-heart-disease", n: 7 },
        source: "ccs-stemi",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE steps to prepare her for the long land transfer.",
        accept: [
          { id: "pads", text: "Defibrillator pads on and continuous cardiac monitoring", match: ["pad", "defib", "defibrillator", "defibrillation", "monitor"] },
          { id: "crew", text: "An advanced care or critical care crew able to manage arrhythmias", match: ["advanced care", "critical care", "acp", "crew", "escort", "nurse", "physician"] },
          { id: "iv", text: "Two IV lines", match: ["two iv", "2 iv", "iv access", "iv line", "large bore", "intravenous access", "second iv"] },
          { id: "ecg", text: "Repeat ECG at 60 to 90 minutes after lysis to assess reperfusion", match: ["repeat ecg", "ecg at 60", "ecg at 90", "st resolution", "serial ecg"] },
          { id: "plan", text: "A rescue PCI plan agreed with the receiving cardiologist", match: ["rescue", "cardiologist", "accepting", "criticall"] },
          { id: "bleed", text: "Monitor for bleeding and neurological change", match: ["bleed", "neuro", "neurological", "neurologic", "hemorrhage"] },
          { id: "docs", text: "Send ECGs, times and medication record", match: ["send", "copy", "record", "documentation"] },
        ],
        explanation:
          "Reperfusion arrhythmias and failed lysis are expected complications during transfer. The crew must be able to defibrillate and treat instability. A clear plan and ST resolution check drive whether she needs rescue PCI.",
        keyFeature: { topic: "ems", n: 3 },
        source: "ccs-stemi",
      },
      {
        id: "q4",
        kind: "single",
        update: "Seventy minutes after tenecteplase she still has chest pain. ST elevation has fallen by only 20%. The weather has cleared.",
        prompt: "Which is the most appropriate next step? Select one.",
        options: [
          "Repeat tenecteplase",
          "Urgent air transfer for rescue PCI",
          "Observe and repeat the ECG in 3 hours",
          "Start a nitroglycerin infusion and admit locally",
          "Transfer for elective angiography within 24 hours",
        ],
        correct: 1,
        explanation:
          "Less than 50% ST resolution at 60 to 90 minutes means failed reperfusion. Rescue PCI is indicated. Repeat fibrinolysis adds bleeding risk without benefit.",
        keyFeature: { topic: "ems", n: 3 },
        source: "ccs-stemi",
      },
    ],
    sources: [S.ccsStemi],
    ...META,
  },

  /* 11 ------------------------------------------------------------------ */
  {
    id: "ems-11",
    topic: "ems",
    title: "A sick child awaiting a transport team",
    stem:
      "You are working in a community hospital. A 7 year old girl, 25 kg, with new onset diabetes has vomiting and deep rapid breathing. Glucose 32 mmol/L, venous pH 6.98, bicarbonate 4 mmol/L, potassium 4.6 mmol/L, GCS 14. She received 10 mL/kg normal saline. The pediatric critical care transport team will arrive in 3 hours and the drive back is 2 hours.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE treatments or monitoring that should be in place before the team arrives.",
        accept: [
          { id: "insulin", text: "Insulin infusion 0.05 to 0.1 units/kg/h without a bolus", match: ["insulin infusion", "insulin drip", "insulin 0.1", "insulin 0.05"] },
          { id: "fluids", text: "Rehydration fluids at a calculated rate over 48 hours", match: ["fluid", "rehydration", "saline"] },
          { id: "potassium", text: "Potassium added to fluids once urine output confirmed", match: ["potassium", "kcl"] },
          { id: "neuro", text: "Hourly neurological checks", match: ["neuro", "neurological", "neurologic", "gcs", "mental status"] },
          { id: "glucose", text: "Hourly glucose checks", match: ["glucose"] },
          { id: "lytes", text: "Electrolytes and gas every 2 hours", match: ["electrolyte", "gas", "lytes"] },
          { id: "iofluids", text: "Strict intake and output", match: ["intake", "output", "input"] },
          { id: "iv", text: "Two IV lines", match: ["two iv", "2 iv", "ivs", "second iv", "iv access"] },
        ],
        unacceptable: [
          { text: "Sodium bicarbonate", match: ["sodium bicarbonate", "give bicarbonate", "bicarbonate bolus", "bicarb"] },
        ],
        explanation:
          "Pediatric DKA care is an insulin infusion without a bolus, measured rehydration and close neurological and biochemical monitoring. Bicarbonate and insulin boluses are linked with cerebral edema. Care must begin at the sending site, not when the team arrives.",
        keyFeature: { topic: "ems", n: 3 },
        source: "trekk-dka",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "The nurse asks whether she should be intubated for the transfer because she is drowsy. Which is the best response? Select one.",
        options: [
          "Intubate now because the transport is long",
          "Avoid intubation and monitor closely, since intubation can worsen acidosis and cerebral edema",
          "Intubate only if pH remains below 7.0",
          "Give sodium bicarbonate to avoid intubation",
          "Intubate and set the ventilator to a normal PaCO2",
        ],
        correct: 1,
        explanation:
          "Intubating a child in severe DKA is high risk. Loss of compensatory hyperventilation can cause rapid acidosis and cardiovascular collapse. If it becomes essential, ventilation must match her pre-intubation minute ventilation. A GCS of 14 is not an indication.",
        keyFeature: { topic: "ems", n: 3 },
        source: "trekk-dka",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "Which medication should be ready at the bedside and sent with her for the most feared complication? Select one.",
        options: [
          "Mannitol 0.5 to 1 g/kg IV",
          "Dexamethasone 0.6 mg/kg IV",
          "Sodium bicarbonate 1 mmol/kg IV",
          "Insulin 0.1 units/kg IV bolus",
          "Lorazepam 0.1 mg/kg IV",
        ],
        correct: 0,
        explanation:
          "Cerebral edema is the leading cause of DKA death in children. Signs include headache, bradycardia, hypertension, falling GCS and incontinence. Treat with mannitol 0.5 to 1 g/kg or 3% saline 2.5 to 5 mL/kg, and reduce the fluid rate.",
        keyFeature: { topic: "ems", n: 3 },
        source: "dc-peds",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO items to include in your handover to the transport team.",
        accept: [
          { id: "fluids", text: "Total fluid volumes given and current rate", match: ["fluid", "volume", "bolus"] },
          { id: "insulin", text: "Insulin start time and rate", match: ["insulin"] },
          { id: "trend", text: "Trends in glucose, pH, sodium and potassium", match: ["trend", "glucose", "ph", "sodium", "potassium", "lab"] },
          { id: "neuro", text: "Neurological observations over time", match: ["neuro", "neurological", "neurologic", "gcs"] },
          { id: "weight", text: "Weight used for calculations", match: ["weight"] },
          { id: "output", text: "Urine output", match: ["urine", "output"] },
        ],
        explanation:
          "A flowsheet with volumes, insulin timing and serial labs lets the team continue care safely. Corrected sodium that fails to rise and a falling GCS are warning signs of cerebral edema. The weight used for all doses must be clear.",
        keyFeature: { topic: "ems", n: 3 },
        source: "trekk-dka",
      },
    ],
    sources: [S.trekkDka, S.dcPeds],
    ...META,
  },

  /* 12 ------------------------------------------------------------------ */
  {
    id: "ems-12",
    topic: "ems",
    alsoTopics: ["multiple-patients"],
    title: "A call from the scene of a bus crash",
    stem:
      "You are the emergency physician in charge at the closest hospital, a mid sized community hospital. At 1530 the EMS scene commander calls. A school bus carrying 32 students aged 6 to 17 and 2 adults collided with a transport truck 10 km away. Several patients are trapped. The scene commander asks for guidance.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE pieces of information you want from the scene commander.",
        accept: [
          { id: "number", text: "Total number of patients", match: ["number of patient", "how many", "total number", "number"] },
          { id: "triage", text: "Number in each triage category", match: ["triage", "category", "red", "critical"] },
          { id: "injuries", text: "Types of injuries, including burns or entrapment", match: ["injury", "injuries", "burn", "entrap", "trapped"] },
          { id: "hazard", text: "Hazards such as fuel spill or hazardous cargo on the truck", match: ["hazard", "cargo", "fuel", "chemical", "hazmat"] },
          { id: "eta", text: "Estimated arrival times", match: ["eta", "arrival", "when"] },
          { id: "resources", text: "EMS resources on scene and other hospitals notified", match: ["resource", "other hospital", "ambulances", "unit"] },
          { id: "ages", text: "Ages, including any young children", match: ["age", "child", "pediatric", "paediatric"] },
        ],
        explanation:
          "Numbers, acuity and hazards decide how you scale your response. The truck cargo may add a contamination risk. Knowing what other hospitals are receiving prevents your department from being overwhelmed.",
        keyFeature: { topic: "ems", n: 1 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Using START triage, a 16 year old cannot walk. RR is 34, the radial pulse is present and he follows commands. Which category is he? Select one.",
        options: ["Green, minor", "Yellow, delayed", "Red, immediate", "Black, expectant", "Yellow until reassessed at hospital"],
        correct: 2,
        explanation:
          "In START, a respiratory rate over 30 places the patient in the immediate category regardless of other findings. Absent radial pulse or capillary refill over 2 seconds and inability to follow commands are the other red triggers. He is not walking, so he is not green.",
        keyFeature: { topic: "ems", n: 4 },
        source: "start",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "A 6 year old is not breathing after the airway is repositioned but has a palpable pulse. Under JumpSTART, which is the next field action? Select one.",
        options: [
          "Tag black and move on",
          "Give five rescue breaths, then tag red if breathing resumes",
          "Begin full CPR",
          "Tag red and move on without intervention",
          "Intubate on scene",
        ],
        correct: 1,
        explanation:
          "JumpSTART is used for children aged about 1 to 8 years. Children often have primary respiratory arrest. JumpSTART calls for five rescue breaths in an apneic child with a pulse. If breathing starts, the child is red. If not, the child is expectant. Full CPR is not done during mass casualty triage.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 4,
        prompt: "List FOUR steps to prepare your hospital.",
        accept: [
          { id: "code", text: "Activate the external disaster plan, Code Orange in Ontario and many provinces", match: ["code orange", "disaster plan", "emergency plan", "incident command", "mass casualty plan"] },
          { id: "staff", text: "Call in extra physicians, nurses and staff", match: ["staff", "call in", "fan out", "callback", "extra physician", "nurse"] },
          { id: "clear", text: "Clear the department by discharging or moving admitted patients", match: ["clear", "discharge", "decant", "move admitted", "empty"] },
          { id: "triage", text: "Set up a triage area at the ambulance entrance led by a senior clinician", match: ["triage area", "triage officer", "triage point", "entrance"] },
          { id: "or", text: "Notify the OR, surgeons and anesthesia", match: ["operating room", "surgeon", "anesthesia", "anesthetist", "anesthesiologist", "anesthetic", "anaesthesia", "anaesthetist", "anaesthetic", "notify or"] },
          { id: "blood", text: "Notify the blood bank", match: ["blood bank", "blood"] },
          { id: "peds", text: "Mobilize pediatric equipment and consultants", match: ["pediatric", "paediatric", "broselow", "child"] },
          { id: "family", text: "Open a family information centre", match: ["family", "information centre", "reunification"] },
          { id: "security", text: "Security and traffic control", match: ["security", "traffic"] },
          { id: "media", text: "Designate a media spokesperson", match: ["media", "communication"] },
          { id: "tracking", text: "Patient tracking and identification system", match: ["tracking", "identification", "tag"] },
        ],
        explanation:
          "Code Orange mobilizes the hospital for an external disaster. Clearing beds and calling in staff creates capacity before patients arrive. With many children, pediatric resources and a reunification area for parents are essential.",
        keyFeature: { topic: "ems", n: 1 },
        source: "oha-codes",
      },
      {
        id: "q5",
        kind: "short",
        required: 2,
        prompt: "List TWO principles you advise the scene commander to use when distributing patients.",
        accept: [
          { id: "spread", text: "Distribute patients across several hospitals rather than sending all to the closest", match: ["distribute", "spread", "several hospital", "multiple hospital", "other hospital", "not all"] },
          { id: "trauma", text: "Send the most critical patients to the trauma centre", match: ["trauma centre", "trauma center", "most critical", "most injured", "red to"] },
          { id: "peds", text: "Send children to a pediatric capable centre when feasible", match: ["pediatric", "paediatric", "children"] },
          { id: "walking", text: "Expect walking wounded to self present to the closest hospital", match: ["walking wounded", "self present", "self refer", "green"] },
          { id: "dispatch", text: "Coordinate destinations through the ambulance communication centre", match: ["dispatch", "communication centre", "central", "coordinate", "coordination"] },
        ],
        explanation:
          "The closest hospital is usually overwhelmed by walking wounded arriving on their own. Distribution through central dispatch matches patient severity to hospital capability. The most injured should go to the trauma centre when transport times allow.",
        keyFeature: { topic: "ems", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.start, S.ohaCodes, S.rosen],
    ...META,
  },

  /* 13 ------------------------------------------------------------------ */
  {
    id: "ems-13",
    topic: "ems",
    alsoTopics: ["tox"],
    title: "Several sick workers at a greenhouse",
    stem:
      "An advanced care paramedic supervisor patches to your emergency department from a large greenhouse 20 minutes away. Six workers became unwell after a pesticide tank ruptured. Several are vomiting, drooling and wheezing. One has HR 42, copious secretions and pinpoint pupils. Fire services with a hazardous materials team are on scene.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE directions you give to EMS before transport.",
        accept: [
          { id: "decon", text: "Decontaminate at the scene before transport, with clothing removed and skin washed", match: ["decontaminate", "decontamination", "decon", "remove clothing", "undress", "wash"] },
          { id: "ppe", text: "Paramedics wear appropriate PPE", match: ["ppe", "protective", "glove", "gown"] },
          { id: "atropine", text: "Atropine for patients with secretions or bradycardia per protocol", match: ["atropine"] },
          { id: "airway", text: "Suction, oxygen and airway support", match: ["suction", "oxygen", "airway"] },
          { id: "product", text: "Identify the product and bring the label or safety data sheet", match: ["label", "safety data sheet", "sds", "msds", "product", "identify"] },
          { id: "prenotify", text: "Pre-notify with numbers and ETA so the ED can prepare", match: ["notify", "eta", "numbers"] },
          { id: "triage", text: "Triage by severity and distribute patients", match: ["triage", "distribute"] },
          { id: "seizure", text: "Benzodiazepine for seizures", match: ["benzodiazepine", "midazolam", "diazepam", "seizure"] },
        ],
        explanation:
          "This is a cholinergic toxidrome from an organophosphate or carbamate. Removing clothing and washing at the scene protects patients, crews and the ED. Early atropine for bronchorrhea and bradycardia is lifesaving. The product label guides specific therapy.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "The most severely affected worker, 80 kg, arrives decontaminated with bronchorrhea and HR 40. Select TWO appropriate treatments.",
        options: [
          "Atropine 0.5 mg IV once",
          "Atropine 1 to 2 mg IV, doubling every 5 minutes until secretions dry",
          "Pralidoxime 30 mg/kg IV over 30 minutes",
          "Physostigmine 1 mg IV",
          "Succinylcholine for intubation",
          "Pralidoxime 500 mg/kg IV",
          "Glucagon 5 mg IV",
          "Epinephrine 1 mg IV",
        ],
        correct: [1, 2],
        explanation:
          "Atropine is titrated rapidly by doubling doses until bronchial secretions clear. Heart rate and pupils are poor end points. Pralidoxime reactivates acetylcholinesterase if given before aging. Physostigmine is itself a cholinesterase inhibitor and would worsen toxicity.",
        keyFeature: { topic: "tox", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "He needs intubation. Which paralytic is most appropriate? Select one.",
        options: ["Succinylcholine 1.5 mg/kg", "Rocuronium 1.2 mg/kg", "No paralytic, awake intubation only", "Succinylcholine 0.5 mg/kg", "Cisatracurium 0.1 mg/kg"],
        correct: 1,
        explanation:
          "Succinylcholine is metabolized by plasma cholinesterase, which organophosphates inhibit. Paralysis can last for hours. Rocuronium at 1.2 mg/kg gives rapid, reliable conditions.",
        keyFeature: { topic: "tox", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "List THREE ways to prepare your department for more exposed patients.",
        accept: [
          { id: "decon", text: "Set up a decontamination area outside the ED entrance", match: ["decon", "decontaminate", "decontamination"] },
          { id: "lock", text: "Control entrances so contaminated patients cannot walk in", match: ["lock", "secure entrance", "control entrance", "entrance", "security"] },
          { id: "ppe", text: "Staff PPE for decontamination", match: ["ppe", "protective", "respirator"] },
          { id: "antidote", text: "Gather atropine and pralidoxime stock", match: ["atropine", "pralidoxime", "antidote", "stock"] },
          { id: "poison", text: "Call the regional poison centre", match: ["poison"] },
          { id: "code", text: "Activate the hospital disaster or CBRN plan", match: ["code", "plan", "cbrn", "disaster"] },
          { id: "vent", text: "Prepare ventilators and airway equipment", match: ["ventilator", "airway", "suction"] },
          { id: "public", text: "Notify public health", match: ["public health"] },
        ],
        explanation:
          "Secondary contamination of staff can close an ED. Decontamination must happen before entry, and entrances need control because self presenters arrive unannounced. Atropine may be needed in very large doses, so stock must be gathered early.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },

  /* 14 ------------------------------------------------------------------ */
  {
    id: "ems-14",
    topic: "ems",
    alsoTopics: ["environmental"],
    title: "Summer festival medical planning",
    stem:
      "You are the medical director for a three day outdoor music festival expecting 40 000 people. The forecast is 34 C with high humidity. The on-site medical team has physicians, nurses and paramedics, and the local EMS service has two dedicated ambulances. Your hospital is 15 minutes away.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE conditions the on-site team should be ready to treat.",
        accept: [
          { id: "heat", text: "Heat exhaustion and heat stroke", match: ["heat"] },
          { id: "stim", text: "Stimulant toxicity such as MDMA or amphetamines", match: ["mdma", "stimulant", "amphetamine", "ecstasy", "cocaine", "sympathomimetic"] },
          { id: "opioid", text: "Opioid overdose", match: ["opioid", "fentanyl"] },
          { id: "hypona", text: "Hyponatremia", match: ["hyponatremia", "hyponatraemia", "low sodium"] },
          { id: "etoh", text: "Alcohol intoxication", match: ["alcohol", "intoxication", "intoxicated"] },
          { id: "trauma", text: "Trauma and crowd crush injuries", match: ["trauma", "crush", "fall", "injury", "injuries"] },
          { id: "dehyd", text: "Dehydration", match: ["dehydration", "dehydrated"] },
          { id: "assault", text: "Sexual assault", match: ["sexual assault", "assault"] },
          { id: "asthma", text: "Asthma and allergic reactions", match: ["asthma", "allergy", "allergic", "anaphylaxis"] },
          { id: "psych", text: "Agitation and acute psychiatric crises", match: ["agitation", "psych", "psychiatric", "psychosis", "anxiety"] },
        ],
        explanation:
          "Heat, stimulants and alcohol dominate at summer music festivals. Opioid contamination of the drug supply is a real risk. On-site treatment of minor problems reduces ambulance transports and ED load.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        update: "On day two, the on-site physician calls. A 19 year old man took MDMA and is confused and agitated. Rectal temperature 41.4 C, HR 152, BP 150/90.",
        prompt: "List THREE directions for his care before and during transport.",
        accept: [
          { id: "cool", text: "Start cooling now with ice water immersion before transport", match: ["immersion", "immerse", "ice water", "cold water", "cool", "cooling", "ice", "evaporative"] },
          { id: "benzo", text: "Benzodiazepine for agitation, such as midazolam", match: ["benzodiazepine", "midazolam", "diazepam", "lorazepam"] },
          { id: "glucose", text: "Check glucose", match: ["glucose", "sugar"] },
          { id: "sodium", text: "Check sodium if point of care testing is available", match: ["sodium", "na"] },
          { id: "notify", text: "Pre-notify the ED to prepare a cooling set up", match: ["notify", "prepare"] },
          { id: "iv", text: "IV access and isotonic fluids", match: ["iv access", "iv fluid", "fluid", "intravenous", "iv line"] },
          { id: "monitor", text: "Continuous temperature monitoring and stop cooling at about 39 C", match: ["monitor temperature", "39", "38.5", "rectal probe", "core temperature", "rectal temperature", "temperature monitoring", "continuous temperature", "stop cooling 39", "stop cooling 38.5"] },
          { id: "noapap", text: "No antipyretics, since they do not work in hyperthermia", match: ["no antipyretic", "avoid antipyretic", "no acetaminophen", "avoid acetaminophen", "not antipyretic"] },
        ],
        unacceptable: [
          { text: "Antipyretics", match: ["acetaminophen", "tylenol", "ibuprofen", "antipyretic"] },
          { text: "Physical restraint without sedation", match: ["physical restraint", "restraints only", "restrain only", "restrain without sedation", "restraint without sedation"] },
        ],
        explanation:
          "Temperature above 41 C with altered mental status is life threatening. Cool first, transport second, because minutes at this temperature drive organ injury. Benzodiazepines reduce heat production from agitation. Antipyretics do not work in hyperthermia and restraints increase heat production.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "single",
        update: "Later, a 21 year old woman who took MDMA and drank large amounts of water has a generalized seizure. Point of care sodium is 117 mmol/L.",
        prompt: "Which is the most appropriate initial treatment? Select one.",
        options: [
          "3% saline 100 mL IV over 10 minutes, repeated up to three times",
          "Normal saline 1 L IV bolus",
          "Fluid restriction alone",
          "3% saline 500 mL IV over 10 minutes",
          "Furosemide 40 mg IV",
        ],
        correct: 0,
        explanation:
          "Severe symptomatic hyponatremia needs a rapid rise of 4 to 6 mmol/L to stop seizures. A 100 mL bolus of 3% saline, repeated up to three times, is standard. Normal saline can worsen hyponatremia when ADH is high, as with MDMA.",
        keyFeature: { topic: "ems", n: 4 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO event level measures that reduce harm and hospital transports at this festival.",
        accept: [
          { id: "water", text: "Free water and cooling stations or shaded areas", match: ["water", "cooling station", "shade", "misting"] },
          { id: "naloxone", text: "Naloxone kits and harm reduction services", match: ["naloxone", "harm reduction"] },
          { id: "checking", text: "Drug checking services", match: ["drug checking", "drug testing"] },
          { id: "roving", text: "Roving medical teams in the crowd", match: ["roving", "mobile team", "foot team", "bike team"] },
          { id: "comms", text: "Direct communication with EMS dispatch and the hospital", match: ["communication", "radio", "dispatch"] },
          { id: "onsite", text: "On-site treat and release for minor problems", match: ["on site", "onsite", "treat and release"] },
          { id: "messaging", text: "Public messaging about heat and drug risks", match: ["message", "messaging", "education", "warning", "announcement", "public"] },
          { id: "tracking", text: "Patient tracking and surveillance to detect clusters", match: ["tracking", "surveillance", "cluster"] },
        ],
        explanation:
          "Mass gathering medicine relies on planning, on-site care and early detection of clusters such as a toxic drug batch. Water, shade and harm reduction reduce heat and overdose events. Good communication with EMS and the hospital prevents surprise surges.",
        keyFeature: { topic: "ems", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.tintinalli, S.rosen],
    ...META,
  },

  /* 15 ------------------------------------------------------------------ */
  {
    id: "ems-15",
    topic: "ems",
    alsoTopics: ["tox"],
    title: "Many calls during a power outage",
    stem:
      "An ice storm has left much of your region without power for two days. At 0600 the EMS duty supervisor calls your emergency department. Crews are at four homes where families used generators or barbecues indoors. There are 14 patients, including children and a pregnant woman. Symptoms include headache, vomiting and confusion. One man was found unconscious.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE directions you give EMS for field management.",
        accept: [
          { id: "remove", text: "Remove everyone from the homes and away from the source", match: ["remove", "evacuate", "evacuation", "fresh air", "leave the home", "out of the home"] },
          { id: "o2", text: "High flow oxygen by non-rebreather for all symptomatic patients", match: ["non rebreather", "nonrebreather", "high flow", "100% oxygen", "100% o2", "oxygen"] },
          { id: "spo2", text: "Do not rely on pulse oximetry", match: ["not rely", "don rely", "dont rely", "unreliable", "not trust", "falsely normal", "falsely high", "misleading", "ignore spo2", "ignore pulse oximetry"] },
          { id: "spco", text: "Use a CO-oximeter if available to screen", match: ["spco", "co oximeter", "cooximeter", "rad 57"] },
          { id: "prioritize", text: "Prioritize the unconscious, the pregnant woman and those with chest pain", match: ["unconscious", "pregnant", "pregnancy", "chest pain", "prioritize", "priority", "prioritise"] },
          { id: "fire", text: "Fire services to ventilate homes and check others nearby", match: ["fire", "ventilate", "neighbour", "neighbor"] },
          { id: "distribute", text: "Distribute patients across hospitals", match: ["distribute", "other hospital"] },
          { id: "ppe", text: "Crews protect themselves from exposure", match: ["crew safety", "scene safety", "ppe", "protect"] },
        ],
        explanation:
          "Carbon monoxide poisoning clusters after storms when generators are used indoors. Removal from the source and high flow oxygen are the core field treatments. Pulse oximetry reads falsely normal. Fire services must clear homes and check neighbours.",
        keyFeature: { topic: "ems", n: 4 },
        source: "uhms",
      },
      {
        id: "q2",
        kind: "menu",
        select: 3,
        prompt: "The patients arrive and levels are drawn. Select the THREE who most warrant urgent discussion with the hyperbaric centre.",
        options: [
          "A 28 year old man with headache and carboxyhemoglobin 14%",
          "A 31 year old woman at 30 weeks gestation with nausea and carboxyhemoglobin 17%",
          "A 58 year old man who was unconscious at the scene, now carboxyhemoglobin 11%",
          "A 9 year old with vomiting and carboxyhemoglobin 8%",
          "A 40 year old woman with dizziness and carboxyhemoglobin 19%",
          "A 67 year old man with chest pain, new ST depression and carboxyhemoglobin 22%",
          "A 35 year old man, asymptomatic, carboxyhemoglobin 6%",
        ],
        correct: [1, 2, 5],
        explanation:
          "Accepted indications to consider hyperbaric oxygen include loss of consciousness, neurological deficits, cardiac ischemia, severe acidosis, carboxyhemoglobin above 25%, and pregnancy with a level above about 15% (some centres use 20%). The fetus is especially vulnerable because fetal hemoglobin binds CO avidly. Headache or dizziness alone at moderate levels is treated with normobaric oxygen.",
        keyFeature: { topic: "tox", n: 2 },
        source: "weaver",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE steps to prepare your hospital for this surge.",
        accept: [
          { id: "masks", text: "Gather non-rebreather masks and oxygen supply", match: ["mask", "oxygen supply", "non rebreather", "nonrebreather", "oxygen"] },
          { id: "gas", text: "Ensure co-oximetry blood gas capacity", match: ["co oximetry", "blood gas", "cohb", "lab"] },
          { id: "hbo", text: "Contact the hyperbaric centre early, through CritiCall in Ontario or the provincial transfer line", match: ["hyperbaric", "criticall", "hbo"] },
          { id: "ob", text: "Notify obstetrics for fetal monitoring", match: ["obstetric", "fetal", "labour and delivery", "ob"] },
          { id: "peds", text: "Pediatric equipment and staff", match: ["pediatric", "paediatric", "child"] },
          { id: "code", text: "Activate the surge or Code Orange plan and call in staff", match: ["code orange", "surge", "call in", "staff"] },
          { id: "space", text: "Open additional treatment space", match: ["space", "bed", "area"] },
          { id: "power", text: "Confirm hospital backup power and generator safety", match: ["power", "generator"] },
          { id: "ecg", text: "ECG and troponin for adults with cardiac risk", match: ["ecg", "troponin"] },
        ],
        explanation:
          "Many patients need prolonged high flow oxygen at once, which strains mask and oxygen supply. The hyperbaric centre has limited capacity, so early contact is essential. A pregnant patient needs obstetric input.",
        keyFeature: { topic: "ems", n: 1 },
        source: "uhms",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which is the approximate half life of carboxyhemoglobin while breathing 100% oxygen at normal atmospheric pressure? Select one.",
        options: ["5 minutes", "20 minutes", "75 minutes", "5 hours", "12 hours"],
        correct: 2,
        explanation:
          "The half life of carboxyhemoglobin is about 4 to 5 hours on room air, about 60 to 90 minutes on 100% oxygen, and about 20 to 30 minutes with hyperbaric oxygen. Oxygen should continue until symptoms resolve and the level is low, often for at least 6 hours.",
        keyFeature: { topic: "tox", n: 2 },
        source: "uhms",
      },
    ],
    sources: [S.uhms, S.weaver],
    ...META,
  },
];
