// DRAFT. Written for exam practice only. Requires physician review before release. Verify every dose and threshold against current guidelines.

import type { Samp } from "@/engine/samp";
import type { Source } from "@/engine/types";

const META = { reviewed: false, author: "Draft for review by Arjan Dhoot, MD", version: 1 } as const;

const S = {
  wmsHeat: { id: "wms-heat", citation: "Wilderness Medical Society. Clinical practice guidelines for the prevention and treatment of heat illness. Wilderness Environ Med." },
  wmsHypo: { id: "wms-hypo", citation: "Wilderness Medical Society. Clinical practice guidelines for the out-of-hospital evaluation and treatment of accidental hypothermia. Wilderness Environ Med." },
  wmsFrost: { id: "wms-frost", citation: "Wilderness Medical Society. Clinical practice guidelines for the prevention and treatment of frostbite. 2024 update. Wilderness Environ Med. 2024.", url: "https://journals.sagepub.com/doi/10.1177/10806032231222359" },
  wmsDrown: { id: "wms-drown", citation: "Wilderness Medical Society. Clinical practice guidelines for the treatment and prevention of drowning. Wilderness Environ Med." },
  wmsLightning: { id: "wms-lightning", citation: "Wilderness Medical Society. Clinical practice guidelines for the prevention and treatment of lightning injuries. Wilderness Environ Med." },
  erc: { id: "erc", citation: "European Resuscitation Council Guidelines 2021. Cardiac arrest in special circumstances. Resuscitation. 2021. Reaffirmed in the ERC 2025 special circumstances guidelines.", url: "https://www.sciencedirect.com/science/article/pii/S0300957221000642" },
  hope: { id: "hope", citation: "Pasquier M, et al. Hypothermia outcome prediction after extracorporeal life support for hypothermic cardiac arrest patients. The HOPE score. Resuscitation. 2018." },
  uhmsDcs: { id: "uhms-dcs", citation: "Undersea and Hyperbaric Medical Society. Best practice guidelines. Prevention and treatment of decompression sickness and arterial gas embolism." },
  navy: { id: "navy", citation: "United States Navy. U.S. Navy Diving Manual. Chapters on diagnosis and recompression treatment of decompression sickness and arterial gas embolism." },
  danFlying: { id: "dan-flying", citation: "Divers Alert Network. Flying after recreational diving. Workshop proceedings and consensus guidelines." },
  ataThyro: { id: "ata-thyro", citation: "American Thyroid Association. Guidelines for the diagnosis and management of hyperthyroidism and other causes of thyrotoxicosis." },
  ataHypo: { id: "ata-hypo", citation: "American Thyroid Association. Guidelines for the treatment of hypothyroidism." },
  abls: { id: "abls", citation: "American Burn Association. Advanced Burn Life Support Provider Manual. Chapter on electrical injury." },
  rosen: { id: "rosen", citation: "Walls RM, Hockberger RS, Gausche-Hill M, editors. Rosen's Emergency Medicine: Concepts and Clinical Practice. Elsevier. Chapters on heat illness, dysbarism and electrical and lightning injuries." },
  tintinalli: { id: "tintinalli", citation: "Tintinalli JE, et al, editors. Tintinalli's Emergency Medicine: A Comprehensive Study Guide. McGraw Hill. Chapters on heat emergencies, diving disorders and electrical injuries." },
} satisfies Record<string, Source>;

export const ENVIRONMENTAL_SAMPS: Samp[] = [
  /* 01 ------------------------------------------------------------------ */
  {
    id: "environmental-01",
    topic: "environmental",
    title: "Collapse near a marathon finish line",
    stem:
      "You are the physician in the medical tent at a city marathon in late May. It is 27 C and humid. A 24 year old woman collapsed at kilometre 40. She is confused and combative. HR 152, BP 102/60, RR 28, SpO2 97% on room air, capillary glucose 5.4 mmol/L. Rectal temperature is 42.1 C.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List the TWO clinical criteria that define the most likely diagnosis.",
        accept: [
          { id: "temp", text: "Core temperature above 40 C", match: ["temperature", "40", "hyperthermia", "core temp", "rectal"] },
          { id: "cns", text: "Central nervous system dysfunction such as confusion, seizure or coma", match: ["cns", "confusion", "confused", "mental status", "altered", "neuro", "neurological", "neurologic", "encephalopathy", "combative", "seizure", "coma", "delirium"] },
          { id: "exertion", text: "Exertion or heat exposure as the setting", match: ["exertion", "exercise", "heat exposure", "running", "marathon"] },
        ],
        explanation:
          "Exertional heat stroke is defined by a core temperature usually above 40 C with central nervous system dysfunction. Sweating may persist in exertional heat stroke. Any runner who collapses confused on a warm day has heat stroke until a rectal temperature proves otherwise.",
        keyFeature: { topic: "environmental", n: 1 },
        source: "wms-heat",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate cooling method? Select one.",
        options: [
          "Ice packs to the neck, axillae and groin",
          "Whole body cold water immersion in the tent now",
          "Evaporative cooling with fans during transport to hospital",
          "Cold IV normal saline 2 L",
          "Transport immediately to the ED for cooling",
        ],
        correct: 1,
        explanation:
          "Cold water immersion gives the fastest cooling rate and is the standard for exertional heat stroke. The rule is cool first, transport second. Survival approaches 100% when temperature falls below 39 C within 30 minutes. Ice packs to the groin and axillae alone are much slower.",
        keyFeature: { topic: "environmental", n: 1 },
        source: "wms-heat",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO things you monitor during immersion, including when you stop.",
        accept: [
          { id: "probe", text: "Continuous rectal temperature probe", match: ["rectal", "core temp", "temperature probe", "continuous temperature"] },
          { id: "stop", text: "Remove from water at about 39 C to avoid overshoot", match: ["39", "38.9", "38.6", "38.5", "stop", "remove"] },
          { id: "airway", text: "Airway, head above water and vital signs", match: ["airway", "head above", "vital"] },
          { id: "mental", text: "Mental status improvement", match: ["mental status", "gcs", "level of consciousness", "neuro", "neurological", "neurologic"] },
          { id: "glucose", text: "Glucose and sodium if available", match: ["glucose", "sodium"] },
        ],
        explanation:
          "Temperature must be tracked continuously with a rectal probe because oral and tympanic readings are unreliable. Stop immersion at about 39 C to prevent rebound hypothermia. Improving mental status is reassuring. A persistent deficit after cooling needs another explanation.",
        keyFeature: { topic: "environmental", n: 1 },
        source: "wms-heat",
      },
      {
        id: "q4",
        kind: "menu",
        select: 1,
        prompt: "Which medication should be added to physical cooling? Select one, or None if none are required.",
        options: [
          "Acetaminophen 1 g PO",
          "Ibuprofen 400 mg PO",
          "Dantrolene 2.5 mg/kg IV",
          "Bromocriptine 2.5 mg PO",
          "Cyproheptadine 12 mg PO",
          "None",
        ],
        correct: [5],
        explanation:
          "Heat stroke is failure of heat dissipation, not a raised hypothalamic set point. Antipyretics do not help and NSAIDs may worsen kidney and gut injury. Dantrolene has not been shown to help in heat stroke. Physical cooling is the treatment.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "wms-heat",
      },
      {
        id: "q5",
        kind: "short",
        required: 3,
        update: "She is cooled to 39 C in 18 minutes and becomes oriented. She is taken to hospital.",
        prompt: "List THREE complications you look for with laboratory testing.",
        accept: [
          { id: "rhabdo", text: "Rhabdomyolysis with CK", match: ["rhabdo", "rhabdomyolysis", "ck", "creatine kinase"] },
          { id: "aki", text: "Acute kidney injury with creatinine", match: ["kidney", "renal", "creatinine", "aki"] },
          { id: "liver", text: "Liver injury with transaminases", match: ["liver", "hepatic", "hepatitis", "transaminase", "alt", "ast", "lft"] },
          { id: "dic", text: "Coagulopathy or DIC with INR, platelets and fibrinogen", match: ["dic", "coagulopathy", "coagulation", "inr", "platelet", "fibrinogen"] },
          { id: "k", text: "Hyperkalemia", match: ["potassium", "hyperkalemia", "hyperkalaemia"] },
          { id: "na", text: "Hyponatremia or hypernatremia", match: ["sodium", "hyponatremia", "hypernatremia", "hyponatraemia", "hypernatraemia", "dysnatremia"] },
          { id: "glucose", text: "Hypoglycemia", match: ["glucose", "hypoglycemia", "hypoglycaemia"] },
          { id: "lactate", text: "Lactic acidosis", match: ["lactate", "lactic", "acidosis"] },
        ],
        explanation:
          "Heat stroke injures muscle, kidney, liver and the coagulation system. Liver enzymes often peak 24 to 48 hours later. Rhabdomyolysis and hyperkalemia can threaten life even after cooling.",
        keyFeature: { topic: "environmental", n: 1 },
        source: "tintinalli",
      },
    ],
    sources: [S.wmsHeat, S.tintinalli],
    ...META,
  },

  /* 02 ------------------------------------------------------------------ */
  {
    id: "environmental-02",
    topic: "environmental",
    title: "An older man found confused during a heat wave",
    stem:
      "During the fourth day of a summer heat wave, a 79 year old man is brought from his third floor apartment, which has no air conditioning. A neighbour found him confused. He has schizophrenia and hypertension. Medications are olanzapine, benztropine and hydrochlorothiazide. HR 124, BP 96/58, RR 26, SpO2 93% on room air. Rectal temperature is 41.3 C. His skin is hot and dry.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE factors in this history that increase his risk of heat illness.",
        accept: [
          { id: "age", text: "Older age", match: ["age", "older", "elderly", "79"] },
          { id: "ac", text: "No air conditioning in an upper floor apartment", match: ["air condition", "ac", "apartment", "floor"] },
          { id: "alone", text: "Living alone and socially isolated", match: ["alone", "isolated", "isolation"] },
          { id: "anticholinergic", text: "Anticholinergic medication, benztropine", match: ["anticholinergic", "benztropine"] },
          { id: "antipsychotic", text: "Antipsychotic medication, olanzapine", match: ["antipsychotic", "olanzapine", "neuroleptic"] },
          { id: "diuretic", text: "Diuretic, hydrochlorothiazide", match: ["diuretic", "hydrochlorothiazide", "hctz", "thiazide"] },
          { id: "psych", text: "Chronic mental illness", match: ["schizophrenia", "mental illness", "psychiatric"] },
        ],
        explanation:
          "Classic heat stroke strikes older, isolated people in prolonged heat waves. Anticholinergics impair sweating, antipsychotics impair thermoregulation and diuretics reduce volume. Loss of air conditioning is a major modifiable risk.",
        keyFeature: { topic: "environmental", n: 1 },
        source: "wms-heat",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Select TWO effective cooling methods to start now.",
        options: [
          "Cold water immersion",
          "Evaporative cooling with lukewarm water spray and fans",
          "Acetaminophen 1 g rectally",
          "Ice packs to the groin and axillae as the only method",
          "Cooling blanket as the only method",
          "Dantrolene 2.5 mg/kg IV",
          "Warm IV fluids",
          "Wait for blood cultures before cooling",
        ],
        correct: [0, 1],
        explanation:
          "Cold water immersion is the most effective method and is safe in older patients with monitoring. Evaporative cooling with spray and fans is a good alternative or addition when immersion is impractical. Ice packs and cooling blankets alone are too slow. Cooling must never wait for investigations.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "wms-heat",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "While cooling, list THREE other causes of his fever and confusion that you must consider.",
        accept: [
          { id: "sepsis", text: "Sepsis, including pneumonia or meningitis", match: ["sepsis", "infection", "pneumonia", "meningitis", "encephalitis", "septic"] },
          { id: "nms", text: "Neuroleptic malignant syndrome", match: ["neuroleptic malignant", "nms"] },
          { id: "anticholinergic", text: "Anticholinergic toxicity", match: ["anticholinergic"] },
          { id: "serotonin", text: "Serotonin syndrome", match: ["serotonin"] },
          { id: "thyroid", text: "Thyroid storm", match: ["thyroid", "thyrotoxic"] },
          { id: "cns", text: "Intracranial hemorrhage or stroke", match: ["hemorrhage", "haemorrhage", "stroke", "bleed", "ich"] },
          { id: "seizure", text: "Nonconvulsive status epilepticus", match: ["status epilepticus", "seizure", "nonconvulsive"] },
          { id: "salicylate", text: "Salicylate toxicity", match: ["salicylate", "asa"] },
          { id: "withdrawal", text: "Alcohol or sedative withdrawal", match: ["withdrawal"] },
        ],
        explanation:
          "Heat stroke is a diagnosis of context, but it must not blind you. His olanzapine and benztropine raise the possibility of NMS and anticholinergic toxicity. Infection in older adults commonly causes fever and delirium. Cooling proceeds while these are sought.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "short",
        required: 3,
        prompt: "List THREE investigations that would help distinguish these causes or guide treatment.",
        accept: [
          { id: "cultures", text: "Blood cultures", match: ["blood culture", "culture"] },
          { id: "ck", text: "CK", match: ["ck", "creatine kinase"] },
          { id: "lytes", text: "Electrolytes and creatinine", match: ["electrolyte", "creatinine", "lytes", "renal"] },
          { id: "lft", text: "Liver enzymes", match: ["liver", "lft", "transaminase", "alt"] },
          { id: "coag", text: "INR, platelets and fibrinogen", match: ["inr", "coag", "coagulopathy", "platelet", "fibrinogen", "dic"] },
          { id: "tsh", text: "TSH and free T4", match: ["tsh", "thyroid", "t4"] },
          { id: "lp", text: "Lumbar puncture if meningitis is still suspected after cooling", match: ["lumbar puncture", "lp", "csf"] },
          { id: "ct", text: "CT head", match: ["ct head", "ct brain", "head ct", "ct"] },
          { id: "cxr", text: "Chest X-ray", match: ["chest x ray", "cxr", "xray"] },
          { id: "ua", text: "Urinalysis for infection and myoglobin", match: ["urinalysis", "urine"] },
          { id: "salicylate", text: "Salicylate level", match: ["salicylate", "asa level"] },
          { id: "gas", text: "Blood gas and lactate", match: ["gas", "lactate"] },
          { id: "ecg", text: "ECG", match: ["ecg"] },
        ],
        explanation:
          "Cultures and a chest X-ray look for sepsis. A markedly elevated CK with rigidity suggests NMS. Organ injury tests guide supportive care. Empiric antibiotics are reasonable when sepsis cannot be excluded.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "rosen",
      },
    ],
    sources: [S.wmsHeat, S.rosen],
    ...META,
  },

  /* 03 ------------------------------------------------------------------ */
  {
    id: "environmental-03",
    topic: "environmental",
    alsoTopics: ["tox"],
    title: "Fever and rigidity after a recent ED visit",
    stem:
      "A 32 year old man with schizophrenia is brought from his group home in July. Two days ago he received haloperidol 10 mg IM twice in another ED for agitation, and his haloperidol decanoate dose was recently increased. He is now mute and diaphoretic. Temperature 40.4 C rectal, HR 128, BP 172/104 then 118/70 ten minutes later. He has generalized lead pipe rigidity. CK is 18 400 U/L.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO clinical features that help distinguish this condition from serotonin syndrome.",
        accept: [
          { id: "rigidity", text: "Lead pipe rigidity rather than clonus", match: ["rigidity", "lead pipe", "clonus"] },
          { id: "reflex", text: "Normal or reduced reflexes rather than hyperreflexia", match: ["reflex", "reflexes", "hyporeflexia", "hyperreflexia"] },
          { id: "onset", text: "Slower onset over days rather than hours", match: ["onset", "days", "hours", "time course", "timing"] },
          { id: "drug", text: "Dopamine antagonist exposure rather than a serotonergic drug", match: ["dopamine", "antipsychotic", "haloperidol", "serotonergic", "neuroleptic"] },
          { id: "gi", text: "Absence of diarrhea and hyperactive bowel sounds", match: ["diarrhea", "diarrhoea", "bowel sound"] },
          { id: "pupils", text: "Pupils usually normal rather than dilated", match: ["pupil", "mydriasis"] },
        ],
        explanation:
          "NMS develops over days after a dopamine antagonist, with bradykinesia and lead pipe rigidity. Serotonin syndrome develops within hours, with clonus, hyperreflexia, mydriasis and diarrhea. Both cause hyperthermia and autonomic instability.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate management steps.",
        accept: [
          { id: "stop", text: "Stop all antipsychotics", match: ["stop", "discontinue", "hold", "withdraw"] },
          { id: "cool", text: "Aggressive active cooling with several methods", match: ["cool", "cooling", "ice", "evaporative", "evaporation", "immersion"] },
          { id: "benzo", text: "Benzodiazepine such as lorazepam IV", match: ["benzodiazepine", "lorazepam", "diazepam", "midazolam"] },
          { id: "fluids", text: "IV fluids for volume and rhabdomyolysis", match: ["fluid", "saline", "crystalloid", "hydration", "hydrate"] },
          { id: "icu", text: "ICU admission with monitoring", match: ["icu", "intensive care", "critical care"] },
          { id: "airway", text: "Protect the airway if needed", match: ["airway", "intubate", "intubation", "intubated"] },
          { id: "specific", text: "Bromocriptine or dantrolene in severe cases", match: ["bromocriptine", "dantrolene"] },
        ],
        unacceptable: [
          { text: "More haloperidol for agitation", match: ["haloperidol", "antipsychotic for agitation", "olanzapine"], dangerous: true },
          { text: "Physical restraint without sedation", match: ["physical restraint", "restraints only", "restrain only", "restrain without sedation", "restraint without sedation"] },
        ],
        explanation:
          "Removing the trigger and cooling aggressively come first. Benzodiazepines reduce rigidity and agitation. Further antipsychotic would worsen the syndrome and could be fatal. Severe cases need ICU care.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "menu",
        select: 2,
        prompt: "His temperature remains 40 C and rigidity persists after an hour. Select TWO appropriate specific therapies.",
        options: [
          "Bromocriptine 2.5 mg via NG tube every 8 hours",
          "Bromocriptine 50 mg via NG tube once",
          "Dantrolene 1 to 2.5 mg/kg IV",
          "Dantrolene 25 mg/kg IV",
          "Cyproheptadine 12 mg via NG tube",
          "Haloperidol 5 mg IV",
          "Succinylcholine 1.5 mg/kg IV",
          "Acetaminophen 1 g IV",
        ],
        correct: [0, 2],
        explanation:
          "Bromocriptine is a dopamine agonist started at 2.5 mg two or three times daily. Dantrolene at 1 to 2.5 mg/kg IV reduces muscle heat production in severe rigidity. Cyproheptadine treats serotonin syndrome. Succinylcholine risks hyperkalemia in rhabdomyolysis.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO complications to monitor for over the next 48 hours.",
        accept: [
          { id: "aki", text: "Acute kidney injury from rhabdomyolysis", match: ["kidney", "renal", "aki", "creatinine", "rhabdo", "rhabdomyolysis"] },
          { id: "k", text: "Hyperkalemia", match: ["potassium", "hyperkalemia", "hyperkalaemia"] },
          { id: "resp", text: "Aspiration pneumonia or respiratory failure", match: ["aspiration", "pneumonia", "respiratory"] },
          { id: "dic", text: "DIC", match: ["dic", "coagulopathy", "coagulation"] },
          { id: "vte", text: "Venous thromboembolism", match: ["thrombosis", "thromboembolism", "clot", "dvt", "pe", "vte"] },
          { id: "arrhythmia", text: "Arrhythmia", match: ["arrhythmia", "dysrhythmia"] },
          { id: "seizure", text: "Seizures", match: ["seizure"] },
          { id: "liver", text: "Liver injury", match: ["liver", "hepatic", "hepatitis"] },
        ],
        explanation:
          "NMS kills through rhabdomyolysis, renal failure, aspiration and autonomic collapse. Immobility and dehydration add VTE risk. Recovery usually takes 1 to 2 weeks, longer after depot antipsychotics.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "tintinalli",
      },
    ],
    sources: [S.rosen, S.tintinalli],
    ...META,
  },

  /* 04 ------------------------------------------------------------------ */
  {
    id: "environmental-04",
    topic: "environmental",
    title: "A roofer who collapsed at work",
    stem:
      "A 45 year old woman working on a roof in July is brought in after becoming confused and agitated. Temperature 40.2 C rectal, HR 168 irregularly irregular, BP 146/64, RR 28. She has a fine tremor and a diffuse goitre. Her co-worker says she lost weight recently and stopped a thyroid pill two months ago.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO cooling measures you start immediately.",
        accept: [
          { id: "evap", text: "Evaporative cooling with water spray and fans", match: ["evaporative", "evaporation", "spray", "fan", "mist"] },
          { id: "immersion", text: "Cold water immersion", match: ["immersion", "ice water", "cold water"] },
          { id: "ice", text: "Ice packs to neck, axillae and groin", match: ["ice pack", "ice"] },
          { id: "fluids", text: "Cool IV fluids", match: ["cool fluid", "cold fluid", "chilled", "cold saline", "cool iv", "cold iv"] },
          { id: "blanket", text: "Cooling blanket or surface cooling device", match: ["blanket", "surface cooling", "cooling pad"] },
          { id: "undress", text: "Remove clothing", match: ["undress", "clothing"] },
          { id: "apap", text: "Acetaminophen as an adjunct in thyrotoxicosis", match: ["acetaminophen", "tylenol"] },
        ],
        unacceptable: [{ text: "ASA as antipyretic", match: ["asa", "aspirin", "salicylate"] }],
        explanation:
          "Cool at once with several methods, before the cause is confirmed. Acetaminophen may help in thyroid storm because the set point may be raised, but physical cooling remains essential. Salicylates displace thyroid hormone from binding proteins and should be avoided.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "ata-thyro",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE clues that point to a cause other than environmental heat alone.",
        accept: [
          { id: "goitre", text: "Goitre", match: ["goitre", "goiter", "thyroid enlargement"] },
          { id: "stopped", text: "Stopped antithyroid medication", match: ["stopped", "thyroid pill", "methimazole", "medication"] },
          { id: "af", text: "Atrial fibrillation with rapid rate", match: ["atrial fibrillation", "af", "irregular"] },
          { id: "tremor", text: "Tremor", match: ["tremor"] },
          { id: "weight", text: "Recent weight loss", match: ["weight"] },
          { id: "pp", text: "Wide pulse pressure", match: ["pulse pressure"] },
          { id: "hr", text: "Tachycardia out of proportion to temperature", match: ["tachycardia", "heart rate", "168"] },
        ],
        explanation:
          "A goitre, stopped antithyroid drug, weight loss, tremor and rapid atrial fibrillation suggest thyroid storm triggered by heat and exertion. Recognizing an alternative cause changes treatment. Cooling still proceeds without delay.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "ata-thyro",
      },
      {
        id: "q3",
        kind: "menu",
        select: 3,
        prompt: "Select THREE appropriate treatments for the underlying condition.",
        options: [
          "Propranolol 60 to 80 mg PO every 4 hours",
          "Propylthiouracil 500 to 1000 mg PO load, then 250 mg every 4 hours",
          "Hydrocortisone 100 mg IV every 8 hours",
          "Potassium iodide before any thionamide",
          "Levothyroxine 100 mcg IV",
          "ASA 650 mg PO",
          "Amiodarone 150 mg IV as the first line rate control",
          "Dantrolene 2.5 mg/kg IV",
        ],
        correct: [0, 1, 2],
        explanation:
          "Thyroid storm treatment combines a beta blocker, a thionamide to block synthesis, iodine at least an hour after the thionamide, and glucocorticoids. Iodine given first can fuel more hormone synthesis. Amiodarone contains iodine and is not first line.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "ata-thyro",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "When should iodine be given in relation to the thionamide? Select one.",
        options: [
          "At the same time",
          "At least 1 hour after the thionamide",
          "At least 1 hour before the thionamide",
          "Only after 24 hours of thionamide",
          "Iodine is contraindicated in thyroid storm",
        ],
        correct: 1,
        explanation:
          "Iodine blocks hormone release, but it is also substrate for new hormone synthesis. Giving the thionamide first blocks organification so iodine cannot be used to make more hormone. The usual gap is at least 1 hour.",
        keyFeature: { topic: "environmental", n: 2 },
        source: "ata-thyro",
      },
    ],
    sources: [S.ataThyro],
    ...META,
  },

  /* 05 ------------------------------------------------------------------ */
  {
    id: "environmental-05",
    topic: "environmental",
    title: "A snowshoer found after a night outdoors",
    stem:
      "Police search and rescue bring in a 52 year old man who was lost snowshoeing for 9 hours at minus 18 C. He is drowsy and not shivering. GCS 12, HR 42, BP 92/58, RR 10. SpO2 does not read. The triage oral thermometer displays LO. The ECG shows sinus bradycardia with J waves.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO reliable ways to measure his core temperature.",
        accept: [
          { id: "eso", text: "Esophageal probe in the lower third, once the airway is secured", match: ["esophageal", "oesophageal"] },
          { id: "rectal", text: "Low reading rectal probe", match: ["rectal"] },
          { id: "bladder", text: "Bladder temperature catheter", match: ["bladder", "foley"] },
          { id: "epitympanic", text: "Epitympanic thermistor probe", match: ["epitympanic", "thermistor"] },
        ],
        unacceptable: [
          { text: "Oral thermometer", match: ["oral"] },
          { text: "Infrared tympanic thermometer", match: ["infrared", "tympanic thermometer", "ear thermometer"] },
          { text: "Axillary or temporal thermometer", match: ["axillary", "temporal", "forehead"] },
        ],
        explanation:
          "An esophageal probe is most accurate once the airway is protected. Rectal and bladder probes are acceptable but lag during rewarming. Standard thermometers often do not read below 34 C. Infrared tympanic and oral readings are unreliable in the cold.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
      {
        id: "q2",
        kind: "single",
        update: "A rectal probe reads 29.8 C.",
        prompt: "Which is the most appropriate rewarming strategy? Select one.",
        options: [
          "Passive rewarming with blankets only",
          "Active external rewarming with forced air plus warmed IV fluids, and alert an ECLS capable centre",
          "Immediate ECMO cannulation while he has a perfusing rhythm",
          "Immersion in a 42 C bath",
          "Warm peritoneal lavage",
        ],
        correct: 1,
        explanation:
          "He has moderate hypothermia with a perfusing rhythm. Forced air warming, warm blankets and warmed IV fluids at 38 to 42 C rewarm at about 1 to 2 C per hour. Extracorporeal rewarming is reserved for cardiac arrest or instability that does not respond. His core temperature below 30 C and heart rate below 45 are European criteria for early contact with, or direct transfer to, an ECLS centre in case he arrests. Warm baths cause vasodilation and collapse.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        prompt: "List THREE precautions during his resuscitation.",
        accept: [
          { id: "gentle", text: "Gentle handling and keep him horizontal", match: ["gentle", "horizontal", "avoid rough", "no rough", "avoid jostling", "minimal movement", "handling", "rough", "movement"] },
          { id: "monitor", text: "Continuous cardiac monitoring with pads on", match: ["monitor", "pad", "defib", "defibrillator", "defibrillation"] },
          { id: "warmfluid", text: "Only warmed IV fluids, 38 to 42 C", match: ["warm fluid", "warmed fluid", "warmed iv", "warm iv", "warm saline", "warmed saline"] },
          { id: "central", text: "Avoid deep central line guidewires into the heart", match: ["avoid central line", "no central line", "avoid guidewire", "no guidewire", "avoid deep guidewire", "avoid wire", "short guidewire", "femoral line"] },
          { id: "glucose", text: "Check glucose", match: ["glucose", "sugar"] },
          { id: "volume", text: "Anticipate hypotension during rewarming and give volume", match: ["hypotension", "volume", "bolus"] },
          { id: "wet", text: "Remove wet clothing and insulate", match: ["wet", "clothing", "insulate", "insulation"] },
          { id: "afterdrop", text: "Watch for afterdrop", match: ["afterdrop", "after drop"] },
          { id: "brady", text: "Do not treat the bradycardia with pacing or atropine", match: ["not treat bradycardia", "don treat bradycardia", "no atropine", "no pacing", "avoid atropine", "avoid pacing", "bradycardia physiological", "bradycardia physiologic", "bradycardia expected"] },
        ],
        explanation:
          "The cold myocardium is irritable, and rough handling or wires in the heart can trigger VF. Bradycardia is physiological and resolves with warming. Rewarming causes vasodilation and hypotension, so warmed volume is needed.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
      {
        id: "q4",
        kind: "single",
        update: "While moving him to the CT table, he goes into ventricular fibrillation. Core temperature is 29.5 C.",
        prompt: "Which is the most appropriate management? Select one.",
        options: [
          "CPR, up to three shocks, hold epinephrine until core temperature is above 30 C, and arrange extracorporeal rewarming",
          "Standard ACLS with epinephrine every 3 to 5 minutes and shocks every 2 minutes, with forced air warming only",
          "Stop resuscitation, since VF below 30 C is not survivable",
          "Amiodarone 300 mg IV before any shock",
          "Forced air warming and delay CPR until he is warmer",
        ],
        correct: 0,
        explanation:
          "Below 30 C the heart often does not respond to shocks or drugs, and drugs accumulate. European guidance allows up to three shocks, then withholds further shocks and epinephrine until above 30 C. AHA guidance, which Heart and Stroke Canada follows, allows standard shocks and epinephrine alongside rewarming. Either way, the priority is extracorporeal rewarming. Hypothermic arrest has good survival with extracorporeal rewarming, so it is a reason to escalate, not stop.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "erc",
      },
      {
        id: "q5",
        kind: "short",
        required: 2,
        prompt: "Looking back at his first ECG, list TWO findings typical of hypothermia.",
        accept: [
          { id: "jwave", text: "Osborn or J waves", match: ["osborn", "j wave", "j point"] },
          { id: "brady", text: "Sinus bradycardia", match: ["bradycardia", "slow"] },
          { id: "intervals", text: "Prolonged PR, QRS or QT intervals", match: ["prolonged", "qt", "pr", "qrs", "interval"] },
          { id: "af", text: "Atrial fibrillation with slow ventricular response", match: ["atrial fibrillation", "af"] },
          { id: "artifact", text: "Shivering artifact", match: ["artifact", "artefact", "shivering"] },
          { id: "ectopy", text: "Ventricular ectopy", match: ["ectopy", "pvc", "premature"] },
        ],
        explanation:
          "J waves at the junction of the QRS and ST segment grow larger as temperature falls. Bradycardia and prolonged intervals reflect slowed conduction. Atrial fibrillation is common and usually resolves with rewarming.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
    ],
    sources: [S.wmsHypo, S.erc],
    ...META,
  },

  /* 06 ------------------------------------------------------------------ */
  {
    id: "environmental-06",
    topic: "environmental",
    title: "A man found in a snowbank",
    stem:
      "Paramedics bring in a 34 year old man found in a snowbank at 0500 after leaving a party. He had been seen walking at 0100. Bystanders heard him moaning when he was found, and he became pulseless just as paramedics arrived. He has had 40 minutes of CPR. He is intubated. Rhythm is VF. Esophageal temperature is 23.8 C. The nearest ECMO centre is 45 minutes away by land.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO features that support continuing resuscitation with extracorporeal rewarming.",
        accept: [
          { id: "temp", text: "Core temperature below 30 C, consistent with hypothermic arrest", match: ["temperature", "23.8", "below 30", "below 32", "hypothermia", "hypothermic"] },
          { id: "witnessed", text: "Arrest occurred after cooling, witnessed by paramedics", match: ["witnessed", "arrest after", "cooled before", "moaning", "signs of life"] },
          { id: "young", text: "Young age and no major comorbidity", match: ["young", "age", "comorbid"] },
          { id: "vf", text: "Shockable rhythm", match: ["vf", "shockable", "ventricular fibrillation"] },
          { id: "noasphyxia", text: "No asphyxia or lethal injury", match: ["asphyxia", "injury", "injuries", "trauma", "airway patent"] },
          { id: "cpr", text: "Continuous CPR since arrest", match: ["continuous cpr", "cpr since", "high quality cpr", "cpr"] },
        ],
        explanation:
          "He cooled while alive and then arrested, the pattern with the best outcome. A core temperature this low can protect the brain for hours. With ECMO rewarming, survival with good neurological outcome after prolonged CPR is well described.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which rewarming method is most appropriate? Select one.",
        options: [
          "Forced air warming and warm IV fluids",
          "Extracorporeal life support with VA ECMO or cardiopulmonary bypass",
          "Warm bladder irrigation",
          "Hemodialysis",
          "Warm humidified oxygen alone",
        ],
        correct: 1,
        explanation:
          "ECLS rewarms at several degrees per hour while providing full circulation and oxygenation. It is the method of choice for hypothermic cardiac arrest. If ECLS is truly unavailable, thoracic lavage is the best alternative, but it is far less effective.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "erc",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO measures for his transfer to the ECMO centre.",
        accept: [
          { id: "mech", text: "Mechanical CPR device", match: ["mechanical", "lucas", "autopulse", "device"] },
          { id: "notify", text: "Pre-notify the ECMO team to be ready on arrival", match: ["notify", "ecmo team", "activate", "ready"] },
          { id: "cpr", text: "Continue CPR throughout, or intermittent CPR if continuous CPR is impossible", match: ["continue cpr", "intermittent", "cpr"] },
          { id: "insulate", text: "Prevent further heat loss", match: ["heat loss", "insulate", "insulation", "warm", "blanket"] },
          { id: "epi", text: "Withhold epinephrine and repeated shocks below 30 C", match: ["withhold epinephrine", "withhold shock", "no epinephrine", "hold epinephrine", "avoid epinephrine", "no shock", "no further shock", "hold shock"] },
          { id: "vent", text: "Ventilate with capnography and oxygen", match: ["ventilate", "ventilation", "ventilator", "capnography", "etco2", "oxygen"] },
          { id: "labs", text: "Send a potassium level", match: ["potassium", "k"] },
        ],
        explanation:
          "A mechanical CPR device gives consistent compressions during transport. Wilderness guidance allows intermittent CPR in severe hypothermia when continuous CPR is impossible. The ECMO team needs time to set up.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which finding would most strongly argue against extracorporeal rewarming in an adult? Select one.",
        options: [
          "Serum potassium 14 mmol/L",
          "pH 6.9",
          "Lactate 12 mmol/L",
          "Glucose 15 mmol/L",
          "Fixed dilated pupils",
        ],
        correct: 0,
        explanation:
          "A very high potassium suggests cell death before cooling, often from asphyxia. No adult has survived with a potassium above 12 mmol/L, and older sources used 10 mmol/L. The HOPE score is now preferred where possible. Acidosis, lactate and fixed pupils are expected and do not predict death in hypothermic arrest.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "hope",
      },
      {
        id: "q5",
        kind: "single",
        prompt: "When may resuscitation be stopped in hypothermic cardiac arrest without another lethal cause? Select one.",
        options: [
          "When core temperature reaches 28 C",
          "When core temperature has been restored to at least 32 C and asystole persists",
          "After 60 minutes of CPR regardless of temperature",
          "When the pupils are fixed and dilated",
          "When core temperature reaches 37 C",
        ],
        correct: 1,
        explanation:
          "The patient is not dead until warm and dead. Resuscitation continues until core temperature is at least 32 C. Termination is then reasonable if asystole persists. Pupils and duration of CPR are unreliable guides in hypothermia.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "erc",
      },
    ],
    sources: [S.wmsHypo, S.erc, S.hope],
    ...META,
  },

  /* 07 ------------------------------------------------------------------ */
  {
    id: "environmental-07",
    topic: "environmental",
    title: "An older woman found cold at home",
    stem:
      "An 81 year old woman is brought in after her son found her in bed, confused, in a house heated only by a small space heater. She has been slowing down for months. Bladder temperature is 31.4 C. HR 48, BP 90/52, RR 10, SpO2 94% on room air. She is not shivering. Her face is puffy and her tongue appears large.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE underlying causes you must look for in this patient.",
        accept: [
          { id: "thyroid", text: "Hypothyroidism or myxedema", match: ["thyroid", "myxedema", "myxoedema"] },
          { id: "sepsis", text: "Sepsis", match: ["sepsis", "infection", "septic", "pneumonia", "uti"] },
          { id: "glucose", text: "Hypoglycemia", match: ["hypoglycemia", "hypoglycaemia", "glucose"] },
          { id: "adrenal", text: "Adrenal insufficiency", match: ["adrenal", "cortisol", "addison"] },
          { id: "cns", text: "Stroke or intracranial bleed", match: ["stroke", "intracranial", "hemorrhage", "subdural", "bleed"] },
          { id: "drugs", text: "Sedating drugs or alcohol", match: ["drug", "alcohol", "sedative", "medication", "overdose"] },
          { id: "pit", text: "Hypopituitarism", match: ["pituitary", "hypopituitarism", "panhypopituitarism"] },
          { id: "fall", text: "Fall with fracture or immobility", match: ["fall", "fracture", "immobility", "immobile", "immobilization"] },
          { id: "wernicke", text: "Thiamine deficiency", match: ["thiamine", "wernicke"] },
          { id: "co", text: "Carbon monoxide from the heater", match: ["carbon monoxide", "co"] },
        ],
        explanation:
          "Urban hypothermia in older adults is often secondary. Her puffy face, large tongue and months of slowing suggest myxedema. Sepsis, hypoglycemia and adrenal insufficiency must also be excluded because each is treatable.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE investigations to send now.",
        accept: [
          { id: "tsh", text: "TSH and free T4", match: ["tsh", "t4", "thyroid"] },
          { id: "cortisol", text: "Random cortisol", match: ["cortisol"] },
          { id: "glucose", text: "Glucose", match: ["glucose"] },
          { id: "cultures", text: "Blood and urine cultures", match: ["culture"] },
          { id: "lytes", text: "Electrolytes and creatinine", match: ["electrolyte", "sodium", "creatinine", "lytes"] },
          { id: "ck", text: "CK", match: ["ck", "creatine kinase"] },
          { id: "gas", text: "Blood gas and lactate", match: ["gas", "lactate"] },
          { id: "ecg", text: "ECG", match: ["ecg"] },
          { id: "cohb", text: "Carboxyhemoglobin", match: ["carboxyhemoglobin", "cohb"] },
          { id: "cbc", text: "CBC", match: ["cbc", "blood count"] },
          { id: "cxr", text: "Chest X-ray", match: ["cxr", "chest x ray", "xray"] },
          { id: "ct", text: "CT head", match: ["ct"] },
        ],
        explanation:
          "Thyroid, cortisol and glucose results define treatable causes. Cultures and a chest X-ray look for sepsis. Blood gases are interpreted without temperature correction in hypothermia.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "single",
        update: "After two hours of forced air warming and warmed fluids, her temperature has risen only 0.3 C per hour. Sodium is 127 mmol/L and glucose 3.4 mmol/L. TSH is pending.",
        prompt: "Which is the most appropriate treatment? Select one.",
        options: [
          "Levothyroxine 200 to 400 mcg IV plus hydrocortisone 100 mg IV",
          "Levothyroxine 25 mcg PO daily",
          "Hydrocortisone 100 mg IV alone and wait for the TSH",
          "Levothyroxine 300 mcg IV alone",
          "Wait for the TSH before any hormone therapy",
        ],
        correct: 0,
        explanation:
          "Failure to rewarm with active external warming suggests an endocrine cause. Suspected myxedema coma is treated empirically with IV levothyroxine. Hydrocortisone is given first or together because adrenal insufficiency may coexist and thyroid hormone can precipitate adrenal crisis.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "ata-hypo",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "List TWO complications to anticipate during rewarming.",
        accept: [
          { id: "hypotension", text: "Rewarming hypotension from vasodilation", match: ["hypotension", "vasodilation", "vasodilatation", "shock"] },
          { id: "arrhythmia", text: "Arrhythmias such as atrial fibrillation or VF", match: ["arrhythmia", "vf", "fibrillation", "dysrhythmia"] },
          { id: "afterdrop", text: "Afterdrop of core temperature", match: ["afterdrop", "after drop"] },
          { id: "k", text: "Potassium shifts", match: ["potassium", "hyperkalemia", "hyperkalaemia", "hypokalemia", "hypokalaemia"] },
          { id: "glucose", text: "Hypoglycemia", match: ["glucose", "hypoglycemia", "hypoglycaemia"] },
          { id: "burns", text: "Burns from heat packs on poorly perfused skin", match: ["burn"] },
          { id: "coag", text: "Coagulopathy", match: ["coagulopathy", "coagulation", "bleed"] },
          { id: "rhabdo", text: "Rhabdomyolysis", match: ["rhabdo", "rhabdomyolysis"] },
          { id: "edema", text: "Pulmonary edema from fluid", match: ["pulmonary edema", "pulmonary oedema", "fluid overload"] },
        ],
        explanation:
          "As peripheral vessels dilate, blood pressure falls and cold blood returns to the core. The cold myocardium stays prone to arrhythmia. Hot packs can burn cold skin, so forced air is preferred.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-hypo",
      },
    ],
    sources: [S.rosen, S.ataHypo, S.wmsHypo],
    ...META,
  },

  /* 08 ------------------------------------------------------------------ */
  {
    id: "environmental-08",
    topic: "environmental",
    title: "A child pulled from a frozen pond",
    stem:
      "A 4 year old boy, 17 kg, fell through the ice on a pond in March. Firefighters pulled him out after about 12 minutes under water. He was pulseless and apneic. Paramedics have done CPR for 20 minutes. He is 25 minutes from your pediatric tertiary centre, which has ECMO. The paramedic patches to you from the ambulance.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO directions for the crew during transport.",
        accept: [
          { id: "vent", text: "Prioritize ventilation and oxygenation with bag valve mask or airway", match: ["ventilate", "ventilation", "ventilator", "breath", "oxygen", "bvm", "bag", "airway"] },
          { id: "cpr", text: "Continue high quality CPR", match: ["continue cpr", "cpr", "compression"] },
          { id: "wet", text: "Remove wet clothing and prevent further heat loss", match: ["wet", "clothing", "heat loss", "blanket", "insulate", "insulation", "warm"] },
          { id: "temp", text: "Measure core temperature", match: ["temperature"] },
          { id: "defib", text: "Attach defibrillator and shock a shockable rhythm", match: ["defib", "defibrillator", "defibrillation", "pad", "shock", "aed"] },
          { id: "io", text: "IO or IV access if it does not delay transport", match: ["io", "intraosseous", "iv access", "iv line"] },
        ],
        unacceptable: [{ text: "Abdominal thrusts to drain water", match: ["abdominal thrust", "heimlich", "drain water", "drain the lung"] }],
        explanation:
          "Drowning is a hypoxic arrest, so ventilation is the priority. Abdominal thrusts to remove water delay ventilation and cause vomiting and aspiration. Further heat loss must be stopped, but severe hypothermia is itself a reason to continue.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-drown",
      },
      {
        id: "q2",
        kind: "single",
        update: "He arrives in asystole. Rectal temperature is 26.9 C.",
        prompt: "Which is the most appropriate plan? Select one.",
        options: [
          "Stop resuscitation because submersion exceeded 10 minutes",
          "Continue CPR and proceed to ECMO rewarming",
          "Forced air warming for 10 minutes, then stop if no ROSC",
          "Stop resuscitation because he is in asystole",
          "Continue CPR until core temperature reaches 30 C, then stop",
        ],
        correct: 1,
        explanation:
          "Submersion in icy water can cool a small child quickly and protect the brain. Pediatric survivors of long ice water submersion have been rewarmed with ECMO. Asystole and submersion time are not reliable reasons to stop while he is this cold.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "erc",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO factors associated with poor outcome in drowning.",
        accept: [
          { id: "sub", text: "Submersion longer than 10 minutes", match: ["submersion", "duration", "10 minute", "time under"] },
          { id: "cpr", text: "Delay to effective CPR", match: ["delay", "bystander cpr", "time to cpr"] },
          { id: "cprlong", text: "Prolonged resuscitation without ROSC", match: ["prolonged", "long resuscitation", "no rosc"] },
          { id: "gcs", text: "Coma or GCS 3 on arrival", match: ["gcs", "coma", "unresponsive"] },
          { id: "asystole", text: "Asystole on arrival", match: ["asystole"] },
          { id: "acid", text: "Severe acidosis", match: ["acidosis", "ph"] },
          { id: "warm", text: "Warm water submersion", match: ["warm water"] },
          { id: "pupils", text: "Fixed pupils after rewarming", match: ["pupil"] },
        ],
        explanation:
          "Submersion duration is the strongest predictor of outcome. Delayed CPR, prolonged resuscitation and coma on arrival are also associated with death or severe disability. Cold water may be protective only if cooling happened before hypoxic injury.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-drown",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "He is placed on ECMO and has ROSC at 33 C.",
        prompt: "List TWO complications to anticipate in the next 24 hours.",
        accept: [
          { id: "ards", text: "ARDS or pulmonary edema", match: ["ards", "pulmonary edema", "pulmonary oedema", "lung injury", "respiratory distress"] },
          { id: "brain", text: "Hypoxic brain injury and cerebral edema", match: ["brain", "cerebral", "hypoxic", "neuro", "neurological", "neurologic", "seizure"] },
          { id: "arrhythmia", text: "Arrhythmias", match: ["arrhythmia", "dysrhythmia"] },
          { id: "coag", text: "Coagulopathy and bleeding on ECMO", match: ["coagulopathy", "coagulation", "bleed", "dic"] },
          { id: "k", text: "Electrolyte disturbance such as hyperkalemia", match: ["potassium", "electrolyte", "hyperkalemia", "hyperkalaemia"] },
          { id: "pneumonia", text: "Aspiration pneumonia", match: ["pneumonia", "aspiration"] },
          { id: "aki", text: "Acute kidney injury", match: ["kidney", "renal", "aki"] },
          { id: "fever", text: "Rebound hyperthermia", match: ["hyperthermia", "fever"] },
        ],
        explanation:
          "Aspiration and surfactant loss cause lung injury that may worsen over hours. Hypoxic brain injury is the main determinant of outcome. Fever after arrest should be avoided.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-drown",
      },
    ],
    sources: [S.wmsDrown, S.erc],
    ...META,
  },

  /* 09 ------------------------------------------------------------------ */
  {
    id: "environmental-09",
    topic: "environmental",
    title: "Hard white fingers in January",
    stem:
      "A 38 year old man is brought in by police at 0300 in January. He slept outside after drinking. The overnight low was minus 29 C. Both hands are white, hard and numb to the wrists. Rectal temperature is 34.6 C. HR 96, BP 118/70, glucose 4.8 mmol/L. He has not been rewarmed.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO priorities before rewarming his hands.",
        accept: [
          { id: "core", text: "Correct systemic hypothermia first, to about 35 C", match: ["hypothermia", "hypothermic", "core", "35", "systemic"] },
          { id: "abc", text: "Assess and support airway, breathing and circulation", match: ["abc", "airway", "circulation", "resuscitate", "resuscitation"] },
          { id: "trauma", text: "Look for trauma and other injuries", match: ["trauma", "injury", "injuries", "secondary survey"] },
          { id: "analgesia", text: "Give opioid analgesia, since rewarming is very painful", match: ["analgesia", "analgesic", "opioid", "pain", "morphine", "hydromorphone", "fentanyl"] },
          { id: "refreeze", text: "Ensure no risk of refreezing", match: ["no refreezing", "avoid refreezing", "prevent refreezing", "not refreeze", "no refreeze", "refreezing", "refreeze"] },
          { id: "tox", text: "Assess intoxication and co-ingestions", match: ["intoxication", "intoxicated", "alcohol", "ingestion", "tox", "toxic", "toxicity"] },
          { id: "fluids", text: "IV fluids for volume depletion", match: ["fluid"] },
        ],
        explanation:
          "Systemic hypothermia takes priority because it threatens life. Wilderness guidance suggests a core temperature of at least 35 C before rewarming frostbite. Thawing is intensely painful and needs parenteral analgesia.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-frost",
      },
      {
        id: "q2",
        kind: "menu",
        select: 2,
        prompt: "Select TWO appropriate treatments for his hands.",
        options: [
          "Immersion in circulating water at 37 to 39 C until tissue is soft and red or purple",
          "Immersion in water at 44 to 46 C for 10 minutes",
          "Dry heat from a heater or heat lamp",
          "Rubbing the hands with snow",
          "Slow passive rewarming at room temperature",
          "Ibuprofen 400 mg PO twice daily",
          "Prednisone 50 mg PO daily",
          "Warfarin",
        ],
        correct: [0, 5],
        explanation:
          "Rapid rewarming in 37 to 39 C water, usually about 30 minutes, is the standard. Hotter water burns insensate tissue and dry heat is uncontrolled. Rubbing causes further injury. Ibuprofen, about 12 mg/kg/day divided twice daily (400 mg twice daily for most adults), inhibits prostaglandins and thromboxane that drive progressive ischemia.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-frost",
      },
      {
        id: "q3",
        kind: "short",
        required: 3,
        update: "After rewarming, several fingers remain cyanotic beyond the PIP joints and have hemorrhagic blisters. It is 4 hours since rewarming.",
        prompt: "List THREE further management steps.",
        accept: [
          { id: "tpa", text: "Discuss thrombolysis with tPA within 24 hours of injury, ideally within 12 hours, at a capable centre", match: ["tpa", "alteplase", "thrombolys", "tissue plasminogen"] },
          { id: "iloprost", text: "Consider IV iloprost", match: ["iloprost", "prostacyclin"] },
          { id: "imaging", text: "Perfusion imaging with bone scan or angiography", match: ["bone scan", "angiography", "angiogram", "scintigraphy", "technetium", "imaging"] },
          { id: "tetanus", text: "Tetanus prophylaxis", match: ["tetanus"] },
          { id: "blisters", text: "Leave hemorrhagic blisters intact", match: ["leave hemorrhagic", "leave blister", "intact", "not unroof", "don unroof", "not drain", "don drain"] },
          { id: "aloe", text: "Topical aloe vera to blisters", match: ["aloe"] },
          { id: "dressing", text: "Loose bulky dressings, splint and elevate", match: ["dressing", "splint", "elevate", "elevation", "elevated"] },
          { id: "consult", text: "Consult plastic surgery or a burn centre", match: ["plastic", "burn centre", "burn center", "surgery", "surgeon", "surgical", "consult"] },
          { id: "smoking", text: "No smoking", match: ["no smoking", "avoid smoking", "stop smoking", "smoking cessation", "not smoke", "smoking", "smoke"] },
        ],
        unacceptable: [
          { text: "Early amputation or debridement of fingers", match: ["amputate", "amputation", "debride finger"] },
          { text: "Unroof hemorrhagic blisters", match: ["unroof hemorrhagic", "drain hemorrhagic", "aspirate hemorrhagic"] },
        ],
        explanation:
          "Severe frostbite with poor perfusion may benefit from tPA within 24 hours of injury, best within 12 hours, or iloprost, guided by angiography or bone scan. Hemorrhagic blisters are left intact. The extent of tissue loss declares itself over weeks, so early amputation is avoided.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-frost",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which test best predicts tissue viability? Select one.",
        options: ["Plain X-ray of the hands", "Technetium 99m bone scintigraphy", "MRI", "Nerve conduction studies", "CT of the hands without contrast"],
        correct: 1,
        explanation:
          "Technetium 99m bone scintigraphy shows early loss of perfusion and predicts amputation level. Digital angiography is the alternative used during thrombolysis. Plain films are normal early.",
        keyFeature: { topic: "environmental", n: 3 },
        source: "wms-frost",
      },
    ],
    sources: [S.wmsFrost],
    ...META,
  },

  /* 10 ------------------------------------------------------------------ */
  {
    id: "environmental-10",
    topic: "environmental",
    title: "Back pain and leg numbness after a weekend trip",
    stem:
      "A 42 year old man presents at 2100 with mid back pain, tingling in both legs and difficulty passing urine. Today he did three wreck dives to 30 m on air in a Great Lakes marine park. He surfaced from the last dive at 1600 and drove home. HR 88, BP 136/84, SpO2 98% on room air. He has decreased sensation below T10 and mild bilateral leg weakness.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE further details of the dive history you want.",
        accept: [
          { id: "profile", text: "Depth and bottom time of each dive", match: ["depth", "bottom time", "profile", "time at depth"] },
          { id: "ascent", text: "Ascent rate, missed safety or decompression stops", match: ["ascent", "safety stop", "decompression stop", "missed stop", "rapid"] },
          { id: "surface", text: "Surface intervals between dives", match: ["surface interval", "interval"] },
          { id: "onset", text: "Time of symptom onset after surfacing", match: ["onset", "when symptoms", "time of symptom"] },
          { id: "gas", text: "Breathing gas used", match: ["gas", "nitrox", "air", "mix"] },
          { id: "computer", text: "Dive computer data", match: ["computer", "log"] },
          { id: "altitude", text: "Travel to altitude or flying after the dive", match: ["altitude", "fly", "flight", "mountain"] },
          { id: "buddy", text: "Whether the buddy has symptoms", match: ["buddy"] },
          { id: "prior", text: "Previous decompression illness or PFO", match: ["previous", "prior", "pfo"] },
          { id: "problem", text: "Any problem underwater such as running out of air", match: ["out of air", "problem", "equipment", "panic"] },
        ],
        explanation:
          "Depth, time, ascent rate and repeat dives define the inert gas load. Onset timing helps separate decompression sickness from gas embolism. Dive computer data is invaluable to the hyperbaric physician.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE immediate treatments.",
        accept: [
          { id: "o2", text: "100% oxygen by non-rebreather or demand valve", match: ["oxygen", "o2", "non rebreather", "nonrebreather"] },
          { id: "fluids", text: "Isotonic IV fluids without glucose", match: ["fluid", "saline", "ringer", "crystalloid"] },
          { id: "supine", text: "Keep him supine", match: ["supine", "flat", "avoid trendelenburg", "no trendelenburg", "no head down"] },
          { id: "foley", text: "Urinary catheter for retention", match: ["catheter", "foley"] },
          { id: "hbo", text: "Urgent referral for hyperbaric recompression", match: ["hyperbaric", "recompression", "hbo", "chamber"] },
          { id: "dan", text: "Call Divers Alert Network or the hyperbaric physician", match: ["divers alert", "dan"] },
          { id: "analgesia", text: "Simple analgesia such as an NSAID", match: ["nsaid", "analgesia", "analgesic", "ibuprofen", "acetaminophen"] },
        ],
        unacceptable: [
          { text: "Nitrous oxide for analgesia", match: ["nitrous", "entonox"], dangerous: true },
          { text: "Head down position", match: ["trendelenburg", "head down"] },
          { text: "Dextrose containing fluids", match: ["dextrose", "d5w"] },
        ],
        explanation:
          "Spinal cord decompression sickness needs recompression as soon as possible. High flow oxygen speeds nitrogen washout and shrinks bubbles. Nitrous oxide diffuses into bubbles and enlarges them. Head down positioning is no longer advised.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q3",
        kind: "single",
        prompt: "The nearest chamber is 300 km away. Which transport is most appropriate? Select one.",
        options: [
          "Commercial flight",
          "Unpressurized aircraft cruising at 8000 feet",
          "Land ambulance or aircraft pressurized to sea level or flown very low",
          "Delay transfer until symptoms stabilize for 24 hours",
          "Private car driven by his wife",
        ],
        correct: 2,
        explanation:
          "Any fall in ambient pressure enlarges bubbles and worsens injury. Air transport should keep the cabin at sea level pressure or fly as low as safely possible. Ground transport is acceptable when it does not add major delay.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which recompression schedule is the usual initial treatment for his condition? Select one.",
        options: [
          "US Navy Treatment Table 5",
          "US Navy Treatment Table 6",
          "US Navy Treatment Table 9",
          "100% oxygen at 1 atmosphere for 24 hours",
          "In-water recompression on air",
        ],
        correct: 1,
        explanation:
          "Treatment Table 6 is the standard first treatment for neurological decompression sickness and gas embolism. It uses oxygen at 2.8 atmospheres with air breaks. Table 5 is for pain only cases that resolve quickly. Table 9 is used for carbon monoxide and some wound indications.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "navy",
      },
    ],
    sources: [S.uhmsDcs, S.navy],
    ...META,
  },

  /* 11 ------------------------------------------------------------------ */
  {
    id: "environmental-11",
    topic: "environmental",
    title: "Collapse at a quarry dive site",
    stem:
      "A 27 year old woman on her fourth open water training dive in a flooded quarry panicked at 18 m and shot to the surface holding her breath. Within 2 minutes of surfacing she became confused and could not move her left arm. Paramedics report she now has left arm weakness, chest pain and crackling under the skin of her neck. HR 110, BP 128/76, RR 24, SpO2 93% on oxygen by mask.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO features that favour arterial gas embolism over decompression sickness.",
        accept: [
          { id: "onset", text: "Onset within about 10 minutes of surfacing", match: ["onset", "within minute", "immediate", "10 minute", "2 minute", "sudden"] },
          { id: "breathhold", text: "Rapid or breath holding ascent", match: ["breath hold", "breath holding", "rapid ascent", "panic", "uncontrolled ascent"] },
          { id: "barotrauma", text: "Signs of lung barotrauma such as subcutaneous emphysema", match: ["subcutaneous", "emphysema", "barotrauma", "chest pain", "pneumothorax"] },
          { id: "cerebral", text: "Stroke like cerebral signs", match: ["stroke", "cerebral", "hemiparesis", "arm weakness", "confusion"] },
          { id: "shallow", text: "Shallow short dive with little nitrogen load", match: ["shallow", "short dive", "nitrogen load", "depth"] },
        ],
        explanation:
          "Gas embolism follows pulmonary overpressure during ascent, often with breath holding. It presents within minutes with stroke like signs and can happen in shallow water. Decompression sickness depends on inert gas load and usually appears later.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        prompt: "List TWO investigations to obtain quickly before hyperbaric treatment.",
        accept: [
          { id: "cxr", text: "Chest X-ray for pneumothorax", match: ["chest x ray", "cxr", "xray", "chest film"] },
          { id: "us", text: "Lung ultrasound for pneumothorax", match: ["ultrasound", "pocus"] },
          { id: "ecg", text: "ECG for coronary air embolism", match: ["ecg"] },
          { id: "trop", text: "Troponin", match: ["troponin"] },
          { id: "glucose", text: "Glucose", match: ["glucose"] },
          { id: "ck", text: "CK", match: ["ck", "creatine kinase"] },
          { id: "neuro", text: "Documented baseline neurological examination", match: ["neuro exam", "neurological exam", "neurologic exam", "baseline"] },
        ],
        explanation:
          "An untreated pneumothorax is the key contraindication to hyperbaric oxygen because it can become a tension pneumothorax during decompression. The ECG looks for coronary gas. Tests must not delay recompression.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q3",
        kind: "single",
        update: "Chest X-ray shows a 15% left pneumothorax and pneumomediastinum.",
        prompt: "Which is the most appropriate next step? Select one.",
        options: [
          "Proceed to hyperbaric treatment without chest drainage",
          "Insert a chest tube, then proceed to hyperbaric treatment",
          "Cancel hyperbaric treatment because of the pneumothorax",
          "Observe for 6 hours and repeat the X-ray",
          "Needle decompression only if she deteriorates in the chamber",
        ],
        correct: 1,
        explanation:
          "Her neurological deficit needs recompression. The pneumothorax must be drained first, because gas trapped in the pleural space expands on ascent from treatment depth. Pneumomediastinum alone does not need drainage.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "uhms-dcs",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        prompt: "Beyond those already found, list TWO other manifestations of pulmonary barotrauma to look for.",
        accept: [
          { id: "pericard", text: "Pneumopericardium", match: ["pneumopericardium", "pericardial"] },
          { id: "hemoptysis", text: "Hemoptysis from alveolar hemorrhage", match: ["hemoptysis", "haemoptysis", "alveolar hemorrhage", "blood"] },
          { id: "voice", text: "Voice change or neck swelling", match: ["voice", "neck swelling", "dysphagia"] },
          { id: "tension", text: "Enlarging or tension pneumothorax", match: ["tension", "enlarging pneumothorax", "contralateral pneumothorax"] },
          { id: "peritoneum", text: "Pneumoperitoneum", match: ["pneumoperitoneum"] },
          { id: "coronary", text: "Coronary gas embolism with ischemia", match: ["coronary", "ischemia", "ischemic", "ischaemia", "myocardial"] },
        ],
        explanation:
          "Pulmonary overpressure can track air into the mediastinum, pericardium, neck and pleura. Alveolar hemorrhage causes hemoptysis. Air in the coronary arteries causes ischemia and arrhythmia.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "rosen",
      },
    ],
    sources: [S.uhmsDcs, S.rosen],
    ...META,
  },

  /* 12 ------------------------------------------------------------------ */
  {
    id: "environmental-12",
    topic: "environmental",
    title: "Vertigo after a morning dive",
    stem:
      "A 33 year old diver presents with severe vertigo, nausea, right ear pain, tinnitus and hearing loss. She had trouble equalizing her right ear on descent and forced repeated Valsalva manoeuvres. Symptoms began during descent at about 6 m. The dive was 35 minutes to a maximum of 14 m with a normal ascent. The right tympanic membrane is hemorrhagic. She has horizontal nystagmus. The rest of her neurological exam is normal.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 2,
        prompt: "List TWO features that favour inner ear barotrauma over inner ear decompression sickness.",
        accept: [
          { id: "descent", text: "Onset during descent rather than after ascent", match: ["descent", "onset", "timing", "before ascent"] },
          { id: "equalize", text: "Difficulty equalizing and forceful Valsalva", match: ["equalize", "equalizing", "equalization", "equalise", "equalising", "valsalva"] },
          { id: "tm", text: "Middle ear barotrauma with hemorrhagic tympanic membrane", match: ["tympanic", "tm", "middle ear", "eardrum", "ear drum"] },
          { id: "profile", text: "Shallow dive with low inert gas load", match: ["shallow", "profile", "depth", "gas load", "14 m"] },
          { id: "isolated", text: "No other neurological or systemic DCS symptoms", match: ["no other", "isolated", "normal neuro", "normal neurological", "normal neurologic"] },
          { id: "pain", text: "Ear pain", match: ["ear pain", "otalgia", "pain"] },
        ],
        explanation:
          "Inner ear barotrauma follows failed equalization and forceful Valsalva during descent. It can rupture the round or oval window. Inner ear decompression sickness follows ascent from deeper or longer dives, often with other symptoms.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "rosen",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate management? Select one.",
        options: [
          "Urgent hyperbaric recompression",
          "Urgent ENT assessment, head elevated rest, no straining and no diving",
          "Immediate myringotomy",
          "Gentamicin ear drops",
          "Discharge with meclizine and resume diving in 48 hours",
        ],
        correct: 1,
        explanation:
          "Inner ear barotrauma with a possible perilymph fistula needs ENT assessment, rest and avoidance of pressure changes. Recompression can worsen a fistula and is not indicated when barotrauma is clear. If inner ear decompression sickness cannot be excluded, discuss with a hyperbaric physician.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "rosen",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        prompt: "List TWO pieces of discharge advice.",
        accept: [
          { id: "nodive", text: "No diving until cleared by ENT", match: ["no diving", "avoid diving", "not dive", "no dive", "stop diving", "no further diving"] },
          { id: "nofly", text: "Avoid flying", match: ["avoid flying", "no flying", "not fly", "no flight", "avoid flight", "no air travel", "avoid air travel", "don fly"] },
          { id: "strain", text: "Avoid straining, nose blowing, heavy lifting and Valsalva", match: ["avoid straining", "no straining", "straining", "strain", "avoid valsalva", "no valsalva", "nose blowing", "blow", "lifting", "valsalva", "sneeze"] },
          { id: "return", text: "Return if hearing or vertigo worsens", match: ["return", "worsen"] },
          { id: "followup", text: "Formal audiogram and ENT follow up", match: ["audiogram", "audiology", "ent", "hearing test", "follow up"] },
          { id: "water", text: "Keep the ear dry", match: ["dry", "water"] },
        ],
        explanation:
          "Pressure changes and straining can enlarge a perilymph fistula. An audiogram documents the hearing loss. Diving should not resume until ENT clearance.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "rosen",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Her dive buddy is well but plans to fly home. He did two dives a day for five days without decompression stops. What is the minimum recommended surface interval before flying? Select one.",
        options: ["2 hours", "6 hours", "12 hours", "18 hours", "72 hours"],
        correct: 3,
        explanation:
          "Consensus guidance recommends at least 12 hours after a single no decompression dive and at least 18 hours after multiple dives per day or multiple days of diving. Dives needing decompression stops call for substantially longer. Flying too soon can provoke decompression sickness.",
        keyFeature: { topic: "environmental", n: 4 },
        source: "dan-flying",
      },
    ],
    sources: [S.rosen, S.danFlying],
    ...META,
  },

  /* 13 ------------------------------------------------------------------ */
  {
    id: "environmental-13",
    topic: "environmental",
    alsoTopics: ["burns"],
    title: "A power line worker",
    stem:
      "A 36 year old power line worker contacted a 14 400 volt line. He was thrown about 3 m from a ladder. He is awake and talking. HR 112, BP 132/80, RR 20, SpO2 97% on room air. He has a 2 cm charred wound on the right palm and a 3 cm wound on the left heel. He has no other visible burns.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 4,
        prompt: "List FOUR injuries or complications you must look for that may not be apparent from his skin.",
        accept: [
          { id: "cardiac", text: "Arrhythmia or myocardial injury", match: ["arrhythmia", "dysrhythmia", "cardiac", "myocardial", "myocarditis", "heart"] },
          { id: "rhabdo", text: "Rhabdomyolysis and myoglobinuric kidney injury", match: ["rhabdo", "rhabdomyolysis", "myoglobin", "kidney", "renal", "muscle"] },
          { id: "compartment", text: "Compartment syndrome", match: ["compartment"] },
          { id: "spine", text: "Spinal injury from the fall", match: ["spine", "spinal", "cervical", "c spine", "vertebra"] },
          { id: "fracture", text: "Fractures or dislocations from the fall or tetany, such as posterior shoulder dislocation", match: ["fracture", "dislocation", "shoulder"] },
          { id: "head", text: "Head injury", match: ["head"] },
          { id: "abdo", text: "Intra-abdominal visceral injury", match: ["abdomen", "abdominal", "visceral", "bowel", "solid organ"] },
          { id: "vascular", text: "Vascular thrombosis", match: ["vascular", "thrombosis", "arterial"] },
          { id: "nerve", text: "Peripheral nerve or spinal cord injury from current", match: ["nerve", "neuro", "neurological", "neurologic", "cord"] },
          { id: "deep", text: "Deep muscle necrosis along the current path", match: ["deep", "necrosis", "deep tissue"] },
          { id: "ear", text: "Tympanic membrane rupture", match: ["tympanic", "tm", "ear"] },
          { id: "eye", text: "Eye injury and later cataract", match: ["eye", "cataract"] },
        ],
        explanation:
          "High voltage current passes through deep tissue, so small skin wounds hide extensive muscle and nerve injury. The fall and tetanic contractions add fractures and spinal injury. Cardiac arrhythmia and rhabdomyolysis are the early threats.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "abls",
      },
      {
        id: "q2",
        kind: "short",
        required: 3,
        prompt: "List THREE investigations or monitoring you order now.",
        accept: [
          { id: "ecg", text: "12 lead ECG", match: ["ecg", "12 lead"] },
          { id: "monitor", text: "Continuous cardiac monitoring", match: ["monitor", "monitoring", "telemetry"] },
          { id: "ck", text: "CK", match: ["ck", "creatine kinase"] },
          { id: "urine", text: "Urinalysis for myoglobin", match: ["urine", "urinalysis", "myoglobin"] },
          { id: "lytes", text: "Electrolytes, potassium and creatinine", match: ["electrolyte", "potassium", "creatinine", "lytes"] },
          { id: "trop", text: "Troponin", match: ["troponin"] },
          { id: "imaging", text: "Trauma imaging of the spine and injured limbs", match: ["ct", "x ray", "xray", "imaging", "trauma series"] },
          { id: "cbc", text: "CBC and type and screen", match: ["cbc", "type and screen", "group and screen"] },
          { id: "gas", text: "Blood gas", match: ["gas"] },
          { id: "compartment", text: "Serial compartment checks or pressures", match: ["compartment"] },
        ],
        explanation:
          "High voltage injury needs an ECG and cardiac monitoring for at least 24 hours in most protocols. CK and urine myoglobin guide fluids. Imaging is guided by the fall and by the current path.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "abls",
      },
      {
        id: "q3",
        kind: "single",
        update: "His urine is dark red brown. CK is 42 000 U/L.",
        prompt: "Which is the most appropriate fluid target? Select one.",
        options: [
          "Parkland formula based on burn surface area only",
          "Urine output 0.5 mL/kg/h",
          "Urine output about 1 to 1.5 mL/kg/h, roughly 75 to 100 mL/h, until the urine clears",
          "Restrict fluids to prevent compartment syndrome",
          "Furosemide to keep urine output above 3 mL/kg/h",
        ],
        correct: 2,
        explanation:
          "Formulas based on burn surface area underestimate fluid needs in electrical injury because the damage is deep. With myoglobinuria, fluids are titrated to a higher urine output of about 75 to 100 mL/h in adults until the urine clears. Diuretics before adequate volume worsen kidney injury.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "abls",
      },
      {
        id: "q4",
        kind: "short",
        required: 2,
        update: "Six hours later his right forearm is tense and he has severe pain with passive finger extension.",
        prompt: "List TWO actions you take now.",
        accept: [
          { id: "surgery", text: "Urgent surgical consultation for fasciotomy", match: ["fasciotomy", "surgery", "surgeon", "surgical", "plastic", "decompress"] },
          { id: "pressure", text: "Measure compartment pressures if the diagnosis is uncertain", match: ["compartment pressure", "pressure"] },
          { id: "dressing", text: "Remove constrictive dressings", match: ["dressing", "constrict", "remove"] },
          { id: "position", text: "Keep the limb at heart level", match: ["heart level", "level of the heart", "avoid elevation", "not elevate", "no elevation", "don elevate"] },
          { id: "analgesia", text: "Analgesia", match: ["analgesia", "analgesic", "opioid", "pain"] },
          { id: "burn", text: "Transfer to a burn centre", match: ["burn centre", "burn center", "burn unit", "transfer"] },
          { id: "carpal", text: "Carpal tunnel release with the fasciotomy", match: ["carpal"] },
        ],
        unacceptable: [{ text: "Elevate the limb above the heart", match: ["elevate", "elevation", "elevated"] }],
        explanation:
          "Pain with passive stretch and a tense compartment are classic signs of compartment syndrome. Elevation lowers perfusion pressure, so the limb is kept at heart level. Electrical injury often needs fasciotomy and carpal tunnel release. Electrical injuries meet criteria for burn centre referral.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "abls",
      },
    ],
    sources: [S.abls],
    ...META,
  },

  /* 14 ------------------------------------------------------------------ */
  {
    id: "environmental-14",
    topic: "environmental",
    title: "Two household shocks",
    stem:
      "A 26 year old woman at 24 weeks gestation felt a jolt and tingling up her right arm when she touched a faulty kettle at home, 120 volts. She did not lose consciousness and feels well now. HR 84, BP 112/68. There is no visible burn. Her ECG is normal sinus rhythm. The fetal heart rate is 148 on Doppler.",
    questions: [
      {
        id: "q1",
        kind: "short",
        required: 3,
        prompt: "List THREE features that would make you monitor a patient after a low voltage electrical injury.",
        accept: [
          { id: "loc", text: "Loss of consciousness", match: ["loss of consciousness", "loc", "unconscious", "syncope"] },
          { id: "ecg", text: "Abnormal ECG or documented arrhythmia", match: ["ecg", "arrhythmia", "dysrhythmia"] },
          { id: "chest", text: "Chest pain or palpitations", match: ["chest pain", "palpitation"] },
          { id: "burn", text: "Significant burns or deep tissue injury", match: ["burn", "tissue"] },
          { id: "cardiac", text: "Known heart disease", match: ["heart disease", "cardiac history", "cardiac disease"] },
          { id: "preg", text: "Pregnancy beyond about 20 weeks", match: ["pregnant", "pregnancy", "fetal"] },
          { id: "hypoxia", text: "Hypoxia or abnormal vital signs", match: ["hypoxia", "hypoxic", "hypoxemia", "vital"] },
          { id: "neuro", text: "Neurological symptoms", match: ["neuro", "neurological", "neurologic", "weakness", "confusion"] },
          { id: "trauma", text: "Associated trauma", match: ["trauma", "fall"] },
        ],
        explanation:
          "Adults with low voltage exposure who are asymptomatic with a normal ECG can usually be discharged. Loss of consciousness, abnormal ECG, chest pain, significant burns and heart disease warrant monitoring. Pregnancy adds fetal risk because the amniotic fluid conducts current well.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q2",
        kind: "single",
        prompt: "Which is the most appropriate plan for her? Select one.",
        options: [
          "Discharge now, since the ECG is normal",
          "Admit to telemetry for 24 hours",
          "Obstetrical assessment with a period of fetal monitoring",
          "Serial troponins at 0 and 6 hours",
          "Urgent obstetric ultrasound only",
        ],
        correct: 2,
        explanation:
          "Case reports describe fetal death and injury even after minor maternal shocks. Current practice is obstetrical assessment with fetal heart rate monitoring for pregnancies beyond viability. Maternal cardiac monitoring is not needed with a normal ECG and no symptoms.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q3",
        kind: "short",
        required: 2,
        update: "Later, a 2 year old boy is brought in after biting an extension cord. He has a grey white burn at the left corner of the mouth. He is playful, with a normal ECG.",
        prompt: "List TWO complications to warn his parents about.",
        accept: [
          { id: "bleed", text: "Delayed labial artery bleeding when the eschar separates, about 5 to 14 days later", match: ["bleed", "labial artery", "hemorrhage", "haemorrhage", "eschar"] },
          { id: "scar", text: "Scarring and microstomia", match: ["scar", "microstomia", "contracture", "deformity"] },
          { id: "teeth", text: "Damage to developing teeth", match: ["teeth", "tooth", "dental"] },
          { id: "infection", text: "Infection", match: ["infection"] },
          { id: "feeding", text: "Feeding difficulty", match: ["feed", "feeding", "eating"] },
        ],
        explanation:
          "The key hazard of oral commissure burns is brisk labial artery bleeding when the eschar falls off. Parents must be taught to pinch the lip and return. Scarring can limit mouth opening and needs plastic surgery follow up.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "tintinalli",
      },
      {
        id: "q4",
        kind: "single",
        prompt: "Which is the most appropriate disposition for the boy? Select one.",
        options: [
          "Admit for 24 hours of cardiac monitoring",
          "Discharge with bleeding instructions and plastic surgery follow up",
          "Immediate debridement under general anesthesia",
          "CT head before discharge",
          "Admit until the eschar separates",
        ],
        correct: 1,
        explanation:
          "A well child with a household low voltage injury and a normal ECG does not need cardiac monitoring. Oral commissure burns are managed conservatively with close plastic surgery or dental follow up. Reliable caregivers who can apply pressure are essential.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "tintinalli",
      },
    ],
    sources: [S.tintinalli],
    ...META,
  },

  /* 15 ------------------------------------------------------------------ */
  {
    id: "environmental-15",
    topic: "environmental",
    alsoTopics: ["ems"],
    title: "A thunderstorm at a campground",
    stem:
      "Paramedics patch to your rural emergency department from a provincial park campground. A sudden thunderstorm struck a group sheltering under a tree. Four people are down. The paramedic describes them. Patient A is moaning and cannot move his legs. Patient B is apneic and pulseless. Patient C is confused with a fern like red pattern on her chest. Patient D is walking and cannot hear.",
    questions: [
      {
        id: "q1",
        kind: "single",
        prompt: "Which patient should receive resuscitation first? Select one.",
        options: ["Patient A", "Patient B", "Patient C", "Patient D", "None, all should be moved to shelter first"],
        correct: 1,
        explanation:
          "Lightning strike uses reverse triage. Victims who show signs of life usually survive. The apparently dead often have a primary respiratory arrest after the heart restarts, and they can be saved with prompt ventilation and CPR.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "wms-lightning",
      },
      {
        id: "q2",
        kind: "short",
        required: 2,
        update: "Patient A arrives. His legs are mottled, cool and pulseless with no movement. His blood pressure is 128/76.",
        prompt: "List TWO elements of your assessment or management of his legs.",
        accept: [
          { id: "kerauno", text: "Recognize likely keraunoparalysis, which is usually transient", match: ["keraunoparalysis", "transient", "vasospasm", "autonomic"] },
          { id: "spine", text: "Spinal motion restriction and imaging to exclude spinal injury", match: ["spine", "spinal", "collar", "ct", "mri"] },
          { id: "reassess", text: "Serial reassessment of pulses and neurological function", match: ["reassess", "serial", "repeat", "pulse"] },
          { id: "vascular", text: "Vascular assessment if pulses do not return within hours", match: ["vascular", "doppler", "angiography", "angiogram"] },
          { id: "compartment", text: "Watch for compartment syndrome", match: ["compartment"] },
        ],
        explanation:
          "Keraunoparalysis is transient paralysis with cool mottled limbs from autonomic vasospasm. It usually resolves within hours. Persistent deficits call for spinal imaging and vascular assessment, since victims are often thrown.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "wms-lightning",
      },
      {
        id: "q3",
        kind: "short",
        required: 4,
        prompt: "List FOUR injuries or complications to look for in lightning victims.",
        accept: [
          { id: "tm", text: "Tympanic membrane rupture", match: ["tympanic", "tm", "eardrum", "ear drum", "hearing"] },
          { id: "eye", text: "Eye injury including later cataracts", match: ["eye", "cataract"] },
          { id: "cardiac", text: "Arrhythmia or myocardial injury", match: ["arrhythmia", "cardiac", "myocardial", "myocarditis", "dysrhythmia", "ecg"] },
          { id: "blunt", text: "Blunt trauma from being thrown, including spine and head", match: ["blunt", "trauma", "fracture", "head injury", "spine", "spinal"] },
          { id: "burn", text: "Burns, including feathering Lichtenberg figures and contact burns", match: ["burn", "lichtenberg", "feathering"] },
          { id: "neuro", text: "Confusion, amnesia, seizures or intracranial injury", match: ["confusion", "amnesia", "seizure", "intracranial", "neuro", "neurological", "neurologic", "brain"] },
          { id: "kerauno", text: "Keraunoparalysis", match: ["keraunoparalysis", "paralysis"] },
          { id: "preg", text: "Fetal injury in pregnancy", match: ["fetal", "pregnant", "pregnancy"] },
          { id: "chronic", text: "Chronic pain and neuropsychological symptoms", match: ["chronic", "psychological", "ptsd", "memory"] },
        ],
        explanation:
          "Lightning is a very brief, high energy current that mostly flashes over the skin. Deep burns and rhabdomyolysis are less common than with high voltage injury. Ear, eye, cardiac and neurological injuries are common, and victims may be thrown.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "wms-lightning",
      },
      {
        id: "q4",
        kind: "single",
        update: "Patient B has return of spontaneous circulation after 6 minutes of CPR. His pupils are fixed and dilated.",
        prompt: "Which is the most appropriate approach? Select one.",
        options: [
          "Stop resuscitation, since fixed dilated pupils indicate brain death",
          "Continue full resuscitation, since fixed dilated pupils are not reliable after lightning",
          "Limit care to comfort measures",
          "Wait for pupils to react before intubation",
          "Give atropine to reverse the pupil findings",
        ],
        correct: 1,
        explanation:
          "Autonomic disturbance after lightning can cause fixed dilated pupils in patients who recover fully. Pupils should not be used to stop resuscitation or withdraw care. Full post-arrest care is indicated.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "wms-lightning",
      },
      {
        id: "q5",
        kind: "short",
        required: 2,
        update: "Patient D, who is walking, has ruptured tympanic membranes and feels well otherwise. His ECG is normal.",
        prompt: "List TWO elements of his discharge plan.",
        accept: [
          { id: "ent", text: "ENT or audiology follow up for the tympanic membranes and hearing", match: ["ent", "audiology", "audiogram", "hearing", "otolaryngology"] },
          { id: "eye", text: "Eye examination and follow up because cataracts can develop later", match: ["eye", "ophthalmology", "cataract", "vision"] },
          { id: "ear", text: "Keep the ears dry until healed", match: ["dry", "water"] },
          { id: "neuro", text: "Watch for delayed neurological or psychological symptoms and arrange follow up", match: ["neurological", "neuro", "psychological", "memory", "ptsd", "family physician", "follow up"] },
          { id: "return", text: "Return for chest pain, palpitations, weakness or confusion", match: ["return", "chest pain", "palpitation"] },
        ],
        explanation:
          "A walking lightning victim with a normal ECG can usually go home. Tympanic membrane rupture is common and most heal with dry ear precautions. Cataracts and neuropsychological problems may appear weeks to months later, so follow up matters.",
        keyFeature: { topic: "environmental", n: 5 },
        source: "wms-lightning",
      },
    ],
    sources: [S.wmsLightning],
    ...META,
  },
];
